# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 4 Trig functions/4.7 Miscellaneous/4.7.2 trig^m (a trig+b trig)^n.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '4 Trig functions/4.7 Miscellaneous/4.7.2 trig^m (a trig+b trig)^n.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, c, d, m, n = symbols('a b c d m n')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=(a*cos(x) + b*sin(x))*sin(x)**3,
        variable=x,
        num_steps=7,
        integral=a*sin(x)**4/4 + 3*b*x/8 - b*sin(x)**3*cos(x)/4 - 3*b*sin(x)*cos(x)/8,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x) + b*sin(x))*sin(x)**2,
        variable=x,
        num_steps=6,
        integral=a*sin(x)**3/3 + b*cos(x)**3/3 - b*cos(x),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x) + b*sin(x))*sin(x),
        variable=x,
        num_steps=6,
        integral=a*sin(x)**2/2 + b*x/2 - b*sin(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=a*cos(x) + b*sin(x),
        variable=x,
        num_steps=3,
        integral=a*sin(x) - b*cos(x),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x) + b*sin(x))*csc(x),
        variable=x,
        num_steps=3,
        integral=a*log(sin(x)) + b*x,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x) + b*sin(x))*csc(x)**2,
        variable=x,
        num_steps=5,
        integral=-a*csc(x) - b*atanh(cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x) + b*sin(x))*csc(x)**3,
        variable=x,
        num_steps=6,
        integral=-a*csc(x)**2/2 - b*cot(x),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=5,
        integral=-a**3*log(a*cos(x) + b*sin(x))/(a**2 + b**2)**2 + a**2*b*x/(a**2 + b**2)**2 - a*sin(x)**2/(2*a**2 + 2*b**2) + b*x/(2*a**2 + 2*b**2) - b*sin(x)*cos(x)/(2*a**2 + 2*b**2),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=4,
        integral=-a**2*atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/(a**2 + b**2)**(sympy.S(3)/2) - a*sin(x)/(a**2 + b**2) - b*cos(x)/(a**2 + b**2),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=2,
        integral=-a*log(a*cos(x) + b*sin(x))/(a**2 + b**2) + b*x/(a**2 + b**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=2,
        integral=-atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/sqrt(a**2 + b**2),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=3,
        integral=-log(a*cos(x) + b*sin(x))/a + log(sin(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**2/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=4,
        integral=-csc(x)/a + b*atanh(cos(x))/a**2 - sqrt(a**2 + b**2)*atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/a**2,
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**3/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=6,
        integral=-csc(x)**2/(2*a) + b*cot(x)/a**2 - (a**2 + b**2)*log(a*cos(x) + b*sin(x))/a**3 + (a**2 + b**2)*log(sin(x))/a**3,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3/(a*cos(x) + b*sin(x))**2,
        variable=x,
        num_steps=-19,
        integral=6*a**2*b*atanh((a*tan(x/2) - b)/sqrt(a**2 + b**2))/(a**2 + b**2)**(sympy.S(5)/2) + (3*a*(a**2 - b**2) + a*(a**2 + b**2)*cos(2*x) - b*(a**2 + b**2)*sin(2*x))/(2*(a**2 + b**2)**2*(a*cos(x) + b*sin(x))),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2/(a*cos(x) + b*sin(x))**2,
        variable=x,
        num_steps=4,
        integral=-2*a*b*log(a*cos(x) + b*sin(x))/(a**2 + b**2)**2 + a/((a**2 + b**2)*(a*cot(x) + b)) - x*(a**2 - b**2)/(a**2 + b**2)**2,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/(a*cos(x) + b*sin(x))**2,
        variable=x,
        num_steps=3,
        integral=a/((a**2 + b**2)*(a*cos(x) + b*sin(x))) - b*atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/(a**2 + b**2)**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x) + b*sin(x))**(-2),
        variable=x,
        num_steps=1,
        integral=sin(x)/(a*(a*cos(x) + b*sin(x))),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)/(a*cos(x) + b*sin(x))**2,
        variable=x,
        num_steps=4,
        integral=1/(a*(a*cos(x) + b*sin(x))) + b*atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/(a**2*sqrt(a**2 + b**2)) - atanh(cos(x))/a**2,
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**2/(a*cos(x) + b*sin(x))**2,
        variable=x,
        num_steps=3,
        integral=-(1/b + b/a**2)/(a + b*tan(x)) - cot(x)/a**2 + 2*b*log(a + b*tan(x))/a**3 - 2*b*log(tan(x))/a**3,
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**3/(a*cos(x) + b*sin(x))**2,
        variable=x,
        num_steps=11,
        integral=-cot(x)*csc(x)/(2*a**2) - atanh(cos(x))/(2*a**2) + 2*b*csc(x)/a**3 + (a**2 + b**2)/(a**3*(a*cos(x) + b*sin(x))) - 2*b**2*atanh(cos(x))/a**4 + 3*b*sqrt(a**2 + b**2)*atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/a**4 - (a**2 + b**2)*atanh(cos(x))/a**4,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3/(a*cos(x) + b*sin(x))**3,
        variable=x,
        num_steps=5,
        integral=2*a*b/((a**2 + b**2)**2*(a*cot(x) + b)) + a*(a**2 - 3*b**2)*log(a*cos(x) + b*sin(x))/(a**2 + b**2)**3 + a/((2*a**2 + 2*b**2)*(a*cot(x) + b)**2) - b*x*(3*a**2 - b**2)/(a**2 + b**2)**3,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2/(a*cos(x) + b*sin(x))**3,
        variable=x,
        num_steps=-13,
        integral=a*(3*a*b*cos(x) + (a**2 + 4*b**2)*sin(x))/(2*(a**2 + b**2)**2*(a*cos(x) + b*sin(x))**2) - (a**2 - 2*b**2)*atanh((a*tan(x/2) - b)/sqrt(a**2 + b**2))/(a**2 + b**2)**(sympy.S(5)/2),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x) + b*sin(x))**(-3),
        variable=x,
        num_steps=3,
        integral=-(-a*sin(x) + b*cos(x))/((2*a**2 + 2*b**2)*(a*cos(x) + b*sin(x))**2) - atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/(2*(a**2 + b**2)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)/(a*cos(x) + b*sin(x))**3,
        variable=x,
        num_steps=3,
        integral=(-1/b**2 + a**(-2))/(a + b*tan(x)) + (a/b**2 + 1/a)/(2*(a + b*tan(x))**2) - log(a + b*tan(x))/a**3 + log(tan(x))/a**3,
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**2/(a*cos(x) + b*sin(x))**3,
        variable=x,
        num_steps=12,
        integral=-(-a*sin(x) + b*cos(x))/(2*a**2*(a*cos(x) + b*sin(x))**2) - atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/(2*a**2*sqrt(a**2 + b**2)) - 2*b/(a**3*(a*cos(x) + b*sin(x))) - csc(x)/a**3 - 2*b**2*atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/(a**4*sqrt(a**2 + b**2)) + 3*b*atanh(cos(x))/a**4 - sqrt(a**2 + b**2)*atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/a**4,
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**3/(a*cos(x) + b*sin(x))**3,
        variable=x,
        num_steps=3,
        integral=-cot(x)**2/(2*a**3) + (a**2 + b**2)**2/(2*a**3*b**2*(a + b*tan(x))**2) + 3*b*cot(x)/a**4 - (a**2 - 3*b**2)*(a**2 + b**2)/(a**4*b**2*(a + b*tan(x))) - (2*a**2 + 6*b**2)*log(a + b*tan(x))/a**5 + (2*a**2 + 6*b**2)*log(tan(x))/a**5,
    ),
    RubiTestSuiteCase(
        integrand=(I*a*sin(c + d*x) + a*cos(c + d*x))**n/sin(c + d*x)**n,
        variable=x,
        num_steps=1,
        integral=-I*(I*a*sin(c + d*x) + a*cos(c + d*x))**n*hyper((1, n), (n + 1,), -I*(cot(c + d*x) + I)/2)/(2*d*n*sin(c + d*x)**n),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))*cos(c + d*x)**5,
        variable=x,
        num_steps=8,
        integral=5*a*x/16 + a*sin(c + d*x)*cos(c + d*x)**5/(6*d) + 5*a*sin(c + d*x)*cos(c + d*x)**3/(24*d) + 5*a*sin(c + d*x)*cos(c + d*x)/(16*d) - b*cos(c + d*x)**6/(6*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))*cos(c + d*x)**4,
        variable=x,
        num_steps=6,
        integral=a*sin(c + d*x)**5/(5*d) - 2*a*sin(c + d*x)**3/(3*d) + a*sin(c + d*x)/d - b*cos(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))*cos(c + d*x)**3,
        variable=x,
        num_steps=7,
        integral=3*a*x/8 + a*sin(c + d*x)*cos(c + d*x)**3/(4*d) + 3*a*sin(c + d*x)*cos(c + d*x)/(8*d) - b*cos(c + d*x)**4/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))*cos(c + d*x)**2,
        variable=x,
        num_steps=6,
        integral=-a*sin(c + d*x)**3/(3*d) + a*sin(c + d*x)/d - b*cos(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))*cos(c + d*x),
        variable=x,
        num_steps=6,
        integral=a*x/2 + a*sin(c + d*x)*cos(c + d*x)/(2*d) + b*sin(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=a*cos(c + d*x) + b*sin(c + d*x),
        variable=x,
        num_steps=3,
        integral=a*sin(c + d*x)/d - b*cos(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))*sec(c + d*x),
        variable=x,
        num_steps=3,
        integral=a*x - b*log(cos(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))*sec(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=a*atanh(sin(c + d*x))/d + b*sec(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))*sec(c + d*x)**3,
        variable=x,
        num_steps=6,
        integral=a*tan(c + d*x)/d + b*sec(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))*sec(c + d*x)**4,
        variable=x,
        num_steps=6,
        integral=a*tan(c + d*x)*sec(c + d*x)/(2*d) + a*atanh(sin(c + d*x))/(2*d) + b*sec(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))*sec(c + d*x)**5,
        variable=x,
        num_steps=6,
        integral=a*tan(c + d*x)**3/(3*d) + a*tan(c + d*x)/d + b*sec(c + d*x)**4/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))*sec(c + d*x)**6,
        variable=x,
        num_steps=7,
        integral=a*tan(c + d*x)*sec(c + d*x)**3/(4*d) + 3*a*tan(c + d*x)*sec(c + d*x)/(8*d) + 3*a*atanh(sin(c + d*x))/(8*d) + b*sec(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))*sec(c + d*x)**7,
        variable=x,
        num_steps=6,
        integral=a*tan(c + d*x)**5/(5*d) + 2*a*tan(c + d*x)**3/(3*d) + a*tan(c + d*x)/d + b*sec(c + d*x)**6/(6*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**2*cos(c + d*x)**5,
        variable=x,
        num_steps=9,
        integral=-a**2*sin(c + d*x)**7/(7*d) + 3*a**2*sin(c + d*x)**5/(5*d) - a**2*sin(c + d*x)**3/d + a**2*sin(c + d*x)/d - 2*a*b*cos(c + d*x)**7/(7*d) + b**2*sin(c + d*x)**7/(7*d) - 2*b**2*sin(c + d*x)**5/(5*d) + b**2*sin(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**2*cos(c + d*x)**4,
        variable=x,
        num_steps=12,
        integral=5*a**2*x/16 + a**2*sin(c + d*x)*cos(c + d*x)**5/(6*d) + 5*a**2*sin(c + d*x)*cos(c + d*x)**3/(24*d) + 5*a**2*sin(c + d*x)*cos(c + d*x)/(16*d) - a*b*cos(c + d*x)**6/(3*d) + b**2*x/16 - b**2*sin(c + d*x)*cos(c + d*x)**5/(6*d) + b**2*sin(c + d*x)*cos(c + d*x)**3/(24*d) + b**2*sin(c + d*x)*cos(c + d*x)/(16*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**2*cos(c + d*x)**3,
        variable=x,
        num_steps=9,
        integral=a**2*sin(c + d*x)**5/(5*d) - 2*a**2*sin(c + d*x)**3/(3*d) + a**2*sin(c + d*x)/d - 2*a*b*cos(c + d*x)**5/(5*d) - b**2*sin(c + d*x)**5/(5*d) + b**2*sin(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**2*cos(c + d*x)**2,
        variable=x,
        num_steps=10,
        integral=3*a**2*x/8 + a**2*sin(c + d*x)*cos(c + d*x)**3/(4*d) + 3*a**2*sin(c + d*x)*cos(c + d*x)/(8*d) - a*b*cos(c + d*x)**4/(2*d) + b**2*x/8 - b**2*sin(c + d*x)*cos(c + d*x)**3/(4*d) + b**2*sin(c + d*x)*cos(c + d*x)/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**2*cos(c + d*x),
        variable=x,
        num_steps=8,
        integral=-a**2*sin(c + d*x)**3/(3*d) + a**2*sin(c + d*x)/d - 2*a*b*cos(c + d*x)**3/(3*d) + b**2*sin(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**2,
        variable=x,
        num_steps=2,
        integral=x*(a**2/2 + b**2/2) - (-a*sin(c + d*x) + b*cos(c + d*x))*(a*cos(c + d*x) + b*sin(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**2*sec(c + d*x),
        variable=x,
        num_steps=7,
        integral=a**2*sin(c + d*x)/d - 2*a*b*cos(c + d*x)/d - b**2*sin(c + d*x)/d + b**2*atanh(sin(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**2*sec(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=-2*a*b*log(cos(c + d*x))/d + b**2*tan(c + d*x)/d + x*(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**2*sec(c + d*x)**3,
        variable=x,
        num_steps=7,
        integral=a**2*atanh(sin(c + d*x))/d + 2*a*b*sec(c + d*x)/d + b**2*tan(c + d*x)*sec(c + d*x)/(2*d) - b**2*atanh(sin(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**2*sec(c + d*x)**4,
        variable=x,
        num_steps=2,
        integral=(a*cot(c + d*x) + b)**3*tan(c + d*x)**3/(3*b*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**2*sec(c + d*x)**5,
        variable=x,
        num_steps=9,
        integral=a**2*tan(c + d*x)*sec(c + d*x)/(2*d) + a**2*atanh(sin(c + d*x))/(2*d) + 2*a*b*sec(c + d*x)**3/(3*d) + b**2*tan(c + d*x)*sec(c + d*x)**3/(4*d) - b**2*tan(c + d*x)*sec(c + d*x)/(8*d) - b**2*atanh(sin(c + d*x))/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**2*sec(c + d*x)**6,
        variable=x,
        num_steps=3,
        integral=a**2*tan(c + d*x)/d + a*b*tan(c + d*x)**4/(2*d) + a*b*tan(c + d*x)**2/d + b**2*tan(c + d*x)**5/(5*d) + (a**2 + b**2)*tan(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**2*sec(c + d*x)**7,
        variable=x,
        num_steps=11,
        integral=a**2*tan(c + d*x)*sec(c + d*x)**3/(4*d) + 3*a**2*tan(c + d*x)*sec(c + d*x)/(8*d) + 3*a**2*atanh(sin(c + d*x))/(8*d) + 2*a*b*sec(c + d*x)**5/(5*d) + b**2*tan(c + d*x)*sec(c + d*x)**5/(6*d) - b**2*tan(c + d*x)*sec(c + d*x)**3/(24*d) - b**2*tan(c + d*x)*sec(c + d*x)/(16*d) - b**2*atanh(sin(c + d*x))/(16*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**2*sec(c + d*x)**8,
        variable=x,
        num_steps=3,
        integral=a**2*tan(c + d*x)/d + a*b*tan(c + d*x)**6/(3*d) + a*b*tan(c + d*x)**4/d + a*b*tan(c + d*x)**2/d + b**2*tan(c + d*x)**7/(7*d) + (a**2 + 2*b**2)*tan(c + d*x)**5/(5*d) + (2*a**2 + b**2)*tan(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*cos(c + d*x)**5,
        variable=x,
        num_steps=17,
        integral=35*a**3*x/128 + a**3*sin(c + d*x)*cos(c + d*x)**7/(8*d) + 7*a**3*sin(c + d*x)*cos(c + d*x)**5/(48*d) + 35*a**3*sin(c + d*x)*cos(c + d*x)**3/(192*d) + 35*a**3*sin(c + d*x)*cos(c + d*x)/(128*d) - 3*a**2*b*cos(c + d*x)**8/(8*d) + 15*a*b**2*x/128 - 3*a*b**2*sin(c + d*x)*cos(c + d*x)**7/(8*d) + a*b**2*sin(c + d*x)*cos(c + d*x)**5/(16*d) + 5*a*b**2*sin(c + d*x)*cos(c + d*x)**3/(64*d) + 15*a*b**2*sin(c + d*x)*cos(c + d*x)/(128*d) + b**3*cos(c + d*x)**8/(8*d) - b**3*cos(c + d*x)**6/(6*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*cos(c + d*x)**4,
        variable=x,
        num_steps=12,
        integral=-a**3*sin(c + d*x)**7/(7*d) + 3*a**3*sin(c + d*x)**5/(5*d) - a**3*sin(c + d*x)**3/d + a**3*sin(c + d*x)/d - 3*a**2*b*cos(c + d*x)**7/(7*d) + 3*a*b**2*sin(c + d*x)**7/(7*d) - 6*a*b**2*sin(c + d*x)**5/(5*d) + a*b**2*sin(c + d*x)**3/d + b**3*cos(c + d*x)**7/(7*d) - b**3*cos(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*cos(c + d*x)**3,
        variable=x,
        num_steps=15,
        integral=5*a**3*x/16 + a**3*sin(c + d*x)*cos(c + d*x)**5/(6*d) + 5*a**3*sin(c + d*x)*cos(c + d*x)**3/(24*d) + 5*a**3*sin(c + d*x)*cos(c + d*x)/(16*d) - a**2*b*cos(c + d*x)**6/(2*d) + 3*a*b**2*x/16 - a*b**2*sin(c + d*x)*cos(c + d*x)**5/(2*d) + a*b**2*sin(c + d*x)*cos(c + d*x)**3/(8*d) + 3*a*b**2*sin(c + d*x)*cos(c + d*x)/(16*d) - b**3*sin(c + d*x)**6/(6*d) + b**3*sin(c + d*x)**4/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*cos(c + d*x)**2,
        variable=x,
        num_steps=12,
        integral=a**3*sin(c + d*x)**5/(5*d) - 2*a**3*sin(c + d*x)**3/(3*d) + a**3*sin(c + d*x)/d - 3*a**2*b*cos(c + d*x)**5/(5*d) - 3*a*b**2*sin(c + d*x)**5/(5*d) + a*b**2*sin(c + d*x)**3/d + b**3*cos(c + d*x)**5/(5*d) - b**3*cos(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*cos(c + d*x),
        variable=x,
        num_steps=4,
        integral=3*a*x*(a**2 + b**2)/8 + 3*a*(a - b*cot(c + d*x))*(a*cot(c + d*x) + b)*sin(c + d*x)**2/(8*d) + (a*cot(c + d*x) + b)**3*sin(c + d*x)**4/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3,
        variable=x,
        num_steps=2,
        integral=-(a**2 + b**2)*(-a*sin(c + d*x) + b*cos(c + d*x))/d + (-a*sin(c + d*x) + b*cos(c + d*x))**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*sec(c + d*x),
        variable=x,
        num_steps=7,
        integral=a*x*(a**2 + 3*b**2)/2 - b**3*log(sin(c + d*x))/d + b**3*log(tan(c + d*x))/d + (a*(a**2 - 3*b**2)*cot(c + d*x) + b*(3*a**2 - b**2))*sin(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*sec(c + d*x)**2,
        variable=x,
        num_steps=10,
        integral=a**3*sin(c + d*x)/d - 3*a**2*b*cos(c + d*x)/d - 3*a*b**2*sin(c + d*x)/d + 3*a*b**2*atanh(sin(c + d*x))/d + b**3*cos(c + d*x)/d + b**3*sec(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*sec(c + d*x)**3,
        variable=x,
        num_steps=4,
        integral=2*a*b**2*tan(c + d*x)/d + a*x*(a**2 - 3*b**2) + b*(a + b*tan(c + d*x))**2/(2*d) - b*(3*a**2 - b**2)*log(cos(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*sec(c + d*x)**4,
        variable=x,
        num_steps=9,
        integral=a**3*atanh(sin(c + d*x))/d + 3*a**2*b*sec(c + d*x)/d + 3*a*b**2*tan(c + d*x)*sec(c + d*x)/(2*d) - 3*a*b**2*atanh(sin(c + d*x))/(2*d) + b**3*sec(c + d*x)**3/(3*d) - b**3*sec(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*sec(c + d*x)**5,
        variable=x,
        num_steps=2,
        integral=(a*cot(c + d*x) + b)**4*tan(c + d*x)**4/(4*b*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*sec(c + d*x)**6,
        variable=x,
        num_steps=12,
        integral=a**3*tan(c + d*x)*sec(c + d*x)/(2*d) + a**3*atanh(sin(c + d*x))/(2*d) + a**2*b*sec(c + d*x)**3/d + 3*a*b**2*tan(c + d*x)*sec(c + d*x)**3/(4*d) - 3*a*b**2*tan(c + d*x)*sec(c + d*x)/(8*d) - 3*a*b**2*atanh(sin(c + d*x))/(8*d) + b**3*sec(c + d*x)**5/(5*d) - b**3*sec(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*sec(c + d*x)**7,
        variable=x,
        num_steps=3,
        integral=a**3*tan(c + d*x)/d + 3*a**2*b*tan(c + d*x)**2/(2*d) + 3*a*b**2*tan(c + d*x)**5/(5*d) + a*(a**2 + 3*b**2)*tan(c + d*x)**3/(3*d) + b**3*tan(c + d*x)**6/(6*d) + b*(3*a**2 + b**2)*tan(c + d*x)**4/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*sec(c + d*x)**8,
        variable=x,
        num_steps=14,
        integral=a**3*tan(c + d*x)*sec(c + d*x)**3/(4*d) + 3*a**3*tan(c + d*x)*sec(c + d*x)/(8*d) + 3*a**3*atanh(sin(c + d*x))/(8*d) + 3*a**2*b*sec(c + d*x)**5/(5*d) + a*b**2*tan(c + d*x)*sec(c + d*x)**5/(2*d) - a*b**2*tan(c + d*x)*sec(c + d*x)**3/(8*d) - 3*a*b**2*tan(c + d*x)*sec(c + d*x)/(16*d) - 3*a*b**2*atanh(sin(c + d*x))/(16*d) + b**3*sec(c + d*x)**7/(7*d) - b**3*sec(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*sec(c + d*x)**9,
        variable=x,
        num_steps=3,
        integral=a**3*tan(c + d*x)/d + 3*a**2*b*tan(c + d*x)**2/(2*d) + 3*a*b**2*tan(c + d*x)**7/(7*d) + a*(a**2 + 6*b**2)*tan(c + d*x)**5/(5*d) + a*(2*a**2 + 3*b**2)*tan(c + d*x)**3/(3*d) + b**3*tan(c + d*x)**8/(8*d) + b*(3*a**2 + 2*b**2)*tan(c + d*x)**6/(6*d) + b*(6*a**2 + b**2)*tan(c + d*x)**4/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*sec(c + d*x)**10,
        variable=x,
        num_steps=16,
        integral=a**3*tan(c + d*x)*sec(c + d*x)**5/(6*d) + 5*a**3*tan(c + d*x)*sec(c + d*x)**3/(24*d) + 5*a**3*tan(c + d*x)*sec(c + d*x)/(16*d) + 5*a**3*atanh(sin(c + d*x))/(16*d) + 3*a**2*b*sec(c + d*x)**7/(7*d) + 3*a*b**2*tan(c + d*x)*sec(c + d*x)**7/(8*d) - a*b**2*tan(c + d*x)*sec(c + d*x)**5/(16*d) - 5*a*b**2*tan(c + d*x)*sec(c + d*x)**3/(64*d) - 15*a*b**2*tan(c + d*x)*sec(c + d*x)/(128*d) - 15*a*b**2*atanh(sin(c + d*x))/(128*d) + b**3*sec(c + d*x)**9/(9*d) - b**3*sec(c + d*x)**7/(7*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**3*sec(c + d*x)**11,
        variable=x,
        num_steps=3,
        integral=a**3*tan(c + d*x)/d + 3*a**2*b*tan(c + d*x)**2/(2*d) + a*b**2*tan(c + d*x)**9/(3*d) + a*(a**2 + b**2)*tan(c + d*x)**3/d + 3*a*(a**2 + 3*b**2)*tan(c + d*x)**5/(5*d) + a*(a**2 + 9*b**2)*tan(c + d*x)**7/(7*d) + b**3*tan(c + d*x)**10/(10*d) + 3*b*(a**2 + b**2)*tan(c + d*x)**8/(8*d) + b*(3*a**2 + b**2)*tan(c + d*x)**6/(2*d) + b*(9*a**2 + b**2)*tan(c + d*x)**4/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*cos(c + d*x)**5,
        variable=x,
        num_steps=15,
        integral=a**4*sin(c + d*x)**9/(9*d) - 4*a**4*sin(c + d*x)**7/(7*d) + 6*a**4*sin(c + d*x)**5/(5*d) - 4*a**4*sin(c + d*x)**3/(3*d) + a**4*sin(c + d*x)/d - 4*a**3*b*cos(c + d*x)**9/(9*d) - 2*a**2*b**2*sin(c + d*x)**9/(3*d) + 18*a**2*b**2*sin(c + d*x)**7/(7*d) - 18*a**2*b**2*sin(c + d*x)**5/(5*d) + 2*a**2*b**2*sin(c + d*x)**3/d + 4*a*b**3*cos(c + d*x)**9/(9*d) - 4*a*b**3*cos(c + d*x)**7/(7*d) + b**4*sin(c + d*x)**9/(9*d) - 2*b**4*sin(c + d*x)**7/(7*d) + b**4*sin(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*cos(c + d*x)**4,
        variable=x,
        num_steps=22,
        integral=35*a**4*x/128 + a**4*sin(c + d*x)*cos(c + d*x)**7/(8*d) + 7*a**4*sin(c + d*x)*cos(c + d*x)**5/(48*d) + 35*a**4*sin(c + d*x)*cos(c + d*x)**3/(192*d) + 35*a**4*sin(c + d*x)*cos(c + d*x)/(128*d) - a**3*b*cos(c + d*x)**8/(2*d) + 15*a**2*b**2*x/64 - 3*a**2*b**2*sin(c + d*x)*cos(c + d*x)**7/(4*d) + a**2*b**2*sin(c + d*x)*cos(c + d*x)**5/(8*d) + 5*a**2*b**2*sin(c + d*x)*cos(c + d*x)**3/(32*d) + 15*a**2*b**2*sin(c + d*x)*cos(c + d*x)/(64*d) + a*b**3*cos(c + d*x)**8/(2*d) - 2*a*b**3*cos(c + d*x)**6/(3*d) + 3*b**4*x/128 - b**4*sin(c + d*x)**3*cos(c + d*x)**5/(8*d) - b**4*sin(c + d*x)*cos(c + d*x)**5/(16*d) + b**4*sin(c + d*x)*cos(c + d*x)**3/(64*d) + 3*b**4*sin(c + d*x)*cos(c + d*x)/(128*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*cos(c + d*x)**3,
        variable=x,
        num_steps=15,
        integral=-a**4*sin(c + d*x)**7/(7*d) + 3*a**4*sin(c + d*x)**5/(5*d) - a**4*sin(c + d*x)**3/d + a**4*sin(c + d*x)/d - 4*a**3*b*cos(c + d*x)**7/(7*d) + 6*a**2*b**2*sin(c + d*x)**7/(7*d) - 12*a**2*b**2*sin(c + d*x)**5/(5*d) + 2*a**2*b**2*sin(c + d*x)**3/d + 4*a*b**3*cos(c + d*x)**7/(7*d) - 4*a*b**3*cos(c + d*x)**5/(5*d) - b**4*sin(c + d*x)**7/(7*d) + b**4*sin(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*cos(c + d*x)**2,
        variable=x,
        num_steps=19,
        integral=5*a**4*x/16 + a**4*sin(c + d*x)*cos(c + d*x)**5/(6*d) + 5*a**4*sin(c + d*x)*cos(c + d*x)**3/(24*d) + 5*a**4*sin(c + d*x)*cos(c + d*x)/(16*d) - 2*a**3*b*cos(c + d*x)**6/(3*d) + 3*a**2*b**2*x/8 - a**2*b**2*sin(c + d*x)*cos(c + d*x)**5/d + a**2*b**2*sin(c + d*x)*cos(c + d*x)**3/(4*d) + 3*a**2*b**2*sin(c + d*x)*cos(c + d*x)/(8*d) - 2*a*b**3*sin(c + d*x)**6/(3*d) + a*b**3*sin(c + d*x)**4/d + b**4*x/16 - b**4*sin(c + d*x)**3*cos(c + d*x)**3/(6*d) - b**4*sin(c + d*x)*cos(c + d*x)**3/(8*d) + b**4*sin(c + d*x)*cos(c + d*x)/(16*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*cos(c + d*x),
        variable=x,
        num_steps=14,
        integral=a**4*sin(c + d*x)**5/(5*d) - 2*a**4*sin(c + d*x)**3/(3*d) + a**4*sin(c + d*x)/d - 4*a**3*b*cos(c + d*x)**5/(5*d) - 6*a**2*b**2*sin(c + d*x)**5/(5*d) + 2*a**2*b**2*sin(c + d*x)**3/d + 4*a*b**3*cos(c + d*x)**5/(5*d) - 4*a*b**3*cos(c + d*x)**3/(3*d) + b**4*sin(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4,
        variable=x,
        num_steps=3,
        integral=3*x*(a**2 + b**2)**2/8 - (3*a**2 + 3*b**2)*(-a*sin(c + d*x) + b*cos(c + d*x))*(a*cos(c + d*x) + b*sin(c + d*x))/(8*d) - (-a*sin(c + d*x) + b*cos(c + d*x))*(a*cos(c + d*x) + b*sin(c + d*x))**3/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*sec(c + d*x),
        variable=x,
        num_steps=14,
        integral=-a**4*sin(c + d*x)**3/(3*d) + a**4*sin(c + d*x)/d - 4*a**3*b*cos(c + d*x)**3/(3*d) + 2*a**2*b**2*sin(c + d*x)**3/d + 4*a*b**3*cos(c + d*x)**3/(3*d) - 4*a*b**3*cos(c + d*x)/d - b**4*sin(c + d*x)**3/(3*d) - b**4*sin(c + d*x)/d + b**4*atanh(sin(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*sec(c + d*x)**2,
        variable=x,
        num_steps=7,
        integral=-4*a*b**3*log(sin(c + d*x))/d + 4*a*b**3*log(tan(c + d*x))/d + b**4*tan(c + d*x)/d + x*(a**4/2 + 3*a**2*b**2 - 3*b**4/2) + (4*a*b*(a**2 - b**2) + (a**4 - 6*a**2*b**2 + b**4)*cot(c + d*x))*sin(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*sec(c + d*x)**3,
        variable=x,
        num_steps=14,
        integral=a**4*sin(c + d*x)/d - 4*a**3*b*cos(c + d*x)/d - 6*a**2*b**2*sin(c + d*x)/d + 6*a**2*b**2*atanh(sin(c + d*x))/d + 4*a*b**3*cos(c + d*x)/d + 4*a*b**3*sec(c + d*x)/d + b**4*sin(c + d*x)*tan(c + d*x)**2/(2*d) + 3*b**4*sin(c + d*x)/(2*d) - 3*b**4*atanh(sin(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*sec(c + d*x)**4,
        variable=x,
        num_steps=5,
        integral=a*b*(a + b*tan(c + d*x))**2/d - 4*a*b*(a**2 - b**2)*log(cos(c + d*x))/d + b**2*(3*a**2 - b**2)*tan(c + d*x)/d + b*(a + b*tan(c + d*x))**3/(3*d) + x*(a**4 - 6*a**2*b**2 + b**4),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*sec(c + d*x)**5,
        variable=x,
        num_steps=12,
        integral=a**4*atanh(sin(c + d*x))/d + 4*a**3*b*sec(c + d*x)/d + 3*a**2*b**2*tan(c + d*x)*sec(c + d*x)/d - 3*a**2*b**2*atanh(sin(c + d*x))/d + 4*a*b**3*sec(c + d*x)**3/(3*d) - 4*a*b**3*sec(c + d*x)/d + b**4*tan(c + d*x)**3*sec(c + d*x)/(4*d) - 3*b**4*tan(c + d*x)*sec(c + d*x)/(8*d) + 3*b**4*atanh(sin(c + d*x))/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*sec(c + d*x)**6,
        variable=x,
        num_steps=2,
        integral=(a*cot(c + d*x) + b)**5*tan(c + d*x)**5/(5*b*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*sec(c + d*x)**7,
        variable=x,
        num_steps=16,
        integral=a**4*tan(c + d*x)*sec(c + d*x)/(2*d) + a**4*atanh(sin(c + d*x))/(2*d) + 4*a**3*b*sec(c + d*x)**3/(3*d) + 3*a**2*b**2*tan(c + d*x)*sec(c + d*x)**3/(2*d) - 3*a**2*b**2*tan(c + d*x)*sec(c + d*x)/(4*d) - 3*a**2*b**2*atanh(sin(c + d*x))/(4*d) + 4*a*b**3*sec(c + d*x)**5/(5*d) - 4*a*b**3*sec(c + d*x)**3/(3*d) + b**4*tan(c + d*x)**3*sec(c + d*x)**3/(6*d) - b**4*tan(c + d*x)*sec(c + d*x)**3/(8*d) + b**4*tan(c + d*x)*sec(c + d*x)/(16*d) + b**4*atanh(sin(c + d*x))/(16*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*sec(c + d*x)**8,
        variable=x,
        num_steps=3,
        integral=a**4*tan(c + d*x)/d + 2*a**3*b*tan(c + d*x)**2/d + a**2*(a**2 + 6*b**2)*tan(c + d*x)**3/(3*d) + 2*a*b**3*tan(c + d*x)**6/(3*d) + a*b*(a**2 + b**2)*tan(c + d*x)**4/d + b**4*tan(c + d*x)**7/(7*d) + b**2*(6*a**2 + b**2)*tan(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*sec(c + d*x)**9,
        variable=x,
        num_steps=19,
        integral=a**4*tan(c + d*x)*sec(c + d*x)**3/(4*d) + 3*a**4*tan(c + d*x)*sec(c + d*x)/(8*d) + 3*a**4*atanh(sin(c + d*x))/(8*d) + 4*a**3*b*sec(c + d*x)**5/(5*d) + a**2*b**2*tan(c + d*x)*sec(c + d*x)**5/d - a**2*b**2*tan(c + d*x)*sec(c + d*x)**3/(4*d) - 3*a**2*b**2*tan(c + d*x)*sec(c + d*x)/(8*d) - 3*a**2*b**2*atanh(sin(c + d*x))/(8*d) + 4*a*b**3*sec(c + d*x)**7/(7*d) - 4*a*b**3*sec(c + d*x)**5/(5*d) + b**4*tan(c + d*x)**3*sec(c + d*x)**5/(8*d) - b**4*tan(c + d*x)*sec(c + d*x)**5/(16*d) + b**4*tan(c + d*x)*sec(c + d*x)**3/(64*d) + 3*b**4*tan(c + d*x)*sec(c + d*x)/(128*d) + 3*b**4*atanh(sin(c + d*x))/(128*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*sec(c + d*x)**10,
        variable=x,
        num_steps=3,
        integral=a**4*tan(c + d*x)/d + 2*a**3*b*tan(c + d*x)**2/d + 2*a**2*(a**2 + 3*b**2)*tan(c + d*x)**3/(3*d) + a*b**3*tan(c + d*x)**8/(2*d) + 2*a*b*(a**2 + 2*b**2)*tan(c + d*x)**6/(3*d) + a*b*(2*a**2 + b**2)*tan(c + d*x)**4/d + b**4*tan(c + d*x)**9/(9*d) + 2*b**2*(3*a**2 + b**2)*tan(c + d*x)**7/(7*d) + (a**4 + 12*a**2*b**2 + b**4)*tan(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*sec(c + d*x)**11,
        variable=x,
        num_steps=22,
        integral=a**4*tan(c + d*x)*sec(c + d*x)**5/(6*d) + 5*a**4*tan(c + d*x)*sec(c + d*x)**3/(24*d) + 5*a**4*tan(c + d*x)*sec(c + d*x)/(16*d) + 5*a**4*atanh(sin(c + d*x))/(16*d) + 4*a**3*b*sec(c + d*x)**7/(7*d) + 3*a**2*b**2*tan(c + d*x)*sec(c + d*x)**7/(4*d) - a**2*b**2*tan(c + d*x)*sec(c + d*x)**5/(8*d) - 5*a**2*b**2*tan(c + d*x)*sec(c + d*x)**3/(32*d) - 15*a**2*b**2*tan(c + d*x)*sec(c + d*x)/(64*d) - 15*a**2*b**2*atanh(sin(c + d*x))/(64*d) + 4*a*b**3*sec(c + d*x)**9/(9*d) - 4*a*b**3*sec(c + d*x)**7/(7*d) + b**4*tan(c + d*x)**3*sec(c + d*x)**7/(10*d) - 3*b**4*tan(c + d*x)*sec(c + d*x)**7/(80*d) + b**4*tan(c + d*x)*sec(c + d*x)**5/(160*d) + b**4*tan(c + d*x)*sec(c + d*x)**3/(128*d) + 3*b**4*tan(c + d*x)*sec(c + d*x)/(256*d) + 3*b**4*atanh(sin(c + d*x))/(256*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**4*sec(c + d*x)**12,
        variable=x,
        num_steps=3,
        integral=a**4*tan(c + d*x)/d + 2*a**3*b*tan(c + d*x)**2/d + a**2*(a**2 + 2*b**2)*tan(c + d*x)**3/d + 2*a*b**3*tan(c + d*x)**10/(5*d) + 2*a*b*(a**2 + b**2)*tan(c + d*x)**6/d + a*b*(a**2 + 3*b**2)*tan(c + d*x)**8/(2*d) + a*b*(3*a**2 + b**2)*tan(c + d*x)**4/d + b**4*tan(c + d*x)**11/(11*d) + b**2*(2*a**2 + b**2)*tan(c + d*x)**9/(3*d) + (a**4 + 18*a**2*b**2 + 3*b**4)*tan(c + d*x)**7/(7*d) + (3*a**4 + 18*a**2*b**2 + b**4)*tan(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*cos(c + d*x)**5,
        variable=x,
        num_steps=29,
        integral=63*a**5*x/256 + a**5*sin(c + d*x)*cos(c + d*x)**9/(10*d) + 9*a**5*sin(c + d*x)*cos(c + d*x)**7/(80*d) + 21*a**5*sin(c + d*x)*cos(c + d*x)**5/(160*d) + 21*a**5*sin(c + d*x)*cos(c + d*x)**3/(128*d) + 63*a**5*sin(c + d*x)*cos(c + d*x)/(256*d) - a**4*b*cos(c + d*x)**10/(2*d) + 35*a**3*b**2*x/128 - a**3*b**2*sin(c + d*x)*cos(c + d*x)**9/d + a**3*b**2*sin(c + d*x)*cos(c + d*x)**7/(8*d) + 7*a**3*b**2*sin(c + d*x)*cos(c + d*x)**5/(48*d) + 35*a**3*b**2*sin(c + d*x)*cos(c + d*x)**3/(192*d) + 35*a**3*b**2*sin(c + d*x)*cos(c + d*x)/(128*d) + a**2*b**3*cos(c + d*x)**10/d - 5*a**2*b**3*cos(c + d*x)**8/(4*d) + 15*a*b**4*x/256 - a*b**4*sin(c + d*x)**3*cos(c + d*x)**7/(2*d) - 3*a*b**4*sin(c + d*x)*cos(c + d*x)**7/(16*d) + a*b**4*sin(c + d*x)*cos(c + d*x)**5/(32*d) + 5*a*b**4*sin(c + d*x)*cos(c + d*x)**3/(128*d) + 15*a*b**4*sin(c + d*x)*cos(c + d*x)/(256*d) + b**5*sin(c + d*x)**10/(10*d) - b**5*sin(c + d*x)**8/(4*d) + b**5*sin(c + d*x)**6/(6*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*cos(c + d*x)**4,
        variable=x,
        num_steps=18,
        integral=a**5*sin(c + d*x)**9/(9*d) - 4*a**5*sin(c + d*x)**7/(7*d) + 6*a**5*sin(c + d*x)**5/(5*d) - 4*a**5*sin(c + d*x)**3/(3*d) + a**5*sin(c + d*x)/d - 5*a**4*b*cos(c + d*x)**9/(9*d) - 10*a**3*b**2*sin(c + d*x)**9/(9*d) + 30*a**3*b**2*sin(c + d*x)**7/(7*d) - 6*a**3*b**2*sin(c + d*x)**5/d + 10*a**3*b**2*sin(c + d*x)**3/(3*d) + 10*a**2*b**3*cos(c + d*x)**9/(9*d) - 10*a**2*b**3*cos(c + d*x)**7/(7*d) + 5*a*b**4*sin(c + d*x)**9/(9*d) - 10*a*b**4*sin(c + d*x)**7/(7*d) + a*b**4*sin(c + d*x)**5/d - b**5*cos(c + d*x)**9/(9*d) + 2*b**5*cos(c + d*x)**7/(7*d) - b**5*cos(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*cos(c + d*x)**3,
        variable=x,
        num_steps=25,
        integral=35*a**5*x/128 + a**5*sin(c + d*x)*cos(c + d*x)**7/(8*d) + 7*a**5*sin(c + d*x)*cos(c + d*x)**5/(48*d) + 35*a**5*sin(c + d*x)*cos(c + d*x)**3/(192*d) + 35*a**5*sin(c + d*x)*cos(c + d*x)/(128*d) - 5*a**4*b*cos(c + d*x)**8/(8*d) + 25*a**3*b**2*x/64 - 5*a**3*b**2*sin(c + d*x)*cos(c + d*x)**7/(4*d) + 5*a**3*b**2*sin(c + d*x)*cos(c + d*x)**5/(24*d) + 25*a**3*b**2*sin(c + d*x)*cos(c + d*x)**3/(96*d) + 25*a**3*b**2*sin(c + d*x)*cos(c + d*x)/(64*d) + 5*a**2*b**3*cos(c + d*x)**8/(4*d) - 5*a**2*b**3*cos(c + d*x)**6/(3*d) + 15*a*b**4*x/128 - 5*a*b**4*sin(c + d*x)**3*cos(c + d*x)**5/(8*d) - 5*a*b**4*sin(c + d*x)*cos(c + d*x)**5/(16*d) + 5*a*b**4*sin(c + d*x)*cos(c + d*x)**3/(64*d) + 15*a*b**4*sin(c + d*x)*cos(c + d*x)/(128*d) - b**5*sin(c + d*x)**8/(8*d) + b**5*sin(c + d*x)**6/(6*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*cos(c + d*x)**2,
        variable=x,
        num_steps=18,
        integral=-a**5*sin(c + d*x)**7/(7*d) + 3*a**5*sin(c + d*x)**5/(5*d) - a**5*sin(c + d*x)**3/d + a**5*sin(c + d*x)/d - 5*a**4*b*cos(c + d*x)**7/(7*d) + 10*a**3*b**2*sin(c + d*x)**7/(7*d) - 4*a**3*b**2*sin(c + d*x)**5/d + 10*a**3*b**2*sin(c + d*x)**3/(3*d) + 10*a**2*b**3*cos(c + d*x)**7/(7*d) - 2*a**2*b**3*cos(c + d*x)**5/d - 5*a*b**4*sin(c + d*x)**7/(7*d) + a*b**4*sin(c + d*x)**5/d - b**5*cos(c + d*x)**7/(7*d) + 2*b**5*cos(c + d*x)**5/(5*d) - b**5*cos(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*cos(c + d*x),
        variable=x,
        num_steps=5,
        integral=5*a*x*(a**2 + b**2)**2/16 + 5*a*(a - b*cot(c + d*x))*(a**2 + b**2)*(a*cot(c + d*x) + b)*sin(c + d*x)**2/(16*d) + 5*a*(a - b*cot(c + d*x))*(a*cot(c + d*x) + b)**3*sin(c + d*x)**4/(24*d) + (a*cot(c + d*x) + b)**5*sin(c + d*x)**6/(6*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5,
        variable=x,
        num_steps=3,
        integral=-(a**2 + b**2)**2*(-a*sin(c + d*x) + b*cos(c + d*x))/d + (2*a**2 + 2*b**2)*(-a*sin(c + d*x) + b*cos(c + d*x))**3/(3*d) - (-a*sin(c + d*x) + b*cos(c + d*x))**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*sec(c + d*x),
        variable=x,
        num_steps=8,
        integral=a*x*(3*a**4 + 10*a**2*b**2 + 15*b**4)/8 - b**5*log(sin(c + d*x))/d + b**5*log(tan(c + d*x))/d - (a*(a**4 - 10*a**2*b**2 + 5*b**4)*cot(c + d*x) + b*(5*a**4 - 10*a**2*b**2 + b**4))*sin(c + d*x)**4/(4*d) + (5*a*(a**2 - 3*b**2)*(a**2 + b**2)*cot(c + d*x) + 4*b*(5*a**4 - b**4))*sin(c + d*x)**2/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*sec(c + d*x)**2,
        variable=x,
        num_steps=17,
        integral=-a**5*sin(c + d*x)**3/(3*d) + a**5*sin(c + d*x)/d - 5*a**4*b*cos(c + d*x)**3/(3*d) + 10*a**3*b**2*sin(c + d*x)**3/(3*d) + 10*a**2*b**3*cos(c + d*x)**3/(3*d) - 10*a**2*b**3*cos(c + d*x)/d - 5*a*b**4*sin(c + d*x)**3/(3*d) - 5*a*b**4*sin(c + d*x)/d + 5*a*b**4*atanh(sin(c + d*x))/d - b**5*cos(c + d*x)**3/(3*d) + 2*b**5*cos(c + d*x)/d + b**5*sec(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*sec(c + d*x)**3,
        variable=x,
        num_steps=7,
        integral=5*a*b**4*tan(c + d*x)/d + a*x*(a**4 + 10*a**2*b**2 - 15*b**4)/2 + b**5*tan(c + d*x)**2/(2*d) - 2*b**3*(5*a**2 - b**2)*log(sin(c + d*x))/d + 2*b**3*(5*a**2 - b**2)*log(tan(c + d*x))/d + (a*(a**4 - 10*a**2*b**2 + 5*b**4)*cot(c + d*x) + b*(5*a**4 - 10*a**2*b**2 + b**4))*sin(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*sec(c + d*x)**4,
        variable=x,
        num_steps=17,
        integral=a**5*sin(c + d*x)/d - 5*a**4*b*cos(c + d*x)/d - 10*a**3*b**2*sin(c + d*x)/d + 10*a**3*b**2*atanh(sin(c + d*x))/d + 10*a**2*b**3*cos(c + d*x)/d + 10*a**2*b**3*sec(c + d*x)/d + 5*a*b**4*sin(c + d*x)*tan(c + d*x)**2/(2*d) + 15*a*b**4*sin(c + d*x)/(2*d) - 15*a*b**4*atanh(sin(c + d*x))/(2*d) - b**5*cos(c + d*x)/d + b**5*sec(c + d*x)**3/(3*d) - 2*b**5*sec(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*sec(c + d*x)**5,
        variable=x,
        num_steps=6,
        integral=4*a*b**2*(a**2 - b**2)*tan(c + d*x)/d + 2*a*b*(a + b*tan(c + d*x))**3/(3*d) + a*x*(a**4 - 10*a**2*b**2 + 5*b**4) + b*(a + b*tan(c + d*x))**4/(4*d) + b*(a + b*tan(c + d*x))**2*(3*a**2 - b**2)/(2*d) - b*(5*a**4 - 10*a**2*b**2 + b**4)*log(cos(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*sec(c + d*x)**6,
        variable=x,
        num_steps=15,
        integral=a**5*atanh(sin(c + d*x))/d + 5*a**4*b*sec(c + d*x)/d + 5*a**3*b**2*tan(c + d*x)*sec(c + d*x)/d - 5*a**3*b**2*atanh(sin(c + d*x))/d + 10*a**2*b**3*sec(c + d*x)**3/(3*d) - 10*a**2*b**3*sec(c + d*x)/d + 5*a*b**4*tan(c + d*x)**3*sec(c + d*x)/(4*d) - 15*a*b**4*tan(c + d*x)*sec(c + d*x)/(8*d) + 15*a*b**4*atanh(sin(c + d*x))/(8*d) + b**5*sec(c + d*x)**5/(5*d) - 2*b**5*sec(c + d*x)**3/(3*d) + b**5*sec(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*sec(c + d*x)**7,
        variable=x,
        num_steps=2,
        integral=(a*cot(c + d*x) + b)**6*tan(c + d*x)**6/(6*b*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*sec(c + d*x)**8,
        variable=x,
        num_steps=19,
        integral=a**5*tan(c + d*x)*sec(c + d*x)/(2*d) + a**5*atanh(sin(c + d*x))/(2*d) + 5*a**4*b*sec(c + d*x)**3/(3*d) + 5*a**3*b**2*tan(c + d*x)*sec(c + d*x)**3/(2*d) - 5*a**3*b**2*tan(c + d*x)*sec(c + d*x)/(4*d) - 5*a**3*b**2*atanh(sin(c + d*x))/(4*d) + 2*a**2*b**3*sec(c + d*x)**5/d - 10*a**2*b**3*sec(c + d*x)**3/(3*d) + 5*a*b**4*tan(c + d*x)**3*sec(c + d*x)**3/(6*d) - 5*a*b**4*tan(c + d*x)*sec(c + d*x)**3/(8*d) + 5*a*b**4*tan(c + d*x)*sec(c + d*x)/(16*d) + 5*a*b**4*atanh(sin(c + d*x))/(16*d) + b**5*sec(c + d*x)**7/(7*d) - 2*b**5*sec(c + d*x)**5/(5*d) + b**5*sec(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*sec(c + d*x)**9,
        variable=x,
        num_steps=3,
        integral=a**5*tan(c + d*x)/d + 5*a**4*b*tan(c + d*x)**2/(2*d) + a**3*(a**2 + 10*b**2)*tan(c + d*x)**3/(3*d) + 5*a**2*b*(a**2 + 2*b**2)*tan(c + d*x)**4/(4*d) + 5*a*b**4*tan(c + d*x)**7/(7*d) + a*b**2*(2*a**2 + b**2)*tan(c + d*x)**5/d + b**5*tan(c + d*x)**8/(8*d) + b**3*(10*a**2 + b**2)*tan(c + d*x)**6/(6*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*sec(c + d*x)**10,
        variable=x,
        num_steps=22,
        integral=a**5*tan(c + d*x)*sec(c + d*x)**3/(4*d) + 3*a**5*tan(c + d*x)*sec(c + d*x)/(8*d) + 3*a**5*atanh(sin(c + d*x))/(8*d) + a**4*b*sec(c + d*x)**5/d + 5*a**3*b**2*tan(c + d*x)*sec(c + d*x)**5/(3*d) - 5*a**3*b**2*tan(c + d*x)*sec(c + d*x)**3/(12*d) - 5*a**3*b**2*tan(c + d*x)*sec(c + d*x)/(8*d) - 5*a**3*b**2*atanh(sin(c + d*x))/(8*d) + 10*a**2*b**3*sec(c + d*x)**7/(7*d) - 2*a**2*b**3*sec(c + d*x)**5/d + 5*a*b**4*tan(c + d*x)**3*sec(c + d*x)**5/(8*d) - 5*a*b**4*tan(c + d*x)*sec(c + d*x)**5/(16*d) + 5*a*b**4*tan(c + d*x)*sec(c + d*x)**3/(64*d) + 15*a*b**4*tan(c + d*x)*sec(c + d*x)/(128*d) + 15*a*b**4*atanh(sin(c + d*x))/(128*d) + b**5*sec(c + d*x)**9/(9*d) - 2*b**5*sec(c + d*x)**7/(7*d) + b**5*sec(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*sec(c + d*x)**11,
        variable=x,
        num_steps=3,
        integral=a**5*tan(c + d*x)/d + 5*a**4*b*tan(c + d*x)**2/(2*d) + 2*a**3*(a**2 + 5*b**2)*tan(c + d*x)**3/(3*d) + 5*a**2*b*(a**2 + b**2)*tan(c + d*x)**4/(2*d) + 5*a*b**4*tan(c + d*x)**9/(9*d) + 10*a*b**2*(a**2 + b**2)*tan(c + d*x)**7/(7*d) + a*(a**4 + 20*a**2*b**2 + 5*b**4)*tan(c + d*x)**5/(5*d) + b**5*tan(c + d*x)**10/(10*d) + b**3*(5*a**2 + b**2)*tan(c + d*x)**8/(4*d) + b*(5*a**4 + 20*a**2*b**2 + b**4)*tan(c + d*x)**6/(6*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**5*sec(c + d*x)**12,
        variable=x,
        num_steps=25,
        integral=a**5*tan(c + d*x)*sec(c + d*x)**5/(6*d) + 5*a**5*tan(c + d*x)*sec(c + d*x)**3/(24*d) + 5*a**5*tan(c + d*x)*sec(c + d*x)/(16*d) + 5*a**5*atanh(sin(c + d*x))/(16*d) + 5*a**4*b*sec(c + d*x)**7/(7*d) + 5*a**3*b**2*tan(c + d*x)*sec(c + d*x)**7/(4*d) - 5*a**3*b**2*tan(c + d*x)*sec(c + d*x)**5/(24*d) - 25*a**3*b**2*tan(c + d*x)*sec(c + d*x)**3/(96*d) - 25*a**3*b**2*tan(c + d*x)*sec(c + d*x)/(64*d) - 25*a**3*b**2*atanh(sin(c + d*x))/(64*d) + 10*a**2*b**3*sec(c + d*x)**9/(9*d) - 10*a**2*b**3*sec(c + d*x)**7/(7*d) + a*b**4*tan(c + d*x)**3*sec(c + d*x)**7/(2*d) - 3*a*b**4*tan(c + d*x)*sec(c + d*x)**7/(16*d) + a*b**4*tan(c + d*x)*sec(c + d*x)**5/(32*d) + 5*a*b**4*tan(c + d*x)*sec(c + d*x)**3/(128*d) + 15*a*b**4*tan(c + d*x)*sec(c + d*x)/(256*d) + 15*a*b**4*atanh(sin(c + d*x))/(256*d) + b**5*sec(c + d*x)**11/(11*d) - 2*b**5*sec(c + d*x)**9/(9*d) + b**5*sec(c + d*x)**7/(7*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**5/(a*cos(c + d*x) + b*sin(c + d*x)),
        variable=x,
        num_steps=9,
        integral=a*b**4*x/(a**2 + b**2)**3 + a*b**2*x/(2*(a**2 + b**2)**2) + a*b**2*sin(c + d*x)*cos(c + d*x)/(2*d*(a**2 + b**2)**2) + 3*a*x/(8*a**2 + 8*b**2) + 3*a*sin(c + d*x)*cos(c + d*x)/(d*(8*a**2 + 8*b**2)) + a*sin(c + d*x)*cos(c + d*x)**3/(d*(4*a**2 + 4*b**2)) + b**5*log(a*cos(c + d*x) + b*sin(c + d*x))/(d*(a**2 + b**2)**3) + b**3*cos(c + d*x)**2/(2*d*(a**2 + b**2)**2) + b*cos(c + d*x)**4/(d*(4*a**2 + 4*b**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**4/(a*cos(c + d*x) + b*sin(c + d*x)),
        variable=x,
        num_steps=7,
        integral=a*b**2*sin(c + d*x)/(d*(a**2 + b**2)**2) - a*sin(c + d*x)**3/(d*(3*a**2 + 3*b**2)) + a*sin(c + d*x)/(d*(a**2 + b**2)) - b**4*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(d*(a**2 + b**2)**(sympy.S(5)/2)) + b**3*cos(c + d*x)/(d*(a**2 + b**2)**2) + b*cos(c + d*x)**3/(d*(3*a**2 + 3*b**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/(a*cos(c + d*x) + b*sin(c + d*x)),
        variable=x,
        num_steps=5,
        integral=a*b**2*x/(a**2 + b**2)**2 + a*x/(2*a**2 + 2*b**2) + a*sin(c + d*x)*cos(c + d*x)/(d*(2*a**2 + 2*b**2)) + b**3*log(a*cos(c + d*x) + b*sin(c + d*x))/(d*(a**2 + b**2)**2) + b*cos(c + d*x)**2/(d*(2*a**2 + 2*b**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(a*cos(c + d*x) + b*sin(c + d*x)),
        variable=x,
        num_steps=4,
        integral=a*sin(c + d*x)/(d*(a**2 + b**2)) - b**2*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(d*(a**2 + b**2)**(sympy.S(3)/2)) + b*cos(c + d*x)/(d*(a**2 + b**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(a*cos(c + d*x) + b*sin(c + d*x)),
        variable=x,
        num_steps=2,
        integral=a*x/(a**2 + b**2) + b*log(a*cos(c + d*x) + b*sin(c + d*x))/(d*(a**2 + b**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(a*cos(c + d*x) + b*sin(c + d*x)),
        variable=x,
        num_steps=2,
        integral=-atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(d*sqrt(a**2 + b**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(a*cos(c + d*x) + b*sin(c + d*x)),
        variable=x,
        num_steps=3,
        integral=log(a*cos(c + d*x) + b*sin(c + d*x))/(b*d) - log(cos(c + d*x))/(b*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(a*cos(c + d*x) + b*sin(c + d*x)),
        variable=x,
        num_steps=4,
        integral=-a*atanh(sin(c + d*x))/(b**2*d) + sec(c + d*x)/(b*d) - sqrt(a**2 + b**2)*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(a*cos(c + d*x) + b*sin(c + d*x)),
        variable=x,
        num_steps=6,
        integral=-a*tan(c + d*x)/(b**2*d) + sec(c + d*x)**2/(2*b*d) + (a**2 + b**2)*log(a*cos(c + d*x) + b*sin(c + d*x))/(b**3*d) - (a**2 + b**2)*log(cos(c + d*x))/(b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**4/(a*cos(c + d*x) + b*sin(c + d*x)),
        variable=x,
        num_steps=7,
        integral=-a*tan(c + d*x)*sec(c + d*x)/(2*b**2*d) - a*atanh(sin(c + d*x))/(2*b**2*d) - a*(a**2 + b**2)*atanh(sin(c + d*x))/(b**4*d) + sec(c + d*x)**3/(3*b*d) + (a**2 + b**2)*sec(c + d*x)/(b**3*d) - (a**2 + b**2)**(sympy.S(3)/2)*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**5/(a*cos(c + d*x) + b*sin(c + d*x)),
        variable=x,
        num_steps=9,
        integral=-a*tan(c + d*x)**3/(3*b**2*d) - a*tan(c + d*x)/(b**2*d) - a*(a**2 + b**2)*tan(c + d*x)/(b**4*d) + sec(c + d*x)**4/(4*b*d) + (a**2 + b**2)*sec(c + d*x)**2/(2*b**3*d) + (a**2 + b**2)**2*log(a*cos(c + d*x) + b*sin(c + d*x))/(b**5*d) - (a**2 + b**2)**2*log(cos(c + d*x))/(b**5*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**6/(a*cos(c + d*x) + b*sin(c + d*x)),
        variable=x,
        num_steps=11,
        integral=-a*tan(c + d*x)*sec(c + d*x)**3/(4*b**2*d) - 3*a*tan(c + d*x)*sec(c + d*x)/(8*b**2*d) - 3*a*atanh(sin(c + d*x))/(8*b**2*d) - a*(a**2 + b**2)*tan(c + d*x)*sec(c + d*x)/(2*b**4*d) - a*(a**2 + b**2)*atanh(sin(c + d*x))/(2*b**4*d) - a*(a**2 + b**2)**2*atanh(sin(c + d*x))/(b**6*d) + sec(c + d*x)**5/(5*b*d) + (a**2 + b**2)*sec(c + d*x)**3/(3*b**3*d) + (a**2 + b**2)**2*sec(c + d*x)/(b**5*d) - (a**2 + b**2)**(sympy.S(5)/2)*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(b**6*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**4/(a*cos(c + d*x) + b*sin(c + d*x))**2,
        variable=x,
        num_steps=7,
        integral=4*a*b**3*log(a*cos(c + d*x) + b*sin(c + d*x))/(d*(a**2 + b**2)**3) + x*(a**4 + 6*a**2*b**2 - 3*b**4)/(2*(a**2 + b**2)**3) - (2*a*b - (a**2 - b**2)*cot(c + d*x))*sin(c + d*x)**2/(2*d*(a**2 + b**2)**2) + b**4/(a*d*(a**2 + b**2)**2*(a*cot(c + d*x) + b)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/(a*cos(c + d*x) + b*sin(c + d*x))**2,
        variable=x,
        num_steps=-11,
        integral=-3*a*b**2*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(d*(a**2 + b**2)**(sympy.S(5)/2)) + 2*a*b*cos(c + d*x)/(d*(a**2 + b**2)**2) - b**3/(d*(a**2 + b**2)**2*(a*cos(c + d*x) + b*sin(c + d*x))) + (a**2 - b**2)*sin(c + d*x)/(d*(a**2 + b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(a*cos(c + d*x) + b*sin(c + d*x))**2,
        variable=x,
        num_steps=4,
        integral=2*a*b*log(a*cos(c + d*x) + b*sin(c + d*x))/(d*(a**2 + b**2)**2) - b/(d*(a + b*tan(c + d*x))*(a**2 + b**2)) + x*(a**2 - b**2)/(a**2 + b**2)**2,
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(a*cos(c + d*x) + b*sin(c + d*x))**2,
        variable=x,
        num_steps=3,
        integral=-a*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(d*(a**2 + b**2)**(sympy.S(3)/2)) - b/(d*(a**2 + b**2)*(a*cos(c + d*x) + b*sin(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**(-2),
        variable=x,
        num_steps=1,
        integral=sin(c + d*x)/(a*d*(a*cos(c + d*x) + b*sin(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(a*cos(c + d*x) + b*sin(c + d*x))**2,
        variable=x,
        num_steps=4,
        integral=a*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(b**2*d*sqrt(a**2 + b**2)) - 1/(b*d*(a*cos(c + d*x) + b*sin(c + d*x))) + atanh(sin(c + d*x))/(b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(a*cos(c + d*x) + b*sin(c + d*x))**2,
        variable=x,
        num_steps=3,
        integral=-2*a*log(a*cot(c + d*x) + b)/(b**3*d) - 2*a*log(tan(c + d*x))/(b**3*d) + (a/b**2 + 1/a)/(d*(a*cot(c + d*x) + b)) + tan(c + d*x)/(b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(a*cos(c + d*x) + b*sin(c + d*x))**2,
        variable=x,
        num_steps=11,
        integral=2*a**2*atanh(sin(c + d*x))/(b**4*d) - 2*a*sec(c + d*x)/(b**3*d) + 3*a*sqrt(a**2 + b**2)*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(b**4*d) + tan(c + d*x)*sec(c + d*x)/(2*b**2*d) + atanh(sin(c + d*x))/(2*b**2*d) - (a**2 + b**2)/(b**3*d*(a*cos(c + d*x) + b*sin(c + d*x))) + (a**2 + b**2)*atanh(sin(c + d*x))/(b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**4/(a*cos(c + d*x) + b*sin(c + d*x))**2,
        variable=x,
        num_steps=3,
        integral=-a*tan(c + d*x)**2/(b**3*d) - 4*a*(a**2 + b**2)*log(a*cot(c + d*x) + b)/(b**5*d) - 4*a*(a**2 + b**2)*log(tan(c + d*x))/(b**5*d) + tan(c + d*x)**3/(3*b**2*d) + (3*a**2 + 2*b**2)*tan(c + d*x)/(b**4*d) + (a**2 + b**2)**2/(a*b**4*d*(a*cot(c + d*x) + b)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**4/(a*cos(c + d*x) + b*sin(c + d*x))**3,
        variable=x,
        num_steps=-15,
        integral=a*(a**2 - 3*b**2)*sin(c + d*x)/(d*(a**2 + b**2)**3) - 3*b**2*(4*a**2 - b**2)*atanh((-a*tan(c/2 + d*x/2) + b)/sqrt(a**2 + b**2))/(d*(a**2 + b**2)**(sympy.S(7)/2)) + b*(3*a**2 - b**2)*cos(c + d*x)/(d*(a**2 + b**2)**3) + b**4*sin(c + d*x)/(2*a*d*(a**2 + b**2)**2*(a*cos(c + d*x) + b*sin(c + d*x))**2) - b**3*(8*a**2 + b**2)/(2*a*d*(a**2 + b**2)**3*(a*cos(c + d*x) + b*sin(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/(a*cos(c + d*x) + b*sin(c + d*x))**3,
        variable=x,
        num_steps=5,
        integral=-2*a*b/(d*(a + b*tan(c + d*x))*(a**2 + b**2)**2) + a*x*(a**2 - 3*b**2)/(a**2 + b**2)**3 + b*(3*a**2 - b**2)*log(a*cos(c + d*x) + b*sin(c + d*x))/(d*(a**2 + b**2)**3) - b/(d*(a + b*tan(c + d*x))**2*(2*a**2 + 2*b**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(a*cos(c + d*x) + b*sin(c + d*x))**3,
        variable=x,
        num_steps=-6,
        integral=-b*(3*a*b*sin(c + d*x) + (4*a**2 + b**2)*cos(c + d*x))/(2*d*(a**2 + b**2)**2*(a*cos(c + d*x) + b*sin(c + d*x))**2) + (4*a**2 - 2*b**2)*atanh((a*tan(c/2 + d*x/2) - b)/sqrt(a**2 + b**2))/(2*d*(a**2 + b**2)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**(-3),
        variable=x,
        num_steps=3,
        integral=-(-a*sin(c + d*x) + b*cos(c + d*x))/(d*(2*a**2 + 2*b**2)*(a*cos(c + d*x) + b*sin(c + d*x))**2) - atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(2*d*(a**2 + b**2)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(a*cos(c + d*x) + b*sin(c + d*x))**3,
        variable=x,
        num_steps=3,
        integral=(-1/b**2 + a**(-2))/(d*(a*cot(c + d*x) + b)) - (1/b + b/a**2)/(2*d*(a*cot(c + d*x) + b)**2) + log(a*cot(c + d*x) + b)/(b**3*d) + log(tan(c + d*x))/(b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(a*cos(c + d*x) + b*sin(c + d*x))**3,
        variable=x,
        num_steps=12,
        integral=-2*a**2*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(b**4*d*sqrt(a**2 + b**2)) + 2*a/(b**3*d*(a*cos(c + d*x) + b*sin(c + d*x))) - 3*a*atanh(sin(c + d*x))/(b**4*d) - (-a*sin(c + d*x) + b*cos(c + d*x))/(2*b**2*d*(a*cos(c + d*x) + b*sin(c + d*x))**2) - atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(2*b**2*d*sqrt(a**2 + b**2)) + sec(c + d*x)/(b**3*d) - sqrt(a**2 + b**2)*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(a*cos(c + d*x) + b*sin(c + d*x))**3,
        variable=x,
        num_steps=3,
        integral=-3*a*tan(c + d*x)/(b**4*d) + tan(c + d*x)**2/(2*b**3*d) + (6*a**2 + 2*b**2)*log(a*cot(c + d*x) + b)/(b**5*d) + (6*a**2 + 2*b**2)*log(tan(c + d*x))/(b**5*d) - (a**2 + b**2)**2/(2*a**2*b**3*d*(a*cot(c + d*x) + b)**2) - (a**2 + b**2)*(3*a**2 - b**2)/(a**2*b**4*d*(a*cot(c + d*x) + b)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**4/(a*cos(c + d*x) + b*sin(c + d*x))**3,
        variable=x,
        num_steps=31,
        integral=-4*a**3*atanh(sin(c + d*x))/(b**6*d) + 4*a**2*sec(c + d*x)/(b**5*d) - 8*a**2*sqrt(a**2 + b**2)*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(b**6*d) - 3*a*tan(c + d*x)*sec(c + d*x)/(2*b**4*d) - 3*a*atanh(sin(c + d*x))/(2*b**4*d) + 4*a*(a**2 + b**2)/(b**5*d*(a*cos(c + d*x) + b*sin(c + d*x))) - 6*a*(a**2 + b**2)*atanh(sin(c + d*x))/(b**6*d) + sec(c + d*x)**3/(3*b**3*d) - sqrt(a**2 + b**2)*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(2*b**4*d) - (a**2 + b**2)*(-a*sin(c + d*x) + b*cos(c + d*x))/(2*b**4*d*(a*cos(c + d*x) + b*sin(c + d*x))**2) + (2*a**2 + 2*b**2)*sec(c + d*x)/(b**5*d) - 2*(a**2 + b**2)**(sympy.S(3)/2)*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(b**6*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**5/(a*cos(c + d*x) + b*sin(c + d*x))**3,
        variable=x,
        num_steps=3,
        integral=-a*tan(c + d*x)**3/(b**4*d) - a*(10*a**2 + 9*b**2)*tan(c + d*x)/(b**6*d) + tan(c + d*x)**4/(4*b**3*d) + (6*a**2 + 3*b**2)*tan(c + d*x)**2/(2*b**5*d) + (3*a**2 + 3*b**2)*(5*a**2 + b**2)*log(a*cot(c + d*x) + b)/(b**7*d) + (3*a**2 + 3*b**2)*(5*a**2 + b**2)*log(tan(c + d*x))/(b**7*d) - (a**2 + b**2)**3/(2*a**2*b**5*d*(a*cot(c + d*x) + b)**2) - (a**2 + b**2)**2*(5*a**2 - b**2)/(a**2*b**6*d*(a*cot(c + d*x) + b)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**4/(a*cos(c + d*x) + b*sin(c + d*x))**4,
        variable=x,
        num_steps=6,
        integral=4*a*b*(a**2 - b**2)*log(a*cos(c + d*x) + b*sin(c + d*x))/(d*(a**2 + b**2)**4) - a*b/(d*(a + b*tan(c + d*x))**2*(a**2 + b**2)**2) - b*(3*a**2 - b**2)/(d*(a + b*tan(c + d*x))*(a**2 + b**2)**3) - b/(d*(a + b*tan(c + d*x))**3*(3*a**2 + 3*b**2)) + x*(a**4 - 6*a**2*b**2 + b**4)/(a**2 + b**2)**4,
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/(a*cos(c + d*x) + b*sin(c + d*x))**4,
        variable=x,
        num_steps=-7,
        integral=a*(2*a**2 - 3*b**2)*atanh((a*tan(c/2 + d*x/2) - b)/sqrt(a**2 + b**2))/(d*(a**2 + b**2)**(sympy.S(7)/2)) + (b*(-9*a**2 + b**2)*(2*a**2 + 3*a*b*sin(2*c + 2*d*x) + 2*b**2)/2 + (-9*a**4*b + 3*a**2*b**3 - 3*b**5)*cos(2*c + 2*d*x))/(6*d*(a**2 + b**2)**3*(a*cos(c + d*x) + b*sin(c + d*x))**3),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(a*cos(c + d*x) + b*sin(c + d*x))**4,
        variable=x,
        num_steps=2,
        integral=-cot(c + d*x)**3/(3*b*d*(a*cot(c + d*x) + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(a*cos(c + d*x) + b*sin(c + d*x))**4,
        variable=x,
        num_steps=5,
        integral=-a*(-a*sin(c + d*x) + b*cos(c + d*x))/(2*d*(a**2 + b**2)**2*(a*cos(c + d*x) + b*sin(c + d*x))**2) - a*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(2*d*(a**2 + b**2)**(sympy.S(5)/2)) - b/(d*(3*a**2 + 3*b**2)*(a*cos(c + d*x) + b*sin(c + d*x))**3),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(c + d*x) + b*sin(c + d*x))**(-4),
        variable=x,
        num_steps=2,
        integral=-(-a*sin(c + d*x) + b*cos(c + d*x))/(d*(3*a**2 + 3*b**2)*(a*cos(c + d*x) + b*sin(c + d*x))**3) + 2*sin(c + d*x)/(3*a*d*(a**2 + b**2)*(a*cos(c + d*x) + b*sin(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(a*cos(c + d*x) + b*sin(c + d*x))**4,
        variable=x,
        num_steps=8,
        integral=a*(-a*sin(c + d*x) + b*cos(c + d*x))/(2*b**2*d*(a**2 + b**2)*(a*cos(c + d*x) + b*sin(c + d*x))**2) + a*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(2*b**2*d*(a**2 + b**2)**(sympy.S(3)/2)) + a*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(b**4*d*sqrt(a**2 + b**2)) - 1/(3*b*d*(a*cos(c + d*x) + b*sin(c + d*x))**3) - 1/(b**3*d*(a*cos(c + d*x) + b*sin(c + d*x))) + atanh(sin(c + d*x))/(b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(a*cos(c + d*x) + b*sin(c + d*x))**4,
        variable=x,
        num_steps=3,
        integral=-4*a*log(a*cot(c + d*x) + b)/(b**5*d) - 4*a*log(tan(c + d*x))/(b**5*d) + (3*a/b**4 + a**(-3))/(d*(a*cot(c + d*x) + b)) + (a/b**3 - b/a**3)/(d*(a*cot(c + d*x) + b)**2) + tan(c + d*x)/(b**4*d) + (a**2 + b**2)**2/(3*a**3*b**2*d*(a*cot(c + d*x) + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(a*cos(c + d*x) + b*sin(c + d*x))**4,
        variable=x,
        num_steps=32,
        integral=4*a**3*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(b**6*d*sqrt(a**2 + b**2)) - 4*a**2/(b**5*d*(a*cos(c + d*x) + b*sin(c + d*x))) + 8*a**2*atanh(sin(c + d*x))/(b**6*d) + 3*a*(-a*sin(c + d*x) + b*cos(c + d*x))/(2*b**4*d*(a*cos(c + d*x) + b*sin(c + d*x))**2) + 3*a*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(2*b**4*d*sqrt(a**2 + b**2)) - 4*a*sec(c + d*x)/(b**5*d) + 6*a*sqrt(a**2 + b**2)*atanh((-a*sin(c + d*x) + b*cos(c + d*x))/sqrt(a**2 + b**2))/(b**6*d) - (a**2 + b**2)/(3*b**3*d*(a*cos(c + d*x) + b*sin(c + d*x))**3) + tan(c + d*x)*sec(c + d*x)/(2*b**4*d) + atanh(sin(c + d*x))/(2*b**4*d) - (2*a**2 + 2*b**2)/(b**5*d*(a*cos(c + d*x) + b*sin(c + d*x))) + (2*a**2 + 2*b**2)*atanh(sin(c + d*x))/(b**6*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**4/(a*cos(c + d*x) + b*sin(c + d*x))**4,
        variable=x,
        num_steps=3,
        integral=-2*a*tan(c + d*x)**2/(b**5*d) - 4*a*(5*a**2 + 3*b**2)*log(a*cot(c + d*x) + b)/(b**7*d) - 4*a*(5*a**2 + 3*b**2)*log(tan(c + d*x))/(b**7*d) + tan(c + d*x)**3/(3*b**4*d) + (10*a**2 + 3*b**2)*tan(c + d*x)/(b**6*d) + (a**2 + b**2)**3/(3*a**3*b**4*d*(a*cot(c + d*x) + b)**3) + (2*a**6 + 3*a**4*b**2 - b**6)/(a**3*b**5*d*(a*cot(c + d*x) + b)**2) + (10*a**6 + 9*a**4*b**2 + b**6)/(a**3*b**6*d*(a*cot(c + d*x) + b)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**5/(I*a*sin(c + d*x) + a*cos(c + d*x)),
        variable=x,
        num_steps=9,
        integral=5*x/(16*a) + sin(c + d*x)*cos(c + d*x)**5/(6*a*d) + 5*sin(c + d*x)*cos(c + d*x)**3/(24*a*d) + 5*sin(c + d*x)*cos(c + d*x)/(16*a*d) + I*cos(c + d*x)**6/(6*a*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**4/(I*a*sin(c + d*x) + a*cos(c + d*x)),
        variable=x,
        num_steps=7,
        integral=sin(c + d*x)**5/(5*a*d) - 2*sin(c + d*x)**3/(3*a*d) + sin(c + d*x)/(a*d) + I*cos(c + d*x)**5/(5*a*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/(I*a*sin(c + d*x) + a*cos(c + d*x)),
        variable=x,
        num_steps=8,
        integral=3*x/(8*a) + sin(c + d*x)*cos(c + d*x)**3/(4*a*d) + 3*sin(c + d*x)*cos(c + d*x)/(8*a*d) + I*cos(c + d*x)**4/(4*a*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(I*a*sin(c + d*x) + a*cos(c + d*x)),
        variable=x,
        num_steps=7,
        integral=-sin(c + d*x)**3/(3*a*d) + sin(c + d*x)/(a*d) + I*cos(c + d*x)**3/(3*a*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(I*a*sin(c + d*x) + a*cos(c + d*x)),
        variable=x,
        num_steps=2,
        integral=I*cos(c + d*x)/(2*d*(I*a*sin(c + d*x) + a*cos(c + d*x))) + x/(2*a),
    ),
    RubiTestSuiteCase(
        integrand=1/(I*a*sin(c + d*x) + a*cos(c + d*x)),
        variable=x,
        num_steps=1,
        integral=I/(d*(I*a*sin(c + d*x) + a*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(I*a*sin(c + d*x) + a*cos(c + d*x)),
        variable=x,
        num_steps=4,
        integral=x/a + I*log(cos(c + d*x))/(a*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(I*a*sin(c + d*x) + a*cos(c + d*x)),
        variable=x,
        num_steps=6,
        integral=atanh(sin(c + d*x))/(a*d) - I*sec(c + d*x)/(a*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(I*a*sin(c + d*x) + a*cos(c + d*x)),
        variable=x,
        num_steps=7,
        integral=tan(c + d*x)/(a*d) - I*sec(c + d*x)**2/(2*a*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**4/(I*a*sin(c + d*x) + a*cos(c + d*x)),
        variable=x,
        num_steps=7,
        integral=tan(c + d*x)*sec(c + d*x)/(2*a*d) + atanh(sin(c + d*x))/(2*a*d) - I*sec(c + d*x)**3/(3*a*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**5/(I*a*sin(c + d*x) + a*cos(c + d*x)),
        variable=x,
        num_steps=7,
        integral=tan(c + d*x)**3/(3*a*d) + tan(c + d*x)/(a*d) - I*sec(c + d*x)**4/(4*a*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**6/(I*a*sin(c + d*x) + a*cos(c + d*x)),
        variable=x,
        num_steps=8,
        integral=tan(c + d*x)*sec(c + d*x)**3/(4*a*d) + 3*tan(c + d*x)*sec(c + d*x)/(8*a*d) + 3*atanh(sin(c + d*x))/(8*a*d) - I*sec(c + d*x)**5/(5*a*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**7/(I*a*sin(c + d*x) + a*cos(c + d*x)),
        variable=x,
        num_steps=7,
        integral=tan(c + d*x)**5/(5*a*d) + 2*tan(c + d*x)**3/(3*a*d) + tan(c + d*x)/(a*d) - I*sec(c + d*x)**6/(6*a*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**5/(I*a*sin(c + d*x) + a*cos(c + d*x))**2,
        variable=x,
        num_steps=10,
        integral=-2*sin(c + d*x)**7/(7*a**2*d) + sin(c + d*x)**5/(a**2*d) - 4*sin(c + d*x)**3/(3*a**2*d) + sin(c + d*x)/(a**2*d) + 2*I*cos(c + d*x)**7/(7*a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**4/(I*a*sin(c + d*x) + a*cos(c + d*x))**2,
        variable=x,
        num_steps=5,
        integral=x/(4*a**2) + 11/(16*a**2*d*(cot(c + d*x) + I)) - 3*I/(8*a**2*d*(cot(c + d*x) + I)**2) - 1/(12*a**2*d*(cot(c + d*x) + I)**3) - 1/(16*a**2*d*(-cot(c + d*x) + I)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/(I*a*sin(c + d*x) + a*cos(c + d*x))**2,
        variable=x,
        num_steps=10,
        integral=2*sin(c + d*x)**5/(5*a**2*d) - sin(c + d*x)**3/(a**2*d) + sin(c + d*x)/(a**2*d) + 2*I*cos(c + d*x)**5/(5*a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(I*a*sin(c + d*x) + a*cos(c + d*x))**2,
        variable=x,
        num_steps=3,
        integral=I*cos(c + d*x)/(4*d*(I*a**2*sin(c + d*x) + a**2*cos(c + d*x))) + I*cos(c + d*x)**2/(4*d*(I*a*sin(c + d*x) + a*cos(c + d*x))**2) + x/(4*a**2),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(I*a*sin(c + d*x) + a*cos(c + d*x))**2,
        variable=x,
        num_steps=9,
        integral=-2*sin(c + d*x)**3/(3*a**2*d) + sin(c + d*x)/(a**2*d) + 2*I*cos(c + d*x)**3/(3*a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=(I*a*sin(c + d*x) + a*cos(c + d*x))**(-2),
        variable=x,
        num_steps=1,
        integral=I/(2*d*(I*a*sin(c + d*x) + a*cos(c + d*x))**2),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(I*a*sin(c + d*x) + a*cos(c + d*x))**2,
        variable=x,
        num_steps=8,
        integral=2*sin(c + d*x)/(a**2*d) + 2*I*cos(c + d*x)/(a**2*d) - atanh(sin(c + d*x))/(a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(I*a*sin(c + d*x) + a*cos(c + d*x))**2,
        variable=x,
        num_steps=4,
        integral=2*x/a**2 + 2*I*log(sin(c + d*x))/(a**2*d) - 2*I*log(tan(c + d*x))/(a**2*d) - tan(c + d*x)/(a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(I*a*sin(c + d*x) + a*cos(c + d*x))**2,
        variable=x,
        num_steps=8,
        integral=-tan(c + d*x)*sec(c + d*x)/(2*a**2*d) + 3*atanh(sin(c + d*x))/(2*a**2*d) - 2*I*sec(c + d*x)/(a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**4/(I*a*sin(c + d*x) + a*cos(c + d*x))**2,
        variable=x,
        num_steps=3,
        integral=-I*(-cot(c + d*x) + I)**3*tan(c + d*x)**3/(3*a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**5/(I*a*sin(c + d*x) + a*cos(c + d*x))**2,
        variable=x,
        num_steps=10,
        integral=-tan(c + d*x)*sec(c + d*x)**3/(4*a**2*d) + 5*tan(c + d*x)*sec(c + d*x)/(8*a**2*d) + 5*atanh(sin(c + d*x))/(8*a**2*d) - 2*I*sec(c + d*x)**3/(3*a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**6/(I*a*sin(c + d*x) + a*cos(c + d*x))**2,
        variable=x,
        num_steps=4,
        integral=-tan(c + d*x)**5/(5*a**2*d) - I*tan(c + d*x)**4/(2*a**2*d) - I*tan(c + d*x)**2/(a**2*d) + tan(c + d*x)/(a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**5/(I*a*sin(c + d*x) + a*cos(c + d*x))**3,
        variable=x,
        num_steps=5,
        integral=5*x/(32*a**3) + 13/(16*a**3*d*(cot(c + d*x) + I)) - 23*I/(32*a**3*d*(cot(c + d*x) + I)**2) - 1/(3*a**3*d*(cot(c + d*x) + I)**3) + I/(16*a**3*d*(cot(c + d*x) + I)**4) - 1/(32*a**3*d*(-cot(c + d*x) + I)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**4/(I*a*sin(c + d*x) + a*cos(c + d*x))**3,
        variable=x,
        num_steps=13,
        integral=-4*sin(c + d*x)**7/(7*a**3*d) + 9*sin(c + d*x)**5/(5*a**3*d) - 2*sin(c + d*x)**3/(a**3*d) + sin(c + d*x)/(a**3*d) + 4*I*cos(c + d*x)**7/(7*a**3*d) - I*cos(c + d*x)**5/(5*a**3*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/(I*a*sin(c + d*x) + a*cos(c + d*x))**3,
        variable=x,
        num_steps=4,
        integral=I*cos(c + d*x)/(8*d*(I*a**3*sin(c + d*x) + a**3*cos(c + d*x))) + I*cos(c + d*x)**3/(6*d*(I*a*sin(c + d*x) + a*cos(c + d*x))**3) + I*cos(c + d*x)**2/(8*a*d*(I*a*sin(c + d*x) + a*cos(c + d*x))**2) + x/(8*a**3),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(I*a*sin(c + d*x) + a*cos(c + d*x))**3,
        variable=x,
        num_steps=13,
        integral=4*sin(c + d*x)**5/(5*a**3*d) - 5*sin(c + d*x)**3/(3*a**3*d) + sin(c + d*x)/(a**3*d) + 4*I*cos(c + d*x)**5/(5*a**3*d) - I*cos(c + d*x)**3/(3*a**3*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(I*a*sin(c + d*x) + a*cos(c + d*x))**3,
        variable=x,
        num_steps=2,
        integral=I*cot(c + d*x)**2/(2*a**3*d*(cot(c + d*x) + I)**2),
    ),
    RubiTestSuiteCase(
        integrand=(I*a*sin(c + d*x) + a*cos(c + d*x))**(-3),
        variable=x,
        num_steps=1,
        integral=I/(3*d*(I*a*sin(c + d*x) + a*cos(c + d*x))**3),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(I*a*sin(c + d*x) + a*cos(c + d*x))**3,
        variable=x,
        num_steps=4,
        integral=-x/a**3 - I*log(sin(c + d*x))/(a**3*d) + I*log(tan(c + d*x))/(a**3*d) + 2/(a**3*d*(cot(c + d*x) + I)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(I*a*sin(c + d*x) + a*cos(c + d*x))**3,
        variable=x,
        num_steps=11,
        integral=4*sin(c + d*x)/(a**3*d) + 4*I*cos(c + d*x)/(a**3*d) - 3*atanh(sin(c + d*x))/(a**3*d) + I*sec(c + d*x)/(a**3*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(I*a*sin(c + d*x) + a*cos(c + d*x))**3,
        variable=x,
        num_steps=4,
        integral=4*x/a**3 + 4*I*log(sin(c + d*x))/(a**3*d) - 4*I*log(tan(c + d*x))/(a**3*d) + I*tan(c + d*x)**2/(2*a**3*d) - 3*tan(c + d*x)/(a**3*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**4/(I*a*sin(c + d*x) + a*cos(c + d*x))**3,
        variable=x,
        num_steps=10,
        integral=-3*tan(c + d*x)*sec(c + d*x)/(2*a**3*d) + 5*atanh(sin(c + d*x))/(2*a**3*d) + I*sec(c + d*x)**3/(3*a**3*d) - 4*I*sec(c + d*x)/(a**3*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**5/(I*a*sin(c + d*x) + a*cos(c + d*x))**3,
        variable=x,
        num_steps=3,
        integral=I*(-cot(c + d*x) + I)**4*tan(c + d*x)**4/(4*a**3*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**6/(I*a*sin(c + d*x) + a*cos(c + d*x))**3,
        variable=x,
        num_steps=13,
        integral=-3*tan(c + d*x)*sec(c + d*x)**3/(4*a**3*d) + 7*tan(c + d*x)*sec(c + d*x)/(8*a**3*d) + 7*atanh(sin(c + d*x))/(8*a**3*d) + I*sec(c + d*x)**5/(5*a**3*d) - 4*I*sec(c + d*x)**3/(3*a**3*d),
    ),
    RubiTestSuiteCase(
        integrand=(I*a*sin(c + d*x) + a*cos(c + d*x))**n/cos(c + d*x)**n,
        variable=x,
        num_steps=1,
        integral=-I*(I*a*sin(c + d*x) + a*cos(c + d*x))**n*hyper((1, n), (n + 1,), I*tan(c + d*x)/2 + sympy.S.Half)/(2*d*n*cos(c + d*x)**n),
    ),
    RubiTestSuiteCase(
        integrand=1/(tan(x) + sec(x)),
        variable=x,
        num_steps=3,
        integral=log(sin(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/(tan(x) + sec(x)),
        variable=x,
        num_steps=4,
        integral=-log(sin(x) + 1) + sin(x),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)/(tan(x) + sec(x)),
        variable=x,
        num_steps=3,
        integral=x + cos(x),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)/(tan(x) + sec(x)),
        variable=x,
        num_steps=3,
        integral=x + cos(x)/(sin(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=cot(x)/(tan(x) + sec(x)),
        variable=x,
        num_steps=4,
        integral=-x - atanh(cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)/(tan(x) + sec(x)),
        variable=x,
        num_steps=2,
        integral=-cos(x)/(sin(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)/(tan(x) + sec(x)),
        variable=x,
        num_steps=5,
        integral=-log(sin(x) + 1) + log(sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(-tan(x) + sec(x)),
        variable=x,
        num_steps=3,
        integral=-log(1 - sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/(-tan(x) + sec(x)),
        variable=x,
        num_steps=4,
        integral=-log(1 - sin(x)) - sin(x),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)/(-tan(x) + sec(x)),
        variable=x,
        num_steps=3,
        integral=x - cos(x),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)/(-tan(x) + sec(x)),
        variable=x,
        num_steps=3,
        integral=-x + cos(x)/(1 - sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=cot(x)/(-tan(x) + sec(x)),
        variable=x,
        num_steps=4,
        integral=x - atanh(cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)/(-tan(x) + sec(x)),
        variable=x,
        num_steps=2,
        integral=cos(x)/(1 - sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)/(-tan(x) + sec(x)),
        variable=x,
        num_steps=5,
        integral=-log(1 - sin(x)) + log(sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=(cot(c + d*x) + csc(c + d*x))*csc(c + d*x),
        variable=x,
        num_steps=4,
        integral=-cot(c + d*x)/d - csc(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/(cot(x) + csc(x)),
        variable=x,
        num_steps=3,
        integral=x - sin(x),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)/(cot(x) + csc(x)),
        variable=x,
        num_steps=4,
        integral=log(cos(x) + 1) - cos(x),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)/(cot(x) + csc(x)),
        variable=x,
        num_steps=4,
        integral=-x + atanh(sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=cot(x)/(cot(x) + csc(x)),
        variable=x,
        num_steps=3,
        integral=x - sin(x)/(cos(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)/(cot(x) + csc(x)),
        variable=x,
        num_steps=5,
        integral=log(cos(x) + 1) - log(cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)/(cot(x) + csc(x)),
        variable=x,
        num_steps=2,
        integral=sin(x)/(cos(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/(-cot(x) + csc(x)),
        variable=x,
        num_steps=3,
        integral=x + sin(x),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)/(-cot(x) + csc(x)),
        variable=x,
        num_steps=4,
        integral=log(1 - cos(x)) + cos(x),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)/(-cot(x) + csc(x)),
        variable=x,
        num_steps=4,
        integral=x + atanh(sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=cot(x)/(-cot(x) + csc(x)),
        variable=x,
        num_steps=3,
        integral=-x - sin(x)/(1 - cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)/(-cot(x) + csc(x)),
        variable=x,
        num_steps=5,
        integral=log(1 - cos(x)) - log(cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)/(-cot(x) + csc(x)),
        variable=x,
        num_steps=2,
        integral=-sin(x)/(1 - cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(sin(c + d*x) + csc(c + d*x)),
        variable=x,
        num_steps=3,
        integral=-sqrt(2)*atanh(sqrt(2)*cos(c + d*x)/2)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=sin(c + d*x)/(sin(c + d*x) + csc(c + d*x)),
        variable=x,
        num_steps=4,
        integral=-sqrt(2)*x/2 + x - sqrt(2)*atan(sin(c + d*x)*cos(c + d*x)/(sin(c + d*x)**2 + 1 + sqrt(2)))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(sin(c + d*x) + csc(c + d*x)),
        variable=x,
        num_steps=2,
        integral=log(sin(c + d*x)**2 + 1)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=tan(c + d*x)/(sin(c + d*x) + csc(c + d*x)),
        variable=x,
        num_steps=4,
        integral=-atan(sin(c + d*x))/(2*d) + atanh(sin(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=cot(c + d*x)/(sin(c + d*x) + csc(c + d*x)),
        variable=x,
        num_steps=2,
        integral=atan(sin(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(sin(c + d*x) + csc(c + d*x)),
        variable=x,
        num_steps=3,
        integral=atanh(sin(c + d*x)**2)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=csc(c + d*x)/(sin(c + d*x) + csc(c + d*x)),
        variable=x,
        num_steps=2,
        integral=sqrt(2)*x/2 + sqrt(2)*atan(sin(c + d*x)*cos(c + d*x)/(sin(c + d*x)**2 + 1 + sqrt(2)))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=1/(-sin(c + d*x) + csc(c + d*x)),
        variable=x,
        num_steps=3,
        integral=sec(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=sin(c + d*x)/(-sin(c + d*x) + csc(c + d*x)),
        variable=x,
        num_steps=3,
        integral=-x + tan(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(-sin(c + d*x) + csc(c + d*x)),
        variable=x,
        num_steps=2,
        integral=-log(cos(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=tan(c + d*x)/(-sin(c + d*x) + csc(c + d*x)),
        variable=x,
        num_steps=3,
        integral=tan(c + d*x)*sec(c + d*x)/(2*d) - atanh(sin(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=cot(c + d*x)/(-sin(c + d*x) + csc(c + d*x)),
        variable=x,
        num_steps=2,
        integral=atanh(sin(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(-sin(c + d*x) + csc(c + d*x)),
        variable=x,
        num_steps=2,
        integral=sec(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=csc(c + d*x)/(-sin(c + d*x) + csc(c + d*x)),
        variable=x,
        num_steps=2,
        integral=tan(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))*cos(c + d*x)**3,
        variable=x,
        num_steps=6,
        integral=-a*cos(c + d*x)**4/(4*d) - b*cos(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))*cos(c + d*x)**2,
        variable=x,
        num_steps=6,
        integral=-a*cos(c + d*x)**3/(3*d) + b*sin(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=a*sin(c + d*x) + b*tan(c + d*x),
        variable=x,
        num_steps=3,
        integral=-a*cos(c + d*x)/d - b*log(cos(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))*sec(c + d*x),
        variable=x,
        num_steps=5,
        integral=-a*log(cos(c + d*x))/d + b*sec(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))*sec(c + d*x)**2,
        variable=x,
        num_steps=6,
        integral=a*sec(c + d*x)/d + b*sec(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))*sec(c + d*x)**3,
        variable=x,
        num_steps=6,
        integral=a*sec(c + d*x)**2/(2*d) + b*sec(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**2*cos(c + d*x)**3,
        variable=x,
        num_steps=6,
        integral=a*b*x/4 - a*b*sin(c + d*x)*cos(c + d*x)/(4*d) + b*(a*cos(c + d*x) + b)*sin(c + d*x)**3/(10*d) + (4*a**2 + b**2)*sin(c + d*x)**3/(30*d) + (a*cos(c + d*x) + b)**2*sin(c + d*x)**3/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**2*cos(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=5*a*b*sin(c + d*x)**3/(12*d) + a*(a*cos(c + d*x) + b)*sin(c + d*x)**3/(4*d) + x*(a**2/8 + b**2/2) - (a**2 + 4*b**2)*sin(c + d*x)*cos(c + d*x)/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**2*cos(c + d*x),
        variable=x,
        num_steps=7,
        integral=a*b*x - a*b*sin(c + d*x)*cos(c + d*x)/(3*d) + b**2*atanh(sin(c + d*x))/d + (a**2 - 2*b**2)*sin(c + d*x)/(3*d) - (a*cos(c + d*x) + b)**2*sin(c + d*x)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**2,
        variable=x,
        num_steps=10,
        integral=a**2*x/2 - a**2*sin(c + d*x)*cos(c + d*x)/(2*d) - 2*a*b*sin(c + d*x)/d + 2*a*b*atanh(sin(c + d*x))/d - b**2*x + b**2*tan(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**2*sec(c + d*x),
        variable=x,
        num_steps=7,
        integral=-3*a**2*sin(c + d*x)/(2*d) - 2*a*b*x + a*b*tan(c + d*x)/d + (2*a**2 - b**2)*atanh(sin(c + d*x))/(2*d) + (a*cos(c + d*x) + b)**2*tan(c + d*x)*sec(c + d*x)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**2*sec(c + d*x)**2,
        variable=x,
        num_steps=7,
        integral=-a**2*x + a*b*tan(c + d*x)*sec(c + d*x)/(3*d) - a*b*atanh(sin(c + d*x))/d + (2*a**2 - b**2)*tan(c + d*x)/(3*d) + (a*cos(c + d*x) + b)**2*tan(c + d*x)*sec(c + d*x)**2/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**2*sec(c + d*x)**3,
        variable=x,
        num_steps=9,
        integral=a*b*tan(c + d*x)*sec(c + d*x)**2/(6*d) - 2*a*b*tan(c + d*x)/(3*d) + (2*a**2 - b**2)*tan(c + d*x)*sec(c + d*x)/(8*d) - (4*a**2 + b**2)*atanh(sin(c + d*x))/(8*d) + (a*cos(c + d*x) + b)**2*tan(c + d*x)*sec(c + d*x)**3/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**3*cos(c + d*x)**3,
        variable=x,
        num_steps=4,
        integral=-2*b*(a*cos(c + d*x) + b)**5/(5*a**3*d) - (a**2 - b**2)*(a*cos(c + d*x) + b)**4/(4*a**3*d) + (a*cos(c + d*x) + b)**6/(6*a**3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**3*cos(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=a**3*cos(c + d*x)**5/(5*d) + 3*a**2*b*cos(c + d*x)**4/(4*d) - 3*a*b**2*cos(c + d*x)/d - a*(a**2 - 3*b**2)*cos(c + d*x)**3/(3*d) - b**3*log(cos(c + d*x))/d - b*(3*a**2 - b**2)*cos(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**3*cos(c + d*x),
        variable=x,
        num_steps=5,
        integral=a**3*cos(c + d*x)**4/(4*d) + a**2*b*cos(c + d*x)**3/d - 3*a*b**2*log(cos(c + d*x))/d - a*(a**2 - 3*b**2)*cos(c + d*x)**2/(2*d) + b**3*sec(c + d*x)/d - b*(3*a**2 - b**2)*cos(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**3,
        variable=x,
        num_steps=4,
        integral=a**3*cos(c + d*x)**3/(3*d) + 3*a**2*b*cos(c + d*x)**2/(2*d) + 3*a*b**2*sec(c + d*x)/d - a*(a**2 - 3*b**2)*cos(c + d*x)/d + b**3*sec(c + d*x)**2/(2*d) - b*(3*a**2 - b**2)*log(cos(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**3*sec(c + d*x),
        variable=x,
        num_steps=5,
        integral=a**3*cos(c + d*x)**2/(2*d) + 3*a**2*b*cos(c + d*x)/d + 3*a*b**2*sec(c + d*x)**2/(2*d) - a*(a**2 - 3*b**2)*log(cos(c + d*x))/d + b**3*sec(c + d*x)**3/(3*d) + b*(3*a**2 - b**2)*sec(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**3*sec(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=a**3*cos(c + d*x)/d + 3*a**2*b*log(cos(c + d*x))/d + a*b**2*sec(c + d*x)**3/d + a*(a**2 - 3*b**2)*sec(c + d*x)/d + b**3*sec(c + d*x)**4/(4*d) + b*(3*a**2 - b**2)*sec(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**3*sec(c + d*x)**3,
        variable=x,
        num_steps=5,
        integral=a**3*log(cos(c + d*x))/d - 3*a**2*b*sec(c + d*x)/d + 3*a*b**2*sec(c + d*x)**4/(4*d) + a*(a**2 - 3*b**2)*sec(c + d*x)**2/(2*d) + b**3*sec(c + d*x)**5/(5*d) + b*(3*a**2 - b**2)*sec(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/(a*sin(c + d*x) + b*tan(c + d*x)),
        variable=x,
        num_steps=5,
        integral=log(1 - cos(c + d*x))/(d*(2*a + 2*b)) + log(cos(c + d*x) + 1)/(d*(2*a - 2*b)) + cos(c + d*x)**2/(2*a*d) - b*cos(c + d*x)/(a**2*d) - b**4*log(a*cos(c + d*x) + b)/(a**3*d*(a**2 - b**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(a*sin(c + d*x) + b*tan(c + d*x)),
        variable=x,
        num_steps=5,
        integral=log(1 - cos(c + d*x))/(d*(2*a + 2*b)) - log(cos(c + d*x) + 1)/(d*(2*a - 2*b)) + cos(c + d*x)/(a*d) + b**3*log(a*cos(c + d*x) + b)/(a**2*d*(a**2 - b**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(a*sin(c + d*x) + b*tan(c + d*x)),
        variable=x,
        num_steps=5,
        integral=log(1 - cos(c + d*x))/(d*(2*a + 2*b)) + log(cos(c + d*x) + 1)/(d*(2*a - 2*b)) - b**2*log(a*cos(c + d*x) + b)/(a*d*(a**2 - b**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(a*sin(c + d*x) + b*tan(c + d*x)),
        variable=x,
        num_steps=4,
        integral=b*log(a*cos(c + d*x) + b)/(d*(a**2 - b**2)) + log(1 - cos(c + d*x))/(d*(2*a + 2*b)) - log(cos(c + d*x) + 1)/(d*(2*a - 2*b)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(a*sin(c + d*x) + b*tan(c + d*x)),
        variable=x,
        num_steps=7,
        integral=-a*log(a*cos(c + d*x) + b)/(d*(a**2 - b**2)) + log(1 - cos(c + d*x))/(d*(2*a + 2*b)) + log(cos(c + d*x) + 1)/(d*(2*a - 2*b)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(a*sin(c + d*x) + b*tan(c + d*x)),
        variable=x,
        num_steps=5,
        integral=a**2*log(a*cos(c + d*x) + b)/(b*d*(a**2 - b**2)) + log(1 - cos(c + d*x))/(d*(2*a + 2*b)) - log(cos(c + d*x) + 1)/(d*(2*a - 2*b)) - log(cos(c + d*x))/(b*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(a*sin(c + d*x) + b*tan(c + d*x)),
        variable=x,
        num_steps=5,
        integral=-a**3*log(a*cos(c + d*x) + b)/(b**2*d*(a**2 - b**2)) + a*log(cos(c + d*x))/(b**2*d) + log(1 - cos(c + d*x))/(d*(2*a + 2*b)) + log(cos(c + d*x) + 1)/(d*(2*a - 2*b)) + sec(c + d*x)/(b*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/(a*sin(c + d*x) + b*tan(c + d*x))**2,
        variable=x,
        num_steps=12,
        integral=-sin(c + d*x)/(2*d*(a - b)**2*(cos(c + d*x) + 1)) - sin(c + d*x)/(2*d*(1 - cos(c + d*x))*(a + b)**2) - b**5*sin(c + d*x)/(a**2*d*(a**2 - b**2)**2*(a*cos(c + d*x) + b)) - sin(c + d*x)/(a**2*d) + 2*b**6*atanh(sqrt(a - b)*tan(c/2 + d*x/2)/sqrt(a + b))/(a**3*d*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)) + 2*b**4*(5*a**2 - 3*b**2)*atanh(sqrt(a - b)*tan(c/2 + d*x/2)/sqrt(a + b))/(a**3*d*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)) + 2*b*x/a**3,
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(a*sin(c + d*x) + b*tan(c + d*x))**2,
        variable=x,
        num_steps=11,
        integral=sin(c + d*x)/(2*d*(a - b)**2*(cos(c + d*x) + 1)) - sin(c + d*x)/(2*d*(1 - cos(c + d*x))*(a + b)**2) + b**4*sin(c + d*x)/(a*d*(a**2 - b**2)**2*(a*cos(c + d*x) + b)) - 2*b**5*atanh(sqrt(a - b)*tan(c/2 + d*x/2)/sqrt(a + b))/(a**2*d*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)) - 4*b**3*(2*a**2 - b**2)*atanh(sqrt(a - b)*tan(c/2 + d*x/2)/sqrt(a + b))/(a**2*d*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)) - x/a**2,
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(a*sin(c + d*x) + b*tan(c + d*x))**2,
        variable=x,
        num_steps=11,
        integral=-b**3*sin(c + d*x)/(d*(a**2 - b**2)**2*(a*cos(c + d*x) + b)) - sin(c + d*x)/(2*d*(a - b)**2*(cos(c + d*x) + 1)) - sin(c + d*x)/(2*d*(1 - cos(c + d*x))*(a + b)**2) + 2*b**4*atanh(sqrt(a - b)*tan(c/2 + d*x/2)/sqrt(a + b))/(a*d*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)) + 2*b**2*(3*a**2 - b**2)*atanh(sqrt(a - b)*tan(c/2 + d*x/2)/sqrt(a + b))/(a*d*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**(-2),
        variable=x,
        num_steps=11,
        integral=-4*a**2*b*atanh(sqrt(a - b)*tan(c/2 + d*x/2)/sqrt(a + b))/(d*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)) + a*b**2*sin(c + d*x)/(d*(a**2 - b**2)**2*(a*cos(c + d*x) + b)) - 2*b**3*atanh(sqrt(a - b)*tan(c/2 + d*x/2)/sqrt(a + b))/(d*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)) + sin(c + d*x)/(2*d*(a - b)**2*(cos(c + d*x) + 1)) - sin(c + d*x)/(2*d*(1 - cos(c + d*x))*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(a*sin(c + d*x) + b*tan(c + d*x))**2,
        variable=x,
        num_steps=6,
        integral=2*a*(a**2 + 2*b**2)*atanh(sqrt(a - b)*tan(c/2 + d*x/2)/sqrt(a + b))/(d*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)) - b*csc(c + d*x)/(d*(a**2 - b**2)*(a*cos(c + d*x) + b)) - (a**2 - 3*a*b*cos(c + d*x) + 2*b**2)*csc(c + d*x)/(d*(a**2 - b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(a*sin(c + d*x) + b*tan(c + d*x))**2,
        variable=x,
        num_steps=6,
        integral=-6*a**2*b*atanh(sqrt(a - b)*tan(c/2 + d*x/2)/sqrt(a + b))/(d*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)) + a*csc(c + d*x)/(d*(a**2 - b**2)*(a*cos(c + d*x) + b)) + (3*a*b - (2*a**2 + b**2)*cos(c + d*x))*csc(c + d*x)/(d*(a**2 - b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(a*sin(c + d*x) + b*tan(c + d*x))**2,
        variable=x,
        num_steps=12,
        integral=-a**4*sin(c + d*x)/(b*d*(a**2 - b**2)**2*(a*cos(c + d*x) + b)) + 2*a**3*atanh(sqrt(a - b)*tan(c/2 + d*x/2)/sqrt(a + b))/(d*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)) - 2*a**3*(a**2 - 3*b**2)*atanh(sqrt(a - b)*tan(c/2 + d*x/2)/sqrt(a + b))/(b**2*d*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)) - sin(c + d*x)/(2*d*(a - b)**2*(cos(c + d*x) + 1)) - sin(c + d*x)/(2*d*(1 - cos(c + d*x))*(a + b)**2) + atanh(sin(c + d*x))/(b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/(a*sin(c + d*x) + b*tan(c + d*x))**3,
        variable=x,
        num_steps=6,
        integral=-(a*(a**2 + 3*b**2) - b*(3*a**2 + b**2)*cos(c + d*x))*csc(c + d*x)**2/(2*d*(a**2 - b**2)**3) - (2*a + 5*b)*log(1 - cos(c + d*x))/(4*d*(a + b)**4) - (2*a - 5*b)*log(cos(c + d*x) + 1)/(4*d*(a - b)**4) + b**6/(2*a**3*d*(a**2 - b**2)**2*(a*cos(c + d*x) + b)**2) - 2*b**5*(3*a**2 - b**2)/(a**3*d*(a**2 - b**2)**3*(a*cos(c + d*x) + b)) - b**4*(15*a**4 - 4*a**2*b**2 + b**4)*log(a*cos(c + d*x) + b)/(a**3*d*(a**2 - b**2)**4),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(a*sin(c + d*x) + b*tan(c + d*x))**3,
        variable=x,
        num_steps=6,
        integral=2*b**3*(5*a**2 + b**2)*log(a*cos(c + d*x) + b)/(d*(a**2 - b**2)**4) + (a - 4*b)*log(cos(c + d*x) + 1)/(4*d*(a - b)**4) + (-a*(a**2 + 3*b**2)*cos(c + d*x) + b*(3*a**2 + b**2))*csc(c + d*x)**2/(2*d*(a**2 - b**2)**3) - (a + 4*b)*log(1 - cos(c + d*x))/(4*d*(a + b)**4) - b**5/(2*a**2*d*(a**2 - b**2)**2*(a*cos(c + d*x) + b)**2) + b**4*(5*a**2 - b**2)/(a**2*d*(a**2 - b**2)**3*(a*cos(c + d*x) + b)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(a*sin(c + d*x) + b*tan(c + d*x))**3,
        variable=x,
        num_steps=6,
        integral=-4*a*b**3/(d*(a**2 - b**2)**3*(a*cos(c + d*x) + b)) - 6*a*b**2*(a**2 + b**2)*log(a*cos(c + d*x) + b)/(d*(a**2 - b**2)**4) - 3*b*log(1 - cos(c + d*x))/(4*d*(a + b)**4) + 3*b*log(cos(c + d*x) + 1)/(4*d*(a - b)**4) - (a*(a**2 + 3*b**2) - b*(3*a**2 + b**2)*cos(c + d*x))*csc(c + d*x)**2/(2*d*(a**2 - b**2)**3) + b**4/(2*a*d*(a**2 - b**2)**2*(a*cos(c + d*x) + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**(-3),
        variable=x,
        num_steps=5,
        integral=-b**3/(2*d*(a**2 - b**2)**2*(a*cos(c + d*x) + b)**2) + b**2*(3*a**2 + b**2)/(d*(a**2 - b**2)**3*(a*cos(c + d*x) + b)) + b*(3*a**4 + 8*a**2*b**2 + b**4)*log(a*cos(c + d*x) + b)/(d*(a**2 - b**2)**4) + (a - 2*b)*log(1 - cos(c + d*x))/(4*d*(a + b)**4) + (-a*(a**2 + 3*b**2)*cos(c + d*x) + b*(3*a**2 + b**2))*csc(c + d*x)**2/(2*d*(a**2 - b**2)**3) - (a + 2*b)*log(cos(c + d*x) + 1)/(4*d*(a - b)**4),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(a*sin(c + d*x) + b*tan(c + d*x))**3,
        variable=x,
        num_steps=6,
        integral=a*b**2/(2*d*(a**2 - b**2)**2*(a*cos(c + d*x) + b)**2) - 2*a*b*(a**2 + b**2)/(d*(a**2 - b**2)**3*(a*cos(c + d*x) + b)) - a*(a**4 + 8*a**2*b**2 + 3*b**4)*log(a*cos(c + d*x) + b)/(d*(a**2 - b**2)**4) - (a*(a**2 + 3*b**2) - b*(3*a**2 + b**2)*cos(c + d*x))*csc(c + d*x)**2/(2*d*(a**2 - b**2)**3) + (2*a - b)*log(1 - cos(c + d*x))/(4*d*(a + b)**4) + (2*a + b)*log(cos(c + d*x) + 1)/(4*d*(a - b)**4),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(a*sin(c + d*x) + b*tan(c + d*x))**3,
        variable=x,
        num_steps=6,
        integral=-3*a**2*b/(2*d*(a**2 - b**2)**2*(a*cos(c + d*x) + b)**2) + 6*a**2*b*(a**2 + b**2)*log(a*cos(c + d*x) + b)/(d*(a**2 - b**2)**4) + 3*a**2*(a**2 + 3*b**2)/(2*d*(a**2 - b**2)**3*(a*cos(c + d*x) + b)) + 3*a*log(1 - cos(c + d*x))/(4*d*(a + b)**4) - 3*a*log(cos(c + d*x) + 1)/(4*d*(a - b)**4) + (-a*cos(c + d*x) + b)*csc(c + d*x)**2/(d*(2*a**2 - 2*b**2)*(a*cos(c + d*x) + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(a*sin(c + d*x) + b*tan(c + d*x))**3,
        variable=x,
        num_steps=5,
        integral=-2*a**3*(a**2 + 5*b**2)*log(a*cos(c + d*x) + b)/(d*(a**2 - b**2)**4) - a*b*(11*a**2 + b**2)/(2*d*(a**2 - b**2)**3*(a*cos(c + d*x) + b)) + a*(2*a**2 + b**2)/(2*d*(a**2 - b**2)**2*(a*cos(c + d*x) + b)**2) - (a - b*cos(c + d*x))*csc(c + d*x)**2/(d*(2*a**2 - 2*b**2)*(a*cos(c + d*x) + b)**2) + (4*a + b)*log(1 - cos(c + d*x))/(4*d*(a + b)**4) + (4*a - b)*log(cos(c + d*x) + 1)/(4*d*(a - b)**4),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**3*cos(c + d*x)**m,
        variable=x,
        num_steps=4,
        integral=a**3*cos(c + d*x)**(m + 3)/(d*(m + 3)) + 3*a**2*b*cos(c + d*x)**(m + 2)/(d*(m + 2)) + 3*a*b**2*cos(c + d*x)**(m - 1)/(d*(1 - m)) - a*(a**2 - 3*b**2)*cos(c + d*x)**(m + 1)/(d*(m + 1)) + b**3*cos(c + d*x)**(m - 2)/(d*(2 - m)) - b*(3*a**2 - b**2)*cos(c + d*x)**m/(d*m),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))**2*cos(c + d*x)**m,
        variable=x,
        num_steps=8,
        integral=-2*a*b*sin(c + d*x)*cos(c + d*x)**m/(d*(m**2 + 3*m + 2)) - 2*a*b*sin(c + d*x)*cos(c + d*x)**m*hyper((sympy.S.Half, m/2), (m/2 + 1,), cos(c + d*x)**2)/(d*m*(m + 1)*sqrt(sin(c + d*x)**2)) - (a*cos(c + d*x) + b)**2*sin(c + d*x)*cos(c + d*x)**(m - 1)/(d*(m + 2)) + (a**2 - 2*b**2)*sin(c + d*x)*cos(c + d*x)**(m - 1)/(d*m*(m + 2)) - (a**2*(1 - m) - b**2*(m + 2))*sin(c + d*x)*cos(c + d*x)**(m - 1)*hyper((sympy.S.Half, m/2 + sympy.S(-1)/2), (m/2 + sympy.S.Half,), cos(c + d*x)**2)/(d*m*(1 - m)*(m + 2)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(c + d*x) + b*tan(c + d*x))*cos(c + d*x)**m,
        variable=x,
        num_steps=6,
        integral=-a*cos(c + d*x)**(m + 1)/(d*(m + 1)) - b*cos(c + d*x)**m/(d*m),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**m/(a*sin(c + d*x) + b*tan(c + d*x)),
        variable=x,
        num_steps=7,
        integral=-a**2*cos(c + d*x)**(m + 2)*hyper((1, m + 2), (m + 3,), -a*cos(c + d*x)/b)/(b*d*(a**2 - b**2)*(m + 2)) - cos(c + d*x)**(m + 2)*hyper((1, m + 2), (m + 3,), cos(c + d*x))/(d*(2*a + 2*b)*(m + 2)) + cos(c + d*x)**(m + 2)*hyper((1, m + 2), (m + 3,), -cos(c + d*x))/(d*(2*a - 2*b)*(m + 2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)*cos(x)/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=5,
        integral=a*b*atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/(a**2 + b**2)**(sympy.S(3)/2) - a*cos(x)/(a**2 + b**2) + b*sin(x)/(a**2 + b**2),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2*cos(x)/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=7,
        integral=a**2*b*log(a*cos(x) + b*sin(x))/(a**2 + b**2)**2 - a*b**2*x/(a**2 + b**2)**2 + a*x/(2*a**2 + 2*b**2) - a*sin(x)*cos(x)/(2*a**2 + 2*b**2) + b*sin(x)**2/(2*a**2 + 2*b**2),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3*cos(x)/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=9,
        integral=a**3*b*atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/(a**2 + b**2)**(sympy.S(5)/2) + a**2*b*sin(x)/(a**2 + b**2)**2 + a*b**2*cos(x)/(a**2 + b**2)**2 + a*cos(x)**3/(3*a**2 + 3*b**2) - a*cos(x)/(a**2 + b**2) + b*sin(x)**3/(3*a**2 + 3*b**2),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)*cos(x)**2/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=7,
        integral=-a**2*b*x/(a**2 + b**2)**2 - a*b**2*log(a*cos(x) + b*sin(x))/(a**2 + b**2)**2 + a*sin(x)**2/(2*a**2 + 2*b**2) + b*x/(2*a**2 + 2*b**2) + b*sin(x)*cos(x)/(2*a**2 + 2*b**2),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2*cos(x)**2/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=10,
        integral=-a**2*b**2*atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/(a**2 + b**2)**(sympy.S(5)/2) + a**2*b*cos(x)/(a**2 + b**2)**2 - a*b**2*sin(x)/(a**2 + b**2)**2 + a*sin(x)**3/(3*a**2 + 3*b**2) - b*cos(x)**3/(3*a**2 + 3*b**2),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3*cos(x)**2/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=13,
        integral=-a**3*b**2*log(a*cos(x) + b*sin(x))/(a**2 + b**2)**3 + a**2*b**3*x/(a**2 + b**2)**3 - a**2*b*x/(2*(a**2 + b**2)**2) + a**2*b*sin(x)*cos(x)/(2*(a**2 + b**2)**2) - a*b**2*sin(x)**2/(2*(a**2 + b**2)**2) + a*sin(x)**4/(4*a**2 + 4*b**2) + b*x/(8*a**2 + 8*b**2) + b*sin(x)*cos(x)/(8*a**2 + 8*b**2) - b*sin(x)*cos(x)**3/(4*a**2 + 4*b**2),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)*cos(x)**3/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=9,
        integral=-a**2*b*sin(x)/(a**2 + b**2)**2 + a*b**3*atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/(a**2 + b**2)**(sympy.S(5)/2) - a*b**2*cos(x)/(a**2 + b**2)**2 - a*cos(x)**3/(3*a**2 + 3*b**2) - b*sin(x)**3/(3*a**2 + 3*b**2) + b*sin(x)/(a**2 + b**2),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2*cos(x)**3/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=13,
        integral=a**3*b**2*x/(a**2 + b**2)**3 + a**2*b**3*log(a*cos(x) + b*sin(x))/(a**2 + b**2)**3 - a**2*b*sin(x)**2/(2*(a**2 + b**2)**2) - a*b**2*x/(2*(a**2 + b**2)**2) - a*b**2*sin(x)*cos(x)/(2*(a**2 + b**2)**2) + a*x/(8*a**2 + 8*b**2) + a*sin(x)*cos(x)/(8*a**2 + 8*b**2) - a*sin(x)*cos(x)**3/(4*a**2 + 4*b**2) - b*cos(x)**4/(4*a**2 + 4*b**2),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3*cos(x)**3/(a*cos(x) + b*sin(x)),
        variable=x,
        num_steps=17,
        integral=a**3*b**3*atanh((-a*sin(x) + b*cos(x))/sqrt(a**2 + b**2))/(a**2 + b**2)**(sympy.S(7)/2) - a**3*b**2*cos(x)/(a**2 + b**2)**3 + a**2*b**3*sin(x)/(a**2 + b**2)**3 - a**2*b*sin(x)**3/(3*(a**2 + b**2)**2) + a*b**2*cos(x)**3/(3*(a**2 + b**2)**2) + a*cos(x)**5/(5*a**2 + 5*b**2) - a*cos(x)**3/(3*a**2 + 3*b**2) - b*sin(x)**5/(5*a**2 + 5*b**2) + b*sin(x)**3/(3*a**2 + 3*b**2),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)/(a*sin(x) + b*cos(x)),
        variable=x,
        num_steps=5,
        integral=b*atanh((a*cos(x) - b*sin(x))/sqrt(a**2 + b**2))/(a*sqrt(a**2 + b**2)) + atanh(sin(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=cot(x)/(a*sin(x) + b*cos(x)),
        variable=x,
        num_steps=5,
        integral=a*atanh((a*cos(x) - b*sin(x))/sqrt(a**2 + b**2))/(b*sqrt(a**2 + b**2)) - atanh(cos(x))/b,
    ),
]
