# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 4 Trig functions/4.7 Miscellaneous/4.7.1 (c trig)^m (d trig)^n.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '4 Trig functions/4.7 Miscellaneous/4.7.1 (c trig)^m (d trig)^n.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, c, d, m, n = symbols('a b c d m n')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sin(2*a + 2*b*x)**7,
        variable=x,
        num_steps=4,
        integral=-128*sin(a + b*x)**15/(15*b) + 384*sin(a + b*x)**13/(13*b) - 384*sin(a + b*x)**11/(11*b) + 128*sin(a + b*x)**9/(9*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sin(2*a + 2*b*x)**6,
        variable=x,
        num_steps=4,
        integral=64*cos(a + b*x)**13/(13*b) - 192*cos(a + b*x)**11/(11*b) + 64*cos(a + b*x)**9/(3*b) - 64*cos(a + b*x)**7/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sin(2*a + 2*b*x)**5,
        variable=x,
        num_steps=4,
        integral=32*sin(a + b*x)**11/(11*b) - 64*sin(a + b*x)**9/(9*b) + 32*sin(a + b*x)**7/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sin(2*a + 2*b*x)**4,
        variable=x,
        num_steps=4,
        integral=-16*cos(a + b*x)**9/(9*b) + 32*cos(a + b*x)**7/(7*b) - 16*cos(a + b*x)**5/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sin(2*a + 2*b*x)**3,
        variable=x,
        num_steps=4,
        integral=-8*sin(a + b*x)**7/(7*b) + 8*sin(a + b*x)**5/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sin(2*a + 2*b*x)**2,
        variable=x,
        num_steps=4,
        integral=4*cos(a + b*x)**5/(5*b) - 4*cos(a + b*x)**3/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sin(2*a + 2*b*x),
        variable=x,
        num_steps=1,
        integral=sin(a + b*x)/(2*b) - sin(3*a + 3*b*x)/(6*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*csc(2*a + 2*b*x),
        variable=x,
        num_steps=2,
        integral=atanh(sin(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*csc(2*a + 2*b*x)**2,
        variable=x,
        num_steps=4,
        integral=-atanh(cos(a + b*x))/(4*b) + sec(a + b*x)/(4*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*csc(2*a + 2*b*x)**3,
        variable=x,
        num_steps=5,
        integral=3*atanh(sin(a + b*x))/(16*b) + csc(a + b*x)*sec(a + b*x)**2/(16*b) - 3*csc(a + b*x)/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*csc(2*a + 2*b*x)**4,
        variable=x,
        num_steps=6,
        integral=-5*atanh(cos(a + b*x))/(32*b) - csc(a + b*x)**2*sec(a + b*x)**3/(32*b) + 5*sec(a + b*x)**3/(96*b) + 5*sec(a + b*x)/(32*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*csc(2*a + 2*b*x)**5,
        variable=x,
        num_steps=7,
        integral=35*atanh(sin(a + b*x))/(256*b) + csc(a + b*x)**3*sec(a + b*x)**4/(128*b) + 7*csc(a + b*x)**3*sec(a + b*x)**2/(256*b) - 35*csc(a + b*x)**3/(768*b) - 35*csc(a + b*x)/(256*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*sin(2*a + 2*b*x)**5,
        variable=x,
        num_steps=5,
        integral=8*sin(a + b*x)**12/(3*b) - 32*sin(a + b*x)**10/(5*b) + 4*sin(a + b*x)**8/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*sin(2*a + 2*b*x)**4,
        variable=x,
        num_steps=6,
        integral=3*x/16 - sin(2*a + 2*b*x)**5/(20*b) - sin(2*a + 2*b*x)**3*cos(2*a + 2*b*x)/(16*b) - 3*sin(2*a + 2*b*x)*cos(2*a + 2*b*x)/(32*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*sin(2*a + 2*b*x)**3,
        variable=x,
        num_steps=4,
        integral=-sin(a + b*x)**8/b + 4*sin(a + b*x)**6/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*sin(2*a + 2*b*x)**2,
        variable=x,
        num_steps=5,
        integral=x/4 - sin(2*a + 2*b*x)**3/(12*b) - sin(2*a + 2*b*x)*cos(2*a + 2*b*x)/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*sin(2*a + 2*b*x),
        variable=x,
        num_steps=3,
        integral=sin(a + b*x)**4/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*csc(2*a + 2*b*x),
        variable=x,
        num_steps=2,
        integral=-log(cos(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*csc(2*a + 2*b*x)**2,
        variable=x,
        num_steps=3,
        integral=tan(a + b*x)/(4*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*csc(2*a + 2*b*x)**3,
        variable=x,
        num_steps=4,
        integral=log(tan(a + b*x))/(8*b) + tan(a + b*x)**2/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*csc(2*a + 2*b*x)**4,
        variable=x,
        num_steps=4,
        integral=tan(a + b*x)**3/(48*b) + tan(a + b*x)/(8*b) - cot(a + b*x)/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*csc(2*a + 2*b*x)**5,
        variable=x,
        num_steps=5,
        integral=3*log(tan(a + b*x))/(32*b) + tan(a + b*x)**4/(128*b) + 3*tan(a + b*x)**2/(64*b) - cot(a + b*x)**2/(64*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*sin(2*a + 2*b*x)**5,
        variable=x,
        num_steps=4,
        integral=32*sin(a + b*x)**13/(13*b) - 64*sin(a + b*x)**11/(11*b) + 32*sin(a + b*x)**9/(9*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*sin(2*a + 2*b*x)**4,
        variable=x,
        num_steps=4,
        integral=16*cos(a + b*x)**11/(11*b) - 16*cos(a + b*x)**9/(3*b) + 48*cos(a + b*x)**7/(7*b) - 16*cos(a + b*x)**5/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*sin(2*a + 2*b*x)**3,
        variable=x,
        num_steps=4,
        integral=-8*sin(a + b*x)**9/(9*b) + 8*sin(a + b*x)**7/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*sin(2*a + 2*b*x)**2,
        variable=x,
        num_steps=4,
        integral=-4*cos(a + b*x)**7/(7*b) + 8*cos(a + b*x)**5/(5*b) - 4*cos(a + b*x)**3/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*sin(2*a + 2*b*x),
        variable=x,
        num_steps=3,
        integral=2*sin(a + b*x)**5/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*csc(2*a + 2*b*x),
        variable=x,
        num_steps=4,
        integral=-sin(a + b*x)/(2*b) + atanh(sin(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*csc(2*a + 2*b*x)**2,
        variable=x,
        num_steps=3,
        integral=sec(a + b*x)/(4*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*csc(2*a + 2*b*x)**3,
        variable=x,
        num_steps=3,
        integral=tan(a + b*x)*sec(a + b*x)/(16*b) + atanh(sin(a + b*x))/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*csc(2*a + 2*b*x)**4,
        variable=x,
        num_steps=5,
        integral=-atanh(cos(a + b*x))/(16*b) + sec(a + b*x)**3/(48*b) + sec(a + b*x)/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*csc(2*a + 2*b*x)**5,
        variable=x,
        num_steps=6,
        integral=15*atanh(sin(a + b*x))/(256*b) + csc(a + b*x)*sec(a + b*x)**4/(128*b) + 5*csc(a + b*x)*sec(a + b*x)**2/(256*b) - 15*csc(a + b*x)/(256*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**8*csc(a + b*x),
        variable=x,
        num_steps=4,
        integral=256*cos(a + b*x)**15/(15*b) - 768*cos(a + b*x)**13/(13*b) + 768*cos(a + b*x)**11/(11*b) - 256*cos(a + b*x)**9/(9*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**7*csc(a + b*x),
        variable=x,
        num_steps=4,
        integral=-128*sin(a + b*x)**13/(13*b) + 384*sin(a + b*x)**11/(11*b) - 128*sin(a + b*x)**9/(3*b) + 128*sin(a + b*x)**7/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**6*csc(a + b*x),
        variable=x,
        num_steps=4,
        integral=-64*cos(a + b*x)**11/(11*b) + 128*cos(a + b*x)**9/(9*b) - 64*cos(a + b*x)**7/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**5*csc(a + b*x),
        variable=x,
        num_steps=4,
        integral=32*sin(a + b*x)**9/(9*b) - 64*sin(a + b*x)**7/(7*b) + 32*sin(a + b*x)**5/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**4*csc(a + b*x),
        variable=x,
        num_steps=4,
        integral=16*cos(a + b*x)**7/(7*b) - 16*cos(a + b*x)**5/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**3*csc(a + b*x),
        variable=x,
        num_steps=4,
        integral=-8*sin(a + b*x)**5/(5*b) + 8*sin(a + b*x)**3/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**2*csc(a + b*x),
        variable=x,
        num_steps=3,
        integral=-4*cos(a + b*x)**3/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)*csc(a + b*x),
        variable=x,
        num_steps=2,
        integral=2*sin(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)*csc(2*a + 2*b*x),
        variable=x,
        num_steps=4,
        integral=atanh(sin(a + b*x))/(2*b) - csc(a + b*x)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)*csc(2*a + 2*b*x)**2,
        variable=x,
        num_steps=5,
        integral=-3*atanh(cos(a + b*x))/(8*b) - csc(a + b*x)**2*sec(a + b*x)/(8*b) + 3*sec(a + b*x)/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)*csc(2*a + 2*b*x)**3,
        variable=x,
        num_steps=6,
        integral=5*atanh(sin(a + b*x))/(16*b) + csc(a + b*x)**3*sec(a + b*x)**2/(16*b) - 5*csc(a + b*x)**3/(48*b) - 5*csc(a + b*x)/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)*csc(2*a + 2*b*x)**4,
        variable=x,
        num_steps=7,
        integral=-35*atanh(cos(a + b*x))/(128*b) - csc(a + b*x)**4*sec(a + b*x)**3/(64*b) - 7*csc(a + b*x)**2*sec(a + b*x)**3/(128*b) + 35*sec(a + b*x)**3/(384*b) + 35*sec(a + b*x)/(128*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**8*csc(a + b*x)**2,
        variable=x,
        num_steps=9,
        integral=5*x/8 - 128*sin(a + b*x)**5*cos(a + b*x)**9/(7*b) - 160*sin(a + b*x)**3*cos(a + b*x)**9/(21*b) - 16*sin(a + b*x)*cos(a + b*x)**9/(7*b) + 2*sin(a + b*x)*cos(a + b*x)**7/(7*b) + sin(a + b*x)*cos(a + b*x)**5/(3*b) + 5*sin(a + b*x)*cos(a + b*x)**3/(12*b) + 5*sin(a + b*x)*cos(a + b*x)/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**7*csc(a + b*x)**2,
        variable=x,
        num_steps=5,
        integral=-32*cos(a + b*x)**12/(3*b) + 128*cos(a + b*x)**10/(5*b) - 16*cos(a + b*x)**8/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**6*csc(a + b*x)**2,
        variable=x,
        num_steps=7,
        integral=3*x/4 - 32*sin(a + b*x)**3*cos(a + b*x)**7/(5*b) - 12*sin(a + b*x)*cos(a + b*x)**7/(5*b) + 2*sin(a + b*x)*cos(a + b*x)**5/(5*b) + sin(a + b*x)*cos(a + b*x)**3/(2*b) + 3*sin(a + b*x)*cos(a + b*x)/(4*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**5*csc(a + b*x)**2,
        variable=x,
        num_steps=4,
        integral=4*cos(a + b*x)**8/b - 16*cos(a + b*x)**6/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**4*csc(a + b*x)**2,
        variable=x,
        num_steps=5,
        integral=x - 8*sin(a + b*x)*cos(a + b*x)**5/(3*b) + 2*sin(a + b*x)*cos(a + b*x)**3/(3*b) + sin(a + b*x)*cos(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**3*csc(a + b*x)**2,
        variable=x,
        num_steps=3,
        integral=-2*cos(a + b*x)**4/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**2*csc(a + b*x)**2,
        variable=x,
        num_steps=3,
        integral=2*x + 2*sin(a + b*x)*cos(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)*csc(a + b*x)**2,
        variable=x,
        num_steps=2,
        integral=2*log(sin(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**2*csc(2*a + 2*b*x),
        variable=x,
        num_steps=4,
        integral=log(tan(a + b*x))/(2*b) - cot(a + b*x)**2/(4*b),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**2*csc(2*a + 2*b*x)**2,
        variable=x,
        num_steps=4,
        integral=tan(a + b*x)/(4*b) - cot(a + b*x)**3/(12*b) - cot(a + b*x)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**2*csc(2*a + 2*b*x)**3,
        variable=x,
        num_steps=5,
        integral=3*log(tan(a + b*x))/(8*b) + tan(a + b*x)**2/(16*b) - cot(a + b*x)**4/(32*b) - 3*cot(a + b*x)**2/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**2*csc(2*a + 2*b*x)**4,
        variable=x,
        num_steps=4,
        integral=tan(a + b*x)**3/(48*b) + tan(a + b*x)/(4*b) - cot(a + b*x)**5/(80*b) - cot(a + b*x)**3/(12*b) - 3*cot(a + b*x)/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**2*csc(2*a + 2*b*x)**5,
        variable=x,
        num_steps=5,
        integral=5*log(tan(a + b*x))/(16*b) + tan(a + b*x)**4/(128*b) + 5*tan(a + b*x)**2/(64*b) - cot(a + b*x)**6/(192*b) - 5*cot(a + b*x)**4/(128*b) - 5*cot(a + b*x)**2/(32*b),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**2*csc(2*a + 2*b*x)**6,
        variable=x,
        num_steps=4,
        integral=tan(a + b*x)**5/(320*b) + tan(a + b*x)**3/(32*b) + 15*tan(a + b*x)/(64*b) - cot(a + b*x)**7/(448*b) - 3*cot(a + b*x)**5/(160*b) - 5*cot(a + b*x)**3/(64*b) - 5*cot(a + b*x)/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**10*csc(a + b*x)**3,
        variable=x,
        num_steps=4,
        integral=1024*cos(a + b*x)**17/(17*b) - 1024*cos(a + b*x)**15/(5*b) + 3072*cos(a + b*x)**13/(13*b) - 1024*cos(a + b*x)**11/(11*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**9*csc(a + b*x)**3,
        variable=x,
        num_steps=4,
        integral=512*sin(a + b*x)**15/(15*b) - 2048*sin(a + b*x)**13/(13*b) + 3072*sin(a + b*x)**11/(11*b) - 2048*sin(a + b*x)**9/(9*b) + 512*sin(a + b*x)**7/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**8*csc(a + b*x)**3,
        variable=x,
        num_steps=4,
        integral=-256*cos(a + b*x)**13/(13*b) + 512*cos(a + b*x)**11/(11*b) - 256*cos(a + b*x)**9/(9*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**7*csc(a + b*x)**3,
        variable=x,
        num_steps=4,
        integral=-128*sin(a + b*x)**11/(11*b) + 128*sin(a + b*x)**9/(3*b) - 384*sin(a + b*x)**7/(7*b) + 128*sin(a + b*x)**5/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**6*csc(a + b*x)**3,
        variable=x,
        num_steps=4,
        integral=64*cos(a + b*x)**9/(9*b) - 64*cos(a + b*x)**7/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**5*csc(a + b*x)**3,
        variable=x,
        num_steps=4,
        integral=32*sin(a + b*x)**7/(7*b) - 64*sin(a + b*x)**5/(5*b) + 32*sin(a + b*x)**3/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**4*csc(a + b*x)**3,
        variable=x,
        num_steps=3,
        integral=-16*cos(a + b*x)**5/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**3*csc(a + b*x)**3,
        variable=x,
        num_steps=3,
        integral=-8*sin(a + b*x)**3/(3*b) + 8*sin(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**2*csc(a + b*x)**3,
        variable=x,
        num_steps=4,
        integral=4*cos(a + b*x)/b - 4*atanh(cos(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)*csc(a + b*x)**3,
        variable=x,
        num_steps=3,
        integral=-2*csc(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**3*csc(2*a + 2*b*x),
        variable=x,
        num_steps=5,
        integral=atanh(sin(a + b*x))/(2*b) - csc(a + b*x)**3/(6*b) - csc(a + b*x)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**3*csc(2*a + 2*b*x)**2,
        variable=x,
        num_steps=6,
        integral=-15*atanh(cos(a + b*x))/(32*b) - csc(a + b*x)**4*sec(a + b*x)/(16*b) - 5*csc(a + b*x)**2*sec(a + b*x)/(32*b) + 15*sec(a + b*x)/(32*b),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**3*csc(2*a + 2*b*x)**3,
        variable=x,
        num_steps=6,
        integral=7*atanh(sin(a + b*x))/(16*b) + csc(a + b*x)**5*sec(a + b*x)**2/(16*b) - 7*csc(a + b*x)**5/(80*b) - 7*csc(a + b*x)**3/(48*b) - 7*csc(a + b*x)/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**3*csc(2*a + 2*b*x)**4,
        variable=x,
        num_steps=8,
        integral=-105*atanh(cos(a + b*x))/(256*b) - csc(a + b*x)**6*sec(a + b*x)**3/(96*b) - 3*csc(a + b*x)**4*sec(a + b*x)**3/(128*b) - 21*csc(a + b*x)**2*sec(a + b*x)**3/(256*b) + 35*sec(a + b*x)**3/(256*b) + 105*sec(a + b*x)/(256*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sin(2*a + 2*b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=5*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(32*b) + 5*sin(a + b*x)*sin(2*a + 2*b*x)**(sympy.S(3)/2)/(24*b) - sin(2*a + 2*b*x)**(sympy.S(5)/2)*cos(a + b*x)/(6*b) - 5*sqrt(sin(2*a + 2*b*x))*cos(a + b*x)/(16*b) + 5*asin(sin(a + b*x) - cos(a + b*x))/(32*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sin(2*a + 2*b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-3*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(16*b) + 3*sin(a + b*x)*sqrt(sin(2*a + 2*b*x))/(8*b) - sin(2*a + 2*b*x)**(sympy.S(3)/2)*cos(a + b*x)/(4*b) + 3*asin(sin(a + b*x) - cos(a + b*x))/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sqrt(sin(2*a + 2*b*x)),
        variable=x,
        num_steps=2,
        integral=log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(4*b) - sqrt(sin(2*a + 2*b*x))*cos(a + b*x)/(2*b) + asin(sin(a + b*x) - cos(a + b*x))/(4*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)/sqrt(sin(2*a + 2*b*x)),
        variable=x,
        num_steps=1,
        integral=-log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(2*b) + asin(sin(a + b*x) - cos(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)/sin(2*a + 2*b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=1,
        integral=sin(a + b*x)/(b*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)/sin(2*a + 2*b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=sin(a + b*x)/(3*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)) - 2*cos(a + b*x)/(3*b*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)/sin(2*a + 2*b*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=8*sin(a + b*x)/(15*b*sqrt(sin(2*a + 2*b*x))) + sin(a + b*x)/(5*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)) - 4*cos(a + b*x)/(15*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)/sin(2*a + 2*b*x)**(sympy.S(9)/2),
        variable=x,
        num_steps=4,
        integral=8*sin(a + b*x)/(35*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)) + sin(a + b*x)/(7*b*sin(2*a + 2*b*x)**(sympy.S(7)/2)) - 16*cos(a + b*x)/(35*b*sqrt(sin(2*a + 2*b*x))) - 6*cos(a + b*x)/(35*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*sin(2*a + 2*b*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=4,
        integral=-sin(2*a + 2*b*x)**(sympy.S(9)/2)/(18*b) - sin(2*a + 2*b*x)**(sympy.S(5)/2)*cos(2*a + 2*b*x)/(14*b) - 5*sqrt(sin(2*a + 2*b*x))*cos(2*a + 2*b*x)/(42*b) + 5*elliptic_f(a + b*x - pi/4, 2)/(42*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*sin(2*a + 2*b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=-sin(2*a + 2*b*x)**(sympy.S(7)/2)/(14*b) - sin(2*a + 2*b*x)**(sympy.S(3)/2)*cos(2*a + 2*b*x)/(10*b) + 3*elliptic_e(a + b*x - pi/4, 2)/(10*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*sin(2*a + 2*b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-sin(2*a + 2*b*x)**(sympy.S(5)/2)/(10*b) - sqrt(sin(2*a + 2*b*x))*cos(2*a + 2*b*x)/(6*b) + elliptic_f(a + b*x - pi/4, 2)/(6*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*sqrt(sin(2*a + 2*b*x)),
        variable=x,
        num_steps=2,
        integral=-sin(2*a + 2*b*x)**(sympy.S(3)/2)/(6*b) + elliptic_e(a + b*x - pi/4, 2)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2/sqrt(sin(2*a + 2*b*x)),
        variable=x,
        num_steps=2,
        integral=-sqrt(sin(2*a + 2*b*x))/(2*b) + elliptic_f(a + b*x - pi/4, 2)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2/sin(2*a + 2*b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=sin(a + b*x)**2/(b*sqrt(sin(2*a + 2*b*x))) - elliptic_e(a + b*x - pi/4, 2)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2/sin(2*a + 2*b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=sin(a + b*x)**2/(3*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)) + elliptic_f(a + b*x - pi/4, 2)/(6*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2/sin(2*a + 2*b*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=sin(a + b*x)**2/(5*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)) - 3*elliptic_e(a + b*x - pi/4, 2)/(10*b) - 3*cos(2*a + 2*b*x)/(10*b*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*sin(2*a + 2*b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=-7*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(64*b) - sin(a + b*x)*sin(2*a + 2*b*x)**(sympy.S(5)/2)/(12*b) + 7*sin(a + b*x)*sqrt(sin(2*a + 2*b*x))/(32*b) - 7*sin(2*a + 2*b*x)**(sympy.S(3)/2)*cos(a + b*x)/(48*b) + 7*asin(sin(a + b*x) - cos(a + b*x))/(64*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*sqrt(sin(2*a + 2*b*x)),
        variable=x,
        num_steps=3,
        integral=5*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(32*b) - sin(a + b*x)*sin(2*a + 2*b*x)**(sympy.S(3)/2)/(8*b) - 5*sqrt(sin(2*a + 2*b*x))*cos(a + b*x)/(16*b) + 5*asin(sin(a + b*x) - cos(a + b*x))/(32*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3/sqrt(sin(2*a + 2*b*x)),
        variable=x,
        num_steps=2,
        integral=-3*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(8*b) - sin(a + b*x)*sqrt(sin(2*a + 2*b*x))/(4*b) + 3*asin(sin(a + b*x) - cos(a + b*x))/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3/sin(2*a + 2*b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(4*b) + sin(a + b*x)/(b*sqrt(sin(2*a + 2*b*x))) - asin(sin(a + b*x) - cos(a + b*x))/(4*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3/sin(2*a + 2*b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=1,
        integral=sin(a + b*x)**3/(3*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3/sin(2*a + 2*b*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=2,
        integral=sin(a + b*x)**3/(5*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)) + sin(a + b*x)/(5*b*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3/sin(2*a + 2*b*x)**(sympy.S(9)/2),
        variable=x,
        num_steps=3,
        integral=sin(a + b*x)**3/(7*b*sin(2*a + 2*b*x)**(sympy.S(7)/2)) + 2*sin(a + b*x)/(21*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)) - 4*cos(a + b*x)/(21*b*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3/sin(2*a + 2*b*x)**(sympy.S(11)/2),
        variable=x,
        num_steps=4,
        integral=sin(a + b*x)**3/(9*b*sin(2*a + 2*b*x)**(sympy.S(9)/2)) + 8*sin(a + b*x)/(45*b*sqrt(sin(2*a + 2*b*x))) + sin(a + b*x)/(15*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)) - 4*cos(a + b*x)/(45*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(7)/2)*csc(a + b*x),
        variable=x,
        num_steps=5,
        integral=-5*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(16*b) + sin(a + b*x)*sin(2*a + 2*b*x)**(sympy.S(5)/2)/(3*b) + 5*sin(a + b*x)*sqrt(sin(2*a + 2*b*x))/(8*b) - 5*sin(2*a + 2*b*x)**(sympy.S(3)/2)*cos(a + b*x)/(12*b) + 5*asin(sin(a + b*x) - cos(a + b*x))/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(5)/2)*csc(a + b*x),
        variable=x,
        num_steps=4,
        integral=3*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(8*b) + sin(a + b*x)*sin(2*a + 2*b*x)**(sympy.S(3)/2)/(2*b) - 3*sqrt(sin(2*a + 2*b*x))*cos(a + b*x)/(4*b) + 3*asin(sin(a + b*x) - cos(a + b*x))/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(3)/2)*csc(a + b*x),
        variable=x,
        num_steps=3,
        integral=-log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(2*b) + sin(a + b*x)*sqrt(sin(2*a + 2*b*x))/b + asin(sin(a + b*x) - cos(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sin(2*a + 2*b*x))*csc(a + b*x),
        variable=x,
        num_steps=2,
        integral=log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/b + asin(sin(a + b*x) - cos(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)/sqrt(sin(2*a + 2*b*x)),
        variable=x,
        num_steps=1,
        integral=-sqrt(sin(2*a + 2*b*x))*csc(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)/sin(2*a + 2*b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=4*sin(a + b*x)/(3*b*sqrt(sin(2*a + 2*b*x))) - 2*cos(a + b*x)/(3*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)/sin(2*a + 2*b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=8*sin(a + b*x)/(15*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)) - 16*cos(a + b*x)/(15*b*sqrt(sin(2*a + 2*b*x))) - 2*cos(a + b*x)/(5*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)/sin(2*a + 2*b*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=5,
        integral=32*sin(a + b*x)/(35*b*sqrt(sin(2*a + 2*b*x))) + 12*sin(a + b*x)/(35*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)) - 16*cos(a + b*x)/(35*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)) - 2*cos(a + b*x)/(7*b*sin(2*a + 2*b*x)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(9)/2)*csc(a + b*x)**2,
        variable=x,
        num_steps=4,
        integral=sin(2*a + 2*b*x)**(sympy.S(11)/2)*csc(a + b*x)**2/(7*b) - 2*sin(2*a + 2*b*x)**(sympy.S(7)/2)*cos(2*a + 2*b*x)/(7*b) - 2*sin(2*a + 2*b*x)**(sympy.S(3)/2)*cos(2*a + 2*b*x)/(5*b) + 6*elliptic_e(a + b*x - pi/4, 2)/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(7)/2)*csc(a + b*x)**2,
        variable=x,
        num_steps=4,
        integral=sin(2*a + 2*b*x)**(sympy.S(9)/2)*csc(a + b*x)**2/(5*b) - 2*sin(2*a + 2*b*x)**(sympy.S(5)/2)*cos(2*a + 2*b*x)/(5*b) - 2*sqrt(sin(2*a + 2*b*x))*cos(2*a + 2*b*x)/(3*b) + 2*elliptic_f(a + b*x - pi/4, 2)/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(5)/2)*csc(a + b*x)**2,
        variable=x,
        num_steps=3,
        integral=sin(2*a + 2*b*x)**(sympy.S(7)/2)*csc(a + b*x)**2/(3*b) - 2*sin(2*a + 2*b*x)**(sympy.S(3)/2)*cos(2*a + 2*b*x)/(3*b) + 2*elliptic_e(a + b*x - pi/4, 2)/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(3)/2)*csc(a + b*x)**2,
        variable=x,
        num_steps=3,
        integral=sin(2*a + 2*b*x)**(sympy.S(5)/2)*csc(a + b*x)**2/b - 2*sqrt(sin(2*a + 2*b*x))*cos(2*a + 2*b*x)/b + 2*elliptic_f(a + b*x - pi/4, 2)/b,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sin(2*a + 2*b*x))*csc(a + b*x)**2,
        variable=x,
        num_steps=2,
        integral=-sin(2*a + 2*b*x)**(sympy.S(3)/2)*csc(a + b*x)**2/b - 2*elliptic_e(a + b*x - pi/4, 2)/b,
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**2/sqrt(sin(2*a + 2*b*x)),
        variable=x,
        num_steps=2,
        integral=-sqrt(sin(2*a + 2*b*x))*csc(a + b*x)**2/(3*b) + 2*elliptic_f(a + b*x - pi/4, 2)/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**2/sin(2*a + 2*b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-6*elliptic_e(a + b*x - pi/4, 2)/(5*b) - 6*cos(2*a + 2*b*x)/(5*b*sqrt(sin(2*a + 2*b*x))) - csc(a + b*x)**2/(5*b*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**2/sin(2*a + 2*b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=10*elliptic_f(a + b*x - pi/4, 2)/(21*b) - 10*cos(2*a + 2*b*x)/(21*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)) - csc(a + b*x)**2/(7*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**2/sin(2*a + 2*b*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=4,
        integral=-14*elliptic_e(a + b*x - pi/4, 2)/(15*b) - 14*cos(2*a + 2*b*x)/(15*b*sqrt(sin(2*a + 2*b*x))) - 14*cos(2*a + 2*b*x)/(45*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)) - csc(a + b*x)**2/(9*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**2/sin(2*a + 2*b*x)**(sympy.S(9)/2),
        variable=x,
        num_steps=4,
        integral=30*elliptic_f(a + b*x - pi/4, 2)/(77*b) - 30*cos(2*a + 2*b*x)/(77*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)) - 18*cos(2*a + 2*b*x)/(77*b*sin(2*a + 2*b*x)**(sympy.S(7)/2)) - csc(a + b*x)**2/(11*b*sin(2*a + 2*b*x)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(9)/2)*csc(a + b*x)**3,
        variable=x,
        num_steps=7,
        integral=7*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(8*b) + 4*sin(a + b*x)*sin(2*a + 2*b*x)**(sympy.S(7)/2)/(5*b) + 7*sin(a + b*x)*sin(2*a + 2*b*x)**(sympy.S(3)/2)/(6*b) + sin(2*a + 2*b*x)**(sympy.S(11)/2)*csc(a + b*x)**3/(5*b) - 14*sin(2*a + 2*b*x)**(sympy.S(5)/2)*cos(a + b*x)/(15*b) - 7*sqrt(sin(2*a + 2*b*x))*cos(a + b*x)/(4*b) + 7*asin(sin(a + b*x) - cos(a + b*x))/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(7)/2)*csc(a + b*x)**3,
        variable=x,
        num_steps=6,
        integral=-5*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(4*b) + 4*sin(a + b*x)*sin(2*a + 2*b*x)**(sympy.S(5)/2)/(3*b) + 5*sin(a + b*x)*sqrt(sin(2*a + 2*b*x))/(2*b) + sin(2*a + 2*b*x)**(sympy.S(9)/2)*csc(a + b*x)**3/(3*b) - 5*sin(2*a + 2*b*x)**(sympy.S(3)/2)*cos(a + b*x)/(3*b) + 5*asin(sin(a + b*x) - cos(a + b*x))/(4*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(5)/2)*csc(a + b*x)**3,
        variable=x,
        num_steps=5,
        integral=3*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/b + 4*sin(a + b*x)*sin(2*a + 2*b*x)**(sympy.S(3)/2)/b + sin(2*a + 2*b*x)**(sympy.S(7)/2)*csc(a + b*x)**3/b - 6*sqrt(sin(2*a + 2*b*x))*cos(a + b*x)/b + 3*asin(sin(a + b*x) - cos(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(3)/2)*csc(a + b*x)**3,
        variable=x,
        num_steps=4,
        integral=2*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/b - 4*sin(a + b*x)*sqrt(sin(2*a + 2*b*x))/b - sin(2*a + 2*b*x)**(sympy.S(5)/2)*csc(a + b*x)**3/b - 2*asin(sin(a + b*x) - cos(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sin(2*a + 2*b*x))*csc(a + b*x)**3,
        variable=x,
        num_steps=1,
        integral=-sin(2*a + 2*b*x)**(sympy.S(3)/2)*csc(a + b*x)**3/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**3/sqrt(sin(2*a + 2*b*x)),
        variable=x,
        num_steps=2,
        integral=-sqrt(sin(2*a + 2*b*x))*csc(a + b*x)**3/(5*b) - 4*sqrt(sin(2*a + 2*b*x))*csc(a + b*x)/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**3/sin(2*a + 2*b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=32*sin(a + b*x)/(21*b*sqrt(sin(2*a + 2*b*x))) - csc(a + b*x)**3/(7*b*sqrt(sin(2*a + 2*b*x))) - 16*cos(a + b*x)/(21*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**3/sin(2*a + 2*b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=32*sin(a + b*x)/(45*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)) - 64*cos(a + b*x)/(45*b*sqrt(sin(2*a + 2*b*x))) - csc(a + b*x)**3/(9*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)) - 8*cos(a + b*x)/(15*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*sin(2*a + 2*b*x)**m,
        variable=x,
        num_steps=2,
        integral=(cos(a + b*x)**2)**(sympy.S.Half - m/2)*sin(a + b*x)**3*sin(2*a + 2*b*x)**m*tan(a + b*x)*hyper((sympy.S.Half - m/2, m/2 + 2), (m/2 + 3,), sin(a + b*x)**2)/(b*(m + 4)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*sin(2*a + 2*b*x)**m,
        variable=x,
        num_steps=2,
        integral=(cos(a + b*x)**2)**(sympy.S.Half - m/2)*sin(a + b*x)**2*sin(2*a + 2*b*x)**m*tan(a + b*x)*hyper((sympy.S.Half - m/2, m/2 + sympy.S(3)/2), (m/2 + sympy.S(5)/2,), sin(a + b*x)**2)/(b*(m + 3)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sin(2*a + 2*b*x)**m,
        variable=x,
        num_steps=2,
        integral=(cos(a + b*x)**2)**(sympy.S.Half - m/2)*sin(a + b*x)*sin(2*a + 2*b*x)**m*tan(a + b*x)*hyper((sympy.S.Half - m/2, m/2 + 1), (m/2 + 2,), sin(a + b*x)**2)/(b*(m + 2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**m*csc(a + b*x),
        variable=x,
        num_steps=2,
        integral=(cos(a + b*x)**2)**(sympy.S.Half - m/2)*sin(2*a + 2*b*x)**m*hyper((m/2, sympy.S.Half - m/2), (m/2 + 1,), sin(a + b*x)**2)*sec(a + b*x)/(b*m),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**m*csc(a + b*x)**2,
        variable=x,
        num_steps=2,
        integral=-(cos(a + b*x)**2)**(sympy.S.Half - m/2)*sin(2*a + 2*b*x)**m*csc(a + b*x)*hyper((sympy.S.Half - m/2, m/2 + sympy.S(-1)/2), (m/2 + sympy.S.Half,), sin(a + b*x)**2)*sec(a + b*x)/(b*(1 - m)),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**m*csc(a + b*x)**3,
        variable=x,
        num_steps=2,
        integral=-(cos(a + b*x)**2)**(sympy.S.Half - m/2)*sin(2*a + 2*b*x)**m*csc(a + b*x)**2*hyper((sympy.S.Half - m/2, m/2 - 1), (m/2,), sin(a + b*x)**2)*sec(a + b*x)/(b*(2 - m)),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**7*cos(a + b*x),
        variable=x,
        num_steps=4,
        integral=128*cos(a + b*x)**15/(15*b) - 384*cos(a + b*x)**13/(13*b) + 384*cos(a + b*x)**11/(11*b) - 128*cos(a + b*x)**9/(9*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**6*cos(a + b*x),
        variable=x,
        num_steps=4,
        integral=-64*sin(a + b*x)**13/(13*b) + 192*sin(a + b*x)**11/(11*b) - 64*sin(a + b*x)**9/(3*b) + 64*sin(a + b*x)**7/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**5*cos(a + b*x),
        variable=x,
        num_steps=4,
        integral=-32*cos(a + b*x)**11/(11*b) + 64*cos(a + b*x)**9/(9*b) - 32*cos(a + b*x)**7/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**4*cos(a + b*x),
        variable=x,
        num_steps=4,
        integral=16*sin(a + b*x)**9/(9*b) - 32*sin(a + b*x)**7/(7*b) + 16*sin(a + b*x)**5/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**3*cos(a + b*x),
        variable=x,
        num_steps=4,
        integral=8*cos(a + b*x)**7/(7*b) - 8*cos(a + b*x)**5/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**2*cos(a + b*x),
        variable=x,
        num_steps=4,
        integral=-4*sin(a + b*x)**5/(5*b) + 4*sin(a + b*x)**3/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)*cos(a + b*x),
        variable=x,
        num_steps=1,
        integral=-cos(a + b*x)/(2*b) - cos(3*a + 3*b*x)/(6*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)/sin(2*a + 2*b*x),
        variable=x,
        num_steps=2,
        integral=-atanh(cos(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)/sin(2*a + 2*b*x)**2,
        variable=x,
        num_steps=4,
        integral=atanh(sin(a + b*x))/(4*b) - csc(a + b*x)/(4*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)/sin(2*a + 2*b*x)**3,
        variable=x,
        num_steps=5,
        integral=-3*atanh(cos(a + b*x))/(16*b) - csc(a + b*x)**2*sec(a + b*x)/(16*b) + 3*sec(a + b*x)/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)/sin(2*a + 2*b*x)**4,
        variable=x,
        num_steps=6,
        integral=5*atanh(sin(a + b*x))/(32*b) + csc(a + b*x)**3*sec(a + b*x)**2/(32*b) - 5*csc(a + b*x)**3/(96*b) - 5*csc(a + b*x)/(32*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)/sin(2*a + 2*b*x)**5,
        variable=x,
        num_steps=7,
        integral=-35*atanh(cos(a + b*x))/(256*b) - csc(a + b*x)**4*sec(a + b*x)**3/(128*b) - 7*csc(a + b*x)**2*sec(a + b*x)**3/(256*b) + 35*sec(a + b*x)**3/(768*b) + 35*sec(a + b*x)/(256*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**5*cos(a + b*x)**2,
        variable=x,
        num_steps=5,
        integral=-8*cos(a + b*x)**12/(3*b) + 32*cos(a + b*x)**10/(5*b) - 4*cos(a + b*x)**8/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**4*cos(a + b*x)**2,
        variable=x,
        num_steps=6,
        integral=3*x/16 + sin(2*a + 2*b*x)**5/(20*b) - sin(2*a + 2*b*x)**3*cos(2*a + 2*b*x)/(16*b) - 3*sin(2*a + 2*b*x)*cos(2*a + 2*b*x)/(32*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**3*cos(a + b*x)**2,
        variable=x,
        num_steps=4,
        integral=cos(a + b*x)**8/b - 4*cos(a + b*x)**6/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**2*cos(a + b*x)**2,
        variable=x,
        num_steps=5,
        integral=x/4 + sin(2*a + 2*b*x)**3/(12*b) - sin(2*a + 2*b*x)*cos(2*a + 2*b*x)/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)*cos(a + b*x)**2,
        variable=x,
        num_steps=3,
        integral=-cos(a + b*x)**4/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2/sin(2*a + 2*b*x),
        variable=x,
        num_steps=2,
        integral=log(sin(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2/sin(2*a + 2*b*x)**2,
        variable=x,
        num_steps=3,
        integral=-cot(a + b*x)/(4*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2/sin(2*a + 2*b*x)**3,
        variable=x,
        num_steps=4,
        integral=log(tan(a + b*x))/(8*b) - cot(a + b*x)**2/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2/sin(2*a + 2*b*x)**4,
        variable=x,
        num_steps=4,
        integral=tan(a + b*x)/(16*b) - cot(a + b*x)**3/(48*b) - cot(a + b*x)/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2/sin(2*a + 2*b*x)**5,
        variable=x,
        num_steps=5,
        integral=3*log(tan(a + b*x))/(32*b) + tan(a + b*x)**2/(64*b) - cot(a + b*x)**4/(128*b) - 3*cot(a + b*x)**2/(64*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**5*cos(a + b*x)**3,
        variable=x,
        num_steps=4,
        integral=-32*cos(a + b*x)**13/(13*b) + 64*cos(a + b*x)**11/(11*b) - 32*cos(a + b*x)**9/(9*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**4*cos(a + b*x)**3,
        variable=x,
        num_steps=4,
        integral=-16*sin(a + b*x)**11/(11*b) + 16*sin(a + b*x)**9/(3*b) - 48*sin(a + b*x)**7/(7*b) + 16*sin(a + b*x)**5/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**3*cos(a + b*x)**3,
        variable=x,
        num_steps=4,
        integral=8*cos(a + b*x)**9/(9*b) - 8*cos(a + b*x)**7/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**2*cos(a + b*x)**3,
        variable=x,
        num_steps=4,
        integral=4*sin(a + b*x)**7/(7*b) - 8*sin(a + b*x)**5/(5*b) + 4*sin(a + b*x)**3/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)*cos(a + b*x)**3,
        variable=x,
        num_steps=3,
        integral=-2*cos(a + b*x)**5/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3/sin(2*a + 2*b*x),
        variable=x,
        num_steps=4,
        integral=cos(a + b*x)/(2*b) - atanh(cos(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3/sin(2*a + 2*b*x)**2,
        variable=x,
        num_steps=3,
        integral=-csc(a + b*x)/(4*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3/sin(2*a + 2*b*x)**3,
        variable=x,
        num_steps=3,
        integral=-cot(a + b*x)*csc(a + b*x)/(16*b) - atanh(cos(a + b*x))/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3/sin(2*a + 2*b*x)**4,
        variable=x,
        num_steps=5,
        integral=atanh(sin(a + b*x))/(16*b) - csc(a + b*x)**3/(48*b) - csc(a + b*x)/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3/sin(2*a + 2*b*x)**5,
        variable=x,
        num_steps=6,
        integral=-15*atanh(cos(a + b*x))/(256*b) - csc(a + b*x)**4*sec(a + b*x)/(128*b) - 5*csc(a + b*x)**2*sec(a + b*x)/(256*b) + 15*sec(a + b*x)/(256*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(5)/2)*cos(a + b*x),
        variable=x,
        num_steps=4,
        integral=-5*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(32*b) + sin(a + b*x)*sin(2*a + 2*b*x)**(sympy.S(5)/2)/(6*b) + 5*sin(a + b*x)*sqrt(sin(2*a + 2*b*x))/(16*b) - 5*sin(2*a + 2*b*x)**(sympy.S(3)/2)*cos(a + b*x)/(24*b) + 5*asin(sin(a + b*x) - cos(a + b*x))/(32*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(3)/2)*cos(a + b*x),
        variable=x,
        num_steps=3,
        integral=3*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(16*b) + sin(a + b*x)*sin(2*a + 2*b*x)**(sympy.S(3)/2)/(4*b) - 3*sqrt(sin(2*a + 2*b*x))*cos(a + b*x)/(8*b) + 3*asin(sin(a + b*x) - cos(a + b*x))/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sin(2*a + 2*b*x))*cos(a + b*x),
        variable=x,
        num_steps=2,
        integral=-log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(4*b) + sin(a + b*x)*sqrt(sin(2*a + 2*b*x))/(2*b) + asin(sin(a + b*x) - cos(a + b*x))/(4*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)/sqrt(sin(2*a + 2*b*x)),
        variable=x,
        num_steps=1,
        integral=log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(2*b) + asin(sin(a + b*x) - cos(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)/sin(2*a + 2*b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=1,
        integral=-cos(a + b*x)/(b*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)/sin(2*a + 2*b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=2*sin(a + b*x)/(3*b*sqrt(sin(2*a + 2*b*x))) - cos(a + b*x)/(3*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)/sin(2*a + 2*b*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=4*sin(a + b*x)/(15*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)) - 8*cos(a + b*x)/(15*b*sqrt(sin(2*a + 2*b*x))) - cos(a + b*x)/(5*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)/sin(2*a + 2*b*x)**(sympy.S(9)/2),
        variable=x,
        num_steps=4,
        integral=16*sin(a + b*x)/(35*b*sqrt(sin(2*a + 2*b*x))) + 6*sin(a + b*x)/(35*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)) - 8*cos(a + b*x)/(35*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)) - cos(a + b*x)/(7*b*sin(2*a + 2*b*x)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(7)/2)*cos(a + b*x)**2,
        variable=x,
        num_steps=4,
        integral=sin(2*a + 2*b*x)**(sympy.S(9)/2)/(18*b) - sin(2*a + 2*b*x)**(sympy.S(5)/2)*cos(2*a + 2*b*x)/(14*b) - 5*sqrt(sin(2*a + 2*b*x))*cos(2*a + 2*b*x)/(42*b) + 5*elliptic_f(a + b*x - pi/4, 2)/(42*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(5)/2)*cos(a + b*x)**2,
        variable=x,
        num_steps=3,
        integral=sin(2*a + 2*b*x)**(sympy.S(7)/2)/(14*b) - sin(2*a + 2*b*x)**(sympy.S(3)/2)*cos(2*a + 2*b*x)/(10*b) + 3*elliptic_e(a + b*x - pi/4, 2)/(10*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(3)/2)*cos(a + b*x)**2,
        variable=x,
        num_steps=3,
        integral=sin(2*a + 2*b*x)**(sympy.S(5)/2)/(10*b) - sqrt(sin(2*a + 2*b*x))*cos(2*a + 2*b*x)/(6*b) + elliptic_f(a + b*x - pi/4, 2)/(6*b),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sin(2*a + 2*b*x))*cos(a + b*x)**2,
        variable=x,
        num_steps=2,
        integral=sin(2*a + 2*b*x)**(sympy.S(3)/2)/(6*b) + elliptic_e(a + b*x - pi/4, 2)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2/sqrt(sin(2*a + 2*b*x)),
        variable=x,
        num_steps=2,
        integral=sqrt(sin(2*a + 2*b*x))/(2*b) + elliptic_f(a + b*x - pi/4, 2)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2/sin(2*a + 2*b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=-elliptic_e(a + b*x - pi/4, 2)/(2*b) - cos(a + b*x)**2/(b*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2/sin(2*a + 2*b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=elliptic_f(a + b*x - pi/4, 2)/(6*b) - cos(a + b*x)**2/(3*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2/sin(2*a + 2*b*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=-3*elliptic_e(a + b*x - pi/4, 2)/(10*b) - 3*cos(2*a + 2*b*x)/(10*b*sqrt(sin(2*a + 2*b*x))) - cos(a + b*x)**2/(5*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**(sympy.S(3)/2)*cos(a + b*x)**3,
        variable=x,
        num_steps=4,
        integral=7*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(64*b) + 7*sin(a + b*x)*sin(2*a + 2*b*x)**(sympy.S(3)/2)/(48*b) + sin(2*a + 2*b*x)**(sympy.S(5)/2)*cos(a + b*x)/(12*b) - 7*sqrt(sin(2*a + 2*b*x))*cos(a + b*x)/(32*b) + 7*asin(sin(a + b*x) - cos(a + b*x))/(64*b),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sin(2*a + 2*b*x))*cos(a + b*x)**3,
        variable=x,
        num_steps=3,
        integral=-5*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(32*b) + 5*sin(a + b*x)*sqrt(sin(2*a + 2*b*x))/(16*b) + sin(2*a + 2*b*x)**(sympy.S(3)/2)*cos(a + b*x)/(8*b) + 5*asin(sin(a + b*x) - cos(a + b*x))/(32*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3/sqrt(sin(2*a + 2*b*x)),
        variable=x,
        num_steps=2,
        integral=3*log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(8*b) + sqrt(sin(2*a + 2*b*x))*cos(a + b*x)/(4*b) + 3*asin(sin(a + b*x) - cos(a + b*x))/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3/sin(2*a + 2*b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=log(sin(a + b*x) + sqrt(sin(2*a + 2*b*x)) + cos(a + b*x))/(4*b) - asin(sin(a + b*x) - cos(a + b*x))/(4*b) - cos(a + b*x)/(b*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3/sin(2*a + 2*b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=1,
        integral=-cos(a + b*x)**3/(3*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3/sin(2*a + 2*b*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=2,
        integral=-cos(a + b*x)/(5*b*sqrt(sin(2*a + 2*b*x))) - cos(a + b*x)**3/(5*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3/sin(2*a + 2*b*x)**(sympy.S(9)/2),
        variable=x,
        num_steps=3,
        integral=4*sin(a + b*x)/(21*b*sqrt(sin(2*a + 2*b*x))) - 2*cos(a + b*x)/(21*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)) - cos(a + b*x)**3/(7*b*sin(2*a + 2*b*x)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3/sin(2*a + 2*b*x)**(sympy.S(11)/2),
        variable=x,
        num_steps=4,
        integral=4*sin(a + b*x)/(45*b*sin(2*a + 2*b*x)**(sympy.S(3)/2)) - 8*cos(a + b*x)/(45*b*sqrt(sin(2*a + 2*b*x))) - cos(a + b*x)/(15*b*sin(2*a + 2*b*x)**(sympy.S(5)/2)) - cos(a + b*x)**3/(9*b*sin(2*a + 2*b*x)**(sympy.S(9)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)/sqrt(sin(2*x)),
        variable=x,
        num_steps=1,
        integral=log(sin(x) + sqrt(sin(2*x)) + cos(x))/2 + asin(sin(x) - cos(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sin(2*x))*csc(x),
        variable=x,
        num_steps=2,
        integral=log(sin(x) + sqrt(sin(2*x)) + cos(x)) + asin(sin(x) - cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**m*cos(a + b*x)**3,
        variable=x,
        num_steps=2,
        integral=-(sin(a + b*x)**2)**(sympy.S.Half - m/2)*sin(2*a + 2*b*x)**m*cos(a + b*x)**3*cot(a + b*x)*hyper((sympy.S.Half - m/2, m/2 + 2), (m/2 + 3,), cos(a + b*x)**2)/(b*(m + 4)),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**m*cos(a + b*x)**2,
        variable=x,
        num_steps=2,
        integral=-(sin(a + b*x)**2)**(sympy.S.Half - m/2)*sin(2*a + 2*b*x)**m*cos(a + b*x)**2*cot(a + b*x)*hyper((sympy.S.Half - m/2, m/2 + sympy.S(3)/2), (m/2 + sympy.S(5)/2,), cos(a + b*x)**2)/(b*(m + 3)),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*a + 2*b*x)**m*cos(a + b*x),
        variable=x,
        num_steps=2,
        integral=-(sin(a + b*x)**2)**(sympy.S.Half - m/2)*sin(2*a + 2*b*x)**m*cos(a + b*x)*cot(a + b*x)*hyper((sympy.S.Half - m/2, m/2 + 1), (m/2 + 2,), cos(a + b*x)**2)/(b*(m + 2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*sin(2*a + 2*b*x)**2*cos(a + b*x)**2,
        variable=x,
        num_steps=4,
        integral=-4*cos(a + b*x)**9/(9*b) + 8*cos(a + b*x)**7/(7*b) - 4*cos(a + b*x)**5/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sin(c + d*x)**n,
        variable=x,
        num_steps=10,
        integral=-2**(-n - 1)*(-I*exp(I*(c + d*x)) + I*exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) - I*x*(b + d*n) - I*(a + c*n))*hyper((-n, -(b + d*n)/(2*d)), (1 - (b + d*n)/(2*d),), exp(2*I*(c + d*x)))/((1 - exp(2*I*c + 2*I*d*x))**n*(b + d*n)) - 2**(-n - 1)*(-I*exp(I*(c + d*x)) + I*exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) + I*x*(b - d*n) + I*(a - c*n))*hyper((-n, (b - d*n)/(2*d)), (b/(2*d) - n/2 + 1,), exp(2*I*(c + d*x)))/((1 - exp(2*I*c + 2*I*d*x))**n*(b - d*n)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sin(c + d*x)**3,
        variable=x,
        num_steps=6,
        integral=sin(a + 3*c + x*(b + 3*d))/(8*b + 24*d) - 3*sin(a + c + x*(b + d))/(8*b + 8*d) + 3*sin(a - c + x*(b - d))/(8*b - 8*d) - sin(a - 3*c + x*(b - 3*d))/(8*b - 24*d),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sin(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=cos(a + 2*c + x*(b + 2*d))/(4*b + 8*d) + cos(a - 2*c + x*(b - 2*d))/(4*b - 8*d) - cos(a + b*x)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sin(c + d*x),
        variable=x,
        num_steps=4,
        integral=-sin(a + c + x*(b + d))/(2*b + 2*d) + sin(a - c + x*(b - d))/(2*b - 2*d),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*csc(b*x + c),
        variable=x,
        num_steps=3,
        integral=x*cos(a - c) + log(sin(b*x + c))*sin(a - c)/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*csc(b*x + c)**2,
        variable=x,
        num_steps=4,
        integral=-sin(a - c)*csc(b*x + c)/b - cos(a - c)*atanh(cos(b*x + c))/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*csc(b*x + c)**3,
        variable=x,
        num_steps=5,
        integral=-sin(a - c)*csc(b*x + c)**2/(2*b) - cos(a - c)*cot(b*x + c)/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*csc(b*x + c)**4,
        variable=x,
        num_steps=5,
        integral=-sin(a - c)*csc(b*x + c)**3/(3*b) - cos(a - c)*cot(b*x + c)*csc(b*x + c)/(2*b) - cos(a - c)*atanh(cos(b*x + c))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*csc(b*x + c)**5,
        variable=x,
        num_steps=5,
        integral=-sin(a - c)*csc(b*x + c)**4/(4*b) - cos(a - c)*cot(b*x + c)**3/(3*b) - cos(a - c)*cot(b*x + c)/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*csc(b*x + c)**6,
        variable=x,
        num_steps=6,
        integral=-sin(a - c)*csc(b*x + c)**5/(5*b) - cos(a - c)*cot(b*x + c)*csc(b*x + c)**3/(4*b) - 3*cos(a - c)*cot(b*x + c)*csc(b*x + c)/(8*b) - 3*cos(a - c)*atanh(cos(b*x + c))/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*sin(c + d*x)**n,
        variable=x,
        num_steps=15,
        integral=-2**(-n - 2)*I*(-I*exp(I*(c + d*x)) + I*exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) - I*x*(2*b + d*n) - I*(2*a + c*n))*hyper((-n, -b/d - n/2), (-b/d - n/2 + 1,), exp(2*I*(c + d*x)))/((1 - exp(2*I*c + 2*I*d*x))**n*(2*b + d*n)) + 2**(-n - 2)*I*(-I*exp(I*(c + d*x)) + I*exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) + I*x*(2*b - d*n) + I*(2*a - c*n))*hyper((-n, b/d - n/2), (b/d - n/2 + 1,), exp(2*I*(c + d*x)))/((1 - exp(2*I*c + 2*I*d*x))**n*(2*b - d*n)) + 2**(-n - 1)*I*(-I*exp(I*(c + d*x)) + I*exp(-I*(c + d*x)))**n*hyper((-n, -n/2), (1 - n/2,), exp(2*I*(c + d*x)))/(d*n*(1 - exp(2*I*(c + d*x)))**n),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*sin(c + d*x),
        variable=x,
        num_steps=5,
        integral=cos(2*a + c + x*(2*b + d))/(8*b + 4*d) - cos(2*a - c + x*(2*b - d))/(8*b - 4*d) - cos(c + d*x)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*sin(c + d*x)**2,
        variable=x,
        num_steps=6,
        integral=x/4 + sin(2*a + 2*c + x*(2*b + 2*d))/(16*b + 16*d) + sin(2*a - 2*c + x*(2*b - 2*d))/(16*b - 16*d) - sin(2*c + 2*d*x)/(8*d) - sin(2*a + 2*b*x)/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*sin(c + d*x)**3,
        variable=x,
        num_steps=8,
        integral=-cos(2*a + 3*c + x*(2*b + 3*d))/(32*b + 48*d) + 3*cos(2*a + c + x*(2*b + d))/(32*b + 16*d) - 3*cos(2*a - c + x*(2*b - d))/(32*b - 16*d) + cos(2*a - 3*c + x*(2*b - 3*d))/(32*b - 48*d) - 3*cos(c + d*x)/(8*d) + cos(3*c + 3*d*x)/(24*d),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*sin(c + d*x)**n,
        variable=x,
        num_steps=18,
        integral=2**(-n - 3)*(-I*exp(I*(c + d*x)) + I*exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) - I*x*(3*b + d*n) - I*(3*a + c*n))*hyper((-n, -(3*b + d*n)/(2*d)), (-3*b/(2*d) - n/2 + 1,), exp(2*I*(c + d*x)))/((1 - exp(2*I*c + 2*I*d*x))**n*(3*b + d*n)) + 2**(-n - 3)*(-I*exp(I*(c + d*x)) + I*exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) + I*x*(3*b - d*n) + I*(3*a - c*n))*hyper((-n, 3*b/(2*d) - n/2), (3*b/(2*d) - n/2 + 1,), exp(2*I*(c + d*x)))/((1 - exp(2*I*c + 2*I*d*x))**n*(3*b - d*n)) - 3*2**(-n - 3)*(-I*exp(I*(c + d*x)) + I*exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) - I*x*(b + d*n) - I*(a + c*n))*hyper((-n, -(b + d*n)/(2*d)), (1 - (b + d*n)/(2*d),), exp(2*I*(c + d*x)))/((1 - exp(2*I*c + 2*I*d*x))**n*(b + d*n)) - 3*2**(-n - 3)*(-I*exp(I*(c + d*x)) + I*exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) + I*x*(b - d*n) + I*(a - c*n))*hyper((-n, (b - d*n)/(2*d)), (b/(2*d) - n/2 + 1,), exp(2*I*(c + d*x)))/((1 - exp(2*I*c + 2*I*d*x))**n*(b - d*n)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*sin(c + d*x),
        variable=x,
        num_steps=6,
        integral=sin(3*a + c + x*(3*b + d))/(24*b + 8*d) - sin(3*a - c + x*(3*b - d))/(24*b - 8*d) - 3*sin(a + c + x*(b + d))/(8*b + 8*d) + 3*sin(a - c + x*(b - d))/(8*b - 8*d),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*sin(c + d*x)**2,
        variable=x,
        num_steps=8,
        integral=-cos(3*a + 2*c + x*(3*b + 2*d))/(48*b + 32*d) - cos(3*a - 2*c + x*(3*b - 2*d))/(48*b - 32*d) + 3*cos(a + 2*c + x*(b + 2*d))/(16*b + 32*d) + 3*cos(a - 2*c + x*(b - 2*d))/(16*b - 32*d) - 3*cos(a + b*x)/(8*b) + cos(3*a + 3*b*x)/(24*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*sin(c + d*x)**3,
        variable=x,
        num_steps=10,
        integral=-sin(3*a + 3*c + x*(3*b + 3*d))/(96*b + 96*d) + 3*sin(3*a + c + x*(3*b + d))/(96*b + 32*d) - 3*sin(3*a - c + x*(3*b - d))/(96*b - 32*d) + sin(3*a - 3*c + x*(3*b - 3*d))/(96*b - 96*d) + 3*sin(a + 3*c + x*(b + 3*d))/(32*b + 96*d) - 9*sin(a + c + x*(b + d))/(32*b + 32*d) + 9*sin(a - c + x*(b - d))/(32*b - 32*d) - 3*sin(a - 3*c + x*(b - 3*d))/(32*b - 96*d),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*cos(c + d*x)**n,
        variable=x,
        num_steps=8,
        integral=-2**(-n - 1)*(exp(I*(c + d*x)) + exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) - I*x*(b + d*n) - I*(a + c*n))*hyper((-n, -(b + d*n)/(2*d)), (1 - (b + d*n)/(2*d),), -exp(2*I*(c + d*x)))/((b + d*n)*(exp(2*I*c + 2*I*d*x) + 1)**n) - 2**(-n - 1)*(exp(I*(c + d*x)) + exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) + I*x*(b - d*n) + I*(a - c*n))*hyper((-n, (b - d*n)/(2*d)), (b/(2*d) - n/2 + 1,), -exp(2*I*(c + d*x)))/((b - d*n)*(exp(2*I*c + 2*I*d*x) + 1)**n),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*cos(c + d*x)**3,
        variable=x,
        num_steps=6,
        integral=-cos(a + 3*c + x*(b + 3*d))/(8*b + 24*d) - 3*cos(a + c + x*(b + d))/(8*b + 8*d) - 3*cos(a - c + x*(b - d))/(8*b - 8*d) - cos(a - 3*c + x*(b - 3*d))/(8*b - 24*d),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*cos(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=-cos(a + 2*c + x*(b + 2*d))/(4*b + 8*d) - cos(a - 2*c + x*(b - 2*d))/(4*b - 8*d) - cos(a + b*x)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*cos(c + d*x),
        variable=x,
        num_steps=4,
        integral=-cos(a + c + x*(b + d))/(2*b + 2*d) - cos(a - c + x*(b - d))/(2*b - 2*d),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sec(b*x + c),
        variable=x,
        num_steps=3,
        integral=x*sin(a - c) - log(cos(b*x + c))*cos(a - c)/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sec(b*x + c)**2,
        variable=x,
        num_steps=4,
        integral=sin(a - c)*atanh(sin(b*x + c))/b + cos(a - c)*sec(b*x + c)/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sec(b*x + c)**3,
        variable=x,
        num_steps=5,
        integral=sin(a - c)*tan(b*x + c)/b + cos(a - c)*sec(b*x + c)**2/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sec(b*x + c)**4,
        variable=x,
        num_steps=5,
        integral=sin(a - c)*tan(b*x + c)*sec(b*x + c)/(2*b) + sin(a - c)*atanh(sin(b*x + c))/(2*b) + cos(a - c)*sec(b*x + c)**3/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sec(b*x + c)**5,
        variable=x,
        num_steps=5,
        integral=sin(a - c)*tan(b*x + c)**3/(3*b) + sin(a - c)*tan(b*x + c)/b + cos(a - c)*sec(b*x + c)**4/(4*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*sec(b*x + c)**6,
        variable=x,
        num_steps=6,
        integral=sin(a - c)*tan(b*x + c)*sec(b*x + c)**3/(4*b) + 3*sin(a - c)*tan(b*x + c)*sec(b*x + c)/(8*b) + 3*sin(a - c)*atanh(sin(b*x + c))/(8*b) + cos(a - c)*sec(b*x + c)**5/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*cos(c + d*x)**n,
        variable=x,
        num_steps=11,
        integral=-2**(-n - 2)*I*(exp(I*(c + d*x)) + exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) - I*x*(2*b + d*n) - I*(2*a + c*n))*hyper((-n, -b/d - n/2), (-b/d - n/2 + 1,), -exp(2*I*(c + d*x)))/((2*b + d*n)*(exp(2*I*c + 2*I*d*x) + 1)**n) + 2**(-n - 2)*I*(exp(I*(c + d*x)) + exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) + I*x*(2*b - d*n) + I*(2*a - c*n))*hyper((-n, b/d - n/2), (b/d - n/2 + 1,), -exp(2*I*(c + d*x)))/((2*b - d*n)*(exp(2*I*c + 2*I*d*x) + 1)**n) + 2**(-n - 1)*I*(exp(I*(c + d*x)) + exp(-I*(c + d*x)))**n*hyper((-n, -n/2), (1 - n/2,), -exp(2*I*(c + d*x)))/(d*n*(exp(2*I*(c + d*x)) + 1)**n),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*cos(c + d*x),
        variable=x,
        num_steps=5,
        integral=-sin(2*a + c + x*(2*b + d))/(8*b + 4*d) - sin(2*a - c + x*(2*b - d))/(8*b - 4*d) + sin(c + d*x)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*cos(c + d*x)**2,
        variable=x,
        num_steps=6,
        integral=x/4 - sin(2*a + 2*c + x*(2*b + 2*d))/(16*b + 16*d) - sin(2*a - 2*c + x*(2*b - 2*d))/(16*b - 16*d) + sin(2*c + 2*d*x)/(8*d) - sin(2*a + 2*b*x)/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2*cos(c + d*x)**3,
        variable=x,
        num_steps=8,
        integral=-sin(2*a + 3*c + x*(2*b + 3*d))/(32*b + 48*d) - 3*sin(2*a + c + x*(2*b + d))/(32*b + 16*d) - 3*sin(2*a - c + x*(2*b - d))/(32*b - 16*d) - sin(2*a - 3*c + x*(2*b - 3*d))/(32*b - 48*d) + 3*sin(c + d*x)/(8*d) + sin(3*c + 3*d*x)/(24*d),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*cos(c + d*x)**n,
        variable=x,
        num_steps=14,
        integral=2**(-n - 3)*(exp(I*(c + d*x)) + exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) - I*x*(3*b + d*n) - I*(3*a + c*n))*hyper((-n, -(3*b + d*n)/(2*d)), (-3*b/(2*d) - n/2 + 1,), -exp(2*I*(c + d*x)))/((3*b + d*n)*(exp(2*I*c + 2*I*d*x) + 1)**n) + 2**(-n - 3)*(exp(I*(c + d*x)) + exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) + I*x*(3*b - d*n) + I*(3*a - c*n))*hyper((-n, 3*b/(2*d) - n/2), (3*b/(2*d) - n/2 + 1,), -exp(2*I*(c + d*x)))/((3*b - d*n)*(exp(2*I*c + 2*I*d*x) + 1)**n) - 3*2**(-n - 3)*(exp(I*(c + d*x)) + exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) - I*x*(b + d*n) - I*(a + c*n))*hyper((-n, -(b + d*n)/(2*d)), (1 - (b + d*n)/(2*d),), -exp(2*I*(c + d*x)))/((b + d*n)*(exp(2*I*c + 2*I*d*x) + 1)**n) - 3*2**(-n - 3)*(exp(I*(c + d*x)) + exp(-I*(c + d*x)))**n*exp(I*n*(c + d*x) + I*x*(b - d*n) + I*(a - c*n))*hyper((-n, (b - d*n)/(2*d)), (b/(2*d) - n/2 + 1,), -exp(2*I*(c + d*x)))/((b - d*n)*(exp(2*I*c + 2*I*d*x) + 1)**n),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*cos(c + d*x),
        variable=x,
        num_steps=6,
        integral=cos(3*a + c + x*(3*b + d))/(24*b + 8*d) + cos(3*a - c + x*(3*b - d))/(24*b - 8*d) - 3*cos(a + c + x*(b + d))/(8*b + 8*d) - 3*cos(a - c + x*(b - d))/(8*b - 8*d),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*cos(c + d*x)**2,
        variable=x,
        num_steps=8,
        integral=cos(3*a + 2*c + x*(3*b + 2*d))/(48*b + 32*d) + cos(3*a - 2*c + x*(3*b - 2*d))/(48*b - 32*d) - 3*cos(a + 2*c + x*(b + 2*d))/(16*b + 32*d) - 3*cos(a - 2*c + x*(b - 2*d))/(16*b - 32*d) - 3*cos(a + b*x)/(8*b) + cos(3*a + 3*b*x)/(24*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3*cos(c + d*x)**3,
        variable=x,
        num_steps=10,
        integral=cos(3*a + 3*c + x*(3*b + 3*d))/(96*b + 96*d) + 3*cos(3*a + c + x*(3*b + d))/(96*b + 32*d) + 3*cos(3*a - c + x*(3*b - d))/(96*b - 32*d) + cos(3*a - 3*c + x*(3*b - 3*d))/(96*b - 96*d) - 3*cos(a + 3*c + x*(b + 3*d))/(32*b + 96*d) - 9*cos(a + c + x*(b + d))/(32*b + 32*d) - 9*cos(a - c + x*(b - d))/(32*b - 32*d) - 3*cos(a - 3*c + x*(b - 3*d))/(32*b - 96*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)/sin(b*x + c),
        variable=x,
        num_steps=3,
        integral=-x*sin(a - c) + log(sin(b*x + c))*cos(a - c)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)/sin(b*x + c)**2,
        variable=x,
        num_steps=4,
        integral=sin(a - c)*atanh(cos(b*x + c))/b - cos(a - c)*csc(b*x + c)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)/sin(b*x + c)**3,
        variable=x,
        num_steps=5,
        integral=sin(a - c)*cot(b*x + c)/b - cos(a - c)*csc(b*x + c)**2/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*tan(b*x + c)**3,
        variable=x,
        num_steps=9,
        integral=sin(a - c)*sec(b*x + c)/b + sin(a + b*x)/b + cos(a - c)*tan(b*x + c)*sec(b*x + c)/(2*b) - 3*cos(a - c)*atanh(sin(b*x + c))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*tan(b*x + c)**2,
        variable=x,
        num_steps=6,
        integral=sin(a - c)*atanh(sin(b*x + c))/b + cos(a - c)*sec(b*x + c)/b + cos(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*tan(b*x + c),
        variable=x,
        num_steps=3,
        integral=-sin(a + b*x)/b + cos(a - c)*atanh(sin(b*x + c))/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*cot(b*x + c),
        variable=x,
        num_steps=3,
        integral=-sin(a - c)*atanh(cos(b*x + c))/b + sin(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*cot(b*x + c)**2,
        variable=x,
        num_steps=6,
        integral=-sin(a - c)*csc(b*x + c)/b - cos(a - c)*atanh(cos(b*x + c))/b + cos(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*cot(b*x + c)**3,
        variable=x,
        num_steps=9,
        integral=-sin(a - c)*cot(b*x + c)*csc(b*x + c)/(2*b) + 3*sin(a - c)*atanh(cos(b*x + c))/(2*b) - sin(a + b*x)/b - cos(a - c)*csc(b*x + c)/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*tan(c + d*x),
        variable=x,
        num_steps=6,
        integral=-I*exp(I*(a + b*x))*hyper((1, b/(2*d)), (b/(2*d) + 1,), -exp(2*I*(c + d*x)))/b + I*exp(I*(a + b*x))/(2*b) - I*exp(-I*(a + b*x))*hyper((1, -b/(2*d)), (-b/(2*d) + 1,), -exp(2*I*(c + d*x)))/b + I*exp(-I*(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)*cot(c + d*x),
        variable=x,
        num_steps=6,
        integral=I*exp(I*(a + b*x))*hyper((1, b/(2*d)), (b/(2*d) + 1,), exp(2*I*(c + d*x)))/b - I*exp(I*(a + b*x))/(2*b) + I*exp(-I*(a + b*x))*hyper((1, -b/(2*d)), (-b/(2*d) + 1,), exp(2*I*(c + d*x)))/b - I*exp(-I*(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*cos(c + d*x)**3,
        variable=x,
        num_steps=6,
        integral=sin(a + 3*c + x*(b + 3*d))/(8*b + 24*d) + 3*sin(a + c + x*(b + d))/(8*b + 8*d) + 3*sin(a - c + x*(b - d))/(8*b - 8*d) + sin(a - 3*c + x*(b - 3*d))/(8*b - 24*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*cos(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=sin(a + 2*c + x*(b + 2*d))/(4*b + 8*d) + sin(a - 2*c + x*(b - 2*d))/(4*b - 8*d) + sin(a + b*x)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*cos(c + d*x),
        variable=x,
        num_steps=4,
        integral=sin(a + c + x*(b + d))/(2*b + 2*d) + sin(a - c + x*(b - d))/(2*b - 2*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*sec(b*x + c),
        variable=x,
        num_steps=3,
        integral=x*cos(a - c) + log(cos(b*x + c))*sin(a - c)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*sec(b*x + c)**2,
        variable=x,
        num_steps=4,
        integral=-sin(a - c)*sec(b*x + c)/b + cos(a - c)*atanh(sin(b*x + c))/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*sec(b*x + c)**3,
        variable=x,
        num_steps=5,
        integral=-sin(a - c)*sec(b*x + c)**2/(2*b) + cos(a - c)*tan(b*x + c)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2*cos(c + d*x)**3,
        variable=x,
        num_steps=8,
        integral=sin(2*a + 3*c + x*(2*b + 3*d))/(32*b + 48*d) + 3*sin(2*a + c + x*(2*b + d))/(32*b + 16*d) + 3*sin(2*a - c + x*(2*b - d))/(32*b - 16*d) + sin(2*a - 3*c + x*(2*b - 3*d))/(32*b - 48*d) + 3*sin(c + d*x)/(8*d) + sin(3*c + 3*d*x)/(24*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2*cos(c + d*x)**2,
        variable=x,
        num_steps=6,
        integral=x/4 + sin(2*a + 2*c + x*(2*b + 2*d))/(16*b + 16*d) + sin(2*a - 2*c + x*(2*b - 2*d))/(16*b - 16*d) + sin(2*c + 2*d*x)/(8*d) + sin(2*a + 2*b*x)/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3*cos(c + d*x)**3,
        variable=x,
        num_steps=10,
        integral=sin(3*a + 3*c + x*(3*b + 3*d))/(96*b + 96*d) + 3*sin(3*a + c + x*(3*b + d))/(96*b + 32*d) + 3*sin(3*a - c + x*(3*b - d))/(96*b - 32*d) + sin(3*a - 3*c + x*(3*b - 3*d))/(96*b - 96*d) + 3*sin(a + 3*c + x*(b + 3*d))/(32*b + 96*d) + 9*sin(a + c + x*(b + d))/(32*b + 32*d) + 9*sin(a - c + x*(b - d))/(32*b - 32*d) + 3*sin(a - 3*c + x*(b - 3*d))/(32*b - 96*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*tan(b*x + c)**3,
        variable=x,
        num_steps=9,
        integral=-sin(a - c)*tan(b*x + c)*sec(b*x + c)/(2*b) + 3*sin(a - c)*atanh(sin(b*x + c))/(2*b) + cos(a - c)*sec(b*x + c)/b + cos(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*tan(b*x + c)**2,
        variable=x,
        num_steps=6,
        integral=-sin(a - c)*sec(b*x + c)/b - sin(a + b*x)/b + cos(a - c)*atanh(sin(b*x + c))/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*tan(b*x + c),
        variable=x,
        num_steps=3,
        integral=-sin(a - c)*atanh(sin(b*x + c))/b - cos(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*cot(b*x + c),
        variable=x,
        num_steps=3,
        integral=-cos(a - c)*atanh(cos(b*x + c))/b + cos(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*cot(b*x + c)**2,
        variable=x,
        num_steps=6,
        integral=sin(a - c)*atanh(cos(b*x + c))/b - sin(a + b*x)/b - cos(a - c)*csc(b*x + c)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*cot(b*x + c)**3,
        variable=x,
        num_steps=9,
        integral=sin(a - c)*csc(b*x + c)/b - cos(a - c)*cot(b*x + c)*csc(b*x + c)/(2*b) + 3*cos(a - c)*atanh(cos(b*x + c))/(2*b) - cos(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*tan(c + d*x),
        variable=x,
        num_steps=6,
        integral=exp(I*(a + b*x))*hyper((1, b/(2*d)), (b/(2*d) + 1,), -exp(2*I*(c + d*x)))/b - exp(I*(a + b*x))/(2*b) - exp(-I*(a + b*x))*hyper((1, -b/(2*d)), (-b/(2*d) + 1,), -exp(2*I*(c + d*x)))/b + exp(-I*(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*cot(c + d*x),
        variable=x,
        num_steps=6,
        integral=-exp(I*(a + b*x))*hyper((1, b/(2*d)), (b/(2*d) + 1,), exp(2*I*(c + d*x)))/b + exp(I*(a + b*x))/(2*b) + exp(-I*(a + b*x))*hyper((1, -b/(2*d)), (-b/(2*d) + 1,), exp(2*I*(c + d*x)))/b - exp(-I*(a + b*x))/(2*b),
    ),
]
