# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 4 Trig functions/4.7 Miscellaneous/4.7.5 x^m trig(a+b log(c x^n))^p.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '4 Trig functions/4.7 Miscellaneous/4.7.5 x^m trig(a+b log(c x^n))^p.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, c, d, e, m, n, p = symbols('a b c d e m n p')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=x**2*sin(a + b*log(c*x**n)),
        variable=x,
        num_steps=1,
        integral=-b*n*x**3*cos(a + b*log(c*x**n))/(b**2*n**2 + 9) + 3*x**3*sin(a + b*log(c*x**n))/(b**2*n**2 + 9),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(a + b*log(c*x**n)),
        variable=x,
        num_steps=1,
        integral=-b*n*x**2*cos(a + b*log(c*x**n))/(b**2*n**2 + 4) + 2*x**2*sin(a + b*log(c*x**n))/(b**2*n**2 + 4),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n)),
        variable=x,
        num_steps=1,
        integral=-b*n*x*cos(a + b*log(c*x**n))/(b**2*n**2 + 1) + x*sin(a + b*log(c*x**n))/(b**2*n**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))/x,
        variable=x,
        num_steps=2,
        integral=-cos(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))/x**2,
        variable=x,
        num_steps=1,
        integral=-b*n*cos(a + b*log(c*x**n))/(x*(b**2*n**2 + 1)) - sin(a + b*log(c*x**n))/(x*(b**2*n**2 + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))/x**3,
        variable=x,
        num_steps=1,
        integral=-b*n*cos(a + b*log(c*x**n))/(x**2*(b**2*n**2 + 4)) - 2*sin(a + b*log(c*x**n))/(x**2*(b**2*n**2 + 4)),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sin(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=2,
        integral=2*b**2*n**2*x**3/(12*b**2*n**2 + 27) - 2*b*n*x**3*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(4*b**2*n**2 + 9) + 3*x**3*sin(a + b*log(c*x**n))**2/(4*b**2*n**2 + 9),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=2,
        integral=b**2*n**2*x**2/(4*b**2*n**2 + 4) - b*n*x**2*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(2*b**2*n**2 + 2) + x**2*sin(a + b*log(c*x**n))**2/(2*b**2*n**2 + 2),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=2,
        integral=2*b**2*n**2*x/(4*b**2*n**2 + 1) - 2*b*n*x*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(4*b**2*n**2 + 1) + x*sin(a + b*log(c*x**n))**2/(4*b**2*n**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**2/x,
        variable=x,
        num_steps=3,
        integral=log(x)/2 - sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**2/x**2,
        variable=x,
        num_steps=2,
        integral=-2*b**2*n**2/(x*(4*b**2*n**2 + 1)) - 2*b*n*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(x*(4*b**2*n**2 + 1)) - sin(a + b*log(c*x**n))**2/(x*(4*b**2*n**2 + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**2/x**3,
        variable=x,
        num_steps=2,
        integral=-b**2*n**2/(x**2*(4*b**2*n**2 + 4)) - b*n*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(x**2*(2*b**2*n**2 + 2)) - sin(a + b*log(c*x**n))**2/(x**2*(2*b**2*n**2 + 2)),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sin(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=2,
        integral=-2*b**3*n**3*x**3*cos(a + b*log(c*x**n))/(3*b**4*n**4 + 30*b**2*n**2 + 27) + 2*b**2*n**2*x**3*sin(a + b*log(c*x**n))/(b**4*n**4 + 10*b**2*n**2 + 9) - b*n*x**3*sin(a + b*log(c*x**n))**2*cos(a + b*log(c*x**n))/(3*b**2*n**2 + 3) + x**3*sin(a + b*log(c*x**n))**3/(3*b**2*n**2 + 3),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=2,
        integral=-6*b**3*n**3*x**2*cos(a + b*log(c*x**n))/(9*b**4*n**4 + 40*b**2*n**2 + 16) + 12*b**2*n**2*x**2*sin(a + b*log(c*x**n))/(9*b**4*n**4 + 40*b**2*n**2 + 16) - 3*b*n*x**2*sin(a + b*log(c*x**n))**2*cos(a + b*log(c*x**n))/(9*b**2*n**2 + 4) + 2*x**2*sin(a + b*log(c*x**n))**3/(9*b**2*n**2 + 4),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=2,
        integral=-6*b**3*n**3*x*cos(a + b*log(c*x**n))/(9*b**4*n**4 + 10*b**2*n**2 + 1) + 6*b**2*n**2*x*sin(a + b*log(c*x**n))/(9*b**4*n**4 + 10*b**2*n**2 + 1) - 3*b*n*x*sin(a + b*log(c*x**n))**2*cos(a + b*log(c*x**n))/(9*b**2*n**2 + 1) + x*sin(a + b*log(c*x**n))**3/(9*b**2*n**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**3/x,
        variable=x,
        num_steps=3,
        integral=cos(a + b*log(c*x**n))**3/(3*b*n) - cos(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**3/x**2,
        variable=x,
        num_steps=2,
        integral=-6*b**3*n**3*cos(a + b*log(c*x**n))/(x*(9*b**4*n**4 + 10*b**2*n**2 + 1)) - 6*b**2*n**2*sin(a + b*log(c*x**n))/(x*(9*b**4*n**4 + 10*b**2*n**2 + 1)) - 3*b*n*sin(a + b*log(c*x**n))**2*cos(a + b*log(c*x**n))/(x*(9*b**2*n**2 + 1)) - sin(a + b*log(c*x**n))**3/(x*(9*b**2*n**2 + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**3/x**3,
        variable=x,
        num_steps=2,
        integral=-6*b**3*n**3*cos(a + b*log(c*x**n))/(x**2*(9*b**4*n**4 + 40*b**2*n**2 + 16)) - 12*b**2*n**2*sin(a + b*log(c*x**n))/(x**2*(9*b**4*n**4 + 40*b**2*n**2 + 16)) - 3*b*n*sin(a + b*log(c*x**n))**2*cos(a + b*log(c*x**n))/(x**2*(9*b**2*n**2 + 4)) - 2*sin(a + b*log(c*x**n))**3/(x**2*(9*b**2*n**2 + 4)),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sin(a + b*log(c*x**n))**4,
        variable=x,
        num_steps=3,
        integral=8*b**4*n**4*x**3/(64*b**4*n**4 + 180*b**2*n**2 + 81) - 24*b**3*n**3*x**3*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(64*b**4*n**4 + 180*b**2*n**2 + 81) + 36*b**2*n**2*x**3*sin(a + b*log(c*x**n))**2/(64*b**4*n**4 + 180*b**2*n**2 + 81) - 4*b*n*x**3*sin(a + b*log(c*x**n))**3*cos(a + b*log(c*x**n))/(16*b**2*n**2 + 9) + 3*x**3*sin(a + b*log(c*x**n))**4/(16*b**2*n**2 + 9),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(a + b*log(c*x**n))**4,
        variable=x,
        num_steps=3,
        integral=3*b**4*n**4*x**2/(16*b**4*n**4 + 20*b**2*n**2 + 4) - 3*b**3*n**3*x**2*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(8*b**4*n**4 + 10*b**2*n**2 + 2) + 3*b**2*n**2*x**2*sin(a + b*log(c*x**n))**2/(8*b**4*n**4 + 10*b**2*n**2 + 2) - b*n*x**2*sin(a + b*log(c*x**n))**3*cos(a + b*log(c*x**n))/(4*b**2*n**2 + 1) + x**2*sin(a + b*log(c*x**n))**4/(8*b**2*n**2 + 2),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**4,
        variable=x,
        num_steps=3,
        integral=24*b**4*n**4*x/(64*b**4*n**4 + 20*b**2*n**2 + 1) - 24*b**3*n**3*x*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(64*b**4*n**4 + 20*b**2*n**2 + 1) + 12*b**2*n**2*x*sin(a + b*log(c*x**n))**2/(64*b**4*n**4 + 20*b**2*n**2 + 1) - 4*b*n*x*sin(a + b*log(c*x**n))**3*cos(a + b*log(c*x**n))/(16*b**2*n**2 + 1) + x*sin(a + b*log(c*x**n))**4/(16*b**2*n**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**4/x,
        variable=x,
        num_steps=4,
        integral=3*log(x)/8 - sin(a + b*log(c*x**n))**3*cos(a + b*log(c*x**n))/(4*b*n) - 3*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(8*b*n),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**4/x**2,
        variable=x,
        num_steps=3,
        integral=-24*b**4*n**4/(x*(64*b**4*n**4 + 20*b**2*n**2 + 1)) - 24*b**3*n**3*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(x*(64*b**4*n**4 + 20*b**2*n**2 + 1)) - 12*b**2*n**2*sin(a + b*log(c*x**n))**2/(x*(64*b**4*n**4 + 20*b**2*n**2 + 1)) - 4*b*n*sin(a + b*log(c*x**n))**3*cos(a + b*log(c*x**n))/(x*(16*b**2*n**2 + 1)) - sin(a + b*log(c*x**n))**4/(x*(16*b**2*n**2 + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**4/x**3,
        variable=x,
        num_steps=3,
        integral=-3*b**4*n**4/(x**2*(16*b**4*n**4 + 20*b**2*n**2 + 4)) - 3*b**3*n**3*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(x**2*(8*b**4*n**4 + 10*b**2*n**2 + 2)) - 3*b**2*n**2*sin(a + b*log(c*x**n))**2/(x**2*(8*b**4*n**4 + 10*b**2*n**2 + 2)) - b*n*sin(a + b*log(c*x**n))**3*cos(a + b*log(c*x**n))/(x**2*(4*b**2*n**2 + 1)) - sin(a + b*log(c*x**n))**4/(x**2*(8*b**2*n**2 + 2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(log(a + b*x)),
        variable=x,
        num_steps=2,
        integral=(a + b*x)*sin(log(a + b*x))/(2*b) - (a + b*x)*cos(log(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sin(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)),
        variable=x,
        num_steps=3,
        integral=-x**(m + 1)*(c*x**n)**((m + 1)/n)*exp(a*(m + 1)/(n*sqrt(-(m + 1)**2/n**2)))/(4*n*sqrt(-(m + 1)**2/n**2)) + x**(m + 1)*(m + 1)*exp(a*n*sqrt(-(m + 1)**2/n**2)/(m + 1))*log(x)/(2*n*(c*x**n)**((m + 1)/n)*sqrt(-(m + 1)**2/n**2)),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sin(a + 3*sqrt(-1/n**2)*log(c*x**n)),
        variable=x,
        num_steps=3,
        integral=n*x**3*sqrt(-1/n**2)*(c*x**n)**(3/n)*exp(-a*n*sqrt(-1/n**2))/12 - n*x**3*sqrt(-1/n**2)*exp(a*n*sqrt(-1/n**2))*log(x)/(2*(c*x**n)**(3/n)),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(a + 2*sqrt(-1/n**2)*log(c*x**n)),
        variable=x,
        num_steps=3,
        integral=n*x**2*sqrt(-1/n**2)*(c*x**n)**(2/n)*exp(-a*n*sqrt(-1/n**2))/8 - n*x**2*sqrt(-1/n**2)*exp(a*n*sqrt(-1/n**2))*log(x)/(2*(c*x**n)**(2/n)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + sqrt(-1/n**2)*log(c*x**n)),
        variable=x,
        num_steps=3,
        integral=n*x*sqrt(-1/n**2)*(c*x**n)**(1/n)*exp(-a*n*sqrt(-1/n**2))/4 - n*x*sqrt(-1/n**2)*exp(a*n*sqrt(-1/n**2))*log(x)/(2*(c*x**n)**(1/n)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a)/x,
        variable=x,
        num_steps=2,
        integral=log(x)*sin(a),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + sqrt(-1/n**2)*log(c*x**n))/x**2,
        variable=x,
        num_steps=3,
        integral=n*sqrt(-1/n**2)*(c*x**n)**(1/n)*exp(-a*n*sqrt(-1/n**2))*log(x)/(2*x) + n*sqrt(-1/n**2)*exp(a*n*sqrt(-1/n**2))/(4*x*(c*x**n)**(1/n)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + 2*sqrt(-1/n**2)*log(c*x**n))/x**3,
        variable=x,
        num_steps=3,
        integral=n*sqrt(-1/n**2)*(c*x**n)**(2/n)*exp(-a*n*sqrt(-1/n**2))*log(x)/(2*x**2) + n*sqrt(-1/n**2)*exp(a*n*sqrt(-1/n**2))/(8*x**2*(c*x**n)**(2/n)),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sin(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)/2)**2,
        variable=x,
        num_steps=3,
        integral=-x**(m + 1)*(c*x**n)**((m + 1)/n)*exp(-2*a*n*sqrt(-(m + 1)**2/n**2)/(m + 1))/(8*m + 8) + x**(m + 1)/(2*m + 2) - x**(m + 1)*exp(2*a*n*sqrt(-(m + 1)**2/n**2)/(m + 1))*log(x)/(4*(c*x**n)**((m + 1)/n)),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sin(a + 3*sqrt(-1/n**2)*log(c*x**n)/2)**2,
        variable=x,
        num_steps=3,
        integral=-x**3*(c*x**n)**(3/n)*exp(-2*a*n*sqrt(-1/n**2))/24 + x**3/6 - x**3*exp(2*a*n*sqrt(-1/n**2))*log(x)/(4*(c*x**n)**(3/n)),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(a + sqrt(-1/n**2)*log(c*x**n))**2,
        variable=x,
        num_steps=3,
        integral=-x**2*(c*x**n)**(2/n)*exp(-2*a*n*sqrt(-1/n**2))/16 + x**2/4 - x**2*exp(2*a*n*sqrt(-1/n**2))*log(x)/(4*(c*x**n)**(2/n)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + sqrt(-1/n**2)*log(c*x**n)/2)**2,
        variable=x,
        num_steps=3,
        integral=-x*(c*x**n)**(1/n)*exp(-2*a*n*sqrt(-1/n**2))/8 + x/2 - x*exp(2*a*n*sqrt(-1/n**2))*log(x)/(4*(c*x**n)**(1/n)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a)**2/x,
        variable=x,
        num_steps=2,
        integral=log(x)*sin(a)**2,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + sqrt(-1/n**2)*log(c*x**n)/2)**2/x**2,
        variable=x,
        num_steps=3,
        integral=-(c*x**n)**(1/n)*exp(-2*a*n*sqrt(-1/n**2))*log(x)/(4*x) - 1/(2*x) + exp(2*a*n*sqrt(-1/n**2))/(8*x*(c*x**n)**(1/n)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + sqrt(-1/n**2)*log(c*x**n))**2/x**3,
        variable=x,
        num_steps=3,
        integral=-(c*x**n)**(2/n)*exp(-2*a*n*sqrt(-1/n**2))*log(x)/(4*x**2) - 1/(4*x**2) + exp(2*a*n*sqrt(-1/n**2))/(16*x**2*(c*x**n)**(2/n)),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sin(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)/2)**3,
        variable=x,
        num_steps=2,
        integral=6*n*x**(m + 1)*sqrt(-(m + 1)**2/n**2)*sin(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)/2)**2*cos(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)/2)/(5*(m + 1)**2) - 4*n*x**(m + 1)*sqrt(-(m + 1)**2/n**2)*cos(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)/2)/(5*(m + 1)**2) - 4*x**(m + 1)*sin(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)/2)**3/(5*m + 5) + 8*x**(m + 1)*sin(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)/2)/(5*m + 5),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sin(a + sqrt(-1/n**2)*log(c*x**n))**3,
        variable=x,
        num_steps=3,
        integral=-n*x**3*sqrt(-1/n**2)*(c*x**n)**(3/n)*exp(-3*a*n*sqrt(-1/n**2))/48 + 3*n*x**3*sqrt(-1/n**2)*(c*x**n)**(1/n)*exp(-a*n*sqrt(-1/n**2))/32 - 3*n*x**3*sqrt(-1/n**2)*exp(a*n*sqrt(-1/n**2))/(16*(c*x**n)**(1/n)) + n*x**3*sqrt(-1/n**2)*exp(3*a*n*sqrt(-1/n**2))*log(x)/(8*(c*x**n)**(3/n)),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(a + 2*sqrt(-1/n**2)*log(c*x**n)/3)**3,
        variable=x,
        num_steps=3,
        integral=9*n*x**2*sqrt(-1/n**2)*(c*x**n)**(2/(3*n))*exp(-a*n*sqrt(-1/n**2))/64 - n*x**2*sqrt(-1/n**2)*(c*x**n)**(2/n)*exp(-3*a*n*sqrt(-1/n**2))/32 + n*x**2*sqrt(-1/n**2)*exp(3*a*n*sqrt(-1/n**2))*log(x)/(8*(c*x**n)**(2/n)) - 9*n*x**2*sqrt(-1/n**2)*exp(a*n*sqrt(-1/n**2))/(32*(c*x**n)**(2/(3*n))),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + sqrt(-1/n**2)*log(c*x**n)/3)**3,
        variable=x,
        num_steps=3,
        integral=9*n*x*sqrt(-1/n**2)*(c*x**n)**(1/(3*n))*exp(-a*n*sqrt(-1/n**2))/32 - n*x*sqrt(-1/n**2)*(c*x**n)**(1/n)*exp(-3*a*n*sqrt(-1/n**2))/16 + n*x*sqrt(-1/n**2)*exp(3*a*n*sqrt(-1/n**2))*log(x)/(8*(c*x**n)**(1/n)) - 9*n*x*sqrt(-1/n**2)*exp(a*n*sqrt(-1/n**2))/(16*(c*x**n)**(1/(3*n))),
    ),
    RubiTestSuiteCase(
        integrand=sin(a)**3/x,
        variable=x,
        num_steps=2,
        integral=log(x)*sin(a)**3,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + sqrt(-1/n**2)*log(c*x**n)/3)**3/x**2,
        variable=x,
        num_steps=3,
        integral=-9*n*sqrt(-1/n**2)*(c*x**n)**(1/(3*n))*exp(-a*n*sqrt(-1/n**2))/(16*x) - n*sqrt(-1/n**2)*(c*x**n)**(1/n)*exp(-3*a*n*sqrt(-1/n**2))*log(x)/(8*x) - n*sqrt(-1/n**2)*exp(3*a*n*sqrt(-1/n**2))/(16*x*(c*x**n)**(1/n)) + 9*n*sqrt(-1/n**2)*exp(a*n*sqrt(-1/n**2))/(32*x*(c*x**n)**(1/(3*n))),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + 2*sqrt(-1/n**2)*log(c*x**n)/3)**3/x**3,
        variable=x,
        num_steps=3,
        integral=-9*n*sqrt(-1/n**2)*(c*x**n)**(2/(3*n))*exp(-a*n*sqrt(-1/n**2))/(32*x**2) - n*sqrt(-1/n**2)*(c*x**n)**(2/n)*exp(-3*a*n*sqrt(-1/n**2))*log(x)/(8*x**2) - n*sqrt(-1/n**2)*exp(3*a*n*sqrt(-1/n**2))/(32*x**2*(c*x**n)**(2/n)) + 9*n*sqrt(-1/n**2)*exp(a*n*sqrt(-1/n**2))/(64*x**2*(c*x**n)**(2/(3*n))),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sin(a + sqrt(-(m + 1)**2)*log(c*x**2)/2),
        variable=x,
        num_steps=3,
        integral=x**(m + 1)*(c*x**2)**(-m/2 + sympy.S(-1)/2)*(m + 1)*exp(a*sqrt(-(m + 1)**2)/(m + 1))*log(x)/(2*sqrt(-(m + 1)**2)) - x**(m + 1)*(c*x**2)**(m/2 + sympy.S.Half)*exp(a*(m + 1)/sqrt(-(m + 1)**2))/(4*sqrt(-(m + 1)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + I*log(c*x**2)/2),
        variable=x,
        num_steps=3,
        integral=I*c*x**3*exp(-I*a)/(4*sqrt(c*x**2)) - I*x*exp(I*a)*log(x)/(2*sqrt(c*x**2)),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sin(a + sqrt(-(m + 1)**2)*log(c*x**2)/4)**2,
        variable=x,
        num_steps=3,
        integral=-x**(m + 1)*(c*x**2)**(-m/2 + sympy.S(-1)/2)*exp(-2*a*(m + 1)/sqrt(-(m + 1)**2))*log(x)/4 - x**(m + 1)*(c*x**2)**(m/2 + sympy.S.Half)*exp(2*a*(m + 1)/sqrt(-(m + 1)**2))/(8*m + 8) + x**(m + 1)/(2*m + 2),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + I*log(c*x**2)/4)**2,
        variable=x,
        num_steps=3,
        integral=-c*x**3*exp(-2*I*a)/(8*sqrt(c*x**2)) + x/2 - x*exp(2*I*a)*log(x)/(4*sqrt(c*x**2)),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sin(a + sqrt(-(m + 1)**2)*log(c*x**2)/6)**3,
        variable=x,
        num_steps=3,
        integral=-x**(m + 1)*(c*x**2)**(-m/2 + sympy.S(-1)/2)*(m + 1)*exp(-3*a*(m + 1)/sqrt(-(m + 1)**2))*log(x)/(8*sqrt(-(m + 1)**2)) + 9*x**(m + 1)*(c*x**2)**(-m/6 + sympy.S(-1)/6)*exp(a*sqrt(-(m + 1)**2)/(m + 1))/(16*sqrt(-(m + 1)**2)) - 9*x**(m + 1)*(c*x**2)**(m/6 + sympy.S(1)/6)*exp(a*(m + 1)/sqrt(-(m + 1)**2))/(32*sqrt(-(m + 1)**2)) + x**(m + 1)*(c*x**2)**(m/2 + sympy.S.Half)*exp(3*a*(m + 1)/sqrt(-(m + 1)**2))/(16*sqrt(-(m + 1)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + I*log(c*x**2)/6)**3,
        variable=x,
        num_steps=3,
        integral=-I*c*x**3*exp(-3*I*a)/(16*sqrt(c*x**2)) + 9*I*x*(c*x**2)**(sympy.S(1)/6)*exp(-I*a)/32 + I*x*exp(3*I*a)*log(x)/(8*sqrt(c*x**2)) - 9*I*x*exp(I*a)/(16*(c*x**2)**(sympy.S(1)/6)),
    ),
    RubiTestSuiteCase(
        integrand=x*sqrt(sin(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x**2*sqrt(sin(a + b*log(c*x**n)))*hyper((sympy.S(-1)/2, sympy.S(-1)/4 - I/(b*n)), (sympy.S(3)/4 - I/(b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(sqrt(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)*(-I*b*n + 4)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sin(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x*sqrt(sin(a + b*log(c*x**n)))*hyper((sympy.S(-1)/2, -(b*n + 2*I)/(4*b*n)), (sympy.S(3)/4 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(sqrt(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)*(-I*b*n + 2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sin(a + b*log(c*x**n)))/x,
        variable=x,
        num_steps=2,
        integral=2*elliptic_e(a/2 + b*log(c*x**n)/2 - pi/4, 2)/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sin(a + b*log(c*x**n)))/x**2,
        variable=x,
        num_steps=3,
        integral=-2*sqrt(sin(a + b*log(c*x**n)))*hyper((sympy.S(-1)/2, sympy.S(-1)/4 + I/(2*b*n)), (sympy.S(3)/4 + I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(x*sqrt(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)*(I*b*n + 2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sin(a + b*log(c*x**n)))/x**3,
        variable=x,
        num_steps=3,
        integral=-2*sqrt(sin(a + b*log(c*x**n)))*hyper((sympy.S(-1)/2, sympy.S(-1)/4 + I/(b*n)), (sympy.S(3)/4 + I/(b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(x**2*sqrt(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)*(I*b*n + 4)),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(a + b*log(c*x**n))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*x**2*sin(a + b*log(c*x**n))**(sympy.S(3)/2)*hyper((sympy.S(-3)/2, sympy.S(-3)/4 - I/(b*n)), (sympy.S(1)/4 - I/(b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/((-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*(-3*I*b*n + 4)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*x*sin(a + b*log(c*x**n))**(sympy.S(3)/2)*hyper((sympy.S(-3)/2, sympy.S(-3)/4 - I/(2*b*n)), (sympy.S(1)/4 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/((-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*(-3*I*b*n + 2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**(sympy.S(3)/2)/x,
        variable=x,
        num_steps=3,
        integral=-2*sqrt(sin(a + b*log(c*x**n)))*cos(a + b*log(c*x**n))/(3*b*n) + 2*elliptic_f(a/2 + b*log(c*x**n)/2 - pi/4, 2)/(3*b*n),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**(sympy.S(3)/2)/x**2,
        variable=x,
        num_steps=3,
        integral=-2*sin(a + b*log(c*x**n))**(sympy.S(3)/2)*hyper((sympy.S(-3)/2, sympy.S(-3)/4 + I/(2*b*n)), (sympy.S(1)/4 + I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(x*(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*(3*I*b*n + 2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**(sympy.S(3)/2)/x**3,
        variable=x,
        num_steps=3,
        integral=-2*sin(a + b*log(c*x**n))**(sympy.S(3)/2)*hyper((sympy.S(-3)/2, sympy.S(-3)/4 + I/(b*n)), (sympy.S(1)/4 + I/(b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(x**2*(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*(3*I*b*n + 4)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(sin(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x*sqrt(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)*hyper((sympy.S.Half, sympy.S(1)/4 - I/(2*b*n)), (sympy.S(5)/4 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/((I*b*n + 2)*sqrt(sin(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(sin(a + b*log(c*x**n)))),
        variable=x,
        num_steps=2,
        integral=2*elliptic_f(a/2 + b*log(c*x**n)/2 - pi/4, 2)/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*x*(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*hyper((sympy.S(3)/2, sympy.S(3)/4 - I/(2*b*n)), (sympy.S(7)/4 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/((3*I*b*n + 2)*sin(a + b*log(c*x**n))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sin(a + b*log(c*x**n))**(sympy.S(3)/2)),
        variable=x,
        num_steps=3,
        integral=-2*elliptic_e(a/2 + b*log(c*x**n)/2 - pi/4, 2)/(b*n) - 2*cos(a + b*log(c*x**n))/(b*n*sqrt(sin(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**(sympy.S(-5)/2),
        variable=x,
        num_steps=3,
        integral=2*x*(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(5)/2)*hyper((sympy.S(5)/2, sympy.S(5)/4 - I/(2*b*n)), (sympy.S(9)/4 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/((5*I*b*n + 2)*sin(a + b*log(c*x**n))**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sin(a + b*log(c*x**n))**(sympy.S(5)/2)),
        variable=x,
        num_steps=3,
        integral=2*elliptic_f(a/2 + b*log(c*x**n)/2 - pi/4, 2)/(3*b*n) - 2*cos(a + b*log(c*x**n))/(3*b*n*sin(a + b*log(c*x**n))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a - 2*I*log(c*x))**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=(-c**4*x**4*exp(2*I*a) + 1)*exp(-2*I*a)/(2*c**4*x**3*sin(a - 2*I*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m*sin(d*(a + b*log(c*x**n)))**4,
        variable=x,
        num_steps=3,
        integral=24*b**4*d**4*n**4*(e*x)**(m + 1)/(e*(m + 1)*(4*b**2*d**2*n**2 + (m + 1)**2)*(16*b**2*d**2*n**2 + (m + 1)**2)) - 24*b**3*d**3*n**3*(e*x)**(m + 1)*sin(d*(a + b*log(c*x**n)))*cos(d*(a + b*log(c*x**n)))/(e*(4*b**2*d**2*n**2 + (m + 1)**2)*(16*b**2*d**2*n**2 + (m + 1)**2)) + 12*b**2*d**2*n**2*(e*x)**(m + 1)*(m + 1)*sin(d*(a + b*log(c*x**n)))**2/(e*(4*b**2*d**2*n**2 + (m + 1)**2)*(16*b**2*d**2*n**2 + (m + 1)**2)) - 4*b*d*n*(e*x)**(m + 1)*sin(d*(a + b*log(c*x**n)))**3*cos(d*(a + b*log(c*x**n)))/(e*(16*b**2*d**2*n**2 + (m + 1)**2)) + (e*x)**(m + 1)*(m + 1)*sin(d*(a + b*log(c*x**n)))**4/(e*(16*b**2*d**2*n**2 + (m + 1)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m*sin(d*(a + b*log(c*x**n)))**3,
        variable=x,
        num_steps=2,
        integral=-6*b**3*d**3*n**3*(e*x)**(m + 1)*cos(d*(a + b*log(c*x**n)))/(e*(b**2*d**2*n**2 + (m + 1)**2)*(9*b**2*d**2*n**2 + (m + 1)**2)) + 6*b**2*d**2*n**2*(e*x)**(m + 1)*(m + 1)*sin(d*(a + b*log(c*x**n)))/(e*(b**2*d**2*n**2 + (m + 1)**2)*(9*b**2*d**2*n**2 + (m + 1)**2)) - 3*b*d*n*(e*x)**(m + 1)*sin(d*(a + b*log(c*x**n)))**2*cos(d*(a + b*log(c*x**n)))/(e*(9*b**2*d**2*n**2 + (m + 1)**2)) + (e*x)**(m + 1)*(m + 1)*sin(d*(a + b*log(c*x**n)))**3/(e*(9*b**2*d**2*n**2 + (m + 1)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m*sin(d*(a + b*log(c*x**n)))**2,
        variable=x,
        num_steps=2,
        integral=2*b**2*d**2*n**2*(e*x)**(m + 1)/(e*(m + 1)*(4*b**2*d**2*n**2 + (m + 1)**2)) - 2*b*d*n*(e*x)**(m + 1)*sin(d*(a + b*log(c*x**n)))*cos(d*(a + b*log(c*x**n)))/(e*(4*b**2*d**2*n**2 + (m + 1)**2)) + (e*x)**(m + 1)*(m + 1)*sin(d*(a + b*log(c*x**n)))**2/(e*(4*b**2*d**2*n**2 + (m + 1)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m*sin(d*(a + b*log(c*x**n))),
        variable=x,
        num_steps=1,
        integral=-b*d*n*(e*x)**(m + 1)*cos(d*(a + b*log(c*x**n)))/(e*(b**2*d**2*n**2 + (m + 1)**2)) + (e*x)**(m + 1)*(m + 1)*sin(d*(a + b*log(c*x**n)))/(e*(b**2*d**2*n**2 + (m + 1)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m*sin(d*(a + b*log(c*x**n)))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*(e*x)**(m + 1)*sin(d*(a + b*log(c*x**n)))**(sympy.S(3)/2)*hyper((sympy.S(-3)/2, -(3*b*d*n + 2*I*m + 2*I)/(4*b*d*n)), (-(-b*d*n + 2*I*m + 2*I)/(4*b*d*n),), (c*x**n)**(2*I*b*d)*exp(2*I*a*d))/(e*(-(c*x**n)**(2*I*b*d)*exp(2*I*a*d) + 1)**(sympy.S(3)/2)*(-3*I*b*d*n + 2*m + 2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m*sqrt(sin(d*(a + b*log(c*x**n)))),
        variable=x,
        num_steps=3,
        integral=2*(e*x)**(m + 1)*sqrt(sin(d*(a + b*log(c*x**n))))*hyper((sympy.S(-1)/2, -(b*d*n + 2*I*m + 2*I)/(4*b*d*n)), (-(-3*b*d*n + 2*I*m + 2*I)/(4*b*d*n),), (c*x**n)**(2*I*b*d)*exp(2*I*a*d))/(e*sqrt(-(c*x**n)**(2*I*b*d)*exp(2*I*a*d) + 1)*(-I*b*d*n + 2*m + 2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m/sqrt(sin(d*(a + b*log(c*x**n)))),
        variable=x,
        num_steps=3,
        integral=2*(e*x)**(m + 1)*sqrt(-(c*x**n)**(2*I*b*d)*exp(2*I*a*d) + 1)*hyper((sympy.S.Half, -(-b*d*n + 2*I*m + 2*I)/(4*b*d*n)), (-(-5*b*d*n + 2*I*m + 2*I)/(4*b*d*n),), (c*x**n)**(2*I*b*d)*exp(2*I*a*d))/(e*(I*b*d*n + 2*m + 2)*sqrt(sin(d*(a + b*log(c*x**n))))),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m/sin(d*(a + b*log(c*x**n)))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*(e*x)**(m + 1)*(-(c*x**n)**(2*I*b*d)*exp(2*I*a*d) + 1)**(sympy.S(3)/2)*hyper((sympy.S(3)/2, -(-3*b*d*n + 2*I*m + 2*I)/(4*b*d*n)), (-(-7*b*d*n + 2*I*m + 2*I)/(4*b*d*n),), (c*x**n)**(2*I*b*d)*exp(2*I*a*d))/(e*(3*I*b*d*n + 2*m + 2)*sin(d*(a + b*log(c*x**n)))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m/sin(d*(a + b*log(c*x**n)))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*(e*x)**(m + 1)*(-(c*x**n)**(2*I*b*d)*exp(2*I*a*d) + 1)**(sympy.S(5)/2)*hyper((sympy.S(5)/2, -(-5*b*d*n + 2*I*m + 2*I)/(4*b*d*n)), (-(-9*b*d*n + 2*I*m + 2*I)/(4*b*d*n),), (c*x**n)**(2*I*b*d)*exp(2*I*a*d))/(e*(5*I*b*d*n + 2*m + 2)*sin(d*(a + b*log(c*x**n)))**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m*sin(d*(a + b*log(c*x**n)))**p,
        variable=x,
        num_steps=3,
        integral=(e*x)**(m + 1)*sin(d*(a + b*log(c*x**n)))**p*hyper((-p, -(b*d*n*p + I*m + I)/(2*b*d*n)), (-p/2 + 1 - I*(m + 1)/(2*b*d*n),), (c*x**n)**(2*I*b*d)*exp(2*I*a*d))/(e*(-(c*x**n)**(2*I*b*d)*exp(2*I*a*d) + 1)**p*(-I*b*d*n*p + m + 1)),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sin(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=3,
        integral=x**3*sin(a + b*log(c*x**n))**p*hyper((-p, -(b*n*p + 3*I)/(2*b*n)), (-p/2 + 1 - 3*I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/((-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**p*(-I*b*n*p + 3)),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=3,
        integral=x**2*sin(a + b*log(c*x**n))**p*hyper((-p, -p/2 - I/(b*n)), (-p/2 + 1 - I/(b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/((-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**p*(-I*b*n*p + 2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=3,
        integral=x*sin(a + b*log(c*x**n))**p*hyper((-p, -(b*n*p + I)/(2*b*n)), (-p/2 + 1 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/((-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**p*(-I*b*n*p + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**p/x,
        variable=x,
        num_steps=2,
        integral=sin(a + b*log(c*x**n))**(p + 1)*cos(a + b*log(c*x**n))*hyper((sympy.S.Half, p/2 + sympy.S.Half), (p/2 + sympy.S(3)/2,), sin(a + b*log(c*x**n))**2)/(b*n*(p + 1)*sqrt(cos(a + b*log(c*x**n))**2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**p/x**2,
        variable=x,
        num_steps=3,
        integral=-sin(a + b*log(c*x**n))**p*hyper((-p, -p/2 + I/(2*b*n)), (-p/2 + 1 + I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(x*(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**p*(I*b*n*p + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*log(c*x**n))**p/x**3,
        variable=x,
        num_steps=3,
        integral=-sin(a + b*log(c*x**n))**p*hyper((-p, -p/2 + I/(b*n)), (-p/2 + 1 + I/(b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(x**2*(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**p*(I*b*n*p + 2)),
    ),
    RubiTestSuiteCase(
        integrand=x**2*cos(a + b*log(c*x**n)),
        variable=x,
        num_steps=1,
        integral=b*n*x**3*sin(a + b*log(c*x**n))/(b**2*n**2 + 9) + 3*x**3*cos(a + b*log(c*x**n))/(b**2*n**2 + 9),
    ),
    RubiTestSuiteCase(
        integrand=x*cos(a + b*log(c*x**n)),
        variable=x,
        num_steps=1,
        integral=b*n*x**2*sin(a + b*log(c*x**n))/(b**2*n**2 + 4) + 2*x**2*cos(a + b*log(c*x**n))/(b**2*n**2 + 4),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n)),
        variable=x,
        num_steps=1,
        integral=b*n*x*sin(a + b*log(c*x**n))/(b**2*n**2 + 1) + x*cos(a + b*log(c*x**n))/(b**2*n**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))/x,
        variable=x,
        num_steps=2,
        integral=sin(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))/x**2,
        variable=x,
        num_steps=1,
        integral=b*n*sin(a + b*log(c*x**n))/(x*(b**2*n**2 + 1)) - cos(a + b*log(c*x**n))/(x*(b**2*n**2 + 1)),
    ),
    RubiTestSuiteCase(
        integrand=x**2*cos(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=2,
        integral=2*b**2*n**2*x**3/(12*b**2*n**2 + 27) + 2*b*n*x**3*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(4*b**2*n**2 + 9) + 3*x**3*cos(a + b*log(c*x**n))**2/(4*b**2*n**2 + 9),
    ),
    RubiTestSuiteCase(
        integrand=x*cos(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=2,
        integral=b**2*n**2*x**2/(4*b**2*n**2 + 4) + b*n*x**2*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(2*b**2*n**2 + 2) + x**2*cos(a + b*log(c*x**n))**2/(2*b**2*n**2 + 2),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=2,
        integral=2*b**2*n**2*x/(4*b**2*n**2 + 1) + 2*b*n*x*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(4*b**2*n**2 + 1) + x*cos(a + b*log(c*x**n))**2/(4*b**2*n**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**2/x,
        variable=x,
        num_steps=3,
        integral=log(x)/2 + sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**2/x**2,
        variable=x,
        num_steps=2,
        integral=-2*b**2*n**2/(x*(4*b**2*n**2 + 1)) + 2*b*n*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(x*(4*b**2*n**2 + 1)) - cos(a + b*log(c*x**n))**2/(x*(4*b**2*n**2 + 1)),
    ),
    RubiTestSuiteCase(
        integrand=x**2*cos(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=2,
        integral=2*b**3*n**3*x**3*sin(a + b*log(c*x**n))/(3*b**4*n**4 + 30*b**2*n**2 + 27) + 2*b**2*n**2*x**3*cos(a + b*log(c*x**n))/(b**4*n**4 + 10*b**2*n**2 + 9) + b*n*x**3*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))**2/(3*b**2*n**2 + 3) + x**3*cos(a + b*log(c*x**n))**3/(3*b**2*n**2 + 3),
    ),
    RubiTestSuiteCase(
        integrand=x*cos(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=2,
        integral=6*b**3*n**3*x**2*sin(a + b*log(c*x**n))/(9*b**4*n**4 + 40*b**2*n**2 + 16) + 12*b**2*n**2*x**2*cos(a + b*log(c*x**n))/(9*b**4*n**4 + 40*b**2*n**2 + 16) + 3*b*n*x**2*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))**2/(9*b**2*n**2 + 4) + 2*x**2*cos(a + b*log(c*x**n))**3/(9*b**2*n**2 + 4),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=2,
        integral=6*b**3*n**3*x*sin(a + b*log(c*x**n))/(9*b**4*n**4 + 10*b**2*n**2 + 1) + 6*b**2*n**2*x*cos(a + b*log(c*x**n))/(9*b**4*n**4 + 10*b**2*n**2 + 1) + 3*b*n*x*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))**2/(9*b**2*n**2 + 1) + x*cos(a + b*log(c*x**n))**3/(9*b**2*n**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**3/x,
        variable=x,
        num_steps=3,
        integral=-sin(a + b*log(c*x**n))**3/(3*b*n) + sin(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**3/x**2,
        variable=x,
        num_steps=2,
        integral=6*b**3*n**3*sin(a + b*log(c*x**n))/(x*(9*b**4*n**4 + 10*b**2*n**2 + 1)) - 6*b**2*n**2*cos(a + b*log(c*x**n))/(x*(9*b**4*n**4 + 10*b**2*n**2 + 1)) + 3*b*n*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))**2/(x*(9*b**2*n**2 + 1)) - cos(a + b*log(c*x**n))**3/(x*(9*b**2*n**2 + 1)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**4,
        variable=x,
        num_steps=3,
        integral=24*b**4*n**4*x/(64*b**4*n**4 + 20*b**2*n**2 + 1) + 24*b**3*n**3*x*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(64*b**4*n**4 + 20*b**2*n**2 + 1) + 12*b**2*n**2*x*cos(a + b*log(c*x**n))**2/(64*b**4*n**4 + 20*b**2*n**2 + 1) + 4*b*n*x*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))**3/(16*b**2*n**2 + 1) + x*cos(a + b*log(c*x**n))**4/(16*b**2*n**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**4/x,
        variable=x,
        num_steps=4,
        integral=3*log(x)/8 + sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))**3/(4*b*n) + 3*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(8*b*n),
    ),
    RubiTestSuiteCase(
        integrand=cos(log(3*x + 6)),
        variable=x,
        num_steps=2,
        integral=(x/2 + 1)*sin(log(3*x + 6)) + (x/2 + 1)*cos(log(3*x + 6)),
    ),
    RubiTestSuiteCase(
        integrand=x**m*cos(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)),
        variable=x,
        num_steps=3,
        integral=x**(m + 1)*(c*x**n)**((m + 1)/n)*exp(a*(m + 1)/(n*sqrt(-(m + 1)**2/n**2)))/(4*m + 4) + x**(m + 1)*exp(a*n*sqrt(-(m + 1)**2/n**2)/(m + 1))*log(x)/(2*(c*x**n)**((m + 1)/n)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + sqrt(-1/n**2)*log(c*x**n)),
        variable=x,
        num_steps=3,
        integral=x*(c*x**n)**(1/n)*exp(-a*n*sqrt(-1/n**2))/4 + x*exp(a*n*sqrt(-1/n**2))*log(x)/(2*(c*x**n)**(1/n)),
    ),
    RubiTestSuiteCase(
        integrand=x**m*cos(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)/2)**2,
        variable=x,
        num_steps=3,
        integral=x**(m + 1)*(c*x**n)**((m + 1)/n)*exp(-2*a*n*sqrt(-(m + 1)**2/n**2)/(m + 1))/(8*m + 8) + x**(m + 1)/(2*m + 2) + x**(m + 1)*exp(2*a*n*sqrt(-(m + 1)**2/n**2)/(m + 1))*log(x)/(4*(c*x**n)**((m + 1)/n)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + sqrt(-1/n**2)*log(c*x**n)/2)**2,
        variable=x,
        num_steps=3,
        integral=x*(c*x**n)**(1/n)*exp(-2*a*n*sqrt(-1/n**2))/8 + x/2 + x*exp(2*a*n*sqrt(-1/n**2))*log(x)/(4*(c*x**n)**(1/n)),
    ),
    RubiTestSuiteCase(
        integrand=x**m*cos(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)/2)**3,
        variable=x,
        num_steps=2,
        integral=-6*n*x**(m + 1)*sqrt(-(m + 1)**2/n**2)*sin(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)/2)*cos(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)/2)**2/(5*(m + 1)**2) + 4*n*x**(m + 1)*sqrt(-(m + 1)**2/n**2)*sin(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)/2)/(5*(m + 1)**2) - 4*x**(m + 1)*cos(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)/2)**3/(5*m + 5) + 8*x**(m + 1)*cos(a + sqrt(-(m + 1)**2/n**2)*log(c*x**n)/2)/(5*m + 5),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + sqrt(-1/n**2)*log(c*x**n)/3)**3,
        variable=x,
        num_steps=3,
        integral=9*x*(c*x**n)**(1/(3*n))*exp(-a*n*sqrt(-1/n**2))/32 + x*(c*x**n)**(1/n)*exp(-3*a*n*sqrt(-1/n**2))/16 + x*exp(3*a*n*sqrt(-1/n**2))*log(x)/(8*(c*x**n)**(1/n)) + 9*x*exp(a*n*sqrt(-1/n**2))/(16*(c*x**n)**(1/(3*n))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(cos(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x*sqrt(cos(a + b*log(c*x**n)))*hyper((sympy.S(-1)/2, -(b*n + 2*I)/(4*b*n)), (sympy.S(3)/4 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(sqrt((c*x**n)**(2*I*b)*exp(2*I*a) + 1)*(-I*b*n + 2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(cos(a + b*log(c*x**n)))/x,
        variable=x,
        num_steps=2,
        integral=2*elliptic_e(a/2 + b*log(c*x**n)/2, 2)/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*x*cos(a + b*log(c*x**n))**(sympy.S(3)/2)*hyper((sympy.S(-3)/2, sympy.S(-3)/4 - I/(2*b*n)), (sympy.S(1)/4 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*(-3*I*b*n + 2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**(sympy.S(3)/2)/x,
        variable=x,
        num_steps=3,
        integral=2*sin(a + b*log(c*x**n))*sqrt(cos(a + b*log(c*x**n)))/(3*b*n) + 2*elliptic_f(a/2 + b*log(c*x**n)/2, 2)/(3*b*n),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*x*cos(a + b*log(c*x**n))**(sympy.S(5)/2)*hyper((sympy.S(-5)/2, sympy.S(-5)/4 - I/(2*b*n)), (-(b*n + 2*I)/(4*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(5)/2)*(-5*I*b*n + 2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**(sympy.S(5)/2)/x,
        variable=x,
        num_steps=3,
        integral=2*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))**(sympy.S(3)/2)/(5*b*n) + 6*elliptic_e(a/2 + b*log(c*x**n)/2, 2)/(5*b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(cos(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x*sqrt((c*x**n)**(2*I*b)*exp(2*I*a) + 1)*hyper((sympy.S.Half, sympy.S(1)/4 - I/(2*b*n)), (sympy.S(5)/4 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/((I*b*n + 2)*sqrt(cos(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(cos(a + b*log(c*x**n)))),
        variable=x,
        num_steps=2,
        integral=2*elliptic_f(a/2 + b*log(c*x**n)/2, 2)/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*x*((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*hyper((sympy.S(3)/2, sympy.S(3)/4 - I/(2*b*n)), (sympy.S(7)/4 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/((3*I*b*n + 2)*cos(a + b*log(c*x**n))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*cos(a + b*log(c*x**n))**(sympy.S(3)/2)),
        variable=x,
        num_steps=3,
        integral=2*sin(a + b*log(c*x**n))/(b*n*sqrt(cos(a + b*log(c*x**n)))) - 2*elliptic_e(a/2 + b*log(c*x**n)/2, 2)/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**(sympy.S(-5)/2),
        variable=x,
        num_steps=3,
        integral=2*x*((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(5)/2)*hyper((sympy.S(5)/2, sympy.S(5)/4 - I/(2*b*n)), (sympy.S(9)/4 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/((5*I*b*n + 2)*cos(a + b*log(c*x**n))**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*cos(a + b*log(c*x**n))**(sympy.S(5)/2)),
        variable=x,
        num_steps=3,
        integral=2*sin(a + b*log(c*x**n))/(3*b*n*cos(a + b*log(c*x**n))**(sympy.S(3)/2)) + 2*elliptic_f(a/2 + b*log(c*x**n)/2, 2)/(3*b*n),
    ),
    RubiTestSuiteCase(
        integrand=cos(a - 2*I*log(c*x))**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=-(c**4*x**4*exp(2*I*a) + 1)*exp(-2*I*a)/(2*c**4*x**3*cos(a - 2*I*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**m*cos(a + b*log(c*x**n))**4,
        variable=x,
        num_steps=3,
        integral=24*b**4*n**4*x**(m + 1)/((m + 1)*(4*b**2*n**2 + (m + 1)**2)*(16*b**2*n**2 + (m + 1)**2)) + 24*b**3*n**3*x**(m + 1)*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/((4*b**2*n**2 + (m + 1)**2)*(16*b**2*n**2 + (m + 1)**2)) + 12*b**2*n**2*x**(m + 1)*(m + 1)*cos(a + b*log(c*x**n))**2/((4*b**2*n**2 + (m + 1)**2)*(16*b**2*n**2 + (m + 1)**2)) + 4*b*n*x**(m + 1)*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))**3/(16*b**2*n**2 + (m + 1)**2) + x**(m + 1)*(m + 1)*cos(a + b*log(c*x**n))**4/(16*b**2*n**2 + (m + 1)**2),
    ),
    RubiTestSuiteCase(
        integrand=x**m*cos(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=2,
        integral=6*b**3*n**3*x**(m + 1)*sin(a + b*log(c*x**n))/((b**2*n**2 + (m + 1)**2)*(9*b**2*n**2 + (m + 1)**2)) + 6*b**2*n**2*x**(m + 1)*(m + 1)*cos(a + b*log(c*x**n))/((b**2*n**2 + (m + 1)**2)*(9*b**2*n**2 + (m + 1)**2)) + 3*b*n*x**(m + 1)*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))**2/(9*b**2*n**2 + (m + 1)**2) + x**(m + 1)*(m + 1)*cos(a + b*log(c*x**n))**3/(9*b**2*n**2 + (m + 1)**2),
    ),
    RubiTestSuiteCase(
        integrand=x**m*cos(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=2,
        integral=2*b**2*n**2*x**(m + 1)/((m + 1)*(4*b**2*n**2 + (m + 1)**2)) + 2*b*n*x**(m + 1)*sin(a + b*log(c*x**n))*cos(a + b*log(c*x**n))/(4*b**2*n**2 + (m + 1)**2) + x**(m + 1)*(m + 1)*cos(a + b*log(c*x**n))**2/(4*b**2*n**2 + (m + 1)**2),
    ),
    RubiTestSuiteCase(
        integrand=x**m*cos(a + b*log(c*x**n)),
        variable=x,
        num_steps=1,
        integral=b*n*x**(m + 1)*sin(a + b*log(c*x**n))/(b**2*n**2 + (m + 1)**2) + x**(m + 1)*(m + 1)*cos(a + b*log(c*x**n))/(b**2*n**2 + (m + 1)**2),
    ),
    RubiTestSuiteCase(
        integrand=x**m*cos(a + b*log(c*x**n))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*cos(a + b*log(c*x**n))**(sympy.S(3)/2)*hyper((sympy.S(-3)/2, -(3*b*n + 2*I*m + 2*I)/(4*b*n)), (-(-b*n + 2*I*m + 2*I)/(4*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*(-3*I*b*n + 2*m + 2)),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sqrt(cos(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*sqrt(cos(a + b*log(c*x**n)))*hyper((sympy.S(-1)/2, -(b*n + 2*I*m + 2*I)/(4*b*n)), (-(-3*b*n + 2*I*m + 2*I)/(4*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(sqrt((c*x**n)**(2*I*b)*exp(2*I*a) + 1)*(-I*b*n + 2*m + 2)),
    ),
    RubiTestSuiteCase(
        integrand=x**m/sqrt(cos(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*sqrt((c*x**n)**(2*I*b)*exp(2*I*a) + 1)*hyper((sympy.S.Half, -(-b*n + 2*I*m + 2*I)/(4*b*n)), (-(-5*b*n + 2*I*m + 2*I)/(4*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/((I*b*n + 2*m + 2)*sqrt(cos(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=x**m/cos(a + b*log(c*x**n))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*hyper((sympy.S(3)/2, -(-3*b*n + 2*I*m + 2*I)/(4*b*n)), (-(-7*b*n + 2*I*m + 2*I)/(4*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/((3*I*b*n + 2*m + 2)*cos(a + b*log(c*x**n))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**m/cos(a + b*log(c*x**n))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(5)/2)*hyper((sympy.S(5)/2, -(-5*b*n + 2*I*m + 2*I)/(4*b*n)), (-(-9*b*n + 2*I*m + 2*I)/(4*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/((5*I*b*n + 2*m + 2)*cos(a + b*log(c*x**n))**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m*cos(d*(a + b*log(c*x**n)))**p,
        variable=x,
        num_steps=3,
        integral=(e*x)**(m + 1)*cos(d*(a + b*log(c*x**n)))**p*hyper((-p, -(b*d*n*p + I*m + I)/(2*b*d*n)), (-p/2 + 1 - I*(m + 1)/(2*b*d*n),), -(c*x**n)**(2*I*b*d)*exp(2*I*a*d))/(e*((c*x**n)**(2*I*b*d)*exp(2*I*a*d) + 1)**p*(-I*b*d*n*p + m + 1)),
    ),
    RubiTestSuiteCase(
        integrand=x*cos(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=3,
        integral=x**2*cos(a + b*log(c*x**n))**p*hyper((-p, -p/2 - I/(b*n)), (-p/2 + 1 - I/(b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**p*(-I*b*n*p + 2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=3,
        integral=x*cos(a + b*log(c*x**n))**p*hyper((-p, -(b*n*p + I)/(2*b*n)), (-p/2 + 1 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**p*(-I*b*n*p + 1)),
    ),
    RubiTestSuiteCase(
        integrand=tan(a + b*log(c*x**n))/x,
        variable=x,
        num_steps=2,
        integral=-log(cos(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=tan(a + b*log(c*x**n))**2/x,
        variable=x,
        num_steps=3,
        integral=-log(x) + tan(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=tan(a + b*log(c*x**n))**3/x,
        variable=x,
        num_steps=3,
        integral=log(cos(a + b*log(c*x**n)))/(b*n) + tan(a + b*log(c*x**n))**2/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=tan(a + b*log(c*x**n))**4/x,
        variable=x,
        num_steps=4,
        integral=log(x) + tan(a + b*log(c*x**n))**3/(3*b*n) - tan(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=tan(a + b*log(c*x**n))**5/x,
        variable=x,
        num_steps=4,
        integral=-log(cos(a + b*log(c*x**n)))/(b*n) + tan(a + b*log(c*x**n))**4/(4*b*n) - tan(a + b*log(c*x**n))**2/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=tan(a + b*log(c*x**n))**(sympy.S(5)/2)/x,
        variable=x,
        num_steps=13,
        integral=-sqrt(2)*log(-sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + tan(a + b*log(c*x**n)) + 1)/(4*b*n) + sqrt(2)*log(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + tan(a + b*log(c*x**n)) + 1)/(4*b*n) + 2*tan(a + b*log(c*x**n))**(sympy.S(3)/2)/(3*b*n) - sqrt(2)*atan(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) - 1)/(2*b*n) - sqrt(2)*atan(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + 1)/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=tan(a + b*log(c*x**n))**(sympy.S(3)/2)/x,
        variable=x,
        num_steps=13,
        integral=sqrt(2)*log(-sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + tan(a + b*log(c*x**n)) + 1)/(4*b*n) - sqrt(2)*log(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + tan(a + b*log(c*x**n)) + 1)/(4*b*n) + 2*sqrt(tan(a + b*log(c*x**n)))/(b*n) - sqrt(2)*atan(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) - 1)/(2*b*n) - sqrt(2)*atan(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + 1)/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(tan(a + b*log(c*x**n)))/x,
        variable=x,
        num_steps=12,
        integral=sqrt(2)*log(-sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + tan(a + b*log(c*x**n)) + 1)/(4*b*n) - sqrt(2)*log(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + tan(a + b*log(c*x**n)) + 1)/(4*b*n) + sqrt(2)*atan(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) - 1)/(2*b*n) + sqrt(2)*atan(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + 1)/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(tan(a + b*log(c*x**n)))),
        variable=x,
        num_steps=12,
        integral=-sqrt(2)*log(-sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + tan(a + b*log(c*x**n)) + 1)/(4*b*n) + sqrt(2)*log(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + tan(a + b*log(c*x**n)) + 1)/(4*b*n) + sqrt(2)*atan(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) - 1)/(2*b*n) + sqrt(2)*atan(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + 1)/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*tan(a + b*log(c*x**n))**(sympy.S(3)/2)),
        variable=x,
        num_steps=13,
        integral=-sqrt(2)*log(-sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + tan(a + b*log(c*x**n)) + 1)/(4*b*n) + sqrt(2)*log(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + tan(a + b*log(c*x**n)) + 1)/(4*b*n) - sqrt(2)*atan(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) - 1)/(2*b*n) - sqrt(2)*atan(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + 1)/(2*b*n) - 2/(b*n*sqrt(tan(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*tan(a + b*log(c*x**n))**(sympy.S(5)/2)),
        variable=x,
        num_steps=13,
        integral=sqrt(2)*log(-sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + tan(a + b*log(c*x**n)) + 1)/(4*b*n) - sqrt(2)*log(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + tan(a + b*log(c*x**n)) + 1)/(4*b*n) - sqrt(2)*atan(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) - 1)/(2*b*n) - sqrt(2)*atan(sqrt(2)*sqrt(tan(a + b*log(c*x**n))) + 1)/(2*b*n) - 2/(3*b*n*tan(a + b*log(c*x**n))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cot(a + b*log(c*x**n))/x,
        variable=x,
        num_steps=2,
        integral=log(sin(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=cot(a + b*log(c*x**n))**2/x,
        variable=x,
        num_steps=3,
        integral=-log(x) - cot(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=cot(a + b*log(c*x**n))**3/x,
        variable=x,
        num_steps=3,
        integral=-log(sin(a + b*log(c*x**n)))/(b*n) - cot(a + b*log(c*x**n))**2/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=cot(a + b*log(c*x**n))**4/x,
        variable=x,
        num_steps=4,
        integral=log(x) - cot(a + b*log(c*x**n))**3/(3*b*n) + cot(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=cot(a + b*log(c*x**n))**5/x,
        variable=x,
        num_steps=4,
        integral=log(sin(a + b*log(c*x**n)))/(b*n) - cot(a + b*log(c*x**n))**4/(4*b*n) + cot(a + b*log(c*x**n))**2/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=cot(a + b*log(c*x**n))**(sympy.S(5)/2)/x,
        variable=x,
        num_steps=13,
        integral=sqrt(2)*log(-sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + cot(a + b*log(c*x**n)) + 1)/(4*b*n) - sqrt(2)*log(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + cot(a + b*log(c*x**n)) + 1)/(4*b*n) - 2*cot(a + b*log(c*x**n))**(sympy.S(3)/2)/(3*b*n) + sqrt(2)*atan(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) - 1)/(2*b*n) + sqrt(2)*atan(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + 1)/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=cot(a + b*log(c*x**n))**(sympy.S(3)/2)/x,
        variable=x,
        num_steps=13,
        integral=-sqrt(2)*log(-sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + cot(a + b*log(c*x**n)) + 1)/(4*b*n) + sqrt(2)*log(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + cot(a + b*log(c*x**n)) + 1)/(4*b*n) - 2*sqrt(cot(a + b*log(c*x**n)))/(b*n) + sqrt(2)*atan(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) - 1)/(2*b*n) + sqrt(2)*atan(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + 1)/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(cot(a + b*log(c*x**n)))/x,
        variable=x,
        num_steps=12,
        integral=-sqrt(2)*log(-sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + cot(a + b*log(c*x**n)) + 1)/(4*b*n) + sqrt(2)*log(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + cot(a + b*log(c*x**n)) + 1)/(4*b*n) - sqrt(2)*atan(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) - 1)/(2*b*n) - sqrt(2)*atan(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + 1)/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(cot(a + b*log(c*x**n)))),
        variable=x,
        num_steps=12,
        integral=sqrt(2)*log(-sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + cot(a + b*log(c*x**n)) + 1)/(4*b*n) - sqrt(2)*log(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + cot(a + b*log(c*x**n)) + 1)/(4*b*n) - sqrt(2)*atan(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) - 1)/(2*b*n) - sqrt(2)*atan(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + 1)/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*cot(a + b*log(c*x**n))**(sympy.S(3)/2)),
        variable=x,
        num_steps=13,
        integral=sqrt(2)*log(-sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + cot(a + b*log(c*x**n)) + 1)/(4*b*n) - sqrt(2)*log(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + cot(a + b*log(c*x**n)) + 1)/(4*b*n) + sqrt(2)*atan(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) - 1)/(2*b*n) + sqrt(2)*atan(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + 1)/(2*b*n) + 2/(b*n*sqrt(cot(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*cot(a + b*log(c*x**n))**(sympy.S(5)/2)),
        variable=x,
        num_steps=13,
        integral=-sqrt(2)*log(-sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + cot(a + b*log(c*x**n)) + 1)/(4*b*n) + sqrt(2)*log(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + cot(a + b*log(c*x**n)) + 1)/(4*b*n) + sqrt(2)*atan(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) - 1)/(2*b*n) + sqrt(2)*atan(sqrt(2)*sqrt(cot(a + b*log(c*x**n))) + 1)/(2*b*n) + 2/(3*b*n*cot(a + b*log(c*x**n))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sec(a + b*log(c*x**n)),
        variable=x,
        num_steps=3,
        integral=2*x**3*(c*x**n)**(I*b)*exp(I*a)*hyper((1, sympy.S.Half - 3*I/(2*b*n)), (sympy.S(3)/2 - 3*I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(I*b*n + 3),
    ),
    RubiTestSuiteCase(
        integrand=x*sec(a + b*log(c*x**n)),
        variable=x,
        num_steps=3,
        integral=2*x**2*(c*x**n)**(I*b)*exp(I*a)*hyper((1, sympy.S.Half - I/(b*n)), (sympy.S(3)/2 - I/(b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(I*b*n + 2),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n)),
        variable=x,
        num_steps=3,
        integral=2*x*(c*x**n)**(I*b)*exp(I*a)*hyper((1, sympy.S.Half - I/(2*b*n)), (sympy.S(3)/2 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(I*b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))/x,
        variable=x,
        num_steps=2,
        integral=atanh(sin(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))/x**2,
        variable=x,
        num_steps=3,
        integral=-2*(c*x**n)**(I*b)*exp(I*a)*hyper((1, sympy.S.Half + I/(2*b*n)), (sympy.S(3)/2 + I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(x*(-I*b*n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))/x**3,
        variable=x,
        num_steps=3,
        integral=-2*(c*x**n)**(I*b)*exp(I*a)*hyper((1, sympy.S.Half + I/(b*n)), (sympy.S(3)/2 + I/(b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(x**2*(-I*b*n + 2)),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sec(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=3,
        integral=4*x**3*(c*x**n)**(2*I*b)*exp(2*I*a)*hyper((2, 1 - 3*I/(2*b*n)), (2 - 3*I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(2*I*b*n + 3),
    ),
    RubiTestSuiteCase(
        integrand=x*sec(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=3,
        integral=2*x**2*(c*x**n)**(2*I*b)*exp(2*I*a)*hyper((2, 1 - I/(b*n)), (2 - I/(b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(I*b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=3,
        integral=4*x*(c*x**n)**(2*I*b)*exp(2*I*a)*hyper((2, 1 - I/(2*b*n)), (2 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(2*I*b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**2/x,
        variable=x,
        num_steps=3,
        integral=tan(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**2/x**2,
        variable=x,
        num_steps=3,
        integral=-4*(c*x**n)**(2*I*b)*exp(2*I*a)*hyper((2, 1 + I/(2*b*n)), (2 + I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(x*(-2*I*b*n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**2/x**3,
        variable=x,
        num_steps=3,
        integral=-2*(c*x**n)**(2*I*b)*exp(2*I*a)*hyper((2, 1 + I/(b*n)), (2 + I/(b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(x**2*(-I*b*n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=x*sec(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=3,
        integral=8*x**2*(c*x**n)**(3*I*b)*exp(3*I*a)*hyper((3, sympy.S(3)/2 - I/(b*n)), (sympy.S(5)/2 - I/(b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(3*I*b*n + 2),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=3,
        integral=8*x*(c*x**n)**(3*I*b)*exp(3*I*a)*hyper((3, sympy.S(3)/2 - I/(2*b*n)), (sympy.S(5)/2 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(3*I*b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**3/x,
        variable=x,
        num_steps=3,
        integral=tan(a + b*log(c*x**n))*sec(a + b*log(c*x**n))/(2*b*n) + atanh(sin(a + b*log(c*x**n)))/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**3/x**2,
        variable=x,
        num_steps=3,
        integral=-8*(c*x**n)**(3*I*b)*exp(3*I*a)*hyper((3, sympy.S(3)/2 + I/(2*b*n)), (sympy.S(5)/2 + I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(x*(-3*I*b*n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**3/x**3,
        variable=x,
        num_steps=3,
        integral=-8*(c*x**n)**(3*I*b)*exp(3*I*a)*hyper((3, sympy.S(3)/2 + I/(b*n)), (sympy.S(5)/2 + I/(b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(x**2*(-3*I*b*n + 2)),
    ),
    RubiTestSuiteCase(
        integrand=x*sec(a + b*log(c*x**n))**4,
        variable=x,
        num_steps=3,
        integral=8*x**2*(c*x**n)**(4*I*b)*exp(4*I*a)*hyper((4, 2 - I/(b*n)), (3 - I/(b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(2*I*b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**4,
        variable=x,
        num_steps=3,
        integral=16*x*(c*x**n)**(4*I*b)*exp(4*I*a)*hyper((4, 2 - I/(2*b*n)), (3 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(4*I*b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**4/x,
        variable=x,
        num_steps=3,
        integral=tan(a + b*log(c*x**n))**3/(3*b*n) + tan(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**4/x**2,
        variable=x,
        num_steps=3,
        integral=-16*(c*x**n)**(4*I*b)*exp(4*I*a)*hyper((4, 2 + I/(2*b*n)), (3 + I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(x*(-4*I*b*n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**4/x**3,
        variable=x,
        num_steps=3,
        integral=-8*(c*x**n)**(4*I*b)*exp(4*I*a)*hyper((4, 2 + I/(b*n)), (3 + I/(b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(x**2*(-2*I*b*n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=2*b**2*n**2*sec(a + b*log(c*x**n))**3 - (b**2*n**2 + 1)*sec(a + b*log(c*x**n)),
        variable=x,
        num_steps=-7,
        integral=b*n*x*tan(a + b*log(c*x**n))*sec(a + b*log(c*x**n)) - x*sec(a + b*log(c*x**n)),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sec(a + 2*log(c*x**(sqrt(-(m + 1)**2)/2)))**3,
        variable=x,
        num_steps=-3,
        integral=x**(m + 1)*sec(a + 2*log(c*x**(sqrt(-(m + 1)**2)/2)))/(2*m + 2) + x**(m + 1)*tan(a + 2*log(c*x**(sqrt(-(m + 1)**2)/2)))*sec(a + 2*log(c*x**(sqrt(-(m + 1)**2)/2)))/(2*sqrt(-(m + 1)**2)),
    ),
    RubiTestSuiteCase(
        integrand=x*sec(a + 2*log(c*x**I))**3,
        variable=x,
        num_steps=3,
        integral=x**2*(c*x**I)**(2*I)*exp(I*a)/((c*x**I)**(4*I)*exp(2*I*a) + 1)**2,
    ),
    RubiTestSuiteCase(
        integrand=sec(a + 2*log(c/x**(I/2)))**3,
        variable=x,
        num_steps=3,
        integral=2*x*(c/x**(I/2))**(6*I)*exp(3*I*a)/((c/x**(I/2))**(4*I)*exp(2*I*a) + 1)**2,
    ),
    RubiTestSuiteCase(
        integrand=sec(a + I*log(c*x**n)/(n*(p - 2)))**p,
        variable=x,
        num_steps=3,
        integral=x*(2 - p)*((c*x**n)**(2/(n*(2 - p)))*exp(2*I*a) + 1)*exp(-2*I*a)*sec(a - I*log(c*x**n)/(n*(2 - p)))**p/((c*x**n)**(2/(n*(2 - p)))*(2 - 2*p)),
    ),
    RubiTestSuiteCase(
        integrand=sec(a - I*log(c*x**n)/(n*(p - 2)))**p,
        variable=x,
        num_steps=3,
        integral=x*(1 + exp(2*I*a)/(c*x**n)**(2/(n*(2 - p))))*(2 - p)*sec(a + I*log(c*x**n)/(n*(2 - p)))**p/(2 - 2*p),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sec(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x*sqrt((c*x**n)**(2*I*b)*exp(2*I*a) + 1)*hyper((sympy.S.Half, sympy.S(1)/4 - I/(2*b*n)), (sympy.S(5)/4 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))*sqrt(sec(a + b*log(c*x**n)))/(I*b*n + 2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sec(a + b*log(c*x**n)))/x,
        variable=x,
        num_steps=3,
        integral=2*sqrt(cos(a + b*log(c*x**n)))*elliptic_f(a/2 + b*log(c*x**n)/2, 2)*sqrt(sec(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*x*((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*hyper((sympy.S(3)/2, sympy.S(3)/4 - I/(2*b*n)), (sympy.S(7)/4 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))*sec(a + b*log(c*x**n))**(sympy.S(3)/2)/(3*I*b*n + 2),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**(sympy.S(3)/2)/x,
        variable=x,
        num_steps=4,
        integral=2*sin(a + b*log(c*x**n))*sqrt(sec(a + b*log(c*x**n)))/(b*n) - 2*sqrt(cos(a + b*log(c*x**n)))*elliptic_e(a/2 + b*log(c*x**n)/2, 2)*sqrt(sec(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*x*((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(5)/2)*hyper((sympy.S(5)/2, sympy.S(5)/4 - I/(2*b*n)), (sympy.S(9)/4 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))*sec(a + b*log(c*x**n))**(sympy.S(5)/2)/(5*I*b*n + 2),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**(sympy.S(5)/2)/x,
        variable=x,
        num_steps=4,
        integral=2*sin(a + b*log(c*x**n))*sec(a + b*log(c*x**n))**(sympy.S(3)/2)/(3*b*n) + 2*sqrt(cos(a + b*log(c*x**n)))*elliptic_f(a/2 + b*log(c*x**n)/2, 2)*sqrt(sec(a + b*log(c*x**n)))/(3*b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(sec(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x*hyper((sympy.S(-1)/2, -(b*n + 2*I)/(4*b*n)), (sympy.S(3)/4 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(sqrt((c*x**n)**(2*I*b)*exp(2*I*a) + 1)*(-I*b*n + 2)*sqrt(sec(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(sec(a + b*log(c*x**n)))),
        variable=x,
        num_steps=3,
        integral=2*sqrt(cos(a + b*log(c*x**n)))*elliptic_e(a/2 + b*log(c*x**n)/2, 2)*sqrt(sec(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*x*hyper((sympy.S(-3)/2, sympy.S(-3)/4 - I/(2*b*n)), (sympy.S(1)/4 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*(-3*I*b*n + 2)*sec(a + b*log(c*x**n))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sec(a + b*log(c*x**n))**(sympy.S(3)/2)),
        variable=x,
        num_steps=4,
        integral=2*sin(a + b*log(c*x**n))/(3*b*n*sqrt(sec(a + b*log(c*x**n)))) + 2*sqrt(cos(a + b*log(c*x**n)))*elliptic_f(a/2 + b*log(c*x**n)/2, 2)*sqrt(sec(a + b*log(c*x**n)))/(3*b*n),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**(sympy.S(-5)/2),
        variable=x,
        num_steps=3,
        integral=2*x*hyper((sympy.S(-5)/2, sympy.S(-5)/4 - I/(2*b*n)), (-(b*n + 2*I)/(4*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(5)/2)*(-5*I*b*n + 2)*sec(a + b*log(c*x**n))**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sec(a + b*log(c*x**n))**(sympy.S(5)/2)),
        variable=x,
        num_steps=4,
        integral=2*sin(a + b*log(c*x**n))/(5*b*n*sec(a + b*log(c*x**n))**(sympy.S(3)/2)) + 6*sqrt(cos(a + b*log(c*x**n)))*elliptic_e(a/2 + b*log(c*x**n)/2, 2)*sqrt(sec(a + b*log(c*x**n)))/(5*b*n),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sec(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=3,
        integral=8*x**(m + 1)*(c*x**n)**(3*I*b)*exp(3*I*a)*hyper((3, -(-3*b*n + I*(m + 1))/(2*b*n)), (-(-5*b*n + I*(m + 1))/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(3*I*b*n + m + 1),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sec(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=3,
        integral=4*x**(m + 1)*(c*x**n)**(2*I*b)*exp(2*I*a)*hyper((2, -(-2*b*n + I*(m + 1))/(2*b*n)), (-(-4*b*n + I*(m + 1))/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(2*I*b*n + m + 1),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sec(a + b*log(c*x**n)),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*(c*x**n)**(I*b)*exp(I*a)*hyper((1, -(-b*n + I*m + I)/(2*b*n)), (-(-3*b*n + I*(m + 1))/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(I*b*n + m + 1),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sec(a + b*log(c*x**n))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(5)/2)*hyper((sympy.S(5)/2, -(-5*b*n + 2*I*m + 2*I)/(4*b*n)), (-(-9*b*n + 2*I*m + 2*I)/(4*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))*sec(a + b*log(c*x**n))**(sympy.S(5)/2)/(5*I*b*n + 2*m + 2),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sec(a + b*log(c*x**n))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*hyper((sympy.S(3)/2, -(-3*b*n + 2*I*m + 2*I)/(4*b*n)), (-(-7*b*n + 2*I*m + 2*I)/(4*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))*sec(a + b*log(c*x**n))**(sympy.S(3)/2)/(3*I*b*n + 2*m + 2),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sqrt(sec(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*sqrt((c*x**n)**(2*I*b)*exp(2*I*a) + 1)*hyper((sympy.S.Half, -(-b*n + 2*I*m + 2*I)/(4*b*n)), (-(-5*b*n + 2*I*m + 2*I)/(4*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))*sqrt(sec(a + b*log(c*x**n)))/(I*b*n + 2*m + 2),
    ),
    RubiTestSuiteCase(
        integrand=x**m/sqrt(sec(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*hyper((sympy.S(-1)/2, -(b*n + 2*I*m + 2*I)/(4*b*n)), (-(-3*b*n + 2*I*m + 2*I)/(4*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(sqrt((c*x**n)**(2*I*b)*exp(2*I*a) + 1)*(-I*b*n + 2*m + 2)*sqrt(sec(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=x**m/sec(a + b*log(c*x**n))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*hyper((sympy.S(-3)/2, -(3*b*n + 2*I*m + 2*I)/(4*b*n)), (-(-b*n + 2*I*m + 2*I)/(4*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))/(((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*(-3*I*b*n + 2*m + 2)*sec(a + b*log(c*x**n))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m*sec(d*(a + b*log(c*x**n)))**p,
        variable=x,
        num_steps=3,
        integral=(e*x)**(m + 1)*((c*x**n)**(2*I*b*d)*exp(2*I*a*d) + 1)**p*hyper((p, -(-b*d*n*p + I*m + I)/(2*b*d*n)), (p/2 + 1 - I*(m + 1)/(2*b*d*n),), -(c*x**n)**(2*I*b*d)*exp(2*I*a*d))*sec(d*(a + b*log(c*x**n)))**p/(e*(I*b*d*n*p + m + 1)),
    ),
    RubiTestSuiteCase(
        integrand=x*sec(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=3,
        integral=x**2*((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**p*hyper((p, p/2 - I/(b*n)), (p/2 + 1 - I/(b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))*sec(a + b*log(c*x**n))**p/(I*b*n*p + 2),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=3,
        integral=x*((c*x**n)**(2*I*b)*exp(2*I*a) + 1)**p*hyper((p, -(-b*n*p + I)/(2*b*n)), (p/2 + 1 - I/(2*b*n),), -(c*x**n)**(2*I*b)*exp(2*I*a))*sec(a + b*log(c*x**n))**p/(I*b*n*p + 1),
    ),
    RubiTestSuiteCase(
        integrand=x**2*csc(a + b*log(c*x**n)),
        variable=x,
        num_steps=3,
        integral=2*x**3*(c*x**n)**(I*b)*exp(I*a)*hyper((1, sympy.S.Half - 3*I/(2*b*n)), (sympy.S(3)/2 - 3*I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(-b*n + 3*I),
    ),
    RubiTestSuiteCase(
        integrand=x*csc(a + b*log(c*x**n)),
        variable=x,
        num_steps=3,
        integral=2*x**2*(c*x**n)**(I*b)*exp(I*a)*hyper((1, sympy.S.Half - I/(b*n)), (sympy.S(3)/2 - I/(b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(-b*n + 2*I),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n)),
        variable=x,
        num_steps=3,
        integral=2*x*(c*x**n)**(I*b)*exp(I*a)*hyper((1, sympy.S.Half - I/(2*b*n)), (sympy.S(3)/2 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(-b*n + I),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))/x,
        variable=x,
        num_steps=2,
        integral=-atanh(cos(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))/x**2,
        variable=x,
        num_steps=3,
        integral=-2*(c*x**n)**(I*b)*exp(I*a)*hyper((1, sympy.S.Half + I/(2*b*n)), (sympy.S(3)/2 + I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(x*(b*n + I)),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))/x**3,
        variable=x,
        num_steps=3,
        integral=-2*(c*x**n)**(I*b)*exp(I*a)*hyper((1, sympy.S.Half + I/(b*n)), (sympy.S(3)/2 + I/(b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(x**2*(b*n + 2*I)),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=3,
        integral=-4*x*(c*x**n)**(2*I*b)*exp(2*I*a)*hyper((2, 1 - I/(2*b*n)), (2 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(2*I*b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))**2/x,
        variable=x,
        num_steps=3,
        integral=-cot(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=3,
        integral=-8*x*(c*x**n)**(3*I*b)*exp(3*I*a)*hyper((3, sympy.S(3)/2 - I/(2*b*n)), (sympy.S(5)/2 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(-3*b*n + I),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))**3/x,
        variable=x,
        num_steps=3,
        integral=-cot(a + b*log(c*x**n))*csc(a + b*log(c*x**n))/(2*b*n) - atanh(cos(a + b*log(c*x**n)))/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))**4,
        variable=x,
        num_steps=3,
        integral=16*x*(c*x**n)**(4*I*b)*exp(4*I*a)*hyper((4, 2 - I/(2*b*n)), (3 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(4*I*b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))**4/x,
        variable=x,
        num_steps=3,
        integral=-cot(a + b*log(c*x**n))**3/(3*b*n) - cot(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=2*b**2*n**2*csc(a + b*log(c*x**n))**3 - (b**2*n**2 + 1)*csc(a + b*log(c*x**n)),
        variable=x,
        num_steps=-7,
        integral=-b*n*x*cot(a + b*log(c*x**n))*csc(a + b*log(c*x**n)) - x*csc(a + b*log(c*x**n)),
    ),
    RubiTestSuiteCase(
        integrand=x**m*csc(a + 2*log(c*x**(sqrt(-(m + 1)**2)/2)))**3,
        variable=x,
        num_steps=-3,
        integral=x**(m + 1)*csc(a + 2*log(c*x**(sqrt(-(m + 1)**2)/2)))/(2*m + 2) - x**(m + 1)*cot(a + 2*log(c*x**(sqrt(-(m + 1)**2)/2)))*csc(a + 2*log(c*x**(sqrt(-(m + 1)**2)/2)))/(2*sqrt(-(m + 1)**2)),
    ),
    RubiTestSuiteCase(
        integrand=x*csc(a + 2*log(c*x**I))**3,
        variable=x,
        num_steps=3,
        integral=-I*x**2*(c*x**I)**(2*I)*exp(I*a)/(-(c*x**I)**(4*I)*exp(2*I*a) + 1)**2,
    ),
    RubiTestSuiteCase(
        integrand=csc(a + 2*log(c/x**(I/2)))**3,
        variable=x,
        num_steps=3,
        integral=2*I*x*(c/x**(I/2))**(6*I)*exp(3*I*a)/(-(c/x**(I/2))**(4*I)*exp(2*I*a) + 1)**2,
    ),
    RubiTestSuiteCase(
        integrand=csc(a + I*log(c*x**n)/(n*(p - 2)))**p,
        variable=x,
        num_steps=3,
        integral=-x*(2 - p)*(-(c*x**n)**(2/(n*(2 - p)))*exp(2*I*a) + 1)*exp(-2*I*a)*csc(a - I*log(c*x**n)/(n*(2 - p)))**p/((c*x**n)**(2/(n*(2 - p)))*(2 - 2*p)),
    ),
    RubiTestSuiteCase(
        integrand=csc(a - I*log(c*x**n)/(n*(p - 2)))**p,
        variable=x,
        num_steps=3,
        integral=x*(1 - exp(2*I*a)/(c*x**n)**(2/(n*(2 - p))))*(2 - p)*csc(a + I*log(c*x**n)/(n*(2 - p)))**p/(2 - 2*p),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(csc(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x*sqrt(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)*sqrt(csc(a + b*log(c*x**n)))*hyper((sympy.S.Half, sympy.S(1)/4 - I/(2*b*n)), (sympy.S(5)/4 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(I*b*n + 2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(csc(a + b*log(c*x**n)))/x,
        variable=x,
        num_steps=3,
        integral=2*sqrt(sin(a + b*log(c*x**n)))*sqrt(csc(a + b*log(c*x**n)))*elliptic_f(a/2 + b*log(c*x**n)/2 - pi/4, 2)/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*x*(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*csc(a + b*log(c*x**n))**(sympy.S(3)/2)*hyper((sympy.S(3)/2, sympy.S(3)/4 - I/(2*b*n)), (sympy.S(7)/4 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(3*I*b*n + 2),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))**(sympy.S(3)/2)/x,
        variable=x,
        num_steps=4,
        integral=-2*sqrt(sin(a + b*log(c*x**n)))*sqrt(csc(a + b*log(c*x**n)))*elliptic_e(a/2 + b*log(c*x**n)/2 - pi/4, 2)/(b*n) - 2*cos(a + b*log(c*x**n))*sqrt(csc(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*x*(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(5)/2)*csc(a + b*log(c*x**n))**(sympy.S(5)/2)*hyper((sympy.S(5)/2, sympy.S(5)/4 - I/(2*b*n)), (sympy.S(9)/4 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(5*I*b*n + 2),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))**(sympy.S(5)/2)/x,
        variable=x,
        num_steps=4,
        integral=2*sqrt(sin(a + b*log(c*x**n)))*sqrt(csc(a + b*log(c*x**n)))*elliptic_f(a/2 + b*log(c*x**n)/2 - pi/4, 2)/(3*b*n) - 2*cos(a + b*log(c*x**n))*csc(a + b*log(c*x**n))**(sympy.S(3)/2)/(3*b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(csc(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x*hyper((sympy.S(-1)/2, -(b*n + 2*I)/(4*b*n)), (sympy.S(3)/4 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(sqrt(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)*(-I*b*n + 2)*sqrt(csc(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(csc(a + b*log(c*x**n)))),
        variable=x,
        num_steps=3,
        integral=2*sqrt(sin(a + b*log(c*x**n)))*sqrt(csc(a + b*log(c*x**n)))*elliptic_e(a/2 + b*log(c*x**n)/2 - pi/4, 2)/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*x*hyper((sympy.S(-3)/2, sympy.S(-3)/4 - I/(2*b*n)), (sympy.S(1)/4 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/((-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*(-3*I*b*n + 2)*csc(a + b*log(c*x**n))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*csc(a + b*log(c*x**n))**(sympy.S(3)/2)),
        variable=x,
        num_steps=4,
        integral=2*sqrt(sin(a + b*log(c*x**n)))*sqrt(csc(a + b*log(c*x**n)))*elliptic_f(a/2 + b*log(c*x**n)/2 - pi/4, 2)/(3*b*n) - 2*cos(a + b*log(c*x**n))/(3*b*n*sqrt(csc(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))**(sympy.S(-5)/2),
        variable=x,
        num_steps=3,
        integral=2*x*hyper((sympy.S(-5)/2, sympy.S(-5)/4 - I/(2*b*n)), (-(b*n + 2*I)/(4*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/((-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(5)/2)*(-5*I*b*n + 2)*csc(a + b*log(c*x**n))**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*csc(a + b*log(c*x**n))**(sympy.S(5)/2)),
        variable=x,
        num_steps=4,
        integral=6*sqrt(sin(a + b*log(c*x**n)))*sqrt(csc(a + b*log(c*x**n)))*elliptic_e(a/2 + b*log(c*x**n)/2 - pi/4, 2)/(5*b*n) - 2*cos(a + b*log(c*x**n))/(5*b*n*csc(a + b*log(c*x**n))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m*csc(d*(a + b*log(c*x**n)))**3,
        variable=x,
        num_steps=3,
        integral=-8*(c*x**n)**(3*I*b*d)*(e*x)**(m + 1)*exp(3*I*a*d)*hyper((3, -(-3*b*d*n + I*(m + 1))/(2*b*d*n)), (-(-5*b*d*n + I*(m + 1))/(2*b*d*n),), (c*x**n)**(2*I*b*d)*exp(2*I*a*d))/(e*(-3*b*d*n + I*(m + 1))),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m*csc(d*(a + b*log(c*x**n)))**2,
        variable=x,
        num_steps=3,
        integral=-4*(c*x**n)**(2*I*b*d)*(e*x)**(m + 1)*exp(2*I*a*d)*hyper((2, -(-2*b*d*n + I*(m + 1))/(2*b*d*n)), (-(-4*b*d*n + I*(m + 1))/(2*b*d*n),), (c*x**n)**(2*I*b*d)*exp(2*I*a*d))/(e*(2*I*b*d*n + m + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m*csc(d*(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*(c*x**n)**(I*b*d)*(e*x)**(m + 1)*exp(I*a*d)*hyper((1, -(-b*d*n + I*m + I)/(2*b*d*n)), (-(-3*b*d*n + I*(m + 1))/(2*b*d*n),), (c*x**n)**(2*I*b*d)*exp(2*I*a*d))/(e*(-b*d*n + I*(m + 1))),
    ),
    RubiTestSuiteCase(
        integrand=x**m*csc(a + b*log(c*x**n))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(5)/2)*csc(a + b*log(c*x**n))**(sympy.S(5)/2)*hyper((sympy.S(5)/2, -(-5*b*n + 2*I*m + 2*I)/(4*b*n)), (-(-9*b*n + 2*I*m + 2*I)/(4*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(5*I*b*n + 2*m + 2),
    ),
    RubiTestSuiteCase(
        integrand=x**m*csc(a + b*log(c*x**n))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*csc(a + b*log(c*x**n))**(sympy.S(3)/2)*hyper((sympy.S(3)/2, -(-3*b*n + 2*I*m + 2*I)/(4*b*n)), (-(-7*b*n + 2*I*m + 2*I)/(4*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(3*I*b*n + 2*m + 2),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sqrt(csc(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*sqrt(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)*sqrt(csc(a + b*log(c*x**n)))*hyper((sympy.S.Half, -(-b*n + 2*I*m + 2*I)/(4*b*n)), (-(-5*b*n + 2*I*m + 2*I)/(4*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(I*b*n + 2*m + 2),
    ),
    RubiTestSuiteCase(
        integrand=x**m/sqrt(csc(a + b*log(c*x**n))),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*hyper((sympy.S(-1)/2, -(b*n + 2*I*m + 2*I)/(4*b*n)), (-(-3*b*n + 2*I*m + 2*I)/(4*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(sqrt(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)*(-I*b*n + 2*m + 2)*sqrt(csc(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=x**m/csc(a + b*log(c*x**n))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*x**(m + 1)*hyper((sympy.S(-3)/2, -(3*b*n + 2*I*m + 2*I)/(4*b*n)), (-(-b*n + 2*I*m + 2*I)/(4*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/((-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**(sympy.S(3)/2)*(-3*I*b*n + 2*m + 2)*csc(a + b*log(c*x**n))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m*csc(d*(a + b*log(c*x**n)))**p,
        variable=x,
        num_steps=3,
        integral=(e*x)**(m + 1)*(-(c*x**n)**(2*I*b*d)*exp(2*I*a*d) + 1)**p*csc(d*(a + b*log(c*x**n)))**p*hyper((p, -(-b*d*n*p + I*m + I)/(2*b*d*n)), (p/2 + 1 - I*(m + 1)/(2*b*d*n),), (c*x**n)**(2*I*b*d)*exp(2*I*a*d))/(e*(I*b*d*n*p + m + 1)),
    ),
    RubiTestSuiteCase(
        integrand=x*csc(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=3,
        integral=x**2*(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**p*csc(a + b*log(c*x**n))**p*hyper((p, p/2 - I/(b*n)), (p/2 + 1 - I/(b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(I*b*n*p + 2),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=3,
        integral=x*(-(c*x**n)**(2*I*b)*exp(2*I*a) + 1)**p*csc(a + b*log(c*x**n))**p*hyper((p, -(-b*n*p + I)/(2*b*n)), (p/2 + 1 - I/(2*b*n),), (c*x**n)**(2*I*b)*exp(2*I*a))/(I*b*n*p + 1),
    ),
]
