# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 4 Trig functions/4.4 Cotangent/4.4.2.1 (a+b cot)^m (c+d cot)^n.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '4 Trig functions/4.4 Cotangent/4.4.2.1 (a+b cot)^m (c+d cot)^n.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
A, B, a, b, c, d, e, f, m, n = symbols('A B a b c d e f m n')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=(I*a*cot(c + d*x) + a)**n,
        variable=x,
        num_steps=2,
        integral=I*(I*a*cot(c + d*x) + a)**n*hyper((1, n), (n + 1,), I*cot(c + d*x)/2 + sympy.S.Half)/(2*d*n),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(5)/2)*(a*cot(c + d*x) + a),
        variable=x,
        num_steps=5,
        integral=-sqrt(2)*a*e**(sympy.S(5)/2)*atanh(sqrt(2)*(sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/d + 2*a*e**2*sqrt(e*cot(c + d*x))/d - 2*a*e*(e*cot(c + d*x))**(sympy.S(3)/2)/(3*d) - 2*a*(e*cot(c + d*x))**(sympy.S(5)/2)/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(3)/2)*(a*cot(c + d*x) + a),
        variable=x,
        num_steps=4,
        integral=-sqrt(2)*a*e**(sympy.S(3)/2)*atan(sqrt(2)*(-sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/d - 2*a*e*sqrt(e*cot(c + d*x))/d - 2*a*(e*cot(c + d*x))**(sympy.S(3)/2)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(e*cot(c + d*x))*(a*cot(c + d*x) + a),
        variable=x,
        num_steps=3,
        integral=sqrt(2)*a*sqrt(e)*atanh(sqrt(2)*(sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/d - 2*a*sqrt(e*cot(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*cot(c + d*x) + a)/sqrt(e*cot(c + d*x)),
        variable=x,
        num_steps=2,
        integral=sqrt(2)*a*atan(sqrt(2)*sqrt(e)*(1 - cot(c + d*x))/(2*sqrt(e*cot(c + d*x))))/(d*sqrt(e)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cot(c + d*x) + a)/(e*cot(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*a/(d*e*sqrt(e*cot(c + d*x))) - sqrt(2)*a*atanh(sqrt(2)*(sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(d*e**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cot(c + d*x) + a)/(e*cot(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=2*a/(3*d*e*(e*cot(c + d*x))**(sympy.S(3)/2)) + 2*a/(d*e**2*sqrt(e*cot(c + d*x))) - sqrt(2)*a*atan(sqrt(2)*(-sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(d*e**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(5)/2)*(a*cot(c + d*x) + a)**2,
        variable=x,
        num_steps=16,
        integral=sqrt(2)*a**2*e**(sympy.S(5)/2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(2*d) - sqrt(2)*a**2*e**(sympy.S(5)/2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(2*d) + sqrt(2)*a**2*e**(sympy.S(5)/2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/d - sqrt(2)*a**2*e**(sympy.S(5)/2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/d + 4*a**2*e**2*sqrt(e*cot(c + d*x))/d - 4*a**2*(e*cot(c + d*x))**(sympy.S(5)/2)/(5*d) - 2*a**2*(e*cot(c + d*x))**(sympy.S(7)/2)/(7*d*e),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(3)/2)*(a*cot(c + d*x) + a)**2,
        variable=x,
        num_steps=15,
        integral=sqrt(2)*a**2*e**(sympy.S(3)/2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(2*d) - sqrt(2)*a**2*e**(sympy.S(3)/2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(2*d) - sqrt(2)*a**2*e**(sympy.S(3)/2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/d + sqrt(2)*a**2*e**(sympy.S(3)/2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/d - 4*a**2*(e*cot(c + d*x))**(sympy.S(3)/2)/(3*d) - 2*a**2*(e*cot(c + d*x))**(sympy.S(5)/2)/(5*d*e),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(e*cot(c + d*x))*(a*cot(c + d*x) + a)**2,
        variable=x,
        num_steps=15,
        integral=-sqrt(2)*a**2*sqrt(e)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(2*d) + sqrt(2)*a**2*sqrt(e)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(2*d) - sqrt(2)*a**2*sqrt(e)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/d + sqrt(2)*a**2*sqrt(e)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/d - 4*a**2*sqrt(e*cot(c + d*x))/d - 2*a**2*(e*cot(c + d*x))**(sympy.S(3)/2)/(3*d*e),
    ),
    RubiTestSuiteCase(
        integrand=(a*cot(c + d*x) + a)**2/sqrt(e*cot(c + d*x)),
        variable=x,
        num_steps=14,
        integral=-2*a**2*sqrt(e*cot(c + d*x))/(d*e) - sqrt(2)*a**2*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(2*d*sqrt(e)) + sqrt(2)*a**2*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(2*d*sqrt(e)) + sqrt(2)*a**2*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(d*sqrt(e)) - sqrt(2)*a**2*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(d*sqrt(e)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cot(c + d*x) + a)**2/(e*cot(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=13,
        integral=2*a**2/(d*e*sqrt(e*cot(c + d*x))) + sqrt(2)*a**2*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(2*d*e**(sympy.S(3)/2)) - sqrt(2)*a**2*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(2*d*e**(sympy.S(3)/2)) + sqrt(2)*a**2*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(d*e**(sympy.S(3)/2)) - sqrt(2)*a**2*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(d*e**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cot(c + d*x) + a)**2/(e*cot(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=14,
        integral=2*a**2/(3*d*e*(e*cot(c + d*x))**(sympy.S(3)/2)) + 4*a**2/(d*e**2*sqrt(e*cot(c + d*x))) + sqrt(2)*a**2*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(2*d*e**(sympy.S(5)/2)) - sqrt(2)*a**2*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(2*d*e**(sympy.S(5)/2)) - sqrt(2)*a**2*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(d*e**(sympy.S(5)/2)) + sqrt(2)*a**2*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(d*e**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cot(c + d*x) + a)**2/(e*cot(c + d*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=14,
        integral=2*a**2/(5*d*e*(e*cot(c + d*x))**(sympy.S(5)/2)) + 4*a**2/(3*d*e**2*(e*cot(c + d*x))**(sympy.S(3)/2)) - sqrt(2)*a**2*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(2*d*e**(sympy.S(7)/2)) + sqrt(2)*a**2*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(2*d*e**(sympy.S(7)/2)) - sqrt(2)*a**2*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(d*e**(sympy.S(7)/2)) + sqrt(2)*a**2*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(d*e**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(5)/2)*(a*cot(c + d*x) + a)**3,
        variable=x,
        num_steps=7,
        integral=2*sqrt(2)*a**3*e**(sympy.S(5)/2)*atan(sqrt(2)*(-sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/d + 4*a**3*e**2*sqrt(e*cot(c + d*x))/d + 4*a**3*e*(e*cot(c + d*x))**(sympy.S(3)/2)/(3*d) - 4*a**3*(e*cot(c + d*x))**(sympy.S(5)/2)/(5*d) - 40*a**3*(e*cot(c + d*x))**(sympy.S(7)/2)/(63*d*e) - 2*(e*cot(c + d*x))**(sympy.S(7)/2)*(a**3*cot(c + d*x) + a**3)/(9*d*e),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(3)/2)*(a*cot(c + d*x) + a)**3,
        variable=x,
        num_steps=6,
        integral=-2*sqrt(2)*a**3*e**(sympy.S(3)/2)*atanh(sqrt(2)*(sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/d + 4*a**3*e*sqrt(e*cot(c + d*x))/d - 4*a**3*(e*cot(c + d*x))**(sympy.S(3)/2)/(3*d) - 32*a**3*(e*cot(c + d*x))**(sympy.S(5)/2)/(35*d*e) - 2*(e*cot(c + d*x))**(sympy.S(5)/2)*(a**3*cot(c + d*x) + a**3)/(7*d*e),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(e*cot(c + d*x))*(a*cot(c + d*x) + a)**3,
        variable=x,
        num_steps=5,
        integral=-2*sqrt(2)*a**3*sqrt(e)*atan(sqrt(2)*(-sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/d - 4*a**3*sqrt(e*cot(c + d*x))/d - 8*a**3*(e*cot(c + d*x))**(sympy.S(3)/2)/(5*d*e) - 2*(e*cot(c + d*x))**(sympy.S(3)/2)*(a**3*cot(c + d*x) + a**3)/(5*d*e),
    ),
    RubiTestSuiteCase(
        integrand=(a*cot(c + d*x) + a)**3/sqrt(e*cot(c + d*x)),
        variable=x,
        num_steps=4,
        integral=-16*a**3*sqrt(e*cot(c + d*x))/(3*d*e) + 2*sqrt(2)*a**3*atanh(sqrt(2)*(sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(d*sqrt(e)) - 2*sqrt(e*cot(c + d*x))*(a**3*cot(c + d*x) + a**3)/(3*d*e),
    ),
    RubiTestSuiteCase(
        integrand=(a*cot(c + d*x) + a)**3/(e*cot(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=-4*a**3*sqrt(e*cot(c + d*x))/(d*e**2) + 2*sqrt(2)*a**3*atan(sqrt(2)*(-sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(d*e**(sympy.S(3)/2)) + (2*a**3*cot(c + d*x) + 2*a**3)/(d*e*sqrt(e*cot(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(a*cot(c + d*x) + a)**3/(e*cot(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=16*a**3/(3*d*e**2*sqrt(e*cot(c + d*x))) - 2*sqrt(2)*a**3*atanh(sqrt(2)*(sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(d*e**(sympy.S(5)/2)) + (2*a**3*cot(c + d*x) + 2*a**3)/(3*d*e*(e*cot(c + d*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cot(c + d*x) + a)**3/(e*cot(c + d*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=5,
        integral=8*a**3/(5*d*e**2*(e*cot(c + d*x))**(sympy.S(3)/2)) + 4*a**3/(d*e**3*sqrt(e*cot(c + d*x))) - 2*sqrt(2)*a**3*atan(sqrt(2)*(-sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(d*e**(sympy.S(7)/2)) + (2*a**3*cot(c + d*x) + 2*a**3)/(5*d*e*(e*cot(c + d*x))**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cot(c + d*x) + a)**3/(e*cot(c + d*x))**(sympy.S(9)/2),
        variable=x,
        num_steps=6,
        integral=32*a**3/(35*d*e**2*(e*cot(c + d*x))**(sympy.S(5)/2)) + 4*a**3/(3*d*e**3*(e*cot(c + d*x))**(sympy.S(3)/2)) - 4*a**3/(d*e**4*sqrt(e*cot(c + d*x))) + 2*sqrt(2)*a**3*atanh(sqrt(2)*(sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(d*e**(sympy.S(9)/2)) + (2*a**3*cot(c + d*x) + 2*a**3)/(7*d*e*(e*cot(c + d*x))**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(5)/2)/(a*cot(c + d*x) + a),
        variable=x,
        num_steps=7,
        integral=e**(sympy.S(5)/2)*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(a*d) - sqrt(2)*e**(sympy.S(5)/2)*atan(sqrt(2)*(-sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(2*a*d) - 2*e**2*sqrt(e*cot(c + d*x))/(a*d),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(3)/2)/(a*cot(c + d*x) + a),
        variable=x,
        num_steps=6,
        integral=-e**(sympy.S(3)/2)*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(a*d) + sqrt(2)*e**(sympy.S(3)/2)*atanh(sqrt(2)*(sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(2*a*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(e*cot(c + d*x))/(a*cot(c + d*x) + a),
        variable=x,
        num_steps=6,
        integral=sqrt(e)*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(a*d) + sqrt(2)*sqrt(e)*atan(sqrt(2)*(-sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(2*a*d),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(e*cot(c + d*x))*(a*cot(c + d*x) + a)),
        variable=x,
        num_steps=6,
        integral=-atan(sqrt(e*cot(c + d*x))/sqrt(e))/(a*d*sqrt(e)) - sqrt(2)*atanh(sqrt(2)*sqrt(e)*(cot(c + d*x) + 1)/(2*sqrt(e*cot(c + d*x))))/(2*a*d*sqrt(e)),
    ),
    RubiTestSuiteCase(
        integrand=1/((e*cot(c + d*x))**(sympy.S(3)/2)*(a*cot(c + d*x) + a)),
        variable=x,
        num_steps=7,
        integral=2/(a*d*e*sqrt(e*cot(c + d*x))) + atan(sqrt(e*cot(c + d*x))/sqrt(e))/(a*d*e**(sympy.S(3)/2)) - sqrt(2)*atan(sqrt(2)*(-sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(2*a*d*e**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/((e*cot(c + d*x))**(sympy.S(5)/2)*(a*cot(c + d*x) + a)),
        variable=x,
        num_steps=10,
        integral=2/(3*a*d*e*(e*cot(c + d*x))**(sympy.S(3)/2)) - 2/(a*d*e**2*sqrt(e*cot(c + d*x))) - atan(sqrt(e*cot(c + d*x))/sqrt(e))/(a*d*e**(sympy.S(5)/2)) + sqrt(2)*atanh(sqrt(2)*(sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(2*a*d*e**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(5)/2)/(a*cot(c + d*x) + a)**2,
        variable=x,
        num_steps=17,
        integral=e**2*sqrt(e*cot(c + d*x))/(2*d*(a**2*cot(c + d*x) + a**2)) - sqrt(2)*e**(sympy.S(5)/2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(8*a**2*d) + sqrt(2)*e**(sympy.S(5)/2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(8*a**2*d) - 3*e**(sympy.S(5)/2)*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(2*a**2*d) - sqrt(2)*e**(sympy.S(5)/2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(4*a**2*d) + sqrt(2)*e**(sympy.S(5)/2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(4*a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(3)/2)/(a*cot(c + d*x) + a)**2,
        variable=x,
        num_steps=18,
        integral=-e*sqrt(e*cot(c + d*x))/(2*d*(a**2*cot(c + d*x) + a**2)) - sqrt(2)*e**(sympy.S(3)/2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(8*a**2*d) + sqrt(2)*e**(sympy.S(3)/2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(8*a**2*d) + e**(sympy.S(3)/2)*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(2*a**2*d) + sqrt(2)*e**(sympy.S(3)/2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(4*a**2*d) - sqrt(2)*e**(sympy.S(3)/2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(4*a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(e*cot(c + d*x))/(a*cot(c + d*x) + a)**2,
        variable=x,
        num_steps=17,
        integral=sqrt(e*cot(c + d*x))/(2*d*(a**2*cot(c + d*x) + a**2)) + sqrt(2)*sqrt(e)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(8*a**2*d) - sqrt(2)*sqrt(e)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(8*a**2*d) + sqrt(e)*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(2*a**2*d) + sqrt(2)*sqrt(e)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(4*a**2*d) - sqrt(2)*sqrt(e)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(4*a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(e*cot(c + d*x))*(a*cot(c + d*x) + a)**2),
        variable=x,
        num_steps=18,
        integral=-sqrt(e*cot(c + d*x))/(2*d*e*(a**2*cot(c + d*x) + a**2)) + sqrt(2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(8*a**2*d*sqrt(e)) - sqrt(2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(8*a**2*d*sqrt(e)) - 3*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(2*a**2*d*sqrt(e)) - sqrt(2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(4*a**2*d*sqrt(e)) + sqrt(2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(4*a**2*d*sqrt(e)),
    ),
    RubiTestSuiteCase(
        integrand=1/((e*cot(c + d*x))**(sympy.S(3)/2)*(a*cot(c + d*x) + a)**2),
        variable=x,
        num_steps=18,
        integral=-1/(2*d*e*sqrt(e*cot(c + d*x))*(a**2*cot(c + d*x) + a**2)) + 5/(2*a**2*d*e*sqrt(e*cot(c + d*x))) - sqrt(2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(8*a**2*d*e**(sympy.S(3)/2)) + sqrt(2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(8*a**2*d*e**(sympy.S(3)/2)) + 5*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(2*a**2*d*e**(sympy.S(3)/2)) - sqrt(2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(4*a**2*d*e**(sympy.S(3)/2)) + sqrt(2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(4*a**2*d*e**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/((e*cot(c + d*x))**(sympy.S(5)/2)*(a*cot(c + d*x) + a)**2),
        variable=x,
        num_steps=20,
        integral=-1/(2*d*e*(e*cot(c + d*x))**(sympy.S(3)/2)*(a**2*cot(c + d*x) + a**2)) + 7/(6*a**2*d*e*(e*cot(c + d*x))**(sympy.S(3)/2)) - 9/(2*a**2*d*e**2*sqrt(e*cot(c + d*x))) - sqrt(2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(8*a**2*d*e**(sympy.S(5)/2)) + sqrt(2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(8*a**2*d*e**(sympy.S(5)/2)) - 7*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(2*a**2*d*e**(sympy.S(5)/2)) + sqrt(2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(4*a**2*d*e**(sympy.S(5)/2)) - sqrt(2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(4*a**2*d*e**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(5)/2)/(a*cot(c + d*x) + a)**3,
        variable=x,
        num_steps=8,
        integral=e**2*sqrt(e*cot(c + d*x))/(4*a*d*(a*cot(c + d*x) + a)**2) - e**(sympy.S(5)/2)*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(8*a**3*d) + sqrt(2)*e**(sympy.S(5)/2)*atanh(sqrt(2)*(sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(4*a**3*d) - 5*e**2*sqrt(e*cot(c + d*x))/(8*a**3*d*(cot(c + d*x) + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(3)/2)/(a*cot(c + d*x) + a)**3,
        variable=x,
        num_steps=8,
        integral=e*sqrt(e*cot(c + d*x))/(8*d*(a**3*cot(c + d*x) + a**3)) - e*sqrt(e*cot(c + d*x))/(4*a*d*(a*cot(c + d*x) + a)**2) + 5*e**(sympy.S(3)/2)*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(8*a**3*d) + sqrt(2)*e**(sympy.S(3)/2)*atan(sqrt(2)*(-sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(4*a**3*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(e*cot(c + d*x))/(a*cot(c + d*x) + a)**3,
        variable=x,
        num_steps=8,
        integral=3*sqrt(e*cot(c + d*x))/(8*d*(a**3*cot(c + d*x) + a**3)) + sqrt(e*cot(c + d*x))/(4*a*d*(a*cot(c + d*x) + a)**2) - sqrt(e)*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(8*a**3*d) - sqrt(2)*sqrt(e)*atanh(sqrt(2)*(sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(4*a**3*d),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(e*cot(c + d*x))*(a*cot(c + d*x) + a)**3),
        variable=x,
        num_steps=8,
        integral=-sqrt(e*cot(c + d*x))/(4*a*d*e*(a*cot(c + d*x) + a)**2) - 7*sqrt(e*cot(c + d*x))/(8*a**3*d*e*(cot(c + d*x) + 1)) - 11*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(8*a**3*d*sqrt(e)) - sqrt(2)*atan(sqrt(2)*(-sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(4*a**3*d*sqrt(e)),
    ),
    RubiTestSuiteCase(
        integrand=1/((e*cot(c + d*x))**(sympy.S(3)/2)*(a*cot(c + d*x) + a)**3),
        variable=x,
        num_steps=9,
        integral=-1/(4*a*d*e*sqrt(e*cot(c + d*x))*(a*cot(c + d*x) + a)**2) + 27/(8*a**3*d*e*sqrt(e*cot(c + d*x))) - 9/(8*a**3*d*e*sqrt(e*cot(c + d*x))*(cot(c + d*x) + 1)) + 31*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(8*a**3*d*e**(sympy.S(3)/2)) + sqrt(2)*atanh(sqrt(2)*(sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(4*a**3*d*e**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/((e*cot(c + d*x))**(sympy.S(5)/2)*(a*cot(c + d*x) + a)**3),
        variable=x,
        num_steps=10,
        integral=-1/(4*a*d*e*(e*cot(c + d*x))**(sympy.S(3)/2)*(a*cot(c + d*x) + a)**2) + 55/(24*a**3*d*e*(e*cot(c + d*x))**(sympy.S(3)/2)) - 11/(8*a**3*d*e*(e*cot(c + d*x))**(sympy.S(3)/2)*(cot(c + d*x) + 1)) - 63/(8*a**3*d*e**2*sqrt(e*cot(c + d*x))) - 59*atan(sqrt(e*cot(c + d*x))/sqrt(e))/(8*a**3*d*e**(sympy.S(5)/2)) + sqrt(2)*atan(sqrt(2)*(-sqrt(e)*cot(c + d*x) + sqrt(e))/(2*sqrt(e*cot(c + d*x))))/(4*a**3*d*e**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(cot(x) + 1)*cot(x)**2,
        variable=x,
        num_steps=12,
        integral=-2*(cot(x) + 1)**(sympy.S(3)/2)/3 + log(-sqrt(2 + 2*sqrt(2))*sqrt(cot(x) + 1) + cot(x) + 1 + sqrt(2))/(2*sqrt(2 + 2*sqrt(2))) - log(sqrt(2 + 2*sqrt(2))*sqrt(cot(x) + 1) + cot(x) + 1 + sqrt(2))/(2*sqrt(2 + 2*sqrt(2))) - sqrt(sympy.S.Half + sqrt(2)/2)*atan((-2*sqrt(cot(x) + 1) + sqrt(2 + 2*sqrt(2)))/sqrt(-2 + 2*sqrt(2))) + sqrt(sympy.S.Half + sqrt(2)/2)*atan((2*sqrt(cot(x) + 1) + sqrt(2 + 2*sqrt(2)))/sqrt(-2 + 2*sqrt(2))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(cot(x) + 1)*cot(x),
        variable=x,
        num_steps=6,
        integral=-2*sqrt(cot(x) + 1) + sqrt(sympy.S(-1)/2 + sqrt(2)/2)*atan(((2 - sqrt(2))*cot(x) - 3*sqrt(2) + 4)/(2*sqrt(-7 + 5*sqrt(2))*sqrt(cot(x) + 1))) + sqrt(sympy.S.Half + sqrt(2)/2)*atanh(((sqrt(2) + 2)*cot(x) + 4 + 3*sqrt(2))/(2*sqrt(7 + 5*sqrt(2))*sqrt(cot(x) + 1))),
    ),
    RubiTestSuiteCase(
        integrand=(cot(x) + 1)**(sympy.S(3)/2)*cot(x)**2,
        variable=x,
        num_steps=8,
        integral=-2*(cot(x) + 1)**(sympy.S(5)/2)/5 + 2*sqrt(cot(x) + 1) - sqrt(-1 + sqrt(2))*atan(((1 - sqrt(2))*cot(x) - 2*sqrt(2) + 3)/(sqrt(-14 + 10*sqrt(2))*sqrt(cot(x) + 1))) - sqrt(1 + sqrt(2))*atanh(((1 + sqrt(2))*cot(x) + 2*sqrt(2) + 3)/(sqrt(14 + 10*sqrt(2))*sqrt(cot(x) + 1))),
    ),
    RubiTestSuiteCase(
        integrand=(cot(x) + 1)**(sympy.S(3)/2)*cot(x),
        variable=x,
        num_steps=14,
        integral=-2*(cot(x) + 1)**(sympy.S(3)/2)/3 - 2*sqrt(cot(x) + 1) - log(-sqrt(2 + 2*sqrt(2))*sqrt(cot(x) + 1) + cot(x) + 1 + sqrt(2))/(2*sqrt(1 + sqrt(2))) + log(sqrt(2 + 2*sqrt(2))*sqrt(cot(x) + 1) + cot(x) + 1 + sqrt(2))/(2*sqrt(1 + sqrt(2))) - sqrt(1 + sqrt(2))*atan((-2*sqrt(cot(x) + 1) + sqrt(2 + 2*sqrt(2)))/sqrt(-2 + 2*sqrt(2))) + sqrt(1 + sqrt(2))*atan((2*sqrt(cot(x) + 1) + sqrt(2 + 2*sqrt(2)))/sqrt(-2 + 2*sqrt(2))),
    ),
    RubiTestSuiteCase(
        integrand=cot(x)**2/sqrt(cot(x) + 1),
        variable=x,
        num_steps=12,
        integral=-2*sqrt(cot(x) + 1) - log(-sqrt(2 + 2*sqrt(2))*sqrt(cot(x) + 1) + cot(x) + 1 + sqrt(2))/(4*sqrt(1 + sqrt(2))) + log(sqrt(2 + 2*sqrt(2))*sqrt(cot(x) + 1) + cot(x) + 1 + sqrt(2))/(4*sqrt(1 + sqrt(2))) - sqrt(1 + sqrt(2))*atan((-2*sqrt(cot(x) + 1) + sqrt(2 + 2*sqrt(2)))/sqrt(-2 + 2*sqrt(2)))/2 + sqrt(1 + sqrt(2))*atan((2*sqrt(cot(x) + 1) + sqrt(2 + 2*sqrt(2)))/sqrt(-2 + 2*sqrt(2)))/2,
    ),
    RubiTestSuiteCase(
        integrand=cot(x)/sqrt(cot(x) + 1),
        variable=x,
        num_steps=5,
        integral=sqrt(-1 + sqrt(2))*atan(((1 - sqrt(2))*cot(x) - 2*sqrt(2) + 3)/(sqrt(-14 + 10*sqrt(2))*sqrt(cot(x) + 1)))/2 + sqrt(1 + sqrt(2))*atanh(((1 + sqrt(2))*cot(x) + 2*sqrt(2) + 3)/(sqrt(14 + 10*sqrt(2))*sqrt(cot(x) + 1)))/2,
    ),
    RubiTestSuiteCase(
        integrand=cot(x)**2/(cot(x) + 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=sqrt(sympy.S(-1)/2 + sqrt(2)/2)*atan(((2 - sqrt(2))*cot(x) - 3*sqrt(2) + 4)/(2*sqrt(-7 + 5*sqrt(2))*sqrt(cot(x) + 1)))/2 + sqrt(sympy.S.Half + sqrt(2)/2)*atanh(((sqrt(2) + 2)*cot(x) + 4 + 3*sqrt(2))/(2*sqrt(7 + 5*sqrt(2))*sqrt(cot(x) + 1)))/2 + 1/sqrt(cot(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=cot(x)/(cot(x) + 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=13,
        integral=-log(-sqrt(2 + 2*sqrt(2))*sqrt(cot(x) + 1) + cot(x) + 1 + sqrt(2))/(4*sqrt(2 + 2*sqrt(2))) + log(sqrt(2 + 2*sqrt(2))*sqrt(cot(x) + 1) + cot(x) + 1 + sqrt(2))/(4*sqrt(2 + 2*sqrt(2))) + sqrt(sympy.S.Half + sqrt(2)/2)*atan((-2*sqrt(cot(x) + 1) + sqrt(2 + 2*sqrt(2)))/sqrt(-2 + 2*sqrt(2)))/2 - sqrt(sympy.S.Half + sqrt(2)/2)*atan((2*sqrt(cot(x) + 1) + sqrt(2 + 2*sqrt(2)))/sqrt(-2 + 2*sqrt(2)))/2 - 1/sqrt(cot(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=cot(x)**2/(cot(x) + 1)**(sympy.S(5)/2),
        variable=x,
        num_steps=8,
        integral=sqrt(-1 + sqrt(2))*atan(((1 - sqrt(2))*cot(x) - 2*sqrt(2) + 3)/(sqrt(-14 + 10*sqrt(2))*sqrt(cot(x) + 1)))/4 + sqrt(1 + sqrt(2))*atanh(((1 + sqrt(2))*cot(x) + 2*sqrt(2) + 3)/(sqrt(14 + 10*sqrt(2))*sqrt(cot(x) + 1)))/4 - 1/sqrt(cot(x) + 1) + 1/(3*(cot(x) + 1)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cot(x)/(cot(x) + 1)**(sympy.S(5)/2),
        variable=x,
        num_steps=13,
        integral=log(-sqrt(2 + 2*sqrt(2))*sqrt(cot(x) + 1) + cot(x) + 1 + sqrt(2))/(8*sqrt(1 + sqrt(2))) - log(sqrt(2 + 2*sqrt(2))*sqrt(cot(x) + 1) + cot(x) + 1 + sqrt(2))/(8*sqrt(1 + sqrt(2))) + sqrt(1 + sqrt(2))*atan((-2*sqrt(cot(x) + 1) + sqrt(2 + 2*sqrt(2)))/sqrt(-2 + 2*sqrt(2)))/4 - sqrt(1 + sqrt(2))*atan((2*sqrt(cot(x) + 1) + sqrt(2 + 2*sqrt(2)))/sqrt(-2 + 2*sqrt(2)))/4 - 1/(3*(cot(x) + 1)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(3)/2)*(a + b*cot(c + d*x)),
        variable=x,
        num_steps=12,
        integral=-2*a*e*sqrt(e*cot(c + d*x))/d - 2*b*(e*cot(c + d*x))**(sympy.S(3)/2)/(3*d) - sqrt(2)*e**(sympy.S(3)/2)*(a - b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d) + sqrt(2)*e**(sympy.S(3)/2)*(a - b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d) - sqrt(2)*e**(sympy.S(3)/2)*(a + b)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d) + sqrt(2)*e**(sympy.S(3)/2)*(a + b)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(e*cot(c + d*x))*(a + b*cot(c + d*x)),
        variable=x,
        num_steps=11,
        integral=-2*b*sqrt(e*cot(c + d*x))/d + sqrt(2)*sqrt(e)*(a - b)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d) - sqrt(2)*sqrt(e)*(a - b)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d) - sqrt(2)*sqrt(e)*(a + b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d) + sqrt(2)*sqrt(e)*(a + b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cot(c + d*x))/sqrt(e*cot(c + d*x)),
        variable=x,
        num_steps=10,
        integral=sqrt(2)*(a - b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*sqrt(e)) - sqrt(2)*(a - b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*sqrt(e)) + sqrt(2)*(a + b)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*sqrt(e)) - sqrt(2)*(a + b)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*sqrt(e)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cot(c + d*x))/(e*cot(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=11,
        integral=2*a/(d*e*sqrt(e*cot(c + d*x))) - sqrt(2)*(a - b)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(3)/2)) + sqrt(2)*(a - b)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(3)/2)) + sqrt(2)*(a + b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(3)/2)) - sqrt(2)*(a + b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cot(c + d*x))/(e*cot(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=12,
        integral=2*a/(3*d*e*(e*cot(c + d*x))**(sympy.S(3)/2)) + 2*b/(d*e**2*sqrt(e*cot(c + d*x))) - sqrt(2)*(a - b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(5)/2)) + sqrt(2)*(a - b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(5)/2)) - sqrt(2)*(a + b)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(5)/2)) + sqrt(2)*(a + b)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(3)/2)*(a + b*cot(c + d*x))**2,
        variable=x,
        num_steps=13,
        integral=-4*a*b*(e*cot(c + d*x))**(sympy.S(3)/2)/(3*d) - 2*b**2*(e*cot(c + d*x))**(sympy.S(5)/2)/(5*d*e) - sqrt(2)*e**(sympy.S(3)/2)*(a**2 - 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d) + sqrt(2)*e**(sympy.S(3)/2)*(a**2 - 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d) - sqrt(2)*e**(sympy.S(3)/2)*(a**2 + 2*a*b - b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d) + sqrt(2)*e**(sympy.S(3)/2)*(a**2 + 2*a*b - b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d) - e*sqrt(e*cot(c + d*x))*(2*a**2 - 2*b**2)/d,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(e*cot(c + d*x))*(a + b*cot(c + d*x))**2,
        variable=x,
        num_steps=12,
        integral=-4*a*b*sqrt(e*cot(c + d*x))/d - 2*b**2*(e*cot(c + d*x))**(sympy.S(3)/2)/(3*d*e) + sqrt(2)*sqrt(e)*(a**2 - 2*a*b - b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d) - sqrt(2)*sqrt(e)*(a**2 - 2*a*b - b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d) - sqrt(2)*sqrt(e)*(a**2 + 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d) + sqrt(2)*sqrt(e)*(a**2 + 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cot(c + d*x))**2/sqrt(e*cot(c + d*x)),
        variable=x,
        num_steps=11,
        integral=-2*b**2*sqrt(e*cot(c + d*x))/(d*e) + sqrt(2)*(a**2 - 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*sqrt(e)) - sqrt(2)*(a**2 - 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*sqrt(e)) + sqrt(2)*(a**2 + 2*a*b - b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*sqrt(e)) - sqrt(2)*(a**2 + 2*a*b - b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*sqrt(e)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cot(c + d*x))**2/(e*cot(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=11,
        integral=2*a**2/(d*e*sqrt(e*cot(c + d*x))) - sqrt(2)*(a**2 - 2*a*b - b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(3)/2)) + sqrt(2)*(a**2 - 2*a*b - b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(3)/2)) + sqrt(2)*(a**2 + 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(3)/2)) - sqrt(2)*(a**2 + 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cot(c + d*x))**2/(e*cot(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=12,
        integral=2*a**2/(3*d*e*(e*cot(c + d*x))**(sympy.S(3)/2)) + 4*a*b/(d*e**2*sqrt(e*cot(c + d*x))) - sqrt(2)*(a**2 - 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(5)/2)) + sqrt(2)*(a**2 - 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(5)/2)) - sqrt(2)*(a**2 + 2*a*b - b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(5)/2)) + sqrt(2)*(a**2 + 2*a*b - b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cot(c + d*x))**2/(e*cot(c + d*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=13,
        integral=2*a**2/(5*d*e*(e*cot(c + d*x))**(sympy.S(5)/2)) + 4*a*b/(3*d*e**2*(e*cot(c + d*x))**(sympy.S(3)/2)) - (2*a**2 - 2*b**2)/(d*e**3*sqrt(e*cot(c + d*x))) + sqrt(2)*(a**2 - 2*a*b - b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(7)/2)) - sqrt(2)*(a**2 - 2*a*b - b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(7)/2)) - sqrt(2)*(a**2 + 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(7)/2)) + sqrt(2)*(a**2 + 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(3)/2)*(a + b*cot(c + d*x))**3,
        variable=x,
        num_steps=14,
        integral=-32*a*b**2*(e*cot(c + d*x))**(sympy.S(5)/2)/(35*d*e) - 2*a*e*sqrt(e*cot(c + d*x))*(a**2 - 3*b**2)/d - 2*b**2*(e*cot(c + d*x))**(sympy.S(5)/2)*(a + b*cot(c + d*x))/(7*d*e) - 2*b*(e*cot(c + d*x))**(sympy.S(3)/2)*(3*a**2 - b**2)/(3*d) - sqrt(2)*e**(sympy.S(3)/2)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d) + sqrt(2)*e**(sympy.S(3)/2)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d) - sqrt(2)*e**(sympy.S(3)/2)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d) + sqrt(2)*e**(sympy.S(3)/2)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(e*cot(c + d*x))*(a + b*cot(c + d*x))**3,
        variable=x,
        num_steps=13,
        integral=-8*a*b**2*(e*cot(c + d*x))**(sympy.S(3)/2)/(5*d*e) - 2*b**2*(e*cot(c + d*x))**(sympy.S(3)/2)*(a + b*cot(c + d*x))/(5*d*e) - 2*b*sqrt(e*cot(c + d*x))*(3*a**2 - b**2)/d - sqrt(2)*sqrt(e)*(a - b)*(a**2 + 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d) + sqrt(2)*sqrt(e)*(a - b)*(a**2 + 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d) + sqrt(2)*sqrt(e)*(a + b)*(a**2 - 4*a*b + b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d) - sqrt(2)*sqrt(e)*(a + b)*(a**2 - 4*a*b + b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cot(c + d*x))**3/sqrt(e*cot(c + d*x)),
        variable=x,
        num_steps=12,
        integral=-16*a*b**2*sqrt(e*cot(c + d*x))/(3*d*e) - 2*b**2*sqrt(e*cot(c + d*x))*(a + b*cot(c + d*x))/(3*d*e) + sqrt(2)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*sqrt(e)) - sqrt(2)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*sqrt(e)) + sqrt(2)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*sqrt(e)) - sqrt(2)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*sqrt(e)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cot(c + d*x))**3/(e*cot(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=12,
        integral=2*a**2*(a + b*cot(c + d*x))/(d*e*sqrt(e*cot(c + d*x))) - 2*b*sqrt(e*cot(c + d*x))*(a**2 + b**2)/(d*e**2) + sqrt(2)*(a - b)*(a**2 + 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(3)/2)) - sqrt(2)*(a - b)*(a**2 + 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(3)/2)) - sqrt(2)*(a + b)*(a**2 - 4*a*b + b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(3)/2)) + sqrt(2)*(a + b)*(a**2 - 4*a*b + b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cot(c + d*x))**3/(e*cot(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=12,
        integral=16*a**2*b/(3*d*e**2*sqrt(e*cot(c + d*x))) + 2*a**2*(a + b*cot(c + d*x))/(3*d*e*(e*cot(c + d*x))**(sympy.S(3)/2)) - sqrt(2)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(5)/2)) + sqrt(2)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(5)/2)) - sqrt(2)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(5)/2)) + sqrt(2)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cot(c + d*x))**3/(e*cot(c + d*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=13,
        integral=8*a**2*b/(5*d*e**2*(e*cot(c + d*x))**(sympy.S(3)/2)) + 2*a**2*(a + b*cot(c + d*x))/(5*d*e*(e*cot(c + d*x))**(sympy.S(5)/2)) - 2*a*(a**2 - 3*b**2)/(d*e**3*sqrt(e*cot(c + d*x))) - sqrt(2)*(a - b)*(a**2 + 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(7)/2)) + sqrt(2)*(a - b)*(a**2 + 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(7)/2)) + sqrt(2)*(a + b)*(a**2 - 4*a*b + b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(7)/2)) - sqrt(2)*(a + b)*(a**2 - 4*a*b + b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cot(c + d*x))**3/(e*cot(c + d*x))**(sympy.S(9)/2),
        variable=x,
        num_steps=14,
        integral=32*a**2*b/(35*d*e**2*(e*cot(c + d*x))**(sympy.S(5)/2)) + 2*a**2*(a + b*cot(c + d*x))/(7*d*e*(e*cot(c + d*x))**(sympy.S(7)/2)) - 2*a*(a**2 - 3*b**2)/(3*d*e**3*(e*cot(c + d*x))**(sympy.S(3)/2)) - 2*b*(3*a**2 - b**2)/(d*e**4*sqrt(e*cot(c + d*x))) + sqrt(2)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(9)/2)) - sqrt(2)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(9)/2)) + sqrt(2)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(9)/2)) - sqrt(2)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(9)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(5)/2)/(a + b*cot(c + d*x)),
        variable=x,
        num_steps=15,
        integral=2*a**(sympy.S(5)/2)*e**(sympy.S(5)/2)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(b**(sympy.S(3)/2)*d*(a**2 + b**2)) + sqrt(2)*e**(sympy.S(5)/2)*(a - b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)) - sqrt(2)*e**(sympy.S(5)/2)*(a - b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)) - sqrt(2)*e**(sympy.S(5)/2)*(a + b)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)) + sqrt(2)*e**(sympy.S(5)/2)*(a + b)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)) - 2*e**2*sqrt(e*cot(c + d*x))/(b*d),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(3)/2)/(a + b*cot(c + d*x)),
        variable=x,
        num_steps=14,
        integral=-2*a**(sympy.S(3)/2)*e**(sympy.S(3)/2)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(sqrt(b)*d*(a**2 + b**2)) - sqrt(2)*e**(sympy.S(3)/2)*(a - b)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)) + sqrt(2)*e**(sympy.S(3)/2)*(a - b)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)) - sqrt(2)*e**(sympy.S(3)/2)*(a + b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)) + sqrt(2)*e**(sympy.S(3)/2)*(a + b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(e*cot(c + d*x))/(a + b*cot(c + d*x)),
        variable=x,
        num_steps=14,
        integral=2*sqrt(a)*sqrt(b)*sqrt(e)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(d*(a**2 + b**2)) - sqrt(2)*sqrt(e)*(a - b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)) + sqrt(2)*sqrt(e)*(a - b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)) + sqrt(2)*sqrt(e)*(a + b)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)) - sqrt(2)*sqrt(e)*(a + b)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(e*cot(c + d*x))*(a + b*cot(c + d*x))),
        variable=x,
        num_steps=14,
        integral=sqrt(2)*(a - b)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*sqrt(e)*(a**2 + b**2)) - sqrt(2)*(a - b)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*sqrt(e)*(a**2 + b**2)) + sqrt(2)*(a + b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*sqrt(e)*(a**2 + b**2)) - sqrt(2)*(a + b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*sqrt(e)*(a**2 + b**2)) - 2*b**(sympy.S(3)/2)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(sqrt(a)*d*sqrt(e)*(a**2 + b**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/((e*cot(c + d*x))**(sympy.S(3)/2)*(a + b*cot(c + d*x))),
        variable=x,
        num_steps=15,
        integral=sqrt(2)*(a - b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(3)/2)*(a**2 + b**2)) - sqrt(2)*(a - b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(3)/2)*(a**2 + b**2)) - sqrt(2)*(a + b)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(3)/2)*(a**2 + b**2)) + sqrt(2)*(a + b)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(3)/2)*(a**2 + b**2)) + 2/(a*d*e*sqrt(e*cot(c + d*x))) + 2*b**(sympy.S(5)/2)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(a**(sympy.S(3)/2)*d*e**(sympy.S(3)/2)*(a**2 + b**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/((e*cot(c + d*x))**(sympy.S(5)/2)*(a + b*cot(c + d*x))),
        variable=x,
        num_steps=16,
        integral=-sqrt(2)*(a - b)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(5)/2)*(a**2 + b**2)) + sqrt(2)*(a - b)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(5)/2)*(a**2 + b**2)) - sqrt(2)*(a + b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(5)/2)*(a**2 + b**2)) + sqrt(2)*(a + b)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(5)/2)*(a**2 + b**2)) + 2/(3*a*d*e*(e*cot(c + d*x))**(sympy.S(3)/2)) - 2*b/(a**2*d*e**2*sqrt(e*cot(c + d*x))) - 2*b**(sympy.S(7)/2)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(a**(sympy.S(5)/2)*d*e**(sympy.S(5)/2)*(a**2 + b**2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(7)/2)/(a + b*cot(c + d*x))**2,
        variable=x,
        num_steps=16,
        integral=a**(sympy.S(5)/2)*e**(sympy.S(7)/2)*(3*a**2 + 7*b**2)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(b**(sympy.S(5)/2)*d*(a**2 + b**2)**2) + a**2*e**2*(e*cot(c + d*x))**(sympy.S(3)/2)/(b*d*(a + b*cot(c + d*x))*(a**2 + b**2)) + sqrt(2)*e**(sympy.S(7)/2)*(a**2 - 2*a*b - b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**2) - sqrt(2)*e**(sympy.S(7)/2)*(a**2 - 2*a*b - b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**2) + sqrt(2)*e**(sympy.S(7)/2)*(a**2 + 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**2) - sqrt(2)*e**(sympy.S(7)/2)*(a**2 + 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**2) - e**3*sqrt(e*cot(c + d*x))*(3*a**2 + 2*b**2)/(b**2*d*(a**2 + b**2)),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(5)/2)/(a + b*cot(c + d*x))**2,
        variable=x,
        num_steps=15,
        integral=-a**(sympy.S(3)/2)*e**(sympy.S(5)/2)*(a**2 + 5*b**2)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(b**(sympy.S(3)/2)*d*(a**2 + b**2)**2) + a**2*e**2*sqrt(e*cot(c + d*x))/(b*d*(a + b*cot(c + d*x))*(a**2 + b**2)) + sqrt(2)*e**(sympy.S(5)/2)*(a**2 - 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**2) - sqrt(2)*e**(sympy.S(5)/2)*(a**2 - 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**2) - sqrt(2)*e**(sympy.S(5)/2)*(a**2 + 2*a*b - b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**2) + sqrt(2)*e**(sympy.S(5)/2)*(a**2 + 2*a*b - b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(3)/2)/(a + b*cot(c + d*x))**2,
        variable=x,
        num_steps=15,
        integral=-sqrt(a)*e**(sympy.S(3)/2)*(a**2 - 3*b**2)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(sqrt(b)*d*(a**2 + b**2)**2) - a*e*sqrt(e*cot(c + d*x))/(d*(a + b*cot(c + d*x))*(a**2 + b**2)) - sqrt(2)*e**(sympy.S(3)/2)*(a**2 - 2*a*b - b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**2) + sqrt(2)*e**(sympy.S(3)/2)*(a**2 - 2*a*b - b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**2) - sqrt(2)*e**(sympy.S(3)/2)*(a**2 + 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**2) + sqrt(2)*e**(sympy.S(3)/2)*(a**2 + 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(e*cot(c + d*x))/(a + b*cot(c + d*x))**2,
        variable=x,
        num_steps=15,
        integral=b*sqrt(e*cot(c + d*x))/(d*(a + b*cot(c + d*x))*(a**2 + b**2)) - sqrt(2)*sqrt(e)*(a**2 - 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**2) + sqrt(2)*sqrt(e)*(a**2 - 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**2) + sqrt(2)*sqrt(e)*(a**2 + 2*a*b - b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**2) - sqrt(2)*sqrt(e)*(a**2 + 2*a*b - b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**2) + sqrt(b)*sqrt(e)*(3*a**2 - b**2)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(sqrt(a)*d*(a**2 + b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(e*cot(c + d*x))*(a + b*cot(c + d*x))**2),
        variable=x,
        num_steps=15,
        integral=sqrt(2)*(a**2 - 2*a*b - b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*sqrt(e)*(a**2 + b**2)**2) - sqrt(2)*(a**2 - 2*a*b - b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*sqrt(e)*(a**2 + b**2)**2) + sqrt(2)*(a**2 + 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*sqrt(e)*(a**2 + b**2)**2) - sqrt(2)*(a**2 + 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*sqrt(e)*(a**2 + b**2)**2) - b**2*sqrt(e*cot(c + d*x))/(a*d*e*(a + b*cot(c + d*x))*(a**2 + b**2)) - b**(sympy.S(3)/2)*(5*a**2 + b**2)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(a**(sympy.S(3)/2)*d*sqrt(e)*(a**2 + b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=1/((e*cot(c + d*x))**(sympy.S(3)/2)*(a + b*cot(c + d*x))**2),
        variable=x,
        num_steps=16,
        integral=sqrt(2)*(a**2 - 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(3)/2)*(a**2 + b**2)**2) - sqrt(2)*(a**2 - 2*a*b - b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(3)/2)*(a**2 + b**2)**2) - sqrt(2)*(a**2 + 2*a*b - b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(3)/2)*(a**2 + b**2)**2) + sqrt(2)*(a**2 + 2*a*b - b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(3)/2)*(a**2 + b**2)**2) - b**2/(a*d*e*sqrt(e*cot(c + d*x))*(a + b*cot(c + d*x))*(a**2 + b**2)) + (2*a**2 + 3*b**2)/(a**2*d*e*sqrt(e*cot(c + d*x))*(a**2 + b**2)) + b**(sympy.S(5)/2)*(7*a**2 + 3*b**2)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(a**(sympy.S(5)/2)*d*e**(sympy.S(3)/2)*(a**2 + b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(9)/2)/(a + b*cot(c + d*x))**3,
        variable=x,
        num_steps=17,
        integral=a**(sympy.S(5)/2)*e**(sympy.S(9)/2)*(15*a**4 + 46*a**2*b**2 + 63*b**4)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(4*b**(sympy.S(7)/2)*d*(a**2 + b**2)**3) + a**2*e**2*(e*cot(c + d*x))**(sympy.S(5)/2)/(2*b*d*(a + b*cot(c + d*x))**2*(a**2 + b**2)) + a**2*e**3*(e*cot(c + d*x))**(sympy.S(3)/2)*(5*a**2 + 13*b**2)/(4*b**2*d*(a + b*cot(c + d*x))*(a**2 + b**2)**2) + sqrt(2)*e**(sympy.S(9)/2)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**3) - sqrt(2)*e**(sympy.S(9)/2)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**3) - sqrt(2)*e**(sympy.S(9)/2)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**3) + sqrt(2)*e**(sympy.S(9)/2)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**3) - e**4*sqrt(e*cot(c + d*x))*(15*a**4 + 31*a**2*b**2 + 8*b**4)/(4*b**3*d*(a**2 + b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(7)/2)/(a + b*cot(c + d*x))**3,
        variable=x,
        num_steps=16,
        integral=-a**(sympy.S(3)/2)*e**(sympy.S(7)/2)*(3*a**4 + 6*a**2*b**2 + 35*b**4)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(4*b**(sympy.S(5)/2)*d*(a**2 + b**2)**3) + a**2*e**2*(e*cot(c + d*x))**(sympy.S(3)/2)/(2*b*d*(a + b*cot(c + d*x))**2*(a**2 + b**2)) + a**2*e**3*sqrt(e*cot(c + d*x))*(3*a**2 + 11*b**2)/(4*b**2*d*(a + b*cot(c + d*x))*(a**2 + b**2)**2) + sqrt(2)*e**(sympy.S(7)/2)*(a - b)*(a**2 + 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**3) - sqrt(2)*e**(sympy.S(7)/2)*(a - b)*(a**2 + 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**3) + sqrt(2)*e**(sympy.S(7)/2)*(a + b)*(a**2 - 4*a*b + b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**3) - sqrt(2)*e**(sympy.S(7)/2)*(a + b)*(a**2 - 4*a*b + b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**3),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(5)/2)/(a + b*cot(c + d*x))**3,
        variable=x,
        num_steps=16,
        integral=-sqrt(a)*e**(sympy.S(5)/2)*(a**4 + 18*a**2*b**2 - 15*b**4)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(4*b**(sympy.S(3)/2)*d*(a**2 + b**2)**3) + a**2*e**2*sqrt(e*cot(c + d*x))/(2*b*d*(a + b*cot(c + d*x))**2*(a**2 + b**2)) - a*e**2*sqrt(e*cot(c + d*x))*(a**2 + 9*b**2)/(4*b*d*(a + b*cot(c + d*x))*(a**2 + b**2)**2) - sqrt(2)*e**(sympy.S(5)/2)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**3) + sqrt(2)*e**(sympy.S(5)/2)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**3) + sqrt(2)*e**(sympy.S(5)/2)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**3) - sqrt(2)*e**(sympy.S(5)/2)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**3),
    ),
    RubiTestSuiteCase(
        integrand=(e*cot(c + d*x))**(sympy.S(3)/2)/(a + b*cot(c + d*x))**3,
        variable=x,
        num_steps=16,
        integral=-a*e*sqrt(e*cot(c + d*x))/(d*(a + b*cot(c + d*x))**2*(2*a**2 + 2*b**2)) - sqrt(2)*e**(sympy.S(3)/2)*(a - b)*(a**2 + 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**3) + sqrt(2)*e**(sympy.S(3)/2)*(a - b)*(a**2 + 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**3) - sqrt(2)*e**(sympy.S(3)/2)*(a + b)*(a**2 - 4*a*b + b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**3) + sqrt(2)*e**(sympy.S(3)/2)*(a + b)*(a**2 - 4*a*b + b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**3) - e*sqrt(e*cot(c + d*x))*(3*a**2 - 5*b**2)/(4*d*(a + b*cot(c + d*x))*(a**2 + b**2)**2) - e**(sympy.S(3)/2)*(3*a**4 - 26*a**2*b**2 + 3*b**4)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(4*sqrt(a)*sqrt(b)*d*(a**2 + b**2)**3),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(e*cot(c + d*x))/(a + b*cot(c + d*x))**3,
        variable=x,
        num_steps=16,
        integral=b*sqrt(e*cot(c + d*x))/(d*(a + b*cot(c + d*x))**2*(2*a**2 + 2*b**2)) + sqrt(2)*sqrt(e)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**3) - sqrt(2)*sqrt(e)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*(a**2 + b**2)**3) - sqrt(2)*sqrt(e)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**3) + sqrt(2)*sqrt(e)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*(a**2 + b**2)**3) + b*sqrt(e*cot(c + d*x))*(7*a**2 - b**2)/(4*a*d*(a + b*cot(c + d*x))*(a**2 + b**2)**2) + sqrt(b)*sqrt(e)*(15*a**4 - 18*a**2*b**2 - b**4)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(4*a**(sympy.S(3)/2)*d*(a**2 + b**2)**3),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(e*cot(c + d*x))*(a + b*cot(c + d*x))**3),
        variable=x,
        num_steps=16,
        integral=sqrt(2)*(a - b)*(a**2 + 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*sqrt(e)*(a**2 + b**2)**3) - sqrt(2)*(a - b)*(a**2 + 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*sqrt(e)*(a**2 + b**2)**3) + sqrt(2)*(a + b)*(a**2 - 4*a*b + b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*sqrt(e)*(a**2 + b**2)**3) - sqrt(2)*(a + b)*(a**2 - 4*a*b + b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*sqrt(e)*(a**2 + b**2)**3) - b**2*sqrt(e*cot(c + d*x))/(2*a*d*e*(a + b*cot(c + d*x))**2*(a**2 + b**2)) - b**2*sqrt(e*cot(c + d*x))*(11*a**2 + 3*b**2)/(4*a**2*d*e*(a + b*cot(c + d*x))*(a**2 + b**2)**2) - b**(sympy.S(3)/2)*(35*a**4 + 6*a**2*b**2 + 3*b**4)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(4*a**(sympy.S(5)/2)*d*sqrt(e)*(a**2 + b**2)**3),
    ),
    RubiTestSuiteCase(
        integrand=1/((e*cot(c + d*x))**(sympy.S(3)/2)*(a + b*cot(c + d*x))**3),
        variable=x,
        num_steps=17,
        integral=-sqrt(2)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 - sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(3)/2)*(a**2 + b**2)**3) + sqrt(2)*(a - b)*(a**2 + 4*a*b + b**2)*atan(1 + sqrt(2)*sqrt(e*cot(c + d*x))/sqrt(e))/(2*d*e**(sympy.S(3)/2)*(a**2 + b**2)**3) + sqrt(2)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) - sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(3)/2)*(a**2 + b**2)**3) - sqrt(2)*(a + b)*(a**2 - 4*a*b + b**2)*log(sqrt(e)*cot(c + d*x) + sqrt(e) + sqrt(2)*sqrt(e*cot(c + d*x)))/(4*d*e**(sympy.S(3)/2)*(a**2 + b**2)**3) - b**2/(2*a*d*e*sqrt(e*cot(c + d*x))*(a + b*cot(c + d*x))**2*(a**2 + b**2)) - b**2*(13*a**2 + 5*b**2)/(4*a**2*d*e*sqrt(e*cot(c + d*x))*(a + b*cot(c + d*x))*(a**2 + b**2)**2) + (8*a**4 + 31*a**2*b**2 + 15*b**4)/(4*a**3*d*e*sqrt(e*cot(c + d*x))*(a**2 + b**2)**2) + b**(sympy.S(5)/2)*(63*a**4 + 46*a**2*b**2 + 15*b**4)*atan(sqrt(b)*sqrt(e*cot(c + d*x))/(sqrt(a)*sqrt(e)))/(4*a**(sympy.S(7)/2)*d*e**(sympy.S(3)/2)*(a**2 + b**2)**3),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cot(c + d*x))**n,
        variable=x,
        num_steps=5,
        integral=b*(a + b*cot(c + d*x))**(n + 1)*hyper((1, n + 1), (n + 2,), (a + b*cot(c + d*x))/(a + sqrt(-b**2)))/(2*d*sqrt(-b**2)*(a + sqrt(-b**2))*(n + 1)) - b*(a + b*cot(c + d*x))**(n + 1)*hyper((1, n + 1), (n + 2,), (a + b*cot(c + d*x))/(a - sqrt(-b**2)))/(2*d*sqrt(-b**2)*(a - sqrt(-b**2))*(n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(d*tan(e + f*x))**n*(a + b*cot(e + f*x))**m,
        variable=x,
        num_steps=8,
        integral=-(d*tan(e + f*x))**n*(a + b*cot(e + f*x))**m*cot(e + f*x)*appellf1(1 - n, 1, -m, 2 - n, -I*cot(e + f*x), -b*cot(e + f*x)/a)/(2*f*(1 - n)*(1 + b*cot(e + f*x)/a)**m) - (d*tan(e + f*x))**n*(a + b*cot(e + f*x))**m*cot(e + f*x)*appellf1(1 - n, 1, -m, 2 - n, I*cot(e + f*x), -b*cot(e + f*x)/a)/(2*f*(1 - n)*(1 + b*cot(e + f*x)/a)**m),
    ),
    RubiTestSuiteCase(
        integrand=(I*cot(c + d*x) + 1)/sqrt(a + b*cot(c + d*x)),
        variable=x,
        num_steps=3,
        integral=2*I*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a - I*b))/(d*sqrt(a - I*b)),
    ),
    RubiTestSuiteCase(
        integrand=(-I*cot(c + d*x) + 1)/sqrt(a + b*cot(c + d*x)),
        variable=x,
        num_steps=3,
        integral=-2*I*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a + I*b))/(d*sqrt(a + I*b)),
    ),
    RubiTestSuiteCase(
        integrand=(A + B*cot(c + d*x))/(a + b*cot(c + d*x)),
        variable=x,
        num_steps=2,
        integral=x*(A*a + B*b)/(a**2 + b**2) - (A*b - B*a)*log(a*sin(c + d*x) + b*cos(c + d*x))/(d*(a**2 + b**2)),
    ),
    RubiTestSuiteCase(
        integrand=(A + B*cot(c + d*x))/(a + b*cot(c + d*x))**2,
        variable=x,
        num_steps=3,
        integral=x*(A*a**2 - A*b**2 + 2*B*a*b)/(a**2 + b**2)**2 - (2*A*a*b - B*a**2 + B*b**2)*log(a*sin(c + d*x) + b*cos(c + d*x))/(d*(a**2 + b**2)**2) + (A*b - B*a)/(d*(a + b*cot(c + d*x))*(a**2 + b**2)),
    ),
    RubiTestSuiteCase(
        integrand=(A + B*cot(c + d*x))/(a + b*cot(c + d*x))**3,
        variable=x,
        num_steps=4,
        integral=x*(A*a**3 - 3*A*a*b**2 + 3*B*a**2*b - B*b**3)/(a**2 + b**2)**3 - (3*A*a**2*b - A*b**3 - B*a**3 + 3*B*a*b**2)*log(a*sin(c + d*x) + b*cos(c + d*x))/(d*(a**2 + b**2)**3) + (2*A*a*b - B*a**2 + B*b**2)/(d*(a + b*cot(c + d*x))*(a**2 + b**2)**2) + (A*b - B*a)/(d*(a + b*cot(c + d*x))**2*(2*a**2 + 2*b**2)),
    ),
    RubiTestSuiteCase(
        integrand=(A + B*cot(c + d*x))*(a + b*cot(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=10,
        integral=-2*B*(a + b*cot(c + d*x))**(sympy.S(5)/2)/(5*d) + (a - I*b)**(sympy.S(5)/2)*(I*A + B)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a - I*b))/d - (a + I*b)**(sympy.S(5)/2)*(I*A - B)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a + I*b))/d - (a + b*cot(c + d*x))**(sympy.S(3)/2)*(2*A*b + 2*B*a)/(3*d) - sqrt(a + b*cot(c + d*x))*(4*A*a*b + 2*B*a**2 - 2*B*b**2)/d,
    ),
    RubiTestSuiteCase(
        integrand=(A + B*cot(c + d*x))*(a + b*cot(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=9,
        integral=-2*B*(a + b*cot(c + d*x))**(sympy.S(3)/2)/(3*d) + (a - I*b)**(sympy.S(3)/2)*(I*A + B)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a - I*b))/d - (a + I*b)**(sympy.S(3)/2)*(I*A - B)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a + I*b))/d - sqrt(a + b*cot(c + d*x))*(2*A*b + 2*B*a)/d,
    ),
    RubiTestSuiteCase(
        integrand=(A + B*cot(c + d*x))*sqrt(a + b*cot(c + d*x)),
        variable=x,
        num_steps=8,
        integral=-2*B*sqrt(a + b*cot(c + d*x))/d + sqrt(a - I*b)*(I*A + B)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a - I*b))/d - sqrt(a + I*b)*(I*A - B)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a + I*b))/d,
    ),
    RubiTestSuiteCase(
        integrand=(-a + b*cot(c + d*x))*(a + b*cot(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=10,
        integral=-2*b*(a + b*cot(c + d*x))**(sympy.S(5)/2)/(5*d) + 2*b*sqrt(a + b*cot(c + d*x))*(a**2 + b**2)/d - (a - I*b)**(sympy.S(5)/2)*(I*a - b)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a - I*b))/d + (a + I*b)**(sympy.S(5)/2)*(I*a + b)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a + I*b))/d,
    ),
    RubiTestSuiteCase(
        integrand=(-a + b*cot(c + d*x))*(a + b*cot(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=13,
        integral=-2*b*(a + b*cot(c + d*x))**(sympy.S(3)/2)/(3*d) + sqrt(2)*b*(a**2 + b**2)*log(a + b*cot(c + d*x) - sqrt(2)*sqrt(a + b*cot(c + d*x))*sqrt(a + sqrt(a**2 + b**2)) + sqrt(a**2 + b**2))/(4*d*sqrt(a + sqrt(a**2 + b**2))) - sqrt(2)*b*(a**2 + b**2)*log(a + b*cot(c + d*x) + sqrt(2)*sqrt(a + b*cot(c + d*x))*sqrt(a + sqrt(a**2 + b**2)) + sqrt(a**2 + b**2))/(4*d*sqrt(a + sqrt(a**2 + b**2))) + sqrt(2)*b*(a**2 + b**2)*atanh((-sqrt(2)*sqrt(a + b*cot(c + d*x)) + sqrt(a + sqrt(a**2 + b**2)))/sqrt(a - sqrt(a**2 + b**2)))/(2*d*sqrt(a - sqrt(a**2 + b**2))) - sqrt(2)*b*(a**2 + b**2)*atanh((sqrt(2)*sqrt(a + b*cot(c + d*x)) + sqrt(a + sqrt(a**2 + b**2)))/sqrt(a - sqrt(a**2 + b**2)))/(2*d*sqrt(a - sqrt(a**2 + b**2))),
    ),
    RubiTestSuiteCase(
        integrand=(-a + b*cot(c + d*x))*sqrt(a + b*cot(c + d*x)),
        variable=x,
        num_steps=13,
        integral=-2*b*sqrt(a + b*cot(c + d*x))/d - sqrt(2)*b*sqrt(a**2 + b**2)*log(a + b*cot(c + d*x) - sqrt(2)*sqrt(a + b*cot(c + d*x))*sqrt(a + sqrt(a**2 + b**2)) + sqrt(a**2 + b**2))/(4*d*sqrt(a + sqrt(a**2 + b**2))) + sqrt(2)*b*sqrt(a**2 + b**2)*log(a + b*cot(c + d*x) + sqrt(2)*sqrt(a + b*cot(c + d*x))*sqrt(a + sqrt(a**2 + b**2)) + sqrt(a**2 + b**2))/(4*d*sqrt(a + sqrt(a**2 + b**2))) + sqrt(2)*b*sqrt(a**2 + b**2)*atanh((-sqrt(2)*sqrt(a + b*cot(c + d*x)) + sqrt(a + sqrt(a**2 + b**2)))/sqrt(a - sqrt(a**2 + b**2)))/(2*d*sqrt(a - sqrt(a**2 + b**2))) - sqrt(2)*b*sqrt(a**2 + b**2)*atanh((sqrt(2)*sqrt(a + b*cot(c + d*x)) + sqrt(a + sqrt(a**2 + b**2)))/sqrt(a - sqrt(a**2 + b**2)))/(2*d*sqrt(a - sqrt(a**2 + b**2))),
    ),
    RubiTestSuiteCase(
        integrand=(A + B*cot(c + d*x))/sqrt(a + b*cot(c + d*x)),
        variable=x,
        num_steps=7,
        integral=-(I*A - B)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a + I*b))/(d*sqrt(a + I*b)) + (I*A + B)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a - I*b))/(d*sqrt(a - I*b)),
    ),
    RubiTestSuiteCase(
        integrand=(A + B*cot(c + d*x))/(a + b*cot(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=8,
        integral=(2*A*b - 2*B*a)/(d*sqrt(a + b*cot(c + d*x))*(a**2 + b**2)) - (I*A - B)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a + I*b))/(d*(a + I*b)**(sympy.S(3)/2)) + (I*A + B)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a - I*b))/(d*(a - I*b)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(A + B*cot(c + d*x))/(a + b*cot(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=9,
        integral=(4*A*a*b - 2*B*a**2 + 2*B*b**2)/(d*sqrt(a + b*cot(c + d*x))*(a**2 + b**2)**2) + (2*A*b - 2*B*a)/(d*(a + b*cot(c + d*x))**(sympy.S(3)/2)*(3*a**2 + 3*b**2)) - (I*A - B)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a + I*b))/(d*(a + I*b)**(sympy.S(5)/2)) + (I*A + B)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a - I*b))/(d*(a - I*b)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(-a + b*cot(c + d*x))/sqrt(a + b*cot(c + d*x)),
        variable=x,
        num_steps=7,
        integral=(I*a + b)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a + I*b))/(d*sqrt(a + I*b)) - (I*a - b)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a - I*b))/(d*sqrt(a - I*b)),
    ),
    RubiTestSuiteCase(
        integrand=(-a + b*cot(c + d*x))/(a + b*cot(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=8,
        integral=-4*a*b/(d*sqrt(a + b*cot(c + d*x))*(a**2 + b**2)) + (I*a + b)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a + I*b))/(d*(a + I*b)**(sympy.S(3)/2)) - (I*a - b)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a - I*b))/(d*(a - I*b)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(-a + b*cot(c + d*x))/(a + b*cot(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=9,
        integral=-4*a*b/(d*(a + b*cot(c + d*x))**(sympy.S(3)/2)*(3*a**2 + 3*b**2)) - 2*b*(3*a**2 - b**2)/(d*sqrt(a + b*cot(c + d*x))*(a**2 + b**2)**2) + (I*a + b)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a + I*b))/(d*(a + I*b)**(sympy.S(5)/2)) - (I*a - b)*atanh(sqrt(a + b*cot(c + d*x))/sqrt(a - I*b))/(d*(a - I*b)**(sympy.S(5)/2)),
    ),
]
