# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 1 Algebraic functions/1.2 Trinomial products/1.2.1 Quadratic/1.2.1.1 (a+b x+c x^2)^p.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '1 Algebraic functions/1.2 Trinomial products/1.2.1 Quadratic/1.2.1.1 (a+b x+c x^2)^p.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, c, k, n, p = symbols('a b c k n p')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(7)/2),
        variable=x,
        num_steps=6,
        integral=35*b**8*atanh(sqrt(c)*x/sqrt(b*x + c*x**2))/(16384*c**(sympy.S(9)/2)) - 35*b**6*(b + 2*c*x)*sqrt(b*x + c*x**2)/(16384*c**4) + 35*b**4*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(3)/2)/(6144*c**3) - 7*b**2*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(5)/2)/(384*c**2) + (b + 2*c*x)*(b*x + c*x**2)**(sympy.S(7)/2)/(16*c),
    ),
    RubiTestSuiteCase(
        integrand=(4*x**2 + 3*I*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=6,
        integral=(x/8 + 3*I/64)*(4*x**2 + 3*I*x)**(sympy.S(7)/2) + (168*x + 63*I)*(4*x**2 + 3*I*x)**(sympy.S(5)/2)/2048 + (7560*x + 2835*I)*(4*x**2 + 3*I*x)**(sympy.S(3)/2)/131072 + (204120*x + 76545*I)*sqrt(4*x**2 + 3*I*x)/4194304 - 229635*I*asin(8*I*x/3 - 1)/16777216,
    ),
    RubiTestSuiteCase(
        integrand=(4*x**2 + 3*I*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=(x/6 + I/16)*(4*x**2 + 3*I*x)**(sympy.S(5)/2) + (120*x + 45*I)*(4*x**2 + 3*I*x)**(sympy.S(3)/2)/1024 + (3240*x + 1215*I)*sqrt(4*x**2 + 3*I*x)/32768 - 3645*I*asin(8*I*x/3 - 1)/131072,
    ),
    RubiTestSuiteCase(
        integrand=(4*x**2 + 3*I*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=(x/4 + 3*I/32)*(4*x**2 + 3*I*x)**(sympy.S(3)/2) + (216*x + 81*I)*sqrt(4*x**2 + 3*I*x)/1024 - 243*I*asin(8*I*x/3 - 1)/4096,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(4*x**2 + 3*I*x),
        variable=x,
        num_steps=3,
        integral=(x/2 + 3*I/16)*sqrt(4*x**2 + 3*I*x) - 9*I*asin(8*I*x/3 - 1)/64,
    ),
    RubiTestSuiteCase(
        integrand=(-4*x**2 + 3*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=6,
        integral=-(sympy.S(3)/64 - x/8)*(-4*x**2 + 3*x)**(sympy.S(7)/2) - (63 - 168*x)*(-4*x**2 + 3*x)**(sympy.S(5)/2)/2048 - (2835 - 7560*x)*(-4*x**2 + 3*x)**(sympy.S(3)/2)/131072 - (76545 - 204120*x)*sqrt(-4*x**2 + 3*x)/4194304 + 229635*asin(8*x/3 - 1)/16777216,
    ),
    RubiTestSuiteCase(
        integrand=(-4*x**2 + 3*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=-(sympy.S(1)/16 - x/6)*(-4*x**2 + 3*x)**(sympy.S(5)/2) - (45 - 120*x)*(-4*x**2 + 3*x)**(sympy.S(3)/2)/1024 - (1215 - 3240*x)*sqrt(-4*x**2 + 3*x)/32768 + 3645*asin(8*x/3 - 1)/131072,
    ),
    RubiTestSuiteCase(
        integrand=(-4*x**2 + 3*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=-(sympy.S(3)/32 - x/4)*(-4*x**2 + 3*x)**(sympy.S(3)/2) - (81 - 216*x)*sqrt(-4*x**2 + 3*x)/1024 + 243*asin(8*x/3 - 1)/4096,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-4*x**2 + 3*x),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(-3)/16)*sqrt(-4*x**2 + 3*x) + 9*asin(8*x/3 - 1)/64,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-x**2 + 6*x),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(-3)/2)*sqrt(-x**2 + 6*x) + 9*asin(x/3 - 1)/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-9*x**2 + 5*x),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(-5)/36)*sqrt(-9*x**2 + 5*x) + 25*asin(18*x/5 - 1)/216,
    ),
    RubiTestSuiteCase(
        integrand=(-x**2 + x)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=-(sympy.S(1)/8 - x/4)*(-x**2 + x)**(sympy.S(3)/2) + (3*x/32 + sympy.S(-3)/64)*sqrt(-x**2 + x) + 3*asin(2*x - 1)/128,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x**2 + 4*x),
        variable=x,
        num_steps=3,
        integral=(x/2 + 1)*sqrt(x**2 + 4*x) - 4*atanh(x/sqrt(x**2 + 4*x)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x**2 - 8*x),
        variable=x,
        num_steps=3,
        integral=(x/2 - 2)*sqrt(x**2 - 8*x) - 16*atanh(x/sqrt(x**2 - 8*x)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x**2 - x),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(-1)/4)*sqrt(x**2 - x) - atanh(x/sqrt(x**2 - x))/4,
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(-7)/2),
        variable=x,
        num_steps=3,
        integral=-(2*b + 4*c*x)/(5*b**2*(b*x + c*x**2)**(sympy.S(5)/2)) + 32*c*(b + 2*c*x)/(15*b**4*(b*x + c*x**2)**(sympy.S(3)/2)) - 256*c**2*(b + 2*c*x)/(15*b**6*sqrt(b*x + c*x**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(4*x**2 + 3*I*x),
        variable=x,
        num_steps=2,
        integral=-I*asin(8*I*x/3 - 1)/2,
    ),
    RubiTestSuiteCase(
        integrand=(4*x**2 + 3*I*x)**(sympy.S(-3)/2),
        variable=x,
        num_steps=1,
        integral=(16*x + 6*I)/(9*sqrt(4*x**2 + 3*I*x)),
    ),
    RubiTestSuiteCase(
        integrand=(4*x**2 + 3*I*x)**(sympy.S(-5)/2),
        variable=x,
        num_steps=2,
        integral=(16*x + 6*I)/(27*(4*x**2 + 3*I*x)**(sympy.S(3)/2)) + (512*x + 192*I)/(243*sqrt(4*x**2 + 3*I*x)),
    ),
    RubiTestSuiteCase(
        integrand=(4*x**2 + 3*I*x)**(sympy.S(-7)/2),
        variable=x,
        num_steps=3,
        integral=(16*x + 6*I)/(45*(4*x**2 + 3*I*x)**(sympy.S(5)/2)) + (1024*x + 384*I)/(1215*(4*x**2 + 3*I*x)**(sympy.S(3)/2)) + (32768*x + 12288*I)/(10935*sqrt(4*x**2 + 3*I*x)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-4*x**2 + 3*x),
        variable=x,
        num_steps=2,
        integral=asin(8*x/3 - 1)/2,
    ),
    RubiTestSuiteCase(
        integrand=(-4*x**2 + 3*x)**(sympy.S(-3)/2),
        variable=x,
        num_steps=1,
        integral=-(6 - 16*x)/(9*sqrt(-4*x**2 + 3*x)),
    ),
    RubiTestSuiteCase(
        integrand=(-4*x**2 + 3*x)**(sympy.S(-5)/2),
        variable=x,
        num_steps=2,
        integral=-(6 - 16*x)/(27*(-4*x**2 + 3*x)**(sympy.S(3)/2)) - (192 - 512*x)/(243*sqrt(-4*x**2 + 3*x)),
    ),
    RubiTestSuiteCase(
        integrand=(-4*x**2 + 3*x)**(sympy.S(-7)/2),
        variable=x,
        num_steps=3,
        integral=-(6 - 16*x)/(45*(-4*x**2 + 3*x)**(sympy.S(5)/2)) - (384 - 1024*x)/(1215*(-4*x**2 + 3*x)**(sympy.S(3)/2)) - (12288 - 32768*x)/(10935*sqrt(-4*x**2 + 3*x)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-b**2*x**2 + b*x),
        variable=x,
        num_steps=2,
        integral=asin(2*b*x - 1)/b,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(b**2*x**2 + b*x),
        variable=x,
        num_steps=2,
        integral=2*atanh(b*x/sqrt(b**2*x**2 + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-x**2 + 6*x),
        variable=x,
        num_steps=2,
        integral=asin(x/3 - 1),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(x**2 + 4*x),
        variable=x,
        num_steps=2,
        integral=2*atanh(x/sqrt(x**2 + 4*x)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(x**2 - 2*x),
        variable=x,
        num_steps=2,
        integral=2*atanh(x/sqrt(x**2 - 2*x)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(4)/3),
        variable=x,
        num_steps=6,
        integral=2**(sympy.S(1)/3)*3**(sympy.S(3)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*sqrt(2 - sqrt(3))*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*(b*x + c*x**2)**(sympy.S(4)/3)*elliptic_f(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(55*c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(4)/3)*(b + 2*c*x)) + 3*(-c*x*(b + c*x)/b**2)**(sympy.S(4)/3)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(4)/3)/(22*c*(-c*(b*x + c*x**2)/b**2)**(sympy.S(4)/3)) + 3*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(4)/3)/(55*c*(-c*(b*x + c*x**2)/b**2)**(sympy.S(4)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(1)/3),
        variable=x,
        num_steps=5,
        integral=2**(sympy.S(1)/3)*3**(sympy.S(3)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*sqrt(2 - sqrt(3))*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*(b*x + c*x**2)**(sympy.S(1)/3)*elliptic_f(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(10*c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(1)/3)*(b + 2*c*x)) + 3*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(1)/3)/(10*c*(-c*(b*x + c*x**2)/b**2)**(sympy.S(1)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(-2)/3),
        variable=x,
        num_steps=4,
        integral=2**(sympy.S(1)/3)*3**(sympy.S(3)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(2)/3)*sqrt(2 - sqrt(3))*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*elliptic_f(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(2)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(-5)/3),
        variable=x,
        num_steps=5,
        integral=2**(sympy.S(1)/3)*3**(sympy.S(3)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(5)/3)*sqrt(2 - sqrt(3))*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*elliptic_f(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(5)/3)) + (-c*(b*x + c*x**2)/b**2)**(sympy.S(5)/3)*(3*b + 6*c*x)/(2*c*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3)*(b*x + c*x**2)**(sympy.S(5)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(-8)/3),
        variable=x,
        num_steps=6,
        integral=14*2**(sympy.S(1)/3)*3**(sympy.S(3)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(8)/3)*sqrt(2 - sqrt(3))*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*elliptic_f(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(5*c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(8)/3)) + (-c*(b*x + c*x**2)/b**2)**(sympy.S(8)/3)*(21*b + 42*c*x)/(5*c*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3)*(b*x + c*x**2)**(sympy.S(8)/3)) + (-c*(b*x + c*x**2)/b**2)**(sympy.S(8)/3)*(3*b + 6*c*x)/(5*c*(-c*x*(b + c*x)/b**2)**(sympy.S(5)/3)*(b*x + c*x**2)**(sympy.S(8)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(5)/3),
        variable=x,
        num_steps=8,
        integral=-15*2**(sympy.S(2)/3)*3**(sympy.S(1)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*sqrt(sqrt(3) + 2)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*(b*x + c*x**2)**(sympy.S(5)/3)*elliptic_e(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(728*c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(5)/3)*(b + 2*c*x)) + 5*2**(sympy.S(1)/6)*3**(sympy.S(3)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*(b*x + c*x**2)**(sympy.S(5)/3)*elliptic_f(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(182*c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(5)/3)*(b + 2*c*x)) + 3*(-c*x*(b + c*x)/b**2)**(sympy.S(5)/3)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(5)/3)/(26*c*(-c*(b*x + c*x**2)/b**2)**(sympy.S(5)/3)) + 15*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(5)/3)/(364*c*(-c*(b*x + c*x**2)/b**2)**(sympy.S(5)/3)) - 2**(sympy.S(2)/3)*(15*b + 30*c*x)*(b*x + c*x**2)**(sympy.S(5)/3)/(364*c*(-c*(b*x + c*x**2)/b**2)**(sympy.S(5)/3)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(2)/3),
        variable=x,
        num_steps=7,
        integral=-3*2**(sympy.S(2)/3)*3**(sympy.S(1)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*sqrt(sqrt(3) + 2)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*(b*x + c*x**2)**(sympy.S(2)/3)*elliptic_e(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(28*c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(2)/3)*(b + 2*c*x)) + 2**(sympy.S(1)/6)*3**(sympy.S(3)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*(b*x + c*x**2)**(sympy.S(2)/3)*elliptic_f(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(7*c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(2)/3)*(b + 2*c*x)) + 3*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(2)/3)/(14*c*(-c*(b*x + c*x**2)/b**2)**(sympy.S(2)/3)) - 2**(sympy.S(2)/3)*(3*b + 6*c*x)*(b*x + c*x**2)**(sympy.S(2)/3)/(14*c*(-c*(b*x + c*x**2)/b**2)**(sympy.S(2)/3)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(-1)/3),
        variable=x,
        num_steps=6,
        integral=-3*2**(sympy.S(2)/3)*3**(sympy.S(1)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(1)/3)*sqrt(sqrt(3) + 2)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*elliptic_e(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(4*c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(1)/3)) + 2**(sympy.S(1)/6)*3**(sympy.S(3)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(1)/3)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*elliptic_f(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(1)/3)) - 2**(sympy.S(2)/3)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(1)/3)*(3*b + 6*c*x)/(2*c*(b*x + c*x**2)**(sympy.S(1)/3)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(-4)/3),
        variable=x,
        num_steps=7,
        integral=3*2**(sympy.S(2)/3)*3**(sympy.S(1)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(4)/3)*sqrt(sqrt(3) + 2)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*elliptic_e(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(2*c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(4)/3)) - 2*2**(sympy.S(1)/6)*3**(sympy.S(3)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(4)/3)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*elliptic_f(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(4)/3)) + 3*2**(sympy.S(2)/3)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(4)/3)*(b + 2*c*x)/(c*(b*x + c*x**2)**(sympy.S(4)/3)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)) + (-c*(b*x + c*x**2)/b**2)**(sympy.S(4)/3)*(3*b + 6*c*x)/(c*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3)*(b*x + c*x**2)**(sympy.S(4)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(-7)/3),
        variable=x,
        num_steps=8,
        integral=15*2**(sympy.S(2)/3)*3**(sympy.S(1)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(7)/3)*sqrt(sqrt(3) + 2)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*elliptic_e(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(4*c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(7)/3)) - 5*2**(sympy.S(1)/6)*3**(sympy.S(3)/4)*b**2*sqrt((2*2**(sympy.S(1)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(2)/3) + 2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(7)/3)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)*elliptic_f(asin((-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1 + sqrt(3))/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)), -7 + 4*sqrt(3))/(c*sqrt(-(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) + 1)/(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)**2)*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(7)/3)) + 2**(sympy.S(2)/3)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(7)/3)*(15*b + 30*c*x)/(2*c*(b*x + c*x**2)**(sympy.S(7)/3)*(-2**(sympy.S(2)/3)*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3) - sqrt(3) + 1)) + (-c*(b*x + c*x**2)/b**2)**(sympy.S(7)/3)*(15*b + 30*c*x)/(2*c*(-c*x*(b + c*x)/b**2)**(sympy.S(1)/3)*(b*x + c*x**2)**(sympy.S(7)/3)) + (-c*(b*x + c*x**2)/b**2)**(sympy.S(7)/3)*(3*b + 6*c*x)/(4*c*(-c*x*(b + c*x)/b**2)**(sympy.S(4)/3)*(b*x + c*x**2)**(sympy.S(7)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(5)/4),
        variable=x,
        num_steps=5,
        integral=5*sqrt(2)*b**5*(-c*(b*x + c*x**2)/b**2)**(sympy.S(3)/4)*elliptic_f(asin(1 + 2*c*x/b)/2, 2)/(168*c**3*(b*x + c*x**2)**(sympy.S(3)/4)) - 5*b**2*(b + 2*c*x)*(b*x + c*x**2)**(sympy.S(1)/4)/(84*c**2) + (b + 2*c*x)*(b*x + c*x**2)**(sympy.S(5)/4)/(7*c),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(3)/4),
        variable=x,
        num_steps=4,
        integral=-3*sqrt(2)*b**3*(-c*(b*x + c*x**2)/b**2)**(sympy.S(1)/4)*elliptic_e(asin(1 + 2*c*x/b)/2, 2)/(20*c**2*(b*x + c*x**2)**(sympy.S(1)/4)) + (b + 2*c*x)*(b*x + c*x**2)**(sympy.S(3)/4)/(5*c),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(1)/4),
        variable=x,
        num_steps=4,
        integral=-sqrt(2)*b**3*(-c*(b*x + c*x**2)/b**2)**(sympy.S(3)/4)*elliptic_f(asin(1 + 2*c*x/b)/2, 2)/(6*c**2*(b*x + c*x**2)**(sympy.S(3)/4)) + (b + 2*c*x)*(b*x + c*x**2)**(sympy.S(1)/4)/(3*c),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(-1)/4),
        variable=x,
        num_steps=3,
        integral=sqrt(2)*b*(-c*(b*x + c*x**2)/b**2)**(sympy.S(1)/4)*elliptic_e(asin(1 + 2*c*x/b)/2, 2)/(c*(b*x + c*x**2)**(sympy.S(1)/4)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(-3)/4),
        variable=x,
        num_steps=3,
        integral=2*sqrt(2)*b*(-c*(b*x + c*x**2)/b**2)**(sympy.S(3)/4)*elliptic_f(asin(1 + 2*c*x/b)/2, 2)/(c*(b*x + c*x**2)**(sympy.S(3)/4)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(-5)/4),
        variable=x,
        num_steps=4,
        integral=4*sqrt(2)*(-c*(b*x + c*x**2)/b**2)**(sympy.S(1)/4)*elliptic_e(asin(1 + 2*c*x/b)/2, 2)/(b*(b*x + c*x**2)**(sympy.S(1)/4)) - (4*b + 8*c*x)/(b**2*(b*x + c*x**2)**(sympy.S(1)/4)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(-9)/4),
        variable=x,
        num_steps=5,
        integral=-(4*b + 8*c*x)/(5*b**2*(b*x + c*x**2)**(sympy.S(5)/4)) - 48*sqrt(2)*c*(-c*(b*x + c*x**2)/b**2)**(sympy.S(1)/4)*elliptic_e(asin(1 + 2*c*x/b)/2, 2)/(5*b**3*(b*x + c*x**2)**(sympy.S(1)/4)) + 48*c*(b + 2*c*x)/(5*b**4*(b*x + c*x**2)**(sympy.S(1)/4)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**(sympy.S(-13)/4),
        variable=x,
        num_steps=6,
        integral=-(4*b + 8*c*x)/(9*b**2*(b*x + c*x**2)**(sympy.S(9)/4)) + 112*c*(b + 2*c*x)/(45*b**4*(b*x + c*x**2)**(sympy.S(5)/4)) + 448*sqrt(2)*c**2*(-c*(b*x + c*x**2)/b**2)**(sympy.S(1)/4)*elliptic_e(asin(1 + 2*c*x/b)/2, 2)/(15*b**5*(b*x + c*x**2)**(sympy.S(1)/4)) - 448*c**2*(b + 2*c*x)/(15*b**6*(b*x + c*x**2)**(sympy.S(1)/4)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2)**p,
        variable=x,
        num_steps=1,
        integral=-(-c*x/b)**(-p - 1)*(b*x + c*x**2)**(p + 1)*hyper((-p, p + 1), (p + 2,), (b + c*x)/b)/(b*(p + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(a + c*x**2)**4,
        variable=x,
        num_steps=2,
        integral=a**4*x + 4*a**3*c*x**3/3 + 6*a**2*c**2*x**5/5 + 4*a*c**3*x**7/7 + c**4*x**9/9,
    ),
    RubiTestSuiteCase(
        integrand=(a + c*x**2)**3,
        variable=x,
        num_steps=2,
        integral=a**3*x + a**2*c*x**3 + 3*a*c**2*x**5/5 + c**3*x**7/7,
    ),
    RubiTestSuiteCase(
        integrand=(a + c*x**2)**2,
        variable=x,
        num_steps=2,
        integral=a**2*x + 2*a*c*x**3/3 + c**2*x**5/5,
    ),
    RubiTestSuiteCase(
        integrand=a + c*x**2,
        variable=x,
        num_steps=1,
        integral=a*x + c*x**3/3,
    ),
    RubiTestSuiteCase(
        integrand=1/(a + c*x**2),
        variable=x,
        num_steps=1,
        integral=atan(sqrt(c)*x/sqrt(a))/(sqrt(a)*sqrt(c)),
    ),
    RubiTestSuiteCase(
        integrand=(a + c*x**2)**(-2),
        variable=x,
        num_steps=2,
        integral=x/(2*a*(a + c*x**2)) + atan(sqrt(c)*x/sqrt(a))/(2*a**(sympy.S(3)/2)*sqrt(c)),
    ),
    RubiTestSuiteCase(
        integrand=(a + c*x**2)**(-3),
        variable=x,
        num_steps=3,
        integral=x/(4*a*(a + c*x**2)**2) + 3*x/(8*a**2*(a + c*x**2)) + 3*atan(sqrt(c)*x/sqrt(a))/(8*a**(sympy.S(5)/2)*sqrt(c)),
    ),
    RubiTestSuiteCase(
        integrand=(a + c*x**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=5*a**3*atanh(sqrt(c)*x/sqrt(a + c*x**2))/(16*sqrt(c)) + 5*a**2*x*sqrt(a + c*x**2)/16 + 5*a*x*(a + c*x**2)**(sympy.S(3)/2)/24 + x*(a + c*x**2)**(sympy.S(5)/2)/6,
    ),
    RubiTestSuiteCase(
        integrand=(a + c*x**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=3*a**2*atanh(sqrt(c)*x/sqrt(a + c*x**2))/(8*sqrt(c)) + 3*a*x*sqrt(a + c*x**2)/8 + x*(a + c*x**2)**(sympy.S(3)/2)/4,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + c*x**2),
        variable=x,
        num_steps=3,
        integral=a*atanh(sqrt(c)*x/sqrt(a + c*x**2))/(2*sqrt(c)) + x*sqrt(a + c*x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a + c*x**2),
        variable=x,
        num_steps=2,
        integral=atanh(sqrt(c)*x/sqrt(a + c*x**2))/sqrt(c),
    ),
    RubiTestSuiteCase(
        integrand=(a + c*x**2)**(sympy.S(-3)/2),
        variable=x,
        num_steps=1,
        integral=x/(a*sqrt(a + c*x**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + c*x**2)**(sympy.S(-5)/2),
        variable=x,
        num_steps=2,
        integral=x/(3*a*(a + c*x**2)**(sympy.S(3)/2)) + 2*x/(3*a**2*sqrt(a + c*x**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + c*x**2)**(sympy.S(-7)/2),
        variable=x,
        num_steps=3,
        integral=x/(5*a*(a + c*x**2)**(sympy.S(5)/2)) + 4*x/(15*a**2*(a + c*x**2)**(sympy.S(3)/2)) + 8*x/(15*a**3*sqrt(a + c*x**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + c*x**2)**(sympy.S(-9)/2),
        variable=x,
        num_steps=4,
        integral=x/(7*a*(a + c*x**2)**(sympy.S(7)/2)) + 6*x/(35*a**2*(a + c*x**2)**(sympy.S(5)/2)) + 8*x/(35*a**3*(a + c*x**2)**(sympy.S(3)/2)) + 16*x/(35*a**4*sqrt(a + c*x**2)),
    ),
    RubiTestSuiteCase(
        integrand=(9*x**2 + 12*x + 4)**(sympy.S(3)/2),
        variable=x,
        num_steps=1,
        integral=(x/4 + sympy.S(1)/6)*(9*x**2 + 12*x + 4)**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(9*x**2 + 12*x + 4),
        variable=x,
        num_steps=1,
        integral=(x/2 + sympy.S(1)/3)*sqrt(9*x**2 + 12*x + 4),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(9*x**2 + 12*x + 4),
        variable=x,
        num_steps=2,
        integral=(3*x + 2)*log(3*x + 2)/(3*sqrt(9*x**2 + 12*x + 4)),
    ),
    RubiTestSuiteCase(
        integrand=(9*x**2 + 12*x + 4)**(sympy.S(-3)/2),
        variable=x,
        num_steps=1,
        integral=-1/((18*x + 12)*sqrt(9*x**2 + 12*x + 4)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(9*x**2 - 12*x + 4),
        variable=x,
        num_steps=1,
        integral=(x/2 + sympy.S(-1)/3)*sqrt(9*x**2 - 12*x + 4),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(9*x**2 - 12*x + 4),
        variable=x,
        num_steps=2,
        integral=-(2 - 3*x)*log(2 - 3*x)/(3*sqrt(9*x**2 - 12*x + 4)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-9*x**2 + 12*x - 4),
        variable=x,
        num_steps=1,
        integral=(x/2 + sympy.S(-1)/3)*sqrt(-9*x**2 + 12*x - 4),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-9*x**2 + 12*x - 4),
        variable=x,
        num_steps=2,
        integral=-(2 - 3*x)*log(2 - 3*x)/(3*sqrt(-9*x**2 + 12*x - 4)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-9*x**2 - 12*x - 4),
        variable=x,
        num_steps=1,
        integral=(x/2 + sympy.S(1)/3)*sqrt(-9*x**2 - 12*x - 4),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-9*x**2 - 12*x - 4),
        variable=x,
        num_steps=2,
        integral=(3*x + 2)*log(3*x + 2)/(3*sqrt(-9*x**2 - 12*x - 4)),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2 + (b**2 - 1)/(4*c))**5,
        variable=x,
        num_steps=3,
        integral=-(-b - 2*c*x + 1)**11/(22528*c**6) + (-b - 2*c*x + 1)**10/(2048*c**6) - 5*(-b - 2*c*x + 1)**9/(2304*c**6) + 5*(-b - 2*c*x + 1)**8/(1024*c**6) - 5*(-b - 2*c*x + 1)**7/(896*c**6) + (-b - 2*c*x + 1)**6/(384*c**6),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2 + (b**2 - 4)/(4*c))**5,
        variable=x,
        num_steps=3,
        integral=-(-b - 2*c*x + 2)**11/(22528*c**6) + (-b - 2*c*x + 2)**10/(1024*c**6) - 5*(-b - 2*c*x + 2)**9/(576*c**6) + 5*(-b - 2*c*x + 2)**8/(128*c**6) - 5*(-b - 2*c*x + 2)**7/(56*c**6) + (-b - 2*c*x + 2)**6/(12*c**6),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2 + (b**2 - 9)/(4*c))**5,
        variable=x,
        num_steps=3,
        integral=-(-b - 2*c*x + 3)**11/(22528*c**6) + 3*(-b - 2*c*x + 3)**10/(2048*c**6) - 5*(-b - 2*c*x + 3)**9/(256*c**6) + 135*(-b - 2*c*x + 3)**8/(1024*c**6) - 405*(-b - 2*c*x + 3)**7/(896*c**6) + 81*(-b - 2*c*x + 3)**6/(128*c**6),
    ),
    RubiTestSuiteCase(
        integrand=(b*x + c*x**2 + (b**2 - 16)/(4*c))**5,
        variable=x,
        num_steps=3,
        integral=-(-b - 2*c*x + 4)**11/(22528*c**6) + (-b - 2*c*x + 4)**10/(512*c**6) - 5*(-b - 2*c*x + 4)**9/(144*c**6) + 5*(-b - 2*c*x + 4)**8/(16*c**6) - 10*(-b - 2*c*x + 4)**7/(7*c**6) + 8*(-b - 2*c*x + 4)**6/(3*c**6),
    ),
    RubiTestSuiteCase(
        integrand=1/(3*x**2 + 4*x + 2),
        variable=x,
        num_steps=2,
        integral=sqrt(2)*atan(sqrt(2)*(3*x + 2)/2)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2 - 2*sqrt(3)*x + 4),
        variable=x,
        num_steps=2,
        integral=atan(x - sqrt(3)),
    ),
    RubiTestSuiteCase(
        integrand=1/(-3*x**2 + 4*x + 2),
        variable=x,
        num_steps=2,
        integral=-sqrt(10)*atanh(sqrt(10)*(2 - 3*x)/10)/10,
    ),
    RubiTestSuiteCase(
        integrand=1/(3*x**2 + 5*x + 2),
        variable=x,
        num_steps=3,
        integral=-log(x + 1) + log(3*x + 2),
    ),
    RubiTestSuiteCase(
        integrand=1/(-3*x**2 + 5*x + 2),
        variable=x,
        num_steps=3,
        integral=-log(2 - x)/7 + log(3*x + 1)/7,
    ),
    RubiTestSuiteCase(
        integrand=1/(2*x**2 + pi*x + 1),
        variable=x,
        num_steps=2,
        integral=-2*atanh((4*x + pi)/sqrt(-8 + pi**2))/sqrt(-8 + pi**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(-2*x**2 + pi*x + 1),
        variable=x,
        num_steps=2,
        integral=-2*atanh((pi - 4*x)/sqrt(8 + pi**2))/sqrt(8 + pi**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(3*x**2 + pi*x + 1),
        variable=x,
        num_steps=2,
        integral=2*atan((6*x + pi)/sqrt(12 - pi**2))/sqrt(12 - pi**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(-3*x**2 + pi*x + 1),
        variable=x,
        num_steps=2,
        integral=-2*atanh((pi - 6*x)/sqrt(pi**2 + 12))/sqrt(pi**2 + 12),
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*x**2 + c*x),
        variable=x,
        num_steps=2,
        integral=2*atan((2*b*x + c)/sqrt(4*a*b - c**2))/sqrt(4*a*b - c**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(2*a*x + b*x**2 + b),
        variable=x,
        num_steps=2,
        integral=-atanh((a + b*x)/sqrt(a**2 - b**2))/sqrt(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(2*a*x - b*x**2 + b),
        variable=x,
        num_steps=2,
        integral=-atanh((a - b*x)/sqrt(a**2 + b**2))/sqrt(a**2 + b**2),
    ),
    RubiTestSuiteCase(
        integrand=(3*x**2 + 4*x + 2)**(-2),
        variable=x,
        num_steps=3,
        integral=(3*x + 2)/(12*x**2 + 16*x + 8) + 3*sqrt(2)*atan(sqrt(2)*(3*x + 2)/2)/8,
    ),
    RubiTestSuiteCase(
        integrand=(-3*x**2 + 4*x + 2)**(-2),
        variable=x,
        num_steps=3,
        integral=-(2 - 3*x)/(-60*x**2 + 80*x + 40) - 3*sqrt(10)*atanh(sqrt(10)*(2 - 3*x)/10)/200,
    ),
    RubiTestSuiteCase(
        integrand=(3*x**2 + 5*x + 2)**(-2),
        variable=x,
        num_steps=4,
        integral=-(6*x + 5)/(3*x**2 + 5*x + 2) + 6*log(x + 1) - 6*log(3*x + 2),
    ),
    RubiTestSuiteCase(
        integrand=(-3*x**2 + 5*x + 2)**(-2),
        variable=x,
        num_steps=4,
        integral=-(5 - 6*x)/(-147*x**2 + 245*x + 98) - 6*log(2 - x)/343 + 6*log(3*x + 1)/343,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*x**2 + c*x)**(-2),
        variable=x,
        num_steps=3,
        integral=4*b*atan((2*b*x + c)/sqrt(4*a*b - c**2))/(4*a*b - c**2)**(sympy.S(3)/2) + (2*b*x + c)/((4*a*b - c**2)*(a + b*x**2 + c*x)),
    ),
    RubiTestSuiteCase(
        integrand=(2*a*x + b*x**2 + b)**(-2),
        variable=x,
        num_steps=3,
        integral=b*atanh((a + b*x)/sqrt(a**2 - b**2))/(2*(a**2 - b**2)**(sympy.S(3)/2)) - (a + b*x)/((2*a**2 - 2*b**2)*(2*a*x + b*x**2 + b)),
    ),
    RubiTestSuiteCase(
        integrand=(2*a*x - b*x**2 + b)**(-2),
        variable=x,
        num_steps=3,
        integral=-b*atanh((a - b*x)/sqrt(a**2 + b**2))/(2*(a**2 + b**2)**(sympy.S(3)/2)) - (a - b*x)/((2*a**2 + 2*b**2)*(2*a*x - b*x**2 + b)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2 - 2*x*(a/b)**(1/n)*cos((-2*pi*k + pi)/n) + (a/b)**(2/n)),
        variable=x,
        num_steps=2,
        integral=atan(x*csc((-2*pi*k + pi)/n)/(a/b)**(1/n) - cot((-2*pi*k + pi)/n))*csc((-2*pi*k + pi)/n)/(a/b)**(1/n),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2 + 2*x*cos(sympy.S(1)/7) + 1),
        variable=x,
        num_steps=2,
        integral=atan((x + cos(sympy.S(1)/7))*csc(sympy.S(1)/7))*csc(sympy.S(1)/7),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2 + 2*x*cos(pi/7) + 1),
        variable=x,
        num_steps=2,
        integral=atan(x*csc(pi/7) + cot(pi/7))*csc(pi/7),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(9*x**2 - 6*x + 5),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(-1)/6)*sqrt(9*x**2 - 6*x + 5) + 2*asinh(3*x/2 + sympy.S(-1)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-4*x**2 - 4*x + 3),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(1)/4)*sqrt(-4*x**2 - 4*x + 3) + asin(x + sympy.S.Half),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(9*x**2 + 6*x - 8),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(1)/6)*sqrt(9*x**2 + 6*x - 8) - 3*atanh((3*x + 1)/sqrt(9*x**2 + 6*x - 8))/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(3*x**2 + 4*x + 2),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(1)/3)*sqrt(3*x**2 + 4*x + 2) + sqrt(3)*asinh(sqrt(2)*(3*x + 2)/2)/9,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-3*x**2 + 4*x + 2),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(-1)/3)*sqrt(-3*x**2 + 4*x + 2) - 5*sqrt(3)*asin(sqrt(10)*(2 - 3*x)/10)/9,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(3*x**2 + 5*x + 2),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(5)/12)*sqrt(3*x**2 + 5*x + 2) - sqrt(3)*atanh(sqrt(3)*(6*x + 5)/(6*sqrt(3*x**2 + 5*x + 2)))/72,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-3*x**2 + 5*x + 2),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(-5)/12)*sqrt(-3*x**2 + 5*x + 2) + 49*sqrt(3)*asin(6*x/7 + sympy.S(-5)/7)/72,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(3*x**2 + 4*x - 2),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(1)/3)*sqrt(3*x**2 + 4*x - 2) - 5*sqrt(3)*atanh(sqrt(3)*(3*x + 2)/(3*sqrt(3*x**2 + 4*x - 2)))/9,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-3*x**2 + 4*x - 2),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(-1)/3)*sqrt(-3*x**2 + 4*x - 2) + sqrt(3)*atan(sqrt(3)*(2 - 3*x)/(3*sqrt(-3*x**2 + 4*x - 2)))/9,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(3*x**2 + 5*x - 2),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(5)/12)*sqrt(3*x**2 + 5*x - 2) - 49*sqrt(3)*atanh(sqrt(3)*(6*x + 5)/(6*sqrt(3*x**2 + 5*x - 2)))/72,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-3*x**2 + 5*x - 2),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(-5)/12)*sqrt(-3*x**2 + 5*x - 2) + sqrt(3)*asin(6*x - 5)/72,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(9*x**2 - 6*x + 5),
        variable=x,
        num_steps=2,
        integral=asinh(3*x/2 + sympy.S(-1)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-4*x**2 - 4*x + 3),
        variable=x,
        num_steps=2,
        integral=asin(x + sympy.S.Half)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(9*x**2 + 6*x - 8),
        variable=x,
        num_steps=2,
        integral=atanh((3*x + 1)/sqrt(9*x**2 + 6*x - 8))/3,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(3*x**2 + 4*x + 2),
        variable=x,
        num_steps=2,
        integral=sqrt(3)*asinh(sqrt(2)*(3*x + 2)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-3*x**2 + 4*x + 2),
        variable=x,
        num_steps=2,
        integral=-sqrt(3)*asin(sqrt(10)*(2 - 3*x)/10)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(3*x**2 + 5*x + 2),
        variable=x,
        num_steps=2,
        integral=sqrt(3)*atanh(sqrt(3)*(6*x + 5)/(6*sqrt(3*x**2 + 5*x + 2)))/3,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-3*x**2 + 5*x + 2),
        variable=x,
        num_steps=2,
        integral=sqrt(3)*asin(6*x/7 + sympy.S(-5)/7)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(3*x**2 + 4*x - 2),
        variable=x,
        num_steps=2,
        integral=sqrt(3)*atanh(sqrt(3)*(3*x + 2)/(3*sqrt(3*x**2 + 4*x - 2)))/3,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-3*x**2 + 4*x - 2),
        variable=x,
        num_steps=2,
        integral=-sqrt(3)*atan(sqrt(3)*(2 - 3*x)/(3*sqrt(-3*x**2 + 4*x - 2)))/3,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(3*x**2 + 5*x - 2),
        variable=x,
        num_steps=2,
        integral=sqrt(3)*atanh(sqrt(3)*(6*x + 5)/(6*sqrt(3*x**2 + 5*x - 2)))/3,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-3*x**2 + 5*x - 2),
        variable=x,
        num_steps=2,
        integral=sqrt(3)*asin(6*x - 5)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(b*x + c*x**2 + (b**2 + 4*c)/(4*c)),
        variable=x,
        num_steps=2,
        integral=asinh((b + 2*c*x)/(2*sqrt(c)))/sqrt(c),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(b*x - c*x**2 + (-b**2 + 4*c)/(4*c)),
        variable=x,
        num_steps=2,
        integral=-asin((b - 2*c*x)/(2*sqrt(c)))/sqrt(c),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(b*x - c*x**2 + (-b**2 + c)/(4*c)),
        variable=x,
        num_steps=2,
        integral=-asin((b - 2*c*x)/sqrt(c))/sqrt(c),
    ),
    RubiTestSuiteCase(
        integrand=(x**2 + 3*x + 2)**(sympy.S(-3)/2),
        variable=x,
        num_steps=1,
        integral=(-4*x - 6)/sqrt(x**2 + 3*x + 2),
    ),
    RubiTestSuiteCase(
        integrand=(4*x**2 - 24*x + 27)**(sympy.S(-3)/2),
        variable=x,
        num_steps=1,
        integral=(3 - x)/(9*sqrt(4*x**2 - 24*x + 27)),
    ),
    RubiTestSuiteCase(
        integrand=x/(-x**2 - 4*x + 5)**(sympy.S(3)/2),
        variable=x,
        num_steps=1,
        integral=(5 - 2*x)/(9*sqrt(-x**2 - 4*x + 5)),
    ),
    RubiTestSuiteCase(
        integrand=(-x**2 - 4*x + 5)**(sympy.S(-5)/2),
        variable=x,
        num_steps=2,
        integral=(x + 2)/(27*(-x**2 - 4*x + 5)**(sympy.S(3)/2)) + (2*x + 4)/(243*sqrt(-x**2 - 4*x + 5)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*x + c*x**2)**p,
        variable=x,
        num_steps=1,
        integral=-2**(p + 1)*(-(b + 2*c*x - sqrt(-4*a*c + b**2))/sqrt(-4*a*c + b**2))**(-p - 1)*(a + b*x + c*x**2)**(p + 1)*hyper((-p, p + 1), (p + 2,), (b + 2*c*x + sqrt(-4*a*c + b**2))/(2*sqrt(-4*a*c + b**2)))/((p + 1)*sqrt(-4*a*c + b**2)),
    ),
    RubiTestSuiteCase(
        integrand=(5*x**2 + 4*x + 3)**p,
        variable=x,
        num_steps=2,
        integral=11**p*5**(-p - 1)*(5*x + 2)*hyper((sympy.S.Half, -p), (sympy.S(3)/2,), -(5*x + 2)**2/11),
    ),
    RubiTestSuiteCase(
        integrand=(4*x**2 + 4*x + 3)**p,
        variable=x,
        num_steps=2,
        integral=2**(p - 1)*(2*x + 1)*hyper((sympy.S.Half, -p), (sympy.S(3)/2,), -(2*x + 1)**2/2),
    ),
    RubiTestSuiteCase(
        integrand=(3*x**2 + 4*x + 3)**p,
        variable=x,
        num_steps=2,
        integral=3**(-p - 1)*5**p*(3*x + 2)*hyper((sympy.S.Half, -p), (sympy.S(3)/2,), -(3*x + 2)**2/5),
    ),
    RubiTestSuiteCase(
        integrand=(2*x**2 + 4*x + 3)**p,
        variable=x,
        num_steps=2,
        integral=(x + 1)*hyper((sympy.S.Half, -p), (sympy.S(3)/2,), -2*(x + 1)**2),
    ),
    RubiTestSuiteCase(
        integrand=(x**2 + 4*x + 3)**p,
        variable=x,
        num_steps=1,
        integral=-2**(2*p + 1)*(-2*x - 2)**(-p - 1)*(x**2 + 4*x + 3)**(p + 1)*hyper((-p, p + 1), (p + 2,), x/2 + sympy.S(3)/2)/(p + 1),
    ),
    RubiTestSuiteCase(
        integrand=(4*x + 3)**p,
        variable=x,
        num_steps=1,
        integral=(4*x + 3)**(p + 1)/(4*p + 4),
    ),
    RubiTestSuiteCase(
        integrand=(-x**2 + 4*x + 3)**p,
        variable=x,
        num_steps=2,
        integral=-7**p*(2 - x)*hyper((sympy.S.Half, -p), (sympy.S(3)/2,), (2 - x)**2/7),
    ),
    RubiTestSuiteCase(
        integrand=(-2*x**2 + 4*x + 3)**p,
        variable=x,
        num_steps=2,
        integral=-5**p*(1 - x)*hyper((sympy.S.Half, -p), (sympy.S(3)/2,), 2*(1 - x)**2/5),
    ),
    RubiTestSuiteCase(
        integrand=(-3*x**2 + 4*x + 3)**p,
        variable=x,
        num_steps=2,
        integral=-13**p*3**(-p - 1)*(2 - 3*x)*hyper((sympy.S.Half, -p), (sympy.S(3)/2,), (2 - 3*x)**2/13),
    ),
    RubiTestSuiteCase(
        integrand=(-4*x**2 + 4*x + 3)**p,
        variable=x,
        num_steps=2,
        integral=-2**(2*p - 1)*(1 - 2*x)*hyper((sympy.S.Half, -p), (sympy.S(3)/2,), (1 - 2*x)**2/4),
    ),
    RubiTestSuiteCase(
        integrand=(-5*x**2 + 4*x + 3)**p,
        variable=x,
        num_steps=2,
        integral=-19**p*5**(-p - 1)*(2 - 5*x)*hyper((sympy.S.Half, -p), (sympy.S(3)/2,), (2 - 5*x)**2/19),
    ),
]
