# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 6 Hyperbolic functions/6.4 Hyperbolic cotangent/6.4.2 Hyperbolic cotangent functions.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '6 Hyperbolic functions/6.4 Hyperbolic cotangent/6.4.2 Hyperbolic cotangent functions.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, c, d, m, n = symbols('a b c d m n')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=7,
        integral=b**(sympy.S(7)/2)*atan(sqrt(b*coth(c + d*x))/sqrt(b))/d + b**(sympy.S(7)/2)*atanh(sqrt(b*coth(c + d*x))/sqrt(b))/d - 2*b**3*sqrt(b*coth(c + d*x))/d - 2*b*(b*coth(c + d*x))**(sympy.S(5)/2)/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=6,
        integral=-b**(sympy.S(5)/2)*atan(sqrt(b*coth(c + d*x))/sqrt(b))/d + b**(sympy.S(5)/2)*atanh(sqrt(b*coth(c + d*x))/sqrt(b))/d - 2*b*(b*coth(c + d*x))**(sympy.S(3)/2)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=b**(sympy.S(3)/2)*atan(sqrt(b*coth(c + d*x))/sqrt(b))/d + b**(sympy.S(3)/2)*atanh(sqrt(b*coth(c + d*x))/sqrt(b))/d - 2*b*sqrt(b*coth(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*coth(c + d*x)),
        variable=x,
        num_steps=5,
        integral=-sqrt(b)*atan(sqrt(b*coth(c + d*x))/sqrt(b))/d + sqrt(b)*atanh(sqrt(b*coth(c + d*x))/sqrt(b))/d,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(b*coth(c + d*x)),
        variable=x,
        num_steps=5,
        integral=atan(sqrt(b*coth(c + d*x))/sqrt(b))/(sqrt(b)*d) + atanh(sqrt(b*coth(c + d*x))/sqrt(b))/(sqrt(b)*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x))**(sympy.S(-3)/2),
        variable=x,
        num_steps=6,
        integral=-2/(b*d*sqrt(b*coth(c + d*x))) - atan(sqrt(b*coth(c + d*x))/sqrt(b))/(b**(sympy.S(3)/2)*d) + atanh(sqrt(b*coth(c + d*x))/sqrt(b))/(b**(sympy.S(3)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x))**(sympy.S(-5)/2),
        variable=x,
        num_steps=6,
        integral=-2/(3*b*d*(b*coth(c + d*x))**(sympy.S(3)/2)) + atan(sqrt(b*coth(c + d*x))/sqrt(b))/(b**(sympy.S(5)/2)*d) + atanh(sqrt(b*coth(c + d*x))/sqrt(b))/(b**(sympy.S(5)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x))**(sympy.S(-7)/2),
        variable=x,
        num_steps=7,
        integral=-2/(5*b*d*(b*coth(c + d*x))**(sympy.S(5)/2)) - 2/(b**3*d*sqrt(b*coth(c + d*x))) - atan(sqrt(b*coth(c + d*x))/sqrt(b))/(b**(sympy.S(7)/2)*d) + atanh(sqrt(b*coth(c + d*x))/sqrt(b))/(b**(sympy.S(7)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=13,
        integral=-b**(sympy.S(4)/3)*log(b**(sympy.S(2)/3) - b**(sympy.S(1)/3)*(b*coth(c + d*x))**(sympy.S(1)/3) + (b*coth(c + d*x))**(sympy.S(2)/3))/(4*d) + b**(sympy.S(4)/3)*log(b**(sympy.S(2)/3) + b**(sympy.S(1)/3)*(b*coth(c + d*x))**(sympy.S(1)/3) + (b*coth(c + d*x))**(sympy.S(2)/3))/(4*d) - sqrt(3)*b**(sympy.S(4)/3)*atan(sqrt(3)*(1 - 2*(b*coth(c + d*x))**(sympy.S(1)/3)/b**(sympy.S(1)/3))/3)/(2*d) + sqrt(3)*b**(sympy.S(4)/3)*atan(sqrt(3)*(1 + 2*(b*coth(c + d*x))**(sympy.S(1)/3)/b**(sympy.S(1)/3))/3)/(2*d) + b**(sympy.S(4)/3)*atanh((b*coth(c + d*x))**(sympy.S(1)/3)/b**(sympy.S(1)/3))/d - 3*b*(b*coth(c + d*x))**(sympy.S(1)/3)/d,
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x))**(sympy.S(2)/3),
        variable=x,
        num_steps=12,
        integral=-b**(sympy.S(2)/3)*log(b**(sympy.S(2)/3) - b**(sympy.S(1)/3)*(b*coth(c + d*x))**(sympy.S(1)/3) + (b*coth(c + d*x))**(sympy.S(2)/3))/(4*d) + b**(sympy.S(2)/3)*log(b**(sympy.S(2)/3) + b**(sympy.S(1)/3)*(b*coth(c + d*x))**(sympy.S(1)/3) + (b*coth(c + d*x))**(sympy.S(2)/3))/(4*d) + sqrt(3)*b**(sympy.S(2)/3)*atan(sqrt(3)*(1 - 2*(b*coth(c + d*x))**(sympy.S(1)/3)/b**(sympy.S(1)/3))/3)/(2*d) - sqrt(3)*b**(sympy.S(2)/3)*atan(sqrt(3)*(1 + 2*(b*coth(c + d*x))**(sympy.S(1)/3)/b**(sympy.S(1)/3))/3)/(2*d) + b**(sympy.S(2)/3)*atanh((b*coth(c + d*x))**(sympy.S(1)/3)/b**(sympy.S(1)/3))/d,
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=9,
        integral=-b**(sympy.S(1)/3)*log(b**(sympy.S(2)/3) - (b*coth(c + d*x))**(sympy.S(2)/3))/(2*d) + b**(sympy.S(1)/3)*log(b**(sympy.S(4)/3) + b**(sympy.S(2)/3)*(b*coth(c + d*x))**(sympy.S(2)/3) + (b*coth(c + d*x))**(sympy.S(4)/3))/(4*d) - sqrt(3)*b**(sympy.S(1)/3)*atan(sqrt(3)*(b**(sympy.S(2)/3) + 2*(b*coth(c + d*x))**(sympy.S(2)/3))/(3*b**(sympy.S(2)/3)))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x))**(sympy.S(-1)/3),
        variable=x,
        num_steps=9,
        integral=-log(b**(sympy.S(2)/3) - (b*coth(c + d*x))**(sympy.S(2)/3))/(2*b**(sympy.S(1)/3)*d) + log(b**(sympy.S(4)/3) + b**(sympy.S(2)/3)*(b*coth(c + d*x))**(sympy.S(2)/3) + (b*coth(c + d*x))**(sympy.S(4)/3))/(4*b**(sympy.S(1)/3)*d) + sqrt(3)*atan(sqrt(3)*(b**(sympy.S(2)/3) + 2*(b*coth(c + d*x))**(sympy.S(2)/3))/(3*b**(sympy.S(2)/3)))/(2*b**(sympy.S(1)/3)*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x))**(sympy.S(-2)/3),
        variable=x,
        num_steps=12,
        integral=-log(b**(sympy.S(2)/3) - b**(sympy.S(1)/3)*(b*coth(c + d*x))**(sympy.S(1)/3) + (b*coth(c + d*x))**(sympy.S(2)/3))/(4*b**(sympy.S(2)/3)*d) + log(b**(sympy.S(2)/3) + b**(sympy.S(1)/3)*(b*coth(c + d*x))**(sympy.S(1)/3) + (b*coth(c + d*x))**(sympy.S(2)/3))/(4*b**(sympy.S(2)/3)*d) - sqrt(3)*atan(sqrt(3)*(1 - 2*(b*coth(c + d*x))**(sympy.S(1)/3)/b**(sympy.S(1)/3))/3)/(2*b**(sympy.S(2)/3)*d) + sqrt(3)*atan(sqrt(3)*(1 + 2*(b*coth(c + d*x))**(sympy.S(1)/3)/b**(sympy.S(1)/3))/3)/(2*b**(sympy.S(2)/3)*d) + atanh((b*coth(c + d*x))**(sympy.S(1)/3)/b**(sympy.S(1)/3))/(b**(sympy.S(2)/3)*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x))**(sympy.S(-4)/3),
        variable=x,
        num_steps=13,
        integral=-3/(b*d*(b*coth(c + d*x))**(sympy.S(1)/3)) - log(b**(sympy.S(2)/3) - b**(sympy.S(1)/3)*(b*coth(c + d*x))**(sympy.S(1)/3) + (b*coth(c + d*x))**(sympy.S(2)/3))/(4*b**(sympy.S(4)/3)*d) + log(b**(sympy.S(2)/3) + b**(sympy.S(1)/3)*(b*coth(c + d*x))**(sympy.S(1)/3) + (b*coth(c + d*x))**(sympy.S(2)/3))/(4*b**(sympy.S(4)/3)*d) + sqrt(3)*atan(sqrt(3)*(1 - 2*(b*coth(c + d*x))**(sympy.S(1)/3)/b**(sympy.S(1)/3))/3)/(2*b**(sympy.S(4)/3)*d) - sqrt(3)*atan(sqrt(3)*(1 + 2*(b*coth(c + d*x))**(sympy.S(1)/3)/b**(sympy.S(1)/3))/3)/(2*b**(sympy.S(4)/3)*d) + atanh((b*coth(c + d*x))**(sympy.S(1)/3)/b**(sympy.S(1)/3))/(b**(sympy.S(4)/3)*d),
    ),
    RubiTestSuiteCase(
        integrand=coth(a + b*x)**n,
        variable=x,
        num_steps=2,
        integral=coth(a + b*x)**(n + 1)*hyper((1, n/2 + sympy.S.Half), (n/2 + sympy.S(3)/2,), coth(a + b*x)**2)/(b*(n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x))**n,
        variable=x,
        num_steps=2,
        integral=(b*coth(c + d*x))**(n + 1)*hyper((1, n/2 + sympy.S.Half), (n/2 + sympy.S(3)/2,), coth(c + d*x)**2)/(b*d*(n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**2)**n,
        variable=x,
        num_steps=3,
        integral=(b*coth(c + d*x)**2)**n*coth(c + d*x)*hyper((1, n + sympy.S.Half), (n + sympy.S(3)/2,), coth(c + d*x)**2)/(d*(2*n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=b*sqrt(b*coth(c + d*x)**2)*log(sinh(c + d*x))*tanh(c + d*x)/d - b*sqrt(b*coth(c + d*x)**2)*coth(c + d*x)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*coth(c + d*x)**2),
        variable=x,
        num_steps=2,
        integral=sqrt(b*coth(c + d*x)**2)*log(sinh(c + d*x))*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(b*coth(c + d*x)**2),
        variable=x,
        num_steps=2,
        integral=log(cosh(c + d*x))*coth(c + d*x)/(d*sqrt(b*coth(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**2)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=log(cosh(c + d*x))*coth(c + d*x)/(b*d*sqrt(b*coth(c + d*x)**2)) - tanh(c + d*x)/(2*b*d*sqrt(b*coth(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**2)**(sympy.S(4)/3),
        variable=x,
        num_steps=14,
        integral=-b*(b*coth(c + d*x)**2)**(sympy.S(1)/3)*log(coth(c + d*x)**(sympy.S(2)/3) - coth(c + d*x)**(sympy.S(1)/3) + 1)/(4*d*coth(c + d*x)**(sympy.S(2)/3)) + b*(b*coth(c + d*x)**2)**(sympy.S(1)/3)*log(coth(c + d*x)**(sympy.S(2)/3) + coth(c + d*x)**(sympy.S(1)/3) + 1)/(4*d*coth(c + d*x)**(sympy.S(2)/3)) - 3*b*(b*coth(c + d*x)**2)**(sympy.S(1)/3)*coth(c + d*x)/(5*d) + sqrt(3)*b*(b*coth(c + d*x)**2)**(sympy.S(1)/3)*atan(sqrt(3)*(1 - 2*coth(c + d*x)**(sympy.S(1)/3))/3)/(2*d*coth(c + d*x)**(sympy.S(2)/3)) - sqrt(3)*b*(b*coth(c + d*x)**2)**(sympy.S(1)/3)*atan(sqrt(3)*(2*coth(c + d*x)**(sympy.S(1)/3) + 1)/3)/(2*d*coth(c + d*x)**(sympy.S(2)/3)) + b*(b*coth(c + d*x)**2)**(sympy.S(1)/3)*atanh(coth(c + d*x)**(sympy.S(1)/3))/(d*coth(c + d*x)**(sympy.S(2)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**2)**(sympy.S(2)/3),
        variable=x,
        num_steps=14,
        integral=-(b*coth(c + d*x)**2)**(sympy.S(2)/3)*log(coth(c + d*x)**(sympy.S(2)/3) - coth(c + d*x)**(sympy.S(1)/3) + 1)/(4*d*coth(c + d*x)**(sympy.S(4)/3)) + (b*coth(c + d*x)**2)**(sympy.S(2)/3)*log(coth(c + d*x)**(sympy.S(2)/3) + coth(c + d*x)**(sympy.S(1)/3) + 1)/(4*d*coth(c + d*x)**(sympy.S(4)/3)) - 3*(b*coth(c + d*x)**2)**(sympy.S(2)/3)*tanh(c + d*x)/d - sqrt(3)*(b*coth(c + d*x)**2)**(sympy.S(2)/3)*atan(sqrt(3)*(1 - 2*coth(c + d*x)**(sympy.S(1)/3))/3)/(2*d*coth(c + d*x)**(sympy.S(4)/3)) + sqrt(3)*(b*coth(c + d*x)**2)**(sympy.S(2)/3)*atan(sqrt(3)*(2*coth(c + d*x)**(sympy.S(1)/3) + 1)/3)/(2*d*coth(c + d*x)**(sympy.S(4)/3)) + (b*coth(c + d*x)**2)**(sympy.S(2)/3)*atanh(coth(c + d*x)**(sympy.S(1)/3))/(d*coth(c + d*x)**(sympy.S(4)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**2)**(sympy.S(1)/3),
        variable=x,
        num_steps=13,
        integral=-(b*coth(c + d*x)**2)**(sympy.S(1)/3)*log(coth(c + d*x)**(sympy.S(2)/3) - coth(c + d*x)**(sympy.S(1)/3) + 1)/(4*d*coth(c + d*x)**(sympy.S(2)/3)) + (b*coth(c + d*x)**2)**(sympy.S(1)/3)*log(coth(c + d*x)**(sympy.S(2)/3) + coth(c + d*x)**(sympy.S(1)/3) + 1)/(4*d*coth(c + d*x)**(sympy.S(2)/3)) + sqrt(3)*(b*coth(c + d*x)**2)**(sympy.S(1)/3)*atan(sqrt(3)*(1 - 2*coth(c + d*x)**(sympy.S(1)/3))/3)/(2*d*coth(c + d*x)**(sympy.S(2)/3)) - sqrt(3)*(b*coth(c + d*x)**2)**(sympy.S(1)/3)*atan(sqrt(3)*(2*coth(c + d*x)**(sympy.S(1)/3) + 1)/3)/(2*d*coth(c + d*x)**(sympy.S(2)/3)) + (b*coth(c + d*x)**2)**(sympy.S(1)/3)*atanh(coth(c + d*x)**(sympy.S(1)/3))/(d*coth(c + d*x)**(sympy.S(2)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**2)**(sympy.S(-1)/3),
        variable=x,
        num_steps=13,
        integral=-log(coth(c + d*x)**(sympy.S(2)/3) - coth(c + d*x)**(sympy.S(1)/3) + 1)*coth(c + d*x)**(sympy.S(2)/3)/(4*d*(b*coth(c + d*x)**2)**(sympy.S(1)/3)) + log(coth(c + d*x)**(sympy.S(2)/3) + coth(c + d*x)**(sympy.S(1)/3) + 1)*coth(c + d*x)**(sympy.S(2)/3)/(4*d*(b*coth(c + d*x)**2)**(sympy.S(1)/3)) - sqrt(3)*coth(c + d*x)**(sympy.S(2)/3)*atan(sqrt(3)*(1 - 2*coth(c + d*x)**(sympy.S(1)/3))/3)/(2*d*(b*coth(c + d*x)**2)**(sympy.S(1)/3)) + sqrt(3)*coth(c + d*x)**(sympy.S(2)/3)*atan(sqrt(3)*(2*coth(c + d*x)**(sympy.S(1)/3) + 1)/3)/(2*d*(b*coth(c + d*x)**2)**(sympy.S(1)/3)) + coth(c + d*x)**(sympy.S(2)/3)*atanh(coth(c + d*x)**(sympy.S(1)/3))/(d*(b*coth(c + d*x)**2)**(sympy.S(1)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**2)**(sympy.S(-2)/3),
        variable=x,
        num_steps=14,
        integral=-log(coth(c + d*x)**(sympy.S(2)/3) - coth(c + d*x)**(sympy.S(1)/3) + 1)*coth(c + d*x)**(sympy.S(4)/3)/(4*d*(b*coth(c + d*x)**2)**(sympy.S(2)/3)) + log(coth(c + d*x)**(sympy.S(2)/3) + coth(c + d*x)**(sympy.S(1)/3) + 1)*coth(c + d*x)**(sympy.S(4)/3)/(4*d*(b*coth(c + d*x)**2)**(sympy.S(2)/3)) + sqrt(3)*coth(c + d*x)**(sympy.S(4)/3)*atan(sqrt(3)*(1 - 2*coth(c + d*x)**(sympy.S(1)/3))/3)/(2*d*(b*coth(c + d*x)**2)**(sympy.S(2)/3)) - sqrt(3)*coth(c + d*x)**(sympy.S(4)/3)*atan(sqrt(3)*(2*coth(c + d*x)**(sympy.S(1)/3) + 1)/3)/(2*d*(b*coth(c + d*x)**2)**(sympy.S(2)/3)) + coth(c + d*x)**(sympy.S(4)/3)*atanh(coth(c + d*x)**(sympy.S(1)/3))/(d*(b*coth(c + d*x)**2)**(sympy.S(2)/3)) - 3*coth(c + d*x)/(d*(b*coth(c + d*x)**2)**(sympy.S(2)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**2)**(sympy.S(-4)/3),
        variable=x,
        num_steps=14,
        integral=-log(coth(c + d*x)**(sympy.S(2)/3) - coth(c + d*x)**(sympy.S(1)/3) + 1)*coth(c + d*x)**(sympy.S(2)/3)/(4*b*d*(b*coth(c + d*x)**2)**(sympy.S(1)/3)) + log(coth(c + d*x)**(sympy.S(2)/3) + coth(c + d*x)**(sympy.S(1)/3) + 1)*coth(c + d*x)**(sympy.S(2)/3)/(4*b*d*(b*coth(c + d*x)**2)**(sympy.S(1)/3)) - 3*tanh(c + d*x)/(5*b*d*(b*coth(c + d*x)**2)**(sympy.S(1)/3)) - sqrt(3)*coth(c + d*x)**(sympy.S(2)/3)*atan(sqrt(3)*(1 - 2*coth(c + d*x)**(sympy.S(1)/3))/3)/(2*b*d*(b*coth(c + d*x)**2)**(sympy.S(1)/3)) + sqrt(3)*coth(c + d*x)**(sympy.S(2)/3)*atan(sqrt(3)*(2*coth(c + d*x)**(sympy.S(1)/3) + 1)/3)/(2*b*d*(b*coth(c + d*x)**2)**(sympy.S(1)/3)) + coth(c + d*x)**(sympy.S(2)/3)*atanh(coth(c + d*x)**(sympy.S(1)/3))/(b*d*(b*coth(c + d*x)**2)**(sympy.S(1)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**3)**n,
        variable=x,
        num_steps=3,
        integral=(b*coth(c + d*x)**3)**n*coth(c + d*x)*hyper((1, 3*n/2 + sympy.S.Half), (3*n/2 + sympy.S(3)/2,), coth(c + d*x)**2)/(d*(3*n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**3)**(sympy.S(3)/2),
        variable=x,
        num_steps=8,
        integral=-2*b*sqrt(b*coth(c + d*x)**3)*coth(c + d*x)**2/(7*d) - 2*b*sqrt(b*coth(c + d*x)**3)/(3*d) - b*sqrt(b*coth(c + d*x)**3)*atan(sqrt(coth(c + d*x)))/(d*coth(c + d*x)**(sympy.S(3)/2)) + b*sqrt(b*coth(c + d*x)**3)*atanh(sqrt(coth(c + d*x)))/(d*coth(c + d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*coth(c + d*x)**3),
        variable=x,
        num_steps=7,
        integral=-2*sqrt(b*coth(c + d*x)**3)*tanh(c + d*x)/d + sqrt(b*coth(c + d*x)**3)*atan(sqrt(coth(c + d*x)))/(d*coth(c + d*x)**(sympy.S(3)/2)) + sqrt(b*coth(c + d*x)**3)*atanh(sqrt(coth(c + d*x)))/(d*coth(c + d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(b*coth(c + d*x)**3),
        variable=x,
        num_steps=7,
        integral=-coth(c + d*x)**(sympy.S(3)/2)*atan(sqrt(coth(c + d*x)))/(d*sqrt(b*coth(c + d*x)**3)) + coth(c + d*x)**(sympy.S(3)/2)*atanh(sqrt(coth(c + d*x)))/(d*sqrt(b*coth(c + d*x)**3)) - 2*coth(c + d*x)/(d*sqrt(b*coth(c + d*x)**3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**3)**(sympy.S(-3)/2),
        variable=x,
        num_steps=8,
        integral=-2*tanh(c + d*x)**2/(7*b*d*sqrt(b*coth(c + d*x)**3)) + coth(c + d*x)**(sympy.S(3)/2)*atan(sqrt(coth(c + d*x)))/(b*d*sqrt(b*coth(c + d*x)**3)) + coth(c + d*x)**(sympy.S(3)/2)*atanh(sqrt(coth(c + d*x)))/(b*d*sqrt(b*coth(c + d*x)**3)) - 2/(3*b*d*sqrt(b*coth(c + d*x)**3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**3)**(sympy.S(4)/3),
        variable=x,
        num_steps=4,
        integral=b*x*(b*coth(c + d*x)**3)**(sympy.S(1)/3)*tanh(c + d*x) - b*(b*coth(c + d*x)**3)**(sympy.S(1)/3)*coth(c + d*x)**2/(3*d) - b*(b*coth(c + d*x)**3)**(sympy.S(1)/3)/d,
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**3)**(sympy.S(2)/3),
        variable=x,
        num_steps=3,
        integral=x*(b*coth(c + d*x)**3)**(sympy.S(2)/3)*tanh(c + d*x)**2 - (b*coth(c + d*x)**3)**(sympy.S(2)/3)*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**3)**(sympy.S(1)/3),
        variable=x,
        num_steps=2,
        integral=(b*coth(c + d*x)**3)**(sympy.S(1)/3)*log(sinh(c + d*x))*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**3)**(sympy.S(-1)/3),
        variable=x,
        num_steps=2,
        integral=log(cosh(c + d*x))*coth(c + d*x)/(d*(b*coth(c + d*x)**3)**(sympy.S(1)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**3)**(sympy.S(-2)/3),
        variable=x,
        num_steps=3,
        integral=x*coth(c + d*x)**2/(b*coth(c + d*x)**3)**(sympy.S(2)/3) - coth(c + d*x)/(d*(b*coth(c + d*x)**3)**(sympy.S(2)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**3)**(sympy.S(-4)/3),
        variable=x,
        num_steps=4,
        integral=x*coth(c + d*x)/(b*(b*coth(c + d*x)**3)**(sympy.S(1)/3)) - tanh(c + d*x)**2/(3*b*d*(b*coth(c + d*x)**3)**(sympy.S(1)/3)) - 1/(b*d*(b*coth(c + d*x)**3)**(sympy.S(1)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**4)**n,
        variable=x,
        num_steps=3,
        integral=(b*coth(c + d*x)**4)**n*coth(c + d*x)*hyper((1, 2*n + sympy.S.Half), (2*n + sympy.S(3)/2,), coth(c + d*x)**2)/(d*(4*n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**4)**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=b*x*sqrt(b*coth(c + d*x)**4)*tanh(c + d*x)**2 - b*sqrt(b*coth(c + d*x)**4)*tanh(c + d*x)/d - b*sqrt(b*coth(c + d*x)**4)*coth(c + d*x)**3/(5*d) - b*sqrt(b*coth(c + d*x)**4)*coth(c + d*x)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*coth(c + d*x)**4),
        variable=x,
        num_steps=3,
        integral=x*sqrt(b*coth(c + d*x)**4)*tanh(c + d*x)**2 - sqrt(b*coth(c + d*x)**4)*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(b*coth(c + d*x)**4),
        variable=x,
        num_steps=3,
        integral=x*coth(c + d*x)**2/sqrt(b*coth(c + d*x)**4) - coth(c + d*x)/(d*sqrt(b*coth(c + d*x)**4)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**4)**(sympy.S(-3)/2),
        variable=x,
        num_steps=5,
        integral=x*coth(c + d*x)**2/(b*sqrt(b*coth(c + d*x)**4)) - tanh(c + d*x)**3/(5*b*d*sqrt(b*coth(c + d*x)**4)) - tanh(c + d*x)/(3*b*d*sqrt(b*coth(c + d*x)**4)) - coth(c + d*x)/(b*d*sqrt(b*coth(c + d*x)**4)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**4)**(sympy.S(4)/3),
        variable=x,
        num_steps=16,
        integral=-b*(b*coth(c + d*x)**4)**(sympy.S(1)/3)*log(coth(c + d*x)**(sympy.S(2)/3) - coth(c + d*x)**(sympy.S(1)/3) + 1)/(4*d*coth(c + d*x)**(sympy.S(4)/3)) + b*(b*coth(c + d*x)**4)**(sympy.S(1)/3)*log(coth(c + d*x)**(sympy.S(2)/3) + coth(c + d*x)**(sympy.S(1)/3) + 1)/(4*d*coth(c + d*x)**(sympy.S(4)/3)) - 3*b*(b*coth(c + d*x)**4)**(sympy.S(1)/3)*tanh(c + d*x)/d - 3*b*(b*coth(c + d*x)**4)**(sympy.S(1)/3)*coth(c + d*x)**3/(13*d) - 3*b*(b*coth(c + d*x)**4)**(sympy.S(1)/3)*coth(c + d*x)/(7*d) - sqrt(3)*b*(b*coth(c + d*x)**4)**(sympy.S(1)/3)*atan(sqrt(3)*(1 - 2*coth(c + d*x)**(sympy.S(1)/3))/3)/(2*d*coth(c + d*x)**(sympy.S(4)/3)) + sqrt(3)*b*(b*coth(c + d*x)**4)**(sympy.S(1)/3)*atan(sqrt(3)*(2*coth(c + d*x)**(sympy.S(1)/3) + 1)/3)/(2*d*coth(c + d*x)**(sympy.S(4)/3)) + b*(b*coth(c + d*x)**4)**(sympy.S(1)/3)*atanh(coth(c + d*x)**(sympy.S(1)/3))/(d*coth(c + d*x)**(sympy.S(4)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**4)**(sympy.S(2)/3),
        variable=x,
        num_steps=14,
        integral=-(b*coth(c + d*x)**4)**(sympy.S(2)/3)*log(coth(c + d*x)**(sympy.S(2)/3) - coth(c + d*x)**(sympy.S(1)/3) + 1)/(4*d*coth(c + d*x)**(sympy.S(8)/3)) + (b*coth(c + d*x)**4)**(sympy.S(2)/3)*log(coth(c + d*x)**(sympy.S(2)/3) + coth(c + d*x)**(sympy.S(1)/3) + 1)/(4*d*coth(c + d*x)**(sympy.S(8)/3)) - 3*(b*coth(c + d*x)**4)**(sympy.S(2)/3)*tanh(c + d*x)/(5*d) + sqrt(3)*(b*coth(c + d*x)**4)**(sympy.S(2)/3)*atan(sqrt(3)*(1 - 2*coth(c + d*x)**(sympy.S(1)/3))/3)/(2*d*coth(c + d*x)**(sympy.S(8)/3)) - sqrt(3)*(b*coth(c + d*x)**4)**(sympy.S(2)/3)*atan(sqrt(3)*(2*coth(c + d*x)**(sympy.S(1)/3) + 1)/3)/(2*d*coth(c + d*x)**(sympy.S(8)/3)) + (b*coth(c + d*x)**4)**(sympy.S(2)/3)*atanh(coth(c + d*x)**(sympy.S(1)/3))/(d*coth(c + d*x)**(sympy.S(8)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**4)**(sympy.S(1)/3),
        variable=x,
        num_steps=14,
        integral=-(b*coth(c + d*x)**4)**(sympy.S(1)/3)*log(coth(c + d*x)**(sympy.S(2)/3) - coth(c + d*x)**(sympy.S(1)/3) + 1)/(4*d*coth(c + d*x)**(sympy.S(4)/3)) + (b*coth(c + d*x)**4)**(sympy.S(1)/3)*log(coth(c + d*x)**(sympy.S(2)/3) + coth(c + d*x)**(sympy.S(1)/3) + 1)/(4*d*coth(c + d*x)**(sympy.S(4)/3)) - 3*(b*coth(c + d*x)**4)**(sympy.S(1)/3)*tanh(c + d*x)/d - sqrt(3)*(b*coth(c + d*x)**4)**(sympy.S(1)/3)*atan(sqrt(3)*(1 - 2*coth(c + d*x)**(sympy.S(1)/3))/3)/(2*d*coth(c + d*x)**(sympy.S(4)/3)) + sqrt(3)*(b*coth(c + d*x)**4)**(sympy.S(1)/3)*atan(sqrt(3)*(2*coth(c + d*x)**(sympy.S(1)/3) + 1)/3)/(2*d*coth(c + d*x)**(sympy.S(4)/3)) + (b*coth(c + d*x)**4)**(sympy.S(1)/3)*atanh(coth(c + d*x)**(sympy.S(1)/3))/(d*coth(c + d*x)**(sympy.S(4)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**4)**(sympy.S(-1)/3),
        variable=x,
        num_steps=14,
        integral=-log(coth(c + d*x)**(sympy.S(2)/3) - coth(c + d*x)**(sympy.S(1)/3) + 1)*coth(c + d*x)**(sympy.S(4)/3)/(4*d*(b*coth(c + d*x)**4)**(sympy.S(1)/3)) + log(coth(c + d*x)**(sympy.S(2)/3) + coth(c + d*x)**(sympy.S(1)/3) + 1)*coth(c + d*x)**(sympy.S(4)/3)/(4*d*(b*coth(c + d*x)**4)**(sympy.S(1)/3)) + sqrt(3)*coth(c + d*x)**(sympy.S(4)/3)*atan(sqrt(3)*(1 - 2*coth(c + d*x)**(sympy.S(1)/3))/3)/(2*d*(b*coth(c + d*x)**4)**(sympy.S(1)/3)) - sqrt(3)*coth(c + d*x)**(sympy.S(4)/3)*atan(sqrt(3)*(2*coth(c + d*x)**(sympy.S(1)/3) + 1)/3)/(2*d*(b*coth(c + d*x)**4)**(sympy.S(1)/3)) + coth(c + d*x)**(sympy.S(4)/3)*atanh(coth(c + d*x)**(sympy.S(1)/3))/(d*(b*coth(c + d*x)**4)**(sympy.S(1)/3)) - 3*coth(c + d*x)/(d*(b*coth(c + d*x)**4)**(sympy.S(1)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**4)**(sympy.S(-2)/3),
        variable=x,
        num_steps=14,
        integral=-log(coth(c + d*x)**(sympy.S(2)/3) - coth(c + d*x)**(sympy.S(1)/3) + 1)*coth(c + d*x)**(sympy.S(8)/3)/(4*d*(b*coth(c + d*x)**4)**(sympy.S(2)/3)) + log(coth(c + d*x)**(sympy.S(2)/3) + coth(c + d*x)**(sympy.S(1)/3) + 1)*coth(c + d*x)**(sympy.S(8)/3)/(4*d*(b*coth(c + d*x)**4)**(sympy.S(2)/3)) - sqrt(3)*coth(c + d*x)**(sympy.S(8)/3)*atan(sqrt(3)*(1 - 2*coth(c + d*x)**(sympy.S(1)/3))/3)/(2*d*(b*coth(c + d*x)**4)**(sympy.S(2)/3)) + sqrt(3)*coth(c + d*x)**(sympy.S(8)/3)*atan(sqrt(3)*(2*coth(c + d*x)**(sympy.S(1)/3) + 1)/3)/(2*d*(b*coth(c + d*x)**4)**(sympy.S(2)/3)) + coth(c + d*x)**(sympy.S(8)/3)*atanh(coth(c + d*x)**(sympy.S(1)/3))/(d*(b*coth(c + d*x)**4)**(sympy.S(2)/3)) - 3*coth(c + d*x)/(5*d*(b*coth(c + d*x)**4)**(sympy.S(2)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**4)**(sympy.S(-4)/3),
        variable=x,
        num_steps=16,
        integral=-log(coth(c + d*x)**(sympy.S(2)/3) - coth(c + d*x)**(sympy.S(1)/3) + 1)*coth(c + d*x)**(sympy.S(4)/3)/(4*b*d*(b*coth(c + d*x)**4)**(sympy.S(1)/3)) + log(coth(c + d*x)**(sympy.S(2)/3) + coth(c + d*x)**(sympy.S(1)/3) + 1)*coth(c + d*x)**(sympy.S(4)/3)/(4*b*d*(b*coth(c + d*x)**4)**(sympy.S(1)/3)) - 3*tanh(c + d*x)**3/(13*b*d*(b*coth(c + d*x)**4)**(sympy.S(1)/3)) - 3*tanh(c + d*x)/(7*b*d*(b*coth(c + d*x)**4)**(sympy.S(1)/3)) + sqrt(3)*coth(c + d*x)**(sympy.S(4)/3)*atan(sqrt(3)*(1 - 2*coth(c + d*x)**(sympy.S(1)/3))/3)/(2*b*d*(b*coth(c + d*x)**4)**(sympy.S(1)/3)) - sqrt(3)*coth(c + d*x)**(sympy.S(4)/3)*atan(sqrt(3)*(2*coth(c + d*x)**(sympy.S(1)/3) + 1)/3)/(2*b*d*(b*coth(c + d*x)**4)**(sympy.S(1)/3)) + coth(c + d*x)**(sympy.S(4)/3)*atanh(coth(c + d*x)**(sympy.S(1)/3))/(b*d*(b*coth(c + d*x)**4)**(sympy.S(1)/3)) - 3*coth(c + d*x)/(b*d*(b*coth(c + d*x)**4)**(sympy.S(1)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**m)**n,
        variable=x,
        num_steps=3,
        integral=(b*coth(c + d*x)**m)**n*coth(c + d*x)*hyper((1, m*n/2 + sympy.S.Half), (m*n/2 + sympy.S(3)/2,), coth(c + d*x)**2)/(d*(m*n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**m)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*b*sqrt(b*coth(c + d*x)**m)*coth(c + d*x)**(m + 1)*hyper((1, 3*m/4 + sympy.S.Half), (3*m/4 + sympy.S(3)/2,), coth(c + d*x)**2)/(d*(3*m + 2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*coth(c + d*x)**m),
        variable=x,
        num_steps=3,
        integral=2*sqrt(b*coth(c + d*x)**m)*coth(c + d*x)*hyper((1, m/4 + sympy.S.Half), (m/4 + sympy.S(3)/2,), coth(c + d*x)**2)/(d*(m + 2)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(b*coth(c + d*x)**m),
        variable=x,
        num_steps=3,
        integral=2*coth(c + d*x)*hyper((1, sympy.S.Half - m/4), (sympy.S(3)/2 - m/4,), coth(c + d*x)**2)/(d*sqrt(b*coth(c + d*x)**m)*(2 - m)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**m)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*coth(c + d*x)**(1 - m)*hyper((1, sympy.S.Half - 3*m/4), (sympy.S(3)/2 - 3*m/4,), coth(c + d*x)**2)/(b*d*sqrt(b*coth(c + d*x)**m)*(2 - 3*m)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**m)**(sympy.S(4)/3),
        variable=x,
        num_steps=3,
        integral=3*b*(b*coth(c + d*x)**m)**(sympy.S(1)/3)*coth(c + d*x)**(m + 1)*hyper((1, 2*m/3 + sympy.S.Half), (2*m/3 + sympy.S(3)/2,), coth(c + d*x)**2)/(d*(4*m + 3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**m)**(sympy.S(2)/3),
        variable=x,
        num_steps=3,
        integral=3*(b*coth(c + d*x)**m)**(sympy.S(2)/3)*coth(c + d*x)*hyper((1, m/3 + sympy.S.Half), (m/3 + sympy.S(3)/2,), coth(c + d*x)**2)/(d*(2*m + 3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**m)**(sympy.S(1)/3),
        variable=x,
        num_steps=3,
        integral=3*(b*coth(c + d*x)**m)**(sympy.S(1)/3)*coth(c + d*x)*hyper((1, m/6 + sympy.S.Half), (m/6 + sympy.S(3)/2,), coth(c + d*x)**2)/(d*(m + 3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**m)**(sympy.S(-1)/3),
        variable=x,
        num_steps=3,
        integral=3*coth(c + d*x)*hyper((1, sympy.S.Half - m/6), (sympy.S(3)/2 - m/6,), coth(c + d*x)**2)/(d*(b*coth(c + d*x)**m)**(sympy.S(1)/3)*(3 - m)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**m)**(sympy.S(-2)/3),
        variable=x,
        num_steps=3,
        integral=3*coth(c + d*x)*hyper((1, sympy.S.Half - m/3), (sympy.S(3)/2 - m/3,), coth(c + d*x)**2)/(d*(b*coth(c + d*x)**m)**(sympy.S(2)/3)*(3 - 2*m)),
    ),
    RubiTestSuiteCase(
        integrand=(b*coth(c + d*x)**m)**(sympy.S(-4)/3),
        variable=x,
        num_steps=3,
        integral=3*coth(c + d*x)**(1 - m)*hyper((1, sympy.S.Half - 2*m/3), (sympy.S(3)/2 - 2*m/3,), coth(c + d*x)**2)/(b*d*(b*coth(c + d*x)**m)**(sympy.S(1)/3)*(3 - 4*m)),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**5,
        variable=x,
        num_steps=5,
        integral=16*x - (coth(x) + 1)**4/4 - 2*(coth(x) + 1)**3/3 - 2*(coth(x) + 1)**2 + 16*log(sinh(x)) - 8*coth(x),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**4,
        variable=x,
        num_steps=4,
        integral=8*x - (coth(x) + 1)**3/3 - (coth(x) + 1)**2 + 8*log(sinh(x)) - 4*coth(x),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**3,
        variable=x,
        num_steps=3,
        integral=4*x - (coth(x) + 1)**2/2 + 4*log(sinh(x)) - 2*coth(x),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**2,
        variable=x,
        num_steps=2,
        integral=2*x + 2*log(sinh(x)) - coth(x),
    ),
    RubiTestSuiteCase(
        integrand=1/(coth(x) + 1),
        variable=x,
        num_steps=2,
        integral=x/2 - 1/(2*coth(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**(-2),
        variable=x,
        num_steps=3,
        integral=x/4 - 1/(4*coth(x) + 4) - 1/(4*(coth(x) + 1)**2),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**(-3),
        variable=x,
        num_steps=4,
        integral=x/8 - 1/(8*coth(x) + 8) - 1/(8*(coth(x) + 1)**2) - 1/(6*(coth(x) + 1)**3),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**(-4),
        variable=x,
        num_steps=5,
        integral=x/16 - 1/(16*coth(x) + 16) - 1/(16*(coth(x) + 1)**2) - 1/(12*(coth(x) + 1)**3) - 1/(8*(coth(x) + 1)**4),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**(-5),
        variable=x,
        num_steps=6,
        integral=x/32 - 1/(32*coth(x) + 32) - 1/(32*(coth(x) + 1)**2) - 1/(24*(coth(x) + 1)**3) - 1/(16*(coth(x) + 1)**4) - 1/(10*(coth(x) + 1)**5),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**(sympy.S(7)/2),
        variable=x,
        num_steps=5,
        integral=-2*(coth(x) + 1)**(sympy.S(5)/2)/5 - 4*(coth(x) + 1)**(sympy.S(3)/2)/3 - 8*sqrt(coth(x) + 1) + 8*sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=-2*(coth(x) + 1)**(sympy.S(3)/2)/3 - 4*sqrt(coth(x) + 1) + 4*sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-2*sqrt(coth(x) + 1) + 2*sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(coth(x) + 1),
        variable=x,
        num_steps=2,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(coth(x) + 1),
        variable=x,
        num_steps=3,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2)/2 - 1/sqrt(coth(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**(sympy.S(-3)/2),
        variable=x,
        num_steps=4,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2)/4 - 1/(2*sqrt(coth(x) + 1)) - 1/(3*(coth(x) + 1)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**(sympy.S(-5)/2),
        variable=x,
        num_steps=5,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2)/8 - 1/(4*sqrt(coth(x) + 1)) - 1/(6*(coth(x) + 1)**(sympy.S(3)/2)) - 1/(5*(coth(x) + 1)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*coth(c + d*x))**5,
        variable=x,
        num_steps=5,
        integral=-4*a*b**2*(a**2 + b**2)*coth(c + d*x)/d - 2*a*b*(a + b*coth(c + d*x))**3/(3*d) + a*x*(a**4 + 10*a**2*b**2 + 5*b**4) - b*(a + b*coth(c + d*x))**4/(4*d) - b*(a + b*coth(c + d*x))**2*(3*a**2 + b**2)/(2*d) + b*(5*a**4 + 10*a**2*b**2 + b**4)*log(sinh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*coth(c + d*x))**4,
        variable=x,
        num_steps=4,
        integral=-a*b*(a + b*coth(c + d*x))**2/d + 4*a*b*(a**2 + b**2)*log(sinh(c + d*x))/d - b**2*(3*a**2 + b**2)*coth(c + d*x)/d - b*(a + b*coth(c + d*x))**3/(3*d) + x*(a**4 + 6*a**2*b**2 + b**4),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*coth(c + d*x))**3,
        variable=x,
        num_steps=3,
        integral=-2*a*b**2*coth(c + d*x)/d + a*x*(a**2 + 3*b**2) - b*(a + b*coth(c + d*x))**2/(2*d) + b*(3*a**2 + b**2)*log(sinh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*coth(c + d*x))**2,
        variable=x,
        num_steps=2,
        integral=2*a*b*log(sinh(c + d*x))/d - b**2*coth(c + d*x)/d + x*(a**2 + b**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*coth(c + d*x)),
        variable=x,
        num_steps=2,
        integral=a*x/(a**2 - b**2) - b*log(a*sinh(c + d*x) + b*cosh(c + d*x))/(d*(a**2 - b**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*coth(c + d*x))**(-2),
        variable=x,
        num_steps=3,
        integral=-2*a*b*log(a*sinh(c + d*x) + b*cosh(c + d*x))/(d*(a**2 - b**2)**2) + b/(d*(a + b*coth(c + d*x))*(a**2 - b**2)) + x*(a**2 + b**2)/(a**2 - b**2)**2,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*coth(c + d*x))**(-3),
        variable=x,
        num_steps=4,
        integral=2*a*b/(d*(a + b*coth(c + d*x))*(a**2 - b**2)**2) + a*x*(a**2 + 3*b**2)/(a**2 - b**2)**3 - b*(3*a**2 + b**2)*log(a*sinh(c + d*x) + b*cosh(c + d*x))/(d*(a**2 - b**2)**3) + b/(d*(a + b*coth(c + d*x))**2*(2*a**2 - 2*b**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*coth(c + d*x))**(-4),
        variable=x,
        num_steps=5,
        integral=-4*a*b*(a**2 + b**2)*log(a*sinh(c + d*x) + b*cosh(c + d*x))/(d*(a**2 - b**2)**4) + a*b/(d*(a + b*coth(c + d*x))**2*(a**2 - b**2)**2) + b*(3*a**2 + b**2)/(d*(a + b*coth(c + d*x))*(a**2 - b**2)**3) + b/(d*(a + b*coth(c + d*x))**3*(3*a**2 - 3*b**2)) + x*(a**4 + 6*a**2*b**2 + b**4)/(a**2 - b**2)**4,
    ),
    RubiTestSuiteCase(
        integrand=1/(6*coth(c + d*x) + 4),
        variable=x,
        num_steps=2,
        integral=-x/5 + 3*log(2*sinh(c + d*x) + 3*cosh(c + d*x))/(10*d),
    ),
    RubiTestSuiteCase(
        integrand=1/(4 - 6*coth(c + d*x)),
        variable=x,
        num_steps=2,
        integral=-x/5 - 3*log(-2*sinh(c + d*x) + 3*cosh(c + d*x))/(10*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*coth(c + d*x)),
        variable=x,
        num_steps=5,
        integral=-sqrt(a - b)*atanh(sqrt(a + b*coth(c + d*x))/sqrt(a - b))/d + sqrt(a + b)*atanh(sqrt(a + b*coth(c + d*x))/sqrt(a + b))/d,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a + b*coth(c + d*x)),
        variable=x,
        num_steps=5,
        integral=atanh(sqrt(a + b*coth(c + d*x))/sqrt(a + b))/(d*sqrt(a + b)) - atanh(sqrt(a + b*coth(c + d*x))/sqrt(a - b))/(d*sqrt(a - b)),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**4/(coth(x) + 1),
        variable=x,
        num_steps=4,
        integral=5*x/16 - 3/(16*coth(x) + 16) - 3/(32*(coth(x) + 1)**2) - 1/(24*(coth(x) + 1)**3) + 1/(8 - 8*coth(x)) + 1/(32*(1 - coth(x))**2),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**3/(coth(x) + 1),
        variable=x,
        num_steps=3,
        integral=4*cosh(x)**3/15 - 4*cosh(x)/5 - sinh(x)**3/(5*coth(x) + 5),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**2/(coth(x) + 1),
        variable=x,
        num_steps=4,
        integral=-3*x/8 + 1/(4*coth(x) + 4) + 1/(8*(coth(x) + 1)**2) - 1/(8 - 8*coth(x)),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)/(coth(x) + 1),
        variable=x,
        num_steps=2,
        integral=2*cosh(x)/3 - sinh(x)/(3*coth(x) + 3),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)/(coth(x) + 1),
        variable=x,
        num_steps=1,
        integral=-csch(x)/(coth(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**2/(coth(x) + 1),
        variable=x,
        num_steps=2,
        integral=-log(coth(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**3/(coth(x) + 1),
        variable=x,
        num_steps=2,
        integral=atanh(cosh(x)) - csch(x),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**4/(coth(x) + 1),
        variable=x,
        num_steps=2,
        integral=-coth(x)**2/2 + coth(x),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**4/(a + b*coth(x)),
        variable=x,
        num_steps=5,
        integral=-b**5*log(a + b*coth(x))/(a**2 - b**2)**3 - (-a*coth(x) + b)*sinh(x)**4/(4*a**2 - 4*b**2) - (-a*b**2*(-3*a**2/b**2 + 7)*coth(x) + 4*b**3)*sinh(x)**2/(8*(a**2 - b**2)**2) - (3*a**2 + 9*a*b + 8*b**2)*log(1 - coth(x))/(16*(a + b)**3) + (3*a**2 - 9*a*b + 8*b**2)*log(coth(x) + 1)/(16*(a - b)**3),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**3/(a + b*coth(x)),
        variable=x,
        num_steps=9,
        integral=a*b**2*cosh(x)/(a**2 - b**2)**2 + a*cosh(x)**3/(3*a**2 - 3*b**2) - a*cosh(x)/(a**2 - b**2) - b**4*atanh((a*coth(x) + b)*sinh(x)/sqrt(a**2 - b**2))/(a**2 - b**2)**(sympy.S(5)/2) - b**3*sinh(x)/(a**2 - b**2)**2 - b*sinh(x)**3/(3*a**2 - 3*b**2),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**2/(a + b*coth(x)),
        variable=x,
        num_steps=4,
        integral=-b**3*log(a + b*coth(x))/(a**2 - b**2)**2 - (a - 2*b)*log(coth(x) + 1)/(4*(a - b)**2) - (-a*coth(x) + b)*sinh(x)**2/(2*a**2 - 2*b**2) + (a + 2*b)*log(1 - coth(x))/(4*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)/(a + b*coth(x)),
        variable=x,
        num_steps=5,
        integral=a*cosh(x)/(a**2 - b**2) - b**2*atanh((a*coth(x) + b)*sinh(x)/sqrt(a**2 - b**2))/(a**2 - b**2)**(sympy.S(3)/2) - b*sinh(x)/(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)/(a + b*coth(x)),
        variable=x,
        num_steps=2,
        integral=-atanh((a*coth(x) + b)*sinh(x)/sqrt(a**2 - b**2))/sqrt(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**2/(a + b*coth(x)),
        variable=x,
        num_steps=2,
        integral=-log(a + b*coth(x))/b,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**3/(a + b*coth(x)),
        variable=x,
        num_steps=5,
        integral=a*atanh(cosh(x))/b**2 - csch(x)/b - sqrt(a**2 - b**2)*atanh((a*coth(x) + b)*sinh(x)/sqrt(a**2 - b**2))/b**2,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**4/(a + b*coth(x)),
        variable=x,
        num_steps=3,
        integral=a*coth(x)/b**2 - coth(x)**2/(2*b) - (a**2 - b**2)*log(a + b*coth(x))/b**3,
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**4/(coth(x) + 1),
        variable=x,
        num_steps=5,
        integral=x/16 - 3/(16*coth(x) + 16) + 5/(32*(coth(x) + 1)**2) - 1/(24*(coth(x) + 1)**3) - 1/(8 - 8*coth(x)) + 1/(32*(1 - coth(x))**2),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**3/(coth(x) + 1),
        variable=x,
        num_steps=9,
        integral=-sinh(x)**5/5 - sinh(x)**3/3 + cosh(x)**5/5,
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**2/(coth(x) + 1),
        variable=x,
        num_steps=5,
        integral=x/8 - 1/(4*coth(x) + 4) + 1/(8*(coth(x) + 1)**2) - 1/(8 - 8*coth(x)),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)/(coth(x) + 1),
        variable=x,
        num_steps=8,
        integral=-sinh(x)**3/3 + cosh(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)/(coth(x) + 1),
        variable=x,
        num_steps=8,
        integral=-sinh(x) + cosh(x) + atan(sinh(x)),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**2/(coth(x) + 1),
        variable=x,
        num_steps=3,
        integral=-log(coth(x) + 1) - log(tanh(x)) + tanh(x),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**3/(coth(x) + 1),
        variable=x,
        num_steps=8,
        integral=tanh(x)*sech(x)/2 - atan(sinh(x))/2 - sech(x),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**4/(coth(x) + 1),
        variable=x,
        num_steps=4,
        integral=-tanh(x)**3/3 + tanh(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(coth(x) + 1)*sech(x)**2,
        variable=x,
        num_steps=4,
        integral=sqrt(coth(x) + 1)*tanh(x) + atanh(sqrt(coth(x) + 1)),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**4/(a + b*coth(x)),
        variable=x,
        num_steps=5,
        integral=-a**4*b*log(a + b*coth(x))/(a**2 - b**2)**3 - a*(3*a + b)*log(1 - coth(x))/(16*(a + b)**3) + a*(3*a - b)*log(coth(x) + 1)/(16*(a - b)**3) - (-a*coth(x) + b)*sinh(x)**4/(4*a**2 - 4*b**2) - (-a*(5*a**2 - b**2)*coth(x) + 4*b*(2*a**2 - b**2))*sinh(x)**2/(8*(a**2 - b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**3/(a + b*coth(x)),
        variable=x,
        num_steps=10,
        integral=a**3*b*atanh((a*cosh(x) + b*sinh(x))/sqrt(a**2 - b**2))/(a**2 - b**2)**(sympy.S(5)/2) - a**2*b*cosh(x)/(a**2 - b**2)**2 + a*b**2*sinh(x)/(a**2 - b**2)**2 + a*sinh(x)**3/(3*a**2 - 3*b**2) + a*sinh(x)/(a**2 - b**2) - b*cosh(x)**3/(3*a**2 - 3*b**2),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**2/(a + b*coth(x)),
        variable=x,
        num_steps=4,
        integral=-a**2*b*log(a + b*coth(x))/(a**2 - b**2)**2 - a*log(1 - coth(x))/(4*(a + b)**2) + a*log(coth(x) + 1)/(4*(a - b)**2) - (-a*coth(x) + b)*sinh(x)**2/(2*a**2 - 2*b**2),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)/(a + b*coth(x)),
        variable=x,
        num_steps=6,
        integral=a*b*atanh((a*cosh(x) + b*sinh(x))/sqrt(a**2 - b**2))/(a**2 - b**2)**(sympy.S(3)/2) + a*sinh(x)/(a**2 - b**2) - b*cosh(x)/(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)/(a + b*coth(x)),
        variable=x,
        num_steps=6,
        integral=b*atanh((a*cosh(x) + b*sinh(x))/sqrt(a**2 - b**2))/(a*sqrt(a**2 - b**2)) + atan(sinh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**2/(a + b*coth(x)),
        variable=x,
        num_steps=3,
        integral=tanh(x)/a - b*log(a + b*coth(x))/a**2 - b*log(tanh(x))/a**2,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**3/(a + b*coth(x)),
        variable=x,
        num_steps=9,
        integral=tanh(x)*sech(x)/(2*a) + atan(sinh(x))/(2*a) - b*sech(x)/a**2 - b**2*atan(sinh(x))/a**3 + b*sqrt(a**2 - b**2)*atanh((a*cosh(x) + b*sinh(x))/sqrt(a**2 - b**2))/a**3,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**4/(a + b*coth(x)),
        variable=x,
        num_steps=3,
        integral=-tanh(x)**3/(3*a) + b*tanh(x)**2/(2*a**2) + (a**2 - b**2)*tanh(x)/a**3 - b*(a**2 - b**2)*log(a + b*coth(x))/a**4 - b*(a**2 - b**2)*log(tanh(x))/a**4,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)/(2*coth(x) + I),
        variable=x,
        num_steps=6,
        integral=-I*atan(sinh(x)) - 2*sqrt(5)*atanh(sqrt(5)*(-2*I*sinh(x) + cosh(x))/5)/5,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**4/(coth(x) + 1),
        variable=x,
        num_steps=6,
        integral=5*x/2 - 2*log(cosh(x)) - 5*tanh(x)**3/6 + tanh(x)**2 - 5*tanh(x)/2 + tanh(x)**3/(2*coth(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**3/(coth(x) + 1),
        variable=x,
        num_steps=5,
        integral=-3*x/2 + 2*log(cosh(x)) - tanh(x)**2 + 3*tanh(x)/2 + tanh(x)**2/(2*coth(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**2/(coth(x) + 1),
        variable=x,
        num_steps=4,
        integral=3*x/2 - log(cosh(x)) - 3*tanh(x)/2 + tanh(x)/(2*coth(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/(coth(x) + 1),
        variable=x,
        num_steps=4,
        integral=-x/2 + log(cosh(x)) + 1/(2*coth(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=1/(coth(x) + 1),
        variable=x,
        num_steps=2,
        integral=x/2 - 1/(2*coth(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/(coth(x) + 1),
        variable=x,
        num_steps=2,
        integral=x/2 + 1/(2*coth(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**2/(coth(x) + 1),
        variable=x,
        num_steps=3,
        integral=-x/2 + log(sinh(x)) - 1/(2*coth(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**3/(coth(x) + 1),
        variable=x,
        num_steps=3,
        integral=3*x/2 - log(sinh(x)) - 3*coth(x)/2 + coth(x)**2/(2*coth(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**4/(coth(x) + 1),
        variable=x,
        num_steps=4,
        integral=-3*x/2 + 2*log(sinh(x)) - coth(x)**2 + 3*coth(x)/2 + coth(x)**3/(2*coth(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**(sympy.S(3)/2)*coth(x),
        variable=x,
        num_steps=4,
        integral=-2*(coth(x) + 1)**(sympy.S(3)/2)/3 - 2*sqrt(coth(x) + 1) + 2*sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(coth(x) + 1)*coth(x),
        variable=x,
        num_steps=3,
        integral=-2*sqrt(coth(x) + 1) + sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/sqrt(coth(x) + 1),
        variable=x,
        num_steps=3,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2)/2 + 1/sqrt(coth(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/(coth(x) + 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2)/4 - 1/(2*sqrt(coth(x) + 1)) + 1/(3*(coth(x) + 1)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(coth(x) + 1)**(sympy.S(3)/2)*coth(x)**2,
        variable=x,
        num_steps=4,
        integral=-2*(coth(x) + 1)**(sympy.S(5)/2)/5 - 2*sqrt(coth(x) + 1) + 2*sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(coth(x) + 1)*coth(x)**2,
        variable=x,
        num_steps=3,
        integral=-2*(coth(x) + 1)**(sympy.S(3)/2)/3 + sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**2/sqrt(coth(x) + 1),
        variable=x,
        num_steps=4,
        integral=-2*sqrt(coth(x) + 1) + sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2)/2 - 1/sqrt(coth(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**2/(coth(x) + 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(coth(x) + 1)/2)/4 + 3/(2*sqrt(coth(x) + 1)) - 1/(3*(coth(x) + 1)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**4/(a + b*coth(x)),
        variable=x,
        num_steps=6,
        integral=a*x/(a**2 - b**2) - tanh(x)**3/(3*a) + b*tanh(x)**2/(2*a**2) - (a**2 + b**2)*tanh(x)/a**3 - b**5*log(a*sinh(x) + b*cosh(x))/(a**4*(a**2 - b**2)) - b*(a**2 + b**2)*log(cosh(x))/a**4,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**3/(a + b*coth(x)),
        variable=x,
        num_steps=5,
        integral=-b*x/(a**2 - b**2) - tanh(x)**2/(2*a) + b*tanh(x)/a**2 + b**4*log(a*sinh(x) + b*cosh(x))/(a**3*(a**2 - b**2)) + (a**2 + b**2)*log(cosh(x))/a**3,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**2/(a + b*coth(x)),
        variable=x,
        num_steps=4,
        integral=a*x/(a**2 - b**2) - tanh(x)/a - b**3*log(a*sinh(x) + b*cosh(x))/(a**2*(a**2 - b**2)) - b*log(cosh(x))/a**2,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/(a + b*coth(x)),
        variable=x,
        num_steps=3,
        integral=-b*x/(a**2 - b**2) + b**2*log(a*sinh(x) + b*cosh(x))/(a*(a**2 - b**2)) + log(cosh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*coth(x)),
        variable=x,
        num_steps=2,
        integral=a*x/(a**2 - b**2) - b*log(a*sinh(x) + b*cosh(x))/(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/(a + b*coth(x)),
        variable=x,
        num_steps=2,
        integral=a*log(a*sinh(x) + b*cosh(x))/(a**2 - b**2) - b*x/(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**2/(a + b*coth(x)),
        variable=x,
        num_steps=4,
        integral=a**3*x/(b**2*(a**2 - b**2)) - a**2*log(a*sinh(x) + b*cosh(x))/(b*(a**2 - b**2)) - a*x/b**2 + log(sinh(x))/b,
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**3/(a + b*coth(x)),
        variable=x,
        num_steps=5,
        integral=a**3*log(a + b*coth(x))/(b**2*(a**2 - b**2)) + a*log(sinh(x))/(a**2 - b**2) - b*x/(a**2 - b**2) - coth(x)/b,
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**4/(a + b*coth(x)),
        variable=x,
        num_steps=6,
        integral=-a**4*log(a + b*coth(x))/(b**3*(a**2 - b**2)) + a*x/(a**2 - b**2) + a*coth(x)/b**2 - b*log(sinh(x))/(a**2 - b**2) - coth(x)**2/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**5/(a + b*coth(x)),
        variable=x,
        num_steps=7,
        integral=a**5*log(a + b*coth(x))/(b**4*(a**2 - b**2)) + a*log(sinh(x))/(a**2 - b**2) + a*coth(x)**2/(2*b**2) - b*x/(a**2 - b**2) - coth(x)**3/(3*b) - (a**2 + b**2)*coth(x)/b**3,
    ),
    RubiTestSuiteCase(
        integrand=x*csch(x)**2/(a + b*coth(x))**2,
        variable=x,
        num_steps=3,
        integral=-a*x/(b*(a**2 - b**2)) + log(a*sinh(x) + b*cosh(x))/(a**2 - b**2) + x/(b*(a + b*coth(x))),
    ),
    RubiTestSuiteCase(
        integrand=coth(a + b*log(c*x**n))/x,
        variable=x,
        num_steps=2,
        integral=log(sinh(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=coth(a + b*log(c*x**n))**2/x,
        variable=x,
        num_steps=3,
        integral=log(x) - coth(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=coth(a + b*log(c*x**n))**3/x,
        variable=x,
        num_steps=3,
        integral=log(sinh(a + b*log(c*x**n)))/(b*n) - coth(a + b*log(c*x**n))**2/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=coth(a + b*log(c*x**n))**4/x,
        variable=x,
        num_steps=4,
        integral=log(x) - coth(a + b*log(c*x**n))**3/(3*b*n) - coth(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=coth(a + b*log(c*x**n))**5/x,
        variable=x,
        num_steps=4,
        integral=log(sinh(a + b*log(c*x**n)))/(b*n) - coth(a + b*log(c*x**n))**4/(4*b*n) - coth(a + b*log(c*x**n))**2/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=coth(a + b*log(c*x**n))**(sympy.S(5)/2)/x,
        variable=x,
        num_steps=7,
        integral=-2*coth(a + b*log(c*x**n))**(sympy.S(3)/2)/(3*b*n) - atan(sqrt(coth(a + b*log(c*x**n))))/(b*n) + atanh(sqrt(coth(a + b*log(c*x**n))))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=coth(a + b*log(c*x**n))**(sympy.S(3)/2)/x,
        variable=x,
        num_steps=7,
        integral=-2*sqrt(coth(a + b*log(c*x**n)))/(b*n) + atan(sqrt(coth(a + b*log(c*x**n))))/(b*n) + atanh(sqrt(coth(a + b*log(c*x**n))))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(coth(a + b*log(c*x**n)))/x,
        variable=x,
        num_steps=6,
        integral=-atan(sqrt(coth(a + b*log(c*x**n))))/(b*n) + atanh(sqrt(coth(a + b*log(c*x**n))))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(coth(a + b*log(c*x**n)))),
        variable=x,
        num_steps=6,
        integral=atan(sqrt(coth(a + b*log(c*x**n))))/(b*n) + atanh(sqrt(coth(a + b*log(c*x**n))))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*coth(a + b*log(c*x**n))**(sympy.S(3)/2)),
        variable=x,
        num_steps=7,
        integral=-atan(sqrt(coth(a + b*log(c*x**n))))/(b*n) + atanh(sqrt(coth(a + b*log(c*x**n))))/(b*n) - 2/(b*n*sqrt(coth(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*coth(a + b*log(c*x**n))**(sympy.S(5)/2)),
        variable=x,
        num_steps=7,
        integral=atan(sqrt(coth(a + b*log(c*x**n))))/(b*n) + atanh(sqrt(coth(a + b*log(c*x**n))))/(b*n) - 2/(3*b*n*coth(a + b*log(c*x**n))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**5/sqrt(a + b*coth(x)**2 + c*coth(x)**4),
        variable=x,
        num_steps=8,
        integral=atanh((2*a + b + (b + 2*c)*coth(x)**2)/(2*sqrt(a + b + c)*sqrt(a + b*coth(x)**2 + c*coth(x)**4)))/(2*sqrt(a + b + c)) - sqrt(a + b*coth(x)**2 + c*coth(x)**4)/(2*c) + (b - 2*c)*atanh((b + 2*c*coth(x)**2)/(2*sqrt(c)*sqrt(a + b*coth(x)**2 + c*coth(x)**4)))/(4*c**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**3/sqrt(a + b*coth(x)**2 + c*coth(x)**4),
        variable=x,
        num_steps=7,
        integral=atanh((2*a + b + (b + 2*c)*coth(x)**2)/(2*sqrt(a + b + c)*sqrt(a + b*coth(x)**2 + c*coth(x)**4)))/(2*sqrt(a + b + c)) - atanh((b + 2*c*coth(x)**2)/(2*sqrt(c)*sqrt(a + b*coth(x)**2 + c*coth(x)**4)))/(2*sqrt(c)),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/sqrt(a + b*coth(x)**2 + c*coth(x)**4),
        variable=x,
        num_steps=4,
        integral=atanh((2*a + b + (b + 2*c)*coth(x)**2)/(2*sqrt(a + b + c)*sqrt(a + b*coth(x)**2 + c*coth(x)**4)))/(2*sqrt(a + b + c)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/sqrt(a + b*coth(x)**2 + c*coth(x)**4),
        variable=x,
        num_steps=8,
        integral=atanh((2*a + b + (b + 2*c)*coth(x)**2)/(2*sqrt(a + b + c)*sqrt(a + b*coth(x)**2 + c*coth(x)**4)))/(2*sqrt(a + b + c)) - atanh((2*a + b*coth(x)**2)/(2*sqrt(a)*sqrt(a + b*coth(x)**2 + c*coth(x)**4)))/(2*sqrt(a)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**3/sqrt(a + b*coth(x)**2 + c*coth(x)**4),
        variable=x,
        num_steps=11,
        integral=atanh((2*a + b + (b + 2*c)*coth(x)**2)/(2*sqrt(a + b + c)*sqrt(a + b*coth(x)**2 + c*coth(x)**4)))/(2*sqrt(a + b + c)) - sqrt(a + b*coth(x)**2 + c*coth(x)**4)*tanh(x)**2/(2*a) - atanh((2*a + b*coth(x)**2)/(2*sqrt(a)*sqrt(a + b*coth(x)**2 + c*coth(x)**4)))/(2*sqrt(a)) + b*atanh((2*a + b*coth(x)**2)/(2*sqrt(a)*sqrt(a + b*coth(x)**2 + c*coth(x)**4)))/(4*a**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*coth(x)**2 + c*coth(x)**4)*coth(x),
        variable=x,
        num_steps=8,
        integral=sqrt(a + b + c)*atanh((2*a + b + (b + 2*c)*coth(x)**2)/(2*sqrt(a + b + c)*sqrt(a + b*coth(x)**2 + c*coth(x)**4)))/2 - sqrt(a + b*coth(x)**2 + c*coth(x)**4)/2 - (b + 2*c)*atanh((b + 2*c*coth(x)**2)/(2*sqrt(c)*sqrt(a + b*coth(x)**2 + c*coth(x)**4)))/(4*sqrt(c)),
    ),
    RubiTestSuiteCase(
        integrand=(coth(a*c + b*c*x)**2)**(sympy.S(5)/2)*exp(c*(a + b*x)),
        variable=x,
        num_steps=9,
        integral=sqrt(coth(a*c + b*c*x)**2)*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(b*c) - 15*sqrt(coth(a*c + b*c*x)**2)*tanh(a*c + b*c*x)*atanh(exp(c*(a + b*x)))/(4*b*c) + 25*sqrt(coth(a*c + b*c*x)**2)*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(4*b*c*(1 - exp(2*c*(a + b*x)))) - 55*sqrt(coth(a*c + b*c*x)**2)*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(6*b*c*(1 - exp(2*c*(a + b*x)))**2) + 26*sqrt(coth(a*c + b*c*x)**2)*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(3*b*c*(1 - exp(2*c*(a + b*x)))**3) - 4*sqrt(coth(a*c + b*c*x)**2)*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(b*c*(1 - exp(2*c*(a + b*x)))**4),
    ),
    RubiTestSuiteCase(
        integrand=(coth(a*c + b*c*x)**2)**(sympy.S(3)/2)*exp(c*(a + b*x)),
        variable=x,
        num_steps=8,
        integral=sqrt(coth(a*c + b*c*x)**2)*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(b*c) - 3*sqrt(coth(a*c + b*c*x)**2)*tanh(a*c + b*c*x)*atanh(exp(c*(a + b*x)))/(b*c) + 3*sqrt(coth(a*c + b*c*x)**2)*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(b*c*(1 - exp(2*c*(a + b*x)))) - 2*sqrt(coth(a*c + b*c*x)**2)*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(b*c*(1 - exp(2*c*(a + b*x)))**2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(coth(a*c + b*c*x)**2)*exp(c*(a + b*x)),
        variable=x,
        num_steps=4,
        integral=sqrt(coth(a*c + b*c*x)**2)*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(b*c) - 2*sqrt(coth(a*c + b*c*x)**2)*tanh(a*c + b*c*x)*atanh(exp(c*(a + b*x)))/(b*c),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))/sqrt(coth(a*c + b*c*x)**2),
        variable=x,
        num_steps=4,
        integral=exp(c*(a + b*x))*coth(a*c + b*c*x)/(b*c*sqrt(coth(a*c + b*c*x)**2)) - 2*coth(a*c + b*c*x)*atan(exp(c*(a + b*x)))/(b*c*sqrt(coth(a*c + b*c*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))/(coth(a*c + b*c*x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=8,
        integral=exp(c*(a + b*x))*coth(a*c + b*c*x)/(b*c*sqrt(coth(a*c + b*c*x)**2)) - 3*coth(a*c + b*c*x)*atan(exp(c*(a + b*x)))/(b*c*sqrt(coth(a*c + b*c*x)**2)) + 3*exp(c*(a + b*x))*coth(a*c + b*c*x)/(b*c*(exp(2*c*(a + b*x)) + 1)*sqrt(coth(a*c + b*c*x)**2)) - 2*exp(c*(a + b*x))*coth(a*c + b*c*x)/(b*c*(exp(2*c*(a + b*x)) + 1)**2*sqrt(coth(a*c + b*c*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))/(coth(a*c + b*c*x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=9,
        integral=exp(c*(a + b*x))*coth(a*c + b*c*x)/(b*c*sqrt(coth(a*c + b*c*x)**2)) - 15*coth(a*c + b*c*x)*atan(exp(c*(a + b*x)))/(4*b*c*sqrt(coth(a*c + b*c*x)**2)) + 25*exp(c*(a + b*x))*coth(a*c + b*c*x)/(4*b*c*(exp(2*c*(a + b*x)) + 1)*sqrt(coth(a*c + b*c*x)**2)) - 55*exp(c*(a + b*x))*coth(a*c + b*c*x)/(6*b*c*(exp(2*c*(a + b*x)) + 1)**2*sqrt(coth(a*c + b*c*x)**2)) + 26*exp(c*(a + b*x))*coth(a*c + b*c*x)/(3*b*c*(exp(2*c*(a + b*x)) + 1)**3*sqrt(coth(a*c + b*c*x)**2)) - 4*exp(c*(a + b*x))*coth(a*c + b*c*x)/(b*c*(exp(2*c*(a + b*x)) + 1)**4*sqrt(coth(a*c + b*c*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(coth(a + b*x))**3,
        variable=x,
        num_steps=19,
        integral=((Integer(-1) * ((Integer(3) * sympy.Function('CosIntegral')((Integer(1) + (Integer(-1) * sympy.coth((Symbol('a') + (Symbol('b') * x)))))) * sympy.sin(Integer(1))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * sympy.Function('CosIntegral')((Integer(1) + sympy.coth((Symbol('a') + (Symbol('b') * x))))) * sympy.sin(Integer(1))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))) + ((sympy.Function('CosIntegral')((Integer(3) + (Integer(-1) * (Integer(3) * sympy.coth((Symbol('a') + (Symbol('b') * x))))))) * sympy.sin(Integer(3))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + ((sympy.Function('CosIntegral')((Integer(3) + (Integer(3) * sympy.coth((Symbol('a') + (Symbol('b') * x)))))) * sympy.sin(Integer(3))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.cos(Integer(3)) * sympy.Function('SinIntegral')((Integer(3) + (Integer(-1) * (Integer(3) * sympy.coth((Symbol('a') + (Symbol('b') * x)))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))) + ((Integer(3) * sympy.cos(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + (Integer(-1) * sympy.coth((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + ((Integer(3) * sympy.cos(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + sympy.coth((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.cos(Integer(3)) * sympy.Function('SinIntegral')((Integer(3) + (Integer(3) * sympy.coth((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=sin(coth(a + b*x))**2,
        variable=x,
        num_steps=13,
        integral=(((sympy.cos(Integer(2)) * sympy.Function('CosIntegral')((Integer(2) + (Integer(-1) * (Integer(2) * sympy.coth((Symbol('a') + (Symbol('b') * x)))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.cos(Integer(2)) * sympy.Function('CosIntegral')((Integer(2) + (Integer(2) * sympy.coth((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1)))) + (Integer(-1) * (sympy.log((Integer(1) + (Integer(-1) * sympy.coth((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(4) * Symbol('b')))**(Integer(-1)))) + (sympy.log((Integer(1) + sympy.coth((Symbol('a') + (Symbol('b') * x))))) * ((Integer(4) * Symbol('b')))**(Integer(-1))) + ((sympy.sin(Integer(2)) * sympy.Function('SinIntegral')((Integer(2) + (Integer(-1) * (Integer(2) * sympy.coth((Symbol('a') + (Symbol('b') * x)))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.sin(Integer(2)) * sympy.Function('SinIntegral')((Integer(2) + (Integer(2) * sympy.coth((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=sin(coth(a + b*x)),
        variable=x,
        num_steps=9,
        integral=((Integer(-1) * ((sympy.Function('CosIntegral')((Integer(1) + (Integer(-1) * sympy.coth((Symbol('a') + (Symbol('b') * x)))))) * sympy.sin(Integer(1))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))) + (Integer(-1) * ((sympy.Function('CosIntegral')((Integer(1) + sympy.coth((Symbol('a') + (Symbol('b') * x))))) * sympy.sin(Integer(1))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))) + ((sympy.cos(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + (Integer(-1) * sympy.coth((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(2) * Symbol('b')))**(Integer(-1))) + ((sympy.cos(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + sympy.coth((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=csc(coth(a + b*x)),
        variable=x,
        num_steps=3,
        integral=(((Integer(2))**(Integer(-1)) * sympy.Function('Unintegrable')(((sympy.csc(sympy.coth((Symbol('a') + (Symbol('b') * x)))) * (sympy.csch((Symbol('a') + (Symbol('b') * x))))**(Integer(2))) * ((Integer(-1) + sympy.coth((Symbol('a') + (Symbol('b') * x)))))**(Integer(-1))), x)) + (Integer(-1) * ((Integer(2))**(Integer(-1)) * sympy.Function('Unintegrable')(((sympy.csc(sympy.coth((Symbol('a') + (Symbol('b') * x)))) * (sympy.csch((Symbol('a') + (Symbol('b') * x))))**(Integer(2))) * ((Integer(1) + sympy.coth((Symbol('a') + (Symbol('b') * x)))))**(Integer(-1))), x)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(coth(a + b*x))**3,
        variable=x,
        num_steps=19,
        integral=((Integer(-1) * ((sympy.cos(Integer(3)) * sympy.Function('CosIntegral')((Integer(3) + (Integer(-1) * (Integer(3) * sympy.coth((Symbol('a') + (Symbol('b') * x)))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * sympy.cos(Integer(1)) * sympy.Function('CosIntegral')((Integer(1) + (Integer(-1) * sympy.coth((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))) + ((Integer(3) * sympy.cos(Integer(1)) * sympy.Function('CosIntegral')((Integer(1) + sympy.coth((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + ((sympy.cos(Integer(3)) * sympy.Function('CosIntegral')((Integer(3) + (Integer(3) * sympy.coth((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.sin(Integer(3)) * sympy.Function('SinIntegral')((Integer(3) + (Integer(-1) * (Integer(3) * sympy.coth((Symbol('a') + (Symbol('b') * x)))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * sympy.sin(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + (Integer(-1) * sympy.coth((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))) + ((Integer(3) * sympy.sin(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + sympy.coth((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + ((sympy.sin(Integer(3)) * sympy.Function('SinIntegral')((Integer(3) + (Integer(3) * sympy.coth((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(coth(a + b*x))**2,
        variable=x,
        num_steps=13,
        integral=((Integer(-1) * ((sympy.cos(Integer(2)) * sympy.Function('CosIntegral')((Integer(2) + (Integer(-1) * (Integer(2) * sympy.coth((Symbol('a') + (Symbol('b') * x)))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1)))) + ((sympy.cos(Integer(2)) * sympy.Function('CosIntegral')((Integer(2) + (Integer(2) * sympy.coth((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * (sympy.log((Integer(1) + (Integer(-1) * sympy.coth((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(4) * Symbol('b')))**(Integer(-1)))) + (sympy.log((Integer(1) + sympy.coth((Symbol('a') + (Symbol('b') * x))))) * ((Integer(4) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.sin(Integer(2)) * sympy.Function('SinIntegral')((Integer(2) + (Integer(-1) * (Integer(2) * sympy.coth((Symbol('a') + (Symbol('b') * x)))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1)))) + ((sympy.sin(Integer(2)) * sympy.Function('SinIntegral')((Integer(2) + (Integer(2) * sympy.coth((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(coth(a + b*x)),
        variable=x,
        num_steps=9,
        integral=((Integer(-1) * ((sympy.cos(Integer(1)) * sympy.Function('CosIntegral')((Integer(1) + (Integer(-1) * sympy.coth((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))) + ((sympy.cos(Integer(1)) * sympy.Function('CosIntegral')((Integer(1) + sympy.coth((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(2) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.sin(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + (Integer(-1) * sympy.coth((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))) + ((sympy.sin(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + sympy.coth((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=sec(coth(a + b*x)),
        variable=x,
        num_steps=3,
        integral=(((Integer(2))**(Integer(-1)) * sympy.Function('Unintegrable')((((sympy.csch((Symbol('a') + (Symbol('b') * x))))**(Integer(2)) * sympy.sec(sympy.coth((Symbol('a') + (Symbol('b') * x))))) * ((Integer(-1) + sympy.coth((Symbol('a') + (Symbol('b') * x)))))**(Integer(-1))), x)) + (Integer(-1) * ((Integer(2))**(Integer(-1)) * sympy.Function('Unintegrable')((((sympy.csch((Symbol('a') + (Symbol('b') * x))))**(Integer(2)) * sympy.sec(sympy.coth((Symbol('a') + (Symbol('b') * x))))) * ((Integer(1) + sympy.coth((Symbol('a') + (Symbol('b') * x)))))**(Integer(-1))), x)))),
    ),
]
