# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 4 Trig functions/4.5 Secant/4.5.0 (a sec)^m (b trg)^n.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '4 Trig functions/4.5 Secant/4.5.0 (a sec)^m (b trg)^n.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, c, d, e, f, m, n, p = symbols('a b c d e f m n p')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=sec(a + b*x),
        variable=x,
        num_steps=1,
        integral=atanh(sin(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**2,
        variable=x,
        num_steps=2,
        integral=tan(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**3,
        variable=x,
        num_steps=2,
        integral=tan(a + b*x)*sec(a + b*x)/(2*b) + atanh(sin(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**4,
        variable=x,
        num_steps=2,
        integral=tan(a + b*x)**3/(3*b) + tan(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**5,
        variable=x,
        num_steps=3,
        integral=tan(a + b*x)*sec(a + b*x)**3/(4*b) + 3*tan(a + b*x)*sec(a + b*x)/(8*b) + 3*atanh(sin(a + b*x))/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**6,
        variable=x,
        num_steps=2,
        integral=tan(a + b*x)**5/(5*b) + 2*tan(a + b*x)**3/(3*b) + tan(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**7,
        variable=x,
        num_steps=4,
        integral=tan(a + b*x)*sec(a + b*x)**5/(6*b) + 5*tan(a + b*x)*sec(a + b*x)**3/(24*b) + 5*tan(a + b*x)*sec(a + b*x)/(16*b) + 5*atanh(sin(a + b*x))/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**8,
        variable=x,
        num_steps=2,
        integral=tan(a + b*x)**7/(7*b) + 3*tan(a + b*x)**5/(5*b) + tan(a + b*x)**3/b + tan(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=4,
        integral=2*sin(a + b*x)*sec(a + b*x)**(sympy.S(5)/2)/(5*b) + 6*sin(a + b*x)*sqrt(sec(a + b*x))/(5*b) - 6*sqrt(cos(a + b*x))*elliptic_e(a/2 + b*x/2, 2)*sqrt(sec(a + b*x))/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*sin(a + b*x)*sec(a + b*x)**(sympy.S(3)/2)/(3*b) + 2*sqrt(cos(a + b*x))*elliptic_f(a/2 + b*x/2, 2)*sqrt(sec(a + b*x))/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*sin(a + b*x)*sqrt(sec(a + b*x))/b - 2*sqrt(cos(a + b*x))*elliptic_e(a/2 + b*x/2, 2)*sqrt(sec(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sec(a + b*x)),
        variable=x,
        num_steps=2,
        integral=2*sqrt(cos(a + b*x))*elliptic_f(a/2 + b*x/2, 2)*sqrt(sec(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(sec(a + b*x)),
        variable=x,
        num_steps=2,
        integral=2*sqrt(cos(a + b*x))*elliptic_e(a/2 + b*x/2, 2)*sqrt(sec(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*sin(a + b*x)/(3*b*sqrt(sec(a + b*x))) + 2*sqrt(cos(a + b*x))*elliptic_f(a/2 + b*x/2, 2)*sqrt(sec(a + b*x))/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**(sympy.S(-5)/2),
        variable=x,
        num_steps=3,
        integral=2*sin(a + b*x)/(5*b*sec(a + b*x)**(sympy.S(3)/2)) + 6*sqrt(cos(a + b*x))*elliptic_e(a/2 + b*x/2, 2)*sqrt(sec(a + b*x))/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**(sympy.S(-7)/2),
        variable=x,
        num_steps=4,
        integral=10*sin(a + b*x)/(21*b*sqrt(sec(a + b*x))) + 2*sin(a + b*x)/(7*b*sec(a + b*x)**(sympy.S(5)/2)) + 10*sqrt(cos(a + b*x))*elliptic_f(a/2 + b*x/2, 2)*sqrt(sec(a + b*x))/(21*b),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=4,
        integral=-6*c**4*elliptic_e(a/2 + b*x/2, 2)/(5*b*sqrt(c*sec(a + b*x))*sqrt(cos(a + b*x))) + 6*c**3*sqrt(c*sec(a + b*x))*sin(a + b*x)/(5*b) + 2*c*(c*sec(a + b*x))**(sympy.S(5)/2)*sin(a + b*x)/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*c**2*sqrt(c*sec(a + b*x))*sqrt(cos(a + b*x))*elliptic_f(a/2 + b*x/2, 2)/(3*b) + 2*c*(c*sec(a + b*x))**(sympy.S(3)/2)*sin(a + b*x)/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-2*c**2*elliptic_e(a/2 + b*x/2, 2)/(b*sqrt(c*sec(a + b*x))*sqrt(cos(a + b*x))) + 2*c*sqrt(c*sec(a + b*x))*sin(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(c*sec(a + b*x)),
        variable=x,
        num_steps=2,
        integral=2*sqrt(c*sec(a + b*x))*sqrt(cos(a + b*x))*elliptic_f(a/2 + b*x/2, 2)/b,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(c*sec(a + b*x)),
        variable=x,
        num_steps=2,
        integral=2*elliptic_e(a/2 + b*x/2, 2)/(b*sqrt(c*sec(a + b*x))*sqrt(cos(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*sin(a + b*x)/(3*b*c*sqrt(c*sec(a + b*x))) + 2*sqrt(c*sec(a + b*x))*sqrt(cos(a + b*x))*elliptic_f(a/2 + b*x/2, 2)/(3*b*c**2),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(-5)/2),
        variable=x,
        num_steps=3,
        integral=2*sin(a + b*x)/(5*b*c*(c*sec(a + b*x))**(sympy.S(3)/2)) + 6*elliptic_e(a/2 + b*x/2, 2)/(5*b*c**2*sqrt(c*sec(a + b*x))*sqrt(cos(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(-7)/2),
        variable=x,
        num_steps=4,
        integral=2*sin(a + b*x)/(7*b*c*(c*sec(a + b*x))**(sympy.S(5)/2)) + 10*sin(a + b*x)/(21*b*c**3*sqrt(c*sec(a + b*x))) + 10*sqrt(c*sec(a + b*x))*sqrt(cos(a + b*x))*elliptic_f(a/2 + b*x/2, 2)/(21*b*c**4),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**(sympy.S(4)/3),
        variable=x,
        num_steps=2,
        integral=3*sin(a + b*x)*hyper((sympy.S(-1)/6, sympy.S.Half), (sympy.S(5)/6,), cos(a + b*x)**2)*sec(a + b*x)**(sympy.S(1)/3)/(b*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**(sympy.S(2)/3),
        variable=x,
        num_steps=2,
        integral=-3*sin(a + b*x)*hyper((sympy.S(1)/6, sympy.S.Half), (sympy.S(7)/6,), cos(a + b*x)**2)/(b*sqrt(sin(a + b*x)**2)*sec(a + b*x)**(sympy.S(1)/3)),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**(sympy.S(1)/3),
        variable=x,
        num_steps=2,
        integral=-3*sin(a + b*x)*hyper((sympy.S(1)/3, sympy.S.Half), (sympy.S(4)/3,), cos(a + b*x)**2)/(2*b*sqrt(sin(a + b*x)**2)*sec(a + b*x)**(sympy.S(2)/3)),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**(sympy.S(-1)/3),
        variable=x,
        num_steps=2,
        integral=-3*sin(a + b*x)*hyper((sympy.S.Half, sympy.S(2)/3), (sympy.S(5)/3,), cos(a + b*x)**2)/(4*b*sqrt(sin(a + b*x)**2)*sec(a + b*x)**(sympy.S(4)/3)),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**(sympy.S(-2)/3),
        variable=x,
        num_steps=2,
        integral=-3*sin(a + b*x)*hyper((sympy.S.Half, sympy.S(5)/6), (sympy.S(11)/6,), cos(a + b*x)**2)/(5*b*sqrt(sin(a + b*x)**2)*sec(a + b*x)**(sympy.S(5)/3)),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**(sympy.S(-4)/3),
        variable=x,
        num_steps=2,
        integral=-3*sin(a + b*x)*hyper((sympy.S.Half, sympy.S(7)/6), (sympy.S(13)/6,), cos(a + b*x)**2)/(7*b*sqrt(sin(a + b*x)**2)*sec(a + b*x)**(sympy.S(7)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=2,
        integral=3*c*(c*sec(a + b*x))**(sympy.S(1)/3)*sin(a + b*x)*hyper((sympy.S(-1)/6, sympy.S.Half), (sympy.S(5)/6,), cos(a + b*x)**2)/(b*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(2)/3),
        variable=x,
        num_steps=2,
        integral=-3*c*sin(a + b*x)*hyper((sympy.S(1)/6, sympy.S.Half), (sympy.S(7)/6,), cos(a + b*x)**2)/(b*(c*sec(a + b*x))**(sympy.S(1)/3)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=2,
        integral=-3*c*sin(a + b*x)*hyper((sympy.S(1)/3, sympy.S.Half), (sympy.S(4)/3,), cos(a + b*x)**2)/(2*b*(c*sec(a + b*x))**(sympy.S(2)/3)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(-1)/3),
        variable=x,
        num_steps=2,
        integral=-3*c*sin(a + b*x)*hyper((sympy.S.Half, sympy.S(2)/3), (sympy.S(5)/3,), cos(a + b*x)**2)/(4*b*(c*sec(a + b*x))**(sympy.S(4)/3)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(-2)/3),
        variable=x,
        num_steps=2,
        integral=-3*c*sin(a + b*x)*hyper((sympy.S.Half, sympy.S(5)/6), (sympy.S(11)/6,), cos(a + b*x)**2)/(5*b*(c*sec(a + b*x))**(sympy.S(5)/3)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(-4)/3),
        variable=x,
        num_steps=2,
        integral=-3*c*sin(a + b*x)*hyper((sympy.S.Half, sympy.S(7)/6), (sympy.S(13)/6,), cos(a + b*x)**2)/(7*b*(c*sec(a + b*x))**(sympy.S(7)/3)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**n,
        variable=x,
        num_steps=2,
        integral=-sin(a + b*x)*hyper((sympy.S.Half, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), cos(a + b*x)**2)*sec(a + b*x)**(n - 1)/(b*(1 - n)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**n,
        variable=x,
        num_steps=2,
        integral=-c*(c*sec(a + b*x))**(n - 1)*sin(a + b*x)*hyper((sympy.S.Half, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), cos(a + b*x)**2)/(b*(1 - n)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(sec(x)**2)**(sympy.S(7)/2),
        variable=x,
        num_steps=5,
        integral=(sec(x)**2)**(sympy.S(5)/2)*tan(x)/6 + 5*(sec(x)**2)**(sympy.S(3)/2)*tan(x)/24 + 5*sqrt(sec(x)**2)*tan(x)/16 + 5*asinh(tan(x))/16,
    ),
    RubiTestSuiteCase(
        integrand=(sec(x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=(sec(x)**2)**(sympy.S(3)/2)*tan(x)/4 + 3*sqrt(sec(x)**2)*tan(x)/8 + 3*asinh(tan(x))/8,
    ),
    RubiTestSuiteCase(
        integrand=(sec(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=sqrt(sec(x)**2)*tan(x)/2 + asinh(tan(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sec(x)**2),
        variable=x,
        num_steps=2,
        integral=asinh(tan(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(sec(x)**2),
        variable=x,
        num_steps=2,
        integral=tan(x)/sqrt(sec(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=(sec(x)**2)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*tan(x)/(3*sqrt(sec(x)**2)) + tan(x)/(3*(sec(x)**2)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(sec(x)**2)**(sympy.S(-5)/2),
        variable=x,
        num_steps=4,
        integral=8*tan(x)/(15*sqrt(sec(x)**2)) + 4*tan(x)/(15*(sec(x)**2)**(sympy.S(3)/2)) + tan(x)/(5*(sec(x)**2)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(sec(x)**2)**(sympy.S(-7)/2),
        variable=x,
        num_steps=5,
        integral=16*tan(x)/(35*sqrt(sec(x)**2)) + 8*tan(x)/(35*(sec(x)**2)**(sympy.S(3)/2)) + 6*tan(x)/(35*(sec(x)**2)**(sympy.S(5)/2)) + tan(x)/(7*(sec(x)**2)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**2)**(sympy.S(7)/2),
        variable=x,
        num_steps=6,
        integral=5*a**(sympy.S(7)/2)*atanh(sqrt(a)*tan(x)/sqrt(a*sec(x)**2))/16 + 5*a**3*sqrt(a*sec(x)**2)*tan(x)/16 + 5*a**2*(a*sec(x)**2)**(sympy.S(3)/2)*tan(x)/24 + a*(a*sec(x)**2)**(sympy.S(5)/2)*tan(x)/6,
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=3*a**(sympy.S(5)/2)*atanh(sqrt(a)*tan(x)/sqrt(a*sec(x)**2))/8 + 3*a**2*sqrt(a*sec(x)**2)*tan(x)/8 + a*(a*sec(x)**2)**(sympy.S(3)/2)*tan(x)/4,
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=a**(sympy.S(3)/2)*atanh(sqrt(a)*tan(x)/sqrt(a*sec(x)**2))/2 + a*sqrt(a*sec(x)**2)*tan(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*sec(x)**2),
        variable=x,
        num_steps=3,
        integral=sqrt(a)*atanh(sqrt(a)*tan(x)/sqrt(a*sec(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*sec(x)**2),
        variable=x,
        num_steps=2,
        integral=tan(x)/sqrt(a*sec(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**2)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=tan(x)/(3*(a*sec(x)**2)**(sympy.S(3)/2)) + 2*tan(x)/(3*a*sqrt(a*sec(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**2)**(sympy.S(-5)/2),
        variable=x,
        num_steps=4,
        integral=tan(x)/(5*(a*sec(x)**2)**(sympy.S(5)/2)) + 4*tan(x)/(15*a*(a*sec(x)**2)**(sympy.S(3)/2)) + 8*tan(x)/(15*a**2*sqrt(a*sec(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**2)**(sympy.S(-7)/2),
        variable=x,
        num_steps=5,
        integral=tan(x)/(7*(a*sec(x)**2)**(sympy.S(7)/2)) + 6*tan(x)/(35*a*(a*sec(x)**2)**(sympy.S(5)/2)) + 8*tan(x)/(35*a**2*(a*sec(x)**2)**(sympy.S(3)/2)) + 16*tan(x)/(35*a**3*sqrt(a*sec(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**3)**(sympy.S(5)/2),
        variable=x,
        num_steps=7,
        integral=154*a**2*sqrt(a*sec(x)**3)*sin(x)*cos(x)/195 - 154*a**2*sqrt(a*sec(x)**3)*cos(x)**(sympy.S(3)/2)*elliptic_e(x/2, 2)/195 + 2*a**2*sqrt(a*sec(x)**3)*tan(x)*sec(x)**4/13 + 22*a**2*sqrt(a*sec(x)**3)*tan(x)*sec(x)**2/117 + 154*a**2*sqrt(a*sec(x)**3)*tan(x)/585,
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**3)**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=10*a*sqrt(a*sec(x)**3)*sin(x)/21 + 10*a*sqrt(a*sec(x)**3)*cos(x)**(sympy.S(3)/2)*elliptic_f(x/2, 2)/21 + 2*a*sqrt(a*sec(x)**3)*tan(x)*sec(x)/7,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*sec(x)**3),
        variable=x,
        num_steps=4,
        integral=2*sqrt(a*sec(x)**3)*sin(x)*cos(x) - 2*sqrt(a*sec(x)**3)*cos(x)**(sympy.S(3)/2)*elliptic_e(x/2, 2),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*sec(x)**3),
        variable=x,
        num_steps=4,
        integral=2*tan(x)/(3*sqrt(a*sec(x)**3)) + 2*elliptic_f(x/2, 2)/(3*sqrt(a*sec(x)**3)*cos(x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**3)**(sympy.S(-3)/2),
        variable=x,
        num_steps=5,
        integral=2*sin(x)*cos(x)**2/(9*a*sqrt(a*sec(x)**3)) + 14*sin(x)/(45*a*sqrt(a*sec(x)**3)) + 14*elliptic_e(x/2, 2)/(15*a*sqrt(a*sec(x)**3)*cos(x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**3)**(sympy.S(-5)/2),
        variable=x,
        num_steps=7,
        integral=2*sin(x)*cos(x)**5/(15*a**2*sqrt(a*sec(x)**3)) + 26*sin(x)*cos(x)**3/(165*a**2*sqrt(a*sec(x)**3)) + 78*sin(x)*cos(x)/(385*a**2*sqrt(a*sec(x)**3)) + 26*tan(x)/(77*a**2*sqrt(a*sec(x)**3)) + 26*elliptic_f(x/2, 2)/(77*a**2*sqrt(a*sec(x)**3)*cos(x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**4)**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=a**3*sqrt(a*sec(x)**4)*sin(x)**2*tan(x)**11/13 + 6*a**3*sqrt(a*sec(x)**4)*sin(x)**2*tan(x)**9/11 + 5*a**3*sqrt(a*sec(x)**4)*sin(x)**2*tan(x)**7/3 + 20*a**3*sqrt(a*sec(x)**4)*sin(x)**2*tan(x)**5/7 + 3*a**3*sqrt(a*sec(x)**4)*sin(x)**2*tan(x)**3 + 2*a**3*sqrt(a*sec(x)**4)*sin(x)**2*tan(x) + a**3*sqrt(a*sec(x)**4)*sin(x)*cos(x),
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**4)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=a**2*sqrt(a*sec(x)**4)*sin(x)**2*tan(x)**7/9 + 4*a**2*sqrt(a*sec(x)**4)*sin(x)**2*tan(x)**5/7 + 6*a**2*sqrt(a*sec(x)**4)*sin(x)**2*tan(x)**3/5 + 4*a**2*sqrt(a*sec(x)**4)*sin(x)**2*tan(x)/3 + a**2*sqrt(a*sec(x)**4)*sin(x)*cos(x),
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**4)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=a*sqrt(a*sec(x)**4)*sin(x)**2*tan(x)**3/5 + 2*a*sqrt(a*sec(x)**4)*sin(x)**2*tan(x)/3 + a*sqrt(a*sec(x)**4)*sin(x)*cos(x),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*sec(x)**4),
        variable=x,
        num_steps=3,
        integral=sqrt(a*sec(x)**4)*sin(x)*cos(x),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*sec(x)**4),
        variable=x,
        num_steps=3,
        integral=x*sec(x)**2/(2*sqrt(a*sec(x)**4)) + tan(x)/(2*sqrt(a*sec(x)**4)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**4)**(sympy.S(-3)/2),
        variable=x,
        num_steps=5,
        integral=5*x*sec(x)**2/(16*a*sqrt(a*sec(x)**4)) + sin(x)*cos(x)**3/(6*a*sqrt(a*sec(x)**4)) + 5*sin(x)*cos(x)/(24*a*sqrt(a*sec(x)**4)) + 5*tan(x)/(16*a*sqrt(a*sec(x)**4)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(x)**4)**(sympy.S(-5)/2),
        variable=x,
        num_steps=7,
        integral=63*x*sec(x)**2/(256*a**2*sqrt(a*sec(x)**4)) + sin(x)*cos(x)**7/(10*a**2*sqrt(a*sec(x)**4)) + 9*sin(x)*cos(x)**5/(80*a**2*sqrt(a*sec(x)**4)) + 21*sin(x)*cos(x)**3/(160*a**2*sqrt(a*sec(x)**4)) + 21*sin(x)*cos(x)/(128*a**2*sqrt(a*sec(x)**4)) + 63*tan(x)/(256*a**2*sqrt(a*sec(x)**4)),
    ),
    RubiTestSuiteCase(
        integrand=((b*sec(c + d*x))**p)**n,
        variable=x,
        num_steps=3,
        integral=-((b*sec(c + d*x))**p)**n*sin(c + d*x)*cos(c + d*x)*hyper((sympy.S.Half, -n*p/2 + sympy.S.Half), (-n*p/2 + sympy.S(3)/2,), cos(c + d*x)**2)/(d*(-n*p + 1)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*(b*sec(c + d*x))**p)**n,
        variable=x,
        num_steps=3,
        integral=-(a*(b*sec(c + d*x))**p)**n*sin(c + d*x)*cos(c + d*x)*hyper((sympy.S.Half, -n*p/2 + sympy.S.Half), (-n*p/2 + sympy.S(3)/2,), cos(c + d*x)**2)/(d*(-n*p + 1)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))*sec(c + d*x)**4,
        variable=x,
        num_steps=5,
        integral=10*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d) + 10*(b*sec(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(21*b*d) + 2*(b*sec(c + d*x))**(sympy.S(7)/2)*sin(c + d*x)/(7*b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))*sec(c + d*x)**3,
        variable=x,
        num_steps=5,
        integral=-6*b*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))) + 6*sqrt(b*sec(c + d*x))*sin(c + d*x)/(5*d) + 2*(b*sec(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(5*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))*sec(c + d*x)**2,
        variable=x,
        num_steps=4,
        integral=2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*d) + 2*(b*sec(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(3*b*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))*sec(c + d*x),
        variable=x,
        num_steps=4,
        integral=-2*b*elliptic_e(c/2 + d*x/2, 2)/(d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))) + 2*sqrt(b*sec(c + d*x))*sin(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=2,
        integral=2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/d,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))*cos(c + d*x),
        variable=x,
        num_steps=3,
        integral=2*b*elliptic_e(c/2 + d*x/2, 2)/(d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))*cos(c + d*x)**2,
        variable=x,
        num_steps=4,
        integral=2*b*sin(c + d*x)/(3*d*sqrt(b*sec(c + d*x))) + 2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))*cos(c + d*x)**3,
        variable=x,
        num_steps=4,
        integral=2*b**2*sin(c + d*x)/(5*d*(b*sec(c + d*x))**(sympy.S(3)/2)) + 6*b*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))*cos(c + d*x)**4,
        variable=x,
        num_steps=5,
        integral=2*b**3*sin(c + d*x)/(7*d*(b*sec(c + d*x))**(sympy.S(5)/2)) + 10*b*sin(c + d*x)/(21*d*sqrt(b*sec(c + d*x))) + 10*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))*cos(c + d*x)**5,
        variable=x,
        num_steps=5,
        integral=2*b**4*sin(c + d*x)/(9*d*(b*sec(c + d*x))**(sympy.S(7)/2)) + 14*b**2*sin(c + d*x)/(45*d*(b*sec(c + d*x))**(sympy.S(3)/2)) + 14*b*elliptic_e(c/2 + d*x/2, 2)/(15*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)*sec(c + d*x)**3,
        variable=x,
        num_steps=5,
        integral=10*b*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d) + 10*(b*sec(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(21*d) + 2*(b*sec(c + d*x))**(sympy.S(7)/2)*sin(c + d*x)/(7*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)*sec(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=-6*b**2*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))) + 6*b*sqrt(b*sec(c + d*x))*sin(c + d*x)/(5*d) + 2*(b*sec(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(5*b*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)*sec(c + d*x),
        variable=x,
        num_steps=4,
        integral=2*b*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*d) + 2*(b*sec(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-2*b**2*elliptic_e(c/2 + d*x/2, 2)/(d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))) + 2*b*sqrt(b*sec(c + d*x))*sin(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)*cos(c + d*x),
        variable=x,
        num_steps=3,
        integral=2*b*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/d,
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)*cos(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=2*b**2*elliptic_e(c/2 + d*x/2, 2)/(d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)*cos(c + d*x)**3,
        variable=x,
        num_steps=4,
        integral=2*b**2*sin(c + d*x)/(3*d*sqrt(b*sec(c + d*x))) + 2*b*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)*cos(c + d*x)**4,
        variable=x,
        num_steps=4,
        integral=2*b**3*sin(c + d*x)/(5*d*(b*sec(c + d*x))**(sympy.S(3)/2)) + 6*b**2*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)*cos(c + d*x)**5,
        variable=x,
        num_steps=5,
        integral=2*b**4*sin(c + d*x)/(7*d*(b*sec(c + d*x))**(sympy.S(5)/2)) + 10*b**2*sin(c + d*x)/(21*d*sqrt(b*sec(c + d*x))) + 10*b*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)*cos(c + d*x)**6,
        variable=x,
        num_steps=5,
        integral=2*b**5*sin(c + d*x)/(9*d*(b*sec(c + d*x))**(sympy.S(7)/2)) + 14*b**3*sin(c + d*x)/(45*d*(b*sec(c + d*x))**(sympy.S(3)/2)) + 14*b**2*elliptic_e(c/2 + d*x/2, 2)/(15*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)*sec(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=10*b**2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d) + 10*b*(b*sec(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(21*d) + 2*(b*sec(c + d*x))**(sympy.S(7)/2)*sin(c + d*x)/(7*b*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)*sec(c + d*x),
        variable=x,
        num_steps=5,
        integral=-6*b**3*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))) + 6*b**2*sqrt(b*sec(c + d*x))*sin(c + d*x)/(5*d) + 2*(b*sec(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*b**2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*d) + 2*b*(b*sec(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)*cos(c + d*x),
        variable=x,
        num_steps=4,
        integral=-2*b**3*elliptic_e(c/2 + d*x/2, 2)/(d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))) + 2*b**2*sqrt(b*sec(c + d*x))*sin(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)*cos(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=2*b**2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/d,
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)*cos(c + d*x)**3,
        variable=x,
        num_steps=3,
        integral=2*b**3*elliptic_e(c/2 + d*x/2, 2)/(d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)*cos(c + d*x)**4,
        variable=x,
        num_steps=4,
        integral=2*b**3*sin(c + d*x)/(3*d*sqrt(b*sec(c + d*x))) + 2*b**2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)*cos(c + d*x)**5,
        variable=x,
        num_steps=4,
        integral=2*b**4*sin(c + d*x)/(5*d*(b*sec(c + d*x))**(sympy.S(3)/2)) + 6*b**3*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)*cos(c + d*x)**6,
        variable=x,
        num_steps=5,
        integral=2*b**5*sin(c + d*x)/(7*d*(b*sec(c + d*x))**(sympy.S(5)/2)) + 10*b**3*sin(c + d*x)/(21*d*sqrt(b*sec(c + d*x))) + 10*b**2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)*cos(c + d*x)**7,
        variable=x,
        num_steps=5,
        integral=2*b**6*sin(c + d*x)/(9*d*(b*sec(c + d*x))**(sympy.S(7)/2)) + 14*b**4*sin(c + d*x)/(45*d*(b*sec(c + d*x))**(sympy.S(3)/2)) + 14*b**3*elliptic_e(c/2 + d*x/2, 2)/(15*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=4,
        integral=-6*b**4*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))) + 6*b**3*sqrt(b*sec(c + d*x))*sin(c + d*x)/(5*d) + 2*b*(b*sec(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**5/sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=5,
        integral=10*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*b*d) + 10*(b*sec(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(21*b**2*d) + 2*(b*sec(c + d*x))**(sympy.S(7)/2)*sin(c + d*x)/(7*b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**4/sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=5,
        integral=-6*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))) + 6*sqrt(b*sec(c + d*x))*sin(c + d*x)/(5*b*d) + 2*(b*sec(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(5*b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=4,
        integral=2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*b*d) + 2*(b*sec(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(3*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=4,
        integral=-2*elliptic_e(c/2 + d*x/2, 2)/(d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))) + 2*sqrt(b*sec(c + d*x))*sin(c + d*x)/(b*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=3,
        integral=2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(b*d),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=2,
        integral=2*elliptic_e(c/2 + d*x/2, 2)/(d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=4,
        integral=2*sin(c + d*x)/(3*d*sqrt(b*sec(c + d*x))) + 2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*b*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=4,
        integral=2*b*sin(c + d*x)/(5*d*(b*sec(c + d*x))**(sympy.S(3)/2)) + 6*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=5,
        integral=2*b**2*sin(c + d*x)/(7*d*(b*sec(c + d*x))**(sympy.S(5)/2)) + 10*sin(c + d*x)/(21*d*sqrt(b*sec(c + d*x))) + 10*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*b*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**4/sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=5,
        integral=2*b**3*sin(c + d*x)/(9*d*(b*sec(c + d*x))**(sympy.S(7)/2)) + 14*b*sin(c + d*x)/(45*d*(b*sec(c + d*x))**(sympy.S(3)/2)) + 14*elliptic_e(c/2 + d*x/2, 2)/(15*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**6/(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=10*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*b**2*d) + 10*(b*sec(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(21*b**3*d) + 2*(b*sec(c + d*x))**(sympy.S(7)/2)*sin(c + d*x)/(7*b**5*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**5/(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=-6*elliptic_e(c/2 + d*x/2, 2)/(5*b*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))) + 6*sqrt(b*sec(c + d*x))*sin(c + d*x)/(5*b**2*d) + 2*(b*sec(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(5*b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**4/(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*b**2*d) + 2*(b*sec(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(3*b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=-2*elliptic_e(c/2 + d*x/2, 2)/(b*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))) + 2*sqrt(b*sec(c + d*x))*sin(c + d*x)/(b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*elliptic_e(c/2 + d*x/2, 2)/(b*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*sin(c + d*x)/(3*b*d*sqrt(b*sec(c + d*x))) + 2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=2*sin(c + d*x)/(5*d*(b*sec(c + d*x))**(sympy.S(3)/2)) + 6*elliptic_e(c/2 + d*x/2, 2)/(5*b*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=2*b*sin(c + d*x)/(7*d*(b*sec(c + d*x))**(sympy.S(5)/2)) + 10*sin(c + d*x)/(21*b*d*sqrt(b*sec(c + d*x))) + 10*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=2*b**2*sin(c + d*x)/(9*d*(b*sec(c + d*x))**(sympy.S(7)/2)) + 14*sin(c + d*x)/(45*d*(b*sec(c + d*x))**(sympy.S(3)/2)) + 14*elliptic_e(c/2 + d*x/2, 2)/(15*b*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**7/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=10*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*b**3*d) + 10*(b*sec(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(21*b**4*d) + 2*(b*sec(c + d*x))**(sympy.S(7)/2)*sin(c + d*x)/(7*b**6*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**6/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=-6*elliptic_e(c/2 + d*x/2, 2)/(5*b**2*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))) + 6*sqrt(b*sec(c + d*x))*sin(c + d*x)/(5*b**3*d) + 2*(b*sec(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(5*b**5*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**5/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*b**3*d) + 2*(b*sec(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(3*b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**4/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=-2*elliptic_e(c/2 + d*x/2, 2)/(b**2*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))) + 2*sqrt(b*sec(c + d*x))*sin(c + d*x)/(b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*elliptic_e(c/2 + d*x/2, 2)/(b**2*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=2*sin(c + d*x)/(3*b**2*d*sqrt(b*sec(c + d*x))) + 2*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(-5)/2),
        variable=x,
        num_steps=3,
        integral=2*sin(c + d*x)/(5*b*d*(b*sec(c + d*x))**(sympy.S(3)/2)) + 6*elliptic_e(c/2 + d*x/2, 2)/(5*b**2*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=2*sin(c + d*x)/(7*d*(b*sec(c + d*x))**(sympy.S(5)/2)) + 10*sin(c + d*x)/(21*b**2*d*sqrt(b*sec(c + d*x))) + 10*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=2*b*sin(c + d*x)/(9*d*(b*sec(c + d*x))**(sympy.S(7)/2)) + 14*sin(c + d*x)/(45*b*d*(b*sec(c + d*x))**(sympy.S(3)/2)) + 14*elliptic_e(c/2 + d*x/2, 2)/(15*b**2*d*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(-7)/2),
        variable=x,
        num_steps=4,
        integral=2*sin(c + d*x)/(7*b*d*(b*sec(c + d*x))**(sympy.S(5)/2)) + 10*sin(c + d*x)/(21*b**3*d*sqrt(b*sec(c + d*x))) + 10*sqrt(b*sec(c + d*x))*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))*sec(c + d*x)**(sympy.S(9)/2),
        variable=x,
        num_steps=4,
        integral=sqrt(b*sec(c + d*x))*sin(c + d*x)*sec(c + d*x)**(sympy.S(7)/2)/(4*d) + 3*sqrt(b*sec(c + d*x))*sin(c + d*x)*sec(c + d*x)**(sympy.S(3)/2)/(8*d) + 3*sqrt(b*sec(c + d*x))*atanh(sin(c + d*x))/(8*d*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))*sec(c + d*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=sqrt(b*sec(c + d*x))*sin(c + d*x)**3*sec(c + d*x)**(sympy.S(5)/2)/(3*d) + sqrt(b*sec(c + d*x))*sin(c + d*x)*sqrt(sec(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))*sec(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=sqrt(b*sec(c + d*x))*sin(c + d*x)*sec(c + d*x)**(sympy.S(3)/2)/(2*d) + sqrt(b*sec(c + d*x))*atanh(sin(c + d*x))/(2*d*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))*sec(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=sqrt(b*sec(c + d*x))*sin(c + d*x)*sqrt(sec(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))*sqrt(sec(c + d*x)),
        variable=x,
        num_steps=2,
        integral=sqrt(b*sec(c + d*x))*atanh(sin(c + d*x))/(d*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))/sqrt(sec(c + d*x)),
        variable=x,
        num_steps=2,
        integral=x*sqrt(b*sec(c + d*x))/sqrt(sec(c + d*x)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))/sec(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=sqrt(b*sec(c + d*x))*sin(c + d*x)/(d*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))/sec(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=x*sqrt(b*sec(c + d*x))/(2*sqrt(sec(c + d*x))) + sqrt(b*sec(c + d*x))*sin(c + d*x)/(2*d*sec(c + d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))/sec(c + d*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=-sqrt(b*sec(c + d*x))*sin(c + d*x)**3/(3*d*sqrt(sec(c + d*x))) + sqrt(b*sec(c + d*x))*sin(c + d*x)/(d*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sec(c + d*x))/sec(c + d*x)**(sympy.S(9)/2),
        variable=x,
        num_steps=4,
        integral=3*x*sqrt(b*sec(c + d*x))/(8*sqrt(sec(c + d*x))) + 3*sqrt(b*sec(c + d*x))*sin(c + d*x)/(8*d*sec(c + d*x)**(sympy.S(3)/2)) + sqrt(b*sec(c + d*x))*sin(c + d*x)/(4*d*sec(c + d*x)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)*sec(c + d*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=4,
        integral=b*sqrt(b*sec(c + d*x))*sin(c + d*x)*sec(c + d*x)**(sympy.S(7)/2)/(4*d) + 3*b*sqrt(b*sec(c + d*x))*sin(c + d*x)*sec(c + d*x)**(sympy.S(3)/2)/(8*d) + 3*b*sqrt(b*sec(c + d*x))*atanh(sin(c + d*x))/(8*d*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)*sec(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=b*sqrt(b*sec(c + d*x))*sin(c + d*x)**3*sec(c + d*x)**(sympy.S(5)/2)/(3*d) + b*sqrt(b*sec(c + d*x))*sin(c + d*x)*sqrt(sec(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)*sec(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=b*sqrt(b*sec(c + d*x))*sin(c + d*x)*sec(c + d*x)**(sympy.S(3)/2)/(2*d) + b*sqrt(b*sec(c + d*x))*atanh(sin(c + d*x))/(2*d*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)*sqrt(sec(c + d*x)),
        variable=x,
        num_steps=3,
        integral=b*sqrt(b*sec(c + d*x))*sin(c + d*x)*sqrt(sec(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)/sqrt(sec(c + d*x)),
        variable=x,
        num_steps=2,
        integral=b*sqrt(b*sec(c + d*x))*atanh(sin(c + d*x))/(d*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)/sec(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=b*x*sqrt(b*sec(c + d*x))/sqrt(sec(c + d*x)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)/sec(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=b*sqrt(b*sec(c + d*x))*sin(c + d*x)/(d*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)/sec(c + d*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=b*x*sqrt(b*sec(c + d*x))/(2*sqrt(sec(c + d*x))) + b*sqrt(b*sec(c + d*x))*sin(c + d*x)/(2*d*sec(c + d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)/sec(c + d*x)**(sympy.S(9)/2),
        variable=x,
        num_steps=3,
        integral=-b*sqrt(b*sec(c + d*x))*sin(c + d*x)**3/(3*d*sqrt(sec(c + d*x))) + b*sqrt(b*sec(c + d*x))*sin(c + d*x)/(d*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(3)/2)/sec(c + d*x)**(sympy.S(11)/2),
        variable=x,
        num_steps=4,
        integral=3*b*x*sqrt(b*sec(c + d*x))/(8*sqrt(sec(c + d*x))) + 3*b*sqrt(b*sec(c + d*x))*sin(c + d*x)/(8*d*sec(c + d*x)**(sympy.S(3)/2)) + b*sqrt(b*sec(c + d*x))*sin(c + d*x)/(4*d*sec(c + d*x)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)*sec(c + d*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=b**2*sqrt(b*sec(c + d*x))*sin(c + d*x)**5*sec(c + d*x)**(sympy.S(9)/2)/(5*d) + 2*b**2*sqrt(b*sec(c + d*x))*sin(c + d*x)**3*sec(c + d*x)**(sympy.S(5)/2)/(3*d) + b**2*sqrt(b*sec(c + d*x))*sin(c + d*x)*sqrt(sec(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)*sec(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=b**2*sqrt(b*sec(c + d*x))*sin(c + d*x)**3*sec(c + d*x)**(sympy.S(5)/2)/(3*d) + b**2*sqrt(b*sec(c + d*x))*sin(c + d*x)*sqrt(sec(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)*sqrt(sec(c + d*x)),
        variable=x,
        num_steps=3,
        integral=b**2*sqrt(b*sec(c + d*x))*sin(c + d*x)*sec(c + d*x)**(sympy.S(3)/2)/(2*d) + b**2*sqrt(b*sec(c + d*x))*atanh(sin(c + d*x))/(2*d*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)/sqrt(sec(c + d*x)),
        variable=x,
        num_steps=3,
        integral=b**2*sqrt(b*sec(c + d*x))*sin(c + d*x)*sqrt(sec(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)/sec(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=b**2*sqrt(b*sec(c + d*x))*atanh(sin(c + d*x))/(d*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)/sec(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=b**2*x*sqrt(b*sec(c + d*x))/sqrt(sec(c + d*x)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)/sec(c + d*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=2,
        integral=b**2*sqrt(b*sec(c + d*x))*sin(c + d*x)/(d*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)/sec(c + d*x)**(sympy.S(9)/2),
        variable=x,
        num_steps=3,
        integral=b**2*x*sqrt(b*sec(c + d*x))/(2*sqrt(sec(c + d*x))) + b**2*sqrt(b*sec(c + d*x))*sin(c + d*x)/(2*d*sec(c + d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(5)/2)/sec(c + d*x)**(sympy.S(11)/2),
        variable=x,
        num_steps=3,
        integral=-b**2*sqrt(b*sec(c + d*x))*sin(c + d*x)**3/(3*d*sqrt(sec(c + d*x))) + b**2*sqrt(b*sec(c + d*x))*sin(c + d*x)/(d*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**(sympy.S(7)/2)/sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)*sec(c + d*x)**(sympy.S(5)/2)/(2*d*sqrt(b*sec(c + d*x))) + atanh(sin(c + d*x))*sqrt(sec(c + d*x))/(2*d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**(sympy.S(5)/2)/sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)*sec(c + d*x)**(sympy.S(3)/2)/(d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**(sympy.S(3)/2)/sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=2,
        integral=atanh(sin(c + d*x))*sqrt(sec(c + d*x))/(d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sec(c + d*x))/sqrt(b*sec(c + d*x)),
        variable=x,
        num_steps=2,
        integral=x*sqrt(sec(c + d*x))/sqrt(b*sec(c + d*x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(b*sec(c + d*x))*sqrt(sec(c + d*x))),
        variable=x,
        num_steps=2,
        integral=sin(c + d*x)*sqrt(sec(c + d*x))/(d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(b*sec(c + d*x))*sec(c + d*x)**(sympy.S(3)/2)),
        variable=x,
        num_steps=3,
        integral=x*sqrt(sec(c + d*x))/(2*sqrt(b*sec(c + d*x))) + sin(c + d*x)/(2*d*sqrt(b*sec(c + d*x))*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(b*sec(c + d*x))*sec(c + d*x)**(sympy.S(5)/2)),
        variable=x,
        num_steps=3,
        integral=-sin(c + d*x)**3*sqrt(sec(c + d*x))/(3*d*sqrt(b*sec(c + d*x))) + sin(c + d*x)*sqrt(sec(c + d*x))/(d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**(sympy.S(9)/2)/(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)*sec(c + d*x)**(sympy.S(5)/2)/(2*b*d*sqrt(b*sec(c + d*x))) + atanh(sin(c + d*x))*sqrt(sec(c + d*x))/(2*b*d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**(sympy.S(7)/2)/(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)*sec(c + d*x)**(sympy.S(3)/2)/(b*d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**(sympy.S(5)/2)/(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=atanh(sin(c + d*x))*sqrt(sec(c + d*x))/(b*d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**(sympy.S(3)/2)/(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=x*sqrt(sec(c + d*x))/(b*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sec(c + d*x))/(b*sec(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=sin(c + d*x)*sqrt(sec(c + d*x))/(b*d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((b*sec(c + d*x))**(sympy.S(3)/2)*sqrt(sec(c + d*x))),
        variable=x,
        num_steps=3,
        integral=x*sqrt(sec(c + d*x))/(2*b*sqrt(b*sec(c + d*x))) + sin(c + d*x)/(2*b*d*sqrt(b*sec(c + d*x))*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((b*sec(c + d*x))**(sympy.S(3)/2)*sec(c + d*x)**(sympy.S(3)/2)),
        variable=x,
        num_steps=3,
        integral=-sin(c + d*x)**3*sqrt(sec(c + d*x))/(3*b*d*sqrt(b*sec(c + d*x))) + sin(c + d*x)*sqrt(sec(c + d*x))/(b*d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((b*sec(c + d*x))**(sympy.S(3)/2)*sec(c + d*x)**(sympy.S(5)/2)),
        variable=x,
        num_steps=4,
        integral=3*x*sqrt(sec(c + d*x))/(8*b*sqrt(b*sec(c + d*x))) + 3*sin(c + d*x)/(8*b*d*sqrt(b*sec(c + d*x))*sqrt(sec(c + d*x))) + sin(c + d*x)/(4*b*d*sqrt(b*sec(c + d*x))*sec(c + d*x)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**(sympy.S(11)/2)/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)*sec(c + d*x)**(sympy.S(5)/2)/(2*b**2*d*sqrt(b*sec(c + d*x))) + atanh(sin(c + d*x))*sqrt(sec(c + d*x))/(2*b**2*d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**(sympy.S(9)/2)/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)*sec(c + d*x)**(sympy.S(3)/2)/(b**2*d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**(sympy.S(7)/2)/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=atanh(sin(c + d*x))*sqrt(sec(c + d*x))/(b**2*d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**(sympy.S(5)/2)/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=x*sqrt(sec(c + d*x))/(b**2*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**(sympy.S(3)/2)/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=sin(c + d*x)*sqrt(sec(c + d*x))/(b**2*d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sec(c + d*x))/(b*sec(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=x*sqrt(sec(c + d*x))/(2*b**2*sqrt(b*sec(c + d*x))) + sin(c + d*x)/(2*b**2*d*sqrt(b*sec(c + d*x))*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((b*sec(c + d*x))**(sympy.S(5)/2)*sqrt(sec(c + d*x))),
        variable=x,
        num_steps=3,
        integral=-sin(c + d*x)**3*sqrt(sec(c + d*x))/(3*b**2*d*sqrt(b*sec(c + d*x))) + sin(c + d*x)*sqrt(sec(c + d*x))/(b**2*d*sqrt(b*sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((b*sec(c + d*x))**(sympy.S(5)/2)*sec(c + d*x)**(sympy.S(3)/2)),
        variable=x,
        num_steps=4,
        integral=3*x*sqrt(sec(c + d*x))/(8*b**2*sqrt(b*sec(c + d*x))) + 3*sin(c + d*x)/(8*b**2*d*sqrt(b*sec(c + d*x))*sqrt(sec(c + d*x))) + sin(c + d*x)/(4*b**2*d*sqrt(b*sec(c + d*x))*sec(c + d*x)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(1)/3)*sec(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=3*(b*sec(c + d*x))**(sympy.S(4)/3)*sin(c + d*x)*hyper((sympy.S(-2)/3, sympy.S.Half), (sympy.S(1)/3,), cos(c + d*x)**2)/(4*b*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(1)/3)*sec(c + d*x),
        variable=x,
        num_steps=3,
        integral=3*(b*sec(c + d*x))**(sympy.S(1)/3)*sin(c + d*x)*hyper((sympy.S(-1)/6, sympy.S.Half), (sympy.S(5)/6,), cos(c + d*x)**2)/(d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=2,
        integral=-3*b*sin(c + d*x)*hyper((sympy.S(1)/3, sympy.S.Half), (sympy.S(4)/3,), cos(c + d*x)**2)/(2*d*(b*sec(c + d*x))**(sympy.S(2)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(1)/3)*cos(c + d*x),
        variable=x,
        num_steps=3,
        integral=-3*b**2*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(5)/6), (sympy.S(11)/6,), cos(c + d*x)**2)/(5*d*(b*sec(c + d*x))**(sympy.S(5)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(1)/3)*cos(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=-3*b**3*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(4)/3), (sympy.S(7)/3,), cos(c + d*x)**2)/(8*d*(b*sec(c + d*x))**(sympy.S(8)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(4)/3)*sec(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=3*(b*sec(c + d*x))**(sympy.S(7)/3)*sin(c + d*x)*hyper((sympy.S(-7)/6, sympy.S.Half), (sympy.S(-1)/6,), cos(c + d*x)**2)/(7*b*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(4)/3)*sec(c + d*x),
        variable=x,
        num_steps=3,
        integral=3*(b*sec(c + d*x))**(sympy.S(4)/3)*sin(c + d*x)*hyper((sympy.S(-2)/3, sympy.S.Half), (sympy.S(1)/3,), cos(c + d*x)**2)/(4*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=2,
        integral=3*b*(b*sec(c + d*x))**(sympy.S(1)/3)*sin(c + d*x)*hyper((sympy.S(-1)/6, sympy.S.Half), (sympy.S(5)/6,), cos(c + d*x)**2)/(d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(4)/3)*cos(c + d*x),
        variable=x,
        num_steps=3,
        integral=-3*b**2*sin(c + d*x)*hyper((sympy.S(1)/3, sympy.S.Half), (sympy.S(4)/3,), cos(c + d*x)**2)/(2*d*(b*sec(c + d*x))**(sympy.S(2)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(4)/3)*cos(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=-3*b**3*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(5)/6), (sympy.S(11)/6,), cos(c + d*x)**2)/(5*d*(b*sec(c + d*x))**(sympy.S(5)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(b*sec(c + d*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=3,
        integral=3*(b*sec(c + d*x))**(sympy.S(2)/3)*sin(c + d*x)*hyper((sympy.S(-1)/3, sympy.S.Half), (sympy.S(2)/3,), cos(c + d*x)**2)/(2*b*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(b*sec(c + d*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=3,
        integral=-3*sin(c + d*x)*hyper((sympy.S(1)/6, sympy.S.Half), (sympy.S(7)/6,), cos(c + d*x)**2)/(d*(b*sec(c + d*x))**(sympy.S(1)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(-1)/3),
        variable=x,
        num_steps=2,
        integral=-3*b*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(2)/3), (sympy.S(5)/3,), cos(c + d*x)**2)/(4*d*(b*sec(c + d*x))**(sympy.S(4)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(b*sec(c + d*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=3,
        integral=-3*b**2*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(7)/6), (sympy.S(13)/6,), cos(c + d*x)**2)/(7*d*(b*sec(c + d*x))**(sympy.S(7)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(b*sec(c + d*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=3,
        integral=-3*b**3*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(5)/3), (sympy.S(8)/3,), cos(c + d*x)**2)/(10*d*(b*sec(c + d*x))**(sympy.S(10)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(b*sec(c + d*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=3,
        integral=-3*sin(c + d*x)*hyper((sympy.S(1)/6, sympy.S.Half), (sympy.S(7)/6,), cos(c + d*x)**2)/(b*d*(b*sec(c + d*x))**(sympy.S(1)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(b*sec(c + d*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=3,
        integral=-3*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(2)/3), (sympy.S(5)/3,), cos(c + d*x)**2)/(4*d*(b*sec(c + d*x))**(sympy.S(4)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(-4)/3),
        variable=x,
        num_steps=2,
        integral=-3*b*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(7)/6), (sympy.S(13)/6,), cos(c + d*x)**2)/(7*d*(b*sec(c + d*x))**(sympy.S(7)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(b*sec(c + d*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=3,
        integral=-3*b**2*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(5)/3), (sympy.S(8)/3,), cos(c + d*x)**2)/(10*d*(b*sec(c + d*x))**(sympy.S(10)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(b*sec(c + d*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=3,
        integral=-3*b**3*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(13)/6), (sympy.S(19)/6,), cos(c + d*x)**2)/(13*d*(b*sec(c + d*x))**(sympy.S(13)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(4)/3)*sec(c + d*x)**m,
        variable=x,
        num_steps=3,
        integral=3*b*(b*sec(c + d*x))**(sympy.S(1)/3)*sin(c + d*x)*hyper((sympy.S.Half, -m/2 + sympy.S(-1)/6), (sympy.S(5)/6 - m/2,), cos(c + d*x)**2)*sec(c + d*x)**m/(d*(3*m + 1)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(2)/3)*sec(c + d*x)**m,
        variable=x,
        num_steps=3,
        integral=-3*(b*sec(c + d*x))**(sympy.S(2)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(1)/6 - m/2), (sympy.S(7)/6 - m/2,), cos(c + d*x)**2)*sec(c + d*x)**(m - 1)/(d*(1 - 3*m)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**(sympy.S(1)/3)*sec(c + d*x)**m,
        variable=x,
        num_steps=3,
        integral=-3*(b*sec(c + d*x))**(sympy.S(1)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(1)/3 - m/2), (sympy.S(4)/3 - m/2,), cos(c + d*x)**2)*sec(c + d*x)**(m - 1)/(d*(2 - 3*m)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**m/(b*sec(c + d*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=3,
        integral=-3*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(2)/3 - m/2), (sympy.S(5)/3 - m/2,), cos(c + d*x)**2)*sec(c + d*x)**(m - 1)/(d*(b*sec(c + d*x))**(sympy.S(1)/3)*(4 - 3*m)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**m/(b*sec(c + d*x))**(sympy.S(2)/3),
        variable=x,
        num_steps=3,
        integral=-3*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(5)/6 - m/2), (sympy.S(11)/6 - m/2,), cos(c + d*x)**2)*sec(c + d*x)**(m - 1)/(d*(b*sec(c + d*x))**(sympy.S(2)/3)*(5 - 3*m)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**m/(b*sec(c + d*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=3,
        integral=-3*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(7)/6 - m/2), (sympy.S(13)/6 - m/2,), cos(c + d*x)**2)*sec(c + d*x)**(m - 2)/(b*d*(b*sec(c + d*x))**(sympy.S(1)/3)*(7 - 3*m)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**n*sec(c + d*x)**m,
        variable=x,
        num_steps=3,
        integral=-(b*sec(c + d*x))**n*sin(c + d*x)*hyper((sympy.S.Half, -m/2 - n/2 + sympy.S.Half), (-m/2 - n/2 + sympy.S(3)/2,), cos(c + d*x)**2)*sec(c + d*x)**(m - 1)/(d*(-m - n + 1)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**n*sec(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=(b*sec(c + d*x))**(n + 1)*sin(c + d*x)*hyper((sympy.S.Half, -n/2 + sympy.S(-1)/2), (sympy.S.Half - n/2,), cos(c + d*x)**2)/(b*d*(n + 1)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**n*sec(c + d*x),
        variable=x,
        num_steps=3,
        integral=(b*sec(c + d*x))**n*sin(c + d*x)*hyper((sympy.S.Half, -n/2), (1 - n/2,), cos(c + d*x)**2)/(d*n*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**n,
        variable=x,
        num_steps=2,
        integral=-b*(b*sec(c + d*x))**(n - 1)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), cos(c + d*x)**2)/(d*(1 - n)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**n*cos(c + d*x),
        variable=x,
        num_steps=3,
        integral=-b**2*(b*sec(c + d*x))**(n - 2)*sin(c + d*x)*hyper((sympy.S.Half, 1 - n/2), (2 - n/2,), cos(c + d*x)**2)/(d*(2 - n)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**n*cos(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=-b**3*(b*sec(c + d*x))**(n - 3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(3)/2 - n/2), (sympy.S(5)/2 - n/2,), cos(c + d*x)**2)/(d*(3 - n)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**n*cos(c + d*x)**3,
        variable=x,
        num_steps=3,
        integral=-b**4*(b*sec(c + d*x))**(n - 4)*sin(c + d*x)*hyper((sympy.S.Half, 2 - n/2), (3 - n/2,), cos(c + d*x)**2)/(d*(4 - n)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**n*sec(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*(b*sec(c + d*x))**n*sin(c + d*x)*hyper((sympy.S.Half, -n/2 + sympy.S(-3)/4), (sympy.S(1)/4 - n/2,), cos(c + d*x)**2)*sec(c + d*x)**(sympy.S(3)/2)/(d*(2*n + 3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**n*sec(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*(b*sec(c + d*x))**n*sin(c + d*x)*hyper((sympy.S.Half, -n/2 + sympy.S(-1)/4), (sympy.S(3)/4 - n/2,), cos(c + d*x)**2)*sqrt(sec(c + d*x))/(d*(2*n + 1)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**n*sqrt(sec(c + d*x)),
        variable=x,
        num_steps=3,
        integral=-2*(b*sec(c + d*x))**n*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(1)/4 - n/2), (sympy.S(5)/4 - n/2,), cos(c + d*x)**2)/(d*(1 - 2*n)*sqrt(sin(c + d*x)**2)*sqrt(sec(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**n/sqrt(sec(c + d*x)),
        variable=x,
        num_steps=3,
        integral=-2*(b*sec(c + d*x))**n*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(3)/4 - n/2), (sympy.S(7)/4 - n/2,), cos(c + d*x)**2)/(d*(3 - 2*n)*sqrt(sin(c + d*x)**2)*sec(c + d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**n/sec(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-2*(b*sec(c + d*x))**n*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(5)/4 - n/2), (sympy.S(9)/4 - n/2,), cos(c + d*x)**2)/(d*(5 - 2*n)*sqrt(sin(c + d*x)**2)*sec(c + d*x)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*sec(c + d*x))**n/sec(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=-2*(b*sec(c + d*x))**n*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(7)/4 - n/2), (sympy.S(11)/4 - n/2,), cos(c + d*x)**2)/(d*(7 - 2*n)*sqrt(sin(c + d*x)**2)*sec(c + d*x)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(d*sec(a + b*x))**(sympy.S(7)/2)*sin(a + b*x),
        variable=x,
        num_steps=2,
        integral=2*d*(d*sec(a + b*x))**(sympy.S(5)/2)/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=(d*sec(a + b*x))**(sympy.S(5)/2)*sin(a + b*x),
        variable=x,
        num_steps=2,
        integral=2*d*(d*sec(a + b*x))**(sympy.S(3)/2)/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=(d*sec(a + b*x))**(sympy.S(3)/2)*sin(a + b*x),
        variable=x,
        num_steps=2,
        integral=2*d*sqrt(d*sec(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(d*sec(a + b*x))*sin(a + b*x),
        variable=x,
        num_steps=2,
        integral=-2*d/(b*sqrt(d*sec(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)/sqrt(d*sec(a + b*x)),
        variable=x,
        num_steps=2,
        integral=-2*d/(3*b*(d*sec(a + b*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(d*sec(a + b*x))**(sympy.S(5)/2)*sin(a + b*x)**3,
        variable=x,
        num_steps=3,
        integral=2*d**3/(b*sqrt(d*sec(a + b*x))) + 2*d*(d*sec(a + b*x))**(sympy.S(3)/2)/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=(d*sec(a + b*x))**(sympy.S(9)/2)*sin(a + b*x)**3,
        variable=x,
        num_steps=3,
        integral=-2*d**3*(d*sec(a + b*x))**(sympy.S(3)/2)/(3*b) + 2*d*(d*sec(a + b*x))**(sympy.S(7)/2)/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(c*sec(a + b*x))*(d*csc(a + b*x))**(sympy.S(9)/2),
        variable=x,
        num_steps=5,
        integral=-4*c*d**3*(d*csc(a + b*x))**(sympy.S(3)/2)/(7*b*sqrt(c*sec(a + b*x))) - 2*c*d*(d*csc(a + b*x))**(sympy.S(7)/2)/(7*b*sqrt(c*sec(a + b*x))) + 4*d**4*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))*elliptic_f(a + b*x - pi/4, 2)/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(c*sec(a + b*x))*(d*csc(a + b*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=2,
        integral=-8*c*d**3*sqrt(d*csc(a + b*x))/(5*b*sqrt(c*sec(a + b*x))) - 2*c*d*(d*csc(a + b*x))**(sympy.S(5)/2)/(5*b*sqrt(c*sec(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(c*sec(a + b*x))*(d*csc(a + b*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=-2*c*d*(d*csc(a + b*x))**(sympy.S(3)/2)/(3*b*sqrt(c*sec(a + b*x))) + 2*d**2*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))*elliptic_f(a + b*x - pi/4, 2)/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(c*sec(a + b*x))*(d*csc(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=1,
        integral=-2*c*d*sqrt(d*csc(a + b*x))/(b*sqrt(c*sec(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x)),
        variable=x,
        num_steps=3,
        integral=sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))*elliptic_f(a + b*x - pi/4, 2)/b,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(c*sec(a + b*x))/sqrt(d*csc(a + b*x)),
        variable=x,
        num_steps=12,
        integral=sqrt(2)*sqrt(c*sec(a + b*x))*log(-sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)/(4*b*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) - sqrt(2)*sqrt(c*sec(a + b*x))*log(sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)/(4*b*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) + sqrt(2)*sqrt(c*sec(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) - 1)/(2*b*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) + sqrt(2)*sqrt(c*sec(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) + 1)/(2*b*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(c*sec(a + b*x))/(d*csc(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=-c/(b*d*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))) + sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))*elliptic_f(a + b*x - pi/4, 2)/(2*b*d**2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(c*sec(a + b*x))/(d*csc(a + b*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=13,
        integral=-c/(2*b*d*sqrt(c*sec(a + b*x))*(d*csc(a + b*x))**(sympy.S(3)/2)) + 3*sqrt(2)*sqrt(c*sec(a + b*x))*log(-sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)/(16*b*d**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) - 3*sqrt(2)*sqrt(c*sec(a + b*x))*log(sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)/(16*b*d**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) + 3*sqrt(2)*sqrt(c*sec(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) - 1)/(8*b*d**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) + 3*sqrt(2)*sqrt(c*sec(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) + 1)/(8*b*d**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(3)/2)*(d*csc(a + b*x))**(sympy.S(9)/2),
        variable=x,
        num_steps=3,
        integral=64*c*d**5*sqrt(c*sec(a + b*x))/(21*b*sqrt(d*csc(a + b*x))) - 16*c*d**3*sqrt(c*sec(a + b*x))*(d*csc(a + b*x))**(sympy.S(3)/2)/(21*b) - 2*c*d*sqrt(c*sec(a + b*x))*(d*csc(a + b*x))**(sympy.S(7)/2)/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(3)/2)*(d*csc(a + b*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=6,
        integral=-24*c**2*d**4*elliptic_e(a + b*x - pi/4, 2)/(5*b*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))) + 24*c*d**5*sqrt(c*sec(a + b*x))/(5*b*(d*csc(a + b*x))**(sympy.S(3)/2)) - 12*c*d**3*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))/(5*b) - 2*c*d*sqrt(c*sec(a + b*x))*(d*csc(a + b*x))**(sympy.S(5)/2)/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(3)/2)*(d*csc(a + b*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=8*c*d**3*sqrt(c*sec(a + b*x))/(3*b*sqrt(d*csc(a + b*x))) - 2*c*d*sqrt(c*sec(a + b*x))*(d*csc(a + b*x))**(sympy.S(3)/2)/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(3)/2)*(d*csc(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=-4*c**2*d**2*elliptic_e(a + b*x - pi/4, 2)/(b*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))) + 4*c*d**3*sqrt(c*sec(a + b*x))/(b*(d*csc(a + b*x))**(sympy.S(3)/2)) - 2*c*d*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(3)/2)*sqrt(d*csc(a + b*x)),
        variable=x,
        num_steps=1,
        integral=2*c*d*sqrt(c*sec(a + b*x))/(b*sqrt(d*csc(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(3)/2)/sqrt(d*csc(a + b*x)),
        variable=x,
        num_steps=4,
        integral=-2*c**2*elliptic_e(a + b*x - pi/4, 2)/(b*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))) + 2*c*d*sqrt(c*sec(a + b*x))/(b*(d*csc(a + b*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(3)/2)/(d*csc(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=13,
        integral=sqrt(2)*c**2*sqrt(d*csc(a + b*x))*log(-sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)*sqrt(tan(a + b*x))/(4*b*d**2*sqrt(c*sec(a + b*x))) - sqrt(2)*c**2*sqrt(d*csc(a + b*x))*log(sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)*sqrt(tan(a + b*x))/(4*b*d**2*sqrt(c*sec(a + b*x))) - sqrt(2)*c**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) - 1)/(2*b*d**2*sqrt(c*sec(a + b*x))) - sqrt(2)*c**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) + 1)/(2*b*d**2*sqrt(c*sec(a + b*x))) + 2*c*sqrt(c*sec(a + b*x))/(b*d*sqrt(d*csc(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(3)/2)/(d*csc(a + b*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=-3*c**2*elliptic_e(a + b*x - pi/4, 2)/(b*d**2*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))) + 2*c*sqrt(c*sec(a + b*x))/(b*d*(d*csc(a + b*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(5)/2)*(d*csc(a + b*x))**(sympy.S(9)/2),
        variable=x,
        num_steps=6,
        integral=40*c**2*d**4*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))*elliptic_f(a + b*x - pi/4, 2)/(21*b) + 40*c*d**5*(c*sec(a + b*x))**(sympy.S(3)/2)/(21*b*sqrt(d*csc(a + b*x))) - 20*c*d**3*(c*sec(a + b*x))**(sympy.S(3)/2)*(d*csc(a + b*x))**(sympy.S(3)/2)/(21*b) - 2*c*d*(c*sec(a + b*x))**(sympy.S(3)/2)*(d*csc(a + b*x))**(sympy.S(7)/2)/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(5)/2)*(d*csc(a + b*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=-64*c**3*d**3*sqrt(d*csc(a + b*x))/(15*b*sqrt(c*sec(a + b*x))) + 16*c*d**3*(c*sec(a + b*x))**(sympy.S(3)/2)*sqrt(d*csc(a + b*x))/(15*b) - 2*c*d*(c*sec(a + b*x))**(sympy.S(3)/2)*(d*csc(a + b*x))**(sympy.S(5)/2)/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(5)/2)*(d*csc(a + b*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=4*c**2*d**2*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))*elliptic_f(a + b*x - pi/4, 2)/(3*b) + 4*c*d**3*(c*sec(a + b*x))**(sympy.S(3)/2)/(3*b*sqrt(d*csc(a + b*x))) - 2*c*d*(c*sec(a + b*x))**(sympy.S(3)/2)*(d*csc(a + b*x))**(sympy.S(3)/2)/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(5)/2)*(d*csc(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=-8*c**3*d*sqrt(d*csc(a + b*x))/(3*b*sqrt(c*sec(a + b*x))) + 2*c*d*(c*sec(a + b*x))**(sympy.S(3)/2)*sqrt(d*csc(a + b*x))/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(5)/2)*sqrt(d*csc(a + b*x)),
        variable=x,
        num_steps=4,
        integral=2*c**2*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))*elliptic_f(a + b*x - pi/4, 2)/(3*b) + 2*c*d*(c*sec(a + b*x))**(sympy.S(3)/2)/(3*b*sqrt(d*csc(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(5)/2)/sqrt(d*csc(a + b*x)),
        variable=x,
        num_steps=1,
        integral=2*c*d*(c*sec(a + b*x))**(sympy.S(3)/2)/(3*b*(d*csc(a + b*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(5)/2)/(d*csc(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=-c**2*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))*elliptic_f(a + b*x - pi/4, 2)/(3*b*d**2) + 2*c*(c*sec(a + b*x))**(sympy.S(3)/2)/(3*b*d*sqrt(d*csc(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(c*sec(a + b*x))**(sympy.S(5)/2)/(d*csc(a + b*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=13,
        integral=-sqrt(2)*c**2*sqrt(c*sec(a + b*x))*log(-sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)/(4*b*d**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) + sqrt(2)*c**2*sqrt(c*sec(a + b*x))*log(sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)/(4*b*d**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) - sqrt(2)*c**2*sqrt(c*sec(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) - 1)/(2*b*d**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) - sqrt(2)*c**2*sqrt(c*sec(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) + 1)/(2*b*d**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) + 2*c*(c*sec(a + b*x))**(sympy.S(3)/2)/(3*b*d*(d*csc(a + b*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(d*csc(a + b*x))**(sympy.S(9)/2)/sqrt(c*sec(a + b*x)),
        variable=x,
        num_steps=2,
        integral=-8*c*d**3*(d*csc(a + b*x))**(sympy.S(3)/2)/(21*b*(c*sec(a + b*x))**(sympy.S(3)/2)) - 2*c*d*(d*csc(a + b*x))**(sympy.S(7)/2)/(7*b*(c*sec(a + b*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(d*csc(a + b*x))**(sympy.S(7)/2)/sqrt(c*sec(a + b*x)),
        variable=x,
        num_steps=5,
        integral=-4*c*d**3*sqrt(d*csc(a + b*x))/(5*b*(c*sec(a + b*x))**(sympy.S(3)/2)) - 2*c*d*(d*csc(a + b*x))**(sympy.S(5)/2)/(5*b*(c*sec(a + b*x))**(sympy.S(3)/2)) - 4*d**4*elliptic_e(a + b*x - pi/4, 2)/(5*b*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(d*csc(a + b*x))**(sympy.S(5)/2)/sqrt(c*sec(a + b*x)),
        variable=x,
        num_steps=1,
        integral=-2*c*d*(d*csc(a + b*x))**(sympy.S(3)/2)/(3*b*(c*sec(a + b*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(d*csc(a + b*x))**(sympy.S(3)/2)/sqrt(c*sec(a + b*x)),
        variable=x,
        num_steps=4,
        integral=-2*c*d*sqrt(d*csc(a + b*x))/(b*(c*sec(a + b*x))**(sympy.S(3)/2)) - 2*d**2*elliptic_e(a + b*x - pi/4, 2)/(b*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(d*csc(a + b*x))/sqrt(c*sec(a + b*x)),
        variable=x,
        num_steps=12,
        integral=-sqrt(2)*sqrt(d*csc(a + b*x))*log(-sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)*sqrt(tan(a + b*x))/(4*b*sqrt(c*sec(a + b*x))) + sqrt(2)*sqrt(d*csc(a + b*x))*log(sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)*sqrt(tan(a + b*x))/(4*b*sqrt(c*sec(a + b*x))) + sqrt(2)*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) - 1)/(2*b*sqrt(c*sec(a + b*x))) + sqrt(2)*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) + 1)/(2*b*sqrt(c*sec(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))),
        variable=x,
        num_steps=3,
        integral=elliptic_e(a + b*x - pi/4, 2)/(b*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(c*sec(a + b*x))*(d*csc(a + b*x))**(sympy.S(3)/2)),
        variable=x,
        num_steps=13,
        integral=-c/(2*b*d*(c*sec(a + b*x))**(sympy.S(3)/2)*sqrt(d*csc(a + b*x))) - sqrt(2)*sqrt(d*csc(a + b*x))*log(-sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)*sqrt(tan(a + b*x))/(16*b*d**2*sqrt(c*sec(a + b*x))) + sqrt(2)*sqrt(d*csc(a + b*x))*log(sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)*sqrt(tan(a + b*x))/(16*b*d**2*sqrt(c*sec(a + b*x))) + sqrt(2)*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) - 1)/(8*b*d**2*sqrt(c*sec(a + b*x))) + sqrt(2)*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) + 1)/(8*b*d**2*sqrt(c*sec(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(c*sec(a + b*x))*(d*csc(a + b*x))**(sympy.S(5)/2)),
        variable=x,
        num_steps=4,
        integral=-c/(3*b*d*(c*sec(a + b*x))**(sympy.S(3)/2)*(d*csc(a + b*x))**(sympy.S(3)/2)) + elliptic_e(a + b*x - pi/4, 2)/(2*b*d**2*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(d*csc(a + b*x))**(sympy.S(11)/2)/(c*sec(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=8*d**5*sqrt(d*csc(a + b*x))/(45*b*c*sqrt(c*sec(a + b*x))) + 2*d**3*(d*csc(a + b*x))**(sympy.S(5)/2)/(45*b*c*sqrt(c*sec(a + b*x))) - 2*d*(d*csc(a + b*x))**(sympy.S(9)/2)/(9*b*c*sqrt(c*sec(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(d*csc(a + b*x))**(sympy.S(9)/2)/(c*sec(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=2*d**3*(d*csc(a + b*x))**(sympy.S(3)/2)/(21*b*c*sqrt(c*sec(a + b*x))) - 2*d*(d*csc(a + b*x))**(sympy.S(7)/2)/(7*b*c*sqrt(c*sec(a + b*x))) - 2*d**4*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))*elliptic_f(a + b*x - pi/4, 2)/(21*b*c**2),
    ),
    RubiTestSuiteCase(
        integrand=(d*csc(a + b*x))**(sympy.S(7)/2)/(c*sec(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=1,
        integral=-2*c*d*(d*csc(a + b*x))**(sympy.S(5)/2)/(5*b*(c*sec(a + b*x))**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(d*csc(a + b*x))**(sympy.S(5)/2)/(c*sec(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=-2*d*(d*csc(a + b*x))**(sympy.S(3)/2)/(3*b*c*sqrt(c*sec(a + b*x))) - d**2*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))*elliptic_f(a + b*x - pi/4, 2)/(3*b*c**2),
    ),
    RubiTestSuiteCase(
        integrand=(d*csc(a + b*x))**(sympy.S(3)/2)/(c*sec(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=13,
        integral=-2*d*sqrt(d*csc(a + b*x))/(b*c*sqrt(c*sec(a + b*x))) - sqrt(2)*d**2*sqrt(c*sec(a + b*x))*log(-sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)/(4*b*c**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) + sqrt(2)*d**2*sqrt(c*sec(a + b*x))*log(sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)/(4*b*c**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) - sqrt(2)*d**2*sqrt(c*sec(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) - 1)/(2*b*c**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) - sqrt(2)*d**2*sqrt(c*sec(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) + 1)/(2*b*c**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(d*csc(a + b*x))/(c*sec(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=d/(b*c*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))) + sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))*elliptic_f(a + b*x - pi/4, 2)/(2*b*c**2),
    ),
    RubiTestSuiteCase(
        integrand=1/((c*sec(a + b*x))**(sympy.S(3)/2)*sqrt(d*csc(a + b*x))),
        variable=x,
        num_steps=13,
        integral=d/(2*b*c*sqrt(c*sec(a + b*x))*(d*csc(a + b*x))**(sympy.S(3)/2)) + sqrt(2)*sqrt(c*sec(a + b*x))*log(-sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)/(16*b*c**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) - sqrt(2)*sqrt(c*sec(a + b*x))*log(sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)/(16*b*c**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) + sqrt(2)*sqrt(c*sec(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) - 1)/(8*b*c**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) + sqrt(2)*sqrt(c*sec(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) + 1)/(8*b*c**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((c*sec(a + b*x))**(sympy.S(3)/2)*(d*csc(a + b*x))**(sympy.S(3)/2)),
        variable=x,
        num_steps=5,
        integral=-c/(3*b*d*(c*sec(a + b*x))**(sympy.S(5)/2)*sqrt(d*csc(a + b*x))) + 1/(6*b*c*d*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))) + sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))*elliptic_f(a + b*x - pi/4, 2)/(12*b*c**2*d**2),
    ),
    RubiTestSuiteCase(
        integrand=1/((c*sec(a + b*x))**(sympy.S(3)/2)*(d*csc(a + b*x))**(sympy.S(5)/2)),
        variable=x,
        num_steps=14,
        integral=-c/(4*b*d*(c*sec(a + b*x))**(sympy.S(5)/2)*(d*csc(a + b*x))**(sympy.S(3)/2)) + 3/(16*b*c*d*sqrt(c*sec(a + b*x))*(d*csc(a + b*x))**(sympy.S(3)/2)) + 3*sqrt(2)*sqrt(c*sec(a + b*x))*log(-sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)/(128*b*c**2*d**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) - 3*sqrt(2)*sqrt(c*sec(a + b*x))*log(sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)/(128*b*c**2*d**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) + 3*sqrt(2)*sqrt(c*sec(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) - 1)/(64*b*c**2*d**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))) + 3*sqrt(2)*sqrt(c*sec(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) + 1)/(64*b*c**2*d**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(d*csc(a + b*x))**(sympy.S(9)/2)/(c*sec(a + b*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=1,
        integral=-2*c*d*(d*csc(a + b*x))**(sympy.S(7)/2)/(7*b*(c*sec(a + b*x))**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(d*csc(a + b*x))**(sympy.S(7)/2)/(c*sec(a + b*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=6*d**3*sqrt(d*csc(a + b*x))/(5*b*c*(c*sec(a + b*x))**(sympy.S(3)/2)) - 2*d*(d*csc(a + b*x))**(sympy.S(5)/2)/(5*b*c*(c*sec(a + b*x))**(sympy.S(3)/2)) + 6*d**4*elliptic_e(a + b*x - pi/4, 2)/(5*b*c**2*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(d*csc(a + b*x))**(sympy.S(5)/2)/(c*sec(a + b*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=13,
        integral=-2*d*(d*csc(a + b*x))**(sympy.S(3)/2)/(3*b*c*(c*sec(a + b*x))**(sympy.S(3)/2)) + sqrt(2)*d**2*sqrt(d*csc(a + b*x))*log(-sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)*sqrt(tan(a + b*x))/(4*b*c**2*sqrt(c*sec(a + b*x))) - sqrt(2)*d**2*sqrt(d*csc(a + b*x))*log(sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)*sqrt(tan(a + b*x))/(4*b*c**2*sqrt(c*sec(a + b*x))) - sqrt(2)*d**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) - 1)/(2*b*c**2*sqrt(c*sec(a + b*x))) - sqrt(2)*d**2*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) + 1)/(2*b*c**2*sqrt(c*sec(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(d*csc(a + b*x))**(sympy.S(3)/2)/(c*sec(a + b*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=-2*d*sqrt(d*csc(a + b*x))/(b*c*(c*sec(a + b*x))**(sympy.S(3)/2)) - 3*d**2*elliptic_e(a + b*x - pi/4, 2)/(b*c**2*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(d*csc(a + b*x))/(c*sec(a + b*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=13,
        integral=d/(2*b*c*(c*sec(a + b*x))**(sympy.S(3)/2)*sqrt(d*csc(a + b*x))) - 3*sqrt(2)*sqrt(d*csc(a + b*x))*log(-sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)*sqrt(tan(a + b*x))/(16*b*c**2*sqrt(c*sec(a + b*x))) + 3*sqrt(2)*sqrt(d*csc(a + b*x))*log(sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)*sqrt(tan(a + b*x))/(16*b*c**2*sqrt(c*sec(a + b*x))) + 3*sqrt(2)*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) - 1)/(8*b*c**2*sqrt(c*sec(a + b*x))) + 3*sqrt(2)*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) + 1)/(8*b*c**2*sqrt(c*sec(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((c*sec(a + b*x))**(sympy.S(5)/2)*sqrt(d*csc(a + b*x))),
        variable=x,
        num_steps=4,
        integral=d/(3*b*c*(c*sec(a + b*x))**(sympy.S(3)/2)*(d*csc(a + b*x))**(sympy.S(3)/2)) + elliptic_e(a + b*x - pi/4, 2)/(2*b*c**2*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((c*sec(a + b*x))**(sympy.S(5)/2)*(d*csc(a + b*x))**(sympy.S(3)/2)),
        variable=x,
        num_steps=14,
        integral=-c/(4*b*d*(c*sec(a + b*x))**(sympy.S(7)/2)*sqrt(d*csc(a + b*x))) + 1/(16*b*c*d*(c*sec(a + b*x))**(sympy.S(3)/2)*sqrt(d*csc(a + b*x))) - 3*sqrt(2)*sqrt(d*csc(a + b*x))*log(-sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)*sqrt(tan(a + b*x))/(128*b*c**2*d**2*sqrt(c*sec(a + b*x))) + 3*sqrt(2)*sqrt(d*csc(a + b*x))*log(sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)*sqrt(tan(a + b*x))/(128*b*c**2*d**2*sqrt(c*sec(a + b*x))) + 3*sqrt(2)*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) - 1)/(64*b*c**2*d**2*sqrt(c*sec(a + b*x))) + 3*sqrt(2)*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) + 1)/(64*b*c**2*d**2*sqrt(c*sec(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((c*sec(a + b*x))**(sympy.S(5)/2)*(d*csc(a + b*x))**(sympy.S(5)/2)),
        variable=x,
        num_steps=5,
        integral=-c/(5*b*d*(c*sec(a + b*x))**(sympy.S(7)/2)*(d*csc(a + b*x))**(sympy.S(3)/2)) + 1/(10*b*c*d*(c*sec(a + b*x))**(sympy.S(3)/2)*(d*csc(a + b*x))**(sympy.S(3)/2)) + 3*elliptic_e(a + b*x - pi/4, 2)/(20*b*c**2*d**2*sqrt(c*sec(a + b*x))*sqrt(d*csc(a + b*x))*sqrt(sin(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((c*sec(a + b*x))**(sympy.S(5)/2)*(d*csc(a + b*x))**(sympy.S(7)/2)),
        variable=x,
        num_steps=15,
        integral=-c/(6*b*d*(c*sec(a + b*x))**(sympy.S(7)/2)*(d*csc(a + b*x))**(sympy.S(5)/2)) - 5*c/(48*b*d**3*(c*sec(a + b*x))**(sympy.S(7)/2)*sqrt(d*csc(a + b*x))) + 5/(192*b*c*d**3*(c*sec(a + b*x))**(sympy.S(3)/2)*sqrt(d*csc(a + b*x))) - 5*sqrt(2)*sqrt(d*csc(a + b*x))*log(-sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)*sqrt(tan(a + b*x))/(512*b*c**2*d**4*sqrt(c*sec(a + b*x))) + 5*sqrt(2)*sqrt(d*csc(a + b*x))*log(sqrt(2)*sqrt(tan(a + b*x)) + tan(a + b*x) + 1)*sqrt(tan(a + b*x))/(512*b*c**2*d**4*sqrt(c*sec(a + b*x))) + 5*sqrt(2)*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) - 1)/(256*b*c**2*d**4*sqrt(c*sec(a + b*x))) + 5*sqrt(2)*sqrt(d*csc(a + b*x))*sqrt(tan(a + b*x))*atan(sqrt(2)*sqrt(tan(a + b*x)) + 1)/(256*b*c**2*d**4*sqrt(c*sec(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=csc(e + f*x)**n*sec(e + f*x)**m,
        variable=x,
        num_steps=2,
        integral=(cos(e + f*x)**2)**(m/2 + sympy.S.Half)*csc(e + f*x)**(n - 1)*hyper((sympy.S.Half - n/2, m/2 + sympy.S.Half), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)*sec(e + f*x)**(m + 1)/(f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(e + f*x))**m*csc(e + f*x)**n,
        variable=x,
        num_steps=2,
        integral=(a*sec(e + f*x))**(m + 1)*(cos(e + f*x)**2)**(m/2 + sympy.S.Half)*csc(e + f*x)**(n - 1)*hyper((sympy.S.Half - n/2, m/2 + sympy.S.Half), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)/(a*f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*sec(e + f*x)**m,
        variable=x,
        num_steps=2,
        integral=b*(b*csc(e + f*x))**(n - 1)*(cos(e + f*x)**2)**(m/2 + sympy.S.Half)*hyper((sympy.S.Half - n/2, m/2 + sympy.S.Half), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)*sec(e + f*x)**(m + 1)/(f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sec(e + f*x))**m*(b*csc(e + f*x))**n,
        variable=x,
        num_steps=2,
        integral=b*(a*sec(e + f*x))**(m + 1)*(b*csc(e + f*x))**(n - 1)*(cos(e + f*x)**2)**(m/2 + sympy.S.Half)*hyper((sympy.S.Half - n/2, m/2 + sympy.S.Half), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)/(a*f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*sec(e + f*x)**5,
        variable=x,
        num_steps=2,
        integral=(b*csc(e + f*x))**(n + 5)*hyper((3, n/2 + sympy.S(5)/2), (n/2 + sympy.S(7)/2,), csc(e + f*x)**2)/(b**5*f*(n + 5)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*sec(e + f*x)**3,
        variable=x,
        num_steps=2,
        integral=-(b*csc(e + f*x))**(n + 3)*hyper((2, n/2 + sympy.S(3)/2), (n/2 + sympy.S(5)/2,), csc(e + f*x)**2)/(b**3*f*(n + 3)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*sec(e + f*x),
        variable=x,
        num_steps=2,
        integral=(b*csc(e + f*x))**(n + 1)*hyper((1, n/2 + sympy.S.Half), (n/2 + sympy.S(3)/2,), csc(e + f*x)**2)/(b*f*(n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*cos(e + f*x),
        variable=x,
        num_steps=2,
        integral=b*(b*csc(e + f*x))**(n - 1)/(f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*cos(e + f*x)**3,
        variable=x,
        num_steps=3,
        integral=-b**3*(b*csc(e + f*x))**(n - 3)/(f*(3 - n)) + b*(b*csc(e + f*x))**(n - 1)/(f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*cos(e + f*x)**5,
        variable=x,
        num_steps=3,
        integral=b**5*(b*csc(e + f*x))**(n - 5)/(f*(5 - n)) - 2*b**3*(b*csc(e + f*x))**(n - 3)/(f*(3 - n)) + b*(b*csc(e + f*x))**(n - 1)/(f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*sec(e + f*x)**6,
        variable=x,
        num_steps=2,
        integral=b*(b*csc(e + f*x))**(n - 1)*sqrt(cos(e + f*x)**2)*hyper((sympy.S(7)/2, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)*sec(e + f*x)/(f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*sec(e + f*x)**4,
        variable=x,
        num_steps=2,
        integral=b*(b*csc(e + f*x))**(n - 1)*sqrt(cos(e + f*x)**2)*hyper((sympy.S(5)/2, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)*sec(e + f*x)/(f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*sec(e + f*x)**2,
        variable=x,
        num_steps=2,
        integral=b*(b*csc(e + f*x))**(n - 1)*sqrt(cos(e + f*x)**2)*hyper((sympy.S(3)/2, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)*sec(e + f*x)/(f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n,
        variable=x,
        num_steps=2,
        integral=b*(b*csc(e + f*x))**(n - 1)*cos(e + f*x)*hyper((sympy.S.Half, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)/(f*(1 - n)*sqrt(cos(e + f*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*cos(e + f*x)**2,
        variable=x,
        num_steps=2,
        integral=b*(b*csc(e + f*x))**(n - 1)*cos(e + f*x)*hyper((sympy.S(-1)/2, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)/(f*(1 - n)*sqrt(cos(e + f*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*cos(e + f*x)**4,
        variable=x,
        num_steps=2,
        integral=b*(b*csc(e + f*x))**(n - 1)*cos(e + f*x)*hyper((sympy.S(-3)/2, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)/(f*(1 - n)*sqrt(cos(e + f*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*(c*sec(e + f*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=b*(b*csc(e + f*x))**(n - 1)*(c*sec(e + f*x))**(sympy.S(5)/2)*(cos(e + f*x)**2)**(sympy.S(5)/4)*hyper((sympy.S(5)/4, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)/(c*f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*sqrt(c*sec(e + f*x)),
        variable=x,
        num_steps=2,
        integral=b*(b*csc(e + f*x))**(n - 1)*(c*sec(e + f*x))**(sympy.S(3)/2)*(cos(e + f*x)**2)**(sympy.S(3)/4)*hyper((sympy.S(3)/4, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)/(c*f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n/sqrt(c*sec(e + f*x)),
        variable=x,
        num_steps=2,
        integral=b*(b*csc(e + f*x))**(n - 1)*sqrt(c*sec(e + f*x))*(cos(e + f*x)**2)**(sympy.S(1)/4)*hyper((sympy.S(1)/4, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)/(c*f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n/(c*sec(e + f*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=b*(b*csc(e + f*x))**(n - 1)*hyper((sympy.S(-1)/4, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)/(c*f*sqrt(c*sec(e + f*x))*(1 - n)*(cos(e + f*x)**2)**(sympy.S(1)/4)),
    ),
]
