# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 6 Hyperbolic functions/6.6 Hyperbolic cosecant/6.6.3 Hyperbolic cosecant functions.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '6 Hyperbolic functions/6.6 Hyperbolic cosecant/6.6.3 Hyperbolic cosecant functions.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, c, d, n, p = symbols('a b c d n p')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=csch(a + b*x),
        variable=x,
        num_steps=1,
        integral=-atanh(cosh(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*x)**2,
        variable=x,
        num_steps=2,
        integral=-coth(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*x)**3,
        variable=x,
        num_steps=2,
        integral=-coth(a + b*x)*csch(a + b*x)/(2*b) + atanh(cosh(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*x)**4,
        variable=x,
        num_steps=2,
        integral=-coth(a + b*x)**3/(3*b) + coth(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*x)**5,
        variable=x,
        num_steps=3,
        integral=-coth(a + b*x)*csch(a + b*x)**3/(4*b) + 3*coth(a + b*x)*csch(a + b*x)/(8*b) - 3*atanh(cosh(a + b*x))/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*x)**6,
        variable=x,
        num_steps=2,
        integral=-coth(a + b*x)**5/(5*b) + 2*coth(a + b*x)**3/(3*b) - coth(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*I*sqrt(I*sinh(a + b*x))*sqrt(csch(a + b*x))*elliptic_f(I*a/2 + I*b*x/2 - pi/4, 2)/(3*b) - 2*cosh(a + b*x)*csch(a + b*x)**(sympy.S(3)/2)/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-2*cosh(a + b*x)*sqrt(csch(a + b*x))/b - 2*I*elliptic_e(I*a/2 + I*b*x/2 - pi/4, 2)/(b*sqrt(I*sinh(a + b*x))*sqrt(csch(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(csch(a + b*x)),
        variable=x,
        num_steps=2,
        integral=-2*I*sqrt(I*sinh(a + b*x))*sqrt(csch(a + b*x))*elliptic_f(I*a/2 + I*b*x/2 - pi/4, 2)/b,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(csch(a + b*x)),
        variable=x,
        num_steps=2,
        integral=-2*I*elliptic_e(I*a/2 + I*b*x/2 - pi/4, 2)/(b*sqrt(I*sinh(a + b*x))*sqrt(csch(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*x)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*I*sqrt(I*sinh(a + b*x))*sqrt(csch(a + b*x))*elliptic_f(I*a/2 + I*b*x/2 - pi/4, 2)/(3*b) + 2*cosh(a + b*x)/(3*b*sqrt(csch(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*x)**(sympy.S(-5)/2),
        variable=x,
        num_steps=3,
        integral=2*cosh(a + b*x)/(5*b*csch(a + b*x)**(sympy.S(3)/2)) + 6*I*elliptic_e(I*a/2 + I*b*x/2 - pi/4, 2)/(5*b*sqrt(I*sinh(a + b*x))*sqrt(csch(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*csch(c + d*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=4,
        integral=6*I*b**4*elliptic_e(I*c/2 + I*d*x/2 - pi/4, 2)/(5*d*sqrt(I*sinh(c + d*x))*sqrt(b*csch(c + d*x))) + 6*b**3*sqrt(b*csch(c + d*x))*cosh(c + d*x)/(5*d) - 2*b*(b*csch(c + d*x))**(sympy.S(5)/2)*cosh(c + d*x)/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*csch(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*I*b**2*sqrt(I*sinh(c + d*x))*sqrt(b*csch(c + d*x))*elliptic_f(I*c/2 + I*d*x/2 - pi/4, 2)/(3*d) - 2*b*(b*csch(c + d*x))**(sympy.S(3)/2)*cosh(c + d*x)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*csch(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-2*I*b**2*elliptic_e(I*c/2 + I*d*x/2 - pi/4, 2)/(d*sqrt(I*sinh(c + d*x))*sqrt(b*csch(c + d*x))) - 2*b*sqrt(b*csch(c + d*x))*cosh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*csch(c + d*x)),
        variable=x,
        num_steps=2,
        integral=-2*I*sqrt(I*sinh(c + d*x))*sqrt(b*csch(c + d*x))*elliptic_f(I*c/2 + I*d*x/2 - pi/4, 2)/d,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(b*csch(c + d*x)),
        variable=x,
        num_steps=2,
        integral=-2*I*elliptic_e(I*c/2 + I*d*x/2 - pi/4, 2)/(d*sqrt(I*sinh(c + d*x))*sqrt(b*csch(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*csch(c + d*x))**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*cosh(c + d*x)/(3*b*d*sqrt(b*csch(c + d*x))) + 2*I*sqrt(I*sinh(c + d*x))*sqrt(b*csch(c + d*x))*elliptic_f(I*c/2 + I*d*x/2 - pi/4, 2)/(3*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*csch(c + d*x))**(sympy.S(-5)/2),
        variable=x,
        num_steps=3,
        integral=2*cosh(c + d*x)/(5*b*d*(b*csch(c + d*x))**(sympy.S(3)/2)) + 6*I*elliptic_e(I*c/2 + I*d*x/2 - pi/4, 2)/(5*b**2*d*sqrt(I*sinh(c + d*x))*sqrt(b*csch(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*csch(c + d*x))**(sympy.S(-7)/2),
        variable=x,
        num_steps=4,
        integral=2*cosh(c + d*x)/(7*b*d*(b*csch(c + d*x))**(sympy.S(5)/2)) - 10*cosh(c + d*x)/(21*b**3*d*sqrt(b*csch(c + d*x))) - 10*I*sqrt(I*sinh(c + d*x))*sqrt(b*csch(c + d*x))*elliptic_f(I*c/2 + I*d*x/2 - pi/4, 2)/(21*b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*csch(c + d*x))**n,
        variable=x,
        num_steps=2,
        integral=b*(b*csch(c + d*x))**(n - 1)*cosh(c + d*x)*hyper((sympy.S.Half, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), -sinh(c + d*x)**2)/(d*(1 - n)*sqrt(cosh(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(-csch(x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=(-csch(x)**2)**(sympy.S(3)/2)*coth(x)/4 + 3*sqrt(-csch(x)**2)*coth(x)/8 + 3*asin(coth(x))/8,
    ),
    RubiTestSuiteCase(
        integrand=(-csch(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=sqrt(-csch(x)**2)*coth(x)/2 + asin(coth(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-csch(x)**2),
        variable=x,
        num_steps=2,
        integral=asin(coth(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-csch(x)**2),
        variable=x,
        num_steps=2,
        integral=coth(x)/sqrt(-csch(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=(-csch(x)**2)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*coth(x)/(3*sqrt(-csch(x)**2)) + coth(x)/(3*(-csch(x)**2)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(-csch(x)**2)**(sympy.S(-5)/2),
        variable=x,
        num_steps=4,
        integral=8*coth(x)/(15*sqrt(-csch(x)**2)) + 4*coth(x)/(15*(-csch(x)**2)**(sympy.S(3)/2)) + coth(x)/(5*(-csch(x)**2)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(-csch(x)**2)**(sympy.S(-7)/2),
        variable=x,
        num_steps=5,
        integral=16*coth(x)/(35*sqrt(-csch(x)**2)) + 8*coth(x)/(35*(-csch(x)**2)**(sympy.S(3)/2)) + 6*coth(x)/(35*(-csch(x)**2)**(sympy.S(5)/2)) + coth(x)/(7*(-csch(x)**2)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*csch(x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=-3*a**(sympy.S(5)/2)*atanh(sqrt(a)*coth(x)/sqrt(a*csch(x)**2))/8 + 3*a**2*sqrt(a*csch(x)**2)*coth(x)/8 - a*(a*csch(x)**2)**(sympy.S(3)/2)*coth(x)/4,
    ),
    RubiTestSuiteCase(
        integrand=(a*csch(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=a**(sympy.S(3)/2)*atanh(sqrt(a)*coth(x)/sqrt(a*csch(x)**2))/2 - a*sqrt(a*csch(x)**2)*coth(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*csch(x)**2),
        variable=x,
        num_steps=3,
        integral=-sqrt(a)*atanh(sqrt(a)*coth(x)/sqrt(a*csch(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*csch(x)**2),
        variable=x,
        num_steps=2,
        integral=coth(x)/sqrt(a*csch(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=(a*csch(x)**2)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=coth(x)/(3*(a*csch(x)**2)**(sympy.S(3)/2)) - 2*coth(x)/(3*a*sqrt(a*csch(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*csch(x)**2)**(sympy.S(-5)/2),
        variable=x,
        num_steps=4,
        integral=coth(x)/(5*(a*csch(x)**2)**(sympy.S(5)/2)) - 4*coth(x)/(15*a*(a*csch(x)**2)**(sympy.S(3)/2)) + 8*coth(x)/(15*a**2*sqrt(a*csch(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*csch(x)**2)**(sympy.S(-7)/2),
        variable=x,
        num_steps=5,
        integral=coth(x)/(7*(a*csch(x)**2)**(sympy.S(7)/2)) - 6*coth(x)/(35*a*(a*csch(x)**2)**(sympy.S(5)/2)) + 8*coth(x)/(35*a**2*(a*csch(x)**2)**(sympy.S(3)/2)) - 16*coth(x)/(35*a**3*sqrt(a*csch(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*csch(x)**3)**(sympy.S(5)/2),
        variable=x,
        num_steps=7,
        integral=154*a**2*sqrt(a*csch(x)**3)*sinh(x)*cosh(x)/195 - 2*a**2*sqrt(a*csch(x)**3)*coth(x)*csch(x)**4/13 + 22*a**2*sqrt(a*csch(x)**3)*coth(x)*csch(x)**2/117 - 154*a**2*sqrt(a*csch(x)**3)*coth(x)/585 + 154*I*a**2*sqrt(a*csch(x)**3)*sinh(x)**2*elliptic_e(I*x/2 - pi/4, 2)/(195*sqrt(I*sinh(x))),
    ),
    RubiTestSuiteCase(
        integrand=(a*csch(x)**3)**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=-10*I*a*sqrt(I*sinh(x))*sqrt(a*csch(x)**3)*sinh(x)*elliptic_f(I*x/2 - pi/4, 2)/21 + 10*a*sqrt(a*csch(x)**3)*cosh(x)/21 - 2*a*sqrt(a*csch(x)**3)*coth(x)*csch(x)/7,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*csch(x)**3),
        variable=x,
        num_steps=4,
        integral=2*I*sqrt(I*sinh(x))*csch(x)**2*elliptic_f(I*x/2 - pi/4, 2)/(3*sqrt(a*csch(x)**3)) + 2*coth(x)/(3*sqrt(a*csch(x)**3)),
    ),
    RubiTestSuiteCase(
        integrand=(a*csch(x)**3)**(sympy.S(-3)/2),
        variable=x,
        num_steps=5,
        integral=2*sinh(x)**2*cosh(x)/(9*a*sqrt(a*csch(x)**3)) - 14*cosh(x)/(45*a*sqrt(a*csch(x)**3)) - 14*I*csch(x)*elliptic_e(I*x/2 - pi/4, 2)/(15*a*sqrt(I*sinh(x))*sqrt(a*csch(x)**3)),
    ),
    RubiTestSuiteCase(
        integrand=(a*csch(x)**3)**(sympy.S(-5)/2),
        variable=x,
        num_steps=7,
        integral=-26*I*sqrt(I*sinh(x))*csch(x)**2*elliptic_f(I*x/2 - pi/4, 2)/(77*a**2*sqrt(a*csch(x)**3)) + 2*sinh(x)**5*cosh(x)/(15*a**2*sqrt(a*csch(x)**3)) - 26*sinh(x)**3*cosh(x)/(165*a**2*sqrt(a*csch(x)**3)) + 78*sinh(x)*cosh(x)/(385*a**2*sqrt(a*csch(x)**3)) - 26*coth(x)/(77*a**2*sqrt(a*csch(x)**3)),
    ),
    RubiTestSuiteCase(
        integrand=(a*csch(x)**4)**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=-a**3*sqrt(a*csch(x)**4)*sinh(x)*cosh(x) - a**3*sqrt(a*csch(x)**4)*cosh(x)**2*coth(x)**11/13 + 6*a**3*sqrt(a*csch(x)**4)*cosh(x)**2*coth(x)**9/11 - 5*a**3*sqrt(a*csch(x)**4)*cosh(x)**2*coth(x)**7/3 + 20*a**3*sqrt(a*csch(x)**4)*cosh(x)**2*coth(x)**5/7 - 3*a**3*sqrt(a*csch(x)**4)*cosh(x)**2*coth(x)**3 + 2*a**3*sqrt(a*csch(x)**4)*cosh(x)**2*coth(x),
    ),
    RubiTestSuiteCase(
        integrand=(a*csch(x)**4)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=-a**2*sqrt(a*csch(x)**4)*sinh(x)*cosh(x) - a**2*sqrt(a*csch(x)**4)*cosh(x)**2*coth(x)**7/9 + 4*a**2*sqrt(a*csch(x)**4)*cosh(x)**2*coth(x)**5/7 - 6*a**2*sqrt(a*csch(x)**4)*cosh(x)**2*coth(x)**3/5 + 4*a**2*sqrt(a*csch(x)**4)*cosh(x)**2*coth(x)/3,
    ),
    RubiTestSuiteCase(
        integrand=(a*csch(x)**4)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-a*sqrt(a*csch(x)**4)*sinh(x)*cosh(x) - a*sqrt(a*csch(x)**4)*cosh(x)**2*coth(x)**3/5 + 2*a*sqrt(a*csch(x)**4)*cosh(x)**2*coth(x)/3,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*csch(x)**4),
        variable=x,
        num_steps=3,
        integral=-sqrt(a*csch(x)**4)*sinh(x)*cosh(x),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*csch(x)**4),
        variable=x,
        num_steps=3,
        integral=-x*csch(x)**2/(2*sqrt(a*csch(x)**4)) + coth(x)/(2*sqrt(a*csch(x)**4)),
    ),
    RubiTestSuiteCase(
        integrand=(a*csch(x)**4)**(sympy.S(-3)/2),
        variable=x,
        num_steps=5,
        integral=-5*x*csch(x)**2/(16*a*sqrt(a*csch(x)**4)) + sinh(x)**3*cosh(x)/(6*a*sqrt(a*csch(x)**4)) - 5*sinh(x)*cosh(x)/(24*a*sqrt(a*csch(x)**4)) + 5*coth(x)/(16*a*sqrt(a*csch(x)**4)),
    ),
    RubiTestSuiteCase(
        integrand=(a*csch(x)**4)**(sympy.S(-5)/2),
        variable=x,
        num_steps=7,
        integral=-63*x*csch(x)**2/(256*a**2*sqrt(a*csch(x)**4)) + sinh(x)**7*cosh(x)/(10*a**2*sqrt(a*csch(x)**4)) - 9*sinh(x)**5*cosh(x)/(80*a**2*sqrt(a*csch(x)**4)) + 21*sinh(x)**3*cosh(x)/(160*a**2*sqrt(a*csch(x)**4)) - 21*sinh(x)*cosh(x)/(128*a**2*sqrt(a*csch(x)**4)) + 63*coth(x)/(256*a**2*sqrt(a*csch(x)**4)),
    ),
    RubiTestSuiteCase(
        integrand=1/(I*a*csch(a + b*x) + a),
        variable=x,
        num_steps=2,
        integral=-coth(a + b*x)/(b*(I*a*csch(a + b*x) + a)) + x/a,
    ),
    RubiTestSuiteCase(
        integrand=1/(-I*a*csch(a + b*x) + a),
        variable=x,
        num_steps=2,
        integral=-coth(a + b*x)/(b*(-I*a*csch(a + b*x) + a)) + x/a,
    ),
    RubiTestSuiteCase(
        integrand=(I*a*csch(c + d*x) + a)**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=2*a**(sympy.S(5)/2)*atanh(sqrt(a)*coth(c + d*x)/sqrt(I*a*csch(c + d*x) + a))/d + 14*a**3*coth(c + d*x)/(3*d*sqrt(I*a*csch(c + d*x) + a)) + 2*a**2*sqrt(I*a*csch(c + d*x) + a)*coth(c + d*x)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(I*a*csch(c + d*x) + a)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=2*a**(sympy.S(3)/2)*atanh(sqrt(a)*coth(c + d*x)/sqrt(I*a*csch(c + d*x) + a))/d + 2*a**2*coth(c + d*x)/(d*sqrt(I*a*csch(c + d*x) + a)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(I*a*csch(c + d*x) + a),
        variable=x,
        num_steps=2,
        integral=2*sqrt(a)*atanh(sqrt(a)*coth(c + d*x)/sqrt(I*a*csch(c + d*x) + a))/d,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(I*a*csch(c + d*x) + a),
        variable=x,
        num_steps=5,
        integral=2*atanh(sqrt(a)*coth(c + d*x)/sqrt(I*a*csch(c + d*x) + a))/(sqrt(a)*d) - sqrt(2)*atanh(sqrt(2)*sqrt(a)*coth(c + d*x)/(2*sqrt(I*a*csch(c + d*x) + a)))/(sqrt(a)*d),
    ),
    RubiTestSuiteCase(
        integrand=(I*a*csch(c + d*x) + a)**(sympy.S(-3)/2),
        variable=x,
        num_steps=6,
        integral=-coth(c + d*x)/(2*d*(I*a*csch(c + d*x) + a)**(sympy.S(3)/2)) + 2*atanh(sqrt(a)*coth(c + d*x)/sqrt(I*a*csch(c + d*x) + a))/(a**(sympy.S(3)/2)*d) - 5*sqrt(2)*atanh(sqrt(2)*sqrt(a)*coth(c + d*x)/(2*sqrt(I*a*csch(c + d*x) + a)))/(4*a**(sympy.S(3)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-I*a*csch(c + d*x) + a),
        variable=x,
        num_steps=2,
        integral=2*sqrt(a)*atanh(sqrt(a)*coth(c + d*x)/sqrt(-I*a*csch(c + d*x) + a))/d,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-I*a*csch(c + d*x) + a),
        variable=x,
        num_steps=5,
        integral=2*atanh(sqrt(a)*coth(c + d*x)/sqrt(-I*a*csch(c + d*x) + a))/(sqrt(a)*d) - sqrt(2)*atanh(sqrt(2)*sqrt(a)*coth(c + d*x)/(2*sqrt(-I*a*csch(c + d*x) + a)))/(sqrt(a)*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(3*I*csch(x) + 3),
        variable=x,
        num_steps=2,
        integral=2*sqrt(3)*atanh(coth(x)/sqrt(I*csch(x) + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-3*I*csch(x) + 3),
        variable=x,
        num_steps=2,
        integral=2*sqrt(3)*atanh(coth(x)/sqrt(-I*csch(x) + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(3*I*csch(x) - 3),
        variable=x,
        num_steps=2,
        integral=-2*sqrt(3)*atan(coth(x)/sqrt(I*csch(x) - 1)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-3*I*csch(x) - 3),
        variable=x,
        num_steps=2,
        integral=-2*sqrt(3)*atan(coth(x)/sqrt(-I*csch(x) - 1)),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**4/(csch(x) + I),
        variable=x,
        num_steps=7,
        integral=-15*I*x/8 - 5*I*sinh(x)**3*cosh(x)/4 + 15*I*sinh(x)*cosh(x)/8 + 4*cosh(x)**3/3 - 4*cosh(x) - sinh(x)**3*cosh(x)/(csch(x) + I),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**3/(csch(x) + I),
        variable=x,
        num_steps=6,
        integral=-3*x/2 + 3*sinh(x)*cosh(x)/2 - 4*I*cosh(x)**3/3 + 4*I*cosh(x) - sinh(x)**2*cosh(x)/(csch(x) + I),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**2/(csch(x) + I),
        variable=x,
        num_steps=5,
        integral=3*I*x/2 - 3*I*sinh(x)*cosh(x)/2 + 2*cosh(x) - sinh(x)*cosh(x)/(csch(x) + I),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)/(csch(x) + I),
        variable=x,
        num_steps=4,
        integral=x - 2*I*cosh(x) - cosh(x)/(csch(x) + I),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)/(csch(x) + I),
        variable=x,
        num_steps=1,
        integral=I*coth(x)/(csch(x) + I),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**2/(csch(x) + I),
        variable=x,
        num_steps=3,
        integral=-atanh(cosh(x)) + coth(x)/(csch(x) + I),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**3/(csch(x) + I),
        variable=x,
        num_steps=4,
        integral=-coth(x) + I*atanh(cosh(x)) - I*coth(x)/(csch(x) + I),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**4/(csch(x) + I),
        variable=x,
        num_steps=6,
        integral=-3*coth(x)*csch(x)/2 + 2*I*coth(x) + 3*atanh(cosh(x))/2 + coth(x)*csch(x)**2/(csch(x) + I),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*csch(c + d*x))**4,
        variable=x,
        num_steps=6,
        integral=a**4*x - 4*a*b**3*coth(c + d*x)*csch(c + d*x)/(3*d) - 2*a*b*(2*a**2 - b**2)*atanh(cosh(c + d*x))/d - b**2*(a + b*csch(c + d*x))**2*coth(c + d*x)/(3*d) - b**2*(17*a**2 - 2*b**2)*coth(c + d*x)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*csch(c + d*x))**3,
        variable=x,
        num_steps=5,
        integral=a**3*x - 5*a*b**2*coth(c + d*x)/(2*d) - b**2*(a + b*csch(c + d*x))*coth(c + d*x)/(2*d) - b*(6*a**2 - b**2)*atanh(cosh(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*csch(c + d*x))**2,
        variable=x,
        num_steps=4,
        integral=a**2*x - 2*a*b*atanh(cosh(c + d*x))/d - b**2*coth(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=a + b*csch(c + d*x),
        variable=x,
        num_steps=2,
        integral=a*x - b*atanh(cosh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*csch(c + d*x)),
        variable=x,
        num_steps=4,
        integral=2*b*atanh((a - b*tanh(c/2 + d*x/2))/sqrt(a**2 + b**2))/(a*d*sqrt(a**2 + b**2)) + x/a,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*csch(c + d*x))**(-2),
        variable=x,
        num_steps=6,
        integral=-b**2*coth(c + d*x)/(a*d*(a + b*csch(c + d*x))*(a**2 + b**2)) + 2*b*(2*a**2 + b**2)*atanh((a - b*tanh(c/2 + d*x/2))/sqrt(a**2 + b**2))/(a**2*d*(a**2 + b**2)**(sympy.S(3)/2)) + x/a**2,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*csch(c + d*x))**(-3),
        variable=x,
        num_steps=7,
        integral=-b**2*coth(c + d*x)/(2*a*d*(a + b*csch(c + d*x))**2*(a**2 + b**2)) - b**2*(5*a**2 + 2*b**2)*coth(c + d*x)/(2*a**2*d*(a + b*csch(c + d*x))*(a**2 + b**2)**2) + b*(6*a**4 + 5*a**2*b**2 + 2*b**4)*atanh((a - b*tanh(c/2 + d*x/2))/sqrt(a**2 + b**2))/(a**3*d*(a**2 + b**2)**(sympy.S(5)/2)) + x/a**3,
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**3/(a + b*csch(x)),
        variable=x,
        num_steps=8,
        integral=sinh(x)**2*cosh(x)/(3*a) - b*sinh(x)*cosh(x)/(2*a**2) - (2*a**2 - 3*b**2)*cosh(x)/(3*a**3) - 2*b**4*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/(a**4*sqrt(a**2 + b**2)) + b*x*(a**2 - 2*b**2)/(2*a**4),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**2/(a + b*csch(x)),
        variable=x,
        num_steps=7,
        integral=sinh(x)*cosh(x)/(2*a) - b*cosh(x)/a**2 + 2*b**3*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/(a**3*sqrt(a**2 + b**2)) - x*(a**2 - 2*b**2)/(2*a**3),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)/(a + b*csch(x)),
        variable=x,
        num_steps=6,
        integral=cosh(x)/a - 2*b**2*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/(a**2*sqrt(a**2 + b**2)) - b*x/a**2,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)/(a + b*csch(x)),
        variable=x,
        num_steps=4,
        integral=-2*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/sqrt(a**2 + b**2),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**2/(a + b*csch(x)),
        variable=x,
        num_steps=6,
        integral=2*a*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/(b*sqrt(a**2 + b**2)) - atanh(cosh(x))/b,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**3/(a + b*csch(x)),
        variable=x,
        num_steps=7,
        integral=-2*a**2*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/(b**2*sqrt(a**2 + b**2)) + a*atanh(cosh(x))/b**2 - coth(x)/b,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**4/(a + b*csch(x)),
        variable=x,
        num_steps=8,
        integral=2*a**3*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/(b**3*sqrt(a**2 + b**2)) + a*coth(x)/b**2 - coth(x)*csch(x)/(2*b) - (2*a**2 - b**2)*atanh(cosh(x))/(2*b**3),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**4/(csch(x) + I),
        variable=x,
        num_steps=7,
        integral=I*x/8 - I*sinh(x)*cosh(x)**3/4 + I*sinh(x)*cosh(x)/8 + cosh(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**3/(csch(x) + I),
        variable=x,
        num_steps=6,
        integral=-I*sinh(x)**3/3 + sinh(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**2/(csch(x) + I),
        variable=x,
        num_steps=5,
        integral=I*x/2 - I*sinh(x)*cosh(x)/2 + cosh(x),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)/(csch(x) + I),
        variable=x,
        num_steps=4,
        integral=log(-sinh(x) + I) - I*sinh(x),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)/(csch(x) + I),
        variable=x,
        num_steps=6,
        integral=I*tanh(x)*sech(x)/2 - I*atan(sinh(x))/2 - sech(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**2/(csch(x) + I),
        variable=x,
        num_steps=6,
        integral=-I*tanh(x)**3/3 - sech(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**3/(csch(x) + I),
        variable=x,
        num_steps=7,
        integral=I*tanh(x)*sech(x)**3/4 - I*tanh(x)*sech(x)/8 - I*atan(sinh(x))/8 - sech(x)**4/4,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**4/(csch(x) + I),
        variable=x,
        num_steps=7,
        integral=I*tanh(x)**5/5 - I*tanh(x)**3/3 - sech(x)**5/5,
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**5/(a + b*csch(x)),
        variable=x,
        num_steps=5,
        integral=sinh(x)**5/(5*a) - b*sinh(x)**4/(4*a**2) + (2*a**2 + b**2)*sinh(x)**3/(3*a**3) - b*(2*a**2 + b**2)*sinh(x)**2/(2*a**4) + (a**2 + b**2)**2*sinh(x)/a**5 - b*(a**2 + b**2)**2*log(a*sinh(x) + b)/a**6,
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**4/(a + b*csch(x)),
        variable=x,
        num_steps=7,
        integral=-(-3*a*sinh(x) + 4*b)*cosh(x)**3/(12*a**2) - (-a*(3*a**2 + 4*b**2)*sinh(x) + 8*b*(a**2 + b**2))*cosh(x)/(8*a**4) + 2*b*(a**2 + b**2)**(sympy.S(3)/2)*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/a**5 + x*(3*a**4 + 12*a**2*b**2 + 8*b**4)/(8*a**5),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**3/(a + b*csch(x)),
        variable=x,
        num_steps=5,
        integral=sinh(x)**3/(3*a) - b*sinh(x)**2/(2*a**2) + (a**2 + b**2)*sinh(x)/a**3 - b*(a**2 + b**2)*log(a*sinh(x) + b)/a**4,
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**2/(a + b*csch(x)),
        variable=x,
        num_steps=6,
        integral=-(-a*sinh(x) + 2*b)*cosh(x)/(2*a**2) + 2*b*sqrt(a**2 + b**2)*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/a**3 + x*(a**2 + 2*b**2)/(2*a**3),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)/(a + b*csch(x)),
        variable=x,
        num_steps=5,
        integral=sinh(x)/a - b*log(a*sinh(x) + b)/a**2,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)/(a + b*csch(x)),
        variable=x,
        num_steps=4,
        integral=-b*log(a*sinh(x) + b)/(a**2 + b**2) + log(-sinh(x) + I)/(2*I*a + 2*b) - log(sinh(x) + I)/(2*I*a - 2*b),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**2/(a + b*csch(x)),
        variable=x,
        num_steps=6,
        integral=2*a*b*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/(a**2 + b**2)**(sympy.S(3)/2) - (-a*sinh(x) + b)*sech(x)/(a**2 + b**2),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**3/(a + b*csch(x)),
        variable=x,
        num_steps=6,
        integral=-a**2*b*log(a*sinh(x) + b)/(a**2 + b**2)**2 + I*a*log(sinh(x) + I)/(4*(a + I*b)**2) - I*a*log(-sinh(x) + I)/(4*(a - I*b)**2) - (-a*sinh(x) + b)*sech(x)**2/(2*a**2 + 2*b**2),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**4/(a + b*csch(x)),
        variable=x,
        num_steps=7,
        integral=2*a**3*b*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/(a**2 + b**2)**(sympy.S(5)/2) - (-a*sinh(x) + b)*sech(x)**3/(3*a**2 + 3*b**2) - (3*a**2*b - a*(2*a**2 - b**2)*sinh(x))*sech(x)/(3*(a**2 + b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**5/(a + b*csch(x)),
        variable=x,
        num_steps=7,
        integral=-a**4*b*log(a*sinh(x) + b)/(a**2 + b**2)**3 + a*(3*a + I*b)*log(sinh(x) + I)/(16*(I*a - b)**3) - a*(3*I*a + b)*log(-sinh(x) + I)/(16*(a - I*b)**3) - (-a*sinh(x) + b)*sech(x)**4/(4*a**2 + 4*b**2) - (4*a**2*b - a*(3*a**2 - b**2)*sinh(x))*sech(x)**2/(8*(a**2 + b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**5/(csch(x) + I),
        variable=x,
        num_steps=3,
        integral=-21*I*log(-sinh(x) + I)/32 - 11*I*log(sinh(x) + I)/32 - 15*I/(16*I*sinh(x) + 16) + 9*I/(32*(I*sinh(x) + 1)**2) - I/(24*(I*sinh(x) + 1)**3) + I/(32*(-I*sinh(x) + 1)**2) - I/(-4*I*sinh(x) + 4),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**4/(csch(x) + I),
        variable=x,
        num_steps=5,
        integral=-I*x + (-8*csch(x)/15 + I)*tanh(x) + (-4*csch(x)/15 + I/3)*tanh(x)**3 + (-csch(x)/5 + I/5)*tanh(x)**5,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**3/(csch(x) + I),
        variable=x,
        num_steps=3,
        integral=-11*I*log(-sinh(x) + I)/16 - 5*I*log(sinh(x) + I)/16 - 3*I/(4*I*sinh(x) + 4) + I/(8*(I*sinh(x) + 1)**2) - I/(-8*I*sinh(x) + 8),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**2/(csch(x) + I),
        variable=x,
        num_steps=4,
        integral=-I*x + (-2*csch(x)/3 + I)*tanh(x) + (-csch(x)/3 + I/3)*tanh(x)**3,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/(csch(x) + I),
        variable=x,
        num_steps=3,
        integral=-3*I*log(-sinh(x) + I)/4 - I*log(sinh(x) + I)/4 - I/(2*I*sinh(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/(csch(x) + I),
        variable=x,
        num_steps=2,
        integral=-I*log(-sinh(x) + I),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**2/(csch(x) + I),
        variable=x,
        num_steps=3,
        integral=-I*x - atanh(cosh(x)),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**3/(csch(x) + I),
        variable=x,
        num_steps=3,
        integral=-I*log(sinh(x)) - csch(x),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**4/(csch(x) + I),
        variable=x,
        num_steps=4,
        integral=-I*x + (-csch(x) + 2*I)*coth(x)/2 - atanh(cosh(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**5/(csch(x) + I),
        variable=x,
        num_steps=3,
        integral=-I*log(sinh(x)) - csch(x)**3/3 + I*csch(x)**2/2 - csch(x),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**6/(csch(x) + I),
        variable=x,
        num_steps=5,
        integral=-I*x + (-3*csch(x) + 4*I)*coth(x)**3/12 + (-3*csch(x) + 8*I)*coth(x)/8 - 3*atanh(cosh(x))/8,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**5/(a + b*csch(x)),
        variable=x,
        num_steps=11,
        integral=-a*(a**4 + 3*a**2*b**2 + 3*b**4)*log(tanh(x))/(a**2 + b**2)**3 - b**5*atan(sinh(x))/(a**2 + b**2)**3 - b**3*atan(sinh(x))/(2*(a**2 + b**2)**2) + 3*b*tanh(x)*sech(x)/(8*a**2 + 8*b**2) - 3*b*atan(sinh(x))/(8*a**2 + 8*b**2) - (a - b*csch(x))*tanh(x)**4/(4*a**2 + 4*b**2) - (a*(a**2 + 2*b**2) - b**3*csch(x))*tanh(x)**2/(2*(a**2 + b**2)**2) + b**6*log(a + b*csch(x))/(a*(a**2 + b**2)**3) + log(sinh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**4/(a + b*csch(x)),
        variable=x,
        num_steps=16,
        integral=a*b**2*x/(a**2 + b**2)**2 - a*b**2*tanh(x)/(a**2 + b**2)**2 + a*x/(a**2 + b**2) - a*tanh(x)**3/(3*a**2 + 3*b**2) - a*tanh(x)/(a**2 + b**2) + b**3*sech(x)/(a**2 + b**2)**2 - b*sech(x)**3/(3*a**2 + 3*b**2) + b*sech(x)/(a**2 + b**2) + 2*b**5*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/(a*(a**2 + b**2)**(sympy.S(5)/2)) + b**4*x/(a*(a**2 + b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**3/(a + b*csch(x)),
        variable=x,
        num_steps=8,
        integral=-a*(a**2 + 2*b**2)*log(tanh(x))/(a**2 + b**2)**2 - b**3*atan(sinh(x))/(a**2 + b**2)**2 - b*atan(sinh(x))/(2*a**2 + 2*b**2) - (a - b*csch(x))*tanh(x)**2/(2*a**2 + 2*b**2) + b**4*log(a + b*csch(x))/(a*(a**2 + b**2)**2) + log(sinh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**2/(a + b*csch(x)),
        variable=x,
        num_steps=10,
        integral=a*x/(a**2 + b**2) - a*tanh(x)/(a**2 + b**2) + b*sech(x)/(a**2 + b**2) + 2*b**3*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/(a*(a**2 + b**2)**(sympy.S(3)/2)) + b**2*x/(a*(a**2 + b**2)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/(a + b*csch(x)),
        variable=x,
        num_steps=6,
        integral=-a*log(tanh(x))/(a**2 + b**2) - b*atan(sinh(x))/(a**2 + b**2) + b**2*log(a + b*csch(x))/(a*(a**2 + b**2)) + log(sinh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/(a + b*csch(x)),
        variable=x,
        num_steps=4,
        integral=log(a + b*csch(x))/a + log(sinh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**2/(a + b*csch(x)),
        variable=x,
        num_steps=8,
        integral=-atanh(cosh(x))/b + x/a + 2*sqrt(a**2 + b**2)*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/(a*b),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**3/(a + b*csch(x)),
        variable=x,
        num_steps=3,
        integral=(a/b**2 + 1/a)*log(a + b*csch(x)) - csch(x)/b + log(sinh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**4/(a + b*csch(x)),
        variable=x,
        num_steps=7,
        integral=a*coth(x)/b**2 - coth(x)*csch(x)/(2*b) - (2*a**2 + 3*b**2)*atanh(cosh(x))/(2*b**3) + x/a + 2*(a**2 + b**2)**(sympy.S(3)/2)*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/(a*b**3),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**5/(a + b*csch(x)),
        variable=x,
        num_steps=3,
        integral=a*csch(x)**2/(2*b**2) - csch(x)**3/(3*b) - (a**2 + 2*b**2)*csch(x)/b**3 + log(sinh(x))/a + (a**2 + b**2)**2*log(a + b*csch(x))/(a*b**4),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**6/(a + b*csch(x)),
        variable=x,
        num_steps=16,
        integral=a*coth(x)**3/(3*b**2) - a*coth(x)/b**2 + a*(a**2 + 3*b**2)*coth(x)/b**4 - coth(x)*csch(x)**3/(4*b) + 3*coth(x)*csch(x)/(8*b) - 3*atanh(cosh(x))/(8*b) - (a**2 + 3*b**2)*coth(x)*csch(x)/(2*b**3) + (a**2 + 3*b**2)*atanh(cosh(x))/(2*b**3) - (a**4 + 3*a**2*b**2 + 3*b**4)*atanh(cosh(x))/b**5 + x/a + 2*(a**2 + b**2)**(sympy.S(5)/2)*atanh((a - b*tanh(x/2))/sqrt(a**2 + b**2))/(a*b**5),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**7/(a + b*csch(x)),
        variable=x,
        num_steps=3,
        integral=a*csch(x)**4/(4*b**2) + a*(a**2 + 3*b**2)*csch(x)**2/(2*b**4) - csch(x)**5/(5*b) - (a**2 + 3*b**2)*csch(x)**3/(3*b**3) - (a**4 + 3*a**2*b**2 + 3*b**4)*csch(x)/b**5 + log(sinh(x))/a + (a**2 + b**2)**3*log(a + b*csch(x))/(a*b**6),
    ),
    RubiTestSuiteCase(
        integrand=(csch(a*c + b*c*x)**2)**(sympy.S(7)/2)*exp(c*(a + b*x)),
        variable=x,
        num_steps=6,
        integral=64*sqrt(csch(a*c + b*c*x)**2)*sinh(a*c + b*c*x)/(3*b*c*(1 - exp(2*c*(a + b*x)))**3) - 48*sqrt(csch(a*c + b*c*x)**2)*sinh(a*c + b*c*x)/(b*c*(1 - exp(2*c*(a + b*x)))**4) + 192*sqrt(csch(a*c + b*c*x)**2)*sinh(a*c + b*c*x)/(5*b*c*(1 - exp(2*c*(a + b*x)))**5) - 32*sqrt(csch(a*c + b*c*x)**2)*sinh(a*c + b*c*x)/(3*b*c*(1 - exp(2*c*(a + b*x)))**6),
    ),
    RubiTestSuiteCase(
        integrand=(csch(a*c + b*c*x)**2)**(sympy.S(5)/2)*exp(c*(a + b*x)),
        variable=x,
        num_steps=6,
        integral=-8*sqrt(csch(a*c + b*c*x)**2)*sinh(a*c + b*c*x)/(b*c*(1 - exp(2*c*(a + b*x)))**2) + 32*sqrt(csch(a*c + b*c*x)**2)*sinh(a*c + b*c*x)/(3*b*c*(1 - exp(2*c*(a + b*x)))**3) - 4*sqrt(csch(a*c + b*c*x)**2)*sinh(a*c + b*c*x)/(b*c*(1 - exp(2*c*(a + b*x)))**4),
    ),
    RubiTestSuiteCase(
        integrand=(csch(a*c + b*c*x)**2)**(sympy.S(3)/2)*exp(c*(a + b*x)),
        variable=x,
        num_steps=4,
        integral=-2*sqrt(csch(a*c + b*c*x)**2)*exp(4*c*(a + b*x))*sinh(a*c + b*c*x)/(b*c*(1 - exp(2*c*(a + b*x)))**2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(csch(a*c + b*c*x)**2)*exp(c*(a + b*x)),
        variable=x,
        num_steps=4,
        integral=sqrt(csch(a*c + b*c*x)**2)*log(1 - exp(2*c*(a + b*x)))*sinh(a*c + b*c*x)/(b*c),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))/sqrt(csch(a*c + b*c*x)**2),
        variable=x,
        num_steps=5,
        integral=-x*csch(a*c + b*c*x)/(2*sqrt(csch(a*c + b*c*x)**2)) + exp(2*c*(a + b*x))*csch(a*c + b*c*x)/(4*b*c*sqrt(csch(a*c + b*c*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))/(csch(a*c + b*c*x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=3*x*csch(a*c + b*c*x)/(8*sqrt(csch(a*c + b*c*x)**2)) + exp(4*c*(a + b*x))*csch(a*c + b*c*x)/(32*b*c*sqrt(csch(a*c + b*c*x)**2)) - 3*exp(2*c*(a + b*x))*csch(a*c + b*c*x)/(16*b*c*sqrt(csch(a*c + b*c*x)**2)) + exp(-2*c*(a + b*x))*csch(a*c + b*c*x)/(16*b*c*sqrt(csch(a*c + b*c*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))/(csch(a*c + b*c*x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=6,
        integral=-5*x*csch(a*c + b*c*x)/(16*sqrt(csch(a*c + b*c*x)**2)) + exp(6*c*(a + b*x))*csch(a*c + b*c*x)/(192*b*c*sqrt(csch(a*c + b*c*x)**2)) - 5*exp(4*c*(a + b*x))*csch(a*c + b*c*x)/(128*b*c*sqrt(csch(a*c + b*c*x)**2)) + 5*exp(2*c*(a + b*x))*csch(a*c + b*c*x)/(32*b*c*sqrt(csch(a*c + b*c*x)**2)) - 5*exp(-2*c*(a + b*x))*csch(a*c + b*c*x)/(64*b*c*sqrt(csch(a*c + b*c*x)**2)) + exp(-4*c*(a + b*x))*csch(a*c + b*c*x)/(128*b*c*sqrt(csch(a*c + b*c*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=x**5/sqrt(csch(2*log(c*x))),
        variable=x,
        num_steps=6,
        integral=x**6/(7*sqrt(csch(2*log(c*x)))) - 2*x**2/(21*c**4*sqrt(csch(2*log(c*x)))) + 2*elliptic_f(acsc(c*x), -1)/(21*c**7*x*sqrt(1 - 1/(c**4*x**4))*sqrt(csch(2*log(c*x)))),
    ),
    RubiTestSuiteCase(
        integrand=x**4/sqrt(csch(2*log(c*x))),
        variable=x,
        num_steps=3,
        integral=x**5*(c**4 - 1/x**4)/(6*c**4*sqrt(csch(2*log(c*x)))),
    ),
    RubiTestSuiteCase(
        integrand=x**3/sqrt(csch(2*log(c*x))),
        variable=x,
        num_steps=9,
        integral=x**4/(5*sqrt(csch(2*log(c*x)))) - 2/(5*c**4*sqrt(csch(2*log(c*x)))) - 2*elliptic_e(acsc(c*x), -1)/(5*c**5*x*sqrt(1 - 1/(c**4*x**4))*sqrt(csch(2*log(c*x)))) + 2*elliptic_f(acsc(c*x), -1)/(5*c**5*x*sqrt(1 - 1/(c**4*x**4))*sqrt(csch(2*log(c*x)))),
    ),
    RubiTestSuiteCase(
        integrand=x**2/sqrt(csch(2*log(c*x))),
        variable=x,
        num_steps=6,
        integral=x**3/(4*sqrt(csch(2*log(c*x)))) - atanh(sqrt(1 - 1/(c**4*x**4)))/(4*c**4*x*sqrt(1 - 1/(c**4*x**4))*sqrt(csch(2*log(c*x)))),
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(csch(2*log(c*x))),
        variable=x,
        num_steps=5,
        integral=x**2/(3*sqrt(csch(2*log(c*x)))) + 2*elliptic_f(acsc(c*x), -1)/(3*c**3*x*sqrt(1 - 1/(c**4*x**4))*sqrt(csch(2*log(c*x)))),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(csch(2*log(c*x))),
        variable=x,
        num_steps=6,
        integral=x/(2*sqrt(csch(2*log(c*x)))) + acsc(c**2*x**2)/(2*c**2*x*sqrt(1 - 1/(c**4*x**4))*sqrt(csch(2*log(c*x)))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(csch(2*log(c*x)))/x,
        variable=x,
        num_steps=3,
        integral=-I*sqrt(I*sinh(2*log(c*x)))*sqrt(csch(2*log(c*x)))*elliptic_f(I*log(c*x) - pi/4, 2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(csch(2*log(c*x)))/x**2,
        variable=x,
        num_steps=5,
        integral=-c**2*x*sqrt(1 - 1/(c**4*x**4))*acsc(c**2*x**2)*sqrt(csch(2*log(c*x)))/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(csch(2*log(c*x)))/x**3,
        variable=x,
        num_steps=7,
        integral=-c**3*x*sqrt(1 - 1/(c**4*x**4))*sqrt(csch(2*log(c*x)))*elliptic_e(acsc(c*x), -1) + c**3*x*sqrt(1 - 1/(c**4*x**4))*sqrt(csch(2*log(c*x)))*elliptic_f(acsc(c*x), -1),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(csch(2*log(c*x)))/x**4,
        variable=x,
        num_steps=3,
        integral=x*(c**4/2 - 1/(2*x**4))*sqrt(csch(2*log(c*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(csch(2*log(c*x)))/x**5,
        variable=x,
        num_steps=5,
        integral=-c**5*x*sqrt(1 - 1/(c**4*x**4))*sqrt(csch(2*log(c*x)))*elliptic_f(acsc(c*x), -1)/3 + (c**4/3 - 1/(3*x**4))*sqrt(csch(2*log(c*x))),
    ),
    RubiTestSuiteCase(
        integrand=x**8/csch(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=8,
        integral=x**9/(12*csch(2*log(c*x))**(sympy.S(3)/2)) - x**5/((16*c**4 - 16/x**4)*csch(2*log(c*x))**(sympy.S(3)/2)) + x/(32*c**4*(c**4 - 1/x**4)*csch(2*log(c*x))**(sympy.S(3)/2)) + atanh(sqrt(1 - 1/(c**4*x**4)))/(32*c**12*x**3*(1 - 1/(c**4*x**4))**(sympy.S(3)/2)*csch(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**7/csch(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=7,
        integral=x**8/(11*csch(2*log(c*x))**(sympy.S(3)/2)) - 6*x**4/((77*c**4 - 77/x**4)*csch(2*log(c*x))**(sympy.S(3)/2)) + 4/(77*c**4*(c**4 - 1/x**4)*csch(2*log(c*x))**(sympy.S(3)/2)) - 4*elliptic_f(acsc(c*x), -1)/(77*c**11*x**3*(1 - 1/(c**4*x**4))**(sympy.S(3)/2)*csch(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**6/csch(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=x**7*(c**4 - 1/x**4)/(10*c**4*csch(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**5/csch(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=10,
        integral=x**6/(9*csch(2*log(c*x))**(sympy.S(3)/2)) - 2*x**2/((15*c**4 - 15/x**4)*csch(2*log(c*x))**(sympy.S(3)/2)) + 4/(15*c**4*x**2*(c**4 - 1/x**4)*csch(2*log(c*x))**(sympy.S(3)/2)) + 4*elliptic_e(acsc(c*x), -1)/(15*c**9*x**3*(1 - 1/(c**4*x**4))**(sympy.S(3)/2)*csch(2*log(c*x))**(sympy.S(3)/2)) - 4*elliptic_f(acsc(c*x), -1)/(15*c**9*x**3*(1 - 1/(c**4*x**4))**(sympy.S(3)/2)*csch(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**4/csch(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=7,
        integral=x**5/(8*csch(2*log(c*x))**(sympy.S(3)/2)) - 3*x/((16*c**4 - 16/x**4)*csch(2*log(c*x))**(sympy.S(3)/2)) + 3*atanh(sqrt(1 - 1/(c**4*x**4)))/(16*c**8*x**3*(1 - 1/(c**4*x**4))**(sympy.S(3)/2)*csch(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**3/csch(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=x**4/(7*csch(2*log(c*x))**(sympy.S(3)/2)) - 2/((7*c**4 - 7/x**4)*csch(2*log(c*x))**(sympy.S(3)/2)) - 4*elliptic_f(acsc(c*x), -1)/(7*c**7*x**3*(1 - 1/(c**4*x**4))**(sympy.S(3)/2)*csch(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**2/csch(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=7,
        integral=x**3/(6*csch(2*log(c*x))**(sympy.S(3)/2)) - 1/(x*(2*c**4 - 2/x**4)*csch(2*log(c*x))**(sympy.S(3)/2)) - acsc(c**2*x**2)/(2*c**6*x**3*(1 - 1/(c**4*x**4))**(sympy.S(3)/2)*csch(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x/csch(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=9,
        integral=x**2/(5*csch(2*log(c*x))**(sympy.S(3)/2)) - 6/(x**2*(5*c**4 - 5/x**4)*csch(2*log(c*x))**(sympy.S(3)/2)) - 12*elliptic_e(acsc(c*x), -1)/(5*c**5*x**3*(1 - 1/(c**4*x**4))**(sympy.S(3)/2)*csch(2*log(c*x))**(sympy.S(3)/2)) + 12*elliptic_f(acsc(c*x), -1)/(5*c**5*x**3*(1 - 1/(c**4*x**4))**(sympy.S(3)/2)*csch(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=csch(2*log(c*x))**(sympy.S(-3)/2),
        variable=x,
        num_steps=7,
        integral=x/(4*csch(2*log(c*x))**(sympy.S(3)/2)) + 3/(x**3*(4*c**4 - 4/x**4)*csch(2*log(c*x))**(sympy.S(3)/2)) - 3*atanh(sqrt(1 - 1/(c**4*x**4)))/(4*c**4*x**3*(1 - 1/(c**4*x**4))**(sympy.S(3)/2)*csch(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=csch(2*log(c*x))**(sympy.S(3)/2)/x,
        variable=x,
        num_steps=4,
        integral=-cosh(2*log(c*x))*sqrt(csch(2*log(c*x))) - I*elliptic_e(I*log(c*x) - pi/4, 2)/(sqrt(I*sinh(2*log(c*x)))*sqrt(csch(2*log(c*x)))),
    ),
    RubiTestSuiteCase(
        integrand=csch(2*log(c*x))**(sympy.S(3)/2)/x**2,
        variable=x,
        num_steps=3,
        integral=x**3*(-c**4/2 + 1/(2*x**4))*csch(2*log(c*x))**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=csch(2*log(c*x))**(sympy.S(3)/2)/x**3,
        variable=x,
        num_steps=5,
        integral=c**5*x**3*(1 - 1/(c**4*x**4))**(sympy.S(3)/2)*csch(2*log(c*x))**(sympy.S(3)/2)*elliptic_f(acsc(c*x), -1)/2 + x**2*(-c**4/2 + 1/(2*x**4))*csch(2*log(c*x))**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=csch(2*log(c*x))**(sympy.S(3)/2)/x**4,
        variable=x,
        num_steps=6,
        integral=c**6*x**3*(1 - 1/(c**4*x**4))**(sympy.S(3)/2)*acsc(c**2*x**2)*csch(2*log(c*x))**(sympy.S(3)/2)/2 + x*(-c**4/2 + 1/(2*x**4))*csch(2*log(c*x))**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*log(c*x**n)),
        variable=x,
        num_steps=4,
        integral=-2*x*(c*x**n)**b*exp(a)*hyper((1, (b + 1/n)/(2*b)), (sympy.S(3)/2 + 1/(2*b*n),), (c*x**n)**(2*b)*exp(2*a))/(b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=4,
        integral=4*x*(c*x**n)**(2*b)*exp(2*a)*hyper((2, 1 + 1/(2*b*n)), (2 + 1/(2*b*n),), (c*x**n)**(2*b)*exp(2*a))/(2*b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=4,
        integral=-8*x*(c*x**n)**(3*b)*exp(3*a)*hyper((3, (3*b + 1/n)/(2*b)), (sympy.S(5)/2 + 1/(2*b*n),), (c*x**n)**(2*b)*exp(2*a))/(3*b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*log(c*x**n))**4,
        variable=x,
        num_steps=4,
        integral=16*x*(c*x**n)**(4*b)*exp(4*a)*hyper((4, 2 + 1/(2*b*n)), (3 + 1/(2*b*n),), (c*x**n)**(2*b)*exp(2*a))/(4*b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=2*b**2*n**2*csch(a + b*log(c*x**n))**3 - (-b**2*n**2 + 1)*csch(a + b*log(c*x**n)),
        variable=x,
        num_steps=-9,
        integral=-b*n*x*coth(a + b*log(c*x**n))*csch(a + b*log(c*x**n)) - x*csch(a + b*log(c*x**n)),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + 2*log(c*sqrt(x)))**3,
        variable=x,
        num_steps=3,
        integral=-2*c**6*exp(-a)/(c**4 - exp(-2*a)/x**2)**2,
    ),
    RubiTestSuiteCase(
        integrand=csch(a + 2*log(c/sqrt(x)))**3,
        variable=x,
        num_steps=4,
        integral=2*c**2*exp(-3*a)/(-c**4/x**2 + exp(-2*a))**2,
    ),
    RubiTestSuiteCase(
        integrand=csch(a + log(c*x**n)/(n*(p - 2)))**p,
        variable=x,
        num_steps=3,
        integral=-x*(2 - p)*(-(c*x**n)**(2/(n*(2 - p)))*exp(-2*a) + 1)*exp(2*a)*csch(a - log(c*x**n)/(n*(2 - p)))**p/((c*x**n)**(2/(n*(2 - p)))*(2 - 2*p)),
    ),
    RubiTestSuiteCase(
        integrand=csch(a - log(c*x**n)/(n*(p - 2)))**p,
        variable=x,
        num_steps=3,
        integral=x*(1 - exp(-2*a)/(c*x**n)**(2/(n*(2 - p))))*(2 - p)*csch(a + log(c*x**n)/(n*(2 - p)))**p/(2 - 2*p),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*log(c*x**n))/x,
        variable=x,
        num_steps=2,
        integral=-atanh(cosh(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*log(c*x**n))**2/x,
        variable=x,
        num_steps=3,
        integral=-coth(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*log(c*x**n))**3/x,
        variable=x,
        num_steps=3,
        integral=-coth(a + b*log(c*x**n))*csch(a + b*log(c*x**n))/(2*b*n) + atanh(cosh(a + b*log(c*x**n)))/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*log(c*x**n))**4/x,
        variable=x,
        num_steps=3,
        integral=-coth(a + b*log(c*x**n))**3/(3*b*n) + coth(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*log(c*x**n))**5/x,
        variable=x,
        num_steps=4,
        integral=-coth(a + b*log(c*x**n))*csch(a + b*log(c*x**n))**3/(4*b*n) + 3*coth(a + b*log(c*x**n))*csch(a + b*log(c*x**n))/(8*b*n) - 3*atanh(cosh(a + b*log(c*x**n)))/(8*b*n),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*log(c*x**n))**(sympy.S(5)/2)/x,
        variable=x,
        num_steps=4,
        integral=2*I*sqrt(I*sinh(a + b*log(c*x**n)))*sqrt(csch(a + b*log(c*x**n)))*elliptic_f(I*a/2 + I*b*log(c*x**n)/2 - pi/4, 2)/(3*b*n) - 2*cosh(a + b*log(c*x**n))*csch(a + b*log(c*x**n))**(sympy.S(3)/2)/(3*b*n),
    ),
    RubiTestSuiteCase(
        integrand=csch(a + b*log(c*x**n))**(sympy.S(3)/2)/x,
        variable=x,
        num_steps=4,
        integral=-2*cosh(a + b*log(c*x**n))*sqrt(csch(a + b*log(c*x**n)))/(b*n) - 2*I*elliptic_e(I*a/2 + I*b*log(c*x**n)/2 - pi/4, 2)/(b*n*sqrt(I*sinh(a + b*log(c*x**n)))*sqrt(csch(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(csch(a + b*log(c*x**n)))/x,
        variable=x,
        num_steps=3,
        integral=-2*I*sqrt(I*sinh(a + b*log(c*x**n)))*sqrt(csch(a + b*log(c*x**n)))*elliptic_f(I*a/2 + I*b*log(c*x**n)/2 - pi/4, 2)/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(csch(a + b*log(c*x**n)))),
        variable=x,
        num_steps=3,
        integral=-2*I*elliptic_e(I*a/2 + I*b*log(c*x**n)/2 - pi/4, 2)/(b*n*sqrt(I*sinh(a + b*log(c*x**n)))*sqrt(csch(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*csch(a + b*log(c*x**n))**(sympy.S(3)/2)),
        variable=x,
        num_steps=4,
        integral=2*I*sqrt(I*sinh(a + b*log(c*x**n)))*sqrt(csch(a + b*log(c*x**n)))*elliptic_f(I*a/2 + I*b*log(c*x**n)/2 - pi/4, 2)/(3*b*n) + 2*cosh(a + b*log(c*x**n))/(3*b*n*sqrt(csch(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*csch(a + b*log(c*x**n))**(sympy.S(5)/2)),
        variable=x,
        num_steps=4,
        integral=2*cosh(a + b*log(c*x**n))/(5*b*n*csch(a + b*log(c*x**n))**(sympy.S(3)/2)) + 6*I*elliptic_e(I*a/2 + I*b*log(c*x**n)/2 - pi/4, 2)/(5*b*n*sqrt(I*sinh(a + b*log(c*x**n)))*sqrt(csch(a + b*log(c*x**n)))),
    ),
]
