# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 6 Hyperbolic functions/6.5 Hyperbolic secant/6.5.3 Hyperbolic secant functions.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '6 Hyperbolic functions/6.5 Hyperbolic secant/6.5.3 Hyperbolic secant functions.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, c, d, n, p = symbols('a b c d n p')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=sech(a + b*x),
        variable=x,
        num_steps=1,
        integral=atan(sinh(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*x)**2,
        variable=x,
        num_steps=2,
        integral=tanh(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*x)**3,
        variable=x,
        num_steps=2,
        integral=tanh(a + b*x)*sech(a + b*x)/(2*b) + atan(sinh(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*x)**4,
        variable=x,
        num_steps=2,
        integral=-tanh(a + b*x)**3/(3*b) + tanh(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*x)**5,
        variable=x,
        num_steps=3,
        integral=tanh(a + b*x)*sech(a + b*x)**3/(4*b) + 3*tanh(a + b*x)*sech(a + b*x)/(8*b) + 3*atan(sinh(a + b*x))/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*x)**6,
        variable=x,
        num_steps=2,
        integral=tanh(a + b*x)**5/(5*b) - 2*tanh(a + b*x)**3/(3*b) + tanh(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sech(7*x)**4,
        variable=x,
        num_steps=2,
        integral=-tanh(7*x)**3/21 + tanh(7*x)/7,
    ),
    RubiTestSuiteCase(
        integrand=sech(pi*x)**6,
        variable=x,
        num_steps=2,
        integral=tanh(pi*x)**5/(5*pi) - 2*tanh(pi*x)**3/(3*pi) + tanh(pi*x)/pi,
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*sinh(a + b*x)*sech(a + b*x)**(sympy.S(3)/2)/(3*b) - 2*I*sqrt(cosh(a + b*x))*elliptic_f(I*(a + b*x)/2, 2)*sqrt(sech(a + b*x))/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*sinh(a + b*x)*sqrt(sech(a + b*x))/b + 2*I*sqrt(cosh(a + b*x))*elliptic_e(I*(a + b*x)/2, 2)*sqrt(sech(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sech(a + b*x)),
        variable=x,
        num_steps=2,
        integral=-2*I*sqrt(cosh(a + b*x))*elliptic_f(I*(a + b*x)/2, 2)*sqrt(sech(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(sech(a + b*x)),
        variable=x,
        num_steps=2,
        integral=-2*I*sqrt(cosh(a + b*x))*elliptic_e(I*(a + b*x)/2, 2)*sqrt(sech(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*x)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*sinh(a + b*x)/(3*b*sqrt(sech(a + b*x))) - 2*I*sqrt(cosh(a + b*x))*elliptic_f(I*(a + b*x)/2, 2)*sqrt(sech(a + b*x))/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*x)**(sympy.S(-5)/2),
        variable=x,
        num_steps=3,
        integral=2*sinh(a + b*x)/(5*b*sech(a + b*x)**(sympy.S(3)/2)) - 6*I*sqrt(cosh(a + b*x))*elliptic_e(I*(a + b*x)/2, 2)*sqrt(sech(a + b*x))/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=(b*sech(c + d*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=4,
        integral=6*I*b**4*elliptic_e(I*(c + d*x)/2, 2)/(5*d*sqrt(b*sech(c + d*x))*sqrt(cosh(c + d*x))) + 6*b**3*sqrt(b*sech(c + d*x))*sinh(c + d*x)/(5*d) + 2*b*(b*sech(c + d*x))**(sympy.S(5)/2)*sinh(c + d*x)/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sech(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=-2*I*b**2*sqrt(b*sech(c + d*x))*sqrt(cosh(c + d*x))*elliptic_f(I*(c + d*x)/2, 2)/(3*d) + 2*b*(b*sech(c + d*x))**(sympy.S(3)/2)*sinh(c + d*x)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sech(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*I*b**2*elliptic_e(I*(c + d*x)/2, 2)/(d*sqrt(b*sech(c + d*x))*sqrt(cosh(c + d*x))) + 2*b*sqrt(b*sech(c + d*x))*sinh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*sech(c + d*x)),
        variable=x,
        num_steps=2,
        integral=-2*I*sqrt(b*sech(c + d*x))*sqrt(cosh(c + d*x))*elliptic_f(I*(c + d*x)/2, 2)/d,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(b*sech(c + d*x)),
        variable=x,
        num_steps=2,
        integral=-2*I*elliptic_e(I*(c + d*x)/2, 2)/(d*sqrt(b*sech(c + d*x))*sqrt(cosh(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sech(c + d*x))**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*sinh(c + d*x)/(3*b*d*sqrt(b*sech(c + d*x))) - 2*I*sqrt(b*sech(c + d*x))*sqrt(cosh(c + d*x))*elliptic_f(I*(c + d*x)/2, 2)/(3*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sech(c + d*x))**(sympy.S(-5)/2),
        variable=x,
        num_steps=3,
        integral=2*sinh(c + d*x)/(5*b*d*(b*sech(c + d*x))**(sympy.S(3)/2)) - 6*I*elliptic_e(I*(c + d*x)/2, 2)/(5*b**2*d*sqrt(b*sech(c + d*x))*sqrt(cosh(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*sech(c + d*x))**(sympy.S(-7)/2),
        variable=x,
        num_steps=4,
        integral=2*sinh(c + d*x)/(7*b*d*(b*sech(c + d*x))**(sympy.S(5)/2)) + 10*sinh(c + d*x)/(21*b**3*d*sqrt(b*sech(c + d*x))) - 10*I*sqrt(b*sech(c + d*x))*sqrt(cosh(c + d*x))*elliptic_f(I*(c + d*x)/2, 2)/(21*b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*sech(c + d*x))**n,
        variable=x,
        num_steps=2,
        integral=-b*(b*sech(c + d*x))**(n - 1)*sinh(c + d*x)*hyper((sympy.S.Half, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), cosh(c + d*x)**2)/(d*sqrt(-sinh(c + d*x)**2)*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(sech(a + b*x)**2)**(sympy.S(7)/2),
        variable=x,
        num_steps=5,
        integral=(sech(a + b*x)**2)**(sympy.S(5)/2)*tanh(a + b*x)/(6*b) + 5*(sech(a + b*x)**2)**(sympy.S(3)/2)*tanh(a + b*x)/(24*b) + 5*sqrt(sech(a + b*x)**2)*tanh(a + b*x)/(16*b) + 5*asin(tanh(a + b*x))/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=(sech(a + b*x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=(sech(a + b*x)**2)**(sympy.S(3)/2)*tanh(a + b*x)/(4*b) + 3*sqrt(sech(a + b*x)**2)*tanh(a + b*x)/(8*b) + 3*asin(tanh(a + b*x))/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=(sech(a + b*x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=sqrt(sech(a + b*x)**2)*tanh(a + b*x)/(2*b) + asin(tanh(a + b*x))/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sech(a + b*x)**2),
        variable=x,
        num_steps=2,
        integral=asin(tanh(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(sech(a + b*x)**2),
        variable=x,
        num_steps=2,
        integral=tanh(a + b*x)/(b*sqrt(sech(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(sech(a + b*x)**2)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*tanh(a + b*x)/(3*b*sqrt(sech(a + b*x)**2)) + tanh(a + b*x)/(3*b*(sech(a + b*x)**2)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(sech(a + b*x)**2)**(sympy.S(-5)/2),
        variable=x,
        num_steps=4,
        integral=8*tanh(a + b*x)/(15*b*sqrt(sech(a + b*x)**2)) + 4*tanh(a + b*x)/(15*b*(sech(a + b*x)**2)**(sympy.S(3)/2)) + tanh(a + b*x)/(5*b*(sech(a + b*x)**2)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(sech(a + b*x)**2)**(sympy.S(-7)/2),
        variable=x,
        num_steps=5,
        integral=16*tanh(a + b*x)/(35*b*sqrt(sech(a + b*x)**2)) + 8*tanh(a + b*x)/(35*b*(sech(a + b*x)**2)**(sympy.S(3)/2)) + 6*tanh(a + b*x)/(35*b*(sech(a + b*x)**2)**(sympy.S(5)/2)) + tanh(a + b*x)/(7*b*(sech(a + b*x)**2)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=3*a**(sympy.S(5)/2)*atan(sqrt(a)*tanh(x)/sqrt(a*sech(x)**2))/8 + 3*a**2*sqrt(a*sech(x)**2)*tanh(x)/8 + a*(a*sech(x)**2)**(sympy.S(3)/2)*tanh(x)/4,
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=a**(sympy.S(3)/2)*atan(sqrt(a)*tanh(x)/sqrt(a*sech(x)**2))/2 + a*sqrt(a*sech(x)**2)*tanh(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*sech(x)**2),
        variable=x,
        num_steps=3,
        integral=sqrt(a)*atan(sqrt(a)*tanh(x)/sqrt(a*sech(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*sech(x)**2),
        variable=x,
        num_steps=2,
        integral=tanh(x)/sqrt(a*sech(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(x)**2)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=tanh(x)/(3*(a*sech(x)**2)**(sympy.S(3)/2)) + 2*tanh(x)/(3*a*sqrt(a*sech(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(x)**2)**(sympy.S(-5)/2),
        variable=x,
        num_steps=4,
        integral=tanh(x)/(5*(a*sech(x)**2)**(sympy.S(5)/2)) + 4*tanh(x)/(15*a*(a*sech(x)**2)**(sympy.S(3)/2)) + 8*tanh(x)/(15*a**2*sqrt(a*sech(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(x)**2)**(sympy.S(-7)/2),
        variable=x,
        num_steps=5,
        integral=tanh(x)/(7*(a*sech(x)**2)**(sympy.S(7)/2)) + 6*tanh(x)/(35*a*(a*sech(x)**2)**(sympy.S(5)/2)) + 8*tanh(x)/(35*a**2*(a*sech(x)**2)**(sympy.S(3)/2)) + 16*tanh(x)/(35*a**3*sqrt(a*sech(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(x)**3)**(sympy.S(5)/2),
        variable=x,
        num_steps=7,
        integral=154*a**2*sqrt(a*sech(x)**3)*sinh(x)*cosh(x)/195 + 154*I*a**2*sqrt(a*sech(x)**3)*cosh(x)**(sympy.S(3)/2)*elliptic_e(I*x/2, 2)/195 + 2*a**2*sqrt(a*sech(x)**3)*tanh(x)*sech(x)**4/13 + 22*a**2*sqrt(a*sech(x)**3)*tanh(x)*sech(x)**2/117 + 154*a**2*sqrt(a*sech(x)**3)*tanh(x)/585,
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(x)**3)**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=10*a*sqrt(a*sech(x)**3)*sinh(x)/21 - 10*I*a*sqrt(a*sech(x)**3)*cosh(x)**(sympy.S(3)/2)*elliptic_f(I*x/2, 2)/21 + 2*a*sqrt(a*sech(x)**3)*tanh(x)*sech(x)/7,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*sech(x)**3),
        variable=x,
        num_steps=4,
        integral=2*sqrt(a*sech(x)**3)*sinh(x)*cosh(x) + 2*I*sqrt(a*sech(x)**3)*cosh(x)**(sympy.S(3)/2)*elliptic_e(I*x/2, 2),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*sech(x)**3),
        variable=x,
        num_steps=4,
        integral=2*tanh(x)/(3*sqrt(a*sech(x)**3)) - 2*I*elliptic_f(I*x/2, 2)/(3*sqrt(a*sech(x)**3)*cosh(x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(x)**3)**(sympy.S(-3)/2),
        variable=x,
        num_steps=5,
        integral=2*sinh(x)*cosh(x)**2/(9*a*sqrt(a*sech(x)**3)) + 14*sinh(x)/(45*a*sqrt(a*sech(x)**3)) - 14*I*elliptic_e(I*x/2, 2)/(15*a*sqrt(a*sech(x)**3)*cosh(x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(x)**3)**(sympy.S(-5)/2),
        variable=x,
        num_steps=7,
        integral=2*sinh(x)*cosh(x)**5/(15*a**2*sqrt(a*sech(x)**3)) + 26*sinh(x)*cosh(x)**3/(165*a**2*sqrt(a*sech(x)**3)) + 78*sinh(x)*cosh(x)/(385*a**2*sqrt(a*sech(x)**3)) + 26*tanh(x)/(77*a**2*sqrt(a*sech(x)**3)) - 26*I*elliptic_f(I*x/2, 2)/(77*a**2*sqrt(a*sech(x)**3)*cosh(x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(x)**4)**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=a**3*sqrt(a*sech(x)**4)*sinh(x)**2*tanh(x)**11/13 - 6*a**3*sqrt(a*sech(x)**4)*sinh(x)**2*tanh(x)**9/11 + 5*a**3*sqrt(a*sech(x)**4)*sinh(x)**2*tanh(x)**7/3 - 20*a**3*sqrt(a*sech(x)**4)*sinh(x)**2*tanh(x)**5/7 + 3*a**3*sqrt(a*sech(x)**4)*sinh(x)**2*tanh(x)**3 - 2*a**3*sqrt(a*sech(x)**4)*sinh(x)**2*tanh(x) + a**3*sqrt(a*sech(x)**4)*sinh(x)*cosh(x),
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(x)**4)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=a**2*sqrt(a*sech(x)**4)*sinh(x)**2*tanh(x)**7/9 - 4*a**2*sqrt(a*sech(x)**4)*sinh(x)**2*tanh(x)**5/7 + 6*a**2*sqrt(a*sech(x)**4)*sinh(x)**2*tanh(x)**3/5 - 4*a**2*sqrt(a*sech(x)**4)*sinh(x)**2*tanh(x)/3 + a**2*sqrt(a*sech(x)**4)*sinh(x)*cosh(x),
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(x)**4)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=a*sqrt(a*sech(x)**4)*sinh(x)**2*tanh(x)**3/5 - 2*a*sqrt(a*sech(x)**4)*sinh(x)**2*tanh(x)/3 + a*sqrt(a*sech(x)**4)*sinh(x)*cosh(x),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*sech(x)**4),
        variable=x,
        num_steps=3,
        integral=sqrt(a*sech(x)**4)*sinh(x)*cosh(x),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*sech(x)**4),
        variable=x,
        num_steps=3,
        integral=x*sech(x)**2/(2*sqrt(a*sech(x)**4)) + tanh(x)/(2*sqrt(a*sech(x)**4)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(x)**4)**(sympy.S(-3)/2),
        variable=x,
        num_steps=5,
        integral=5*x*sech(x)**2/(16*a*sqrt(a*sech(x)**4)) + sinh(x)*cosh(x)**3/(6*a*sqrt(a*sech(x)**4)) + 5*sinh(x)*cosh(x)/(24*a*sqrt(a*sech(x)**4)) + 5*tanh(x)/(16*a*sqrt(a*sech(x)**4)),
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(x)**4)**(sympy.S(-5)/2),
        variable=x,
        num_steps=7,
        integral=63*x*sech(x)**2/(256*a**2*sqrt(a*sech(x)**4)) + sinh(x)*cosh(x)**7/(10*a**2*sqrt(a*sech(x)**4)) + 9*sinh(x)*cosh(x)**5/(80*a**2*sqrt(a*sech(x)**4)) + 21*sinh(x)*cosh(x)**3/(160*a**2*sqrt(a*sech(x)**4)) + 21*sinh(x)*cosh(x)/(128*a**2*sqrt(a*sech(x)**4)) + 63*tanh(x)/(256*a**2*sqrt(a*sech(x)**4)),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**4/(a*sech(x) + a),
        variable=x,
        num_steps=7,
        integral=-x/(8*a) - sinh(x)**3/(3*a) + sinh(x)*cosh(x)**3/(4*a) - sinh(x)*cosh(x)/(8*a),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**3/(a*sech(x) + a),
        variable=x,
        num_steps=6,
        integral=-sinh(x)**2/(2*a) + cosh(x)**3/(3*a),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**2/(a*sech(x) + a),
        variable=x,
        num_steps=5,
        integral=x/(2*a) + sinh(x)*cosh(x)/(2*a) - sinh(x)/a,
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)/(a*sech(x) + a),
        variable=x,
        num_steps=5,
        integral=-log(cosh(x) + 1)/a + cosh(x)/a,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)/(a*sech(x) + a),
        variable=x,
        num_steps=6,
        integral=-coth(x)*csch(x)/(2*a) - atanh(cosh(x))/(2*a) + csch(x)**2/(2*a),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**2/(a*sech(x) + a),
        variable=x,
        num_steps=6,
        integral=-coth(x)**3/(3*a) + csch(x)**3/(3*a),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**3/(a*sech(x) + a),
        variable=x,
        num_steps=7,
        integral=-coth(x)*csch(x)**3/(4*a) - coth(x)*csch(x)/(8*a) + atanh(cosh(x))/(8*a) + csch(x)**4/(4*a),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**4/(a*sech(x) + a),
        variable=x,
        num_steps=7,
        integral=-coth(x)**5/(5*a) + coth(x)**3/(3*a) + csch(x)**5/(5*a),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**4/(a + b*sech(x)),
        variable=x,
        num_steps=6,
        integral=-(-3*a*cosh(x) + 4*b)*sinh(x)**3/(12*a**2) + (-a*(3*a**2 - 4*b**2)*cosh(x) + 8*b*(a**2 - b**2))*sinh(x)/(8*a**4) - 2*b*(a - b)**(sympy.S(3)/2)*(a + b)**(sympy.S(3)/2)*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/a**5 + x*(3*a**4 - 12*a**2*b**2 + 8*b**4)/(8*a**5),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**3/(a + b*sech(x)),
        variable=x,
        num_steps=5,
        integral=cosh(x)**3/(3*a) - b*cosh(x)**2/(2*a**2) - (a**2 - b**2)*cosh(x)/a**3 + b*(a**2 - b**2)*log(a*cosh(x) + b)/a**4,
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**2/(a + b*sech(x)),
        variable=x,
        num_steps=5,
        integral=-(-a*cosh(x) + 2*b)*sinh(x)/(2*a**2) + 2*b*sqrt(a - b)*sqrt(a + b)*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/a**3 - x*(a**2 - 2*b**2)/(2*a**3),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)/(a + b*sech(x)),
        variable=x,
        num_steps=5,
        integral=cosh(x)/a - b*log(a*cosh(x) + b)/a**2,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)/(a + b*sech(x)),
        variable=x,
        num_steps=4,
        integral=b*log(a*cosh(x) + b)/(a**2 - b**2) + log(1 - cosh(x))/(2*a + 2*b) - log(cosh(x) + 1)/(2*a - 2*b),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**2/(a + b*sech(x)),
        variable=x,
        num_steps=5,
        integral=2*a*b*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/((a - b)**(sympy.S(3)/2)*(a + b)**(sympy.S(3)/2)) + (-a*cosh(x) + b)*csch(x)/(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**3/(a + b*sech(x)),
        variable=x,
        num_steps=6,
        integral=-a**2*b*log(a*cosh(x) + b)/(a**2 - b**2)**2 - a*log(1 - cosh(x))/(4*(a + b)**2) + a*log(cosh(x) + 1)/(4*(a - b)**2) + (-a*cosh(x) + b)*csch(x)**2/(2*a**2 - 2*b**2),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**4/(a + b*sech(x)),
        variable=x,
        num_steps=6,
        integral=-2*a**3*b*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/((a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)) + (-a*cosh(x) + b)*csch(x)**3/(3*a**2 - 3*b**2) - (3*a**2*b - a*(2*a**2 + b**2)*cosh(x))*csch(x)/(3*(a**2 - b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**4/(a*sech(x) + a),
        variable=x,
        num_steps=7,
        integral=-sinh(x)*cosh(x)**3/(a*sech(x) + a) + 15*x/(8*a) - 4*sinh(x)**3/(3*a) + 5*sinh(x)*cosh(x)**3/(4*a) + 15*sinh(x)*cosh(x)/(8*a) - 4*sinh(x)/a,
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**3/(a*sech(x) + a),
        variable=x,
        num_steps=6,
        integral=-sinh(x)*cosh(x)**2/(a*sech(x) + a) - 3*x/(2*a) + 4*sinh(x)**3/(3*a) - 3*sinh(x)*cosh(x)/(2*a) + 4*sinh(x)/a,
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**2/(a*sech(x) + a),
        variable=x,
        num_steps=5,
        integral=-sinh(x)*cosh(x)/(a*sech(x) + a) + 3*x/(2*a) + 3*sinh(x)*cosh(x)/(2*a) - 2*sinh(x)/a,
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)/(a*sech(x) + a),
        variable=x,
        num_steps=4,
        integral=-sinh(x)/(a*sech(x) + a) - x/a + 2*sinh(x)/a,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)/(a*sech(x) + a),
        variable=x,
        num_steps=1,
        integral=tanh(x)/(a*sech(x) + a),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**2/(a*sech(x) + a),
        variable=x,
        num_steps=3,
        integral=-tanh(x)/(a*sech(x) + a) + atan(sinh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**3/(a*sech(x) + a),
        variable=x,
        num_steps=4,
        integral=tanh(x)/(a*sech(x) + a) + tanh(x)/a - atan(sinh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**4/(a*sech(x) + a),
        variable=x,
        num_steps=6,
        integral=-tanh(x)*sech(x)**2/(a*sech(x) + a) + 3*tanh(x)*sech(x)/(2*a) - 2*tanh(x)/a + 3*atan(sinh(x))/(2*a),
    ),
    RubiTestSuiteCase(
        integrand=1/(a*sech(c + d*x) + a),
        variable=x,
        num_steps=2,
        integral=-tanh(c + d*x)/(d*(a*sech(c + d*x) + a)) + x/a,
    ),
    RubiTestSuiteCase(
        integrand=1/(-a*sech(c + d*x) + a),
        variable=x,
        num_steps=2,
        integral=-tanh(c + d*x)/(d*(-a*sech(c + d*x) + a)) + x/a,
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(c + d*x) + a)**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=2*a**(sympy.S(5)/2)*atanh(sqrt(a)*tanh(c + d*x)/sqrt(a*sech(c + d*x) + a))/d + 14*a**3*tanh(c + d*x)/(3*d*sqrt(a*sech(c + d*x) + a)) + 2*a**2*sqrt(a*sech(c + d*x) + a)*tanh(c + d*x)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(c + d*x) + a)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=2*a**(sympy.S(3)/2)*atanh(sqrt(a)*tanh(c + d*x)/sqrt(a*sech(c + d*x) + a))/d + 2*a**2*tanh(c + d*x)/(d*sqrt(a*sech(c + d*x) + a)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*sech(c + d*x) + a),
        variable=x,
        num_steps=2,
        integral=2*sqrt(a)*atanh(sqrt(a)*tanh(c + d*x)/sqrt(a*sech(c + d*x) + a))/d,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*sech(c + d*x) + a),
        variable=x,
        num_steps=5,
        integral=2*atanh(sqrt(a)*tanh(c + d*x)/sqrt(a*sech(c + d*x) + a))/(sqrt(a)*d) - sqrt(2)*atanh(sqrt(2)*sqrt(a)*tanh(c + d*x)/(2*sqrt(a*sech(c + d*x) + a)))/(sqrt(a)*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*sech(c + d*x) + a)**(sympy.S(-3)/2),
        variable=x,
        num_steps=6,
        integral=-tanh(c + d*x)/(2*d*(a*sech(c + d*x) + a)**(sympy.S(3)/2)) + 2*atanh(sqrt(a)*tanh(c + d*x)/sqrt(a*sech(c + d*x) + a))/(a**(sympy.S(3)/2)*d) - 5*sqrt(2)*atanh(sqrt(2)*sqrt(a)*tanh(c + d*x)/(2*sqrt(a*sech(c + d*x) + a)))/(4*a**(sympy.S(3)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-a*sech(c + d*x) + a),
        variable=x,
        num_steps=2,
        integral=2*sqrt(a)*atanh(sqrt(a)*tanh(c + d*x)/sqrt(-a*sech(c + d*x) + a))/d,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-a*sech(c + d*x) + a),
        variable=x,
        num_steps=5,
        integral=2*atanh(sqrt(a)*tanh(c + d*x)/sqrt(-a*sech(c + d*x) + a))/(sqrt(a)*d) - sqrt(2)*atanh(sqrt(2)*sqrt(a)*tanh(c + d*x)/(2*sqrt(-a*sech(c + d*x) + a)))/(sqrt(a)*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(3*sech(x) + 3),
        variable=x,
        num_steps=2,
        integral=2*sqrt(3)*atanh(tanh(x)/sqrt(sech(x) + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(3 - 3*sech(x)),
        variable=x,
        num_steps=2,
        integral=2*sqrt(3)*atanh(tanh(x)/sqrt(1 - sech(x))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*sech(c + d*x))**4,
        variable=x,
        num_steps=6,
        integral=a**4*x + 4*a*b**3*tanh(c + d*x)*sech(c + d*x)/(3*d) + 2*a*b*(2*a**2 + b**2)*atan(sinh(c + d*x))/d + b**2*(a + b*sech(c + d*x))**2*tanh(c + d*x)/(3*d) + b**2*(17*a**2 + 2*b**2)*tanh(c + d*x)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*sech(c + d*x))**3,
        variable=x,
        num_steps=5,
        integral=a**3*x + 5*a*b**2*tanh(c + d*x)/(2*d) + b**2*(a + b*sech(c + d*x))*tanh(c + d*x)/(2*d) + b*(6*a**2 + b**2)*atan(sinh(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*sech(c + d*x))**2,
        variable=x,
        num_steps=4,
        integral=a**2*x + 2*a*b*atan(sinh(c + d*x))/d + b**2*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=a + b*sech(c + d*x),
        variable=x,
        num_steps=2,
        integral=a*x + b*atan(sinh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*sech(c + d*x)),
        variable=x,
        num_steps=3,
        integral=-2*b*atan(sqrt(a - b)*tanh(c/2 + d*x/2)/sqrt(a + b))/(a*d*sqrt(a - b)*sqrt(a + b)) + x/a,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*sech(c + d*x))**(-2),
        variable=x,
        num_steps=5,
        integral=b**2*tanh(c + d*x)/(a*d*(a + b*sech(c + d*x))*(a**2 - b**2)) - 2*b*(2*a**2 - b**2)*atan(sqrt(a - b)*tanh(c/2 + d*x/2)/sqrt(a + b))/(a**2*d*(a - b)**(sympy.S(3)/2)*(a + b)**(sympy.S(3)/2)) + x/a**2,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*sech(c + d*x))**(-3),
        variable=x,
        num_steps=6,
        integral=b**2*tanh(c + d*x)/(2*a*d*(a + b*sech(c + d*x))**2*(a**2 - b**2)) + b**2*(5*a**2 - 2*b**2)*tanh(c + d*x)/(2*a**2*d*(a + b*sech(c + d*x))*(a**2 - b**2)**2) - b*(6*a**4 - 5*a**2*b**2 + 2*b**4)*atan(sqrt(a - b)*tanh(c/2 + d*x/2)/sqrt(a + b))/(a**3*d*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)) + x/a**3,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a + b*sech(c + d*x)),
        variable=x,
        num_steps=1,
        integral=((Integer(2) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.Function('EllipticPi')(((Symbol('a') + Symbol('b')) * (Symbol('a'))**(Integer(-1))), sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('a') * Symbol('d')))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**4/(a + b*sech(x)),
        variable=x,
        num_steps=8,
        integral=sinh(x)*cosh(x)**3/(4*a) - b*sinh(x)*cosh(x)**2/(3*a**2) + (3*a**2 + 4*b**2)*sinh(x)*cosh(x)/(8*a**3) - b*(2*a**2 + 3*b**2)*sinh(x)/(3*a**4) - 2*b**5*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/(a**5*sqrt(a - b)*sqrt(a + b)) + x*(3*a**4 + 4*a**2*b**2 + 8*b**4)/(8*a**5),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**3/(a + b*sech(x)),
        variable=x,
        num_steps=7,
        integral=sinh(x)*cosh(x)**2/(3*a) - b*sinh(x)*cosh(x)/(2*a**2) + (2*a**2 + 3*b**2)*sinh(x)/(3*a**3) + 2*b**4*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/(a**4*sqrt(a - b)*sqrt(a + b)) - b*x*(a**2 + 2*b**2)/(2*a**4),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**2/(a + b*sech(x)),
        variable=x,
        num_steps=6,
        integral=sinh(x)*cosh(x)/(2*a) - b*sinh(x)/a**2 - 2*b**3*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/(a**3*sqrt(a - b)*sqrt(a + b)) + x*(a**2 + 2*b**2)/(2*a**3),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)/(a + b*sech(x)),
        variable=x,
        num_steps=5,
        integral=sinh(x)/a + 2*b**2*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/(a**2*sqrt(a - b)*sqrt(a + b)) - b*x/a**2,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)/(a + b*sech(x)),
        variable=x,
        num_steps=3,
        integral=2*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/(sqrt(a - b)*sqrt(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**2/(a + b*sech(x)),
        variable=x,
        num_steps=5,
        integral=-2*a*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/(b*sqrt(a - b)*sqrt(a + b)) + atan(sinh(x))/b,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**3/(a + b*sech(x)),
        variable=x,
        num_steps=6,
        integral=2*a**2*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/(b**2*sqrt(a - b)*sqrt(a + b)) - a*atan(sinh(x))/b**2 + tanh(x)/b,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**4/(a + b*sech(x)),
        variable=x,
        num_steps=7,
        integral=-2*a**3*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/(b**3*sqrt(a - b)*sqrt(a + b)) - a*tanh(x)/b**2 + tanh(x)*sech(x)/(2*b) + (2*a**2 + b**2)*atan(sinh(x))/(2*b**3),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**6/(a*sech(x) + a),
        variable=x,
        num_steps=5,
        integral=x/a - (4 - 3*sech(x))*tanh(x)**3/(12*a) - (8 - 3*sech(x))*tanh(x)/(8*a) - 3*atan(sinh(x))/(8*a),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**5/(a*sech(x) + a),
        variable=x,
        num_steps=3,
        integral=log(cosh(x))/a - sech(x)**3/(3*a) + sech(x)**2/(2*a) + sech(x)/a,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**4/(a*sech(x) + a),
        variable=x,
        num_steps=4,
        integral=x/a - (2 - sech(x))*tanh(x)/(2*a) - atan(sinh(x))/(2*a),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**3/(a*sech(x) + a),
        variable=x,
        num_steps=3,
        integral=log(cosh(x))/a + sech(x)/a,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**2/(a*sech(x) + a),
        variable=x,
        num_steps=3,
        integral=x/a - atan(sinh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/(a*sech(x) + a),
        variable=x,
        num_steps=2,
        integral=log(cosh(x) + 1)/a,
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/(a*sech(x) + a),
        variable=x,
        num_steps=3,
        integral=log(1 - cosh(x))/(4*a) + 3*log(cosh(x) + 1)/(4*a) + 1/(2*a*(cosh(x) + 1)),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**2/(a*sech(x) + a),
        variable=x,
        num_steps=4,
        integral=x/a - (1 - sech(x))*coth(x)**3/(3*a) - (3 - 2*sech(x))*coth(x)/(3*a),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**3/(a*sech(x) + a),
        variable=x,
        num_steps=3,
        integral=5*log(1 - cosh(x))/(16*a) + 11*log(cosh(x) + 1)/(16*a) + 3/(4*a*(cosh(x) + 1)) - 1/(8*a*(cosh(x) + 1)**2) + 1/(8*a*(1 - cosh(x))),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**4/(a*sech(x) + a),
        variable=x,
        num_steps=5,
        integral=x/a - (1 - sech(x))*coth(x)**5/(5*a) - (5 - 4*sech(x))*coth(x)**3/(15*a) - (15 - 8*sech(x))*coth(x)/(15*a),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**7/(a + b*sech(x)),
        variable=x,
        num_steps=3,
        integral=-a*sech(x)**4/(4*b**2) - a*(a**2 - 3*b**2)*sech(x)**2/(2*b**4) + sech(x)**5/(5*b) + (a**2 - 3*b**2)*sech(x)**3/(3*b**3) + (a**4 - 3*a**2*b**2 + 3*b**4)*sech(x)/b**5 + log(cosh(x))/a - (a**2 - b**2)**3*log(a + b*sech(x))/(a*b**6),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**6/(a + b*sech(x)),
        variable=x,
        num_steps=15,
        integral=-a*tanh(x)**3/(3*b**2) + a*tanh(x)/b**2 + a*(a**2 - 3*b**2)*tanh(x)/b**4 - tanh(x)*sech(x)**3/(4*b) - 3*tanh(x)*sech(x)/(8*b) - 3*atan(sinh(x))/(8*b) - (a**2 - 3*b**2)*tanh(x)*sech(x)/(2*b**3) - (a**2 - 3*b**2)*atan(sinh(x))/(2*b**3) - (a**4 - 3*a**2*b**2 + 3*b**4)*atan(sinh(x))/b**5 + x/a + 2*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/(a*b**5),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**5/(a + b*sech(x)),
        variable=x,
        num_steps=3,
        integral=a*sech(x)**2/(2*b**2) - sech(x)**3/(3*b) - (a**2 - 2*b**2)*sech(x)/b**3 + log(cosh(x))/a + (a**2 - b**2)**2*log(a + b*sech(x))/(a*b**4),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**4/(a + b*sech(x)),
        variable=x,
        num_steps=6,
        integral=-a*tanh(x)/b**2 + tanh(x)*sech(x)/(2*b) + (2*a**2 - 3*b**2)*atan(sinh(x))/(2*b**3) + x/a - 2*(a - b)**(sympy.S(3)/2)*(a + b)**(sympy.S(3)/2)*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/(a*b**3),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**3/(a + b*sech(x)),
        variable=x,
        num_steps=3,
        integral=sech(x)/b + (-a**2/b**2 + 1)*log(a + b*sech(x))/a + log(cosh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**2/(a + b*sech(x)),
        variable=x,
        num_steps=7,
        integral=-atan(sinh(x))/b + x/a + 2*sqrt(a - b)*sqrt(a + b)*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/(a*b),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/(a + b*sech(x)),
        variable=x,
        num_steps=4,
        integral=log(a + b*sech(x))/a + log(cosh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/(a + b*sech(x)),
        variable=x,
        num_steps=3,
        integral=log(1 - sech(x))/(2*a + 2*b) + log(sech(x) + 1)/(2*a - 2*b) - b**2*log(a + b*sech(x))/(a*(a**2 - b**2)) + log(cosh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**2/(a + b*sech(x)),
        variable=x,
        num_steps=9,
        integral=a*x/(a**2 - b**2) - a*coth(x)/(a**2 - b**2) + b*csch(x)/(a**2 - b**2) + 2*b**3*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/(a*(a - b)**(sympy.S(3)/2)*(a + b)**(sympy.S(3)/2)) - b**2*x/(a*(a**2 - b**2)),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**3/(a + b*sech(x)),
        variable=x,
        num_steps=3,
        integral=-1/((4*a - 4*b)*(sech(x) + 1)) + (2*a + 3*b)*log(1 - sech(x))/(4*(a + b)**2) + (2*a - 3*b)*log(sech(x) + 1)/(4*(a - b)**2) - 1/((1 - sech(x))*(4*a + 4*b)) + b**4*log(a + b*sech(x))/(a*(a**2 - b**2)**2) + log(cosh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**4/(a + b*sech(x)),
        variable=x,
        num_steps=15,
        integral=-a*b**2*x/(a**2 - b**2)**2 + a*b**2*coth(x)/(a**2 - b**2)**2 + a*x/(a**2 - b**2) - a*coth(x)**3/(3*a**2 - 3*b**2) - a*coth(x)/(a**2 - b**2) - b**3*csch(x)/(a**2 - b**2)**2 + b*csch(x)**3/(3*a**2 - 3*b**2) + b*csch(x)/(a**2 - b**2) - 2*b**5*atan(sqrt(a - b)*tanh(x/2)/sqrt(a + b))/(a*(a - b)**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)) + b**4*x/(a*(a**2 - b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**5/(a + b*sech(x)),
        variable=x,
        num_steps=3,
        integral=-1/((16*a - 16*b)*(sech(x) + 1)**2) + (8*a**2 + 21*a*b + 15*b**2)*log(1 - sech(x))/(16*(a + b)**3) - (5*a - 7*b)/(16*(a - b)**2*(sech(x) + 1)) + (8*a**2 - 21*a*b + 15*b**2)*log(sech(x) + 1)/(16*(a - b)**3) - (5*a + 7*b)/(16*(1 - sech(x))*(a + b)**2) - 1/((1 - sech(x))**2*(16*a + 16*b)) - b**6*log(a + b*sech(x))/(a*(a**2 - b**2)**3) + log(cosh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*sech(c + d*x))*tanh(c + d*x)**5,
        variable=x,
        num_steps=5,
        integral=2*sqrt(a)*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/d + 6*a*(a + b*sech(c + d*x))**(sympy.S(7)/2)/(7*b**4*d) + 2*a*(a + b*sech(c + d*x))**(sympy.S(3)/2)*(a**2 - 2*b**2)/(3*b**4*d) - 2*sqrt(a + b*sech(c + d*x))/d - 2*(a + b*sech(c + d*x))**(sympy.S(9)/2)/(9*b**4*d) - (a + b*sech(c + d*x))**(sympy.S(5)/2)*(6*a**2 - 4*b**2)/(5*b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*sech(c + d*x))*tanh(c + d*x)**3,
        variable=x,
        num_steps=5,
        integral=2*sqrt(a)*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/d - 2*a*(a + b*sech(c + d*x))**(sympy.S(3)/2)/(3*b**2*d) - 2*sqrt(a + b*sech(c + d*x))/d + 2*(a + b*sech(c + d*x))**(sympy.S(5)/2)/(5*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*sech(c + d*x))*tanh(c + d*x),
        variable=x,
        num_steps=4,
        integral=2*sqrt(a)*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/d - 2*sqrt(a + b*sech(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*sech(c + d*x))*coth(c + d*x),
        variable=x,
        num_steps=7,
        integral=2*sqrt(a)*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/d - sqrt(a - b)*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a - b))/d - sqrt(a + b)*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a + b))/d,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*sech(c + d*x))*coth(c + d*x)**3,
        variable=x,
        num_steps=13,
        integral=2*sqrt(a)*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/d - a*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a + b))/(d*sqrt(a + b)) - a*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a - b))/(d*sqrt(a - b)) - 3*b*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a + b))/(4*d*sqrt(a + b)) + 3*b*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a - b))/(4*d*sqrt(a - b)) - sqrt(a + b*sech(c + d*x))*coth(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*sech(c + d*x))*tanh(c + d*x)**2,
        variable=x,
        num_steps=7,
        integral=((Integer(-1) * ((Integer(2) * Symbol('a') * (Symbol('a') + (Integer(-1) * Symbol('b'))) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_e(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Integer(3) * (Symbol('b'))**(Integer(2)) * Symbol('d')))**(Integer(-1)))) + (Integer(-1) * ((Integer(2) * sympy.sqrt((Symbol('a') + Symbol('b'))) * (Symbol('a') + (Integer(2) * Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_f(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Integer(3) * Symbol('b') * Symbol('d')))**(Integer(-1)))) + ((Integer(2) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.Function('EllipticPi')(((Symbol('a') + Symbol('b')) * (Symbol('a'))**(Integer(-1))), sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * (Symbol('d'))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * sympy.tanh((Symbol('c') + (Symbol('d') * x)))) * ((Integer(3) * Symbol('d')))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*sech(c + d*x)),
        variable=x,
        num_steps=1,
        integral=((Integer(2) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.Function('EllipticPi')((Symbol('a') * ((Symbol('a') + Symbol('b')))**(Integer(-1))), sympy.asin((sympy.sqrt((Symbol('a') + Symbol('b'))) * (sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))))**(Integer(-1)))), ((Symbol('a') + (Integer(-1) * Symbol('b'))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))**(Integer(-1))))) * sympy.sqrt(((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))**(Integer(-1)))) * (Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((sympy.sqrt((Symbol('a') + Symbol('b'))) * Symbol('d')))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*sech(c + d*x))*coth(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=(((sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_f(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * (Symbol('d'))**(Integer(-1))) + (Integer(-1) * ((sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))) * (Symbol('d'))**(Integer(-1)))) + ((Integer(2) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.Function('EllipticPi')((Symbol('a') * ((Symbol('a') + Symbol('b')))**(Integer(-1))), sympy.asin((sympy.sqrt((Symbol('a') + Symbol('b'))) * (sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))))**(Integer(-1)))), ((Symbol('a') + (Integer(-1) * Symbol('b'))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))**(Integer(-1))))) * sympy.sqrt(((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))**(Integer(-1)))) * (Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((sympy.sqrt((Symbol('a') + Symbol('b'))) * Symbol('d')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**5/sqrt(a + b*sech(c + d*x)),
        variable=x,
        num_steps=5,
        integral=6*a*(a + b*sech(c + d*x))**(sympy.S(5)/2)/(5*b**4*d) + 2*a*sqrt(a + b*sech(c + d*x))*(a**2 - 2*b**2)/(b**4*d) - 2*(a + b*sech(c + d*x))**(sympy.S(7)/2)/(7*b**4*d) - (a + b*sech(c + d*x))**(sympy.S(3)/2)*(6*a**2 - 4*b**2)/(3*b**4*d) + 2*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/(sqrt(a)*d),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**3/sqrt(a + b*sech(c + d*x)),
        variable=x,
        num_steps=5,
        integral=-2*a*sqrt(a + b*sech(c + d*x))/(b**2*d) + 2*(a + b*sech(c + d*x))**(sympy.S(3)/2)/(3*b**2*d) + 2*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/(sqrt(a)*d),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)/sqrt(a + b*sech(c + d*x)),
        variable=x,
        num_steps=3,
        integral=2*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/(sqrt(a)*d),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)/sqrt(a + b*sech(c + d*x)),
        variable=x,
        num_steps=7,
        integral=-atanh(sqrt(a + b*sech(c + d*x))/sqrt(a + b))/(d*sqrt(a + b)) - atanh(sqrt(a + b*sech(c + d*x))/sqrt(a - b))/(d*sqrt(a - b)) + 2*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/(sqrt(a)*d),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)**3/sqrt(a + b*sech(c + d*x)),
        variable=x,
        num_steps=11,
        integral=-b*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a + b))/(4*d*(a + b)**(sympy.S(3)/2)) + b*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a - b))/(4*d*(a - b)**(sympy.S(3)/2)) - sqrt(a + b*sech(c + d*x))/(d*(4*a - 4*b)*(sech(c + d*x) + 1)) - atanh(sqrt(a + b*sech(c + d*x))/sqrt(a + b))/(d*sqrt(a + b)) - atanh(sqrt(a + b*sech(c + d*x))/sqrt(a - b))/(d*sqrt(a - b)) - sqrt(a + b*sech(c + d*x))/(d*(1 - sech(c + d*x))*(4*a + 4*b)) + 2*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/(sqrt(a)*d),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**4/sqrt(a + b*sech(c + d*x)),
        variable=x,
        num_steps=11,
        integral=((Integer(-1) * ((Integer(4) * (Symbol('a') + (Integer(-1) * Symbol('b'))) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_e(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * (((Symbol('b'))**(Integer(2)) * Symbol('d')))**(Integer(-1)))) + ((Integer(2) * (Symbol('a') + (Integer(-1) * Symbol('b'))) * sympy.sqrt((Symbol('a') + Symbol('b'))) * ((Integer(8) * (Symbol('a'))**(Integer(2))) + (Integer(9) * (Symbol('b'))**(Integer(2)))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_e(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Integer(15) * (Symbol('b'))**(Integer(4)) * Symbol('d')))**(Integer(-1))) + (Integer(-1) * ((Integer(4) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_f(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('b') * Symbol('d')))**(Integer(-1)))) + ((Integer(2) * sympy.sqrt((Symbol('a') + Symbol('b'))) * ((Integer(8) * (Symbol('a'))**(Integer(2))) + (Integer(-1) * (Integer(2) * Symbol('a') * Symbol('b'))) + (Integer(9) * (Symbol('b'))**(Integer(2)))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_f(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Integer(15) * (Symbol('b'))**(Integer(3)) * Symbol('d')))**(Integer(-1))) + ((Integer(2) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.Function('EllipticPi')(((Symbol('a') + Symbol('b')) * (Symbol('a'))**(Integer(-1))), sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('a') * Symbol('d')))**(Integer(-1))) + (Integer(-1) * ((Integer(8) * Symbol('a') * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * sympy.tanh((Symbol('c') + (Symbol('d') * x)))) * ((Integer(15) * (Symbol('b'))**(Integer(2)) * Symbol('d')))**(Integer(-1)))) + ((Integer(2) * sympy.sech((Symbol('c') + (Symbol('d') * x))) * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * sympy.tanh((Symbol('c') + (Symbol('d') * x)))) * ((Integer(5) * Symbol('b') * Symbol('d')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**2/sqrt(a + b*sech(c + d*x)),
        variable=x,
        num_steps=6,
        integral=((Integer(-1) * ((Integer(2) * (Symbol('a') + (Integer(-1) * Symbol('b'))) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_e(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * (((Symbol('b'))**(Integer(2)) * Symbol('d')))**(Integer(-1)))) + (Integer(-1) * ((Integer(2) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_f(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('b') * Symbol('d')))**(Integer(-1)))) + ((Integer(2) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.Function('EllipticPi')(((Symbol('a') + Symbol('b')) * (Symbol('a'))**(Integer(-1))), sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('a') * Symbol('d')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a + b*sech(c + d*x)),
        variable=x,
        num_steps=1,
        integral=((Integer(2) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.Function('EllipticPi')(((Symbol('a') + Symbol('b')) * (Symbol('a'))**(Integer(-1))), sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('a') * Symbol('d')))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)**2/sqrt(a + b*sech(c + d*x)),
        variable=x,
        num_steps=9,
        integral=(((sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_e(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((sympy.sqrt((Symbol('a') + Symbol('b'))) * Symbol('d')))**(Integer(-1))) + (Integer(-1) * ((sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_f(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((sympy.sqrt((Symbol('a') + Symbol('b'))) * Symbol('d')))**(Integer(-1)))) + ((Integer(2) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.Function('EllipticPi')(((Symbol('a') + Symbol('b')) * (Symbol('a'))**(Integer(-1))), sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('a') * Symbol('d')))**(Integer(-1))) + (Integer(-1) * (sympy.coth((Symbol('c') + (Symbol('d') * x))) * ((Symbol('d') * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))))**(Integer(-1)))) + (Integer(-1) * (((Symbol('b'))**(Integer(2)) * sympy.tanh((Symbol('c') + (Symbol('d') * x)))) * ((((Symbol('a'))**(Integer(2)) + (Integer(-1) * (Symbol('b'))**(Integer(2)))) * Symbol('d') * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**5/(a + b*sech(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=2*a*(a + b*sech(c + d*x))**(sympy.S(3)/2)/(b**4*d) - 2*(a + b*sech(c + d*x))**(sympy.S(5)/2)/(5*b**4*d) - sqrt(a + b*sech(c + d*x))*(6*a**2 - 4*b**2)/(b**4*d) - 2*(a**2 - b**2)**2/(a*b**4*d*sqrt(a + b*sech(c + d*x))) + 2*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/(a**(sympy.S(3)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**3/(a + b*sech(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=2*sqrt(a + b*sech(c + d*x))/(b**2*d) + (2*a**2 - 2*b**2)/(a*b**2*d*sqrt(a + b*sech(c + d*x))) + 2*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/(a**(sympy.S(3)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)/(a + b*sech(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=-2/(a*d*sqrt(a + b*sech(c + d*x))) + 2*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/(a**(sympy.S(3)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)/(a + b*sech(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=7,
        integral=-atanh(sqrt(a + b*sech(c + d*x))/sqrt(a + b))/(d*(a + b)**(sympy.S(3)/2)) - atanh(sqrt(a + b*sech(c + d*x))/sqrt(a - b))/(d*(a - b)**(sympy.S(3)/2)) + 2*b**2/(a*d*sqrt(a + b*sech(c + d*x))*(a**2 - b**2)) + 2*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/(a**(sympy.S(3)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)**3/(a + b*sech(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=11,
        integral=-b*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a + b))/(4*d*(a + b)**(sympy.S(5)/2)) + b*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a - b))/(4*d*(a - b)**(sympy.S(5)/2)) - (2*a + 3*b)*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a + b))/(2*d*(a + b)**(sympy.S(5)/2)) - sqrt(a + b*sech(c + d*x))/(4*d*(a - b)**2*(sech(c + d*x) + 1)) - (2*a - 3*b)*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a - b))/(2*d*(a - b)**(sympy.S(5)/2)) - sqrt(a + b*sech(c + d*x))/(4*d*(1 - sech(c + d*x))*(a + b)**2) - 2*b**4/(a*d*sqrt(a + b*sech(c + d*x))*(a**2 - b**2)**2) + 2*atanh(sqrt(a + b*sech(c + d*x))/sqrt(a))/(a**(sympy.S(3)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**4/(a + b*sech(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=17,
        integral=((Integer(-1) * ((Integer(2) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_e(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('a') * sympy.sqrt((Symbol('a') + Symbol('b'))) * Symbol('d')))**(Integer(-1)))) + ((Integer(4) * Symbol('a') * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_e(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * (((Symbol('b'))**(Integer(2)) * sympy.sqrt((Symbol('a') + Symbol('b'))) * Symbol('d')))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * Symbol('a') * ((Integer(8) * (Symbol('a'))**(Integer(2))) + (Integer(-1) * (Integer(5) * (Symbol('b'))**(Integer(2))))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_e(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Integer(3) * (Symbol('b'))**(Integer(4)) * sympy.sqrt((Symbol('a') + Symbol('b'))) * Symbol('d')))**(Integer(-1)))) + ((Integer(2) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_f(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('a') * sympy.sqrt((Symbol('a') + Symbol('b'))) * Symbol('d')))**(Integer(-1))) + ((Integer(4) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_f(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('b') * sympy.sqrt((Symbol('a') + Symbol('b'))) * Symbol('d')))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * ((Integer(2) * Symbol('a')) + Symbol('b')) * ((Integer(4) * Symbol('a')) + Symbol('b')) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_f(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Integer(3) * (Symbol('b'))**(Integer(3)) * sympy.sqrt((Symbol('a') + Symbol('b'))) * Symbol('d')))**(Integer(-1)))) + ((Integer(2) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.Function('EllipticPi')(((Symbol('a') + Symbol('b')) * (Symbol('a'))**(Integer(-1))), sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * (((Symbol('a'))**(Integer(2)) * Symbol('d')))**(Integer(-1))) + (Integer(-1) * ((Integer(4) * Symbol('a') * sympy.tanh((Symbol('c') + (Symbol('d') * x)))) * ((((Symbol('a'))**(Integer(2)) + (Integer(-1) * (Symbol('b'))**(Integer(2)))) * Symbol('d') * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))))**(Integer(-1)))) + ((Integer(2) * (Symbol('b'))**(Integer(2)) * sympy.tanh((Symbol('c') + (Symbol('d') * x)))) * ((Symbol('a') * ((Symbol('a'))**(Integer(2)) + (Integer(-1) * (Symbol('b'))**(Integer(2)))) * Symbol('d') * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * (Symbol('a'))**(Integer(2)) * sympy.sech((Symbol('c') + (Symbol('d') * x))) * sympy.tanh((Symbol('c') + (Symbol('d') * x)))) * ((Symbol('b') * ((Symbol('a'))**(Integer(2)) + (Integer(-1) * (Symbol('b'))**(Integer(2)))) * Symbol('d') * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))))**(Integer(-1)))) + ((Integer(2) * ((Integer(4) * (Symbol('a'))**(Integer(2))) + (Integer(-1) * (Symbol('b'))**(Integer(2)))) * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * sympy.tanh((Symbol('c') + (Symbol('d') * x)))) * ((Integer(3) * (Symbol('b'))**(Integer(2)) * ((Symbol('a'))**(Integer(2)) + (Integer(-1) * (Symbol('b'))**(Integer(2)))) * Symbol('d')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**2/(a + b*sech(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=7,
        integral=(((Integer(2) * (Symbol('a') + (Integer(-1) * Symbol('b'))) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_e(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('a') * (Symbol('b'))**(Integer(2)) * Symbol('d')))**(Integer(-1))) + ((Integer(2) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_f(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('a') * Symbol('b') * Symbol('d')))**(Integer(-1))) + ((Integer(2) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.Function('EllipticPi')(((Symbol('a') + Symbol('b')) * (Symbol('a'))**(Integer(-1))), sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * (((Symbol('a'))**(Integer(2)) * Symbol('d')))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * sympy.tanh((Symbol('c') + (Symbol('d') * x)))) * ((Symbol('a') * Symbol('d') * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*sech(c + d*x))**(sympy.S(-3)/2),
        variable=x,
        num_steps=6,
        integral=((Integer(-1) * ((Integer(2) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_e(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('a') * sympy.sqrt((Symbol('a') + Symbol('b'))) * Symbol('d')))**(Integer(-1)))) + ((Integer(2) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_f(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('a') * sympy.sqrt((Symbol('a') + Symbol('b'))) * Symbol('d')))**(Integer(-1))) + ((Integer(2) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.Function('EllipticPi')(((Symbol('a') + Symbol('b')) * (Symbol('a'))**(Integer(-1))), sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * (((Symbol('a'))**(Integer(2)) * Symbol('d')))**(Integer(-1))) + ((Integer(2) * (Symbol('b'))**(Integer(2)) * sympy.tanh((Symbol('c') + (Symbol('d') * x)))) * ((Symbol('a') * ((Symbol('a'))**(Integer(2)) + (Integer(-1) * (Symbol('b'))**(Integer(2)))) * Symbol('d') * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)**2/(a + b*sech(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=14,
        integral=(((Integer(4) * Symbol('a') * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_e(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * (((Symbol('a') + (Integer(-1) * Symbol('b'))) * ((Symbol('a') + Symbol('b')))**((Integer(3) * (Integer(2))**(Integer(-1)))) * Symbol('d')))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_e(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('a') * sympy.sqrt((Symbol('a') + Symbol('b'))) * Symbol('d')))**(Integer(-1)))) + (Integer(-1) * ((((Integer(3) * Symbol('a')) + (Integer(-1) * Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_f(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * (((Symbol('a') + (Integer(-1) * Symbol('b'))) * ((Symbol('a') + Symbol('b')))**((Integer(3) * (Integer(2))**(Integer(-1)))) * Symbol('d')))**(Integer(-1)))) + ((Integer(2) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.elliptic_f(sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Symbol('a') * sympy.sqrt((Symbol('a') + Symbol('b'))) * Symbol('d')))**(Integer(-1))) + ((Integer(2) * sympy.sqrt((Symbol('a') + Symbol('b'))) * sympy.coth((Symbol('c') + (Symbol('d') * x))) * sympy.Function('EllipticPi')(((Symbol('a') + Symbol('b')) * (Symbol('a'))**(Integer(-1))), sympy.asin((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * (sympy.sqrt((Symbol('a') + Symbol('b'))))**(Integer(-1)))), ((Symbol('a') + Symbol('b')) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))) * sympy.sqrt(((Symbol('b') * (Integer(1) + (Integer(-1) * sympy.sech((Symbol('c') + (Symbol('d') * x)))))) * ((Symbol('a') + Symbol('b')))**(Integer(-1)))) * sympy.sqrt((Integer(-1) * ((Symbol('b') * (Integer(1) + sympy.sech((Symbol('c') + (Symbol('d') * x))))) * ((Symbol('a') + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * (((Symbol('a'))**(Integer(2)) * Symbol('d')))**(Integer(-1))) + (Integer(-1) * (sympy.coth((Symbol('c') + (Symbol('d') * x))) * ((Symbol('d') * ((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * (((Symbol('b'))**(Integer(2)) * sympy.tanh((Symbol('c') + (Symbol('d') * x)))) * ((((Symbol('a'))**(Integer(2)) + (Integer(-1) * (Symbol('b'))**(Integer(2)))) * Symbol('d') * ((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((Integer(4) * Symbol('a') * (Symbol('b'))**(Integer(2)) * sympy.tanh((Symbol('c') + (Symbol('d') * x)))) * (((((Symbol('a'))**(Integer(2)) + (Integer(-1) * (Symbol('b'))**(Integer(2)))))**(Integer(2)) * Symbol('d') * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))))**(Integer(-1)))) + ((Integer(2) * (Symbol('b'))**(Integer(2)) * sympy.tanh((Symbol('c') + (Symbol('d') * x)))) * ((Symbol('a') * ((Symbol('a'))**(Integer(2)) + (Integer(-1) * (Symbol('b'))**(Integer(2)))) * Symbol('d') * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.sech((Symbol('c') + (Symbol('d') * x))))))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=(sech(a*c + b*c*x)**2)**(sympy.S(7)/2)*exp(c*(a + b*x)),
        variable=x,
        num_steps=6,
        integral=-64*sqrt(sech(a*c + b*c*x)**2)*cosh(a*c + b*c*x)/(3*b*c*(exp(2*c*(a + b*x)) + 1)**3) + 48*sqrt(sech(a*c + b*c*x)**2)*cosh(a*c + b*c*x)/(b*c*(exp(2*c*(a + b*x)) + 1)**4) - 192*sqrt(sech(a*c + b*c*x)**2)*cosh(a*c + b*c*x)/(5*b*c*(exp(2*c*(a + b*x)) + 1)**5) + 32*sqrt(sech(a*c + b*c*x)**2)*cosh(a*c + b*c*x)/(3*b*c*(exp(2*c*(a + b*x)) + 1)**6),
    ),
    RubiTestSuiteCase(
        integrand=(sech(a*c + b*c*x)**2)**(sympy.S(5)/2)*exp(c*(a + b*x)),
        variable=x,
        num_steps=6,
        integral=-8*sqrt(sech(a*c + b*c*x)**2)*cosh(a*c + b*c*x)/(b*c*(exp(2*c*(a + b*x)) + 1)**2) + 32*sqrt(sech(a*c + b*c*x)**2)*cosh(a*c + b*c*x)/(3*b*c*(exp(2*c*(a + b*x)) + 1)**3) - 4*sqrt(sech(a*c + b*c*x)**2)*cosh(a*c + b*c*x)/(b*c*(exp(2*c*(a + b*x)) + 1)**4),
    ),
    RubiTestSuiteCase(
        integrand=(sech(a*c + b*c*x)**2)**(sympy.S(3)/2)*exp(c*(a + b*x)),
        variable=x,
        num_steps=4,
        integral=2*sqrt(sech(a*c + b*c*x)**2)*exp(4*c*(a + b*x))*cosh(a*c + b*c*x)/(b*c*(exp(2*c*(a + b*x)) + 1)**2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sech(a*c + b*c*x)**2)*exp(c*(a + b*x)),
        variable=x,
        num_steps=4,
        integral=sqrt(sech(a*c + b*c*x)**2)*log(exp(2*c*(a + b*x)) + 1)*cosh(a*c + b*c*x)/(b*c),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))/sqrt(sech(a*c + b*c*x)**2),
        variable=x,
        num_steps=5,
        integral=x*sech(a*c + b*c*x)/(2*sqrt(sech(a*c + b*c*x)**2)) + exp(2*c*(a + b*x))*sech(a*c + b*c*x)/(4*b*c*sqrt(sech(a*c + b*c*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))/(sech(a*c + b*c*x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=3*x*sech(a*c + b*c*x)/(8*sqrt(sech(a*c + b*c*x)**2)) + exp(4*c*(a + b*x))*sech(a*c + b*c*x)/(32*b*c*sqrt(sech(a*c + b*c*x)**2)) + 3*exp(2*c*(a + b*x))*sech(a*c + b*c*x)/(16*b*c*sqrt(sech(a*c + b*c*x)**2)) - exp(-2*c*(a + b*x))*sech(a*c + b*c*x)/(16*b*c*sqrt(sech(a*c + b*c*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))/(sech(a*c + b*c*x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=6,
        integral=5*x*sech(a*c + b*c*x)/(16*sqrt(sech(a*c + b*c*x)**2)) + exp(6*c*(a + b*x))*sech(a*c + b*c*x)/(192*b*c*sqrt(sech(a*c + b*c*x)**2)) + 5*exp(4*c*(a + b*x))*sech(a*c + b*c*x)/(128*b*c*sqrt(sech(a*c + b*c*x)**2)) + 5*exp(2*c*(a + b*x))*sech(a*c + b*c*x)/(32*b*c*sqrt(sech(a*c + b*c*x)**2)) - 5*exp(-2*c*(a + b*x))*sech(a*c + b*c*x)/(64*b*c*sqrt(sech(a*c + b*c*x)**2)) - exp(-4*c*(a + b*x))*sech(a*c + b*c*x)/(128*b*c*sqrt(sech(a*c + b*c*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=x**5/sqrt(sech(2*log(c*x))),
        variable=x,
        num_steps=6,
        integral=x**6/(7*sqrt(sech(2*log(c*x)))) + 2*x**2/(21*c**4*sqrt(sech(2*log(c*x)))) + sqrt((c**4 + x**(-4))/(c**2 + x**(-2))**2)*(c**2 + x**(-2))*elliptic_f(2*acot(c*x), sympy.S.Half)/(21*c**5*x*(c**4 + x**(-4))*sqrt(sech(2*log(c*x)))),
    ),
    RubiTestSuiteCase(
        integrand=x**4/sqrt(sech(2*log(c*x))),
        variable=x,
        num_steps=3,
        integral=x**5*(c**4 + x**(-4))/(6*c**4*sqrt(sech(2*log(c*x)))),
    ),
    RubiTestSuiteCase(
        integrand=x**3/sqrt(sech(2*log(c*x))),
        variable=x,
        num_steps=8,
        integral=x**4/(5*sqrt(sech(2*log(c*x)))) + 2*sqrt((c**4 + x**(-4))/(c**2 + x**(-2))**2)*(c**2 + x**(-2))*elliptic_e(2*acot(c*x), sympy.S.Half)/(5*c**3*x*(c**4 + x**(-4))*sqrt(sech(2*log(c*x)))) - sqrt((c**4 + x**(-4))/(c**2 + x**(-2))**2)*(c**2 + x**(-2))*elliptic_f(2*acot(c*x), sympy.S.Half)/(5*c**3*x*(c**4 + x**(-4))*sqrt(sech(2*log(c*x)))) + 2/(5*c**4*sqrt(sech(2*log(c*x)))) - 2/(5*c**4*x**2*(c**2 + x**(-2))*sqrt(sech(2*log(c*x)))),
    ),
    RubiTestSuiteCase(
        integrand=x**2/sqrt(sech(2*log(c*x))),
        variable=x,
        num_steps=6,
        integral=x**3/(4*sqrt(sech(2*log(c*x)))) + atanh(sqrt(1 + 1/(c**4*x**4)))/(4*c**4*x*sqrt(1 + 1/(c**4*x**4))*sqrt(sech(2*log(c*x)))),
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(sech(2*log(c*x))),
        variable=x,
        num_steps=5,
        integral=x**2/(3*sqrt(sech(2*log(c*x)))) - sqrt((c**4 + x**(-4))/(c**2 + x**(-2))**2)*(c**2 + x**(-2))*elliptic_f(2*acot(c*x), sympy.S.Half)/(3*c*x*(c**4 + x**(-4))*sqrt(sech(2*log(c*x)))),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(sech(2*log(c*x))),
        variable=x,
        num_steps=6,
        integral=x/(2*sqrt(sech(2*log(c*x)))) - acsch(c**2*x**2)/(2*c**2*x*sqrt(1 + 1/(c**4*x**4))*sqrt(sech(2*log(c*x)))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sech(2*log(c*x)))/x,
        variable=x,
        num_steps=3,
        integral=-I*sqrt(cosh(2*log(c*x)))*elliptic_f(I*log(c*x), 2)*sqrt(sech(2*log(c*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sech(2*log(c*x)))/x**2,
        variable=x,
        num_steps=5,
        integral=-c**2*x*sqrt(1 + 1/(c**4*x**4))*acsch(c**2*x**2)*sqrt(sech(2*log(c*x)))/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sech(2*log(c*x)))/x**3,
        variable=x,
        num_steps=6,
        integral=c*x*sqrt((c**4 + x**(-4))/(c**2 + x**(-2))**2)*(c**2 + x**(-2))*elliptic_e(2*acot(c*x), sympy.S.Half)*sqrt(sech(2*log(c*x))) - c*x*sqrt((c**4 + x**(-4))/(c**2 + x**(-2))**2)*(c**2 + x**(-2))*elliptic_f(2*acot(c*x), sympy.S.Half)*sqrt(sech(2*log(c*x)))/2 - (c**4 + x**(-4))*sqrt(sech(2*log(c*x)))/(c**2 + x**(-2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sech(2*log(c*x)))/x**4,
        variable=x,
        num_steps=3,
        integral=x*(-c**4/2 - 1/(2*x**4))*sqrt(sech(2*log(c*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sech(2*log(c*x)))/x**5,
        variable=x,
        num_steps=5,
        integral=c**3*x*sqrt((c**4 + x**(-4))/(c**2 + x**(-2))**2)*(c**2 + x**(-2))*elliptic_f(2*acot(c*x), sympy.S.Half)*sqrt(sech(2*log(c*x)))/6 + (-c**4/3 - 1/(3*x**4))*sqrt(sech(2*log(c*x))),
    ),
    RubiTestSuiteCase(
        integrand=x**8/sech(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=8,
        integral=x**9/(12*sech(2*log(c*x))**(sympy.S(3)/2)) + x**5/((16*c**4 + 16/x**4)*sech(2*log(c*x))**(sympy.S(3)/2)) + x/(32*c**4*(c**4 + x**(-4))*sech(2*log(c*x))**(sympy.S(3)/2)) - atanh(sqrt(1 + 1/(c**4*x**4)))/(32*c**12*x**3*(1 + 1/(c**4*x**4))**(sympy.S(3)/2)*sech(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**7/sech(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=7,
        integral=x**8/(11*sech(2*log(c*x))**(sympy.S(3)/2)) + 6*x**4/((77*c**4 + 77/x**4)*sech(2*log(c*x))**(sympy.S(3)/2)) + 4/(77*c**4*(c**4 + x**(-4))*sech(2*log(c*x))**(sympy.S(3)/2)) + 2*sqrt((c**4 + x**(-4))/(c**2 + x**(-2))**2)*(c**2 + x**(-2))*elliptic_f(2*acot(c*x), sympy.S.Half)/(77*c**5*x**3*(c**4 + x**(-4))**2*sech(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**6/sech(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=x**7*(c**4 + x**(-4))/(10*c**4*sech(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**5/sech(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=9,
        integral=x**6/(9*sech(2*log(c*x))**(sympy.S(3)/2)) + 2*x**2/((15*c**4 + 15/x**4)*sech(2*log(c*x))**(sympy.S(3)/2)) + 4*sqrt((c**4 + x**(-4))/(c**2 + x**(-2))**2)*(c**2 + x**(-2))*elliptic_e(2*acot(c*x), sympy.S.Half)/(15*c**3*x**3*(c**4 + x**(-4))**2*sech(2*log(c*x))**(sympy.S(3)/2)) - 2*sqrt((c**4 + x**(-4))/(c**2 + x**(-2))**2)*(c**2 + x**(-2))*elliptic_f(2*acot(c*x), sympy.S.Half)/(15*c**3*x**3*(c**4 + x**(-4))**2*sech(2*log(c*x))**(sympy.S(3)/2)) + 4/(15*c**4*x**2*(c**4 + x**(-4))*sech(2*log(c*x))**(sympy.S(3)/2)) - 4/(15*c**4*x**4*(c**2 + x**(-2))*(c**4 + x**(-4))*sech(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**4/sech(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=7,
        integral=x**5/(8*sech(2*log(c*x))**(sympy.S(3)/2)) + 3*x/((16*c**4 + 16/x**4)*sech(2*log(c*x))**(sympy.S(3)/2)) + 3*atanh(sqrt(1 + 1/(c**4*x**4)))/(16*c**8*x**3*(1 + 1/(c**4*x**4))**(sympy.S(3)/2)*sech(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**3/sech(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=x**4/(7*sech(2*log(c*x))**(sympy.S(3)/2)) + 2/((7*c**4 + 7/x**4)*sech(2*log(c*x))**(sympy.S(3)/2)) - 2*sqrt((c**4 + x**(-4))/(c**2 + x**(-2))**2)*(c**2 + x**(-2))*elliptic_f(2*acot(c*x), sympy.S.Half)/(7*c*x**3*(c**4 + x**(-4))**2*sech(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**2/sech(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=7,
        integral=x**3/(6*sech(2*log(c*x))**(sympy.S(3)/2)) + 1/(x*(2*c**4 + 2/x**4)*sech(2*log(c*x))**(sympy.S(3)/2)) - acsch(c**2*x**2)/(2*c**6*x**3*(1 + 1/(c**4*x**4))**(sympy.S(3)/2)*sech(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x/sech(2*log(c*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=8,
        integral=12*c*sqrt((c**4 + x**(-4))/(c**2 + x**(-2))**2)*(c**2 + x**(-2))*elliptic_e(2*acot(c*x), sympy.S.Half)/(5*x**3*(c**4 + x**(-4))**2*sech(2*log(c*x))**(sympy.S(3)/2)) - 6*c*sqrt((c**4 + x**(-4))/(c**2 + x**(-2))**2)*(c**2 + x**(-2))*elliptic_f(2*acot(c*x), sympy.S.Half)/(5*x**3*(c**4 + x**(-4))**2*sech(2*log(c*x))**(sympy.S(3)/2)) + x**2/(5*sech(2*log(c*x))**(sympy.S(3)/2)) + 6/(x**2*(5*c**4 + 5/x**4)*sech(2*log(c*x))**(sympy.S(3)/2)) - 12/(x**4*(c**2 + x**(-2))*(5*c**4 + 5/x**4)*sech(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sech(2*log(c*x))**(sympy.S(-3)/2),
        variable=x,
        num_steps=7,
        integral=x/(4*sech(2*log(c*x))**(sympy.S(3)/2)) - 3/(x**3*(4*c**4 + 4/x**4)*sech(2*log(c*x))**(sympy.S(3)/2)) + 3*atanh(sqrt(1 + 1/(c**4*x**4)))/(4*c**4*x**3*(1 + 1/(c**4*x**4))**(sympy.S(3)/2)*sech(2*log(c*x))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sech(2*log(c*x))**(sympy.S(3)/2)/x,
        variable=x,
        num_steps=4,
        integral=sinh(2*log(c*x))*sqrt(sech(2*log(c*x))) + I*sqrt(cosh(2*log(c*x)))*elliptic_e(I*log(c*x), 2)*sqrt(sech(2*log(c*x))),
    ),
    RubiTestSuiteCase(
        integrand=sech(2*log(c*x))**(sympy.S(3)/2)/x**2,
        variable=x,
        num_steps=3,
        integral=x**3*(c**4/2 + 1/(2*x**4))*sech(2*log(c*x))**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=sech(2*log(c*x))**(sympy.S(3)/2)/x**3,
        variable=x,
        num_steps=5,
        integral=x**2*(c**4/2 + 1/(2*x**4))*sech(2*log(c*x))**(sympy.S(3)/2) - x**3*sqrt((c**4 + x**(-4))/(c**2 + x**(-2))**2)*(c**2 + x**(-2))*(c**4 + x**(-4))*elliptic_f(2*acot(c*x), sympy.S.Half)*sech(2*log(c*x))**(sympy.S(3)/2)/(4*c),
    ),
    RubiTestSuiteCase(
        integrand=sech(2*log(c*x))**(sympy.S(3)/2)/x**4,
        variable=x,
        num_steps=6,
        integral=-c**6*x**3*(1 + 1/(c**4*x**4))**(sympy.S(3)/2)*acsch(c**2*x**2)*sech(2*log(c*x))**(sympy.S(3)/2)/2 + x*(c**4/2 + 1/(2*x**4))*sech(2*log(c*x))**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*log(c*x**n)),
        variable=x,
        num_steps=4,
        integral=2*x*(c*x**n)**b*exp(a)*hyper((1, (b + 1/n)/(2*b)), (sympy.S(3)/2 + 1/(2*b*n),), -(c*x**n)**(2*b)*exp(2*a))/(b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=4,
        integral=4*x*(c*x**n)**(2*b)*exp(2*a)*hyper((2, 1 + 1/(2*b*n)), (2 + 1/(2*b*n),), -(c*x**n)**(2*b)*exp(2*a))/(2*b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=4,
        integral=8*x*(c*x**n)**(3*b)*exp(3*a)*hyper((3, (3*b + 1/n)/(2*b)), (sympy.S(5)/2 + 1/(2*b*n),), -(c*x**n)**(2*b)*exp(2*a))/(3*b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*log(c*x**n))**4,
        variable=x,
        num_steps=4,
        integral=16*x*(c*x**n)**(4*b)*exp(4*a)*hyper((4, 2 + 1/(2*b*n)), (3 + 1/(2*b*n),), -(c*x**n)**(2*b)*exp(2*a))/(4*b*n + 1),
    ),
    RubiTestSuiteCase(
        integrand=2*b**2*n**2*sech(a + b*log(c*x**n))**3 + (-b**2*n**2 + 1)*sech(a + b*log(c*x**n)),
        variable=x,
        num_steps=-9,
        integral=b*n*x*tanh(a + b*log(c*x**n))*sech(a + b*log(c*x**n)) + x*sech(a + b*log(c*x**n)),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + 2*log(c*sqrt(x)))**3,
        variable=x,
        num_steps=3,
        integral=2*c**6*exp(-a)/(c**4 + exp(-2*a)/x**2)**2,
    ),
    RubiTestSuiteCase(
        integrand=sech(a + 2*log(c/sqrt(x)))**3,
        variable=x,
        num_steps=4,
        integral=2*c**2*exp(-3*a)/(c**4/x**2 + exp(-2*a))**2,
    ),
    RubiTestSuiteCase(
        integrand=sech(a + log(c*x**n)/(n*(p - 2)))**p,
        variable=x,
        num_steps=3,
        integral=x*(2 - p)*((c*x**n)**(2/(n*(2 - p)))*exp(-2*a) + 1)*exp(2*a)*sech(a - log(c*x**n)/(n*(2 - p)))**p/((c*x**n)**(2/(n*(2 - p)))*(2 - 2*p)),
    ),
    RubiTestSuiteCase(
        integrand=sech(a - log(c*x**n)/(n*(p - 2)))**p,
        variable=x,
        num_steps=3,
        integral=x*(1 + exp(-2*a)/(c*x**n)**(2/(n*(2 - p))))*(2 - p)*sech(a + log(c*x**n)/(n*(2 - p)))**p/(2 - 2*p),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*log(c*x**n))/x,
        variable=x,
        num_steps=2,
        integral=atan(sinh(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*log(c*x**n))**2/x,
        variable=x,
        num_steps=3,
        integral=tanh(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*log(c*x**n))**3/x,
        variable=x,
        num_steps=3,
        integral=tanh(a + b*log(c*x**n))*sech(a + b*log(c*x**n))/(2*b*n) + atan(sinh(a + b*log(c*x**n)))/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*log(c*x**n))**4/x,
        variable=x,
        num_steps=3,
        integral=-tanh(a + b*log(c*x**n))**3/(3*b*n) + tanh(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*log(c*x**n))**5/x,
        variable=x,
        num_steps=4,
        integral=tanh(a + b*log(c*x**n))*sech(a + b*log(c*x**n))**3/(4*b*n) + 3*tanh(a + b*log(c*x**n))*sech(a + b*log(c*x**n))/(8*b*n) + 3*atan(sinh(a + b*log(c*x**n)))/(8*b*n),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*log(c*x**n))**(sympy.S(5)/2)/x,
        variable=x,
        num_steps=4,
        integral=2*sinh(a + b*log(c*x**n))*sech(a + b*log(c*x**n))**(sympy.S(3)/2)/(3*b*n) - 2*I*sqrt(cosh(a + b*log(c*x**n)))*elliptic_f(I*(a + b*log(c*x**n))/2, 2)*sqrt(sech(a + b*log(c*x**n)))/(3*b*n),
    ),
    RubiTestSuiteCase(
        integrand=sech(a + b*log(c*x**n))**(sympy.S(3)/2)/x,
        variable=x,
        num_steps=4,
        integral=2*sinh(a + b*log(c*x**n))*sqrt(sech(a + b*log(c*x**n)))/(b*n) + 2*I*sqrt(cosh(a + b*log(c*x**n)))*elliptic_e(I*(a + b*log(c*x**n))/2, 2)*sqrt(sech(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sech(a + b*log(c*x**n)))/x,
        variable=x,
        num_steps=3,
        integral=-2*I*sqrt(cosh(a + b*log(c*x**n)))*elliptic_f(I*(a + b*log(c*x**n))/2, 2)*sqrt(sech(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(sech(a + b*log(c*x**n)))),
        variable=x,
        num_steps=3,
        integral=-2*I*sqrt(cosh(a + b*log(c*x**n)))*elliptic_e(I*(a + b*log(c*x**n))/2, 2)*sqrt(sech(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sech(a + b*log(c*x**n))**(sympy.S(3)/2)),
        variable=x,
        num_steps=4,
        integral=2*sinh(a + b*log(c*x**n))/(3*b*n*sqrt(sech(a + b*log(c*x**n)))) - 2*I*sqrt(cosh(a + b*log(c*x**n)))*elliptic_f(I*(a + b*log(c*x**n))/2, 2)*sqrt(sech(a + b*log(c*x**n)))/(3*b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sech(a + b*log(c*x**n))**(sympy.S(5)/2)),
        variable=x,
        num_steps=4,
        integral=2*sinh(a + b*log(c*x**n))/(5*b*n*sech(a + b*log(c*x**n))**(sympy.S(3)/2)) - 6*I*sqrt(cosh(a + b*log(c*x**n)))*elliptic_e(I*(a + b*log(c*x**n))/2, 2)*sqrt(sech(a + b*log(c*x**n)))/(5*b*n),
    ),
]
