# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 3 Logarithms/3.1.2 (d x)^m (a+b log(c x^n))^p.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '3 Logarithms/3.1.2 (d x)^m (a+b log(c x^n))^p.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, c, d, d1, d2, m, m1, m2, n, p, q, q1, q2 = symbols('a b c d d1 d2 m m1 m2 n p q q1 q2')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=x**3*log(c*x),
        variable=x,
        num_steps=1,
        integral=x**4*log(c*x)/4 - x**4/16,
    ),
    RubiTestSuiteCase(
        integrand=x**2*log(c*x),
        variable=x,
        num_steps=1,
        integral=x**3*log(c*x)/3 - x**3/9,
    ),
    RubiTestSuiteCase(
        integrand=x*log(c*x),
        variable=x,
        num_steps=1,
        integral=x**2*log(c*x)/2 - x**2/4,
    ),
    RubiTestSuiteCase(
        integrand=log(c*x),
        variable=x,
        num_steps=1,
        integral=x*log(c*x) - x,
    ),
    RubiTestSuiteCase(
        integrand=log(c*x)/x,
        variable=x,
        num_steps=1,
        integral=log(c*x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=log(c*x)/x**2,
        variable=x,
        num_steps=1,
        integral=-log(c*x)/x - 1/x,
    ),
    RubiTestSuiteCase(
        integrand=log(c*x)/x**3,
        variable=x,
        num_steps=1,
        integral=-log(c*x)/(2*x**2) - 1/(4*x**2),
    ),
    RubiTestSuiteCase(
        integrand=x**3*log(c*x)**2,
        variable=x,
        num_steps=2,
        integral=x**4*log(c*x)**2/4 - x**4*log(c*x)/8 + x**4/32,
    ),
    RubiTestSuiteCase(
        integrand=x**2*log(c*x)**2,
        variable=x,
        num_steps=2,
        integral=x**3*log(c*x)**2/3 - 2*x**3*log(c*x)/9 + 2*x**3/27,
    ),
    RubiTestSuiteCase(
        integrand=x*log(c*x)**2,
        variable=x,
        num_steps=2,
        integral=x**2*log(c*x)**2/2 - x**2*log(c*x)/2 + x**2/4,
    ),
    RubiTestSuiteCase(
        integrand=log(c*x)**2,
        variable=x,
        num_steps=2,
        integral=x*log(c*x)**2 - 2*x*log(c*x) + 2*x,
    ),
    RubiTestSuiteCase(
        integrand=log(c*x)**2/x,
        variable=x,
        num_steps=2,
        integral=log(c*x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=log(c*x)**2/x**2,
        variable=x,
        num_steps=2,
        integral=-log(c*x)**2/x - 2*log(c*x)/x - 2/x,
    ),
    RubiTestSuiteCase(
        integrand=log(c*x)**2/x**3,
        variable=x,
        num_steps=2,
        integral=-log(c*x)**2/(2*x**2) - log(c*x)/(2*x**2) - 1/(4*x**2),
    ),
    RubiTestSuiteCase(
        integrand=x**3*log(c*x)**3,
        variable=x,
        num_steps=3,
        integral=x**4*log(c*x)**3/4 - 3*x**4*log(c*x)**2/16 + 3*x**4*log(c*x)/32 - 3*x**4/128,
    ),
    RubiTestSuiteCase(
        integrand=x**2*log(c*x)**3,
        variable=x,
        num_steps=3,
        integral=x**3*log(c*x)**3/3 - x**3*log(c*x)**2/3 + 2*x**3*log(c*x)/9 - 2*x**3/27,
    ),
    RubiTestSuiteCase(
        integrand=x*log(c*x)**3,
        variable=x,
        num_steps=3,
        integral=x**2*log(c*x)**3/2 - 3*x**2*log(c*x)**2/4 + 3*x**2*log(c*x)/4 - 3*x**2/8,
    ),
    RubiTestSuiteCase(
        integrand=log(c*x)**3,
        variable=x,
        num_steps=3,
        integral=x*log(c*x)**3 - 3*x*log(c*x)**2 + 6*x*log(c*x) - 6*x,
    ),
    RubiTestSuiteCase(
        integrand=log(c*x)**3/x,
        variable=x,
        num_steps=2,
        integral=log(c*x)**4/4,
    ),
    RubiTestSuiteCase(
        integrand=log(c*x)**3/x**2,
        variable=x,
        num_steps=3,
        integral=-log(c*x)**3/x - 3*log(c*x)**2/x - 6*log(c*x)/x - 6/x,
    ),
    RubiTestSuiteCase(
        integrand=log(c*x)**3/x**3,
        variable=x,
        num_steps=3,
        integral=-log(c*x)**3/(2*x**2) - 3*log(c*x)**2/(4*x**2) - 3*log(c*x)/(4*x**2) - 3/(8*x**2),
    ),
    RubiTestSuiteCase(
        integrand=x**3/log(c*x),
        variable=x,
        num_steps=2,
        integral=(sympy.Function('ExpIntegralEi')((Integer(4) * sympy.log((Symbol('c') * x)))) * ((Symbol('c'))**(Integer(4)))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x**2/log(c*x),
        variable=x,
        num_steps=2,
        integral=(sympy.Function('ExpIntegralEi')((Integer(3) * sympy.log((Symbol('c') * x)))) * ((Symbol('c'))**(Integer(3)))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x/log(c*x),
        variable=x,
        num_steps=2,
        integral=(sympy.Function('ExpIntegralEi')((Integer(2) * sympy.log((Symbol('c') * x)))) * ((Symbol('c'))**(Integer(2)))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/log(c*x),
        variable=x,
        num_steps=1,
        integral=(sympy.Function('LogIntegral')((Symbol('c') * x)) * (Symbol('c'))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*log(c*x)),
        variable=x,
        num_steps=2,
        integral=log(log(c*x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*log(c*x)),
        variable=x,
        num_steps=2,
        integral=(Symbol('c') * sympy.Function('ExpIntegralEi')((Integer(-1) * sympy.log((Symbol('c') * x))))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3*log(c*x)),
        variable=x,
        num_steps=2,
        integral=((Symbol('c'))**(Integer(2)) * sympy.Function('ExpIntegralEi')((Integer(-2) * sympy.log((Symbol('c') * x))))),
    ),
    RubiTestSuiteCase(
        integrand=x**3/log(c*x)**2,
        variable=x,
        num_steps=3,
        integral=(((Integer(4) * sympy.Function('ExpIntegralEi')((Integer(4) * sympy.log((Symbol('c') * x))))) * ((Symbol('c'))**(Integer(4)))**(Integer(-1))) + (Integer(-1) * ((x)**(Integer(4)) * (sympy.log((Symbol('c') * x)))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**2/log(c*x)**2,
        variable=x,
        num_steps=3,
        integral=(((Integer(3) * sympy.Function('ExpIntegralEi')((Integer(3) * sympy.log((Symbol('c') * x))))) * ((Symbol('c'))**(Integer(3)))**(Integer(-1))) + (Integer(-1) * ((x)**(Integer(3)) * (sympy.log((Symbol('c') * x)))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x/log(c*x)**2,
        variable=x,
        num_steps=3,
        integral=(((Integer(2) * sympy.Function('ExpIntegralEi')((Integer(2) * sympy.log((Symbol('c') * x))))) * ((Symbol('c'))**(Integer(2)))**(Integer(-1))) + (Integer(-1) * ((x)**(Integer(2)) * (sympy.log((Symbol('c') * x)))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=log(c*x)**(-2),
        variable=x,
        num_steps=2,
        integral=((Integer(-1) * (x * (sympy.log((Symbol('c') * x)))**(Integer(-1)))) + (sympy.Function('LogIntegral')((Symbol('c') * x)) * (Symbol('c'))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*log(c*x)**2),
        variable=x,
        num_steps=2,
        integral=-1/log(c*x),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*log(c*x)**2),
        variable=x,
        num_steps=3,
        integral=((Integer(-1) * (Symbol('c') * sympy.Function('ExpIntegralEi')((Integer(-1) * sympy.log((Symbol('c') * x)))))) + (Integer(-1) * ((x * sympy.log((Symbol('c') * x))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3*log(c*x)**2),
        variable=x,
        num_steps=3,
        integral=((Integer(-2) * (Symbol('c'))**(Integer(2)) * sympy.Function('ExpIntegralEi')((Integer(-2) * sympy.log((Symbol('c') * x))))) + (Integer(-1) * (((x)**(Integer(2)) * sympy.log((Symbol('c') * x))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x**3/log(c*x)**3,
        variable=x,
        num_steps=4,
        integral=(((Integer(8) * sympy.Function('ExpIntegralEi')((Integer(4) * sympy.log((Symbol('c') * x))))) * ((Symbol('c'))**(Integer(4)))**(Integer(-1))) + (Integer(-1) * ((x)**(Integer(4)) * ((Integer(2) * (sympy.log((Symbol('c') * x)))**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * ((Integer(2) * (x)**(Integer(4))) * (sympy.log((Symbol('c') * x)))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**2/log(c*x)**3,
        variable=x,
        num_steps=4,
        integral=(((Integer(9) * sympy.Function('ExpIntegralEi')((Integer(3) * sympy.log((Symbol('c') * x))))) * ((Integer(2) * (Symbol('c'))**(Integer(3))))**(Integer(-1))) + (Integer(-1) * ((x)**(Integer(3)) * ((Integer(2) * (sympy.log((Symbol('c') * x)))**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * (x)**(Integer(3))) * ((Integer(2) * sympy.log((Symbol('c') * x))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x/log(c*x)**3,
        variable=x,
        num_steps=4,
        integral=(((Integer(2) * sympy.Function('ExpIntegralEi')((Integer(2) * sympy.log((Symbol('c') * x))))) * ((Symbol('c'))**(Integer(2)))**(Integer(-1))) + (Integer(-1) * ((x)**(Integer(2)) * ((Integer(2) * (sympy.log((Symbol('c') * x)))**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * ((x)**(Integer(2)) * (sympy.log((Symbol('c') * x)))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=log(c*x)**(-3),
        variable=x,
        num_steps=3,
        integral=((Integer(-1) * (x * ((Integer(2) * (sympy.log((Symbol('c') * x)))**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * (x * ((Integer(2) * sympy.log((Symbol('c') * x))))**(Integer(-1)))) + (sympy.Function('LogIntegral')((Symbol('c') * x)) * ((Integer(2) * Symbol('c')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*log(c*x)**3),
        variable=x,
        num_steps=2,
        integral=-1/(2*log(c*x)**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*log(c*x)**3),
        variable=x,
        num_steps=4,
        integral=(((Integer(2))**(Integer(-1)) * Symbol('c') * sympy.Function('ExpIntegralEi')((Integer(-1) * sympy.log((Symbol('c') * x))))) + (Integer(-1) * ((Integer(2) * x * (sympy.log((Symbol('c') * x)))**(Integer(2))))**(Integer(-1))) + ((Integer(2) * x * sympy.log((Symbol('c') * x))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3*log(c*x)**3),
        variable=x,
        num_steps=4,
        integral=((Integer(2) * (Symbol('c'))**(Integer(2)) * sympy.Function('ExpIntegralEi')((Integer(-2) * sympy.log((Symbol('c') * x))))) + (Integer(-1) * ((Integer(2) * (x)**(Integer(2)) * (sympy.log((Symbol('c') * x)))**(Integer(2))))**(Integer(-1))) + (((x)**(Integer(2)) * sympy.log((Symbol('c') * x))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x**3*(a + b*log(c*x**n)),
        variable=x,
        num_steps=1,
        integral=-b*n*x**4/16 + x**4*(a + b*log(c*x**n))/4,
    ),
    RubiTestSuiteCase(
        integrand=x**2*(a + b*log(c*x**n)),
        variable=x,
        num_steps=1,
        integral=-b*n*x**3/9 + x**3*(a + b*log(c*x**n))/3,
    ),
    RubiTestSuiteCase(
        integrand=x*(a + b*log(c*x**n)),
        variable=x,
        num_steps=1,
        integral=-b*n*x**2/4 + x**2*(a + b*log(c*x**n))/2,
    ),
    RubiTestSuiteCase(
        integrand=a + b*log(c*x**n),
        variable=x,
        num_steps=2,
        integral=a*x - b*n*x + b*x*log(c*x**n),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))/x,
        variable=x,
        num_steps=1,
        integral=(a + b*log(c*x**n))**2/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))/x**2,
        variable=x,
        num_steps=1,
        integral=-b*n/x - (a + b*log(c*x**n))/x,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))/x**3,
        variable=x,
        num_steps=1,
        integral=-b*n/(4*x**2) - (a + b*log(c*x**n))/(2*x**2),
    ),
    RubiTestSuiteCase(
        integrand=x**3*(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=2,
        integral=b**2*n**2*x**4/32 - b*n*x**4*(a + b*log(c*x**n))/8 + x**4*(a + b*log(c*x**n))**2/4,
    ),
    RubiTestSuiteCase(
        integrand=x**2*(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=2,
        integral=2*b**2*n**2*x**3/27 - 2*b*n*x**3*(a + b*log(c*x**n))/9 + x**3*(a + b*log(c*x**n))**2/3,
    ),
    RubiTestSuiteCase(
        integrand=x*(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=2,
        integral=b**2*n**2*x**2/4 - b*n*x**2*(a + b*log(c*x**n))/2 + x**2*(a + b*log(c*x**n))**2/2,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=3,
        integral=-2*a*b*n*x + 2*b**2*n**2*x - 2*b**2*n*x*log(c*x**n) + x*(a + b*log(c*x**n))**2,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**2/x,
        variable=x,
        num_steps=2,
        integral=(a + b*log(c*x**n))**3/(3*b*n),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**2/x**2,
        variable=x,
        num_steps=2,
        integral=-2*b**2*n**2/x - 2*b*n*(a + b*log(c*x**n))/x - (a + b*log(c*x**n))**2/x,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**2/x**3,
        variable=x,
        num_steps=2,
        integral=-b**2*n**2/(4*x**2) - b*n*(a + b*log(c*x**n))/(2*x**2) - (a + b*log(c*x**n))**2/(2*x**2),
    ),
    RubiTestSuiteCase(
        integrand=x**3*(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=3,
        integral=-3*b**3*n**3*x**4/128 + 3*b**2*n**2*x**4*(a + b*log(c*x**n))/32 - 3*b*n*x**4*(a + b*log(c*x**n))**2/16 + x**4*(a + b*log(c*x**n))**3/4,
    ),
    RubiTestSuiteCase(
        integrand=x**2*(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=3,
        integral=-2*b**3*n**3*x**3/27 + 2*b**2*n**2*x**3*(a + b*log(c*x**n))/9 - b*n*x**3*(a + b*log(c*x**n))**2/3 + x**3*(a + b*log(c*x**n))**3/3,
    ),
    RubiTestSuiteCase(
        integrand=x*(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=3,
        integral=-3*b**3*n**3*x**2/8 + 3*b**2*n**2*x**2*(a + b*log(c*x**n))/4 - 3*b*n*x**2*(a + b*log(c*x**n))**2/4 + x**2*(a + b*log(c*x**n))**3/2,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=4,
        integral=6*a*b**2*n**2*x - 6*b**3*n**3*x + 6*b**3*n**2*x*log(c*x**n) - 3*b*n*x*(a + b*log(c*x**n))**2 + x*(a + b*log(c*x**n))**3,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**3/x,
        variable=x,
        num_steps=2,
        integral=(a + b*log(c*x**n))**4/(4*b*n),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**3/x**2,
        variable=x,
        num_steps=3,
        integral=-6*b**3*n**3/x - 6*b**2*n**2*(a + b*log(c*x**n))/x - 3*b*n*(a + b*log(c*x**n))**2/x - (a + b*log(c*x**n))**3/x,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**3/x**3,
        variable=x,
        num_steps=3,
        integral=-3*b**3*n**3/(8*x**2) - 3*b**2*n**2*(a + b*log(c*x**n))/(4*x**2) - 3*b*n*(a + b*log(c*x**n))**2/(4*x**2) - (a + b*log(c*x**n))**3/(2*x**2),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**3/x**4,
        variable=x,
        num_steps=3,
        integral=-2*b**3*n**3/(27*x**3) - 2*b**2*n**2*(a + b*log(c*x**n))/(9*x**3) - b*n*(a + b*log(c*x**n))**2/(3*x**3) - (a + b*log(c*x**n))**3/(3*x**3),
    ),
    RubiTestSuiteCase(
        integrand=x**3/(a + b*log(c*x**n)),
        variable=x,
        num_steps=2,
        integral=(((x)**(Integer(4)) * sympy.Function('ExpIntegralEi')(((Integer(4) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('b') * (sympy.E)**(((Integer(4) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * Symbol('n') * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(4) * (Symbol('n'))**(Integer(-1))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x**2/(a + b*log(c*x**n)),
        variable=x,
        num_steps=2,
        integral=(((x)**(Integer(3)) * sympy.Function('ExpIntegralEi')(((Integer(3) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('b') * (sympy.E)**(((Integer(3) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * Symbol('n') * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(3) * (Symbol('n'))**(Integer(-1))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x/(a + b*log(c*x**n)),
        variable=x,
        num_steps=2,
        integral=(((x)**(Integer(2)) * sympy.Function('ExpIntegralEi')(((Integer(2) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('b') * (sympy.E)**(((Integer(2) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * Symbol('n') * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*log(c*x**n)),
        variable=x,
        num_steps=2,
        integral=((x * sympy.Function('ExpIntegralEi')(((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('b') * (sympy.E)**((Symbol('a') * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * Symbol('n') * ((Symbol('c') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1)))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*(a + b*log(c*x**n))),
        variable=x,
        num_steps=2,
        integral=log(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*(a + b*log(c*x**n))),
        variable=x,
        num_steps=2,
        integral=(((sympy.E)**((Symbol('a') * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * sympy.Function('ExpIntegralEi')((Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))))) * ((Symbol('b') * Symbol('n') * x))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3*(a + b*log(c*x**n))),
        variable=x,
        num_steps=2,
        integral=(((sympy.E)**(((Integer(2) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1)))) * sympy.Function('ExpIntegralEi')(((Integer(-2) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('b') * Symbol('n') * (x)**(Integer(2))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4*(a + b*log(c*x**n))),
        variable=x,
        num_steps=2,
        integral=(((sympy.E)**(((Integer(3) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(3) * (Symbol('n'))**(Integer(-1)))) * sympy.Function('ExpIntegralEi')(((Integer(-3) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('b') * Symbol('n') * (x)**(Integer(3))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x**3/(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=3,
        integral=(((Integer(4) * (x)**(Integer(4)) * sympy.Function('ExpIntegralEi')(((Integer(4) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * (((Symbol('b'))**(Integer(2)) * (sympy.E)**(((Integer(4) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * (Symbol('n'))**(Integer(2)) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(4) * (Symbol('n'))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((x)**(Integer(4)) * ((Symbol('b') * Symbol('n') * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**2/(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=3,
        integral=(((Integer(3) * (x)**(Integer(3)) * sympy.Function('ExpIntegralEi')(((Integer(3) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * (((Symbol('b'))**(Integer(2)) * (sympy.E)**(((Integer(3) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * (Symbol('n'))**(Integer(2)) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(3) * (Symbol('n'))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((x)**(Integer(3)) * ((Symbol('b') * Symbol('n') * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x/(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=3,
        integral=(((Integer(2) * (x)**(Integer(2)) * sympy.Function('ExpIntegralEi')(((Integer(2) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * (((Symbol('b'))**(Integer(2)) * (sympy.E)**(((Integer(2) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * (Symbol('n'))**(Integer(2)) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((x)**(Integer(2)) * ((Symbol('b') * Symbol('n') * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**(-2),
        variable=x,
        num_steps=3,
        integral=(((x * sympy.Function('ExpIntegralEi')(((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * (((Symbol('b'))**(Integer(2)) * (sympy.E)**((Symbol('a') * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * (Symbol('n'))**(Integer(2)) * ((Symbol('c') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1)))))**(Integer(-1))) + (Integer(-1) * (x * ((Symbol('b') * Symbol('n') * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*(a + b*log(c*x**n))**2),
        variable=x,
        num_steps=2,
        integral=-1/(b*n*(a + b*log(c*x**n))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*(a + b*log(c*x**n))**2),
        variable=x,
        num_steps=3,
        integral=((Integer(-1) * (((sympy.E)**((Symbol('a') * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * sympy.Function('ExpIntegralEi')((Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))))) * (((Symbol('b'))**(Integer(2)) * (Symbol('n'))**(Integer(2)) * x))**(Integer(-1)))) + (Integer(-1) * ((Symbol('b') * Symbol('n') * x * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3*(a + b*log(c*x**n))**2),
        variable=x,
        num_steps=3,
        integral=(((Integer(-2) * (sympy.E)**(((Integer(2) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1)))) * sympy.Function('ExpIntegralEi')(((Integer(-2) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * (((Symbol('b'))**(Integer(2)) * (Symbol('n'))**(Integer(2)) * (x)**(Integer(2))))**(Integer(-1))) + (Integer(-1) * ((Symbol('b') * Symbol('n') * (x)**(Integer(2)) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4*(a + b*log(c*x**n))**2),
        variable=x,
        num_steps=3,
        integral=(((Integer(-3) * (sympy.E)**(((Integer(3) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(3) * (Symbol('n'))**(Integer(-1)))) * sympy.Function('ExpIntegralEi')(((Integer(-3) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * (((Symbol('b'))**(Integer(2)) * (Symbol('n'))**(Integer(2)) * (x)**(Integer(3))))**(Integer(-1))) + (Integer(-1) * ((Symbol('b') * Symbol('n') * (x)**(Integer(3)) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x**3/(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=4,
        integral=(((Integer(8) * (x)**(Integer(4)) * sympy.Function('ExpIntegralEi')(((Integer(4) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * (((Symbol('b'))**(Integer(3)) * (sympy.E)**(((Integer(4) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * (Symbol('n'))**(Integer(3)) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(4) * (Symbol('n'))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((x)**(Integer(4)) * ((Integer(2) * Symbol('b') * Symbol('n') * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * ((Integer(2) * (x)**(Integer(4))) * (((Symbol('b'))**(Integer(2)) * (Symbol('n'))**(Integer(2)) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**2/(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=4,
        integral=(((Integer(9) * (x)**(Integer(3)) * sympy.Function('ExpIntegralEi')(((Integer(3) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Integer(2) * (Symbol('b'))**(Integer(3)) * (sympy.E)**(((Integer(3) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * (Symbol('n'))**(Integer(3)) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(3) * (Symbol('n'))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((x)**(Integer(3)) * ((Integer(2) * Symbol('b') * Symbol('n') * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * (x)**(Integer(3))) * ((Integer(2) * (Symbol('b'))**(Integer(2)) * (Symbol('n'))**(Integer(2)) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x/(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=4,
        integral=(((Integer(2) * (x)**(Integer(2)) * sympy.Function('ExpIntegralEi')(((Integer(2) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * (((Symbol('b'))**(Integer(3)) * (sympy.E)**(((Integer(2) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * (Symbol('n'))**(Integer(3)) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((x)**(Integer(2)) * ((Integer(2) * Symbol('b') * Symbol('n') * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * ((x)**(Integer(2)) * (((Symbol('b'))**(Integer(2)) * (Symbol('n'))**(Integer(2)) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**(-3),
        variable=x,
        num_steps=4,
        integral=(((x * sympy.Function('ExpIntegralEi')(((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Integer(2) * (Symbol('b'))**(Integer(3)) * (sympy.E)**((Symbol('a') * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * (Symbol('n'))**(Integer(3)) * ((Symbol('c') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1)))))**(Integer(-1))) + (Integer(-1) * (x * ((Integer(2) * Symbol('b') * Symbol('n') * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * (x * ((Integer(2) * (Symbol('b'))**(Integer(2)) * (Symbol('n'))**(Integer(2)) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*(a + b*log(c*x**n))**3),
        variable=x,
        num_steps=2,
        integral=-1/(2*b*n*(a + b*log(c*x**n))**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*(a + b*log(c*x**n))**3),
        variable=x,
        num_steps=4,
        integral=((((sympy.E)**((Symbol('a') * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * sympy.Function('ExpIntegralEi')((Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))))) * ((Integer(2) * (Symbol('b'))**(Integer(3)) * (Symbol('n'))**(Integer(3)) * x))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * Symbol('b') * Symbol('n') * x * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Integer(2))))**(Integer(-1))) + ((Integer(2) * (Symbol('b'))**(Integer(2)) * (Symbol('n'))**(Integer(2)) * x * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3*(a + b*log(c*x**n))**3),
        variable=x,
        num_steps=4,
        integral=(((Integer(2) * (sympy.E)**(((Integer(2) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1)))) * sympy.Function('ExpIntegralEi')(((Integer(-2) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * (((Symbol('b'))**(Integer(3)) * (Symbol('n'))**(Integer(3)) * (x)**(Integer(2))))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * Symbol('b') * Symbol('n') * (x)**(Integer(2)) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Integer(2))))**(Integer(-1))) + (((Symbol('b'))**(Integer(2)) * (Symbol('n'))**(Integer(2)) * (x)**(Integer(2)) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4*(a + b*log(c*x**n))**3),
        variable=x,
        num_steps=4,
        integral=(((Integer(9) * (sympy.E)**(((Integer(3) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(3) * (Symbol('n'))**(Integer(-1)))) * sympy.Function('ExpIntegralEi')(((Integer(-3) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Integer(2) * (Symbol('b'))**(Integer(3)) * (Symbol('n'))**(Integer(3)) * (x)**(Integer(3))))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * Symbol('b') * Symbol('n') * (x)**(Integer(3)) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Integer(2))))**(Integer(-1))) + (Integer(3) * ((Integer(2) * (Symbol('b'))**(Integer(2)) * (Symbol('n'))**(Integer(2)) * (x)**(Integer(3)) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**(sympy.S(5)/2)*(a + b*log(c*x**n)),
        variable=x,
        num_steps=1,
        integral=-4*b*n*(d*x)**(sympy.S(7)/2)/(49*d) + 2*(d*x)**(sympy.S(7)/2)*(a + b*log(c*x**n))/(7*d),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**(sympy.S(3)/2)*(a + b*log(c*x**n)),
        variable=x,
        num_steps=1,
        integral=-4*b*n*(d*x)**(sympy.S(5)/2)/(25*d) + 2*(d*x)**(sympy.S(5)/2)*(a + b*log(c*x**n))/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(d*x)*(a + b*log(c*x**n)),
        variable=x,
        num_steps=1,
        integral=-4*b*n*(d*x)**(sympy.S(3)/2)/(9*d) + 2*(d*x)**(sympy.S(3)/2)*(a + b*log(c*x**n))/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))/sqrt(d*x),
        variable=x,
        num_steps=1,
        integral=-4*b*n*sqrt(d*x)/d + 2*sqrt(d*x)*(a + b*log(c*x**n))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))/(d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=1,
        integral=-4*b*n/(d*sqrt(d*x)) - (2*a + 2*b*log(c*x**n))/(d*sqrt(d*x)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))/(d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=1,
        integral=-4*b*n/(9*d*(d*x)**(sympy.S(3)/2)) - (2*a + 2*b*log(c*x**n))/(3*d*(d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**(sympy.S(5)/2)*(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=2,
        integral=16*b**2*n**2*(d*x)**(sympy.S(7)/2)/(343*d) - 8*b*n*(d*x)**(sympy.S(7)/2)*(a + b*log(c*x**n))/(49*d) + 2*(d*x)**(sympy.S(7)/2)*(a + b*log(c*x**n))**2/(7*d),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**(sympy.S(3)/2)*(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=2,
        integral=16*b**2*n**2*(d*x)**(sympy.S(5)/2)/(125*d) - 8*b*n*(d*x)**(sympy.S(5)/2)*(a + b*log(c*x**n))/(25*d) + 2*(d*x)**(sympy.S(5)/2)*(a + b*log(c*x**n))**2/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(d*x)*(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=2,
        integral=16*b**2*n**2*(d*x)**(sympy.S(3)/2)/(27*d) - 8*b*n*(d*x)**(sympy.S(3)/2)*(a + b*log(c*x**n))/(9*d) + 2*(d*x)**(sympy.S(3)/2)*(a + b*log(c*x**n))**2/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**2/sqrt(d*x),
        variable=x,
        num_steps=2,
        integral=16*b**2*n**2*sqrt(d*x)/d - 8*b*n*sqrt(d*x)*(a + b*log(c*x**n))/d + 2*sqrt(d*x)*(a + b*log(c*x**n))**2/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**2/(d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=-16*b**2*n**2/(d*sqrt(d*x)) - 8*b*n*(a + b*log(c*x**n))/(d*sqrt(d*x)) - 2*(a + b*log(c*x**n))**2/(d*sqrt(d*x)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**2/(d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=-16*b**2*n**2/(27*d*(d*x)**(sympy.S(3)/2)) - 8*b*n*(a + b*log(c*x**n))/(9*d*(d*x)**(sympy.S(3)/2)) - 2*(a + b*log(c*x**n))**2/(3*d*(d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**(sympy.S(5)/2)/(a + b*log(c*x**n)),
        variable=x,
        num_steps=2,
        integral=((((Symbol('d') * x))**((Integer(7) * (Integer(2))**(Integer(-1)))) * sympy.Function('ExpIntegralEi')(((Integer(7) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('b') * Symbol('d') * (sympy.E)**(((Integer(7) * Symbol('a')) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1)))) * Symbol('n') * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(7) * ((Integer(2) * Symbol('n')))**(Integer(-1))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**(sympy.S(3)/2)/(a + b*log(c*x**n)),
        variable=x,
        num_steps=2,
        integral=((((Symbol('d') * x))**((Integer(5) * (Integer(2))**(Integer(-1)))) * sympy.Function('ExpIntegralEi')(((Integer(5) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('b') * Symbol('d') * (sympy.E)**(((Integer(5) * Symbol('a')) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1)))) * Symbol('n') * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(5) * ((Integer(2) * Symbol('n')))**(Integer(-1))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(d*x)/(a + b*log(c*x**n)),
        variable=x,
        num_steps=2,
        integral=((((Symbol('d') * x))**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.Function('ExpIntegralEi')(((Integer(3) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('b') * Symbol('d') * (sympy.E)**(((Integer(3) * Symbol('a')) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1)))) * Symbol('n') * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(3) * ((Integer(2) * Symbol('n')))**(Integer(-1))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(d*x)*(a + b*log(c*x**n))),
        variable=x,
        num_steps=2,
        integral=((sympy.sqrt((Symbol('d') * x)) * sympy.Function('ExpIntegralEi')(((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('b') * Symbol('d') * (sympy.E)**((Symbol('a') * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1)))) * Symbol('n') * ((Symbol('c') * (x)**(Symbol('n'))))**(((Integer(2) * Symbol('n')))**(Integer(-1)))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/((d*x)**(sympy.S(3)/2)*(a + b*log(c*x**n))),
        variable=x,
        num_steps=2,
        integral=(((sympy.E)**((Symbol('a') * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**(((Integer(2) * Symbol('n')))**(Integer(-1))) * sympy.Function('ExpIntegralEi')(((Integer(-1) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('b') * Symbol('d') * Symbol('n') * sympy.sqrt((Symbol('d') * x))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/((d*x)**(sympy.S(5)/2)*(a + b*log(c*x**n))),
        variable=x,
        num_steps=2,
        integral=(((sympy.E)**(((Integer(3) * Symbol('a')) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(3) * ((Integer(2) * Symbol('n')))**(Integer(-1)))) * sympy.Function('ExpIntegralEi')(((Integer(-3) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('b') * Symbol('d') * Symbol('n') * ((Symbol('d') * x))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**(sympy.S(5)/2)/(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=3,
        integral=(((Integer(7) * ((Symbol('d') * x))**((Integer(7) * (Integer(2))**(Integer(-1)))) * sympy.Function('ExpIntegralEi')(((Integer(7) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Integer(2) * (Symbol('b'))**(Integer(2)) * Symbol('d') * (sympy.E)**(((Integer(7) * Symbol('a')) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1)))) * (Symbol('n'))**(Integer(2)) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(7) * ((Integer(2) * Symbol('n')))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * (((Symbol('d') * x))**((Integer(7) * (Integer(2))**(Integer(-1)))) * ((Symbol('b') * Symbol('d') * Symbol('n') * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**(sympy.S(3)/2)/(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=3,
        integral=(((Integer(5) * ((Symbol('d') * x))**((Integer(5) * (Integer(2))**(Integer(-1)))) * sympy.Function('ExpIntegralEi')(((Integer(5) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Integer(2) * (Symbol('b'))**(Integer(2)) * Symbol('d') * (sympy.E)**(((Integer(5) * Symbol('a')) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1)))) * (Symbol('n'))**(Integer(2)) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(5) * ((Integer(2) * Symbol('n')))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * (((Symbol('d') * x))**((Integer(5) * (Integer(2))**(Integer(-1)))) * ((Symbol('b') * Symbol('d') * Symbol('n') * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(d*x)/(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=3,
        integral=(((Integer(3) * ((Symbol('d') * x))**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.Function('ExpIntegralEi')(((Integer(3) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Integer(2) * (Symbol('b'))**(Integer(2)) * Symbol('d') * (sympy.E)**(((Integer(3) * Symbol('a')) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1)))) * (Symbol('n'))**(Integer(2)) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(3) * ((Integer(2) * Symbol('n')))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * (((Symbol('d') * x))**((Integer(3) * (Integer(2))**(Integer(-1)))) * ((Symbol('b') * Symbol('d') * Symbol('n') * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(d*x)*(a + b*log(c*x**n))**2),
        variable=x,
        num_steps=3,
        integral=(((sympy.sqrt((Symbol('d') * x)) * sympy.Function('ExpIntegralEi')(((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Integer(2) * (Symbol('b'))**(Integer(2)) * Symbol('d') * (sympy.E)**((Symbol('a') * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1)))) * (Symbol('n'))**(Integer(2)) * ((Symbol('c') * (x)**(Symbol('n'))))**(((Integer(2) * Symbol('n')))**(Integer(-1)))))**(Integer(-1))) + (Integer(-1) * (sympy.sqrt((Symbol('d') * x)) * ((Symbol('b') * Symbol('d') * Symbol('n') * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=1/((d*x)**(sympy.S(3)/2)*(a + b*log(c*x**n))**2),
        variable=x,
        num_steps=3,
        integral=(((Integer(-1) * ((sympy.E)**((Symbol('a') * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**(((Integer(2) * Symbol('n')))**(Integer(-1))) * sympy.Function('ExpIntegralEi')(((Integer(-1) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1)))))) * ((Integer(2) * (Symbol('b'))**(Integer(2)) * Symbol('d') * (Symbol('n'))**(Integer(2)) * sympy.sqrt((Symbol('d') * x))))**(Integer(-1))) + (Integer(-1) * ((Symbol('b') * Symbol('d') * Symbol('n') * sympy.sqrt((Symbol('d') * x)) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=1/((d*x)**(sympy.S(5)/2)*(a + b*log(c*x**n))**2),
        variable=x,
        num_steps=3,
        integral=(((Integer(-3) * (sympy.E)**(((Integer(3) * Symbol('a')) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(3) * ((Integer(2) * Symbol('n')))**(Integer(-1)))) * sympy.Function('ExpIntegralEi')(((Integer(-3) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Integer(2) * Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Integer(2) * (Symbol('b'))**(Integer(2)) * Symbol('d') * (Symbol('n'))**(Integer(2)) * ((Symbol('d') * x))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Symbol('b') * Symbol('d') * Symbol('n') * ((Symbol('d') * x))**((Integer(3) * (Integer(2))**(Integer(-1)))) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*log(c*x**n)),
        variable=x,
        num_steps=4,
        integral=((((Integer(-1) * (Integer(2))**(Integer(-1))) * sympy.sqrt(Symbol('b')) * sympy.sqrt(Symbol('n')) * sympy.sqrt(sympy.pi) * x * sympy.Function('Erfi')((sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((sympy.sqrt(Symbol('b')) * sympy.sqrt(Symbol('n'))))**(Integer(-1))))) * (((sympy.E)**((Symbol('a') * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1)))))**(Integer(-1))) + (x * sympy.sqrt((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))),
    ),
    RubiTestSuiteCase(
        integrand=x**3*sqrt(log(a*x**n)),
        variable=x,
        num_steps=4,
        integral=((((Integer(-1) * (Integer(16))**(Integer(-1))) * sympy.sqrt(Symbol('n')) * sympy.sqrt(sympy.pi) * (x)**(Integer(4)) * sympy.Function('Erfi')(((Integer(2) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * (((Symbol('a') * (x)**(Symbol('n'))))**((Integer(4) * (Symbol('n'))**(Integer(-1)))))**(Integer(-1))) + ((Integer(4))**(Integer(-1)) * (x)**(Integer(4)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))))),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sqrt(log(a*x**n)),
        variable=x,
        num_steps=4,
        integral=((((Integer(-1) * (Integer(6))**(Integer(-1))) * sympy.sqrt(Symbol('n')) * sympy.sqrt((sympy.pi * (Integer(3))**(Integer(-1)))) * (x)**(Integer(3)) * sympy.Function('Erfi')(((sympy.sqrt(Integer(3)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * (((Symbol('a') * (x)**(Symbol('n'))))**((Integer(3) * (Symbol('n'))**(Integer(-1)))))**(Integer(-1))) + ((Integer(3))**(Integer(-1)) * (x)**(Integer(3)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))))),
    ),
    RubiTestSuiteCase(
        integrand=x*sqrt(log(a*x**n)),
        variable=x,
        num_steps=4,
        integral=((((Integer(-1) * (Integer(4))**(Integer(-1))) * sympy.sqrt(Symbol('n')) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * (x)**(Integer(2)) * sympy.Function('Erfi')(((sympy.sqrt(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * (((Symbol('a') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1)))))**(Integer(-1))) + ((Integer(2))**(Integer(-1)) * (x)**(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(log(a*x**n)),
        variable=x,
        num_steps=4,
        integral=((((Integer(-1) * (Integer(2))**(Integer(-1))) * sympy.sqrt(Symbol('n')) * sympy.sqrt(sympy.pi) * x * sympy.Function('Erfi')((sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * (((Symbol('a') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))))**(Integer(-1))) + (x * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(log(a*x**n))/x,
        variable=x,
        num_steps=2,
        integral=2*log(a*x**n)**(sympy.S(3)/2)/(3*n),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(log(a*x**n))/x**2,
        variable=x,
        num_steps=4,
        integral=(((sympy.sqrt(Symbol('n')) * sympy.sqrt(sympy.pi) * ((Symbol('a') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * sympy.Function('Erf')((sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((Integer(2) * x))**(Integer(-1))) + (Integer(-1) * (sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))) * (x)**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(log(a*x**n))/x**3,
        variable=x,
        num_steps=4,
        integral=(((sympy.sqrt(Symbol('n')) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * ((Symbol('a') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1)))) * sympy.Function('Erf')(((sympy.sqrt(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((Integer(4) * (x)**(Integer(2))))**(Integer(-1))) + (Integer(-1) * (sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))) * ((Integer(2) * (x)**(Integer(2))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**3*log(a*x**n)**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=((((Integer(3) * (Integer(128))**(Integer(-1))) * (Symbol('n'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sqrt(sympy.pi) * (x)**(Integer(4)) * sympy.Function('Erfi')(((Integer(2) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * (((Symbol('a') * (x)**(Symbol('n'))))**((Integer(4) * (Symbol('n'))**(Integer(-1)))))**(Integer(-1))) + (Integer(-1) * ((Integer(3) * (Integer(32))**(Integer(-1))) * Symbol('n') * (x)**(Integer(4)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))))) + ((Integer(4))**(Integer(-1)) * (x)**(Integer(4)) * (sympy.log((Symbol('a') * (x)**(Symbol('n')))))**((Integer(3) * (Integer(2))**(Integer(-1)))))),
    ),
    RubiTestSuiteCase(
        integrand=x**2*log(a*x**n)**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=((((Integer(12))**(Integer(-1)) * (Symbol('n'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sqrt((sympy.pi * (Integer(3))**(Integer(-1)))) * (x)**(Integer(3)) * sympy.Function('Erfi')(((sympy.sqrt(Integer(3)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * (((Symbol('a') * (x)**(Symbol('n'))))**((Integer(3) * (Symbol('n'))**(Integer(-1)))))**(Integer(-1))) + (Integer(-1) * ((Integer(6))**(Integer(-1)) * Symbol('n') * (x)**(Integer(3)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))))) + ((Integer(3))**(Integer(-1)) * (x)**(Integer(3)) * (sympy.log((Symbol('a') * (x)**(Symbol('n')))))**((Integer(3) * (Integer(2))**(Integer(-1)))))),
    ),
    RubiTestSuiteCase(
        integrand=x*log(a*x**n)**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=((((Integer(3) * (Integer(16))**(Integer(-1))) * (Symbol('n'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * (x)**(Integer(2)) * sympy.Function('Erfi')(((sympy.sqrt(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * (((Symbol('a') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1)))))**(Integer(-1))) + (Integer(-1) * ((Integer(3) * (Integer(8))**(Integer(-1))) * Symbol('n') * (x)**(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))))) + ((Integer(2))**(Integer(-1)) * (x)**(Integer(2)) * (sympy.log((Symbol('a') * (x)**(Symbol('n')))))**((Integer(3) * (Integer(2))**(Integer(-1)))))),
    ),
    RubiTestSuiteCase(
        integrand=log(a*x**n)**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=((((Integer(3) * (Integer(4))**(Integer(-1))) * (Symbol('n'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sqrt(sympy.pi) * x * sympy.Function('Erfi')((sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * (((Symbol('a') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))))**(Integer(-1))) + (Integer(-1) * ((Integer(3) * (Integer(2))**(Integer(-1))) * Symbol('n') * x * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))))) + (x * (sympy.log((Symbol('a') * (x)**(Symbol('n')))))**((Integer(3) * (Integer(2))**(Integer(-1)))))),
    ),
    RubiTestSuiteCase(
        integrand=log(a*x**n)**(sympy.S(3)/2)/x,
        variable=x,
        num_steps=2,
        integral=2*log(a*x**n)**(sympy.S(5)/2)/(5*n),
    ),
    RubiTestSuiteCase(
        integrand=log(a*x**n)**(sympy.S(3)/2)/x**2,
        variable=x,
        num_steps=5,
        integral=(((Integer(3) * (Symbol('n'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sqrt(sympy.pi) * ((Symbol('a') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * sympy.Function('Erf')((sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((Integer(4) * x))**(Integer(-1))) + (Integer(-1) * ((Integer(3) * Symbol('n') * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * ((Integer(2) * x))**(Integer(-1)))) + (Integer(-1) * ((sympy.log((Symbol('a') * (x)**(Symbol('n')))))**((Integer(3) * (Integer(2))**(Integer(-1)))) * (x)**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=log(a*x**n)**(sympy.S(3)/2)/x**3,
        variable=x,
        num_steps=5,
        integral=(((Integer(3) * (Symbol('n'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * ((Symbol('a') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1)))) * sympy.Function('Erf')(((sympy.sqrt(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((Integer(16) * (x)**(Integer(2))))**(Integer(-1))) + (Integer(-1) * ((Integer(3) * Symbol('n') * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * ((Integer(8) * (x)**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * ((sympy.log((Symbol('a') * (x)**(Symbol('n')))))**((Integer(3) * (Integer(2))**(Integer(-1)))) * ((Integer(2) * (x)**(Integer(2))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**3/sqrt(log(a*x**n)),
        variable=x,
        num_steps=3,
        integral=((sympy.sqrt(sympy.pi) * (x)**(Integer(4)) * sympy.Function('Erfi')(((Integer(2) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((Integer(2) * sympy.sqrt(Symbol('n')) * ((Symbol('a') * (x)**(Symbol('n'))))**((Integer(4) * (Symbol('n'))**(Integer(-1))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x**2/sqrt(log(a*x**n)),
        variable=x,
        num_steps=3,
        integral=((sympy.sqrt((sympy.pi * (Integer(3))**(Integer(-1)))) * (x)**(Integer(3)) * sympy.Function('Erfi')(((sympy.sqrt(Integer(3)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((sympy.sqrt(Symbol('n')) * ((Symbol('a') * (x)**(Symbol('n'))))**((Integer(3) * (Symbol('n'))**(Integer(-1))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(log(a*x**n)),
        variable=x,
        num_steps=3,
        integral=((sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * (x)**(Integer(2)) * sympy.Function('Erfi')(((sympy.sqrt(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((sympy.sqrt(Symbol('n')) * ((Symbol('a') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(log(a*x**n)),
        variable=x,
        num_steps=3,
        integral=((sympy.sqrt(sympy.pi) * x * sympy.Function('Erfi')((sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((sympy.sqrt(Symbol('n')) * ((Symbol('a') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1)))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(log(a*x**n))),
        variable=x,
        num_steps=2,
        integral=2*sqrt(log(a*x**n))/n,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*sqrt(log(a*x**n))),
        variable=x,
        num_steps=3,
        integral=((sympy.sqrt(sympy.pi) * ((Symbol('a') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * sympy.Function('Erf')((sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((sympy.sqrt(Symbol('n')) * x))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3*sqrt(log(a*x**n))),
        variable=x,
        num_steps=3,
        integral=((sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * ((Symbol('a') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1)))) * sympy.Function('Erf')(((sympy.sqrt(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((sympy.sqrt(Symbol('n')) * (x)**(Integer(2))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x**3/log(a*x**n)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=(((Integer(4) * sympy.sqrt(sympy.pi) * (x)**(Integer(4)) * sympy.Function('Erfi')(((Integer(2) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * (((Symbol('n'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * ((Symbol('a') * (x)**(Symbol('n'))))**((Integer(4) * (Symbol('n'))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * (x)**(Integer(4))) * ((Symbol('n') * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**2/log(a*x**n)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=(((Integer(2) * sympy.sqrt((Integer(3) * sympy.pi)) * (x)**(Integer(3)) * sympy.Function('Erfi')(((sympy.sqrt(Integer(3)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((((Symbol('a') * (x)**(Symbol('n'))))**((Integer(3) * (Symbol('n'))**(Integer(-1)))) * (Symbol('n'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * (x)**(Integer(3))) * ((Symbol('n') * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x/log(a*x**n)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=(((Integer(2) * sympy.sqrt((Integer(2) * sympy.pi)) * (x)**(Integer(2)) * sympy.Function('Erfi')(((sympy.sqrt(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((((Symbol('a') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1)))) * (Symbol('n'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * (x)**(Integer(2))) * ((Symbol('n') * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=log(a*x**n)**(sympy.S(-3)/2),
        variable=x,
        num_steps=4,
        integral=(((Integer(2) * sympy.sqrt(sympy.pi) * x * sympy.Function('Erfi')((sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * (((Symbol('n'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * ((Symbol('a') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1)))))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * x) * ((Symbol('n') * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*log(a*x**n)**(sympy.S(3)/2)),
        variable=x,
        num_steps=2,
        integral=-2/(n*sqrt(log(a*x**n))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*log(a*x**n)**(sympy.S(3)/2)),
        variable=x,
        num_steps=4,
        integral=((Integer(-1) * ((Integer(2) * sympy.sqrt(sympy.pi) * ((Symbol('a') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * sympy.Function('Erf')((sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * (((Symbol('n'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * x))**(Integer(-1)))) + (Integer(-1) * (Integer(2) * ((Symbol('n') * x * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3*log(a*x**n)**(sympy.S(3)/2)),
        variable=x,
        num_steps=4,
        integral=((Integer(-1) * ((Integer(2) * sympy.sqrt((Integer(2) * sympy.pi)) * ((Symbol('a') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1)))) * sympy.Function('Erf')(((sympy.sqrt(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * (((Symbol('n'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * (x)**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * (Integer(2) * ((Symbol('n') * (x)**(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**3/log(a*x**n)**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=(((Integer(32) * sympy.sqrt(sympy.pi) * (x)**(Integer(4)) * sympy.Function('Erfi')(((Integer(2) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((((Symbol('a') * (x)**(Symbol('n'))))**((Integer(4) * (Symbol('n'))**(Integer(-1)))) * (Integer(3) * (Symbol('n'))**((Integer(5) * (Integer(2))**(Integer(-1)))))))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * (x)**(Integer(4))) * ((Integer(3) * Symbol('n') * (sympy.log((Symbol('a') * (x)**(Symbol('n')))))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((Integer(16) * (x)**(Integer(4))) * ((Integer(3) * (Symbol('n'))**(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**2/log(a*x**n)**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=(((Integer(4) * sympy.sqrt((Integer(3) * sympy.pi)) * (x)**(Integer(3)) * sympy.Function('Erfi')(((sympy.sqrt(Integer(3)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((((Symbol('a') * (x)**(Symbol('n'))))**((Integer(3) * (Symbol('n'))**(Integer(-1)))) * (Symbol('n'))**((Integer(5) * (Integer(2))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * (x)**(Integer(3))) * ((Integer(3) * Symbol('n') * (sympy.log((Symbol('a') * (x)**(Symbol('n')))))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((Integer(4) * (x)**(Integer(3))) * (((Symbol('n'))**(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x/log(a*x**n)**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=(((Integer(8) * sympy.sqrt((Integer(2) * sympy.pi)) * (x)**(Integer(2)) * sympy.Function('Erfi')(((sympy.sqrt(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((((Symbol('a') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1)))) * (Integer(3) * (Symbol('n'))**((Integer(5) * (Integer(2))**(Integer(-1)))))))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * (x)**(Integer(2))) * ((Integer(3) * Symbol('n') * (sympy.log((Symbol('a') * (x)**(Symbol('n')))))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((Integer(8) * (x)**(Integer(2))) * ((Integer(3) * (Symbol('n'))**(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=log(a*x**n)**(sympy.S(-5)/2),
        variable=x,
        num_steps=5,
        integral=(((Integer(4) * sympy.sqrt(sympy.pi) * x * sympy.Function('Erfi')((sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((((Symbol('a') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * (Integer(3) * (Symbol('n'))**((Integer(5) * (Integer(2))**(Integer(-1)))))))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * x) * ((Integer(3) * Symbol('n') * (sympy.log((Symbol('a') * (x)**(Symbol('n')))))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((Integer(4) * x) * ((Integer(3) * (Symbol('n'))**(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*log(a*x**n)**(sympy.S(5)/2)),
        variable=x,
        num_steps=2,
        integral=-2/(3*n*log(a*x**n)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*log(a*x**n)**(sympy.S(5)/2)),
        variable=x,
        num_steps=5,
        integral=(((Integer(4) * sympy.sqrt(sympy.pi) * ((Symbol('a') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * sympy.Function('Erf')((sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n'))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((Integer(3) * (Symbol('n'))**((Integer(5) * (Integer(2))**(Integer(-1)))) * x))**(Integer(-1))) + (Integer(-1) * (Integer(2) * ((Integer(3) * Symbol('n') * x * (sympy.log((Symbol('a') * (x)**(Symbol('n')))))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(4) * ((Integer(3) * (Symbol('n'))**(Integer(2)) * x * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3*log(a*x**n)**(sympy.S(5)/2)),
        variable=x,
        num_steps=5,
        integral=(((Integer(8) * sympy.sqrt((Integer(2) * sympy.pi)) * ((Symbol('a') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1)))) * sympy.Function('Erf')(((sympy.sqrt(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((Integer(3) * (Symbol('n'))**((Integer(5) * (Integer(2))**(Integer(-1)))) * (x)**(Integer(2))))**(Integer(-1))) + (Integer(-1) * (Integer(2) * ((Integer(3) * Symbol('n') * (x)**(Integer(2)) * (sympy.log((Symbol('a') * (x)**(Symbol('n')))))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(8) * ((Integer(3) * (Symbol('n'))**(Integer(2)) * (x)**(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**m*(a + a*(m + 1)*log(c*x**n)/n),
        variable=x,
        num_steps=1,
        integral=a*(d*x)**(m + 1)*log(c*x**n)/(d*n),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**m*(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=3,
        integral=-6*b**3*n**3*(d*x)**(m + 1)/(d*(m + 1)**4) + 6*b**2*n**2*(d*x)**(m + 1)*(a + b*log(c*x**n))/(d*(m + 1)**3) - 3*b*n*(d*x)**(m + 1)*(a + b*log(c*x**n))**2/(d*(m + 1)**2) + (d*x)**(m + 1)*(a + b*log(c*x**n))**3/(d*(m + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**m*(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=2,
        integral=2*b**2*n**2*(d*x)**(m + 1)/(d*(m + 1)**3) - 2*b*n*(d*x)**(m + 1)*(a + b*log(c*x**n))/(d*(m + 1)**2) + (d*x)**(m + 1)*(a + b*log(c*x**n))**2/(d*(m + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**m*(a + b*log(c*x**n)),
        variable=x,
        num_steps=1,
        integral=-b*n*(d*x)**(m + 1)/(d*(m + 1)**2) + (d*x)**(m + 1)*(a + b*log(c*x**n))/(d*(m + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**m/(a + b*log(c*x**n)),
        variable=x,
        num_steps=2,
        integral=((((Symbol('d') * x))**((Integer(1) + Symbol('m'))) * sympy.Function('ExpIntegralEi')((((Integer(1) + Symbol('m')) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * (((sympy.E)**(((Symbol('a') * (Integer(1) + Symbol('m'))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (Symbol('b') * Symbol('d') * Symbol('n'))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**m/(a + b*log(c*x**n))**2,
        variable=x,
        num_steps=3,
        integral=((((Integer(1) + Symbol('m')) * ((Symbol('d') * x))**((Integer(1) + Symbol('m'))) * sympy.Function('ExpIntegralEi')((((Integer(1) + Symbol('m')) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * (((sympy.E)**(((Symbol('a') * (Integer(1) + Symbol('m'))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * ((Symbol('b'))**(Integer(2)) * Symbol('d') * (Symbol('n'))**(Integer(2)))))**(Integer(-1))) + (Integer(-1) * (((Symbol('d') * x))**((Integer(1) + Symbol('m'))) * ((Symbol('b') * Symbol('d') * Symbol('n') * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**m/(a + b*log(c*x**n))**3,
        variable=x,
        num_steps=4,
        integral=(((((Integer(1) + Symbol('m')))**(Integer(2)) * ((Symbol('d') * x))**((Integer(1) + Symbol('m'))) * sympy.Function('ExpIntegralEi')((((Integer(1) + Symbol('m')) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * (((sympy.E)**(((Symbol('a') * (Integer(1) + Symbol('m'))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (Integer(2) * (Symbol('b'))**(Integer(3)) * Symbol('d') * (Symbol('n'))**(Integer(3)))))**(Integer(-1))) + (Integer(-1) * (((Symbol('d') * x))**((Integer(1) + Symbol('m'))) * ((Integer(2) * Symbol('b') * Symbol('d') * Symbol('n') * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * (((Integer(1) + Symbol('m')) * ((Symbol('d') * x))**((Integer(1) + Symbol('m')))) * ((Integer(2) * (Symbol('b'))**(Integer(2)) * Symbol('d') * (Symbol('n'))**(Integer(2)) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**(n - 1)*log(c*x**n)**3,
        variable=x,
        num_steps=3,
        integral=(d*x)**n*log(c*x**n)**3/(d*n) - 3*(d*x)**n*log(c*x**n)**2/(d*n) + 6*(d*x)**n*log(c*x**n)/(d*n) - 6*(d*x)**n/(d*n),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**(n - 1)*log(c*x**n)**2,
        variable=x,
        num_steps=2,
        integral=(d*x)**n*log(c*x**n)**2/(d*n) - 2*(d*x)**n*log(c*x**n)/(d*n) + 2*(d*x)**n/(d*n),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**(n - 1)*log(c*x**n),
        variable=x,
        num_steps=1,
        integral=(d*x)**n*log(c*x**n)/(d*n) - (d*x)**n/(d*n),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**(n - 1)/log(c*x**n),
        variable=x,
        num_steps=3,
        integral=(((x)**((Integer(1) + (Integer(-1) * Symbol('n')))) * ((Symbol('d') * x))**((Integer(-1) + Symbol('n'))) * sympy.Function('LogIntegral')((Symbol('c') * (x)**(Symbol('n'))))) * ((Symbol('c') * Symbol('n')))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**(n - 1)/log(c*x**n)**2,
        variable=x,
        num_steps=4,
        integral=((Integer(-1) * (((Symbol('d') * x))**(Symbol('n')) * ((Symbol('d') * Symbol('n') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))**(Integer(-1)))) + (((x)**((Integer(1) + (Integer(-1) * Symbol('n')))) * ((Symbol('d') * x))**((Integer(-1) + Symbol('n'))) * sympy.Function('LogIntegral')((Symbol('c') * (x)**(Symbol('n'))))) * ((Symbol('c') * Symbol('n')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**(n - 1)/log(c*x**n)**3,
        variable=x,
        num_steps=5,
        integral=((Integer(-1) * (((Symbol('d') * x))**(Symbol('n')) * ((Integer(2) * Symbol('d') * Symbol('n') * (sympy.log((Symbol('c') * (x)**(Symbol('n')))))**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * (((Symbol('d') * x))**(Symbol('n')) * ((Integer(2) * Symbol('d') * Symbol('n') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))**(Integer(-1)))) + (((x)**((Integer(1) + (Integer(-1) * Symbol('n')))) * ((Symbol('d') * x))**((Integer(-1) + Symbol('n'))) * sympy.Function('LogIntegral')((Symbol('c') * (x)**(Symbol('n'))))) * ((Integer(2) * Symbol('c') * Symbol('n')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x**m*log(a*x**n)**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=(((Integer(3) * (Symbol('n'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sqrt(sympy.pi) * (x)**((Integer(1) + Symbol('m'))) * sympy.Function('Erfi')(((sympy.sqrt((Integer(1) + Symbol('m'))) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((((Symbol('a') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (Integer(4) * ((Integer(1) + Symbol('m')))**((Integer(5) * (Integer(2))**(Integer(-1)))))))**(Integer(-1))) + (Integer(-1) * ((Integer(3) * Symbol('n') * (x)**((Integer(1) + Symbol('m'))) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * ((Integer(2) * ((Integer(1) + Symbol('m')))**(Integer(2))))**(Integer(-1)))) + (((x)**((Integer(1) + Symbol('m'))) * (sympy.log((Symbol('a') * (x)**(Symbol('n')))))**((Integer(3) * (Integer(2))**(Integer(-1))))) * ((Integer(1) + Symbol('m')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x**m*sqrt(log(a*x**n)),
        variable=x,
        num_steps=4,
        integral=((Integer(-1) * ((sympy.sqrt(Symbol('n')) * sympy.sqrt(sympy.pi) * (x)**((Integer(1) + Symbol('m'))) * sympy.Function('Erfi')(((sympy.sqrt((Integer(1) + Symbol('m'))) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((((Symbol('a') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (Integer(2) * ((Integer(1) + Symbol('m')))**((Integer(3) * (Integer(2))**(Integer(-1)))))))**(Integer(-1)))) + (((x)**((Integer(1) + Symbol('m'))) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * ((Integer(1) + Symbol('m')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x**m/sqrt(log(a*x**n)),
        variable=x,
        num_steps=3,
        integral=((sympy.sqrt(sympy.pi) * (x)**((Integer(1) + Symbol('m'))) * sympy.Function('Erfi')(((sympy.sqrt((Integer(1) + Symbol('m'))) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((((Symbol('a') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (sympy.sqrt((Integer(1) + Symbol('m'))) * sympy.sqrt(Symbol('n')))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x**m/log(a*x**n)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=(((Integer(2) * sympy.sqrt((Integer(1) + Symbol('m'))) * sympy.sqrt(sympy.pi) * (x)**((Integer(1) + Symbol('m'))) * sympy.Function('Erfi')(((sympy.sqrt((Integer(1) + Symbol('m'))) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((((Symbol('a') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (Symbol('n'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * (x)**((Integer(1) + Symbol('m')))) * ((Symbol('n') * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**m/log(a*x**n)**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=(((Integer(4) * ((Integer(1) + Symbol('m')))**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sqrt(sympy.pi) * (x)**((Integer(1) + Symbol('m'))) * sympy.Function('Erfi')(((sympy.sqrt((Integer(1) + Symbol('m'))) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))) * (sympy.sqrt(Symbol('n')))**(Integer(-1))))) * ((((Symbol('a') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (Integer(3) * (Symbol('n'))**((Integer(5) * (Integer(2))**(Integer(-1)))))))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * (x)**((Integer(1) + Symbol('m')))) * ((Integer(3) * Symbol('n') * (sympy.log((Symbol('a') * (x)**(Symbol('n')))))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((Integer(4) * (Integer(1) + Symbol('m')) * (x)**((Integer(1) + Symbol('m')))) * ((Integer(3) * (Symbol('n'))**(Integer(2)) * sympy.sqrt(sympy.log((Symbol('a') * (x)**(Symbol('n')))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**m*(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=2,
        integral=((((Symbol('d') * x))**((Integer(1) + Symbol('m'))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * (((Integer(1) + Symbol('m')) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Symbol('p'))) * (((sympy.E)**(((Symbol('a') * (Integer(1) + Symbol('m'))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * ((Integer(-1) * (((Integer(1) + Symbol('m')) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))))**(Symbol('p')) * (Symbol('d') * (Integer(1) + Symbol('m')))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x**2*(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=2,
        integral=(((Integer(3))**((Integer(-1) + (Integer(-1) * Symbol('p')))) * (x)**(Integer(3)) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * ((Integer(3) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Symbol('p'))) * (((sympy.E)**(((Integer(3) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(3) * (Symbol('n'))**(Integer(-1)))) * ((Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))))**(Symbol('p'))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x*(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=2,
        integral=(((Integer(2))**((Integer(-1) + (Integer(-1) * Symbol('p')))) * (x)**(Integer(2)) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * ((Integer(2) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Symbol('p'))) * (((sympy.E)**(((Integer(2) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1)))) * ((Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))))**(Symbol('p'))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=2,
        integral=((x * sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Symbol('p'))) * (((sympy.E)**((Symbol('a') * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * ((Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))))**(Symbol('p'))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**p/x,
        variable=x,
        num_steps=2,
        integral=(a + b*log(c*x**n))**(p + 1)/(b*n*(p + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**p/x**2,
        variable=x,
        num_steps=2,
        integral=(Integer(-1) * (((sympy.E)**((Symbol('a') * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Symbol('p'))) * (((((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))**(Symbol('p')) * x))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**p/x**3,
        variable=x,
        num_steps=2,
        integral=(Integer(-1) * (((Integer(2))**((Integer(-1) + (Integer(-1) * Symbol('p')))) * (sympy.E)**(((Integer(2) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(2) * (Symbol('n'))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), ((Integer(2) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Symbol('p'))) * (((((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))**(Symbol('p')) * (x)**(Integer(2))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x**n))**p/x**4,
        variable=x,
        num_steps=2,
        integral=(Integer(-1) * (((Integer(3))**((Integer(-1) + (Integer(-1) * Symbol('p')))) * (sympy.E)**(((Integer(3) * Symbol('a')) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**((Integer(3) * (Symbol('n'))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), ((Integer(3) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Symbol('p'))) * (((((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))**(Symbol('p')) * (x)**(Integer(3))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**m*(a + b*log(c*x))**p,
        variable=x,
        num_steps=2,
        integral=((((Symbol('c') * x))**((Integer(-1) + (Integer(-1) * Symbol('m')))) * ((Symbol('d') * x))**((Integer(1) + Symbol('m'))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * (((Integer(1) + Symbol('m')) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x))))) * (Symbol('b'))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))))**(Symbol('p'))) * (((sympy.E)**(((Symbol('a') * (Integer(1) + Symbol('m'))) * (Symbol('b'))**(Integer(-1)))) * ((Integer(-1) * (((Integer(1) + Symbol('m')) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x))))) * (Symbol('b'))**(Integer(-1)))))**(Symbol('p')) * (Symbol('d') * (Integer(1) + Symbol('m')))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x**2*(a + b*log(c*x))**p,
        variable=x,
        num_steps=2,
        integral=(((Integer(3))**((Integer(-1) + (Integer(-1) * Symbol('p')))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * ((Integer(3) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x))))) * (Symbol('b'))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))))**(Symbol('p'))) * (((sympy.E)**(((Integer(3) * Symbol('a')) * (Symbol('b'))**(Integer(-1)))) * ((Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))) * (Symbol('b'))**(Integer(-1)))))**(Symbol('p')) * (Symbol('c'))**(Integer(3))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x*(a + b*log(c*x))**p,
        variable=x,
        num_steps=2,
        integral=(((Integer(2))**((Integer(-1) + (Integer(-1) * Symbol('p')))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * ((Integer(2) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x))))) * (Symbol('b'))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))))**(Symbol('p'))) * (((sympy.E)**(((Integer(2) * Symbol('a')) * (Symbol('b'))**(Integer(-1)))) * ((Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))) * (Symbol('b'))**(Integer(-1)))))**(Symbol('p')) * (Symbol('c'))**(Integer(2))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x))**p,
        variable=x,
        num_steps=2,
        integral=((sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))) * (Symbol('b'))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))))**(Symbol('p'))) * (((sympy.E)**((Symbol('a') * (Symbol('b'))**(Integer(-1)))) * ((Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))) * (Symbol('b'))**(Integer(-1)))))**(Symbol('p')) * Symbol('c')))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x))**p/x,
        variable=x,
        num_steps=2,
        integral=(a + b*log(c*x))**(p + 1)/(b*(p + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x))**p/x**2,
        variable=x,
        num_steps=2,
        integral=(((Integer(-1) * Symbol('c')) * (sympy.E)**((Symbol('a') * (Symbol('b'))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))) * (Symbol('b'))**(Integer(-1)))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))))**(Symbol('p'))) * ((((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))) * (Symbol('b'))**(Integer(-1))))**(Symbol('p')))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x))**p/x**3,
        variable=x,
        num_steps=2,
        integral=(((Integer(-1) * (Integer(2))**((Integer(-1) + (Integer(-1) * Symbol('p'))))) * (Symbol('c'))**(Integer(2)) * (sympy.E)**(((Integer(2) * Symbol('a')) * (Symbol('b'))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), ((Integer(2) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x))))) * (Symbol('b'))**(Integer(-1)))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))))**(Symbol('p'))) * ((((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))) * (Symbol('b'))**(Integer(-1))))**(Symbol('p')))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*x))**p/x**4,
        variable=x,
        num_steps=2,
        integral=(((Integer(-1) * (Integer(3))**((Integer(-1) + (Integer(-1) * Symbol('p'))))) * (Symbol('c'))**(Integer(3)) * (sympy.E)**(((Integer(3) * Symbol('a')) * (Symbol('b'))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), ((Integer(3) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x))))) * (Symbol('b'))**(Integer(-1)))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))))**(Symbol('p'))) * ((((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * x)))) * (Symbol('b'))**(Integer(-1))))**(Symbol('p')))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(d*x)**m*(a + b*log(c*sqrt(x)))**p,
        variable=x,
        num_steps=2,
        integral=((((Symbol('d') * x))**((Integer(1) + Symbol('m'))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * ((Integer(2) * (Integer(1) + Symbol('m')) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x)))))) * (Symbol('b'))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x))))))**(Symbol('p'))) * (((Integer(2))**(Symbol('p')) * (sympy.E)**(((Integer(2) * Symbol('a') * (Integer(1) + Symbol('m'))) * (Symbol('b'))**(Integer(-1)))) * ((Symbol('c') * sympy.sqrt(x)))**((Integer(2) * (Integer(1) + Symbol('m')))) * ((Integer(-1) * (((Integer(1) + Symbol('m')) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x)))))) * (Symbol('b'))**(Integer(-1)))))**(Symbol('p')) * (Symbol('d') * (Integer(1) + Symbol('m')))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x**2*(a + b*log(c*sqrt(x)))**p,
        variable=x,
        num_steps=2,
        integral=(((Integer(3))**((Integer(-1) + (Integer(-1) * Symbol('p')))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * ((Integer(6) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x)))))) * (Symbol('b'))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x))))))**(Symbol('p'))) * (((Integer(2))**(Symbol('p')) * (sympy.E)**(((Integer(6) * Symbol('a')) * (Symbol('b'))**(Integer(-1)))) * ((Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x))))) * (Symbol('b'))**(Integer(-1)))))**(Symbol('p')) * (Symbol('c'))**(Integer(6))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x*(a + b*log(c*sqrt(x)))**p,
        variable=x,
        num_steps=2,
        integral=(((Integer(2))**((Integer(-1) + (Integer(-1) * (Integer(2) * Symbol('p'))))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * ((Integer(4) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x)))))) * (Symbol('b'))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x))))))**(Symbol('p'))) * (((sympy.E)**(((Integer(4) * Symbol('a')) * (Symbol('b'))**(Integer(-1)))) * ((Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x))))) * (Symbol('b'))**(Integer(-1)))))**(Symbol('p')) * (Symbol('c'))**(Integer(4))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*sqrt(x)))**p,
        variable=x,
        num_steps=2,
        integral=((sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * ((Integer(2) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x)))))) * (Symbol('b'))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x))))))**(Symbol('p'))) * (((Integer(2))**(Symbol('p')) * (sympy.E)**(((Integer(2) * Symbol('a')) * (Symbol('b'))**(Integer(-1)))) * ((Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x))))) * (Symbol('b'))**(Integer(-1)))))**(Symbol('p')) * (Symbol('c'))**(Integer(2))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*sqrt(x)))**p/x,
        variable=x,
        num_steps=2,
        integral=2*(a + b*log(c*sqrt(x)))**(p + 1)/(b*(p + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*sqrt(x)))**p/x**2,
        variable=x,
        num_steps=2,
        integral=(((Integer(-1) * (Integer(2))**((Integer(-1) * Symbol('p')))) * (Symbol('c'))**(Integer(2)) * (sympy.E)**(((Integer(2) * Symbol('a')) * (Symbol('b'))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), ((Integer(2) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x)))))) * (Symbol('b'))**(Integer(-1)))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x))))))**(Symbol('p'))) * ((((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x))))) * (Symbol('b'))**(Integer(-1))))**(Symbol('p')))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*sqrt(x)))**p/x**3,
        variable=x,
        num_steps=2,
        integral=(((Integer(-1) * (Integer(2))**((Integer(-1) + (Integer(-1) * (Integer(2) * Symbol('p')))))) * (Symbol('c'))**(Integer(4)) * (sympy.E)**(((Integer(4) * Symbol('a')) * (Symbol('b'))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), ((Integer(4) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x)))))) * (Symbol('b'))**(Integer(-1)))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x))))))**(Symbol('p'))) * ((((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x))))) * (Symbol('b'))**(Integer(-1))))**(Symbol('p')))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*log(c*sqrt(x)))**p/x**4,
        variable=x,
        num_steps=2,
        integral=(((Integer(-1) * (Integer(2))**((Integer(-1) * Symbol('p')))) * (Integer(3))**((Integer(-1) + (Integer(-1) * Symbol('p')))) * (Symbol('c'))**(Integer(6)) * (sympy.E)**(((Integer(6) * Symbol('a')) * (Symbol('b'))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), ((Integer(6) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x)))))) * (Symbol('b'))**(Integer(-1)))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x))))))**(Symbol('p'))) * ((((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * sympy.sqrt(x))))) * (Symbol('b'))**(Integer(-1))))**(Symbol('p')))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x**(n - 1)*(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=2,
        integral=((sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * (Symbol('b'))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Symbol('p'))) * (((sympy.E)**((Symbol('a') * (Symbol('b'))**(Integer(-1)))) * ((Integer(-1) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))) * (Symbol('b'))**(Integer(-1)))))**(Symbol('p')) * (Symbol('c') * Symbol('n'))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(d*x**q)**m*(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=3,
        integral=((x * ((Symbol('d') * (x)**(Symbol('q'))))**(Symbol('m')) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * (((Integer(1) + (Symbol('m') * Symbol('q'))) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Symbol('p'))) * (((sympy.E)**(((Symbol('a') + (Symbol('a') * Symbol('m') * Symbol('q'))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**(((Integer(1) + (Symbol('m') * Symbol('q'))) * (Symbol('n'))**(Integer(-1)))) * ((Integer(-1) * (((Integer(1) + (Symbol('m') * Symbol('q'))) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))))**(Symbol('p')) * (Integer(1) + (Symbol('m') * Symbol('q')))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(d1*x**q1)**m1*(d2*x**q2)**m2*(a + b*log(c*x**n))**p,
        variable=x,
        num_steps=4,
        integral=((x * ((Symbol('d1') * (x)**(Symbol('q1'))))**(Symbol('m1')) * ((Symbol('d2') * (x)**(Symbol('q2'))))**(Symbol('m2')) * sympy.Function('Gamma')((Integer(1) + Symbol('p')), (Integer(-1) * (((Integer(1) + (Symbol('m1') * Symbol('q1')) + (Symbol('m2') * Symbol('q2'))) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1))))) * ((Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n')))))))**(Symbol('p'))) * (((sympy.E)**(((Symbol('a') * (Integer(1) + (Symbol('m1') * Symbol('q1')) + (Symbol('m2') * Symbol('q2')))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))) * ((Symbol('c') * (x)**(Symbol('n'))))**(((Integer(1) + (Symbol('m1') * Symbol('q1')) + (Symbol('m2') * Symbol('q2'))) * (Symbol('n'))**(Integer(-1)))) * ((Integer(-1) * (((Integer(1) + (Symbol('m1') * Symbol('q1')) + (Symbol('m2') * Symbol('q2'))) * (Symbol('a') + (Symbol('b') * sympy.log((Symbol('c') * (x)**(Symbol('n'))))))) * ((Symbol('b') * Symbol('n')))**(Integer(-1)))))**(Symbol('p')) * (Integer(1) + (Symbol('m1') * Symbol('q1')) + (Symbol('m2') * Symbol('q2')))))**(Integer(-1))),
    ),
]
