# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 0 Independent test suites/Apostol Problems.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '0 Independent test suites/Apostol Problems.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, a1, b, b1, n, t, z = symbols('a a1 b b1 n t z')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=sqrt(2*x + 1),
        variable=x,
        num_steps=1,
        integral=(2*x + 1)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=x*sqrt(3*x + 1),
        variable=x,
        num_steps=2,
        integral=2*(3*x + 1)**(sympy.S(5)/2)/45 - 2*(3*x + 1)**(sympy.S(3)/2)/27,
    ),
    RubiTestSuiteCase(
        integrand=x**2*sqrt(x + 1),
        variable=x,
        num_steps=2,
        integral=2*(x + 1)**(sympy.S(7)/2)/7 - 4*(x + 1)**(sympy.S(5)/2)/5 + 2*(x + 1)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(2 - 3*x),
        variable=x,
        num_steps=2,
        integral=2*(2 - 3*x)**(sympy.S(3)/2)/27 - 4*sqrt(2 - 3*x)/9,
    ),
    RubiTestSuiteCase(
        integrand=(x + 1)/(x**2 + 2*x + 2)**3,
        variable=x,
        num_steps=1,
        integral=-1/(4*(x**2 + 2*x + 2)**2),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3,
        variable=x,
        num_steps=2,
        integral=cos(x)**3/3 - cos(x),
    ),
    RubiTestSuiteCase(
        integrand=z*(z - 1)**(sympy.S(1)/3),
        variable=z,
        num_steps=2,
        integral=3*(z - 1)**(sympy.S(7)/3)/7 + 3*(z - 1)**(sympy.S(4)/3)/4,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)/sin(x)**3,
        variable=x,
        num_steps=2,
        integral=-csc(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(4 - sin(2*x))*cos(2*x),
        variable=x,
        num_steps=2,
        integral=-(4 - sin(2*x))**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/(cos(x) + 3)**2,
        variable=x,
        num_steps=2,
        integral=1/(cos(x) + 3),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/sqrt(cos(x)**3),
        variable=x,
        num_steps=3,
        integral=2*cos(x)/sqrt(cos(x)**3),
    ),
    RubiTestSuiteCase(
        integrand=sin(sqrt(x + 1))/sqrt(x + 1),
        variable=x,
        num_steps=3,
        integral=-2*cos(sqrt(x + 1)),
    ),
    RubiTestSuiteCase(
        integrand=x**(n - 1)*sin(x**n),
        variable=x,
        num_steps=2,
        integral=-cos(x**n)/n,
    ),
    RubiTestSuiteCase(
        integrand=x**5/sqrt(1 - x**6),
        variable=x,
        num_steps=1,
        integral=-sqrt(1 - x**6)/3,
    ),
    RubiTestSuiteCase(
        integrand=t*(t + 1)**(sympy.S(1)/4),
        variable=t,
        num_steps=2,
        integral=4*(t + 1)**(sympy.S(9)/4)/9 - 4*(t + 1)**(sympy.S(5)/4)/5,
    ),
    RubiTestSuiteCase(
        integrand=(x**2 + 1)**(sympy.S(-3)/2),
        variable=x,
        num_steps=1,
        integral=x/sqrt(x**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=x**2*(8*x**3 + 27)**(sympy.S(2)/3),
        variable=x,
        num_steps=1,
        integral=(8*x**3 + 27)**(sympy.S(5)/3)/40,
    ),
    RubiTestSuiteCase(
        integrand=(sin(x) + cos(x))/(sin(x) - cos(x))**(sympy.S(1)/3),
        variable=x,
        num_steps=1,
        integral=3*(sin(x) - cos(x))**(sympy.S(2)/3)/2,
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(x**2 + (x**2 + 1)**(sympy.S(3)/2) + 1),
        variable=x,
        num_steps=3,
        integral=2*sqrt((x**2 + 1)*(sqrt(x**2 + 1) + 1))/sqrt(x**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=x/(sqrt(x**2 + 1)*sqrt(sqrt(x**2 + 1) + 1)),
        variable=x,
        num_steps=1,
        integral=2*sqrt(sqrt(x**2 + 1) + 1),
    ),
    RubiTestSuiteCase(
        integrand=(x**2 - 2*x + 1)**(sympy.S(1)/5)/(1 - x),
        variable=x,
        num_steps=2,
        integral=-5*(x**2 - 2*x + 1)**(sympy.S(1)/5)/2,
    ),
    RubiTestSuiteCase(
        integrand=x*sin(x),
        variable=x,
        num_steps=2,
        integral=-x*cos(x) + sin(x),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sin(x),
        variable=x,
        num_steps=3,
        integral=-x**2*cos(x) + 2*x*sin(x) + 2*cos(x),
    ),
    RubiTestSuiteCase(
        integrand=x**3*cos(x),
        variable=x,
        num_steps=4,
        integral=x**3*sin(x) + 3*x**2*cos(x) - 6*x*sin(x) - 6*cos(x),
    ),
    RubiTestSuiteCase(
        integrand=x**3*sin(x),
        variable=x,
        num_steps=4,
        integral=-x**3*cos(x) + 3*x**2*sin(x) + 6*x*cos(x) - 6*sin(x),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)*cos(x),
        variable=x,
        num_steps=2,
        integral=sin(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=x*sin(x)*cos(x),
        variable=x,
        num_steps=3,
        integral=x*sin(x)**2/2 - x/4 + sin(x)*cos(x)/4,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2,
        variable=x,
        num_steps=2,
        integral=x/2 - sin(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3,
        variable=x,
        num_steps=2,
        integral=cos(x)**3/3 - cos(x),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**4,
        variable=x,
        num_steps=3,
        integral=3*x/8 - sin(x)**3*cos(x)/4 - 3*sin(x)*cos(x)/8,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**5,
        variable=x,
        num_steps=2,
        integral=-cos(x)**5/5 + 2*cos(x)**3/3 - cos(x),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**6,
        variable=x,
        num_steps=4,
        integral=5*x/16 - sin(x)**5*cos(x)/6 - 5*sin(x)**3*cos(x)/24 - 5*sin(x)*cos(x)/16,
    ),
    RubiTestSuiteCase(
        integrand=x*sin(x)**2,
        variable=x,
        num_steps=2,
        integral=x**2/4 - x*sin(x)*cos(x)/2 + sin(x)**2/4,
    ),
    RubiTestSuiteCase(
        integrand=x*sin(x)**3,
        variable=x,
        num_steps=3,
        integral=-x*sin(x)**2*cos(x)/3 - 2*x*cos(x)/3 + sin(x)**3/9 + 2*sin(x)/3,
    ),
    RubiTestSuiteCase(
        integrand=x**2*sin(x)**2,
        variable=x,
        num_steps=4,
        integral=x**3/6 - x**2*sin(x)*cos(x)/2 + x*sin(x)**2/2 - x/4 + sin(x)*cos(x)/4,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**2,
        variable=x,
        num_steps=2,
        integral=x/2 + sin(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**3,
        variable=x,
        num_steps=2,
        integral=-sin(x)**3/3 + sin(x),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**4,
        variable=x,
        num_steps=3,
        integral=3*x/8 + sin(x)*cos(x)**3/4 + 3*sin(x)*cos(x)/8,
    ),
    RubiTestSuiteCase(
        integrand=(a**2 - x**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=5*a**6*atan(x/sqrt(a**2 - x**2))/16 + 5*a**4*x*sqrt(a**2 - x**2)/16 + 5*a**2*x*(a**2 - x**2)**(sympy.S(3)/2)/24 + x*(a**2 - x**2)**(sympy.S(5)/2)/6,
    ),
    RubiTestSuiteCase(
        integrand=x**5/sqrt(x**2 + 5),
        variable=x,
        num_steps=3,
        integral=(x**2 + 5)**(sympy.S(5)/2)/5 - 10*(x**2 + 5)**(sympy.S(3)/2)/3 + 25*sqrt(x**2 + 5),
    ),
    RubiTestSuiteCase(
        integrand=t**3/sqrt(t**3 + 4),
        variable=t,
        num_steps=2,
        integral=2*t*sqrt(t**3 + 4)/5 - 8*2**(sympy.S(2)/3)*3**(sympy.S(3)/4)*sqrt((t**2 - 2**(sympy.S(2)/3)*t + 2*2**(sympy.S(1)/3))/(t + 2**(sympy.S(2)/3)*(1 + sqrt(3)))**2)*sqrt(sqrt(3) + 2)*(t + 2**(sympy.S(2)/3))*elliptic_f(asin((t + 2**(sympy.S(2)/3)*(1 - sqrt(3)))/(t + 2**(sympy.S(2)/3)*(1 + sqrt(3)))), -7 - 4*sqrt(3))/(15*sqrt((t + 2**(sympy.S(2)/3))/(t + 2**(sympy.S(2)/3)*(1 + sqrt(3)))**2)*sqrt(t**3 + 4)),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**2,
        variable=x,
        num_steps=2,
        integral=-x + tan(x),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**4,
        variable=x,
        num_steps=3,
        integral=x + tan(x)**3/3 - tan(x),
    ),
    RubiTestSuiteCase(
        integrand=cot(x)**2,
        variable=x,
        num_steps=2,
        integral=-x - cot(x),
    ),
    RubiTestSuiteCase(
        integrand=cot(x)**4,
        variable=x,
        num_steps=3,
        integral=x - cot(x)**3/3 + cot(x),
    ),
    RubiTestSuiteCase(
        integrand=(3*x + 2)*sin(5*x),
        variable=x,
        num_steps=2,
        integral=(-3*x/5 + sympy.S(-2)/5)*cos(5*x) + 3*sin(5*x)/25,
    ),
    RubiTestSuiteCase(
        integrand=x*sqrt(x**2 + 1),
        variable=x,
        num_steps=1,
        integral=(x**2 + 1)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=x*(x**2 - 1)**9,
        variable=x,
        num_steps=1,
        integral=(1 - x**2)**10/20,
    ),
    RubiTestSuiteCase(
        integrand=(2*x + 3)/(6*x + 7)**3,
        variable=x,
        num_steps=1,
        integral=-(2*x + 3)**2/(8*(6*x + 7)**2),
    ),
    RubiTestSuiteCase(
        integrand=x**4*(x**5 + 1)**5,
        variable=x,
        num_steps=1,
        integral=(x**5 + 1)**6/30,
    ),
    RubiTestSuiteCase(
        integrand=x**4*(1 - x)**20,
        variable=x,
        num_steps=2,
        integral=-(1 - x)**25/25 + (1 - x)**24/6 - 6*(1 - x)**23/23 + 2*(1 - x)**22/11 - (1 - x)**21/21,
    ),
    RubiTestSuiteCase(
        integrand=sin(1/x)/x**2,
        variable=x,
        num_steps=2,
        integral=cos(1/x),
    ),
    RubiTestSuiteCase(
        integrand=sin((x - 1)**(sympy.S(1)/4)),
        variable=x,
        num_steps=5,
        integral=-4*(x - 1)**(sympy.S(3)/4)*cos((x - 1)**(sympy.S(1)/4)) + 24*(x - 1)**(sympy.S(1)/4)*cos((x - 1)**(sympy.S(1)/4)) + 12*sqrt(x - 1)*sin((x - 1)**(sympy.S(1)/4)) - 24*sin((x - 1)**(sympy.S(1)/4)),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(x**2)*cos(x**2),
        variable=x,
        num_steps=1,
        integral=sin(x**2)**2/4,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(3*cos(x)**2 + 1)*sin(2*x),
        variable=x,
        num_steps=3,
        integral=-2*(4 - 3*sin(x)**2)**(sympy.S(3)/2)/9,
    ),
    RubiTestSuiteCase(
        integrand=1/(3*x + 2),
        variable=x,
        num_steps=1,
        integral=log(3*x + 2)/3,
    ),
    RubiTestSuiteCase(
        integrand=log(x)**2,
        variable=x,
        num_steps=2,
        integral=x*log(x)**2 - 2*x*log(x) + 2*x,
    ),
    RubiTestSuiteCase(
        integrand=x*log(x),
        variable=x,
        num_steps=1,
        integral=x**2*log(x)/2 - x**2/4,
    ),
    RubiTestSuiteCase(
        integrand=x*log(x)**2,
        variable=x,
        num_steps=2,
        integral=x**2*log(x)**2/2 - x**2*log(x)/2 + x**2/4,
    ),
    RubiTestSuiteCase(
        integrand=1/(t + 1),
        variable=t,
        num_steps=1,
        integral=log(t + 1),
    ),
    RubiTestSuiteCase(
        integrand=cot(x),
        variable=x,
        num_steps=1,
        integral=log(sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=x**n*log(a*x),
        variable=x,
        num_steps=1,
        integral=x**(n + 1)*log(a*x)/(n + 1) - x**(n + 1)/(n + 1)**2,
    ),
    RubiTestSuiteCase(
        integrand=x**2*log(x)**2,
        variable=x,
        num_steps=2,
        integral=x**3*log(x)**2/3 - 2*x**3*log(x)/9 + 2*x**3/27,
    ),
    RubiTestSuiteCase(
        integrand=1/(x*log(x)),
        variable=x,
        num_steps=2,
        integral=log(log(x)),
    ),
    RubiTestSuiteCase(
        integrand=log(1 - t)/(1 - t),
        variable=t,
        num_steps=2,
        integral=-log(1 - t)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=log(x)/(x*sqrt(log(x) + 1)),
        variable=x,
        num_steps=3,
        integral=2*(log(x) + 1)**(sympy.S(3)/2)/3 - 2*sqrt(log(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=x**3*log(x)**3,
        variable=x,
        num_steps=3,
        integral=x**4*log(x)**3/4 - 3*x**4*log(x)**2/16 + 3*x**4*log(x)/32 - 3*x**4/128,
    ),
    RubiTestSuiteCase(
        integrand=x**2*exp(x**3),
        variable=x,
        num_steps=1,
        integral=exp(x**3)/3,
    ),
    RubiTestSuiteCase(
        integrand=2**(sqrt(x))/sqrt(x),
        variable=x,
        num_steps=1,
        integral=2**(sqrt(x) + 1)/log(2),
    ),
    RubiTestSuiteCase(
        integrand=exp(2*sin(x))*cos(x),
        variable=x,
        num_steps=2,
        integral=exp(2*sin(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*sin(x),
        variable=x,
        num_steps=1,
        integral=exp(x)*sin(x)/2 - exp(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*cos(x),
        variable=x,
        num_steps=1,
        integral=exp(x)*sin(x)/2 + exp(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(exp(x) + 1),
        variable=x,
        num_steps=4,
        integral=x - log(exp(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=x*exp(x),
        variable=x,
        num_steps=2,
        integral=x*exp(x) - exp(x),
    ),
    RubiTestSuiteCase(
        integrand=x*exp(-x),
        variable=x,
        num_steps=2,
        integral=-x*exp(-x) - exp(-x),
    ),
    RubiTestSuiteCase(
        integrand=x**2*exp(x),
        variable=x,
        num_steps=3,
        integral=x**2*exp(x) - 2*x*exp(x) + 2*exp(x),
    ),
    RubiTestSuiteCase(
        integrand=x**2*exp(-2*x),
        variable=x,
        num_steps=3,
        integral=-x**2*exp(-2*x)/2 - x*exp(-2*x)/2 - exp(-2*x)/4,
    ),
    RubiTestSuiteCase(
        integrand=exp(sqrt(x)),
        variable=x,
        num_steps=3,
        integral=2*sqrt(x)*exp(sqrt(x)) - 2*exp(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=x**3*exp(-x**2),
        variable=x,
        num_steps=2,
        integral=-x**2*exp(-x**2)/2 - exp(-x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=exp(a*x)*cos(b*x),
        variable=x,
        num_steps=1,
        integral=a*exp(a*x)*cos(b*x)/(a**2 + b**2) + b*exp(a*x)*sin(b*x)/(a**2 + b**2),
    ),
    RubiTestSuiteCase(
        integrand=exp(a*x)*sin(b*x),
        variable=x,
        num_steps=1,
        integral=a*exp(a*x)*sin(b*x)/(a**2 + b**2) - b*exp(a*x)*cos(b*x)/(a**2 + b**2),
    ),
    RubiTestSuiteCase(
        integrand=acot(x),
        variable=x,
        num_steps=2,
        integral=x*acot(x) + log(x**2 + 1)/2,
    ),
    RubiTestSuiteCase(
        integrand=asec(x),
        variable=x,
        num_steps=4,
        integral=x*asec(x) - atanh(sqrt(1 - 1/x**2)),
    ),
    RubiTestSuiteCase(
        integrand=acsc(x),
        variable=x,
        num_steps=4,
        integral=x*acsc(x) + atanh(sqrt(1 - 1/x**2)),
    ),
    RubiTestSuiteCase(
        integrand=asin(x)**2,
        variable=x,
        num_steps=3,
        integral=x*asin(x)**2 - 2*x + 2*sqrt(1 - x**2)*asin(x),
    ),
    RubiTestSuiteCase(
        integrand=asin(x)/x**2,
        variable=x,
        num_steps=4,
        integral=-atanh(sqrt(1 - x**2)) - asin(x)/x,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a**2 - x**2),
        variable=x,
        num_steps=2,
        integral=atan(x/sqrt(a**2 - x**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-x**2 - 2*x + 1),
        variable=x,
        num_steps=2,
        integral=asin(sqrt(2)*(x + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=1/(a**2 + x**2),
        variable=x,
        num_steps=1,
        integral=atan(x/a)/a,
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*x**2),
        variable=x,
        num_steps=1,
        integral=atan(sqrt(b)*x/sqrt(a))/(sqrt(a)*sqrt(b)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2 - x + 2),
        variable=x,
        num_steps=2,
        integral=-2*sqrt(7)*atan(sqrt(7)*(1 - 2*x)/7)/7,
    ),
    RubiTestSuiteCase(
        integrand=x*atan(x),
        variable=x,
        num_steps=3,
        integral=x**2*atan(x)/2 - x/2 + atan(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=x**2*acos(x),
        variable=x,
        num_steps=4,
        integral=x**3*acos(x)/3 + (1 - x**2)**(sympy.S(3)/2)/9 - sqrt(1 - x**2)/3,
    ),
    RubiTestSuiteCase(
        integrand=x*atan(x)**2,
        variable=x,
        num_steps=5,
        integral=x**2*atan(x)**2/2 - x*atan(x) + log(x**2 + 1)/2 + atan(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=atan(sqrt(x)),
        variable=x,
        num_steps=4,
        integral=-sqrt(x) + x*atan(sqrt(x)) + atan(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=atan(sqrt(x))/(sqrt(x)*(x + 1)),
        variable=x,
        num_steps=1,
        integral=atan(sqrt(x))**2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(1 - x**2),
        variable=x,
        num_steps=2,
        integral=x*sqrt(1 - x**2)/2 + asin(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=x*exp(atan(x))/(x**2 + 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=1,
        integral=-(1 - x)*exp(atan(x))/(2*sqrt(x**2 + 1)),
    ),
    RubiTestSuiteCase(
        integrand=exp(atan(x))/(x**2 + 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=1,
        integral=(x + 1)*exp(atan(x))/(2*sqrt(x**2 + 1)),
    ),
    RubiTestSuiteCase(
        integrand=x**2/(x**2 + 1)**2,
        variable=x,
        num_steps=2,
        integral=-x/(2*x**2 + 2) + atan(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=exp(x)/(exp(2*x) + 1),
        variable=x,
        num_steps=2,
        integral=atan(exp(x)),
    ),
    RubiTestSuiteCase(
        integrand=exp(-x)*acot(exp(x)),
        variable=x,
        num_steps=5,
        integral=-x + log(exp(2*x) + 1)/2 - exp(-x)*acot(exp(x)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt((a + x)/(a - x)),
        variable=x,
        num_steps=3,
        integral=2*a*atan(sqrt((a + x)/(a - x))) - sqrt((a + x)/(a - x))*(a - x),
    ),
    RubiTestSuiteCase(
        integrand=sqrt((-a + x)*(b - x)),
        variable=x,
        num_steps=4,
        integral=-(a - b)**2*atan((a + b - 2*x)/(2*sqrt(-a*b - x**2 + x*(a + b))))/8 + (-a/4 - b/4 + x/2)*sqrt(-a*b - x**2 + x*(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt((-a + x)*(b - x)),
        variable=x,
        num_steps=3,
        integral=-atan((a + b - 2*x)/(2*sqrt(-a*b - x**2 + x*(a + b)))),
    ),
    RubiTestSuiteCase(
        integrand=(5*x + 3)/(x**2 + 2*x - 3),
        variable=x,
        num_steps=3,
        integral=2*log(1 - x) + 3*log(x + 3),
    ),
    RubiTestSuiteCase(
        integrand=(2*x + 5)/(x**2 + 2*x - 3),
        variable=x,
        num_steps=3,
        integral=7*log(1 - x)/4 + log(x + 3)/4,
    ),
    RubiTestSuiteCase(
        integrand=(x**3 + 3*x)/(x**2 - 2*x - 3),
        variable=x,
        num_steps=6,
        integral=x**2/2 + 2*x + 9*log(3 - x) + log(x + 1),
    ),
    RubiTestSuiteCase(
        integrand=(2*x**2 + 5*x - 1)/(x**3 + x**2 - 2*x),
        variable=x,
        num_steps=3,
        integral=log(x)/2 + 2*log(1 - x) - log(x + 2)/2,
    ),
    RubiTestSuiteCase(
        integrand=(x**2 + 2*x + 3)/((x - 1)*(x + 1)**2),
        variable=x,
        num_steps=2,
        integral=3*log(1 - x)/2 - log(x + 1)/2 + 1/(x + 1),
    ),
    RubiTestSuiteCase(
        integrand=(3*x**2 + 2*x - 2)/(x**3 - 1),
        variable=x,
        num_steps=5,
        integral=log(1 - x**3) + 4*sqrt(3)*atan(sqrt(3)*(2*x + 1)/3)/3,
    ),
    RubiTestSuiteCase(
        integrand=(x**4 - x**3 + 2*x**2 - x + 2)/((x - 1)*(x**2 + 2)**2),
        variable=x,
        num_steps=6,
        integral=log(1 - x)/3 + log(x**2 + 2)/3 - sqrt(2)*atan(sqrt(2)*x/2)/6 + 1/(2*x**2 + 4),
    ),
    RubiTestSuiteCase(
        integrand=1/(sin(x) + cos(x)),
        variable=x,
        num_steps=2,
        integral=-sqrt(2)*atanh(sqrt(2)*(-sin(x) + cos(x))/2)/2,
    ),
    RubiTestSuiteCase(
        integrand=x/(-x**2 + sqrt(4 - x**2) + 4),
        variable=x,
        num_steps=3,
        integral=-log(sqrt(4 - x**2) + 1),
    ),
    RubiTestSuiteCase(
        integrand=(2*x + 3)/((x - 2)*(x + 5)),
        variable=x,
        num_steps=2,
        integral=log(2 - x) + log(x + 5),
    ),
    RubiTestSuiteCase(
        integrand=x/((x + 1)*(x + 2)*(x + 3)),
        variable=x,
        num_steps=2,
        integral=-log(x + 1)/2 + 2*log(x + 2) - 3*log(x + 3)/2,
    ),
    RubiTestSuiteCase(
        integrand=x/(x**3 - 3*x + 2),
        variable=x,
        num_steps=2,
        integral=2*log(1 - x)/9 - 2*log(x + 2)/9 + 1/(3 - 3*x),
    ),
    RubiTestSuiteCase(
        integrand=(x**4 + 2*x - 6)/(x**3 + x**2 - 2*x),
        variable=x,
        num_steps=3,
        integral=x**2/2 - x + 3*log(x) - log(1 - x) + log(x + 2),
    ),
    RubiTestSuiteCase(
        integrand=(8*x**3 + 7)/((x + 1)*(2*x + 1)**3),
        variable=x,
        num_steps=2,
        integral=log(x + 1) + 3/(2*x + 1) - 3/(2*x + 1)**2,
    ),
    RubiTestSuiteCase(
        integrand=(4*x**2 + x + 1)/(x**3 - 1),
        variable=x,
        num_steps=3,
        integral=2*log(1 - x) + log(x**2 + x + 1),
    ),
    RubiTestSuiteCase(
        integrand=x**4/(x**4 + 5*x**2 + 4),
        variable=x,
        num_steps=4,
        integral=x - 8*atan(x/2)/3 + atan(x)/3,
    ),
    RubiTestSuiteCase(
        integrand=(x + 2)/(x**2 + x),
        variable=x,
        num_steps=2,
        integral=2*log(x) - log(x + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*(x**2 + 1)**2),
        variable=x,
        num_steps=3,
        integral=log(x) - log(x**2 + 1)/2 + 1/(2*x**2 + 2),
    ),
    RubiTestSuiteCase(
        integrand=1/((x + 1)*(x + 2)**2*(x + 3)**3),
        variable=x,
        num_steps=2,
        integral=log(x + 1)/8 + 2*log(x + 2) - 17*log(x + 3)/8 + 5/(4*x + 12) + 1/(4*(x + 3)**2) + 1/(x + 2),
    ),
    RubiTestSuiteCase(
        integrand=x/(x + 1)**2,
        variable=x,
        num_steps=2,
        integral=log(x + 1) + 1/(x + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3 - x),
        variable=x,
        num_steps=5,
        integral=-log(x) + log(1 - x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=x**2/(x**2 + x - 6),
        variable=x,
        num_steps=4,
        integral=x + 4*log(2 - x)/5 - 9*log(x + 3)/5,
    ),
    RubiTestSuiteCase(
        integrand=(x + 2)/(x**2 - 4*x + 4),
        variable=x,
        num_steps=3,
        integral=log(2 - x) + 4/(2 - x),
    ),
    RubiTestSuiteCase(
        integrand=1/((x**2 - 4*x + 4)*(x**2 - 4*x + 5)),
        variable=x,
        num_steps=4,
        integral=-atan(x - 2) + 1/(2 - x),
    ),
    RubiTestSuiteCase(
        integrand=(x - 3)/(x**3 + 3*x**2 + 2*x),
        variable=x,
        num_steps=3,
        integral=-3*log(x)/2 + 4*log(x + 1) - 5*log(x + 2)/2,
    ),
    RubiTestSuiteCase(
        integrand=(x**2 - 1)**(-2),
        variable=x,
        num_steps=2,
        integral=x/(2 - 2*x**2) + atanh(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=(x + 1)/(x**3 - 1),
        variable=x,
        num_steps=3,
        integral=2*log(1 - x)/3 - log(x**2 + x + 1)/3,
    ),
    RubiTestSuiteCase(
        integrand=(x**4 + 1)/(x*(x**2 + 1)**2),
        variable=x,
        num_steps=3,
        integral=log(x) + 1/(x**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 - 2*x**3),
        variable=x,
        num_steps=3,
        integral=-log(x)/8 + log(2 - x)/8 + 1/(4*x) + 1/(4*x**2),
    ),
    RubiTestSuiteCase(
        integrand=(1 - x**3)/(x*(x**2 + 1)),
        variable=x,
        num_steps=5,
        integral=-x + log(x) - log(x**2 + 1)/2 + atan(x),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 - 1),
        variable=x,
        num_steps=3,
        integral=-atan(x)/2 - atanh(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 + 1),
        variable=x,
        num_steps=9,
        integral=-sqrt(2)*log(x**2 - sqrt(2)*x + 1)/8 + sqrt(2)*log(x**2 + sqrt(2)*x + 1)/8 + sqrt(2)*atan(sqrt(2)*x - 1)/4 + sqrt(2)*atan(sqrt(2)*x + 1)/4,
    ),
    RubiTestSuiteCase(
        integrand=x**2/(x**2 + 2*x + 2)**2,
        variable=x,
        num_steps=3,
        integral=-x*(x + 2)/(2*x**2 + 4*x + 4) + atan(x + 1),
    ),
    RubiTestSuiteCase(
        integrand=(4*x**5 - 1)/(x**5 + x + 1)**2,
        variable=x,
        num_steps=1,
        integral=-x/(x**5 + x + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/(2*sin(x) - cos(x) + 5),
        variable=x,
        num_steps=3,
        integral=sqrt(5)*x/10 + sqrt(5)*atan((sin(x) + 2*cos(x))/(2*sin(x) - cos(x) + 2*sqrt(5) + 5))/5,
    ),
    RubiTestSuiteCase(
        integrand=1/(a*cos(x) + 1),
        variable=x,
        num_steps=2,
        integral=2*atan(sqrt(1 - a)*tan(x/2)/sqrt(a + 1))/sqrt(1 - a**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(2*cos(x) + 1),
        variable=x,
        num_steps=2,
        integral=-sqrt(3)*log(-sin(x/2) + sqrt(3)*cos(x/2))/3 + sqrt(3)*log(sin(x/2) + sqrt(3)*cos(x/2))/3,
    ),
    RubiTestSuiteCase(
        integrand=1/(cos(x)/2 + 1),
        variable=x,
        num_steps=1,
        integral=2*sqrt(3)*x/3 - 4*sqrt(3)*atan(sin(x)/(cos(x) + sqrt(3) + 2))/3,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2/(sin(x)**2 + 1),
        variable=x,
        num_steps=3,
        integral=-sqrt(2)*x/2 + x - sqrt(2)*atan(sin(x)*cos(x)/(sin(x)**2 + 1 + sqrt(2)))/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(a**2*sin(x)**2 + b**2*cos(x)**2),
        variable=x,
        num_steps=2,
        integral=atan(a*tan(x)/b)/(a*b),
    ),
    RubiTestSuiteCase(
        integrand=(a*sin(x) + b*cos(x))**(-2),
        variable=x,
        num_steps=1,
        integral=sin(x)/(b*(a*sin(x) + b*cos(x))),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/(sin(x) + cos(x) + 1),
        variable=x,
        num_steps=3,
        integral=x/2 - log(tan(x/2) + 1)/2 - log(sin(x) + cos(x) + 1)/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(3 - x**2),
        variable=x,
        num_steps=2,
        integral=x*sqrt(3 - x**2)/2 + 3*asin(sqrt(3)*x/3)/2,
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(3 - x**2),
        variable=x,
        num_steps=1,
        integral=-sqrt(3 - x**2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(3 - x**2)/x,
        variable=x,
        num_steps=4,
        integral=sqrt(3 - x**2) - sqrt(3)*atanh(sqrt(3)*sqrt(3 - x**2)/3),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x**2 + x)/x,
        variable=x,
        num_steps=3,
        integral=sqrt(x**2 + x) + atanh(x/sqrt(x**2 + x)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x**2 + 5),
        variable=x,
        num_steps=2,
        integral=x*sqrt(x**2 + 5)/2 + 5*asinh(sqrt(5)*x/5)/2,
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(x**2 + x + 1),
        variable=x,
        num_steps=3,
        integral=sqrt(x**2 + x + 1) - asinh(sqrt(3)*(2*x + 1)/3)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(x**2 + x),
        variable=x,
        num_steps=2,
        integral=2*atanh(x/sqrt(x**2 + x)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-x**2 - x + 2)/x**2,
        variable=x,
        num_steps=6,
        integral=-asin(2*x/3 + sympy.S(1)/3) + sqrt(2)*atanh(sqrt(2)*(4 - x)/(4*sqrt(-x**2 - x + 2)))/4 - sqrt(-x**2 - x + 2)/x,
    ),
    RubiTestSuiteCase(
        integrand=log(t)/(t + 1),
        variable=t,
        num_steps=2,
        integral=((sympy.log(Symbol('t')) * sympy.log((Integer(1) + Symbol('t')))) + sympy.Function('PolyLog')(Integer(2), (Integer(-1) * Symbol('t')))),
    ),
    RubiTestSuiteCase(
        integrand=log(exp(cos(x))),
        variable=x,
        num_steps=3,
        integral=x*log(exp(cos(x))) - x*cos(x) + sin(x),
    ),
    RubiTestSuiteCase(
        integrand=exp(t)/t,
        variable=t,
        num_steps=1,
        integral=sympy.Function('ExpIntegralEi')(Symbol('t')),
    ),
    RubiTestSuiteCase(
        integrand=exp(a*t)/t,
        variable=t,
        num_steps=1,
        integral=sympy.Function('ExpIntegralEi')((Symbol('a') * Symbol('t'))),
    ),
    RubiTestSuiteCase(
        integrand=exp(t)/t**2,
        variable=t,
        num_steps=2,
        integral=((Integer(-1) * ((sympy.E)**(Symbol('t')) * (Symbol('t'))**(Integer(-1)))) + sympy.Function('ExpIntegralEi')(Symbol('t'))),
    ),
    RubiTestSuiteCase(
        integrand=exp(1/t),
        variable=t,
        num_steps=2,
        integral=(((sympy.E)**((Symbol('t'))**(Integer(-1))) * Symbol('t')) + (Integer(-1) * sympy.Function('ExpIntegralEi')((Symbol('t'))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=exp(-t)/(-a + t - 1),
        variable=t,
        num_steps=1,
        integral=((sympy.E)**((Integer(-1) + (Integer(-1) * Symbol('a')))) * sympy.Function('ExpIntegralEi')((Integer(1) + Symbol('a') + (Integer(-1) * Symbol('t'))))),
    ),
    RubiTestSuiteCase(
        integrand=t*exp(t**2)/(t**2 + 1),
        variable=t,
        num_steps=2,
        integral=(sympy.Function('ExpIntegralEi')((Integer(1) + (Symbol('t'))**(Integer(2)))) * ((Integer(2) * sympy.E))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=exp(t)/(t + 1)**2,
        variable=t,
        num_steps=2,
        integral=((Integer(-1) * ((sympy.E)**(Symbol('t')) * ((Integer(1) + Symbol('t')))**(Integer(-1)))) + (sympy.Function('ExpIntegralEi')((Integer(1) + Symbol('t'))) * (sympy.E)**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=exp(t)*log(t + 1),
        variable=t,
        num_steps=2,
        integral=((Integer(-1) * (sympy.Function('ExpIntegralEi')((Integer(1) + Symbol('t'))) * (sympy.E)**(Integer(-1)))) + ((sympy.E)**(Symbol('t')) * sympy.log((Integer(1) + Symbol('t'))))),
    ),
    RubiTestSuiteCase(
        integrand=t*exp(-t),
        variable=t,
        num_steps=2,
        integral=-t*exp(-t) - exp(-t),
    ),
    RubiTestSuiteCase(
        integrand=t**2*exp(-t),
        variable=t,
        num_steps=3,
        integral=-t**2*exp(-t) - 2*t*exp(-t) - 2*exp(-t),
    ),
    RubiTestSuiteCase(
        integrand=t**3*exp(-t),
        variable=t,
        num_steps=4,
        integral=-t**3*exp(-t) - 3*t**2*exp(-t) - 6*t*exp(-t) - 6*exp(-t),
    ),
    RubiTestSuiteCase(
        integrand=(a1*sin(x) + b1*cos(x))/(a*sin(x) + b*cos(x)),
        variable=x,
        num_steps=1,
        integral=x*(a*a1 + b*b1)/(a**2 + b**2) - (-a*b1 + a1*b)*log(a*sin(x) + b*cos(x))/(a**2 + b**2),
    ),
    RubiTestSuiteCase(
        integrand=1/log(t),
        variable=t,
        num_steps=1,
        integral=sympy.Function('LogIntegral')(Symbol('t')),
    ),
    RubiTestSuiteCase(
        integrand=log(t)**(-2),
        variable=t,
        num_steps=2,
        integral=((Integer(-1) * (Symbol('t') * (sympy.log(Symbol('t')))**(Integer(-1)))) + sympy.Function('LogIntegral')(Symbol('t'))),
    ),
    RubiTestSuiteCase(
        integrand=log(t)**(-n - 1),
        variable=t,
        num_steps=2,
        integral=(((Integer(-1) * sympy.Function('Gamma')((Integer(-1) * Symbol('n')), (Integer(-1) * sympy.log(Symbol('t'))))) * ((Integer(-1) * sympy.log(Symbol('t'))))**(Symbol('n'))) * ((sympy.log(Symbol('t')))**(Symbol('n')))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=exp(2*t)/(t - 1),
        variable=t,
        num_steps=1,
        integral=((sympy.E)**(Integer(2)) * sympy.Function('ExpIntegralEi')((Integer(-2) * (Integer(1) + (Integer(-1) * Symbol('t')))))),
    ),
    RubiTestSuiteCase(
        integrand=exp(2*x)/(x**2 - 3*x + 2),
        variable=x,
        num_steps=4,
        integral=(((sympy.E)**(Integer(4)) * sympy.Function('ExpIntegralEi')((Integer(-4) + (Integer(2) * x)))) + (Integer(-1) * ((sympy.E)**(Integer(2)) * sympy.Function('ExpIntegralEi')((Integer(-2) + (Integer(2) * x)))))),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(t**3 + 1),
        variable=t,
        num_steps=1,
        integral=2*3**(sympy.S(3)/4)*sqrt((t**2 - t + 1)/(t + 1 + sqrt(3))**2)*sqrt(sqrt(3) + 2)*(t + 1)*elliptic_f(asin((t - sqrt(3) + 1)/(t + 1 + sqrt(3))), -7 - 4*sqrt(3))/(3*sqrt((t + 1)/(t + 1 + sqrt(3))**2)*sqrt(t**3 + 1)),
    ),
]
