# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 0 Independent test suites/Hearn Problems.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '0 Independent test suites/Hearn Problems.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, alpha, b, c, d, e, eps, epsilon, h, k, m, mc, p, q, r, y, z = symbols('a alpha b c d e eps epsilon h k m mc p q r y z')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=x**2 + x + 1,
        variable=x,
        num_steps=1,
        integral=x**3/3 + x**2/2 + x,
    ),
    RubiTestSuiteCase(
        integrand=x**2*(2*x**2 + x)**2,
        variable=x,
        num_steps=3,
        integral=4*x**7/7 + 2*x**6/3 + x**5/5,
    ),
    RubiTestSuiteCase(
        integrand=x*(x**2 + 2*x + 1),
        variable=x,
        num_steps=2,
        integral=x**4/4 + 2*x**3/3 + x**2/2,
    ),
    RubiTestSuiteCase(
        integrand=1/x,
        variable=x,
        num_steps=1,
        integral=log(x),
    ),
    RubiTestSuiteCase(
        integrand=(x + 1)**3/(x - 1)**4,
        variable=x,
        num_steps=2,
        integral=log(1 - x) + 6/(1 - x) - 6/(1 - x)**2 + 8/(3*(1 - x)**3),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*(x - 1)*(x + 1)**2),
        variable=x,
        num_steps=2,
        integral=-log(x) + log(1 - x)/4 + 3*log(x + 1)/4 - 1/(2*x + 2),
    ),
    RubiTestSuiteCase(
        integrand=(a*x + b)/((-p + x)*(-q + x)),
        variable=x,
        num_steps=2,
        integral=(a*p + b)*log(p - x)/(p - q) - (a*q + b)*log(q - x)/(p - q),
    ),
    RubiTestSuiteCase(
        integrand=1/(a*x**2 + b*x + c),
        variable=x,
        num_steps=2,
        integral=-2*atanh((2*a*x + b)/sqrt(-4*a*c + b**2))/sqrt(-4*a*c + b**2),
    ),
    RubiTestSuiteCase(
        integrand=(a*x + b)/(x**2 + 1),
        variable=x,
        num_steps=3,
        integral=a*log(x**2 + 1)/2 + b*atan(x),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2 - 2*x + 3),
        variable=x,
        num_steps=2,
        integral=-sqrt(2)*atan(sqrt(2)*(1 - x)/2)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/((x - 1)**2*(x**2 + 1)**2),
        variable=x,
        num_steps=6,
        integral=-log(1 - x)/2 + log(x**2 + 1)/4 + atan(x)/4 - 1/(4*x**2 + 4) + 1/(4 - 4*x),
    ),
    RubiTestSuiteCase(
        integrand=x/((-a + x)*(-b + x)*(-c + x)),
        variable=x,
        num_steps=2,
        integral=a*log(a - x)/((a - b)*(a - c)) - b*log(b - x)/((a - b)*(b - c)) + c*log(c - x)/((a - c)*(b - c)),
    ),
    RubiTestSuiteCase(
        integrand=x/((a**2 + x**2)*(b**2 + x**2)),
        variable=x,
        num_steps=4,
        integral=-log(a**2 + x**2)/(2*a**2 - 2*b**2) + log(b**2 + x**2)/(2*a**2 - 2*b**2),
    ),
    RubiTestSuiteCase(
        integrand=x**2/((a**2 + x**2)*(b**2 + x**2)),
        variable=x,
        num_steps=3,
        integral=a*atan(x/a)/(a**2 - b**2) - b*atan(x/b)/(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=x/((x - 1)*(x**2 + 1)),
        variable=x,
        num_steps=5,
        integral=log(1 - x)/2 - log(x**2 + 1)/4 + atan(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=x/(x**3 + 1),
        variable=x,
        num_steps=6,
        integral=-log(x + 1)/3 + log(x**2 - x + 1)/6 - sqrt(3)*atan(sqrt(3)*(1 - 2*x)/3)/3,
    ),
    RubiTestSuiteCase(
        integrand=x**3/((x - 1)**2*(x**3 + 1)),
        variable=x,
        num_steps=3,
        integral=3*log(1 - x)/4 - log(x + 1)/12 - log(x**2 - x + 1)/3 + 1/(2 - 2*x),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 + 1),
        variable=x,
        num_steps=9,
        integral=-sqrt(2)*log(x**2 - sqrt(2)*x + 1)/8 + sqrt(2)*log(x**2 + sqrt(2)*x + 1)/8 + sqrt(2)*atan(sqrt(2)*x - 1)/4 + sqrt(2)*atan(sqrt(2)*x + 1)/4,
    ),
    RubiTestSuiteCase(
        integrand=x**2/(x**4 + 1),
        variable=x,
        num_steps=9,
        integral=sqrt(2)*log(x**2 - sqrt(2)*x + 1)/8 - sqrt(2)*log(x**2 + sqrt(2)*x + 1)/8 + sqrt(2)*atan(sqrt(2)*x - 1)/4 + sqrt(2)*atan(sqrt(2)*x + 1)/4,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 + x**2 + 1),
        variable=x,
        num_steps=9,
        integral=-log(x**2 - x + 1)/4 + log(x**2 + x + 1)/4 - sqrt(3)*atan(sqrt(3)*(1 - 2*x)/3)/6 + sqrt(3)*atan(sqrt(3)*(2*x + 1)/3)/6,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*x)**p,
        variable=x,
        num_steps=1,
        integral=(a + b*x)**(p + 1)/(b*(p + 1)),
    ),
    RubiTestSuiteCase(
        integrand=x*(a + b*x)**p,
        variable=x,
        num_steps=2,
        integral=-a*(a + b*x)**(p + 1)/(b**2*(p + 1)) + (a + b*x)**(p + 2)/(b**2*(p + 2)),
    ),
    RubiTestSuiteCase(
        integrand=x**2*(a + b*x)**p,
        variable=x,
        num_steps=2,
        integral=a**2*(a + b*x)**(p + 1)/(b**3*(p + 1)) - 2*a*(a + b*x)**(p + 2)/(b**3*(p + 2)) + (a + b*x)**(p + 3)/(b**3*(p + 3)),
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*x),
        variable=x,
        num_steps=1,
        integral=log(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*x)**(-2),
        variable=x,
        num_steps=1,
        integral=-1/(b*(a + b*x)),
    ),
    RubiTestSuiteCase(
        integrand=x/(a + b*x),
        variable=x,
        num_steps=2,
        integral=-a*log(a + b*x)/b**2 + x/b,
    ),
    RubiTestSuiteCase(
        integrand=x**2/(a + b*x),
        variable=x,
        num_steps=2,
        integral=a**2*log(a + b*x)/b**3 - a*x/b**2 + x**2/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*(a + b*x)),
        variable=x,
        num_steps=3,
        integral=log(x)/a - log(a + b*x)/a,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*(a + b*x)),
        variable=x,
        num_steps=2,
        integral=-1/(a*x) - b*log(x)/a**2 + b*log(a + b*x)/a**2,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*(a + b*x)**2),
        variable=x,
        num_steps=2,
        integral=-b/(a**2*(a + b*x)) - 1/(a**2*x) - 2*b*log(x)/a**3 + 2*b*log(a + b*x)/a**3,
    ),
    RubiTestSuiteCase(
        integrand=1/(c**2 + x**2),
        variable=x,
        num_steps=1,
        integral=atan(x/c)/c,
    ),
    RubiTestSuiteCase(
        integrand=1/(c**2 - x**2),
        variable=x,
        num_steps=1,
        integral=atanh(x/c)/c,
    ),
    RubiTestSuiteCase(
        integrand=1/(2*x**3 - 1),
        variable=x,
        num_steps=6,
        integral=2**(sympy.S(2)/3)*log(-2**(sympy.S(1)/3)*x + 1)/6 - 2**(sympy.S(2)/3)*log(2**(sympy.S(2)/3)*x**2 + 2**(sympy.S(1)/3)*x + 1)/12 - 2**(sympy.S(2)/3)*sqrt(3)*atan(sqrt(3)*(2*2**(sympy.S(1)/3)*x + 1)/3)/6,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3 - 2),
        variable=x,
        num_steps=6,
        integral=2**(sympy.S(1)/3)*log(-x + 2**(sympy.S(1)/3))/6 - 2**(sympy.S(1)/3)*log(x**2 + 2**(sympy.S(1)/3)*x + 2**(sympy.S(2)/3))/12 - 2**(sympy.S(1)/3)*sqrt(3)*atan(sqrt(3)*(2**(sympy.S(2)/3)*x + 1)/3)/6,
    ),
    RubiTestSuiteCase(
        integrand=1/(a*x**3 - b),
        variable=x,
        num_steps=6,
        integral=log(-a**(sympy.S(1)/3)*x + b**(sympy.S(1)/3))/(3*a**(sympy.S(1)/3)*b**(sympy.S(2)/3)) - log(a**(sympy.S(2)/3)*x**2 + a**(sympy.S(1)/3)*b**(sympy.S(1)/3)*x + b**(sympy.S(2)/3))/(6*a**(sympy.S(1)/3)*b**(sympy.S(2)/3)) - sqrt(3)*atan(sqrt(3)*(2*a**(sympy.S(1)/3)*x + b**(sympy.S(1)/3))/(3*b**(sympy.S(1)/3)))/(3*a**(sympy.S(1)/3)*b**(sympy.S(2)/3)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 - 2),
        variable=x,
        num_steps=3,
        integral=-2**(sympy.S(1)/4)*atan(2**(sympy.S(3)/4)*x/2)/4 - 2**(sympy.S(1)/4)*atanh(2**(sympy.S(3)/4)*x/2)/4,
    ),
    RubiTestSuiteCase(
        integrand=1/(5*x**4 - 1),
        variable=x,
        num_steps=3,
        integral=-5**(sympy.S(3)/4)*atan(5**(sympy.S(1)/4)*x)/10 - 5**(sympy.S(3)/4)*atanh(5**(sympy.S(1)/4)*x)/10,
    ),
    RubiTestSuiteCase(
        integrand=1/(3*x**4 + 7),
        variable=x,
        num_steps=9,
        integral=-sqrt(2)*3**(sympy.S(3)/4)*7**(sympy.S(1)/4)*log(3*x**2 - sqrt(2)*3**(sympy.S(3)/4)*7**(sympy.S(1)/4)*x + sqrt(21))/168 + sqrt(2)*3**(sympy.S(3)/4)*7**(sympy.S(1)/4)*log(3*x**2 + sqrt(2)*3**(sympy.S(3)/4)*7**(sympy.S(1)/4)*x + sqrt(21))/168 + sqrt(2)*3**(sympy.S(3)/4)*7**(sympy.S(1)/4)*atan(sqrt(2)*3**(sympy.S(1)/4)*7**(sympy.S(3)/4)*x/7 - 1)/84 + sqrt(2)*3**(sympy.S(3)/4)*7**(sympy.S(1)/4)*atan(sqrt(2)*3**(sympy.S(1)/4)*7**(sympy.S(3)/4)*x/7 + 1)/84,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 + 3*x**2 - 1),
        variable=x,
        num_steps=3,
        integral=-sqrt(2)*atan(sqrt(2)*x/sqrt(3 + sqrt(13)))/sqrt(39 + 13*sqrt(13)) - sqrt(sympy.S(3)/26 + sqrt(13)/26)*atanh(sqrt(2)*x/sqrt(-3 + sqrt(13))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 - 3*x**2 - 1),
        variable=x,
        num_steps=3,
        integral=-sqrt(sympy.S(3)/26 + sqrt(13)/26)*atan(sqrt(2)*x/sqrt(-3 + sqrt(13))) - sqrt(2)*atanh(sqrt(2)*x/sqrt(3 + sqrt(13)))/sqrt(39 + 13*sqrt(13)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 - 3*x**2 + 1),
        variable=x,
        num_steps=3,
        integral=sqrt(sqrt(5)/10 + sympy.S(3)/10)*atanh(x*sqrt(sqrt(5)/2 + sympy.S(3)/2)) - sqrt(2)*atanh(sqrt(2)*x/sqrt(sqrt(5) + 3))/sqrt(5*sqrt(5) + 15),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 - 4*x**2 + 1),
        variable=x,
        num_steps=3,
        integral=atanh(x/sqrt(2 - sqrt(3)))/(2*sqrt(6 - 3*sqrt(3))) - atanh(x/sqrt(sqrt(3) + 2))/(2*sqrt(3*sqrt(3) + 6)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 + 4*x**2 + 1),
        variable=x,
        num_steps=3,
        integral=atan(x/sqrt(2 - sqrt(3)))/(2*sqrt(6 - 3*sqrt(3))) - atan(x/sqrt(sqrt(3) + 2))/(2*sqrt(3*sqrt(3) + 6)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 + x**2 + 2),
        variable=x,
        num_steps=9,
        integral=-log(x**2 - x*sqrt(-1 + 2*sqrt(2)) + sqrt(2))/(4*sqrt(-2 + 4*sqrt(2))) + log(x**2 + x*sqrt(-1 + 2*sqrt(2)) + sqrt(2))/(4*sqrt(-2 + 4*sqrt(2))) - sqrt(sympy.S(-1)/14 + sqrt(2)/7)*atan((-2*x + sqrt(-1 + 2*sqrt(2)))/sqrt(1 + 2*sqrt(2)))/2 + sqrt(sympy.S(-1)/14 + sqrt(2)/7)*atan((2*x + sqrt(-1 + 2*sqrt(2)))/sqrt(1 + 2*sqrt(2)))/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 - x**2 + 2),
        variable=x,
        num_steps=9,
        integral=-log(x**2 - x*sqrt(1 + 2*sqrt(2)) + sqrt(2))/(4*sqrt(2 + 4*sqrt(2))) + log(x**2 + x*sqrt(1 + 2*sqrt(2)) + sqrt(2))/(4*sqrt(2 + 4*sqrt(2))) - sqrt(sympy.S(1)/14 + sqrt(2)/7)*atan((-2*x + sqrt(1 + 2*sqrt(2)))/sqrt(-1 + 2*sqrt(2)))/2 + sqrt(sympy.S(1)/14 + sqrt(2)/7)*atan((2*x + sqrt(1 + 2*sqrt(2)))/sqrt(-1 + 2*sqrt(2)))/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**6 - 1),
        variable=x,
        num_steps=10,
        integral=log(x**2 - x + 1)/12 - log(x**2 + x + 1)/12 + sqrt(3)*atan(sqrt(3)*(1 - 2*x)/3)/6 - sqrt(3)*atan(sqrt(3)*(2*x + 1)/3)/6 - atanh(x)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**6 - 2),
        variable=x,
        num_steps=10,
        integral=2**(sympy.S(1)/6)*log(x**2 - 2**(sympy.S(1)/6)*x + 2**(sympy.S(1)/3))/24 - 2**(sympy.S(1)/6)*log(x**2 + 2**(sympy.S(1)/6)*x + 2**(sympy.S(1)/3))/24 - 2**(sympy.S(1)/6)*sqrt(3)*atan(2**(sympy.S(5)/6)*sqrt(3)*x/3 - sqrt(3)/3)/12 - 2**(sympy.S(1)/6)*sqrt(3)*atan(2**(sympy.S(5)/6)*sqrt(3)*x/3 + sqrt(3)/3)/12 - 2**(sympy.S(1)/6)*atanh(2**(sympy.S(5)/6)*x/2)/6,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**6 + 2),
        variable=x,
        num_steps=10,
        integral=-2**(sympy.S(1)/6)*sqrt(3)*log(x**2 - 2**(sympy.S(1)/6)*sqrt(3)*x + 2**(sympy.S(1)/3))/24 + 2**(sympy.S(1)/6)*sqrt(3)*log(x**2 + 2**(sympy.S(1)/6)*sqrt(3)*x + 2**(sympy.S(1)/3))/24 + 2**(sympy.S(1)/6)*atan(2**(sympy.S(5)/6)*x/2)/6 + 2**(sympy.S(1)/6)*atan(2**(sympy.S(5)/6)*x - sqrt(3))/12 + 2**(sympy.S(1)/6)*atan(2**(sympy.S(5)/6)*x + sqrt(3))/12,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**8 + 1),
        variable=x,
        num_steps=19,
        integral=-sqrt(2 - sqrt(2))*log(x**2 - x*sqrt(2 - sqrt(2)) + 1)/16 + sqrt(2 - sqrt(2))*log(x**2 + x*sqrt(2 - sqrt(2)) + 1)/16 - sqrt(sqrt(2) + 2)*log(x**2 - x*sqrt(sqrt(2) + 2) + 1)/16 + sqrt(sqrt(2) + 2)*log(x**2 + x*sqrt(sqrt(2) + 2) + 1)/16 - atan((-2*x + sqrt(sqrt(2) + 2))/sqrt(2 - sqrt(2)))/(4*sqrt(2*sqrt(2) + 4)) + atan((2*x + sqrt(sqrt(2) + 2))/sqrt(2 - sqrt(2)))/(4*sqrt(2*sqrt(2) + 4)) - atan((-2*x + sqrt(2 - sqrt(2)))/sqrt(sqrt(2) + 2))/(4*sqrt(4 - 2*sqrt(2))) + atan((2*x + sqrt(2 - sqrt(2)))/sqrt(sqrt(2) + 2))/(4*sqrt(4 - 2*sqrt(2))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**8 - 1),
        variable=x,
        num_steps=13,
        integral=sqrt(2)*log(x**2 - sqrt(2)*x + 1)/16 - sqrt(2)*log(x**2 + sqrt(2)*x + 1)/16 - atan(x)/4 - sqrt(2)*atan(sqrt(2)*x - 1)/8 - sqrt(2)*atan(sqrt(2)*x + 1)/8 - atanh(x)/4,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**8 - x**4 + 1),
        variable=x,
        num_steps=19,
        integral=-sqrt(6)*log(x**2 - x*sqrt(2 - sqrt(3)) + 1)/24 + sqrt(6)*log(x**2 + x*sqrt(2 - sqrt(3)) + 1)/24 - sqrt(6)*log(x**2 - x*sqrt(sqrt(3) + 2) + 1)/24 + sqrt(6)*log(x**2 + x*sqrt(sqrt(3) + 2) + 1)/24 - sqrt(6)*atan((-2*x + sqrt(sqrt(3) + 2))/sqrt(2 - sqrt(3)))/12 + sqrt(6)*atan((2*x + sqrt(sqrt(3) + 2))/sqrt(2 - sqrt(3)))/12 - sqrt(6)*atan((-2*x + sqrt(2 - sqrt(3)))/sqrt(sqrt(3) + 2))/12 + sqrt(6)*atan((2*x + sqrt(2 - sqrt(3)))/sqrt(sqrt(3) + 2))/12,
    ),
    RubiTestSuiteCase(
        integrand=x**7/(x**12 + 1),
        variable=x,
        num_steps=7,
        integral=-log(x**4 + 1)/12 + log(x**8 - x**4 + 1)/24 - sqrt(3)*atan(sqrt(3)*(1 - 2*x**4)/3)/12,
    ),
    RubiTestSuiteCase(
        integrand=log(x),
        variable=x,
        num_steps=1,
        integral=x*log(x) - x,
    ),
    RubiTestSuiteCase(
        integrand=x*log(x),
        variable=x,
        num_steps=1,
        integral=x**2*log(x)/2 - x**2/4,
    ),
    RubiTestSuiteCase(
        integrand=x**2*log(x),
        variable=x,
        num_steps=1,
        integral=x**3*log(x)/3 - x**3/9,
    ),
    RubiTestSuiteCase(
        integrand=x**p*log(x),
        variable=x,
        num_steps=1,
        integral=x**(p + 1)*log(x)/(p + 1) - x**(p + 1)/(p + 1)**2,
    ),
    RubiTestSuiteCase(
        integrand=log(x)**2,
        variable=x,
        num_steps=2,
        integral=x*log(x)**2 - 2*x*log(x) + 2*x,
    ),
    RubiTestSuiteCase(
        integrand=x**9*log(x)**11,
        variable=x,
        num_steps=11,
        integral=x**10*log(x)**11/10 - 11*x**10*log(x)**10/100 + 11*x**10*log(x)**9/100 - 99*x**10*log(x)**8/1000 + 99*x**10*log(x)**7/1250 - 693*x**10*log(x)**6/12500 + 2079*x**10*log(x)**5/62500 - 2079*x**10*log(x)**4/125000 + 2079*x**10*log(x)**3/312500 - 6237*x**10*log(x)**2/3125000 + 6237*x**10*log(x)/15625000 - 6237*x**10/156250000,
    ),
    RubiTestSuiteCase(
        integrand=log(x)**2/x,
        variable=x,
        num_steps=2,
        integral=log(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=1/log(x),
        variable=x,
        num_steps=1,
        integral=sympy.Function('LogIntegral')(x),
    ),
    RubiTestSuiteCase(
        integrand=1/log(x + 1),
        variable=x,
        num_steps=2,
        integral=sympy.Function('LogIntegral')((Integer(1) + x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*log(x)),
        variable=x,
        num_steps=2,
        integral=log(log(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*log(x)**2),
        variable=x,
        num_steps=3,
        integral=((Integer(-1) * sympy.Function('ExpIntegralEi')((Integer(-1) * sympy.log(x)))) + (Integer(-1) * ((x * sympy.log(x)))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=log(x)**p/x,
        variable=x,
        num_steps=2,
        integral=log(x)**(p + 1)/(p + 1),
    ),
    RubiTestSuiteCase(
        integrand=(a*x + b)*log(x),
        variable=x,
        num_steps=2,
        integral=a*x**2*log(x)/2 - a*x**2/4 + b*x*log(x) - b*x,
    ),
    RubiTestSuiteCase(
        integrand=(a*x + b)**2*log(x),
        variable=x,
        num_steps=4,
        integral=-a**2*x**3/9 - a*b*x**2/2 - b**2*x - b**3*log(x)/(3*a) + (a*x + b)**3*log(x)/(3*a),
    ),
    RubiTestSuiteCase(
        integrand=log(x)/(a*x + b)**2,
        variable=x,
        num_steps=2,
        integral=x*log(x)/(b*(a*x + b)) - log(a*x + b)/(a*b),
    ),
    RubiTestSuiteCase(
        integrand=x*log(a*x + b),
        variable=x,
        num_steps=3,
        integral=x**2*log(a*x + b)/2 - x**2/4 + b*x/(2*a) - b**2*log(a*x + b)/(2*a**2),
    ),
    RubiTestSuiteCase(
        integrand=x**2*log(a*x + b),
        variable=x,
        num_steps=3,
        integral=x**3*log(a*x + b)/3 - x**3/9 + b*x**2/(6*a) - b**2*x/(3*a**2) + b**3*log(a*x + b)/(3*a**3),
    ),
    RubiTestSuiteCase(
        integrand=log(a**2 + x**2),
        variable=x,
        num_steps=3,
        integral=2*a*atan(x/a) + x*log(a**2 + x**2) - 2*x,
    ),
    RubiTestSuiteCase(
        integrand=x*log(a**2 + x**2),
        variable=x,
        num_steps=3,
        integral=-x**2/2 + (a**2/2 + x**2/2)*log(a**2 + x**2),
    ),
    RubiTestSuiteCase(
        integrand=x**2*log(a**2 + x**2),
        variable=x,
        num_steps=4,
        integral=-2*a**3*atan(x/a)/3 + 2*a**2*x/3 + x**3*log(a**2 + x**2)/3 - 2*x**3/9,
    ),
    RubiTestSuiteCase(
        integrand=x**4*log(a**2 + x**2),
        variable=x,
        num_steps=4,
        integral=2*a**5*atan(x/a)/5 - 2*a**4*x/5 + 2*a**2*x**3/15 + x**5*log(a**2 + x**2)/5 - 2*x**5/25,
    ),
    RubiTestSuiteCase(
        integrand=log(-a**2 + x**2),
        variable=x,
        num_steps=3,
        integral=2*a*atanh(x/a) + x*log(-a**2 + x**2) - 2*x,
    ),
    RubiTestSuiteCase(
        integrand=log(log(log(log(x)))),
        variable=x,
        num_steps=0,
        integral=sympy.Function('CannotIntegrate')(sympy.log(sympy.log(sympy.log(sympy.log(x)))), x),
    ),
    RubiTestSuiteCase(
        integrand=sin(x),
        variable=x,
        num_steps=1,
        integral=-cos(x),
    ),
    RubiTestSuiteCase(
        integrand=cos(x),
        variable=x,
        num_steps=1,
        integral=sin(x),
    ),
    RubiTestSuiteCase(
        integrand=tan(x),
        variable=x,
        num_steps=1,
        integral=-log(cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/tan(x),
        variable=x,
        num_steps=1,
        integral=log(sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=(tan(x) + 1)**(-2),
        variable=x,
        num_steps=2,
        integral=log(sin(x) + cos(x))/2 - 1/(2*tan(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=1/cos(x),
        variable=x,
        num_steps=1,
        integral=atanh(sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/sin(x),
        variable=x,
        num_steps=1,
        integral=-atanh(cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2,
        variable=x,
        num_steps=2,
        integral=x/2 - sin(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=x**3*sin(x**2),
        variable=x,
        num_steps=3,
        integral=-x**2*cos(x**2)/2 + sin(x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3,
        variable=x,
        num_steps=2,
        integral=cos(x)**3/3 - cos(x),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**p,
        variable=x,
        num_steps=1,
        integral=sin(x)**(p + 1)*cos(x)*hyper((sympy.S.Half, p/2 + sympy.S.Half), (p/2 + sympy.S(3)/2,), sin(x)**2)/((p + 1)*sqrt(cos(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(sin(x)**2 + 1)**2*cos(x),
        variable=x,
        num_steps=3,
        integral=sin(x)**5/5 + 2*sin(x)**3/3 + sin(x),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**2,
        variable=x,
        num_steps=2,
        integral=x/2 + sin(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**3,
        variable=x,
        num_steps=2,
        integral=-sin(x)**3/3 + sin(x),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**(-2),
        variable=x,
        num_steps=2,
        integral=tan(x),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)*sin(2*x),
        variable=x,
        num_steps=1,
        integral=sin(x)/2 - sin(3*x)/6,
    ),
    RubiTestSuiteCase(
        integrand=x*sin(x),
        variable=x,
        num_steps=2,
        integral=-x*cos(x) + sin(x),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sin(x),
        variable=x,
        num_steps=3,
        integral=-x**2*cos(x) + 2*x*sin(x) + 2*cos(x),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(x)**2,
        variable=x,
        num_steps=2,
        integral=x**2/4 - x*sin(x)*cos(x)/2 + sin(x)**2/4,
    ),
    RubiTestSuiteCase(
        integrand=x**2*sin(x)**2,
        variable=x,
        num_steps=4,
        integral=x**3/6 - x**2*sin(x)*cos(x)/2 + x*sin(x)**2/2 - x/4 + sin(x)*cos(x)/4,
    ),
    RubiTestSuiteCase(
        integrand=x*sin(x)**3,
        variable=x,
        num_steps=3,
        integral=-x*sin(x)**2*cos(x)/3 - 2*x*cos(x)/3 + sin(x)**3/9 + 2*sin(x)/3,
    ),
    RubiTestSuiteCase(
        integrand=x*cos(x),
        variable=x,
        num_steps=2,
        integral=x*sin(x) + cos(x),
    ),
    RubiTestSuiteCase(
        integrand=x**2*cos(x),
        variable=x,
        num_steps=3,
        integral=x**2*sin(x) + 2*x*cos(x) - 2*sin(x),
    ),
    RubiTestSuiteCase(
        integrand=x*cos(x)**2,
        variable=x,
        num_steps=2,
        integral=x**2/4 + x*sin(x)*cos(x)/2 + cos(x)**2/4,
    ),
    RubiTestSuiteCase(
        integrand=x**2*cos(x)**2,
        variable=x,
        num_steps=4,
        integral=x**3/6 + x**2*sin(x)*cos(x)/2 + x*cos(x)**2/2 - x/4 - sin(x)*cos(x)/4,
    ),
    RubiTestSuiteCase(
        integrand=x*cos(x)**3,
        variable=x,
        num_steps=3,
        integral=x*sin(x)*cos(x)**2/3 + 2*x*sin(x)/3 + cos(x)**3/9 + 2*cos(x)/3,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/x,
        variable=x,
        num_steps=1,
        integral=sympy.Function('SinIntegral')(x),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)/x,
        variable=x,
        num_steps=1,
        integral=sympy.Function('CosIntegral')(x),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/x**2,
        variable=x,
        num_steps=2,
        integral=(sympy.Function('CosIntegral')(x) + (Integer(-1) * (sympy.sin(x) * (x)**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2/x,
        variable=x,
        num_steps=3,
        integral=(((Integer(-1) * (Integer(2))**(Integer(-1))) * sympy.Function('CosIntegral')((Integer(2) * x))) + (sympy.log(x) * (Integer(2))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**3,
        variable=x,
        num_steps=2,
        integral=log(cos(x)) + tan(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x),
        variable=x,
        num_steps=1,
        integral=-cos(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x),
        variable=x,
        num_steps=1,
        integral=sin(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=tan(a + b*x),
        variable=x,
        num_steps=1,
        integral=-log(cos(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=1/tan(a + b*x),
        variable=x,
        num_steps=1,
        integral=log(sin(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=1/sin(a + b*x),
        variable=x,
        num_steps=1,
        integral=-atanh(cos(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=1/cos(a + b*x),
        variable=x,
        num_steps=1,
        integral=atanh(sin(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**2,
        variable=x,
        num_steps=2,
        integral=x/2 - sin(a + b*x)*cos(a + b*x)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + b*x)**3,
        variable=x,
        num_steps=2,
        integral=cos(a + b*x)**3/(3*b) - cos(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2,
        variable=x,
        num_steps=2,
        integral=x/2 + sin(a + b*x)*cos(a + b*x)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3,
        variable=x,
        num_steps=2,
        integral=-sin(a + b*x)**3/(3*b) + sin(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**(-2),
        variable=x,
        num_steps=2,
        integral=tan(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=1/(cos(x) + 1),
        variable=x,
        num_steps=1,
        integral=sin(x)/(cos(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/(1 - cos(x)),
        variable=x,
        num_steps=1,
        integral=-sin(x)/(1 - cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(sin(x) + 1),
        variable=x,
        num_steps=1,
        integral=-cos(x)/(sin(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/(1 - sin(x)),
        variable=x,
        num_steps=1,
        integral=cos(x)/(1 - sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*sin(x)),
        variable=x,
        num_steps=3,
        integral=2*atan((a*tan(x/2) + b)/sqrt(a**2 - b**2))/sqrt(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*sin(x) + cos(x)),
        variable=x,
        num_steps=3,
        integral=-2*atanh((b - (1 - a)*tan(x/2))/sqrt(-a**2 + b**2 + 1))/sqrt(-a**2 + b**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sin(a + b*x)**2,
        variable=x,
        num_steps=4,
        integral=x**3/6 - x**2*sin(a + b*x)*cos(a + b*x)/(2*b) + x*sin(a + b*x)**2/(2*b**2) - x/(4*b**2) + sin(a + b*x)*cos(a + b*x)/(4*b**3),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)*cos(2*x),
        variable=x,
        num_steps=1,
        integral=sin(x)/2 + sin(3*x)/6,
    ),
    RubiTestSuiteCase(
        integrand=x**2*cos(a + b*x)**2,
        variable=x,
        num_steps=4,
        integral=x**3/6 + x**2*sin(a + b*x)*cos(a + b*x)/(2*b) + x*cos(a + b*x)**2/(2*b**2) - x/(4*b**2) - sin(a + b*x)*cos(a + b*x)/(4*b**3),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**(-3),
        variable=x,
        num_steps=2,
        integral=-log(sin(x)) - cot(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=x**3*tan(x)**4,
        variable=x,
        num_steps=17,
        integral=((Integer(-1) * ((x)**(Integer(2)) * (Integer(2))**(Integer(-1)))) + ((Integer(4) * sympy.I * (x)**(Integer(3))) * (Integer(3))**(Integer(-1))) + ((x)**(Integer(4)) * (Integer(4))**(Integer(-1))) + (Integer(-1) * (Integer(4) * (x)**(Integer(2)) * sympy.log((Integer(1) + (sympy.E)**((Integer(2) * sympy.I * x)))))) + sympy.log(sympy.cos(x)) + (Integer(4) * sympy.I * x * sympy.Function('PolyLog')(Integer(2), (Integer(-1) * (sympy.E)**((Integer(2) * sympy.I * x))))) + (Integer(-1) * (Integer(2) * sympy.Function('PolyLog')(Integer(3), (Integer(-1) * (sympy.E)**((Integer(2) * sympy.I * x)))))) + (x * sympy.tan(x)) + (Integer(-1) * ((x)**(Integer(3)) * sympy.tan(x))) + (Integer(-1) * ((Integer(2))**(Integer(-1)) * (x)**(Integer(2)) * (sympy.tan(x))**(Integer(2)))) + ((Integer(3))**(Integer(-1)) * (x)**(Integer(3)) * (sympy.tan(x))**(Integer(3)))),
    ),
    RubiTestSuiteCase(
        integrand=x**3*tan(x)**6,
        variable=x,
        num_steps=34,
        integral=(((Integer(19) * (x)**(Integer(2))) * (Integer(20))**(Integer(-1))) + (Integer(-1) * ((Integer(23) * sympy.I * (x)**(Integer(3))) * (Integer(15))**(Integer(-1)))) + (Integer(-1) * ((x)**(Integer(4)) * (Integer(4))**(Integer(-1)))) + ((Integer(23) * (Integer(5))**(Integer(-1))) * (x)**(Integer(2)) * sympy.log((Integer(1) + (sympy.E)**((Integer(2) * sympy.I * x))))) + (Integer(-1) * (Integer(2) * sympy.log(sympy.cos(x)))) + (Integer(-1) * ((Integer(23) * (Integer(5))**(Integer(-1))) * sympy.I * x * sympy.Function('PolyLog')(Integer(2), (Integer(-1) * (sympy.E)**((Integer(2) * sympy.I * x)))))) + ((Integer(23) * (Integer(10))**(Integer(-1))) * sympy.Function('PolyLog')(Integer(3), (Integer(-1) * (sympy.E)**((Integer(2) * sympy.I * x))))) + (Integer(-1) * ((Integer(19) * (Integer(10))**(Integer(-1))) * x * sympy.tan(x))) + ((x)**(Integer(3)) * sympy.tan(x)) + (Integer(-1) * ((sympy.tan(x))**(Integer(2)) * (Integer(20))**(Integer(-1)))) + ((Integer(4) * (Integer(5))**(Integer(-1))) * (x)**(Integer(2)) * (sympy.tan(x))**(Integer(2))) + ((Integer(10))**(Integer(-1)) * x * (sympy.tan(x))**(Integer(3))) + (Integer(-1) * ((Integer(3))**(Integer(-1)) * (x)**(Integer(3)) * (sympy.tan(x))**(Integer(3)))) + (Integer(-1) * ((Integer(3) * (Integer(20))**(Integer(-1))) * (x)**(Integer(2)) * (sympy.tan(x))**(Integer(4)))) + ((Integer(5))**(Integer(-1)) * (x)**(Integer(3)) * (sympy.tan(x))**(Integer(5)))),
    ),
    RubiTestSuiteCase(
        integrand=x*tan(x)**2,
        variable=x,
        num_steps=3,
        integral=-x**2/2 + x*tan(x) + log(cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*x)*cos(3*x),
        variable=x,
        num_steps=1,
        integral=cos(x)/2 - cos(5*x)/10,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2*cos(x)**2,
        variable=x,
        num_steps=3,
        integral=x/8 - sin(x)*cos(x)**3/4 + sin(x)*cos(x)/8,
    ),
    RubiTestSuiteCase(
        integrand=1/(sin(x)**2*cos(x)**2),
        variable=x,
        num_steps=3,
        integral=tan(x) - cot(x),
    ),
    RubiTestSuiteCase(
        integrand=d**x*sin(x),
        variable=x,
        num_steps=1,
        integral=d**x*log(d)*sin(x)/(log(d)**2 + 1) - d**x*cos(x)/(log(d)**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=d**x*cos(x),
        variable=x,
        num_steps=1,
        integral=d**x*log(d)*cos(x)/(log(d)**2 + 1) + d**x*sin(x)/(log(d)**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=d**x*x*sin(x),
        variable=x,
        num_steps=4,
        integral=d**x*x*log(d)*sin(x)/(log(d)**2 + 1) - d**x*x*cos(x)/(log(d)**2 + 1) - d**x*log(d)**2*sin(x)/(log(d)**2 + 1)**2 + 2*d**x*log(d)*cos(x)/(log(d)**2 + 1)**2 + d**x*sin(x)/(log(d)**2 + 1)**2,
    ),
    RubiTestSuiteCase(
        integrand=d**x*x*cos(x),
        variable=x,
        num_steps=4,
        integral=d**x*x*log(d)*cos(x)/(log(d)**2 + 1) + d**x*x*sin(x)/(log(d)**2 + 1) - d**x*log(d)**2*cos(x)/(log(d)**2 + 1)**2 - 2*d**x*log(d)*sin(x)/(log(d)**2 + 1)**2 + d**x*cos(x)/(log(d)**2 + 1)**2,
    ),
    RubiTestSuiteCase(
        integrand=d**x*x**2*sin(x),
        variable=x,
        num_steps=11,
        integral=d**x*x**2*log(d)*sin(x)/(log(d)**2 + 1) - d**x*x**2*cos(x)/(log(d)**2 + 1) - 2*d**x*x*log(d)**2*sin(x)/(log(d)**2 + 1)**2 + 4*d**x*x*log(d)*cos(x)/(log(d)**2 + 1)**2 + 2*d**x*x*sin(x)/(log(d)**2 + 1)**2 + 2*d**x*log(d)**3*sin(x)/(log(d)**2 + 1)**3 - 6*d**x*log(d)**2*cos(x)/(log(d)**2 + 1)**3 - 6*d**x*log(d)*sin(x)/(log(d)**2 + 1)**3 + 2*d**x*cos(x)/(log(d)**2 + 1)**3,
    ),
    RubiTestSuiteCase(
        integrand=d**x*x**2*cos(x),
        variable=x,
        num_steps=11,
        integral=d**x*x**2*log(d)*cos(x)/(log(d)**2 + 1) + d**x*x**2*sin(x)/(log(d)**2 + 1) - 2*d**x*x*log(d)**2*cos(x)/(log(d)**2 + 1)**2 - 4*d**x*x*log(d)*sin(x)/(log(d)**2 + 1)**2 + 2*d**x*x*cos(x)/(log(d)**2 + 1)**2 + 2*d**x*log(d)**3*cos(x)/(log(d)**2 + 1)**3 + 6*d**x*log(d)**2*sin(x)/(log(d)**2 + 1)**3 - 6*d**x*log(d)*cos(x)/(log(d)**2 + 1)**3 - 2*d**x*sin(x)/(log(d)**2 + 1)**3,
    ),
    RubiTestSuiteCase(
        integrand=d**x*x**3*sin(x),
        variable=x,
        num_steps=25,
        integral=d**x*x**3*log(d)*sin(x)/(log(d)**2 + 1) - d**x*x**3*cos(x)/(log(d)**2 + 1) - 3*d**x*x**2*log(d)**2*sin(x)/(log(d)**2 + 1)**2 + 6*d**x*x**2*log(d)*cos(x)/(log(d)**2 + 1)**2 + 3*d**x*x**2*sin(x)/(log(d)**2 + 1)**2 + 6*d**x*x*log(d)**3*sin(x)/(log(d)**2 + 1)**3 - 18*d**x*x*log(d)**2*cos(x)/(log(d)**2 + 1)**3 - 18*d**x*x*log(d)*sin(x)/(log(d)**2 + 1)**3 + 6*d**x*x*cos(x)/(log(d)**2 + 1)**3 - 6*d**x*log(d)**4*sin(x)/(log(d)**2 + 1)**4 + 24*d**x*log(d)**3*cos(x)/(log(d)**2 + 1)**4 + 36*d**x*log(d)**2*sin(x)/(log(d)**2 + 1)**4 - 24*d**x*log(d)*cos(x)/(log(d)**2 + 1)**4 - 6*d**x*sin(x)/(log(d)**2 + 1)**4,
    ),
    RubiTestSuiteCase(
        integrand=d**x*x**3*cos(x),
        variable=x,
        num_steps=25,
        integral=d**x*x**3*log(d)*cos(x)/(log(d)**2 + 1) + d**x*x**3*sin(x)/(log(d)**2 + 1) - 3*d**x*x**2*log(d)**2*cos(x)/(log(d)**2 + 1)**2 - 6*d**x*x**2*log(d)*sin(x)/(log(d)**2 + 1)**2 + 3*d**x*x**2*cos(x)/(log(d)**2 + 1)**2 + 6*d**x*x*log(d)**3*cos(x)/(log(d)**2 + 1)**3 + 18*d**x*x*log(d)**2*sin(x)/(log(d)**2 + 1)**3 - 18*d**x*x*log(d)*cos(x)/(log(d)**2 + 1)**3 - 6*d**x*x*sin(x)/(log(d)**2 + 1)**3 - 6*d**x*log(d)**4*cos(x)/(log(d)**2 + 1)**4 - 24*d**x*log(d)**3*sin(x)/(log(d)**2 + 1)**4 + 36*d**x*log(d)**2*cos(x)/(log(d)**2 + 1)**4 + 24*d**x*log(d)*sin(x)/(log(d)**2 + 1)**4 - 6*d**x*cos(x)/(log(d)**2 + 1)**4,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)*sin(2*x)*sin(3*x),
        variable=x,
        num_steps=5,
        integral=-cos(2*x)/8 - cos(4*x)/16 + cos(6*x)/24,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)*cos(2*x)*cos(3*x),
        variable=x,
        num_steps=5,
        integral=x/4 + sin(2*x)/8 + sin(4*x)/16 + sin(6*x)/24,
    ),
    RubiTestSuiteCase(
        integrand=x**2*sin(k*x)**3,
        variable=x,
        num_steps=6,
        integral=-x**2*sin(k*x)**2*cos(k*x)/(3*k) - 2*x**2*cos(k*x)/(3*k) + 2*x*sin(k*x)**3/(9*k**2) + 4*x*sin(k*x)/(3*k**2) - 2*cos(k*x)**3/(27*k**3) + 14*cos(k*x)/(9*k**3),
    ),
    RubiTestSuiteCase(
        integrand=x*cos(x)*cos(k/sin(x))/sin(x)**2,
        variable=x,
        num_steps=0,
        integral=sympy.Function('CannotIntegrate')((x * sympy.cos((Symbol('k') * sympy.csc(x))) * sympy.cot(x) * sympy.csc(x)), x),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)/(sin(x)*tan(x/2)),
        variable=x,
        num_steps=4,
        integral=-x - cot(x/2),
    ),
    RubiTestSuiteCase(
        integrand=sin(a*x)/(b + c*sin(a*x))**2,
        variable=x,
        num_steps=5,
        integral=-b*cos(a*x)/(a*(b + c*sin(a*x))*(b**2 - c**2)) - 2*c*atan((b*tan(a*x/2) + c)/sqrt(b**2 - c**2))/(a*(b**2 - c**2)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(log(x)),
        variable=x,
        num_steps=1,
        integral=x*sin(log(x))/2 - x*cos(log(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=cos(log(x)),
        variable=x,
        num_steps=1,
        integral=x*sin(log(x))/2 + x*cos(log(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=exp(x),
        variable=x,
        num_steps=1,
        integral=exp(x),
    ),
    RubiTestSuiteCase(
        integrand=a**x,
        variable=x,
        num_steps=1,
        integral=a**x/log(a),
    ),
    RubiTestSuiteCase(
        integrand=exp(a*x),
        variable=x,
        num_steps=1,
        integral=exp(a*x)/a,
    ),
    RubiTestSuiteCase(
        integrand=exp(a*x)/x,
        variable=x,
        num_steps=1,
        integral=sympy.Function('ExpIntegralEi')((Symbol('a') * x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*exp(m*x)),
        variable=x,
        num_steps=4,
        integral=x/a - log(a + b*exp(m*x))/(a*m),
    ),
    RubiTestSuiteCase(
        integrand=exp(2*x)/(exp(x) + 1),
        variable=x,
        num_steps=3,
        integral=exp(x) - log(exp(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=exp(2*x)*exp(a*x),
        variable=x,
        num_steps=2,
        integral=exp(x*(a + 2))/(a + 2),
    ),
    RubiTestSuiteCase(
        integrand=1/(a*exp(m*x) + b*exp(-m*x)),
        variable=x,
        num_steps=2,
        integral=atan(sqrt(a)*exp(m*x)/sqrt(b))/(sqrt(a)*sqrt(b)*m),
    ),
    RubiTestSuiteCase(
        integrand=x*exp(a*x),
        variable=x,
        num_steps=2,
        integral=x*exp(a*x)/a - exp(a*x)/a**2,
    ),
    RubiTestSuiteCase(
        integrand=x**20*exp(x),
        variable=x,
        num_steps=21,
        integral=x**20*exp(x) - 20*x**19*exp(x) + 380*x**18*exp(x) - 6840*x**17*exp(x) + 116280*x**16*exp(x) - 1860480*x**15*exp(x) + 27907200*x**14*exp(x) - 390700800*x**13*exp(x) + 5079110400*x**12*exp(x) - 60949324800*x**11*exp(x) + 670442572800*x**10*exp(x) - 6704425728000*x**9*exp(x) + 60339831552000*x**8*exp(x) - 482718652416000*x**7*exp(x) + 3379030566912000*x**6*exp(x) - 20274183401472000*x**5*exp(x) + 101370917007360000*x**4*exp(x) - 405483668029440000*x**3*exp(x) + 1216451004088320000*x**2*exp(x) - 2432902008176640000*x*exp(x) + 2432902008176640000*exp(x),
    ),
    RubiTestSuiteCase(
        integrand=a**x/b**x,
        variable=x,
        num_steps=2,
        integral=a**x/(b**x*(log(a) - log(b))),
    ),
    RubiTestSuiteCase(
        integrand=a**x*b**x,
        variable=x,
        num_steps=2,
        integral=a**x*b**x/(log(a) + log(b)),
    ),
    RubiTestSuiteCase(
        integrand=a**x/x**2,
        variable=x,
        num_steps=2,
        integral=((Integer(-1) * ((Symbol('a'))**(x) * (x)**(Integer(-1)))) + (sympy.Function('ExpIntegralEi')((x * sympy.log(Symbol('a')))) * sympy.log(Symbol('a')))),
    ),
    RubiTestSuiteCase(
        integrand=a**x*x/(b*x + 1)**2,
        variable=x,
        num_steps=5,
        integral=(((Symbol('a'))**(x) * (((Symbol('b'))**(Integer(2)) * (Integer(1) + (Symbol('b') * x))))**(Integer(-1))) + (sympy.Function('ExpIntegralEi')((((Integer(1) + (Symbol('b') * x)) * sympy.log(Symbol('a'))) * (Symbol('b'))**(Integer(-1)))) * (((Symbol('a'))**((Symbol('b'))**(Integer(-1))) * (Symbol('b'))**(Integer(2))))**(Integer(-1))) + (Integer(-1) * ((sympy.Function('ExpIntegralEi')((((Integer(1) + (Symbol('b') * x)) * sympy.log(Symbol('a'))) * (Symbol('b'))**(Integer(-1)))) * sympy.log(Symbol('a'))) * (((Symbol('a'))**((Symbol('b'))**(Integer(-1))) * (Symbol('b'))**(Integer(3))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x*exp(a*x)/(a*x + 1)**2,
        variable=x,
        num_steps=1,
        integral=exp(a*x)/(a**2*(a*x + 1)),
    ),
    RubiTestSuiteCase(
        integrand=k**(x**2)*x,
        variable=x,
        num_steps=1,
        integral=k**(x**2)/(2*log(k)),
    ),
    RubiTestSuiteCase(
        integrand=exp(x**2),
        variable=x,
        num_steps=1,
        integral=((Integer(2))**(Integer(-1)) * sympy.sqrt(sympy.pi) * sympy.Function('Erfi')(x)),
    ),
    RubiTestSuiteCase(
        integrand=x*exp(x**2),
        variable=x,
        num_steps=1,
        integral=exp(x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=(x + 1)*exp(1/x)/x**4,
        variable=x,
        num_steps=7,
        integral=-exp(1/x) + exp(1/x)/x - exp(1/x)/x**2,
    ),
    RubiTestSuiteCase(
        integrand=(2*x**3 + x)*exp(2*x**2)*exp(-x*exp(x**2) + 1)/(-x*exp(x**2) + 1)**2,
        variable=x,
        num_steps=-3,
        integral=-exp(-x*exp(x**2) + 1)/(x*exp(x**2) - 1),
    ),
    RubiTestSuiteCase(
        integrand=exp(exp(exp(exp(x)))),
        variable=x,
        num_steps=1,
        integral=sympy.Function('CannotIntegrate')((sympy.E)**((sympy.E)**((sympy.E)**((sympy.E)**(x)))), x),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*log(x),
        variable=x,
        num_steps=2,
        integral=((Integer(-1) * sympy.Function('ExpIntegralEi')(x)) + ((sympy.E)**(x) * sympy.log(x))),
    ),
    RubiTestSuiteCase(
        integrand=x*exp(x)*log(x),
        variable=x,
        num_steps=5,
        integral=((Integer(-1) * (sympy.E)**(x)) + sympy.Function('ExpIntegralEi')(x) + (Integer(-1) * ((sympy.E)**(x) * sympy.log(x))) + ((sympy.E)**(x) * x * sympy.log(x))),
    ),
    RubiTestSuiteCase(
        integrand=exp(2*x)*log(exp(x)),
        variable=x,
        num_steps=3,
        integral=exp(2*x)*log(exp(x))/2 - exp(2*x)/4,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(2)*x**2 + 2*x,
        variable=x,
        num_steps=1,
        integral=sqrt(2)*x**3/3 + x**2,
    ),
    RubiTestSuiteCase(
        integrand=log(x)/sqrt(a*x + b),
        variable=x,
        num_steps=4,
        integral=4*sqrt(b)*atanh(sqrt(a*x + b)/sqrt(b))/a + 2*sqrt(a*x + b)*log(x)/a - 4*sqrt(a*x + b)/a,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*x)*sqrt(c + d*x),
        variable=x,
        num_steps=5,
        integral=(a + b*x)**(sympy.S(3)/2)*sqrt(c + d*x)/(2*b) + sqrt(a + b*x)*sqrt(c + d*x)*(-a*d + b*c)/(4*b*d) - (-a*d + b*c)**2*atanh(sqrt(d)*sqrt(a + b*x)/(sqrt(b)*sqrt(c + d*x)))/(4*b**(sympy.S(3)/2)*d**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*x),
        variable=x,
        num_steps=1,
        integral=2*(a + b*x)**(sympy.S(3)/2)/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=x*sqrt(a + b*x),
        variable=x,
        num_steps=2,
        integral=-2*a*(a + b*x)**(sympy.S(3)/2)/(3*b**2) + 2*(a + b*x)**(sympy.S(5)/2)/(5*b**2),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sqrt(a + b*x),
        variable=x,
        num_steps=2,
        integral=2*a**2*(a + b*x)**(sympy.S(3)/2)/(3*b**3) - 4*a*(a + b*x)**(sympy.S(5)/2)/(5*b**3) + 2*(a + b*x)**(sympy.S(7)/2)/(7*b**3),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*x)/x,
        variable=x,
        num_steps=3,
        integral=-2*sqrt(a)*atanh(sqrt(a + b*x)/sqrt(a)) + 2*sqrt(a + b*x),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*x)/x**2,
        variable=x,
        num_steps=3,
        integral=-sqrt(a + b*x)/x - b*atanh(sqrt(a + b*x)/sqrt(a))/sqrt(a),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a + b*x),
        variable=x,
        num_steps=1,
        integral=2*sqrt(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(a + b*x),
        variable=x,
        num_steps=2,
        integral=-2*a*sqrt(a + b*x)/b**2 + 2*(a + b*x)**(sympy.S(3)/2)/(3*b**2),
    ),
    RubiTestSuiteCase(
        integrand=x**2/sqrt(a + b*x),
        variable=x,
        num_steps=2,
        integral=2*a**2*sqrt(a + b*x)/b**3 - 4*a*(a + b*x)**(sympy.S(3)/2)/(3*b**3) + 2*(a + b*x)**(sympy.S(5)/2)/(5*b**3),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(a + b*x)),
        variable=x,
        num_steps=2,
        integral=-2*atanh(sqrt(a + b*x)/sqrt(a))/sqrt(a),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*sqrt(a + b*x)),
        variable=x,
        num_steps=3,
        integral=-sqrt(a + b*x)/(a*x) + b*atanh(sqrt(a + b*x)/sqrt(a))/a**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*x)**(p/2),
        variable=x,
        num_steps=1,
        integral=2*(a + b*x)**(p/2 + 1)/(b*(p + 2)),
    ),
    RubiTestSuiteCase(
        integrand=x*(a + b*x)**(p/2),
        variable=x,
        num_steps=2,
        integral=-2*a*(a + b*x)**(p/2 + 1)/(b**2*(p + 2)) + 2*(a + b*x)**(p/2 + 2)/(b**2*(p + 4)),
    ),
    RubiTestSuiteCase(
        integrand=atan(sqrt(2)*(2*x - sqrt(2))/2),
        variable=x,
        num_steps=6,
        integral=x*atan(sqrt(2)*x - 1) - sqrt(2)*log(x**2 - sqrt(2)*x + 1)/4 - sqrt(2)*atan(sqrt(2)*x - 1)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(x**2 - 1),
        variable=x,
        num_steps=2,
        integral=atanh(x/sqrt(x**2 - 1)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x)*sqrt(x + 1),
        variable=x,
        num_steps=4,
        integral=x**(sympy.S(3)/2)*sqrt(x + 1)/2 + sqrt(x)*sqrt(x + 1)/4 - asinh(sqrt(x))/4,
    ),
    RubiTestSuiteCase(
        integrand=sin(sqrt(x)),
        variable=x,
        num_steps=3,
        integral=-2*sqrt(x)*cos(sqrt(x)) + 2*sin(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=x/(1 - x**2)**(sympy.S(9)/8),
        variable=x,
        num_steps=1,
        integral=4/(1 - x**2)**(sympy.S(1)/8),
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(1 - x**4),
        variable=x,
        num_steps=2,
        integral=asin(x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(x**4 + 1)),
        variable=x,
        num_steps=3,
        integral=-atanh(sqrt(x**4 + 1))/2,
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(x**4 + x**2 + 1),
        variable=x,
        num_steps=3,
        integral=asinh(sqrt(3)*(2*x**2 + 1)/3)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(-x**4 + x**2 - 1)),
        variable=x,
        num_steps=3,
        integral=-atan((2 - x**2)/(2*sqrt(-x**4 + x**2 - 1)))/2,
    ),
    RubiTestSuiteCase(
        integrand=(x + 1)/((1 - x)**2*sqrt(x**2 + 1)),
        variable=x,
        num_steps=1,
        integral=sqrt(x**2 + 1)/(1 - x),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(x**2 + 1),
        variable=x,
        num_steps=1,
        integral=asinh(x),
    ),
    RubiTestSuiteCase(
        integrand=(sqrt(x)*sqrt(x + 1) + sqrt(x)*sqrt(x + 2) + sqrt(x + 1)*sqrt(x + 2))/(2*sqrt(x)*sqrt(x + 1)*sqrt(x + 2)),
        variable=x,
        num_steps=3,
        integral=sqrt(x) + sqrt(x + 1) + sqrt(x + 2),
    ),
    RubiTestSuiteCase(
        integrand=(5*x**4*sqrt(x**3 + 1) - 3*x**2*sqrt(x**5 - 2*x + 1) - 2*sqrt(x**3 + 1))/(2*sqrt(x**3 + 1)*sqrt(x**5 - 2*x + 1)),
        variable=x,
        num_steps=5,
        integral=-sqrt(x**3 + 1) + sqrt(x**5 - 2*x + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(x**2 - 1) + 10/sqrt(x**2 - 4),
        variable=x,
        num_steps=5,
        integral=10*atanh(x/sqrt(x**2 - 4)) + atanh(x/sqrt(x**2 - 1)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x + sqrt(a**2 + x**2))/x,
        variable=x,
        num_steps=6,
        integral=-2*sqrt(a)*atan(sqrt(x + sqrt(a**2 + x**2))/sqrt(a)) - 2*sqrt(a)*atanh(sqrt(x + sqrt(a**2 + x**2))/sqrt(a)) + 2*sqrt(x + sqrt(a**2 + x**2)),
    ),
    RubiTestSuiteCase(
        integrand=3*x**2/(2*x**3 + 2*sqrt(x**3 + 1) + 2),
        variable=x,
        num_steps=4,
        integral=log(sqrt(x**3 + 1) + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-alpha**2 + 2*h*r**2),
        variable=r,
        num_steps=2,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(h)*r/sqrt(-alpha**2 + 2*h*r**2))/(2*sqrt(h)),
    ),
    RubiTestSuiteCase(
        integrand=1/(r*sqrt(-alpha**2 - epsilon**2 + 2*h*r**2)),
        variable=r,
        num_steps=3,
        integral=atan(sqrt(-alpha**2 - epsilon**2 + 2*h*r**2)/sqrt(alpha**2 + epsilon**2))/sqrt(alpha**2 + epsilon**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(r*sqrt(-alpha**2 + 2*h*r**2 - 2*k*r)),
        variable=r,
        num_steps=2,
        integral=-atan((alpha**2 + k*r)/(alpha*sqrt(-alpha**2 + 2*h*r**2 - 2*k*r)))/alpha,
    ),
    RubiTestSuiteCase(
        integrand=1/(r*sqrt(-alpha**2 - epsilon**2 + 2*h*r**2 - 2*k*r)),
        variable=r,
        num_steps=2,
        integral=-atan((alpha**2 + epsilon**2 + k*r)/(sqrt(alpha**2 + epsilon**2)*sqrt(-alpha**2 - epsilon**2 + 2*h*r**2 - 2*k*r)))/sqrt(alpha**2 + epsilon**2),
    ),
    RubiTestSuiteCase(
        integrand=r/sqrt(-alpha**2 + 2*e*r**2),
        variable=r,
        num_steps=1,
        integral=sqrt(-alpha**2 + 2*e*r**2)/(2*e),
    ),
    RubiTestSuiteCase(
        integrand=r/sqrt(-alpha**2 + 2*e*r**2 - epsilon**2),
        variable=r,
        num_steps=1,
        integral=sqrt(-alpha**2 + 2*e*r**2 - epsilon**2)/(2*e),
    ),
    RubiTestSuiteCase(
        integrand=r/sqrt(-alpha**2 + 2*e*r**2 - 2*k*r**4),
        variable=r,
        num_steps=3,
        integral=-sqrt(2)*atan(sqrt(2)*(e - 2*k*r**2)/(2*sqrt(k)*sqrt(-alpha**2 + 2*e*r**2 - 2*k*r**4)))/(4*sqrt(k)),
    ),
    RubiTestSuiteCase(
        integrand=r/sqrt(-alpha**2 + 2*e*r**2 - 2*k*r),
        variable=r,
        num_steps=3,
        integral=sqrt(-alpha**2 + 2*e*r**2 - 2*k*r)/(2*e) - sqrt(2)*k*atanh(sqrt(2)*(-2*e*r + k)/(2*sqrt(e)*sqrt(-alpha**2 + 2*e*r**2 - 2*k*r)))/(4*e**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(r*sqrt(-alpha**2 + 2*h*r**2 - 2*k*r**4)),
        variable=r,
        num_steps=3,
        integral=-atan((alpha**2 - h*r**2)/(alpha*sqrt(-alpha**2 + 2*h*r**2 - 2*k*r**4)))/(2*alpha),
    ),
    RubiTestSuiteCase(
        integrand=1/(r*sqrt(-alpha**2 - epsilon**2 + 2*h*r**2 - 2*k*r**4)),
        variable=r,
        num_steps=3,
        integral=-atan((alpha**2 + epsilon**2 - h*r**2)/(sqrt(alpha**2 + epsilon**2)*sqrt(-alpha**2 - epsilon**2 + 2*h*r**2 - 2*k*r**4)))/(2*sqrt(alpha**2 + epsilon**2)),
    ),
    RubiTestSuiteCase(
        integrand=a*sin(3*x + 5)**2*cos(3*x + 5),
        variable=x,
        num_steps=3,
        integral=a*sin(3*x + 5)**3/9,
    ),
    RubiTestSuiteCase(
        integrand=log(x**2)/x**3,
        variable=x,
        num_steps=1,
        integral=-log(x**2)/(2*x**2) - 1/(2*x**2),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(a + x),
        variable=x,
        num_steps=2,
        integral=-x*cos(a + x) + sin(a + x),
    ),
    RubiTestSuiteCase(
        integrand=((1 - x)*log(x) - 1)*exp(-x)/log(x)**2,
        variable=x,
        num_steps=1,
        integral=x*exp(-x)/log(x),
    ),
    RubiTestSuiteCase(
        integrand=x**3/(a*x**2 + b),
        variable=x,
        num_steps=3,
        integral=x**2/(2*a) - b*log(a*x**2 + b)/(2*a**2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x)/(x + 1)**(sympy.S(7)/2),
        variable=x,
        num_steps=2,
        integral=4*x**(sympy.S(3)/2)/(15*(x + 1)**(sympy.S(3)/2)) + 2*x**(sympy.S(3)/2)/(5*(x + 1)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*(x + 1)),
        variable=x,
        num_steps=3,
        integral=log(x) - log(x + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(x)*(2*x - 1)),
        variable=x,
        num_steps=2,
        integral=-sqrt(2)*atanh(sqrt(2)*sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x)*(x**2 + 1),
        variable=x,
        num_steps=2,
        integral=2*x**(sympy.S(7)/2)/7 + 2*x**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=(-a + x)**(sympy.S(1)/3)/x,
        variable=x,
        num_steps=5,
        integral=a**(sympy.S(1)/3)*log(x)/2 - 3*a**(sympy.S(1)/3)*log(a**(sympy.S(1)/3) + (-a + x)**(sympy.S(1)/3))/2 + sqrt(3)*a**(sympy.S(1)/3)*atan(sqrt(3)*(a**(sympy.S(1)/3) - 2*(-a + x)**(sympy.S(1)/3))/(3*a**(sympy.S(1)/3))) + 3*(-a + x)**(sympy.S(1)/3),
    ),
    RubiTestSuiteCase(
        integrand=x*sinh(x),
        variable=x,
        num_steps=2,
        integral=x*cosh(x) - sinh(x),
    ),
    RubiTestSuiteCase(
        integrand=x*cosh(x),
        variable=x,
        num_steps=2,
        integral=x*sinh(x) - cosh(x),
    ),
    RubiTestSuiteCase(
        integrand=sinh(2*x)/cosh(2*x),
        variable=x,
        num_steps=1,
        integral=log(cosh(2*x))/2,
    ),
    RubiTestSuiteCase(
        integrand=(I*eps*sinh(x) - 1)/(I*a + I*eps*cosh(x) - x),
        variable=x,
        num_steps=1,
        integral=log(a + eps*cosh(x) + I*x),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*x + 3)*cos(x)**2,
        variable=x,
        num_steps=4,
        integral=x*sin(3)/4 - cos(2*x + 3)/4 - cos(4*x + 3)/16,
    ),
    RubiTestSuiteCase(
        integrand=x*atan(x),
        variable=x,
        num_steps=3,
        integral=x**2*atan(x)/2 - x/2 + atan(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=x*acot(x),
        variable=x,
        num_steps=3,
        integral=x**2*acot(x)/2 + x/2 - atan(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=x*log(a + x**2),
        variable=x,
        num_steps=3,
        integral=-x**2/2 + (a/2 + x**2/2)*log(a + x**2),
    ),
    RubiTestSuiteCase(
        integrand=sin(a + x)*cos(x),
        variable=x,
        num_steps=3,
        integral=x*sin(a)/2 - cos(a + 2*x)/4,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)*cos(a + x),
        variable=x,
        num_steps=3,
        integral=-x*sin(a)/2 - cos(a + 2*x)/4,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sin(x) + 1),
        variable=x,
        num_steps=1,
        integral=-2*cos(x)/sqrt(sin(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(1 - sin(x)),
        variable=x,
        num_steps=1,
        integral=2*cos(x)/sqrt(1 - sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(cos(x) + 1),
        variable=x,
        num_steps=1,
        integral=2*sin(x)/sqrt(cos(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(1 - cos(x)),
        variable=x,
        num_steps=1,
        integral=-2*sin(x)/sqrt(1 - cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(x) - sqrt(x - 1)),
        variable=x,
        num_steps=3,
        integral=2*x**(sympy.S(3)/2)/3 + 2*(x - 1)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/(1 - sqrt(x + 1)),
        variable=x,
        num_steps=4,
        integral=-2*sqrt(x + 1) - 2*log(1 - sqrt(x + 1)),
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(x**4 + 36),
        variable=x,
        num_steps=2,
        integral=asinh(x**2/6)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**(sympy.S(1)/3) + sqrt(x)),
        variable=x,
        num_steps=4,
        integral=6*x**(sympy.S(1)/6) - 3*x**(sympy.S(1)/3) + 2*sqrt(x) - 6*log(x**(sympy.S(1)/6) + 1),
    ),
    RubiTestSuiteCase(
        integrand=log(3*x**2 + 2),
        variable=x,
        num_steps=3,
        integral=x*log(3*x**2 + 2) - 2*x + 2*sqrt(6)*atan(sqrt(6)*x/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=cot(x),
        variable=x,
        num_steps=1,
        integral=log(sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=cot(x)**4,
        variable=x,
        num_steps=3,
        integral=x - cot(x)**3/3 + cot(x),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x),
        variable=x,
        num_steps=1,
        integral=log(cosh(x)),
    ),
    RubiTestSuiteCase(
        integrand=coth(x),
        variable=x,
        num_steps=1,
        integral=log(sinh(x)),
    ),
    RubiTestSuiteCase(
        integrand=b**x,
        variable=x,
        num_steps=1,
        integral=b**x/log(b),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x**4 + 2 + x**(-4)),
        variable=x,
        num_steps=4,
        integral=x**5*sqrt(x**4 + 2 + x**(-4))/(3*x**4 + 3) - x*sqrt(x**4 + 2 + x**(-4))/(x**4 + 1),
    ),
    RubiTestSuiteCase(
        integrand=(2*x + 1)/(3*x + 2),
        variable=x,
        num_steps=2,
        integral=2*x/3 - log(3*x + 2)/9,
    ),
    RubiTestSuiteCase(
        integrand=x*log(x + sqrt(x**2 + 1)),
        variable=x,
        num_steps=3,
        integral=x**2*log(x + sqrt(x**2 + 1))/2 - x*sqrt(x**2 + 1)/4 + asinh(x)/4,
    ),
    RubiTestSuiteCase(
        integrand=x*(exp(x)*sin(x) + 1)**2,
        variable=x,
        num_steps=14,
        integral=x**2/2 + x*exp(2*x)*sin(x)**2/4 - x*exp(2*x)*sin(x)*cos(x)/4 + x*exp(2*x)/8 + x*exp(x)*sin(x) - x*exp(x)*cos(x) - exp(2*x)*sin(x)**2/16 + exp(2*x)*sin(x)*cos(x)/16 + exp(2*x)*sin(2*x)/32 - exp(2*x)*cos(2*x)/32 - 3*exp(2*x)/32 + exp(x)*cos(x),
    ),
    RubiTestSuiteCase(
        integrand=x*exp(x)*cos(x),
        variable=x,
        num_steps=4,
        integral=x*exp(x)*sin(x)/2 + x*exp(x)*cos(x)/2 - exp(x)*sin(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=(x - 3)**(-4),
        variable=x,
        num_steps=1,
        integral=1/(3*(3 - x)**3),
    ),
    RubiTestSuiteCase(
        integrand=x/(x**3 - 1),
        variable=x,
        num_steps=6,
        integral=log(1 - x)/3 - log(x**2 + x + 1)/6 + sqrt(3)*atan(sqrt(3)*(2*x + 1)/3)/3,
    ),
    RubiTestSuiteCase(
        integrand=x/(x**4 - 1),
        variable=x,
        num_steps=2,
        integral=-atanh(x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=(x**3 + 1)*log(x)/(x**4 + 2),
        variable=x,
        num_steps=10,
        integral=(((Integer(8))**(Integer(-1)) * (Integer(2) + (sympy.I * (Integer(-2))**((Integer(4))**(Integer(-1))))) * sympy.log(x) * sympy.log((Integer(1) + (Integer(-1) * (((Integer(1) + sympy.I) * x) * ((Integer(2))**((Integer(3) * (Integer(4))**(Integer(-1)))))**(Integer(-1))))))) + ((Integer(16))**(Integer(-1)) * (Integer(4) + ((Integer(1) + (Integer(-1) * sympy.I)) * (Integer(2))**((Integer(3) * (Integer(4))**(Integer(-1)))))) * sympy.log(x) * sympy.log((Integer(1) + (((Integer(1) + sympy.I) * x) * ((Integer(2))**((Integer(3) * (Integer(4))**(Integer(-1)))))**(Integer(-1)))))) + ((Integer(8))**(Integer(-1)) * (Integer(2) + (Integer(-2))**((Integer(4))**(Integer(-1)))) * sympy.log(x) * sympy.log((Integer(1) + (Integer(-1) * (((Integer(-1))**((Integer(3) * (Integer(4))**(Integer(-1)))) * x) * ((Integer(2))**((Integer(4))**(Integer(-1))))**(Integer(-1))))))) + ((Integer(8))**(Integer(-1)) * (Integer(2) + (Integer(-1) * (Integer(-2))**((Integer(4))**(Integer(-1))))) * sympy.log(x) * sympy.log((Integer(1) + (((Integer(-1))**((Integer(3) * (Integer(4))**(Integer(-1)))) * x) * ((Integer(2))**((Integer(4))**(Integer(-1))))**(Integer(-1)))))) + ((Integer(16))**(Integer(-1)) * (Integer(4) + ((Integer(1) + (Integer(-1) * sympy.I)) * (Integer(2))**((Integer(3) * (Integer(4))**(Integer(-1)))))) * sympy.Function('PolyLog')(Integer(2), (Integer(-1) * (((Integer(1) + sympy.I) * x) * ((Integer(2))**((Integer(3) * (Integer(4))**(Integer(-1)))))**(Integer(-1)))))) + ((Integer(8))**(Integer(-1)) * (Integer(2) + (sympy.I * (Integer(-2))**((Integer(4))**(Integer(-1))))) * sympy.Function('PolyLog')(Integer(2), (((Integer(1) + sympy.I) * x) * ((Integer(2))**((Integer(3) * (Integer(4))**(Integer(-1)))))**(Integer(-1))))) + ((Integer(8))**(Integer(-1)) * (Integer(2) + (Integer(-1) * (Integer(-2))**((Integer(4))**(Integer(-1))))) * sympy.Function('PolyLog')(Integer(2), (Integer(-1) * (((Integer(-1))**((Integer(3) * (Integer(4))**(Integer(-1)))) * x) * ((Integer(2))**((Integer(4))**(Integer(-1))))**(Integer(-1)))))) + ((Integer(8))**(Integer(-1)) * (Integer(2) + (Integer(-2))**((Integer(4))**(Integer(-1)))) * sympy.Function('PolyLog')(Integer(2), (((Integer(-1))**((Integer(3) * (Integer(4))**(Integer(-1)))) * x) * ((Integer(2))**((Integer(4))**(Integer(-1))))**(Integer(-1)))))),
    ),
    RubiTestSuiteCase(
        integrand=log(x) + log(x + 1) + log(x + 2),
        variable=x,
        num_steps=6,
        integral=x*log(x) - 3*x + (x + 1)*log(x + 1) + (x + 2)*log(x + 2),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3 + 5),
        variable=x,
        num_steps=6,
        integral=5**(sympy.S(1)/3)*log(x + 5**(sympy.S(1)/3))/15 - 5**(sympy.S(1)/3)*log(x**2 - 5**(sympy.S(1)/3)*x + 5**(sympy.S(2)/3))/30 - sqrt(3)*5**(sympy.S(1)/3)*atan(sqrt(3)*5**(sympy.S(2)/3)*(-2*x + 5**(sympy.S(1)/3))/15)/15,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(x**2 + 1),
        variable=x,
        num_steps=1,
        integral=asinh(x),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x**2 + 3),
        variable=x,
        num_steps=2,
        integral=x*sqrt(x**2 + 3)/2 + 3*asinh(sqrt(3)*x/3)/2,
    ),
    RubiTestSuiteCase(
        integrand=x/(x + 1)**2,
        variable=x,
        num_steps=2,
        integral=log(x + 1) + 1/(x + 1),
    ),
    RubiTestSuiteCase(
        integrand=asin(x),
        variable=x,
        num_steps=2,
        integral=x*asin(x) + sqrt(1 - x**2),
    ),
    RubiTestSuiteCase(
        integrand=x**2*asin(x),
        variable=x,
        num_steps=4,
        integral=x**3*asin(x)/3 - (1 - x**2)**(sympy.S(3)/2)/9 + sqrt(1 - x**2)/3,
    ),
    RubiTestSuiteCase(
        integrand=sec(x)**2/(-3*tan(x) + sec(x)**2 + 1),
        variable=x,
        num_steps=4,
        integral=-log(-sin(x) + cos(x)) + log(-sin(x) + 2*cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)**(-2),
        variable=x,
        num_steps=2,
        integral=x/2 + sin(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=(5*x**2 - 3*x - 2)/(x**2*(x - 2)),
        variable=x,
        num_steps=2,
        integral=2*log(x) + 3*log(2 - x) - 1/x,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(4*x**2 + 9),
        variable=x,
        num_steps=1,
        integral=asinh(2*x/3)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(x**2 + 4),
        variable=x,
        num_steps=1,
        integral=asinh(x/2),
    ),
    RubiTestSuiteCase(
        integrand=1/(9*x**2 - 12*x + 10),
        variable=x,
        num_steps=2,
        integral=-sqrt(6)*atan(sqrt(6)*(2 - 3*x)/6)/18,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**8 - 2*x**7 + 2*x**6 - 2*x**5 + x**4),
        variable=x,
        num_steps=3,
        integral=2*log(x) - 5*log(1 - x)/2 + log(x**2 + 1)/4 + 1/(2 - 2*x) - 2/x - 1/x**2 - 1/(3*x**3),
    ),
    RubiTestSuiteCase(
        integrand=(a*x**3 + b*x**2 + c*x + d)/(x*(x - 3)*(x + 1)),
        variable=x,
        num_steps=2,
        integral=a*x - d*log(x)/3 - (a/4 - b/4 + c/4 - d/4)*log(x + 1) + (9*a/4 + 3*b/4 + c/4 + d/12)*log(3 - x),
    ),
    RubiTestSuiteCase(
        integrand=(2 - log(x**2 + 1))**(-5),
        variable=x,
        num_steps=0,
        integral=sympy.Function('Unintegrable')((((Integer(2) + (Integer(-1) * sympy.log((Integer(1) + (x)**(Integer(2)))))))**(Integer(5)))**(Integer(-1)), x),
    ),
    RubiTestSuiteCase(
        integrand=2*x*exp(x**2)*log(x) + (1 + 2*log(x)/x + 1/x)/(x + log(x)**2) + (log(x) - 2)/(x + log(x)**2)**2 + exp(x**2)/x,
        variable=x,
        num_steps=9,
        integral=exp(x**2)*log(x) + log(x + log(x)**2) - log(x)/(x + log(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=x**4*exp(x*z + x/2)*sin(pi*z)**4,
        variable=z,
        num_steps=4,
        integral=12*pi**2*x**5*exp(x*z + x/2)*sin(pi*z)**2/(x**4 + 20*pi**2*x**2 + 64*pi**4) + x**5*exp(x*z + x/2)*sin(pi*z)**4/(x**2 + 16*pi**2) - 24*pi**3*x**4*exp(x*z + x/2)*sin(pi*z)*cos(pi*z)/(x**4 + 20*pi**2*x**2 + 64*pi**4) - 4*pi*x**4*exp(x*z + x/2)*sin(pi*z)**3*cos(pi*z)/(x**2 + 16*pi**2) + 24*pi**4*x**3*exp(x*z + x/2)/(x**4 + 20*pi**2*x**2 + 64*pi**4),
    ),
    RubiTestSuiteCase(
        integrand=sympy.Function('Erf')(x),
        variable=x,
        num_steps=1,
        integral=((((sympy.E)**((x)**(Integer(2))) * sympy.sqrt(sympy.pi)))**(Integer(-1)) + (x * sympy.Function('Erf')(x))),
    ),
    RubiTestSuiteCase(
        integrand=sympy.Function('Erf')((x + Symbol('a'))),
        variable=x,
        num_steps=1,
        integral=((((sympy.E)**(((Symbol('a') + x))**(Integer(2))) * sympy.sqrt(sympy.pi)))**(Integer(-1)) + ((Symbol('a') + x) * sympy.Function('Erf')((Symbol('a') + x)))),
    ),
    RubiTestSuiteCase(
        integrand=(2*x**6 + 4*x**5 + 7*x**4 - 3*x**3 - x**2 - 8*x - 8)/((2*x**2 - 1)**2*sqrt(x**4 + 4*x**3 + 2*x**2 + 1)),
        variable=x,
        num_steps=-10,
        integral=(2*x + 1)*sqrt(x**4 + 4*x**3 + 2*x**2 + 1)/(4*x**2 - 2) - atanh(x*(x + 2)*(33*x**3 + 27*x**2 - x + 7)/((31*x**3 + 37*x**2 + 2)*sqrt(x**4 + 4*x**3 + 2*x**2 + 1))),
    ),
    RubiTestSuiteCase(
        integrand=(2*y + 1)*sqrt(-5*y**2 - 5*y + 1)/(y*(y + 1)*(y + 2)*sqrt(-y**2 - y + 1)),
        variable=y,
        num_steps=-2,
        integral=-atanh((1 - 3*y)*sqrt(-5*y**2 - 5*y + 1)/((1 - 5*y)*sqrt(-y**2 - y + 1)))/4 - atanh((3*y + 4)*sqrt(-5*y**2 - 5*y + 1)/((5*y + 6)*sqrt(-y**2 - y + 1)))/2 + 9*atanh((7*y + 11)*sqrt(-5*y**2 - 5*y + 1)/((15*y + 21)*sqrt(-y**2 - y + 1)))/4,
    ),
    RubiTestSuiteCase(
        integrand=x*(x**2*sqrt(x**2 - 4) + x**2*sqrt(x**2 - 1) - sqrt(x**2 - 4) - 4*sqrt(x**2 - 1))/((x**4 - 5*x**2 + 4)*(sqrt(x**2 - 4) + sqrt(x**2 - 1) + 1)),
        variable=x,
        num_steps=1,
        integral=log(sqrt(x**2 - 4) + sqrt(x**2 - 1) + 1),
    ),
    RubiTestSuiteCase(
        integrand=x*sqrt(9 - 4*sqrt(2)) - sqrt(2)*sqrt(x**4 + 2*x**2 + 4*x + 1),
        variable=x,
        num_steps=-1,
        integral=(((Integer(2))**(Integer(-1)) * sympy.sqrt((Integer(9) + (Integer(-1) * (Integer(4) * sympy.sqrt(Integer(2)))))) * (x)**(Integer(2))) + (Integer(-1) * (sympy.sqrt(Integer(2)) * (((Integer(-1) * (Integer(3))**(Integer(-1))) * sympy.sqrt((Integer(1) + (Integer(4) * x) + (Integer(2) * (x)**(Integer(2))) + (x)**(Integer(4))))) + ((Integer(3))**(Integer(-1)) * (Integer(1) + x) * sympy.sqrt((Integer(1) + (Integer(4) * x) + (Integer(2) * (x)**(Integer(2))) + (x)**(Integer(4))))) + ((Integer(4) * sympy.I * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))) * sympy.sqrt((Integer(1) + (Integer(4) * x) + (Integer(2) * (x)**(Integer(2))) + (x)**(Integer(4))))) * (((Integer(4) * (Integer(2))**((Integer(2) * (Integer(3))**(Integer(-1)))) * ((Integer(-1) * sympy.I) + sympy.sqrt(Integer(3)))) + (Integer(-1) * (Integer(2) * sympy.I * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))) + ((Integer(2))**((Integer(3))**(Integer(-1))) * (sympy.I + sympy.sqrt(Integer(3))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(6) * sympy.I * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))) * x)))**(Integer(-1))) + (Integer(-1) * ((Integer(8) * (Integer(2))**((Integer(2) * (Integer(3))**(Integer(-1)))) * sympy.sqrt((Integer(3) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33))) + (Integer(4) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))))**(Integer(-1)))) * sympy.sqrt(((sympy.I * (Integer(-19899) + (Integer(3445) * sympy.sqrt(Integer(33))) + (((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))) * (Integer(-2574) + (Integer(466) * sympy.sqrt(Integer(33))))) + (((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))) * (Integer(-19899) + (Integer(3445) * sympy.sqrt(Integer(33))))) + ((Integer(59697) + (Integer(-1) * (Integer(10335) * sympy.sqrt(Integer(33))))) * x))) * (((Integer(-39) + (Integer(-1) * (Integer(13) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(9) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(9) * sympy.sqrt(Integer(33))) + (Integer(4) * sympy.I * ((Integer(3) * sympy.I) + sympy.sqrt(Integer(3))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))) * (Integer(26) + (Integer(-1) * (Integer(6) * sympy.sqrt(Integer(33)))) + ((Integer(-13) + (Integer(13) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(9) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + ((Integer(-4) + (Integer(-1) * (Integer(4) * sympy.I * sympy.sqrt(Integer(3))))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(6) * (Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))) * x))))**(Integer(-1)))) * sympy.sqrt((Integer(1) + (Integer(4) * x) + (Integer(2) * (x)**(Integer(2))) + (x)**(Integer(4)))) * sympy.elliptic_e(sympy.asin((sympy.sqrt((Integer(26) + (Integer(-1) * (Integer(6) * sympy.sqrt(Integer(33)))) + ((Integer(-13) + (Integer(-1) * (Integer(13) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(9) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + (Integer(4) * sympy.I * (sympy.I + sympy.sqrt(Integer(3))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(6) * (Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))) * x))) * ((sympy.sqrt(((Integer(39) + (Integer(13) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(9) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(-1) * (Integer(9) * sympy.sqrt(Integer(33)))) + (Integer(4) * (Integer(3) + (Integer(-1) * (sympy.I * sympy.sqrt(Integer(3))))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))) * ((Integer(39) + (Integer(-1) * (Integer(13) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(9) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(-1) * (Integer(9) * sympy.sqrt(Integer(33)))) + (Integer(4) * (Integer(3) + (sympy.I * sympy.sqrt(Integer(3)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))))**(Integer(-1)))) * sympy.sqrt((Integer(26) + (Integer(-1) * (Integer(6) * sympy.sqrt(Integer(33)))) + ((Integer(-13) + (Integer(13) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(9) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + ((Integer(-4) + (Integer(-1) * (Integer(4) * sympy.I * sympy.sqrt(Integer(3))))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(6) * (Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))) * x)))))**(Integer(-1)))), (((Integer(4) * (Integer(21) + (Integer(7) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(3) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(-1) * (Integer(3) * sympy.sqrt(Integer(33)))))) + ((Integer(3) + (Integer(-1) * (sympy.I * sympy.sqrt(Integer(3)))) + (Integer(-1) * (Integer(3) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))) * (((Integer(4) * (Integer(21) + (Integer(-1) * (Integer(7) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(3) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(-1) * (Integer(3) * sympy.sqrt(Integer(33)))))) + ((Integer(3) + (sympy.I * sympy.sqrt(Integer(3))) + (Integer(3) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))))**(Integer(-1))))) * ((((Integer(4) * (Integer(2))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(-1) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + (Integer(-1) * ((Integer(2))**((Integer(3))**(Integer(-1))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))))) + (Integer(3) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))) * x)) * sympy.sqrt(((sympy.I * (Integer(1) + x)) * (((Integer(104) + (Integer(-1) * (Integer(24) * sympy.sqrt(Integer(33)))) + ((Integer(-13) + (Integer(-1) * (Integer(13) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(9) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + (Integer(4) * sympy.I * (sympy.I + sympy.sqrt(Integer(3))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))))) * (Integer(26) + (Integer(-1) * (Integer(6) * sympy.sqrt(Integer(33)))) + ((Integer(-13) + (Integer(13) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(9) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + ((Integer(-4) + (Integer(-1) * (Integer(4) * sympy.I * sympy.sqrt(Integer(3))))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(6) * (Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))) * x))))**(Integer(-1)))) * sympy.sqrt((Integer(26) + (Integer(-1) * (Integer(6) * sympy.sqrt(Integer(33)))) + ((Integer(-13) + (Integer(13) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(9) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + ((Integer(-4) + (Integer(-1) * (Integer(4) * sympy.I * sympy.sqrt(Integer(3))))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(6) * (Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))) * x))) * sympy.sqrt((Integer(26) + (Integer(-1) * (Integer(6) * sympy.sqrt(Integer(33)))) + ((Integer(-13) + (Integer(-1) * (Integer(13) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(9) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + (Integer(4) * sympy.I * (sympy.I + sympy.sqrt(Integer(3))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(6) * (Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))) * x)))))**(Integer(-1)))) + (((((Integer(2))**((Integer(3))**(Integer(-1))) * (Integer(13) + (Integer(-1) * (Integer(13) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(9) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(-1) * (Integer(3) * sympy.sqrt(Integer(33)))))) + (Integer(4) * (Integer(2))**((Integer(2) * (Integer(3))**(Integer(-1)))) * (Integer(1) + (sympy.I * sympy.sqrt(Integer(3)))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + (Integer(20) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))))) * ((Integer(4) * (Integer(2))**((Integer(2) * (Integer(3))**(Integer(-1)))) * (sympy.I + sympy.sqrt(Integer(3)))) + (Integer(8) * sympy.I * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + ((Integer(2))**((Integer(3))**(Integer(-1))) * ((Integer(-1) * sympy.I) + sympy.sqrt(Integer(3))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))))) * sympy.sqrt(((Integer(52) + (Integer(-1) * (Integer(12) * sympy.sqrt(Integer(33)))) + (Integer(-1) * ((Integer(2))**((Integer(3))**(Integer(-1))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(4) * (Integer(3))**(Integer(-1)))))) + (Integer(4) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33))) + (Integer(4) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))))**(Integer(-1)))) * sympy.sqrt((((Integer(1) + x))**(Integer(-1)) * ((Integer(-8) * sympy.I * (Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33))))) + (((Integer(-43) * sympy.I) + (Integer(-1) * (Integer(13) * sympy.sqrt(Integer(3)))) + (Integer(9) * sympy.sqrt(Integer(11))) + (Integer(5) * sympy.I * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + (((Integer(2) * sympy.I) + (Integer(4) * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(2) * sympy.I * sympy.sqrt(Integer(33))))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (((Integer(8) * sympy.I * (Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33))))) + (((Integer(13) * sympy.I) + (Integer(-1) * (Integer(13) * sympy.sqrt(Integer(3)))) + (Integer(9) * sympy.sqrt(Integer(11))) + (Integer(-1) * (Integer(3) * sympy.I * sympy.sqrt(Integer(33))))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + (Integer(4) * (sympy.I + sympy.sqrt(Integer(3))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))))) * x)))) * sympy.sqrt((Integer(1) + (Integer(4) * x) + (Integer(2) * (x)**(Integer(2))) + (x)**(Integer(4)))) * sympy.elliptic_f(sympy.asin(((sympy.sqrt((Integer(52) + (Integer(-1) * (Integer(12) * sympy.sqrt(Integer(33)))) + (Integer(-1) * ((Integer(2))**((Integer(3))**(Integer(-1))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(4) * (Integer(3))**(Integer(-1)))))) + (Integer(4) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))))) * sympy.sqrt((Integer(26) + (Integer(-1) * (Integer(6) * sympy.sqrt(Integer(33)))) + ((Integer(-13) + (Integer(-1) * (Integer(13) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(9) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + (Integer(4) * sympy.I * (sympy.I + sympy.sqrt(Integer(3))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(6) * (Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))) * x)))) * (((Integer(2))**((Integer(6))**(Integer(-1))) * sympy.sqrt(Integer(3)) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))) * sympy.sqrt((Integer(39) + (Integer(13) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(9) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(-1) * (Integer(9) * sympy.sqrt(Integer(33)))) + (Integer(4) * (Integer(3) + (Integer(-1) * (sympy.I * sympy.sqrt(Integer(3))))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))))) * sympy.sqrt((Integer(1) + x))))**(Integer(-1)))), (((Integer(4) * ((Integer(21) * sympy.I) + (Integer(-1) * (Integer(7) * sympy.sqrt(Integer(3)))) + (Integer(3) * sympy.sqrt(Integer(11))) + (Integer(-1) * (Integer(3) * sympy.I * sympy.sqrt(Integer(33)))))) + (((Integer(3) * sympy.I) + sympy.sqrt(Integer(3)) + (Integer(3) * sympy.sqrt(Integer(11))) + (Integer(3) * sympy.I * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))) * (((Integer(-56) * sympy.sqrt(Integer(3))) + (Integer(24) * sympy.sqrt(Integer(11))) + (Integer(2) * (sympy.sqrt(Integer(3)) + (Integer(3) * sympy.sqrt(Integer(11)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))))**(Integer(-1))))) * ((Integer(3) * (Integer(2))**((Integer(2) * (Integer(3))**(Integer(-1)))) * (Integer(3))**((Integer(3) * (Integer(4))**(Integer(-1)))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))) * sympy.sqrt((Integer(39) + (Integer(13) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(9) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(-1) * (Integer(9) * sympy.sqrt(Integer(33)))) + (Integer(4) * (Integer(3) + (Integer(-1) * (sympy.I * sympy.sqrt(Integer(3))))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))))) * sympy.sqrt((Integer(1) + x)) * ((Integer(4) * (Integer(2))**((Integer(2) * (Integer(3))**(Integer(-1)))) * ((Integer(-1) * sympy.I) + sympy.sqrt(Integer(3)))) + (Integer(-1) * (Integer(2) * sympy.I * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))) + ((Integer(2))**((Integer(3))**(Integer(-1))) * (sympy.I + sympy.sqrt(Integer(3))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(6) * sympy.I * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))) * x)) * sympy.sqrt((Integer(26) + (Integer(-1) * (Integer(6) * sympy.sqrt(Integer(33)))) + ((Integer(-13) + (Integer(-1) * (Integer(13) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(9) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + (Integer(4) * sympy.I * (sympy.I + sympy.sqrt(Integer(3))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(6) * (Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))) * x))) * sympy.sqrt((((Integer(8) * (Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33))))) + (Integer(-1) * ((Integer(5) + (Integer(-1) * (Integer(3) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(3) * sympy.I * sympy.sqrt(Integer(11))) + sympy.sqrt(Integer(33))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))))) + (((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))) * (Integer(-41) + (Integer(15) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(3) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(7) * sympy.sqrt(Integer(33))))) + ((Integer(104) + (Integer(-1) * (Integer(24) * sympy.sqrt(Integer(33)))) + ((Integer(-13) + (Integer(-1) * (Integer(13) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(9) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + (Integer(4) * sympy.I * (sympy.I + sympy.sqrt(Integer(3))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))))) * x)) * (((Integer(-39) + (Integer(-1) * (Integer(13) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(9) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(9) * sympy.sqrt(Integer(33))) + (Integer(4) * sympy.I * ((Integer(3) * sympy.I) + sympy.sqrt(Integer(3))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))) * (Integer(1) + x)))**(Integer(-1))))))**(Integer(-1))) + ((((Integer(4) * (Integer(2))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(2) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + (Integer(-1) * ((Integer(2))**((Integer(3))**(Integer(-1))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))))) * ((Integer(4) * (Integer(2))**((Integer(2) * (Integer(3))**(Integer(-1)))) * (sympy.I + sympy.sqrt(Integer(3)))) + (Integer(-1) * (Integer(4) * sympy.I * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))) + ((Integer(2))**((Integer(3))**(Integer(-1))) * ((Integer(-1) * sympy.I) + sympy.sqrt(Integer(3))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))))) * ((Integer(4) * (Integer(2))**((Integer(2) * (Integer(3))**(Integer(-1)))) * ((Integer(-1) * sympy.I) + sympy.sqrt(Integer(3)))) + (Integer(4) * sympy.I * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + ((Integer(2))**((Integer(3))**(Integer(-1))) * (sympy.I + sympy.sqrt(Integer(3))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))))) * sympy.sqrt(((Integer(-39) + (Integer(13) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(9) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(9) * sympy.sqrt(Integer(33))) + (Integer(-1) * (Integer(4) * sympy.I * ((Integer(-3) * sympy.I) + sympy.sqrt(Integer(3))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))))) * ((Integer(104) + (Integer(-1) * (Integer(24) * sympy.sqrt(Integer(33)))) + ((Integer(-13) + (Integer(13) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(9) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + ((Integer(-4) + (Integer(-1) * (Integer(4) * sympy.I * sympy.sqrt(Integer(3))))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))))))**(Integer(-1)))) * sympy.sqrt((Integer(1) + x)) * sympy.sqrt(((Integer(104) + (Integer(-1) * (Integer(24) * sympy.sqrt(Integer(33)))) + (Integer(2) * (Integer(1) + (Integer(14) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(6) * sympy.I * sympy.sqrt(Integer(11)))) + sympy.sqrt(Integer(33))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + ((Integer(-7) + (Integer(-1) * (sympy.I * sympy.sqrt(Integer(3)))) + (Integer(-1) * (Integer(3) * sympy.I * sympy.sqrt(Integer(11)))) + sympy.sqrt(Integer(33))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(2) * (Integer(-52) + (Integer(12) * sympy.sqrt(Integer(33))) + ((Integer(2))**((Integer(3))**(Integer(-1))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(4) * (Integer(3))**(Integer(-1))))) + (Integer(-1) * (Integer(4) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))))) * x)) * (((Integer(-39) + (Integer(13) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(9) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(9) * sympy.sqrt(Integer(33))) + (Integer(-1) * (Integer(4) * sympy.I * ((Integer(-3) * sympy.I) + sympy.sqrt(Integer(3))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))))) * (Integer(1) + x)))**(Integer(-1)))) * sympy.sqrt(((Integer(104) + (Integer(-1) * (Integer(24) * sympy.sqrt(Integer(33)))) + (Integer(2) * (Integer(1) + (Integer(-1) * (Integer(14) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(6) * sympy.I * sympy.sqrt(Integer(11))) + sympy.sqrt(Integer(33))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + ((Integer(-7) + (sympy.I * sympy.sqrt(Integer(3))) + (Integer(3) * sympy.I * sympy.sqrt(Integer(11))) + sympy.sqrt(Integer(33))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(2) * (Integer(-52) + (Integer(12) * sympy.sqrt(Integer(33))) + ((Integer(2))**((Integer(3))**(Integer(-1))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(4) * (Integer(3))**(Integer(-1))))) + (Integer(-1) * (Integer(4) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))))) * x)) * (((Integer(-39) + (Integer(-1) * (Integer(13) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(9) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(9) * sympy.sqrt(Integer(33))) + (Integer(4) * sympy.I * ((Integer(3) * sympy.I) + sympy.sqrt(Integer(3))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))) * (Integer(1) + x)))**(Integer(-1)))) * sympy.sqrt((Integer(1) + (Integer(4) * x) + (Integer(2) * (x)**(Integer(2))) + (x)**(Integer(4)))) * sympy.Function('EllipticPi')((((Integer(2))**((Integer(3))**(Integer(-1))) * ((Integer(4) * (Integer(2))**((Integer(3))**(Integer(-1))) * ((Integer(-3) * sympy.I) + sympy.sqrt(Integer(3)))) + (((Integer(3) * sympy.I) + sympy.sqrt(Integer(3))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))))) * (((Integer(4) * (Integer(2))**((Integer(2) * (Integer(3))**(Integer(-1)))) * ((Integer(-1) * sympy.I) + sympy.sqrt(Integer(3)))) + (Integer(-1) * (Integer(8) * sympy.I * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))) + ((Integer(2))**((Integer(3))**(Integer(-1))) * (sympy.I + sympy.sqrt(Integer(3))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))))))**(Integer(-1))), sympy.asin((sympy.sqrt((Integer(13) + (Integer(-1) * (Integer(3) * sympy.sqrt(Integer(33)))) + (Integer(-1) * ((Integer(2))**((Integer(3))**(Integer(-1))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(4) * (Integer(3))**(Integer(-1)))))) + (Integer(4) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + ((Integer(-39) + (Integer(9) * sympy.sqrt(Integer(33)))) * x))) * (((Integer(2))**((Integer(6))**(Integer(-1))) * sympy.sqrt(Integer(3)) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))) * sympy.sqrt(((Integer(-39) + (Integer(13) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(9) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(9) * sympy.sqrt(Integer(33))) + (Integer(-1) * (Integer(4) * sympy.I * ((Integer(-3) * sympy.I) + sympy.sqrt(Integer(3))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))))) * ((Integer(104) + (Integer(-1) * (Integer(24) * sympy.sqrt(Integer(33)))) + ((Integer(-13) + (Integer(13) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(9) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + ((Integer(-4) + (Integer(-1) * (Integer(4) * sympy.I * sympy.sqrt(Integer(3))))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1)))))))**(Integer(-1)))) * sympy.sqrt((Integer(1) + x))))**(Integer(-1)))), (((Integer(4) * (Integer(21) + (Integer(-1) * (Integer(7) * sympy.I * sympy.sqrt(Integer(3)))) + (Integer(3) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(-1) * (Integer(3) * sympy.sqrt(Integer(33)))))) + ((Integer(3) + (sympy.I * sympy.sqrt(Integer(3))) + (Integer(3) * sympy.I * sympy.sqrt(Integer(11))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))) * (((Integer(4) * (Integer(21) + (Integer(7) * sympy.I * sympy.sqrt(Integer(3))) + (Integer(-1) * (Integer(3) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(-1) * (Integer(3) * sympy.sqrt(Integer(33)))))) + ((Integer(3) + (Integer(-1) * (sympy.I * sympy.sqrt(Integer(3)))) + (Integer(-1) * (Integer(3) * sympy.I * sympy.sqrt(Integer(11)))) + (Integer(3) * sympy.sqrt(Integer(33)))) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))))**(Integer(-1))))) * (((Integer(2))**((Integer(6))**(Integer(-1))) * sympy.sqrt(Integer(3)) * ((Integer(4) * (Integer(2))**((Integer(2) * (Integer(3))**(Integer(-1)))) * (sympy.I + sympy.sqrt(Integer(3)))) + (Integer(2) * sympy.I * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1)))) + ((Integer(2))**((Integer(3))**(Integer(-1))) * ((Integer(-1) * sympy.I) + sympy.sqrt(Integer(3))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(-1) * (Integer(6) * sympy.I * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))) * x))) * ((Integer(4) * (Integer(2))**((Integer(2) * (Integer(3))**(Integer(-1)))) * ((Integer(-1) * sympy.I) + sympy.sqrt(Integer(3)))) + (Integer(-1) * (Integer(2) * sympy.I * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))))) + ((Integer(2))**((Integer(3))**(Integer(-1))) * (sympy.I + sympy.sqrt(Integer(3))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + (Integer(6) * sympy.I * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(3))**(Integer(-1))) * x)) * sympy.sqrt((Integer(13) + (Integer(-1) * (Integer(3) * sympy.sqrt(Integer(33)))) + (Integer(-1) * ((Integer(2))**((Integer(3))**(Integer(-1))) * ((Integer(-13) + (Integer(3) * sympy.sqrt(Integer(33)))))**((Integer(4) * (Integer(3))**(Integer(-1)))))) + (Integer(4) * ((Integer(-26) + (Integer(6) * sympy.sqrt(Integer(33)))))**((Integer(2) * (Integer(3))**(Integer(-1))))) + ((Integer(-39) + (Integer(9) * sympy.sqrt(Integer(33)))) * x)))))**(Integer(-1))))))),
    ),
    RubiTestSuiteCase(
        integrand=(12*pi**2*mc**3*x**2*(-12*mc**2 + 3*mc - 8*x)*log(x/mc**2) + pi**2*(4*mc**9 - 3*mc**8 - 48*mc**7*x + 24*mc**6*x - 144*mc**5*x**2 + 176*mc**3*x**3 - 24*mc**2*x**3 + 12*mc*x**4 + 3*x**4))*exp(-x/y)/(384*x**2),
        variable=x,
        num_steps=20,
        integral=((((Integer(3) + (Integer(-1) * (Integer(4) * Symbol('mc')))) * (Symbol('mc'))**(Integer(8)) * (sympy.pi)**(Integer(2))) * (((sympy.E)**((x * (Symbol('y'))**(Integer(-1)))) * (Integer(384) * x)))**(Integer(-1))) + (((Integer(3) * (Integer(8))**(Integer(-1))) * (Symbol('mc'))**(Integer(5)) * (sympy.pi)**(Integer(2)) * Symbol('y')) * ((sympy.E)**((x * (Symbol('y'))**(Integer(-1)))))**(Integer(-1))) + (((Integer(48))**(Integer(-1)) * (Integer(3) + (Integer(-1) * (Integer(22) * Symbol('mc')))) * (Symbol('mc'))**(Integer(2)) * (sympy.pi)**(Integer(2)) * x * Symbol('y')) * ((sympy.E)**((x * (Symbol('y'))**(Integer(-1)))))**(Integer(-1))) + (Integer(-1) * (((Integer(128))**(Integer(-1)) * (Integer(1) + (Integer(4) * Symbol('mc'))) * (sympy.pi)**(Integer(2)) * (x)**(Integer(2)) * Symbol('y')) * ((sympy.E)**((x * (Symbol('y'))**(Integer(-1)))))**(Integer(-1)))) + (((Integer(48))**(Integer(-1)) * (Integer(3) + (Integer(-1) * (Integer(22) * Symbol('mc')))) * (Symbol('mc'))**(Integer(2)) * (sympy.pi)**(Integer(2)) * (Symbol('y'))**(Integer(2))) * ((sympy.E)**((x * (Symbol('y'))**(Integer(-1)))))**(Integer(-1))) + (((Integer(4))**(Integer(-1)) * (Symbol('mc'))**(Integer(3)) * (sympy.pi)**(Integer(2)) * (Symbol('y'))**(Integer(2))) * ((sympy.E)**((x * (Symbol('y'))**(Integer(-1)))))**(Integer(-1))) + (Integer(-1) * (((Integer(64))**(Integer(-1)) * (Integer(1) + (Integer(4) * Symbol('mc'))) * (sympy.pi)**(Integer(2)) * x * (Symbol('y'))**(Integer(2))) * ((sympy.E)**((x * (Symbol('y'))**(Integer(-1)))))**(Integer(-1)))) + (Integer(-1) * (((Integer(64))**(Integer(-1)) * (Integer(1) + (Integer(4) * Symbol('mc'))) * (sympy.pi)**(Integer(2)) * (Symbol('y'))**(Integer(3))) * ((sympy.E)**((x * (Symbol('y'))**(Integer(-1)))))**(Integer(-1)))) + ((Integer(16))**(Integer(-1)) * (Integer(1) + (Integer(-1) * (Integer(2) * Symbol('mc')))) * (Symbol('mc'))**(Integer(6)) * (sympy.pi)**(Integer(2)) * sympy.Function('ExpIntegralEi')((Integer(-1) * (x * (Symbol('y'))**(Integer(-1)))))) + (((Integer(3) + (Integer(-1) * (Integer(4) * Symbol('mc')))) * (Symbol('mc'))**(Integer(8)) * (sympy.pi)**(Integer(2)) * sympy.Function('ExpIntegralEi')((Integer(-1) * (x * (Symbol('y'))**(Integer(-1)))))) * ((Integer(384) * Symbol('y')))**(Integer(-1))) + ((Integer(32))**(Integer(-1)) * (Symbol('mc'))**(Integer(3)) * (sympy.pi)**(Integer(2)) * ((Integer(3) * Symbol('mc')) + (Integer(-1) * (Integer(12) * (Symbol('mc'))**(Integer(2)))) + (Integer(-1) * (Integer(8) * Symbol('y')))) * Symbol('y') * sympy.Function('ExpIntegralEi')((Integer(-1) * (x * (Symbol('y'))**(Integer(-1)))))) + (Integer(-1) * (((Integer(32))**(Integer(-1)) * (Symbol('mc'))**(Integer(3)) * (sympy.pi)**(Integer(2)) * ((Integer(3) * (Integer(1) + (Integer(-1) * (Integer(4) * Symbol('mc')))) * Symbol('mc')) + (Integer(-1) * (Integer(8) * x))) * Symbol('y') * sympy.log((x * ((Symbol('mc'))**(Integer(2)))**(Integer(-1))))) * ((sympy.E)**((x * (Symbol('y'))**(Integer(-1)))))**(Integer(-1)))) + (((Integer(4))**(Integer(-1)) * (Symbol('mc'))**(Integer(3)) * (sympy.pi)**(Integer(2)) * (Symbol('y'))**(Integer(2)) * sympy.log((x * ((Symbol('mc'))**(Integer(2)))**(Integer(-1))))) * ((sympy.E)**((x * (Symbol('y'))**(Integer(-1)))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*x)/cos(x),
        variable=x,
        num_steps=2,
        integral=-2*cos(x),
    ),
    RubiTestSuiteCase(
        integrand=(7*x**13 + 10*x**8 + 4*x**7 - 7*x**6 - 4*x**3 - 4*x**2 + 3*x + 3)/(x**14 - 2*x**8 - 2*x**7 - 2*x**4 - 4*x**3 - x**2 + 2*x + 1),
        variable=x,
        num_steps=-5,
        integral=-(-1 + sqrt(2))*log(x**7 + sqrt(2)*x**2 + x*(-1 + sqrt(2)) - 1)/2 + (1 + sqrt(2))*log(-x**7 + sqrt(2)*x**2 + x + sqrt(2)*x + 1)/2,
    ),
]
