# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 0 Independent test suites/Moses Problems.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '0 Independent test suites/Moses Problems.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
A, B, H, K, a, e, r, t, w, y, z = symbols('A B H K a e r t w y z')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=cot(x)**4,
        variable=x,
        num_steps=3,
        integral=x - cot(x)**3/3 + cot(x),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4*(x**2 + 1)),
        variable=x,
        num_steps=3,
        integral=atan(x) + 1/x - 1/(3*x**3),
    ),
    RubiTestSuiteCase(
        integrand=(x**2 + x)/sqrt(x),
        variable=x,
        num_steps=2,
        integral=2*x**(sympy.S(5)/2)/5 + 2*x**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=cos(x),
        variable=x,
        num_steps=1,
        integral=sin(x),
    ),
    RubiTestSuiteCase(
        integrand=x*exp(x**2),
        variable=x,
        num_steps=1,
        integral=exp(x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)*sec(x)**2,
        variable=x,
        num_steps=2,
        integral=sec(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=x*sqrt(x**2 + 1),
        variable=x,
        num_steps=1,
        integral=(x**2 + 1)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*sin(x),
        variable=x,
        num_steps=1,
        integral=exp(x)*sin(x)/2 - exp(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)*csc(x)**2/sin(x)**2,
        variable=x,
        num_steps=2,
        integral=-csc(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=sin(exp(x)),
        variable=x,
        num_steps=2,
        integral=sympy.Function('SinIntegral')((sympy.E)**(x)),
    ),
    RubiTestSuiteCase(
        integrand=sin(y)/y,
        variable=y,
        num_steps=1,
        integral=sympy.Function('SinIntegral')(Symbol('y')),
    ),
    RubiTestSuiteCase(
        integrand=exp(x) + sin(x),
        variable=x,
        num_steps=3,
        integral=exp(x) - cos(x),
    ),
    RubiTestSuiteCase(
        integrand=2*x**2*exp(x**2) + exp(x**2),
        variable=x,
        num_steps=4,
        integral=x*exp(x**2),
    ),
    RubiTestSuiteCase(
        integrand=(x + exp(x))**2,
        variable=x,
        num_steps=5,
        integral=x**3/3 + 2*x*exp(x) + exp(2*x)/2 - 2*exp(x),
    ),
    RubiTestSuiteCase(
        integrand=x**2 + exp(2*x) + 2*exp(x),
        variable=x,
        num_steps=3,
        integral=x**3/3 + exp(2*x)/2 + 2*exp(x),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)*cos(x),
        variable=x,
        num_steps=2,
        integral=sin(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=x*exp(x**2),
        variable=x,
        num_steps=1,
        integral=exp(x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=x*sqrt(x**2 + 1),
        variable=x,
        num_steps=1,
        integral=(x**2 + 1)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=exp(x)/(exp(x) + 1),
        variable=x,
        num_steps=2,
        integral=log(exp(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=x**(sympy.S(3)/2),
        variable=x,
        num_steps=1,
        integral=2*x**(sympy.S(5)/2)/5,
    ),
    RubiTestSuiteCase(
        integrand=cos(2*x + 3),
        variable=x,
        num_steps=1,
        integral=sin(2*x + 3)/2,
    ),
    RubiTestSuiteCase(
        integrand=2*y*z*exp(2*x),
        variable=x,
        num_steps=2,
        integral=y*z*exp(2*x),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*sin(exp(x))*cos(exp(x))**2,
        variable=x,
        num_steps=3,
        integral=-cos(exp(x))**3/3,
    ),
    RubiTestSuiteCase(
        integrand=x*sqrt(x + 1),
        variable=x,
        num_steps=2,
        integral=2*(x + 1)**(sympy.S(5)/2)/5 - 2*(x + 1)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 - 1),
        variable=x,
        num_steps=3,
        integral=-atan(x)/2 - atanh(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=exp(x)/(3*exp(2*x) + 2),
        variable=x,
        num_steps=2,
        integral=sqrt(6)*atan(sqrt(6)*exp(x)/2)/6,
    ),
    RubiTestSuiteCase(
        integrand=exp(2*x)/(A + B*exp(4*x)),
        variable=x,
        num_steps=2,
        integral=atan(sqrt(B)*exp(2*x)/sqrt(A))/(2*sqrt(A)*sqrt(B)),
    ),
    RubiTestSuiteCase(
        integrand=exp(x + 1)/(exp(x) + 1),
        variable=x,
        num_steps=3,
        integral=(sympy.E * sympy.log((Integer(1) + (sympy.E)**(x)))),
    ),
    RubiTestSuiteCase(
        integrand=10**x*exp(x),
        variable=x,
        num_steps=1,
        integral=(((Integer(10) * sympy.E))**(x) * ((Integer(1) + sympy.log(Integer(10))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=x**3*sin(x**2),
        variable=x,
        num_steps=3,
        integral=-x**2*cos(x**2)/2 + sin(x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=x**7/(x**12 + 1),
        variable=x,
        num_steps=7,
        integral=-log(x**4 + 1)/12 + log(x**8 - x**4 + 1)/24 - sqrt(3)*atan(sqrt(3)*(1 - 2*x**4)/3)/12,
    ),
    RubiTestSuiteCase(
        integrand=x**(3*a)*sin(x**(2*a)),
        variable=x,
        num_steps=3,
        integral=(((sympy.I * (x)**((Integer(1) + (Integer(3) * Symbol('a')))) * sympy.Function('Gamma')(((Integer(2))**(Integer(-1)) * (Integer(3) + (Symbol('a'))**(Integer(-1)))), ((Integer(-1) * sympy.I) * (x)**((Integer(2) * Symbol('a')))))) * (((((Integer(-1) * sympy.I) * (x)**((Integer(2) * Symbol('a')))))**(((Integer(1) + (Integer(3) * Symbol('a'))) * ((Integer(2) * Symbol('a')))**(Integer(-1)))) * (Integer(4) * Symbol('a'))))**(Integer(-1))) + (Integer(-1) * ((sympy.I * (x)**((Integer(1) + (Integer(3) * Symbol('a')))) * sympy.Function('Gamma')(((Integer(2))**(Integer(-1)) * (Integer(3) + (Symbol('a'))**(Integer(-1)))), (sympy.I * (x)**((Integer(2) * Symbol('a')))))) * ((((sympy.I * (x)**((Integer(2) * Symbol('a')))))**(((Integer(1) + (Integer(3) * Symbol('a'))) * ((Integer(2) * Symbol('a')))**(Integer(-1)))) * (Integer(4) * Symbol('a'))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(sqrt(x)),
        variable=x,
        num_steps=3,
        integral=2*sqrt(x)*sin(sqrt(x)) + 2*cos(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=x*sqrt(x + 1),
        variable=x,
        num_steps=2,
        integral=2*(x + 1)**(sympy.S(5)/2)/5 - 2*(x + 1)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**(sympy.S(1)/3) + sqrt(x)),
        variable=x,
        num_steps=4,
        integral=6*x**(sympy.S(1)/6) - 3*x**(sympy.S(1)/3) + 2*sqrt(x) - 6*log(x**(sympy.S(1)/6) + 1),
    ),
    RubiTestSuiteCase(
        integrand=sqrt((x + 1)/(2*x + 3)),
        variable=x,
        num_steps=4,
        integral=sqrt(x + 1)*sqrt(2*x + 3)/2 - sqrt(2)*asinh(sqrt(2)*sqrt(x + 1))/4,
    ),
    RubiTestSuiteCase(
        integrand=x**4/(1 - x**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=x**3/(3*(1 - x**2)**(sympy.S(3)/2)) - x/sqrt(1 - x**2) + asin(x),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x)*(x + 1)**(sympy.S(5)/2),
        variable=x,
        num_steps=6,
        integral=x**(sympy.S(3)/2)*(x + 1)**(sympy.S(5)/2)/4 + 5*x**(sympy.S(3)/2)*(x + 1)**(sympy.S(3)/2)/24 + 5*x**(sympy.S(3)/2)*sqrt(x + 1)/32 + 5*sqrt(x)*sqrt(x + 1)/64 - 5*asinh(sqrt(x))/64,
    ),
    RubiTestSuiteCase(
        integrand=x**4/(1 - x**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=x**3/(3*(1 - x**2)**(sympy.S(3)/2)) - x/sqrt(1 - x**2) + asin(x),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(A**2 - B**2*y**2 + B**2)/(1 - y**2),
        variable=y,
        num_steps=5,
        integral=A*atanh(A*y/sqrt(A**2 - B**2*y**2 + B**2)) + B*atan(B*y/sqrt(A**2 - B**2*y**2 + B**2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2,
        variable=x,
        num_steps=2,
        integral=x/2 - sin(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(cos(x) + 1),
        variable=x,
        num_steps=1,
        integral=sin(x)/(cos(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=x*exp(x),
        variable=x,
        num_steps=2,
        integral=x*exp(x) - exp(x),
    ),
    RubiTestSuiteCase(
        integrand=x*exp(x)/(x + 1)**2,
        variable=x,
        num_steps=1,
        integral=exp(x)/(x + 1),
    ),
    RubiTestSuiteCase(
        integrand=(2*x**2 + 1)*exp(x**2),
        variable=x,
        num_steps=5,
        integral=x*exp(x**2),
    ),
    RubiTestSuiteCase(
        integrand=exp(x**2),
        variable=x,
        num_steps=1,
        integral=((Integer(2))**(Integer(-1)) * sympy.sqrt(sympy.pi) * sympy.Function('Erfi')(x)),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)/x,
        variable=x,
        num_steps=1,
        integral=sympy.Function('ExpIntegralEi')(x),
    ),
    RubiTestSuiteCase(
        integrand=x/(x**3 + 1),
        variable=x,
        num_steps=6,
        integral=-log(x + 1)/3 + log(x**2 - x + 1)/6 - sqrt(3)*atan(sqrt(3)*(1 - 2*x)/3)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/(A**4 - A**2*B**2 + x**2*(-A**2 + B**2)),
        variable=x,
        num_steps=1,
        integral=atanh(x/A)/(A*(A**2 - B**2)),
    ),
    RubiTestSuiteCase(
        integrand=x*log(x),
        variable=x,
        num_steps=1,
        integral=x**2*log(x)/2 - x**2/4,
    ),
    RubiTestSuiteCase(
        integrand=x**2*asin(x),
        variable=x,
        num_steps=4,
        integral=x**3*asin(x)/3 - (1 - x**2)**(sympy.S(3)/2)/9 + sqrt(1 - x**2)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2 + 2*x + 1),
        variable=x,
        num_steps=2,
        integral=-1/(x + 1),
    ),
    RubiTestSuiteCase(
        integrand=log(x)/(log(x) + 1)**2,
        variable=x,
        num_steps=7,
        integral=x/(log(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*(log(x)**2 + 1)),
        variable=x,
        num_steps=2,
        integral=atan(log(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/log(x),
        variable=x,
        num_steps=1,
        integral=sympy.Function('LogIntegral')(x),
    ),
    RubiTestSuiteCase(
        integrand=x*(sin(x) + cos(x)),
        variable=x,
        num_steps=6,
        integral=x*sin(x) - x*cos(x) + sin(x) + cos(x),
    ),
    RubiTestSuiteCase(
        integrand=(x + exp(x))*exp(-x),
        variable=x,
        num_steps=4,
        integral=x - x*exp(-x) - exp(-x),
    ),
    RubiTestSuiteCase(
        integrand=x*(exp(x) + 1)**2,
        variable=x,
        num_steps=6,
        integral=x**2/2 + x*exp(2*x)/2 + 2*x*exp(x) - exp(2*x)/4 - 2*exp(x),
    ),
    RubiTestSuiteCase(
        integrand=x*cos(x),
        variable=x,
        num_steps=2,
        integral=x*sin(x) + cos(x),
    ),
    RubiTestSuiteCase(
        integrand=cos(sqrt(x)),
        variable=x,
        num_steps=3,
        integral=2*sqrt(x)*sin(sqrt(x)) + 2*cos(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=x*cos(x),
        variable=x,
        num_steps=2,
        integral=x*sin(x) + cos(x),
    ),
    RubiTestSuiteCase(
        integrand=x*log(x)**2,
        variable=x,
        num_steps=2,
        integral=x**2*log(x)**2/2 - x**2*log(x)/2 + x**2/4,
    ),
    RubiTestSuiteCase(
        integrand=(sin(x)**3 + 1)*cos(x),
        variable=x,
        num_steps=2,
        integral=sin(x)**4/4 + sin(x),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*(log(x)**2 + 1)),
        variable=x,
        num_steps=2,
        integral=atan(log(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(1 - x**2)*(asin(x)**2 + 1)),
        variable=x,
        num_steps=2,
        integral=atan(asin(x)),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/(sin(x) + cos(x)),
        variable=x,
        num_steps=2,
        integral=x/2 - log(sin(x) + cos(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=-sqrt(A**2 + B**2*(1 - y**2))/(1 - y**2),
        variable=y,
        num_steps=6,
        integral=-A*atanh(A*y/sqrt(A**2 - B**2*y**2 + B**2)) - B*atan(B*y/sqrt(A**2 - B**2*y**2 + B**2)),
    ),
    RubiTestSuiteCase(
        integrand=(-A**2 - B**2)*cos(z)**2/(B*(1 - (A**2 + B**2)*sin(z)**2/B**2)),
        variable=z,
        num_steps=5,
        integral=-A*atanh(A*tan(z)/B) - B*z,
    ),
    RubiTestSuiteCase(
        integrand=(-A**2 - B**2)/(B*(1 - w**2*(A**2 + B**2)/(B**2*(w**2 + 1)))*(w**2 + 1)**2),
        variable=w,
        num_steps=6,
        integral=-A*atanh(A*w/B) - B*atan(w),
    ),
    RubiTestSuiteCase(
        integrand=-B*(A**2 + B**2)/((w**2 + 1)*(-A**2*w**2 + B**2)),
        variable=w,
        num_steps=4,
        integral=-A*atanh(A*w/B) - B*atan(w),
    ),
    RubiTestSuiteCase(
        integrand=x**4/(1 - x**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=x**3/(3*(1 - x**2)**(sympy.S(3)/2)) - x/sqrt(1 - x**2) + asin(x),
    ),
    RubiTestSuiteCase(
        integrand=sin(y)**4/cos(y)**4,
        variable=y,
        num_steps=3,
        integral=y + tan(y)**3/3 - tan(y),
    ),
    RubiTestSuiteCase(
        integrand=z**4/(z**2 + 1),
        variable=z,
        num_steps=3,
        integral=z**3/3 - z + atan(z),
    ),
    RubiTestSuiteCase(
        integrand=(2*x**2 + 1)*exp(x**2),
        variable=x,
        num_steps=5,
        integral=x*exp(x**2),
    ),
    RubiTestSuiteCase(
        integrand=(2*x**6 + 5*x**4 + x**3 + 4*x**2 + 1)*exp(x**2)/(x**2 + 1)**2,
        variable=x,
        num_steps=10,
        integral=x*exp(x**2) + exp(x**2)/(2*x**2 + 2),
    ),
    RubiTestSuiteCase(
        integrand=exp(-1)*exp(-x),
        variable=x,
        num_steps=1,
        integral=-exp(-x - 1),
    ),
    RubiTestSuiteCase(
        integrand=(x + 1/x)*log(x),
        variable=x,
        num_steps=5,
        integral=x**2*log(x)/2 - x**2/4 + log(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=x/(x**4 + 1),
        variable=x,
        num_steps=2,
        integral=atan(x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=x**5/(x**4 + 1),
        variable=x,
        num_steps=3,
        integral=x**2/2 - atan(x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(tan(x)**2 + 1),
        variable=x,
        num_steps=3,
        integral=x/2 + sin(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=x**4/(1 - x**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=x**3/(3*(1 - x**2)**(sympy.S(3)/2)) - x/sqrt(1 - x**2) + asin(x),
    ),
    RubiTestSuiteCase(
        integrand=-x**2/(1 - x**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=-x/sqrt(1 - x**2) + asin(x),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*sin(x),
        variable=x,
        num_steps=1,
        integral=exp(x)*sin(x)/2 - exp(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/x,
        variable=x,
        num_steps=1,
        integral=log(x),
    ),
    RubiTestSuiteCase(
        integrand=sec(2*t)/(3*tan(t) + sec(t)**2 + 1),
        variable=t,
        num_steps=4,
        integral=-log(-sin(t) + cos(t))/12 - log(sin(t) + cos(t))/4 + log(sin(t) + 2*cos(t))/3 - 1/(2*tan(t) + 2),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)**(-2),
        variable=x,
        num_steps=2,
        integral=x/2 + sin(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=(x**2 + 1)/sqrt(x),
        variable=x,
        num_steps=2,
        integral=2*x**(sympy.S(5)/2)/5 + 2*sqrt(x),
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(x**2 + 2*x + 5),
        variable=x,
        num_steps=3,
        integral=sqrt(x**2 + 2*x + 5) - asinh(x/2 + sympy.S.Half),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2*cos(x),
        variable=x,
        num_steps=2,
        integral=sin(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=exp(x)/(exp(x) + 1),
        variable=x,
        num_steps=2,
        integral=log(exp(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=exp(2*x)/(exp(x) + 1),
        variable=x,
        num_steps=3,
        integral=exp(x) - log(exp(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/(1 - cos(x)),
        variable=x,
        num_steps=1,
        integral=-sin(x)/(1 - cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)*sec(x)**2,
        variable=x,
        num_steps=2,
        integral=sec(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=x*log(x),
        variable=x,
        num_steps=1,
        integral=x**2*log(x)/2 - x**2/4,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)*cos(x),
        variable=x,
        num_steps=2,
        integral=sin(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=(x + 1)/sqrt(-x**2 + 2*x),
        variable=x,
        num_steps=3,
        integral=-sqrt(-x**2 + 2*x) + 2*asin(x - 1),
    ),
    RubiTestSuiteCase(
        integrand=2*exp(x)/(3*exp(2*x) + 2),
        variable=x,
        num_steps=3,
        integral=sqrt(6)*atan(sqrt(6)*exp(x)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=x**4/(1 - x**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=x**3/(3*(1 - x**2)**(sympy.S(3)/2)) - x/sqrt(1 - x**2) + asin(x),
    ),
    RubiTestSuiteCase(
        integrand=exp(6*x)/(exp(4*x) + 1),
        variable=x,
        num_steps=3,
        integral=exp(2*x)/2 - atan(exp(2*x))/2,
    ),
    RubiTestSuiteCase(
        integrand=log(3*x**2 + 2),
        variable=x,
        num_steps=3,
        integral=x*log(3*x**2 + 2) - 2*x + 2*sqrt(6)*atan(sqrt(6)*x/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/(r*sqrt(2*H*r**2 - a**2)),
        variable=x,
        num_steps=1,
        integral=x/(r*sqrt(2*H*r**2 - a**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(r*sqrt(2*H*r**2 - a**2 - e**2)),
        variable=x,
        num_steps=1,
        integral=x/(r*sqrt(2*H*r**2 - a**2 - e**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(r*sqrt(2*H*r**2 - 2*K*r**4 - a**2)),
        variable=x,
        num_steps=1,
        integral=x/(r*sqrt(2*H*r**2 - 2*K*r**4 - a**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(r*sqrt(2*H*r**2 - 2*K*r**4 - a**2 - e**2)),
        variable=x,
        num_steps=1,
        integral=x/(r*sqrt(2*H*r**2 - 2*K*r**4 - a**2 - e**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(r*sqrt(2*H*r**2 - 2*K*r - a**2)),
        variable=x,
        num_steps=1,
        integral=x/(r*sqrt(-a**2 - 2*r*(-H*r + K))),
    ),
    RubiTestSuiteCase(
        integrand=1/(r*sqrt(2*H*r**2 - 2*K*r - a**2 - e**2)),
        variable=x,
        num_steps=1,
        integral=x/(r*sqrt(-a**2 - e**2 - 2*r*(-H*r + K))),
    ),
    RubiTestSuiteCase(
        integrand=(Symbol('r') * (sympy.sqrt(((Integer(2) * sympy.E * (Symbol('r'))**(Integer(2))) + (Integer(-1) * (Symbol('a'))**(Integer(2))))))**(Integer(-1))),
        variable=x,
        num_steps=1,
        integral=((Symbol('r') * x) * (sympy.sqrt(((Integer(-1) * (Symbol('a'))**(Integer(2))) + (Integer(2) * sympy.E * (Symbol('r'))**(Integer(2))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(Symbol('r') * (sympy.sqrt(((Integer(2) * sympy.E * (Symbol('r'))**(Integer(2))) + (Integer(-1) * (Symbol('a'))**(Integer(2))) + (Integer(-1) * (Symbol('e'))**(Integer(2))))))**(Integer(-1))),
        variable=x,
        num_steps=1,
        integral=((Symbol('r') * x) * (sympy.sqrt(((Integer(-1) * (Symbol('a'))**(Integer(2))) + (Integer(-1) * (Symbol('e'))**(Integer(2))) + (Integer(2) * sympy.E * (Symbol('r'))**(Integer(2))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(Symbol('r') * (sympy.sqrt(((Integer(2) * sympy.E * (Symbol('r'))**(Integer(2))) + (Integer(-1) * (Symbol('a'))**(Integer(2))) + (Integer(-1) * (Integer(2) * Symbol('K') * (Symbol('r'))**(Integer(4)))))))**(Integer(-1))),
        variable=x,
        num_steps=1,
        integral=((Symbol('r') * x) * (sympy.sqrt(((Integer(-1) * (Symbol('a'))**(Integer(2))) + (Integer(2) * sympy.E * (Symbol('r'))**(Integer(2))) + (Integer(-1) * (Integer(2) * Symbol('K') * (Symbol('r'))**(Integer(4)))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(Symbol('r') * (sympy.sqrt(((Integer(2) * sympy.E * (Symbol('r'))**(Integer(2))) + (Integer(-1) * (Symbol('a'))**(Integer(2))) + (Integer(-1) * (Symbol('e'))**(Integer(2))) + (Integer(-1) * (Integer(2) * Symbol('K') * (Symbol('r'))**(Integer(4)))))))**(Integer(-1))),
        variable=x,
        num_steps=1,
        integral=((Symbol('r') * x) * (sympy.sqrt(((Integer(-1) * (Symbol('a'))**(Integer(2))) + (Integer(-1) * (Symbol('e'))**(Integer(2))) + (Integer(2) * sympy.E * (Symbol('r'))**(Integer(2))) + (Integer(-1) * (Integer(2) * Symbol('K') * (Symbol('r'))**(Integer(4)))))))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=r/sqrt(2*H*r**2 - 2*K*r - a**2 - e**2),
        variable=x,
        num_steps=1,
        integral=r*x/sqrt(-a**2 - e**2 - 2*r*(-H*r + K)),
    ),
]
