# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 0 Independent test suites/Stewart Problems.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '0 Independent test suites/Stewart Problems.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, c, n, t, y = symbols('a b c n t y')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=x**n,
        variable=x,
        num_steps=1,
        integral=x**(n + 1)/(n + 1),
    ),
    RubiTestSuiteCase(
        integrand=exp(x),
        variable=x,
        num_steps=1,
        integral=exp(x),
    ),
    RubiTestSuiteCase(
        integrand=1/x,
        variable=x,
        num_steps=1,
        integral=log(x),
    ),
    RubiTestSuiteCase(
        integrand=a**x,
        variable=x,
        num_steps=1,
        integral=a**x/log(a),
    ),
    RubiTestSuiteCase(
        integrand=sin(x),
        variable=x,
        num_steps=1,
        integral=-cos(x),
    ),
    RubiTestSuiteCase(
        integrand=cos(x),
        variable=x,
        num_steps=1,
        integral=sin(x),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)**2,
        variable=x,
        num_steps=2,
        integral=tan(x),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**2,
        variable=x,
        num_steps=2,
        integral=-cot(x),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)*sec(x),
        variable=x,
        num_steps=2,
        integral=sec(x),
    ),
    RubiTestSuiteCase(
        integrand=cot(x)*csc(x),
        variable=x,
        num_steps=2,
        integral=-csc(x),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x),
        variable=x,
        num_steps=1,
        integral=cosh(x),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x),
        variable=x,
        num_steps=1,
        integral=sinh(x),
    ),
    RubiTestSuiteCase(
        integrand=tan(x),
        variable=x,
        num_steps=1,
        integral=-log(cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=cot(x),
        variable=x,
        num_steps=1,
        integral=log(sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(x),
        variable=x,
        num_steps=2,
        integral=-x*cos(x) + sin(x),
    ),
    RubiTestSuiteCase(
        integrand=log(x),
        variable=x,
        num_steps=1,
        integral=x*log(x) - x,
    ),
    RubiTestSuiteCase(
        integrand=x**2*exp(x),
        variable=x,
        num_steps=3,
        integral=x**2*exp(x) - 2*x*exp(x) + 2*exp(x),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*sin(x),
        variable=x,
        num_steps=1,
        integral=exp(x)*sin(x)/2 - exp(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=atan(x),
        variable=x,
        num_steps=2,
        integral=x*atan(x) - log(x**2 + 1)/2,
    ),
    RubiTestSuiteCase(
        integrand=x*exp(2*x),
        variable=x,
        num_steps=2,
        integral=x*exp(2*x)/2 - exp(2*x)/4,
    ),
    RubiTestSuiteCase(
        integrand=x*cos(x),
        variable=x,
        num_steps=2,
        integral=x*sin(x) + cos(x),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(4*x),
        variable=x,
        num_steps=2,
        integral=-x*cos(4*x)/4 + sin(4*x)/16,
    ),
    RubiTestSuiteCase(
        integrand=x*log(x),
        variable=x,
        num_steps=1,
        integral=x**2*log(x)/2 - x**2/4,
    ),
    RubiTestSuiteCase(
        integrand=x**2*cos(3*x),
        variable=x,
        num_steps=3,
        integral=x**2*sin(3*x)/3 + 2*x*cos(3*x)/9 - 2*sin(3*x)/27,
    ),
    RubiTestSuiteCase(
        integrand=x**2*sin(2*x),
        variable=x,
        num_steps=3,
        integral=-x**2*cos(2*x)/2 + x*sin(2*x)/2 + cos(2*x)/4,
    ),
    RubiTestSuiteCase(
        integrand=log(x)**2,
        variable=x,
        num_steps=2,
        integral=x*log(x)**2 - 2*x*log(x) + 2*x,
    ),
    RubiTestSuiteCase(
        integrand=asin(x),
        variable=x,
        num_steps=2,
        integral=x*asin(x) + sqrt(1 - x**2),
    ),
    RubiTestSuiteCase(
        integrand=t*sin(t)*cos(t),
        variable=t,
        num_steps=3,
        integral=t*sin(t)**2/2 - t/4 + sin(t)*cos(t)/4,
    ),
    RubiTestSuiteCase(
        integrand=t*sec(t)**2,
        variable=t,
        num_steps=2,
        integral=t*tan(t) + log(cos(t)),
    ),
    RubiTestSuiteCase(
        integrand=t**2*log(t),
        variable=t,
        num_steps=1,
        integral=t**3*log(t)/3 - t**3/9,
    ),
    RubiTestSuiteCase(
        integrand=t**3*exp(t),
        variable=t,
        num_steps=4,
        integral=t**3*exp(t) - 3*t**2*exp(t) + 6*t*exp(t) - 6*exp(t),
    ),
    RubiTestSuiteCase(
        integrand=exp(2*t)*sin(3*t),
        variable=t,
        num_steps=1,
        integral=2*exp(2*t)*sin(3*t)/13 - 3*exp(2*t)*cos(3*t)/13,
    ),
    RubiTestSuiteCase(
        integrand=exp(-t)*cos(3*t),
        variable=t,
        num_steps=1,
        integral=3*exp(-t)*sin(3*t)/10 - exp(-t)*cos(3*t)/10,
    ),
    RubiTestSuiteCase(
        integrand=y*sinh(y),
        variable=y,
        num_steps=2,
        integral=y*cosh(y) - sinh(y),
    ),
    RubiTestSuiteCase(
        integrand=y*cosh(a*y),
        variable=y,
        num_steps=2,
        integral=y*sinh(a*y)/a - cosh(a*y)/a**2,
    ),
    RubiTestSuiteCase(
        integrand=t*exp(-t),
        variable=t,
        num_steps=2,
        integral=-t*exp(-t) - exp(-t),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(t)*log(t),
        variable=t,
        num_steps=1,
        integral=2*t**(sympy.S(3)/2)*log(t)/3 - 4*t**(sympy.S(3)/2)/9,
    ),
    RubiTestSuiteCase(
        integrand=x*cos(2*x),
        variable=x,
        num_steps=2,
        integral=x*sin(2*x)/2 + cos(2*x)/4,
    ),
    RubiTestSuiteCase(
        integrand=x**2*exp(-x),
        variable=x,
        num_steps=3,
        integral=-x**2*exp(-x) - 2*x*exp(-x) - 2*exp(-x),
    ),
    RubiTestSuiteCase(
        integrand=acos(x),
        variable=x,
        num_steps=2,
        integral=x*acos(x) - sqrt(1 - x**2),
    ),
    RubiTestSuiteCase(
        integrand=x*csc(x)**2,
        variable=x,
        num_steps=2,
        integral=-x*cot(x) + log(sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=sin(3*x)*cos(5*x),
        variable=x,
        num_steps=1,
        integral=cos(2*x)/4 - cos(8*x)/16,
    ),
    RubiTestSuiteCase(
        integrand=sin(2*x)*sin(4*x),
        variable=x,
        num_steps=1,
        integral=sin(2*x)/4 - sin(6*x)/12,
    ),
    RubiTestSuiteCase(
        integrand=log(sin(x))*cos(x),
        variable=x,
        num_steps=2,
        integral=log(sin(x))*sin(x) - sin(x),
    ),
    RubiTestSuiteCase(
        integrand=x**3*exp(x**2),
        variable=x,
        num_steps=2,
        integral=x**2*exp(x**2)/2 - exp(x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=(2*x + 3)*exp(x),
        variable=x,
        num_steps=2,
        integral=(2*x + 3)*exp(x) - 2*exp(x),
    ),
    RubiTestSuiteCase(
        integrand=5**x*x,
        variable=x,
        num_steps=2,
        integral=5**x*x/log(5) - 5**x/log(5)**2,
    ),
    RubiTestSuiteCase(
        integrand=cos(log(x)),
        variable=x,
        num_steps=1,
        integral=x*sin(log(x))/2 + x*cos(log(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=exp(sqrt(x)),
        variable=x,
        num_steps=3,
        integral=2*sqrt(x)*exp(sqrt(x)) - 2*exp(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=log(sqrt(x)),
        variable=x,
        num_steps=1,
        integral=x*log(sqrt(x)) - x/2,
    ),
    RubiTestSuiteCase(
        integrand=sin(log(x)),
        variable=x,
        num_steps=1,
        integral=x*sin(log(x))/2 - x*cos(log(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=sin(sqrt(x)),
        variable=x,
        num_steps=3,
        integral=-2*sqrt(x)*cos(sqrt(x)) + 2*sin(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=x**5*cos(x**3),
        variable=x,
        num_steps=3,
        integral=x**3*sin(x**3)/3 + cos(x**3)/3,
    ),
    RubiTestSuiteCase(
        integrand=x**5*exp(x**2),
        variable=x,
        num_steps=3,
        integral=x**4*exp(x**2)/2 - x**2*exp(x**2) + exp(x**2),
    ),
    RubiTestSuiteCase(
        integrand=x*atan(x),
        variable=x,
        num_steps=3,
        integral=x**2*atan(x)/2 - x/2 + atan(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=x*cos(pi*x),
        variable=x,
        num_steps=2,
        integral=x*sin(pi*x)/pi + cos(pi*x)/pi**2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x)*log(x),
        variable=x,
        num_steps=1,
        integral=2*x**(sympy.S(3)/2)*log(x)/3 - 4*x**(sympy.S(3)/2)/9,
    ),
    RubiTestSuiteCase(
        integrand=sin(3*x)**2,
        variable=x,
        num_steps=2,
        integral=x/2 - sin(3*x)*cos(3*x)/6,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**2,
        variable=x,
        num_steps=2,
        integral=x/2 + sin(x)*cos(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**4,
        variable=x,
        num_steps=3,
        integral=3*x/8 + sin(x)*cos(x)**3/4 + 3*sin(x)*cos(x)/8,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3,
        variable=x,
        num_steps=2,
        integral=cos(x)**3/3 - cos(x),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3*cos(x)**4,
        variable=x,
        num_steps=3,
        integral=cos(x)**7/7 - cos(x)**5/5,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**4*cos(x)**3,
        variable=x,
        num_steps=3,
        integral=-sin(x)**7/7 + sin(x)**5/5,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**4*cos(x)**2,
        variable=x,
        num_steps=4,
        integral=x/16 - sin(x)**3*cos(x)**3/6 - sin(x)*cos(x)**3/8 + sin(x)*cos(x)/16,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2*cos(x)**2,
        variable=x,
        num_steps=3,
        integral=x/8 - sin(x)*cos(x)**3/4 + sin(x)*cos(x)/8,
    ),
    RubiTestSuiteCase(
        integrand=(1 - sin(2*x))**2,
        variable=x,
        num_steps=1,
        integral=3*x/2 - sin(2*x)*cos(2*x)/4 + cos(2*x),
    ),
    RubiTestSuiteCase(
        integrand=sin(x + pi/6)*cos(x),
        variable=x,
        num_steps=3,
        integral=x/4 - cos(2*x + pi/6)/4,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**5*cos(x)**5,
        variable=x,
        num_steps=4,
        integral=sin(x)**10/10 - sin(x)**8/4 + sin(x)**6/6,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**6,
        variable=x,
        num_steps=4,
        integral=5*x/16 - sin(x)**5*cos(x)/6 - 5*sin(x)**3*cos(x)/24 - 5*sin(x)*cos(x)/16,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**6,
        variable=x,
        num_steps=4,
        integral=5*x/16 + sin(x)*cos(x)**5/6 + 5*sin(x)*cos(x)**3/24 + 5*sin(x)*cos(x)/16,
    ),
    RubiTestSuiteCase(
        integrand=sin(2*x)**2*cos(2*x)**4,
        variable=x,
        num_steps=4,
        integral=x/16 - sin(2*x)*cos(2*x)**5/12 + sin(2*x)*cos(2*x)**3/48 + sin(2*x)*cos(2*x)/32,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**5,
        variable=x,
        num_steps=2,
        integral=-cos(x)**5/5 + 2*cos(x)**3/3 - cos(x),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**4*cos(x)**4,
        variable=x,
        num_steps=5,
        integral=3*x/128 - sin(x)**3*cos(x)**5/8 - sin(x)*cos(x)**5/16 + sin(x)*cos(x)**3/64 + 3*sin(x)*cos(x)/128,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3*sqrt(cos(x)),
        variable=x,
        num_steps=3,
        integral=2*cos(x)**(sympy.S(7)/2)/7 - 2*cos(x)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(sin(x))*cos(x)**3,
        variable=x,
        num_steps=3,
        integral=-2*sin(x)**(sympy.S(7)/2)/7 + 2*sin(x)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=cos(sqrt(x))**2/sqrt(x),
        variable=x,
        num_steps=3,
        integral=sqrt(x) + sin(sqrt(x))*cos(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=x*sin(x**2)**3,
        variable=x,
        num_steps=3,
        integral=cos(x**2)**3/6 - cos(x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**2*tan(x)**3,
        variable=x,
        num_steps=3,
        integral=-log(cos(x)) + cos(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2*cot(x)**5,
        variable=x,
        num_steps=4,
        integral=-2*log(sin(x)) + sin(x)**2/2 - csc(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=(1 - sin(x))/cos(x),
        variable=x,
        num_steps=2,
        integral=log(sin(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/(1 - sin(x)),
        variable=x,
        num_steps=1,
        integral=cos(x)/(1 - sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**2,
        variable=x,
        num_steps=2,
        integral=-x + tan(x),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**4,
        variable=x,
        num_steps=3,
        integral=x + tan(x)**3/3 - tan(x),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)**4,
        variable=x,
        num_steps=2,
        integral=tan(x)**3/3 + tan(x),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)**6,
        variable=x,
        num_steps=2,
        integral=tan(x)**5/5 + 2*tan(x)**3/3 + tan(x),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**4*sec(x)**2,
        variable=x,
        num_steps=2,
        integral=tan(x)**5/5,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**2*sec(x)**4,
        variable=x,
        num_steps=3,
        integral=tan(x)**5/5 + tan(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)*sec(x)**3,
        variable=x,
        num_steps=2,
        integral=sec(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**3*sec(x)**3,
        variable=x,
        num_steps=3,
        integral=sec(x)**5/5 - sec(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**5,
        variable=x,
        num_steps=3,
        integral=-log(cos(x)) + tan(x)**4/4 - tan(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**6,
        variable=x,
        num_steps=4,
        integral=-x + tan(x)**5/5 - tan(x)**3/3 + tan(x),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**5*sec(x),
        variable=x,
        num_steps=3,
        integral=sec(x)**5/5 - 2*sec(x)**3/3 + sec(x),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**5*sec(x)**3,
        variable=x,
        num_steps=3,
        integral=sec(x)**7/7 - 2*sec(x)**5/5 + sec(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)*sec(x)**6,
        variable=x,
        num_steps=2,
        integral=sec(x)**6/6,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**3*sec(x)**6,
        variable=x,
        num_steps=3,
        integral=sec(x)**8/8 - sec(x)**6/6,
    ),
    RubiTestSuiteCase(
        integrand=sec(x)**2/cot(x),
        variable=x,
        num_steps=2,
        integral=sec(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**2*sec(x),
        variable=x,
        num_steps=2,
        integral=tan(x)*sec(x)/2 - atanh(sin(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=cot(x)**2,
        variable=x,
        num_steps=2,
        integral=-x - cot(x),
    ),
    RubiTestSuiteCase(
        integrand=cot(x)**3,
        variable=x,
        num_steps=2,
        integral=-log(sin(x)) - cot(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=cot(x)**4*csc(x)**4,
        variable=x,
        num_steps=3,
        integral=-cot(x)**7/7 - cot(x)**5/5,
    ),
    RubiTestSuiteCase(
        integrand=cot(x)**3*csc(x)**4,
        variable=x,
        num_steps=3,
        integral=-csc(x)**6/6 + csc(x)**4/4,
    ),
    RubiTestSuiteCase(
        integrand=csc(x),
        variable=x,
        num_steps=1,
        integral=-atanh(cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**3,
        variable=x,
        num_steps=2,
        integral=-cot(x)*csc(x)/2 - atanh(cos(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**2/sin(x),
        variable=x,
        num_steps=3,
        integral=cos(x) - atanh(cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**(-4),
        variable=x,
        num_steps=2,
        integral=-cot(x)**3/3 - cot(x),
    ),
    RubiTestSuiteCase(
        integrand=sin(2*x)*sin(5*x),
        variable=x,
        num_steps=1,
        integral=sin(3*x)/6 - sin(7*x)/14,
    ),
    RubiTestSuiteCase(
        integrand=sin(3*x)*cos(x),
        variable=x,
        num_steps=1,
        integral=-cos(2*x)/4 - cos(4*x)/8,
    ),
    RubiTestSuiteCase(
        integrand=cos(3*x)*cos(4*x),
        variable=x,
        num_steps=1,
        integral=sin(x)/2 + sin(7*x)/14,
    ),
    RubiTestSuiteCase(
        integrand=sin(3*x)*sin(6*x),
        variable=x,
        num_steps=1,
        integral=sin(3*x)/6 - sin(9*x)/18,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)*cos(x)**5,
        variable=x,
        num_steps=2,
        integral=-cos(x)**6/6,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)*cos(2*x)*cos(3*x),
        variable=x,
        num_steps=5,
        integral=x/4 + sin(2*x)/8 + sin(4*x)/16 + sin(6*x)/24,
    ),
    RubiTestSuiteCase(
        integrand=(1 - tan(x)**2)/sec(x)**2,
        variable=x,
        num_steps=2,
        integral=sin(x)*cos(x),
    ),
    RubiTestSuiteCase(
        integrand=(sin(x) + cos(x))/sin(2*x),
        variable=x,
        num_steps=6,
        integral=atanh(sin(x))/2 - atanh(cos(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2*tan(x),
        variable=x,
        num_steps=3,
        integral=-log(cos(x)) + cos(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**2*cot(x)**3,
        variable=x,
        num_steps=4,
        integral=-2*log(sin(x)) + sin(x)**2/2 - csc(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)*sec(x)**3,
        variable=x,
        num_steps=2,
        integral=sec(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**3*sec(x)**3,
        variable=x,
        num_steps=3,
        integral=sec(x)**5/5 - sec(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(9 - x**2)/x**2,
        variable=x,
        num_steps=2,
        integral=-asin(x/3) - sqrt(9 - x**2)/x,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*sqrt(x**2 + 4)),
        variable=x,
        num_steps=1,
        integral=-sqrt(x**2 + 4)/(4*x),
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(x**2 + 4),
        variable=x,
        num_steps=1,
        integral=sqrt(x**2 + 4),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-a**2 + x**2),
        variable=x,
        num_steps=2,
        integral=atanh(x/sqrt(-a**2 + x**2)),
    ),
    RubiTestSuiteCase(
        integrand=x**3/(4*x**2 + 9)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=sqrt(4*x**2 + 9)/16 + 9/(16*sqrt(4*x**2 + 9)),
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(-x**2 - 2*x + 3),
        variable=x,
        num_steps=3,
        integral=-sqrt(-x**2 - 2*x + 3) - asin(x/2 + sympy.S.Half),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*sqrt(1 - x**2)),
        variable=x,
        num_steps=1,
        integral=-sqrt(1 - x**2)/x,
    ),
    RubiTestSuiteCase(
        integrand=x**3*sqrt(4 - x**2),
        variable=x,
        num_steps=3,
        integral=(4 - x**2)**(sympy.S(5)/2)/5 - 4*(4 - x**2)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(1 - x**2),
        variable=x,
        num_steps=1,
        integral=-sqrt(1 - x**2),
    ),
    RubiTestSuiteCase(
        integrand=x*sqrt(4 - x**2),
        variable=x,
        num_steps=1,
        integral=-(4 - x**2)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(1 - 4*x**2),
        variable=x,
        num_steps=2,
        integral=x*sqrt(1 - 4*x**2)/2 + asin(2*x)/4,
    ),
    RubiTestSuiteCase(
        integrand=x**3/sqrt(x**2 + 4),
        variable=x,
        num_steps=3,
        integral=(x**2 + 4)**(sympy.S(3)/2)/3 - 4*sqrt(x**2 + 4),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(x**2 + 9),
        variable=x,
        num_steps=1,
        integral=asinh(x/3),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x**2 + 1),
        variable=x,
        num_steps=2,
        integral=x*sqrt(x**2 + 1)/2 + asinh(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3*sqrt(x**2 - 16)),
        variable=x,
        num_steps=4,
        integral=atan(sqrt(x**2 - 16)/4)/128 + sqrt(x**2 - 16)/(32*x**2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-a**2 + x**2)/x**4,
        variable=x,
        num_steps=1,
        integral=(-a**2 + x**2)**(sympy.S(3)/2)/(3*a**2*x**3),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(9*x**2 - 4)/x,
        variable=x,
        num_steps=4,
        integral=sqrt(9*x**2 - 4) - 2*atan(sqrt(9*x**2 - 4)/2),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*sqrt(16*x**2 - 9)),
        variable=x,
        num_steps=1,
        integral=sqrt(16*x**2 - 9)/(9*x),
    ),
    RubiTestSuiteCase(
        integrand=x**2/(a**2 - x**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=x/sqrt(a**2 - x**2) - atan(x/sqrt(a**2 - x**2)),
    ),
    RubiTestSuiteCase(
        integrand=x**2/sqrt(5 - x**2),
        variable=x,
        num_steps=2,
        integral=-x*sqrt(5 - x**2)/2 + 5*asin(sqrt(5)*x/5)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(x**2 + 3)),
        variable=x,
        num_steps=3,
        integral=-sqrt(3)*atanh(sqrt(3)*sqrt(x**2 + 3)/3)/3,
    ),
    RubiTestSuiteCase(
        integrand=x/(x**2 + 4)**(sympy.S(5)/2),
        variable=x,
        num_steps=1,
        integral=-1/(3*(x**2 + 4)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=x**3*sqrt(4 - 9*x**2),
        variable=x,
        num_steps=3,
        integral=(4 - 9*x**2)**(sympy.S(5)/2)/405 - 4*(4 - 9*x**2)**(sympy.S(3)/2)/243,
    ),
    RubiTestSuiteCase(
        integrand=x**2*sqrt(9 - x**2),
        variable=x,
        num_steps=3,
        integral=x**3*sqrt(9 - x**2)/4 - 9*x*sqrt(9 - x**2)/8 + 81*asin(x/3)/8,
    ),
    RubiTestSuiteCase(
        integrand=5*x*sqrt(x**2 + 1),
        variable=x,
        num_steps=2,
        integral=5*(x**2 + 1)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=(4*x**2 - 25)**(sympy.S(-3)/2),
        variable=x,
        num_steps=1,
        integral=-x/(25*sqrt(4*x**2 - 25)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-x**2 + 2*x),
        variable=x,
        num_steps=3,
        integral=(x/2 + sympy.S(-1)/2)*sqrt(-x**2 + 2*x) + asin(x - 1)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(x**2 + 4*x + 8),
        variable=x,
        num_steps=2,
        integral=asinh(x/2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(9*x**2 + 6*x - 8),
        variable=x,
        num_steps=2,
        integral=atanh((3*x + 1)/sqrt(9*x**2 + 6*x - 8))/3,
    ),
    RubiTestSuiteCase(
        integrand=x**2/sqrt(-x**2 + 4*x),
        variable=x,
        num_steps=4,
        integral=-x*sqrt(-x**2 + 4*x)/2 - 3*sqrt(-x**2 + 4*x) + 6*asin(x/2 - 1),
    ),
    RubiTestSuiteCase(
        integrand=(x**2 + 2*x + 2)**(-2),
        variable=x,
        num_steps=3,
        integral=(x + 1)/(2*x**2 + 4*x + 4) + atan(x + 1)/2,
    ),
    RubiTestSuiteCase(
        integrand=(-x**2 - 4*x + 5)**(sympy.S(-5)/2),
        variable=x,
        num_steps=2,
        integral=(x + 2)/(27*(-x**2 - 4*x + 5)**(sympy.S(3)/2)) + (2*x + 4)/(243*sqrt(-x**2 - 4*x + 5)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(9 - exp(2*t))*exp(t),
        variable=t,
        num_steps=3,
        integral=sqrt(9 - exp(2*t))*exp(t)/2 + 9*asin(exp(t)/3)/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(exp(2*t) - 9),
        variable=t,
        num_steps=4,
        integral=sqrt(exp(2*t) - 9) - 3*atan(sqrt(exp(2*t) - 9)/3),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a**2 + x**2),
        variable=x,
        num_steps=2,
        integral=atanh(x/sqrt(a**2 + x**2)),
    ),
    RubiTestSuiteCase(
        integrand=(x + 5)/(x**2 + x - 2),
        variable=x,
        num_steps=3,
        integral=2*log(1 - x) - log(x + 2),
    ),
    RubiTestSuiteCase(
        integrand=(x**3 + x)/(x - 1),
        variable=x,
        num_steps=3,
        integral=x**3/3 + x**2/2 + 2*x + 2*log(1 - x),
    ),
    RubiTestSuiteCase(
        integrand=(x**2 + 2*x - 1)/(2*x**3 + 3*x**2 - 2*x),
        variable=x,
        num_steps=3,
        integral=log(x)/2 + log(1 - 2*x)/10 - log(x + 2)/10,
    ),
    RubiTestSuiteCase(
        integrand=(x**4 - 2*x**2 + 4*x + 1)/(x**3 - x**2 - x + 1),
        variable=x,
        num_steps=2,
        integral=x**2/2 + x + log(1 - x) - log(x + 1) + 2/(1 - x),
    ),
    RubiTestSuiteCase(
        integrand=(2*x**2 - x + 4)/(x**3 + 4*x),
        variable=x,
        num_steps=6,
        integral=log(x) + log(x**2 + 4)/2 - atan(x/2)/2,
    ),
    RubiTestSuiteCase(
        integrand=(4*x**2 - 3*x + 2)/(4*x**2 - 4*x + 3),
        variable=x,
        num_steps=6,
        integral=x + log(4*x**2 - 4*x + 3)/8 + sqrt(2)*atan(sqrt(2)*(1 - 2*x)/2)/8,
    ),
    RubiTestSuiteCase(
        integrand=(x**3 + x**2 + 1)/(x*(x - 1)*(x**2 + 1)**3*(x**2 + x + 1)),
        variable=x,
        num_steps=14,
        integral=3*x/(16*x**2 + 16) - (3 - 3*x)/(8*x**2 + 8) + (x + 1)/(8*(x**2 + 1)**2) - log(x) + log(1 - x)/8 + 15*log(x**2 + 1)/16 - log(x**2 + x + 1)/2 + 7*atan(x)/16 - sqrt(3)*atan(sqrt(3)*(2*x + 1)/3)/3,
    ),
    RubiTestSuiteCase(
        integrand=(-x**3 + 2*x**2 - 3*x + 1)/(x*(x**2 + 1)**2),
        variable=x,
        num_steps=6,
        integral=-(2*x + 1)/(2*x**2 + 2) + log(x) - log(x**2 + 1)/2 - 2*atan(x),
    ),
    RubiTestSuiteCase(
        integrand=(x**2 + 1)**(-2),
        variable=x,
        num_steps=2,
        integral=x/(2*x**2 + 2) + atan(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/((x - 1)*(x + 2)),
        variable=x,
        num_steps=3,
        integral=log(1 - x)/3 - log(x + 2)/3,
    ),
    RubiTestSuiteCase(
        integrand=7/(2*x**2 + 5*x - 12),
        variable=x,
        num_steps=4,
        integral=7*log(3 - 2*x)/11 - 7*log(x + 4)/11,
    ),
    RubiTestSuiteCase(
        integrand=(x**2 + 3*x - 4)/((2*x - 1)**2*(2*x + 3)),
        variable=x,
        num_steps=2,
        integral=41*log(1 - 2*x)/128 - 25*log(2*x + 3)/128 - 9/(32 - 64*x),
    ),
    RubiTestSuiteCase(
        integrand=(x**3 - x**2)/((x - 6)*(5*x + 3)**3),
        variable=x,
        num_steps=3,
        integral=20*log(6 - x)/3993 + 1493*log(5*x + 3)/499125 + 201/(75625*x + 45375) - 12/(1375*(5*x + 3)**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 - x**3),
        variable=x,
        num_steps=3,
        integral=-log(x) + log(1 - x) + 1/x + 1/(2*x**2),
    ),
    RubiTestSuiteCase(
        integrand=(x**4 + x**3 - x**2 - x + 1)/(x**3 - x),
        variable=x,
        num_steps=4,
        integral=x**2/2 + x - log(x) + log(1 - x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=(x**2 - 2)/(x*(x**2 + 2)),
        variable=x,
        num_steps=3,
        integral=-log(x) + log(x**2 + 2),
    ),
    RubiTestSuiteCase(
        integrand=(x**3 - 4*x**2 + 2)/((x**2 + 1)*(x**2 + 2)),
        variable=x,
        num_steps=8,
        integral=-log(x**2 + 1)/2 + log(x**2 + 2) + 6*atan(x) - 5*sqrt(2)*atan(sqrt(2)*x/2),
    ),
    RubiTestSuiteCase(
        integrand=(x**4 + x**2 + 1)/((x**2 + 1)*(x**2 + 4)**2),
        variable=x,
        num_steps=6,
        integral=-13*x/(24*x**2 + 96) + 25*atan(x/2)/144 + atan(x)/9,
    ),
    RubiTestSuiteCase(
        integrand=(16*x + 1)/((x + 5)**2*(2*x - 3)*(x**2 + x + 1)),
        variable=x,
        num_steps=6,
        integral=200*log(3 - 2*x)/3211 + 2731*log(x + 5)/24843 - 481*log(x**2 + x + 1)/5586 + 451*sqrt(3)*atan(sqrt(3)*(2*x + 1)/3)/8379 - 79/(273*x + 1365),
    ),
    RubiTestSuiteCase(
        integrand=x**4/(x**2 + 9)**3,
        variable=x,
        num_steps=3,
        integral=-x**3/(4*(x**2 + 9)**2) - 3*x/(8*x**2 + 72) + atan(x/3)/8,
    ),
    RubiTestSuiteCase(
        integrand=19*x/((x - 1)**3*(4*x**2 + 5*x + 3)**2),
        variable=x,
        num_steps=8,
        integral=209*log(1 - x)/2304 - 209*log(4*x**2 + 5*x + 3)/4608 + 114437*sqrt(23)*atan(sqrt(23)*(8*x + 5)/23)/1218816 - 1843/(4416 - 4416*x) + (836*x + 741)/(276*(1 - x)**2*(4*x**2 + 5*x + 3)) - 399/(736*(1 - x)**2),
    ),
    RubiTestSuiteCase(
        integrand=(x**3 + x**2 + 1)/(x**4 + x**3 + 2*x**2),
        variable=x,
        num_steps=7,
        integral=-log(x)/4 + 5*log(x**2 + x + 2)/8 + sqrt(7)*atan(sqrt(7)*(2*x + 1)/7)/28 - 1/(2*x),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**6 - x**3),
        variable=x,
        num_steps=8,
        integral=log(1 - x)/3 - log(x**2 + x + 1)/6 - sqrt(3)*atan(sqrt(3)*(2*x + 1)/3)/3 + 1/(2*x**2),
    ),
    RubiTestSuiteCase(
        integrand=x**2/(x + 1),
        variable=x,
        num_steps=2,
        integral=x**2/2 - x + log(x + 1),
    ),
    RubiTestSuiteCase(
        integrand=x/(x - 5),
        variable=x,
        num_steps=2,
        integral=x + 5*log(5 - x),
    ),
    RubiTestSuiteCase(
        integrand=(4*x - 1)/((x - 1)*(x + 2)),
        variable=x,
        num_steps=2,
        integral=log(1 - x) + 3*log(x + 2),
    ),
    RubiTestSuiteCase(
        integrand=1/((x + 1)*(x + 2)),
        variable=x,
        num_steps=3,
        integral=log(x + 1) - log(x + 2),
    ),
    RubiTestSuiteCase(
        integrand=(6*x - 5)/(2*x + 3),
        variable=x,
        num_steps=2,
        integral=3*x - 7*log(2*x + 3),
    ),
    RubiTestSuiteCase(
        integrand=1/((a + x)*(b + x)),
        variable=x,
        num_steps=3,
        integral=-log(a + x)/(a - b) + log(b + x)/(a - b),
    ),
    RubiTestSuiteCase(
        integrand=(x**2 + 1)/(x**2 - x),
        variable=x,
        num_steps=3,
        integral=x - log(x) + 2*log(1 - x),
    ),
    RubiTestSuiteCase(
        integrand=(x**3 + x**2 - 12*x + 1)/(x**2 + x - 12),
        variable=x,
        num_steps=5,
        integral=x**2/2 + log(3 - x)/7 - log(x + 4)/7,
    ),
    RubiTestSuiteCase(
        integrand=(2*x + 3)/(x + 1)**2,
        variable=x,
        num_steps=2,
        integral=2*log(x + 1) - 1/(x + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*(x + 1)*(2*x + 3)),
        variable=x,
        num_steps=2,
        integral=log(x)/3 - log(x + 1) + 2*log(2*x + 3)/3,
    ),
    RubiTestSuiteCase(
        integrand=(6*x**2 + 5*x - 3)/(x**3 + 2*x**2 - 3*x),
        variable=x,
        num_steps=3,
        integral=log(x) + 2*log(1 - x) + 3*log(x + 3),
    ),
    RubiTestSuiteCase(
        integrand=x/(x**2 + 4*x + 4),
        variable=x,
        num_steps=3,
        integral=log(x + 2) + 2/(x + 2),
    ),
    RubiTestSuiteCase(
        integrand=1/((x - 1)**2*(x + 4)),
        variable=x,
        num_steps=2,
        integral=-log(1 - x)/25 + log(x + 4)/25 + 1/(5 - 5*x),
    ),
    RubiTestSuiteCase(
        integrand=x**2/((x - 3)*(x + 2)**2),
        variable=x,
        num_steps=2,
        integral=9*log(3 - x)/25 + 16*log(x + 2)/25 + 4/(5*x + 10),
    ),
    RubiTestSuiteCase(
        integrand=(5*x**2 + 3*x - 2)/(x**3 + 2*x**2),
        variable=x,
        num_steps=3,
        integral=2*log(x) + 3*log(x + 2) + 1/x,
    ),
    RubiTestSuiteCase(
        integrand=(-4*x**2 - 2*x + 18)/(x**3 + 4*x**2 + x - 6),
        variable=x,
        num_steps=2,
        integral=log(1 - x) - 2*log(x + 2) - 3*log(x + 3),
    ),
    RubiTestSuiteCase(
        integrand=(x**2 + 2*x)/(x**3 + 3*x**2 + 4),
        variable=x,
        num_steps=1,
        integral=log(x**3 + 3*x**2 + 4)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2*(x - 1)**2),
        variable=x,
        num_steps=2,
        integral=2*log(x) - 2*log(1 - x) + 1/(1 - x) - 1/x,
    ),
    RubiTestSuiteCase(
        integrand=x**2/(x + 1)**3,
        variable=x,
        num_steps=2,
        integral=log(x + 1) + 2/(x + 1) - 1/(2*(x + 1)**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**4 - x**2),
        variable=x,
        num_steps=3,
        integral=-atanh(x) + 1/x,
    ),
    RubiTestSuiteCase(
        integrand=(2*x**3 - x)/(x**4 - x**2 + 1),
        variable=x,
        num_steps=1,
        integral=log(x**4 - x**2 + 1)/2,
    ),
    RubiTestSuiteCase(
        integrand=x**3/(x**2 + 1),
        variable=x,
        num_steps=3,
        integral=x**2/2 - log(x**2 + 1)/2,
    ),
    RubiTestSuiteCase(
        integrand=(x - 1)/(x**2 + 2*x + 2),
        variable=x,
        num_steps=4,
        integral=log(x**2 + 2*x + 2)/2 - 2*atan(x + 1),
    ),
    RubiTestSuiteCase(
        integrand=x/(x**2 + x + 1),
        variable=x,
        num_steps=4,
        integral=log(x**2 + x + 1)/2 - sqrt(3)*atan(sqrt(3)*(2*x + 1)/3)/3,
    ),
    RubiTestSuiteCase(
        integrand=(4*x**2 + 5*x + 7)/(4*x**2 + 4*x + 5),
        variable=x,
        num_steps=6,
        integral=x + log(4*x**2 + 4*x + 5)/8 + 3*atan(x + sympy.S.Half)/8,
    ),
    RubiTestSuiteCase(
        integrand=(3*x**2 - 4*x + 5)/((x - 1)*(x**2 + 1)),
        variable=x,
        num_steps=5,
        integral=2*log(1 - x) + log(x**2 + 1)/2 - 3*atan(x),
    ),
    RubiTestSuiteCase(
        integrand=(2*x + 3)/(x**3 + 3*x),
        variable=x,
        num_steps=6,
        integral=log(x) - log(x**2 + 3)/2 + 2*sqrt(3)*atan(sqrt(3)*x/3)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3 - 1),
        variable=x,
        num_steps=6,
        integral=log(1 - x)/3 - log(x**2 + x + 1)/6 - sqrt(3)*atan(sqrt(3)*(2*x + 1)/3)/3,
    ),
    RubiTestSuiteCase(
        integrand=x**3/(x**3 + 1),
        variable=x,
        num_steps=7,
        integral=x - log(x + 1)/3 + log(x**2 - x + 1)/6 + sqrt(3)*atan(sqrt(3)*(1 - 2*x)/3)/3,
    ),
    RubiTestSuiteCase(
        integrand=(x**2 - 2*x - 1)/((x - 1)**2*(x**2 + 1)),
        variable=x,
        num_steps=5,
        integral=log(1 - x) - log(x**2 + 1)/2 + atan(x) + 1/(x - 1),
    ),
    RubiTestSuiteCase(
        integrand=x**4/(x**4 - 1),
        variable=x,
        num_steps=4,
        integral=x - atan(x)/2 - atanh(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=(3*x**3 - x**2 + 6*x - 4)/((x**2 + 1)*(x**2 + 2)),
        variable=x,
        num_steps=6,
        integral=3*log(x**2 + 1)/2 - 3*atan(x) + sqrt(2)*atan(sqrt(2)*x/2),
    ),
    RubiTestSuiteCase(
        integrand=(x**3 - 2*x**2 + x + 1)/(x**4 + 5*x**2 + 4),
        variable=x,
        num_steps=7,
        integral=log(x**2 + 4)/2 - 3*atan(x/2)/2 + atan(x),
    ),
    RubiTestSuiteCase(
        integrand=(x - 3)/(x**2 + 2*x + 4)**2,
        variable=x,
        num_steps=3,
        integral=(-4*x - 7)/(6*x**2 + 12*x + 24) - 2*sqrt(3)*atan(sqrt(3)*(x + 1)/3)/9,
    ),
    RubiTestSuiteCase(
        integrand=(x**4 + 1)/(x*(x**2 + 1)**2),
        variable=x,
        num_steps=3,
        integral=log(x) + 1/(x**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=(2*sin(x) - 3)*cos(x)/(sin(x)**2 - 3*sin(x) + 2),
        variable=x,
        num_steps=2,
        integral=log(sin(x)**2 - 3*sin(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)*cos(x)**2/(cos(x)**2 + 5),
        variable=x,
        num_steps=3,
        integral=-cos(x) + sqrt(5)*atan(sqrt(5)*cos(x)/5),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2 + 2*x - 3),
        variable=x,
        num_steps=3,
        integral=log(1 - x)/4 - log(x + 3)/4,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**2 - 2*x),
        variable=x,
        num_steps=1,
        integral=-log(x)/2 + log(2 - x)/2,
    ),
    RubiTestSuiteCase(
        integrand=(2*x + 1)/(4*x**2 + 12*x - 7),
        variable=x,
        num_steps=3,
        integral=log(1 - 2*x)/8 + 3*log(2*x + 7)/8,
    ),
    RubiTestSuiteCase(
        integrand=x/(x**2 + x - 1),
        variable=x,
        num_steps=3,
        integral=(sqrt(5) + 5)*log(2*x + 1 + sqrt(5))/10 + (5 - sqrt(5))*log(2*x - sqrt(5) + 1)/10,
    ),
    RubiTestSuiteCase(
        integrand=(4*x**3 - 27*x**2 + 5*x - 32)/(30*x**5 - 13*x**4 + 50*x**3 - 286*x**2 - 299*x - 70),
        variable=x,
        num_steps=6,
        integral=-3146*log(7 - 3*x)/80155 - 334*log(2*x + 1)/323 + 4822*log(5*x + 2)/4879 + 11049*log(x**2 + x + 5)/260015 + 3988*sqrt(19)*atan(sqrt(19)*(2*x + 1)/19)/260015,
    ),
    RubiTestSuiteCase(
        integrand=(12*x**5 - 7*x**3 - 13*x**2 + 8)/(100*x**6 - 80*x**5 + 116*x**4 - 80*x**3 + 41*x**2 - 20*x + 4),
        variable=x,
        num_steps=7,
        integral=-(502*x + 313)/(2904*x**2 + 1452) - 59096*log(2 - 5*x)/99825 + 2843*log(2*x**2 + 1)/7986 + 503*sqrt(2)*atan(sqrt(2)*x)/15972 + 5828/(18150 - 45375*x),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x + 4)/x,
        variable=x,
        num_steps=3,
        integral=2*sqrt(x + 4) - 4*atanh(sqrt(x + 4)/2),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(x) - 1/x**(sympy.S(1)/3)),
        variable=x,
        num_steps=9,
        integral=2*sqrt(x) + 6*log(1 - x**(sympy.S(1)/6))/5 - (sympy.S(3)/10 - 3*sqrt(5)/10)*log(x**(sympy.S(1)/6) + sqrt(5)*x**(sympy.S(1)/6) + 2*x**(sympy.S(1)/3) + 2) - (sympy.S(3)/10 + 3*sqrt(5)/10)*log(-sqrt(5)*x**(sympy.S(1)/6) + x**(sympy.S(1)/6) + 2*x**(sympy.S(1)/3) + 2) - 3*sqrt(2*sqrt(5) + 10)*atan(sqrt(sqrt(5)/10 + sympy.S.Half)*(4*x**(sympy.S(1)/6) + 1 + sqrt(5))/2)/5 + 3*sqrt(10 - 2*sqrt(5))*atan((4*x**(sympy.S(1)/6) - sqrt(5) + 1)/sqrt(2*sqrt(5) + 10))/5,
    ),
    RubiTestSuiteCase(
        integrand=1/(3*sin(x) - 4*cos(x)),
        variable=x,
        num_steps=2,
        integral=-atanh(4*sin(x)/5 + 3*cos(x)/5)/5,
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(x) + 1),
        variable=x,
        num_steps=3,
        integral=2*sqrt(x) - 2*log(sqrt(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/(1 + x**(sympy.S(-1)/3)),
        variable=x,
        num_steps=3,
        integral=-3*x**(sympy.S(2)/3)/2 + 3*x**(sympy.S(1)/3) + x - log(x) - 3*log(1 + x**(sympy.S(-1)/3)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x)/(x + 1),
        variable=x,
        num_steps=3,
        integral=2*sqrt(x) - 2*atan(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(x + 1)),
        variable=x,
        num_steps=2,
        integral=-2*atanh(sqrt(x + 1)),
    ),
    RubiTestSuiteCase(
        integrand=1/(-x**(sympy.S(1)/3) + x),
        variable=x,
        num_steps=2,
        integral=3*log(1 - x**(sympy.S(2)/3))/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(x - sqrt(x + 2)),
        variable=x,
        num_steps=4,
        integral=4*log(2 - sqrt(x + 2))/3 + 2*log(sqrt(x + 2) + 1)/3,
    ),
    RubiTestSuiteCase(
        integrand=x**2/sqrt(x - 1),
        variable=x,
        num_steps=2,
        integral=2*(x - 1)**(sympy.S(5)/2)/5 + 4*(x - 1)**(sympy.S(3)/2)/3 + 2*sqrt(x - 1),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x - 1)/(x + 1),
        variable=x,
        num_steps=3,
        integral=2*sqrt(x - 1) - 2*sqrt(2)*atan(sqrt(2)*sqrt(x - 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(sqrt(x) + 1),
        variable=x,
        num_steps=3,
        integral=4*(sqrt(x) + 1)**(sympy.S(3)/2)/3 - 4*sqrt(sqrt(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x)/(x**2 + x),
        variable=x,
        num_steps=3,
        integral=2*atan(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=(sqrt(x) + 1)/(sqrt(x) - 1),
        variable=x,
        num_steps=3,
        integral=4*sqrt(x) + x + 4*log(1 - sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=(1 + x**(sympy.S(-1)/3))/(-1 + x**(sympy.S(-1)/3)),
        variable=x,
        num_steps=4,
        integral=-3*x**(sympy.S(2)/3) - 6*x**(sympy.S(1)/3) - x - 6*log(1 - x**(sympy.S(1)/3)),
    ),
    RubiTestSuiteCase(
        integrand=x**3/(x**2 + 1)**(sympy.S(1)/3),
        variable=x,
        num_steps=3,
        integral=3*(x**2 + 1)**(sympy.S(5)/3)/10 - 3*(x**2 + 1)**(sympy.S(2)/3)/4,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x)/(sqrt(x) - 1/x**(sympy.S(1)/3)),
        variable=x,
        num_steps=10,
        integral=6*x**(sympy.S(1)/6) + x + 6*log(1 - x**(sympy.S(1)/6))/5 - (sympy.S(3)/10 + 3*sqrt(5)/10)*log(x**(sympy.S(1)/6) + sqrt(5)*x**(sympy.S(1)/6) + 2*x**(sympy.S(1)/3) + 2) - (sympy.S(3)/10 - 3*sqrt(5)/10)*log(-sqrt(5)*x**(sympy.S(1)/6) + x**(sympy.S(1)/6) + 2*x**(sympy.S(1)/3) + 2) - 3*sqrt(10 - 2*sqrt(5))*atan(sqrt(sqrt(5)/10 + sympy.S.Half)*(4*x**(sympy.S(1)/6) + 1 + sqrt(5))/2)/5 - 3*sqrt(2*sqrt(5) + 10)*atan((4*x**(sympy.S(1)/6) - sqrt(5) + 1)/sqrt(2*sqrt(5) + 10))/5,
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(x) + x**(sympy.S(-1)/4)),
        variable=x,
        num_steps=9,
        integral=2*sqrt(x) + 4*log(x**(sympy.S(1)/4) + 1)/3 - 2*log(-x**(sympy.S(1)/4) + sqrt(x) + 1)/3 + 4*sqrt(3)*atan(sqrt(3)*(1 - 2*x**(sympy.S(1)/4))/3)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**(sympy.S(-1)/3) + x**(sympy.S(-1)/4)),
        variable=x,
        num_steps=4,
        integral=12*x**(sympy.S(13)/12)/13 + 12*x**(sympy.S(11)/12)/11 + 12*x**(sympy.S(7)/12)/7 + 12*x**(sympy.S(5)/12)/5 + 12*x**(sympy.S(1)/12) - 6*x**(sympy.S(7)/6)/7 - 6*x**(sympy.S(5)/6)/5 - 6*x**(sympy.S(1)/6) + 4*x**(sympy.S(5)/4)/5 + 4*x**(sympy.S(3)/4)/3 + 4*x**(sympy.S(1)/4) - 3*x**(sympy.S(2)/3)/2 - 3*x**(sympy.S(1)/3) - 2*sqrt(x) - x - 12*log(x**(sympy.S(1)/12) + 1),
    ),
    RubiTestSuiteCase(
        integrand=sqrt((1 - x)/x),
        variable=x,
        num_steps=5,
        integral=x*sqrt(-1 + 1/x) - atan(sqrt(-1 + 1/x)),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)/(sin(x)**2 + sin(x)),
        variable=x,
        num_steps=2,
        integral=-log(sin(x) + 1) + log(sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=exp(2*x)/(exp(2*x) + 3*exp(x) + 2),
        variable=x,
        num_steps=4,
        integral=-log(exp(x) + 1) + 2*log(exp(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(exp(x) + 1),
        variable=x,
        num_steps=3,
        integral=-2*atanh(sqrt(exp(x) + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(1 - exp(x)),
        variable=x,
        num_steps=4,
        integral=2*sqrt(1 - exp(x)) - 2*atanh(sqrt(1 - exp(x))),
    ),
    RubiTestSuiteCase(
        integrand=1/(3 - 5*sin(x)),
        variable=x,
        num_steps=4,
        integral=-log(-3*sin(x/2) + cos(x/2))/4 + log(-sin(x/2) + 3*cos(x/2))/4,
    ),
    RubiTestSuiteCase(
        integrand=1/(sin(x) + cos(x)),
        variable=x,
        num_steps=2,
        integral=-sqrt(2)*atanh(sqrt(2)*(-sin(x) + cos(x))/2)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(sin(x) - cos(x) + 1),
        variable=x,
        num_steps=2,
        integral=-log(cot(x/2) + 1),
    ),
    RubiTestSuiteCase(
        integrand=1/(3*sin(x) + 4*cos(x)),
        variable=x,
        num_steps=2,
        integral=atanh(4*sin(x)/5 - 3*cos(x)/5)/5,
    ),
    RubiTestSuiteCase(
        integrand=1/(sin(x) + tan(x)),
        variable=x,
        num_steps=6,
        integral=cot(x)*csc(x)/2 - atanh(cos(x))/2 - csc(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(2*sin(x) + sin(2*x)),
        variable=x,
        num_steps=4,
        integral=log(tan(x/2))/4 + tan(x/2)**2/8,
    ),
    RubiTestSuiteCase(
        integrand=sec(x)/(sin(x) + 1),
        variable=x,
        num_steps=4,
        integral=atanh(sin(x))/2 - 1/(2*sin(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=1/(a*sin(x) + b*cos(x)),
        variable=x,
        num_steps=2,
        integral=-atanh((a*cos(x) - b*sin(x))/sqrt(a**2 + b**2))/sqrt(a**2 + b**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(a**2*sin(x)**2 + b**2*cos(x)**2),
        variable=x,
        num_steps=2,
        integral=atan(a*tan(x)/b)/(a*b),
    ),
    RubiTestSuiteCase(
        integrand=x/(x**2 - 1),
        variable=x,
        num_steps=1,
        integral=log(1 - x**2)/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x)*(sqrt(x) + 1),
        variable=x,
        num_steps=2,
        integral=2*x**(sympy.S(3)/2)/3 + x**2/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(1 - cos(x)),
        variable=x,
        num_steps=1,
        integral=-sin(x)/(1 - cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**2*sec(x),
        variable=x,
        num_steps=2,
        integral=tan(x)*sec(x)/2 - atanh(sin(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**3*sec(x)**3,
        variable=x,
        num_steps=3,
        integral=sec(x)**5/5 - sec(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=exp(sqrt(x)),
        variable=x,
        num_steps=3,
        integral=2*sqrt(x)*exp(sqrt(x)) - 2*exp(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=(x**5 + 1)/(x**3 - 3*x**2 - 10*x),
        variable=x,
        num_steps=3,
        integral=x**3/3 + 3*x**2/2 + 19*x - log(x)/10 + 3126*log(5 - x)/35 - 31*log(x + 2)/14,
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(log(x))),
        variable=x,
        num_steps=2,
        integral=2*sqrt(log(x)),
    ),
    RubiTestSuiteCase(
        integrand=(2*x + 5)/(x - 3),
        variable=x,
        num_steps=2,
        integral=2*x + 11*log(3 - x),
    ),
    RubiTestSuiteCase(
        integrand=exp(x + exp(x)),
        variable=x,
        num_steps=2,
        integral=exp(exp(x)),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2*cos(x)**2,
        variable=x,
        num_steps=3,
        integral=x/8 - sin(x)*cos(x)**3/4 + sin(x)*cos(x)/8,
    ),
    RubiTestSuiteCase(
        integrand=(sin(x) - cos(x))/(sin(x) + cos(x)),
        variable=x,
        num_steps=1,
        integral=-log(sin(x) + cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(1 - x**2),
        variable=x,
        num_steps=1,
        integral=-sqrt(1 - x**2),
    ),
    RubiTestSuiteCase(
        integrand=x**3*log(x),
        variable=x,
        num_steps=1,
        integral=x**4*log(x)/4 - x**4/16,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x - 2)/(x + 2),
        variable=x,
        num_steps=3,
        integral=2*sqrt(x - 2) - 4*atan(sqrt(x - 2)/2),
    ),
    RubiTestSuiteCase(
        integrand=x/(x + 2)**2,
        variable=x,
        num_steps=2,
        integral=log(x + 2) + 2/(x + 2),
    ),
    RubiTestSuiteCase(
        integrand=log(x**2 + 1),
        variable=x,
        num_steps=3,
        integral=x*log(x**2 + 1) - 2*x + 2*atan(x),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(log(x) + 1)/(x*log(x)),
        variable=x,
        num_steps=4,
        integral=2*sqrt(log(x) + 1) - 2*atanh(sqrt(log(x) + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(sqrt(x) + 1)**8,
        variable=x,
        num_steps=3,
        integral=(sqrt(x) + 1)**10/5 - 2*(sqrt(x) + 1)**9/9,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**3*sec(x)**4,
        variable=x,
        num_steps=3,
        integral=sec(x)**6/6 - sec(x)**4/4,
    ),
    RubiTestSuiteCase(
        integrand=x/(x**2 - 2*x + 2),
        variable=x,
        num_steps=4,
        integral=log(x**2 - 2*x + 2)/2 + atan(x - 1),
    ),
    RubiTestSuiteCase(
        integrand=x*asin(x),
        variable=x,
        num_steps=3,
        integral=x**2*asin(x)/2 + x*sqrt(1 - x**2)/4 - asin(x)/4,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(9 - x**2)/x,
        variable=x,
        num_steps=4,
        integral=sqrt(9 - x**2) - 3*atanh(sqrt(9 - x**2)/3),
    ),
    RubiTestSuiteCase(
        integrand=x/(x**2 + 3*x + 2),
        variable=x,
        num_steps=3,
        integral=-log(x + 1) + 2*log(x + 2),
    ),
    RubiTestSuiteCase(
        integrand=x**2*cosh(x),
        variable=x,
        num_steps=3,
        integral=x**2*sinh(x) - 2*x*cosh(x) + 2*sinh(x),
    ),
    RubiTestSuiteCase(
        integrand=(x**3 + x + 1)/(x**4 + 2*x**2 + 4*x),
        variable=x,
        num_steps=1,
        integral=log(x**4 + 2*x**2 + 4*x)/4,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)/(sin(x)**2 + 1),
        variable=x,
        num_steps=2,
        integral=atan(sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=cos(sqrt(x)),
        variable=x,
        num_steps=3,
        integral=2*sqrt(x)*sin(sqrt(x)) + 2*cos(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=sin(pi*x),
        variable=x,
        num_steps=1,
        integral=-cos(pi*x)/pi,
    ),
    RubiTestSuiteCase(
        integrand=exp(2*x)/(exp(x) + 1),
        variable=x,
        num_steps=3,
        integral=exp(x) - log(exp(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=exp(3*x)*cos(5*x),
        variable=x,
        num_steps=1,
        integral=5*exp(3*x)*sin(5*x)/34 + 3*exp(3*x)*cos(5*x)/34,
    ),
    RubiTestSuiteCase(
        integrand=cos(3*x)*cos(5*x),
        variable=x,
        num_steps=1,
        integral=sin(2*x)/4 + sin(8*x)/16,
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3 + x**2 + x + 1),
        variable=x,
        num_steps=5,
        integral=log(x + 1)/2 - log(x**2 + 1)/4 + atan(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=x**2*log(x + 1),
        variable=x,
        num_steps=3,
        integral=x**3*log(x + 1)/3 - x**3/9 + x**2/6 - x/3 + log(x + 1)/3,
    ),
    RubiTestSuiteCase(
        integrand=x**5*exp(-x**3),
        variable=x,
        num_steps=2,
        integral=-x**3*exp(-x**3)/3 - exp(-x**3)/3,
    ),
    RubiTestSuiteCase(
        integrand=tan(4*x)**2,
        variable=x,
        num_steps=2,
        integral=-x + tan(4*x)/4,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(9*x**2 + 12*x - 5),
        variable=x,
        num_steps=2,
        integral=atanh((3*x + 2)/sqrt(9*x**2 + 12*x - 5))/3,
    ),
    RubiTestSuiteCase(
        integrand=x**2*atan(x),
        variable=x,
        num_steps=4,
        integral=x**3*atan(x)/3 - x**2/6 + log(x**2 + 1)/6,
    ),
    RubiTestSuiteCase(
        integrand=(1 - sqrt(x))/x**(sympy.S(1)/3),
        variable=x,
        num_steps=2,
        integral=-6*x**(sympy.S(7)/6)/7 + 3*x**(sympy.S(2)/3)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(exp(x) - exp(-x)),
        variable=x,
        num_steps=2,
        integral=-atanh(exp(x)),
    ),
    RubiTestSuiteCase(
        integrand=x/(x**4 + 2*x**2 + 10),
        variable=x,
        num_steps=3,
        integral=atan(x**2/3 + sympy.S(1)/3)/6,
    ),
    RubiTestSuiteCase(
        integrand=1/(x + x**(sympy.S(-1)/3)),
        variable=x,
        num_steps=2,
        integral=3*log(x**(sympy.S(4)/3) + 1)/4,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2*cos(x)**4,
        variable=x,
        num_steps=4,
        integral=x/16 - sin(x)*cos(x)**5/6 + sin(x)*cos(x)**3/24 + sin(x)*cos(x)/16,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-x**2 - 4*x + 5),
        variable=x,
        num_steps=2,
        integral=asin(x/3 + sympy.S(2)/3),
    ),
    RubiTestSuiteCase(
        integrand=x/(-x**2 + sqrt(1 - x**2) + 1),
        variable=x,
        num_steps=3,
        integral=-log(sqrt(1 - x**2) + 1),
    ),
    RubiTestSuiteCase(
        integrand=(cos(x) + 1)*csc(x),
        variable=x,
        num_steps=2,
        integral=log(1 - cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)/(exp(2*x) - 1),
        variable=x,
        num_steps=2,
        integral=-atanh(exp(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x**3 - 8),
        variable=x,
        num_steps=6,
        integral=log(2 - x)/12 - log(x**2 + 2*x + 4)/24 - sqrt(3)*atan(sqrt(3)*(x + 1)/3)/12,
    ),
    RubiTestSuiteCase(
        integrand=x**5*cosh(x),
        variable=x,
        num_steps=6,
        integral=x**5*sinh(x) - 5*x**4*cosh(x) + 20*x**3*sinh(x) - 60*x**2*cosh(x) + 120*x*sinh(x) - 120*cosh(x),
    ),
    RubiTestSuiteCase(
        integrand=log(tan(x))/(sin(x)*cos(x)),
        variable=x,
        num_steps=1,
        integral=log(tan(x))**2/2,
    ),
    RubiTestSuiteCase(
        integrand=x**3 + x**2 - 2*x,
        variable=x,
        num_steps=1,
        integral=x**4/4 + x**3/3 - x**2,
    ),
    RubiTestSuiteCase(
        integrand=(exp(x) + 1)/(1 - exp(x)),
        variable=x,
        num_steps=3,
        integral=x - 2*log(1 - exp(x)),
    ),
    RubiTestSuiteCase(
        integrand=x/((x**2 + 1)*(x**2 + 4)),
        variable=x,
        num_steps=4,
        integral=log(x**2 + 1)/6 - log(x**2 + 4)/6,
    ),
    RubiTestSuiteCase(
        integrand=1/(4 - 5*sin(x)),
        variable=x,
        num_steps=4,
        integral=-log(-2*sin(x/2) + cos(x/2))/3 + log(-sin(x/2) + 2*cos(x/2))/3,
    ),
    RubiTestSuiteCase(
        integrand=x*(c + x)**(sympy.S(1)/3),
        variable=x,
        num_steps=2,
        integral=-3*c*(c + x)**(sympy.S(4)/3)/4 + 3*(c + x)**(sympy.S(7)/3)/7,
    ),
    RubiTestSuiteCase(
        integrand=exp(x**(sympy.S(1)/3)),
        variable=x,
        num_steps=4,
        integral=3*x**(sympy.S(2)/3)*exp(x**(sympy.S(1)/3)) - 6*x**(sympy.S(1)/3)*exp(x**(sympy.S(1)/3)) + 6*exp(x**(sympy.S(1)/3)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x + sqrt(x + 1) + 4),
        variable=x,
        num_steps=5,
        integral=log(x + sqrt(x + 1) + 4) - 2*sqrt(11)*atan(sqrt(11)*(2*sqrt(x + 1) + 1)/11)/11,
    ),
    RubiTestSuiteCase(
        integrand=(x**3 + 1)/(x**3 - x**2),
        variable=x,
        num_steps=3,
        integral=x - log(x) + 2*log(1 - x) + 1/x,
    ),
    RubiTestSuiteCase(
        integrand=(x**2 + 4*x - 3)*sin(2*x),
        variable=x,
        num_steps=8,
        integral=-x**2*cos(2*x)/2 + x*sin(2*x)/2 - 2*x*cos(2*x) + sin(2*x) + 7*cos(2*x)/4,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)*cos(cos(x)),
        variable=x,
        num_steps=2,
        integral=-sin(cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(16 - x**2),
        variable=x,
        num_steps=1,
        integral=asin(x/4),
    ),
    RubiTestSuiteCase(
        integrand=x**3/(x + 1)**10,
        variable=x,
        num_steps=2,
        integral=-1/(6*(x + 1)**6) + 3/(7*(x + 1)**7) - 3/(8*(x + 1)**8) + 1/(9*(x + 1)**9),
    ),
    RubiTestSuiteCase(
        integrand=cot(2*x)**3*csc(2*x)**3,
        variable=x,
        num_steps=3,
        integral=-csc(2*x)**5/10 + csc(2*x)**3/6,
    ),
    RubiTestSuiteCase(
        integrand=(x + sin(x))**2,
        variable=x,
        num_steps=6,
        integral=x**3/3 - 2*x*cos(x) + x/2 - sin(x)*cos(x)/2 + 2*sin(x),
    ),
    RubiTestSuiteCase(
        integrand=exp(atan(x))/(x**2 + 1),
        variable=x,
        num_steps=1,
        integral=exp(atan(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*(x**4 + 1)),
        variable=x,
        num_steps=4,
        integral=log(x) - log(x**4 + 1)/4,
    ),
    RubiTestSuiteCase(
        integrand=t**3*exp(-2*t),
        variable=t,
        num_steps=4,
        integral=-t**3*exp(-2*t)/2 - 3*t**2*exp(-2*t)/4 - 3*t*exp(-2*t)/4 - 3*exp(-2*t)/8,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(t)/(t**(sympy.S(1)/3) + 1),
        variable=t,
        num_steps=7,
        integral=6*t**(sympy.S(7)/6)/7 - 6*t**(sympy.S(5)/6)/5 - 6*t**(sympy.S(1)/6) + 2*sqrt(t) + 6*atan(t**(sympy.S(1)/6)),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)*sin(2*x)*sin(3*x),
        variable=x,
        num_steps=5,
        integral=-cos(2*x)/8 - cos(4*x)/16 + cos(6*x)/24,
    ),
    RubiTestSuiteCase(
        integrand=log(x/2),
        variable=x,
        num_steps=1,
        integral=x*log(x/2) - x,
    ),
    RubiTestSuiteCase(
        integrand=sqrt((x + 1)/(1 - x)),
        variable=x,
        num_steps=3,
        integral=-sqrt((x + 1)/(1 - x))*(1 - x) + 2*atan(sqrt((x + 1)/(1 - x))),
    ),
    RubiTestSuiteCase(
        integrand=x*log(x)/sqrt(x**2 - 1),
        variable=x,
        num_steps=5,
        integral=sqrt(x**2 - 1)*log(x) - sqrt(x**2 - 1) + atan(sqrt(x**2 - 1)),
    ),
    RubiTestSuiteCase(
        integrand=(a + x)/(a**2 + x**2),
        variable=x,
        num_steps=3,
        integral=log(a**2 + x**2)/2 + atan(x/a),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-x**2 + x + 1),
        variable=x,
        num_steps=3,
        integral=-(1 - 2*x)*sqrt(-x**2 + x + 1)/4 - 5*asin(sqrt(5)*(1 - 2*x)/5)/8,
    ),
    RubiTestSuiteCase(
        integrand=x**4/(x**10 + 16),
        variable=x,
        num_steps=2,
        integral=atan(x**5/4)/20,
    ),
    RubiTestSuiteCase(
        integrand=(x + 2)/(x**2 + x + 2),
        variable=x,
        num_steps=4,
        integral=log(x**2 + x + 2)/2 + 3*sqrt(7)*atan(sqrt(7)*(2*x + 1)/7)/7,
    ),
    RubiTestSuiteCase(
        integrand=x*tan(x)*sec(x),
        variable=x,
        num_steps=2,
        integral=x*sec(x) - atanh(sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=x/(-a**4 + x**4),
        variable=x,
        num_steps=2,
        integral=-atanh(x**2/a**2)/(2*a**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(x) + sqrt(x + 1)),
        variable=x,
        num_steps=3,
        integral=-2*x**(sympy.S(3)/2)/3 + 2*(x + 1)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/(2*exp(x) + 1 - exp(-x)),
        variable=x,
        num_steps=4,
        integral=log(1 - 2*exp(x))/3 - log(exp(x) + 1)/3,
    ),
    RubiTestSuiteCase(
        integrand=atan(sqrt(x))/sqrt(x),
        variable=x,
        num_steps=2,
        integral=2*sqrt(x)*atan(sqrt(x)) - log(x + 1),
    ),
    RubiTestSuiteCase(
        integrand=log(x + 1)/x**2,
        variable=x,
        num_steps=4,
        integral=log(x) - log(x + 1) - log(x + 1)/x,
    ),
    RubiTestSuiteCase(
        integrand=1/(exp(3*x) - exp(x)),
        variable=x,
        num_steps=3,
        integral=-atanh(exp(x)) + exp(-x),
    ),
    RubiTestSuiteCase(
        integrand=(cos(x)**2 + 1)/(1 - cos(x)**2),
        variable=x,
        num_steps=4,
        integral=-x - 2*cot(x),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(2*x - 25)),
        variable=x,
        num_steps=2,
        integral=2*atan(sqrt(2*x - 25)/5)/5,
    ),
    RubiTestSuiteCase(
        integrand=sin(2*x)/sqrt(9 - cos(x)**4),
        variable=x,
        num_steps=5,
        integral=-asin(cos(x)**2/3),
    ),
    RubiTestSuiteCase(
        integrand=x**2/sqrt(5 - 4*x**2),
        variable=x,
        num_steps=2,
        integral=-x*sqrt(5 - 4*x**2)/8 + 5*asin(2*sqrt(5)*x/5)/16,
    ),
    RubiTestSuiteCase(
        integrand=x**3*sin(x),
        variable=x,
        num_steps=4,
        integral=-x**3*cos(x) + 3*x**2*sin(x) + 6*x*cos(x) - 6*sin(x),
    ),
    RubiTestSuiteCase(
        integrand=x*sqrt(x**2 + 2*x + 4),
        variable=x,
        num_steps=4,
        integral=-(x + 1)*sqrt(x**2 + 2*x + 4)/2 + (x**2 + 2*x + 4)**(sympy.S(3)/2)/3 - 3*asinh(sqrt(3)*(x + 1)/3)/2,
    ),
    RubiTestSuiteCase(
        integrand=x*(x**2 + 5)**8,
        variable=x,
        num_steps=1,
        integral=(x**2 + 5)**9/18,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**5*cos(x)**2,
        variable=x,
        num_steps=3,
        integral=-cos(x)**7/7 + 2*cos(x)**5/5 - cos(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=exp(-3*x)*cos(4*x),
        variable=x,
        num_steps=1,
        integral=4*exp(-3*x)*sin(4*x)/25 - 3*exp(-3*x)*cos(4*x)/25,
    ),
    RubiTestSuiteCase(
        integrand=csc(x/2)**3,
        variable=x,
        num_steps=2,
        integral=-cot(x/2)*csc(x/2) - atanh(cos(x/2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(9*x**2 - 1)/x**2,
        variable=x,
        num_steps=3,
        integral=3*atanh(3*x/sqrt(9*x**2 - 1)) - sqrt(9*x**2 - 1)/x,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(4 - 3*x**2)/x,
        variable=x,
        num_steps=4,
        integral=sqrt(4 - 3*x**2) - 2*atanh(sqrt(4 - 3*x**2)/2),
    ),
    RubiTestSuiteCase(
        integrand=x**2*exp(3*x),
        variable=x,
        num_steps=3,
        integral=x**2*exp(3*x)/3 - 2*x*exp(3*x)/9 + 2*exp(3*x)/27,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)*cos(x)/sqrt(sin(x) + 1),
        variable=x,
        num_steps=3,
        integral=2*(sin(x) + 1)**(sympy.S(3)/2)/3 - 2*sqrt(sin(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=x*asin(x**2),
        variable=x,
        num_steps=3,
        integral=x**2*asin(x**2)/2 + sqrt(1 - x**4)/2,
    ),
    RubiTestSuiteCase(
        integrand=x**3*asin(x**2),
        variable=x,
        num_steps=5,
        integral=x**4*asin(x**2)/4 + x**2*sqrt(1 - x**4)/8 - asin(x**2)/8,
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*sech(exp(x)),
        variable=x,
        num_steps=2,
        integral=atan(sinh(exp(x))),
    ),
    RubiTestSuiteCase(
        integrand=x**2*cos(3*x),
        variable=x,
        num_steps=3,
        integral=x**2*sin(3*x)/3 + 2*x*cos(3*x)/9 - 2*sin(3*x)/27,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-x**2 - 4*x + 5),
        variable=x,
        num_steps=3,
        integral=(x + 2)*sqrt(-x**2 - 4*x + 5)/2 + 9*asin(x/3 + sympy.S(2)/3)/2,
    ),
    RubiTestSuiteCase(
        integrand=x**5/(x**2 + sqrt(2)),
        variable=x,
        num_steps=3,
        integral=x**4/4 - sqrt(2)*x**2/2 + log(x**2 + sqrt(2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)**5,
        variable=x,
        num_steps=3,
        integral=tan(x)*sec(x)**3/4 + 3*tan(x)*sec(x)/8 + 3*atanh(sin(x))/8,
    ),
    RubiTestSuiteCase(
        integrand=sin(2*x)**6,
        variable=x,
        num_steps=4,
        integral=5*x/16 - sin(2*x)**5*cos(2*x)/12 - 5*sin(2*x)**3*cos(2*x)/48 - 5*sin(2*x)*cos(2*x)/32,
    ),
    RubiTestSuiteCase(
        integrand=log(sin(x))*sin(x)**2*cos(x),
        variable=x,
        num_steps=4,
        integral=log(sin(x))*sin(x)**3/3 - sin(x)**3/9,
    ),
    RubiTestSuiteCase(
        integrand=exp(-x)/(2*exp(x) + 1),
        variable=x,
        num_steps=3,
        integral=-2*x + 2*log(2*exp(x) + 1) - exp(-x),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(3*cos(x) + 2)*tan(x),
        variable=x,
        num_steps=4,
        integral=-2*sqrt(3*cos(x) + 2) + 2*sqrt(2)*atanh(sqrt(2)*sqrt(3*cos(x) + 2)/2),
    ),
    RubiTestSuiteCase(
        integrand=x/sqrt(x**2 - 4*x),
        variable=x,
        num_steps=3,
        integral=sqrt(x**2 - 4*x) + 4*atanh(x/sqrt(x**2 - 4*x)),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**5,
        variable=x,
        num_steps=2,
        integral=sin(x)**5/5 - 2*sin(x)**3/3 + sin(x),
    ),
    RubiTestSuiteCase(
        integrand=x**4*exp(-x),
        variable=x,
        num_steps=5,
        integral=-x**4*exp(-x) - 4*x**3*exp(-x) - 12*x**2*exp(-x) - 24*x*exp(-x) - 24*exp(-x),
    ),
    RubiTestSuiteCase(
        integrand=x**4/sqrt(x**10 - 2),
        variable=x,
        num_steps=3,
        integral=atanh(x**5/sqrt(x**10 - 2))/5,
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*cos(3*x + 4),
        variable=x,
        num_steps=1,
        integral=3*exp(x)*sin(3*x + 4)/10 + exp(x)*cos(3*x + 4)/10,
    ),
    RubiTestSuiteCase(
        integrand=x**2*atan(x),
        variable=x,
        num_steps=4,
        integral=x**3*atan(x)/3 - x**2/6 + log(x**2 + 1)/6,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(exp(2*x) - 1),
        variable=x,
        num_steps=4,
        integral=sqrt(exp(2*x) - 1) - atan(sqrt(exp(2*x) - 1)),
    ),
    RubiTestSuiteCase(
        integrand=exp(sin(x))*sin(2*x),
        variable=x,
        num_steps=4,
        integral=2*exp(sin(x))*sin(x) - 2*exp(sin(x)),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sqrt(5 - x**2),
        variable=x,
        num_steps=3,
        integral=x**3*sqrt(5 - x**2)/4 - 5*x*sqrt(5 - x**2)/8 + 25*asin(sqrt(5)*x/5)/8,
    ),
    RubiTestSuiteCase(
        integrand=x**2*(x**3 + 1)**4,
        variable=x,
        num_steps=1,
        integral=(x**3 + 1)**5/15,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3*cos(x)**3,
        variable=x,
        num_steps=3,
        integral=-sin(x)**6/6 + sin(x)**4/4,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**2*sec(x)**4,
        variable=x,
        num_steps=3,
        integral=tan(x)**5/5 + tan(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=x*sqrt(2*x + 1),
        variable=x,
        num_steps=2,
        integral=(2*x + 1)**(sympy.S(5)/2)/10 - (2*x + 1)**(sympy.S(3)/2)/6,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**4,
        variable=x,
        num_steps=3,
        integral=3*x/8 - sin(x)**3*cos(x)/4 - 3*sin(x)*cos(x)/8,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**3,
        variable=x,
        num_steps=2,
        integral=log(cos(x)) + tan(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=x**5*sqrt(x**2 + 1),
        variable=x,
        num_steps=3,
        integral=(x**2 + 1)**(sympy.S(7)/2)/7 - 2*(x**2 + 1)**(sympy.S(5)/2)/5 + (x**2 + 1)**(sympy.S(3)/2)/3,
    ),
]
