# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 4 Trig functions/4.2 Cosine/4.2.0 (a cos)^m (b trg)^n.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '4 Trig functions/4.2 Cosine/4.2.0 (a cos)^m (b trg)^n.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, c, d, e, f, m, n, p = symbols('a b c d e f m n p')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=cos(a + b*x),
        variable=x,
        num_steps=1,
        integral=sin(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2,
        variable=x,
        num_steps=2,
        integral=x/2 + sin(a + b*x)*cos(a + b*x)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3,
        variable=x,
        num_steps=2,
        integral=-sin(a + b*x)**3/(3*b) + sin(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**4,
        variable=x,
        num_steps=3,
        integral=3*x/8 + sin(a + b*x)*cos(a + b*x)**3/(4*b) + 3*sin(a + b*x)*cos(a + b*x)/(8*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**5,
        variable=x,
        num_steps=2,
        integral=sin(a + b*x)**5/(5*b) - 2*sin(a + b*x)**3/(3*b) + sin(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**6,
        variable=x,
        num_steps=4,
        integral=5*x/16 + sin(a + b*x)*cos(a + b*x)**5/(6*b) + 5*sin(a + b*x)*cos(a + b*x)**3/(24*b) + 5*sin(a + b*x)*cos(a + b*x)/(16*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**7,
        variable=x,
        num_steps=2,
        integral=-sin(a + b*x)**7/(7*b) + 3*sin(a + b*x)**5/(5*b) - sin(a + b*x)**3/b + sin(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**8,
        variable=x,
        num_steps=5,
        integral=35*x/128 + sin(a + b*x)*cos(a + b*x)**7/(8*b) + 7*sin(a + b*x)*cos(a + b*x)**5/(48*b) + 35*sin(a + b*x)*cos(a + b*x)**3/(192*b) + 35*sin(a + b*x)*cos(a + b*x)/(128*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=2*sin(a + b*x)*cos(a + b*x)**(sympy.S(5)/2)/(7*b) + 10*sin(a + b*x)*sqrt(cos(a + b*x))/(21*b) + 10*elliptic_f(a/2 + b*x/2, 2)/(21*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=2*sin(a + b*x)*cos(a + b*x)**(sympy.S(3)/2)/(5*b) + 6*elliptic_e(a/2 + b*x/2, 2)/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=2*sin(a + b*x)*sqrt(cos(a + b*x))/(3*b) + 2*elliptic_f(a/2 + b*x/2, 2)/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(cos(a + b*x)),
        variable=x,
        num_steps=1,
        integral=2*elliptic_e(a/2 + b*x/2, 2)/b,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(cos(a + b*x)),
        variable=x,
        num_steps=1,
        integral=2*elliptic_f(a/2 + b*x/2, 2)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**(sympy.S(-3)/2),
        variable=x,
        num_steps=2,
        integral=2*sin(a + b*x)/(b*sqrt(cos(a + b*x))) - 2*elliptic_e(a/2 + b*x/2, 2)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**(sympy.S(-5)/2),
        variable=x,
        num_steps=2,
        integral=2*sin(a + b*x)/(3*b*cos(a + b*x)**(sympy.S(3)/2)) + 2*elliptic_f(a/2 + b*x/2, 2)/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**(sympy.S(-7)/2),
        variable=x,
        num_steps=3,
        integral=6*sin(a + b*x)/(5*b*sqrt(cos(a + b*x))) + 2*sin(a + b*x)/(5*b*cos(a + b*x)**(sympy.S(5)/2)) - 6*elliptic_e(a/2 + b*x/2, 2)/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=4,
        integral=10*c**4*sqrt(cos(a + b*x))*elliptic_f(a/2 + b*x/2, 2)/(21*b*sqrt(c*cos(a + b*x))) + 10*c**3*sqrt(c*cos(a + b*x))*sin(a + b*x)/(21*b) + 2*c*(c*cos(a + b*x))**(sympy.S(5)/2)*sin(a + b*x)/(7*b),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=6*c**2*sqrt(c*cos(a + b*x))*elliptic_e(a/2 + b*x/2, 2)/(5*b*sqrt(cos(a + b*x))) + 2*c*(c*cos(a + b*x))**(sympy.S(3)/2)*sin(a + b*x)/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*c**2*sqrt(cos(a + b*x))*elliptic_f(a/2 + b*x/2, 2)/(3*b*sqrt(c*cos(a + b*x))) + 2*c*sqrt(c*cos(a + b*x))*sin(a + b*x)/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(c*cos(a + b*x)),
        variable=x,
        num_steps=2,
        integral=2*sqrt(c*cos(a + b*x))*elliptic_e(a/2 + b*x/2, 2)/(b*sqrt(cos(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(c*cos(a + b*x)),
        variable=x,
        num_steps=2,
        integral=2*sqrt(cos(a + b*x))*elliptic_f(a/2 + b*x/2, 2)/(b*sqrt(c*cos(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x))**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*sin(a + b*x)/(b*c*sqrt(c*cos(a + b*x))) - 2*sqrt(c*cos(a + b*x))*elliptic_e(a/2 + b*x/2, 2)/(b*c**2*sqrt(cos(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x))**(sympy.S(-5)/2),
        variable=x,
        num_steps=3,
        integral=2*sin(a + b*x)/(3*b*c*(c*cos(a + b*x))**(sympy.S(3)/2)) + 2*sqrt(cos(a + b*x))*elliptic_f(a/2 + b*x/2, 2)/(3*b*c**2*sqrt(c*cos(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x))**(sympy.S(-7)/2),
        variable=x,
        num_steps=4,
        integral=2*sin(a + b*x)/(5*b*c*(c*cos(a + b*x))**(sympy.S(5)/2)) + 6*sin(a + b*x)/(5*b*c**3*sqrt(c*cos(a + b*x))) - 6*sqrt(c*cos(a + b*x))*elliptic_e(a/2 + b*x/2, 2)/(5*b*c**4*sqrt(cos(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**(sympy.S(4)/3),
        variable=x,
        num_steps=1,
        integral=-3*sin(a + b*x)*cos(a + b*x)**(sympy.S(7)/3)*hyper((sympy.S.Half, sympy.S(7)/6), (sympy.S(13)/6,), cos(a + b*x)**2)/(7*b*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**(sympy.S(2)/3),
        variable=x,
        num_steps=1,
        integral=-3*sin(a + b*x)*cos(a + b*x)**(sympy.S(5)/3)*hyper((sympy.S.Half, sympy.S(5)/6), (sympy.S(11)/6,), cos(a + b*x)**2)/(5*b*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**(sympy.S(1)/3),
        variable=x,
        num_steps=1,
        integral=-3*sin(a + b*x)*cos(a + b*x)**(sympy.S(4)/3)*hyper((sympy.S.Half, sympy.S(2)/3), (sympy.S(5)/3,), cos(a + b*x)**2)/(4*b*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**(sympy.S(-1)/3),
        variable=x,
        num_steps=1,
        integral=-3*sin(a + b*x)*cos(a + b*x)**(sympy.S(2)/3)*hyper((sympy.S(1)/3, sympy.S.Half), (sympy.S(4)/3,), cos(a + b*x)**2)/(2*b*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**(sympy.S(-2)/3),
        variable=x,
        num_steps=1,
        integral=-3*sin(a + b*x)*cos(a + b*x)**(sympy.S(1)/3)*hyper((sympy.S(1)/6, sympy.S.Half), (sympy.S(7)/6,), cos(a + b*x)**2)/(b*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**(sympy.S(-4)/3),
        variable=x,
        num_steps=1,
        integral=3*sin(a + b*x)*hyper((sympy.S(-1)/6, sympy.S.Half), (sympy.S(5)/6,), cos(a + b*x)**2)/(b*sqrt(sin(a + b*x)**2)*cos(a + b*x)**(sympy.S(1)/3)),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=1,
        integral=-3*(c*cos(a + b*x))**(sympy.S(7)/3)*sin(a + b*x)*hyper((sympy.S.Half, sympy.S(7)/6), (sympy.S(13)/6,), cos(a + b*x)**2)/(7*b*c*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x))**(sympy.S(2)/3),
        variable=x,
        num_steps=1,
        integral=-3*(c*cos(a + b*x))**(sympy.S(5)/3)*sin(a + b*x)*hyper((sympy.S.Half, sympy.S(5)/6), (sympy.S(11)/6,), cos(a + b*x)**2)/(5*b*c*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=1,
        integral=-3*(c*cos(a + b*x))**(sympy.S(4)/3)*sin(a + b*x)*hyper((sympy.S.Half, sympy.S(2)/3), (sympy.S(5)/3,), cos(a + b*x)**2)/(4*b*c*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x))**(sympy.S(-1)/3),
        variable=x,
        num_steps=1,
        integral=-3*(c*cos(a + b*x))**(sympy.S(2)/3)*sin(a + b*x)*hyper((sympy.S(1)/3, sympy.S.Half), (sympy.S(4)/3,), cos(a + b*x)**2)/(2*b*c*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x))**(sympy.S(-2)/3),
        variable=x,
        num_steps=1,
        integral=-3*(c*cos(a + b*x))**(sympy.S(1)/3)*sin(a + b*x)*hyper((sympy.S(1)/6, sympy.S.Half), (sympy.S(7)/6,), cos(a + b*x)**2)/(b*c*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x))**(sympy.S(-4)/3),
        variable=x,
        num_steps=1,
        integral=3*sin(a + b*x)*hyper((sympy.S(-1)/6, sympy.S.Half), (sympy.S(5)/6,), cos(a + b*x)**2)/(b*c*(c*cos(a + b*x))**(sympy.S(1)/3)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**n,
        variable=x,
        num_steps=1,
        integral=-sin(a + b*x)*cos(a + b*x)**(n + 1)*hyper((sympy.S.Half, n/2 + sympy.S.Half), (n/2 + sympy.S(3)/2,), cos(a + b*x)**2)/(b*(n + 1)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x))**n,
        variable=x,
        num_steps=1,
        integral=-(c*cos(a + b*x))**(n + 1)*sin(a + b*x)*hyper((sympy.S.Half, n/2 + sympy.S.Half), (n/2 + sympy.S(3)/2,), cos(a + b*x)**2)/(b*c*(n + 1)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=8*a**2*sqrt(a*cos(x)**2)*tan(x)/15 + 4*a*(a*cos(x)**2)**(sympy.S(3)/2)*tan(x)/15 + (a*cos(x)**2)**(sympy.S(5)/2)*tan(x)/5,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*a*sqrt(a*cos(x)**2)*tan(x)/3 + (a*cos(x)**2)**(sympy.S(3)/2)*tan(x)/3,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*cos(x)**2),
        variable=x,
        num_steps=2,
        integral=sqrt(a*cos(x)**2)*tan(x),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*cos(x)**2),
        variable=x,
        num_steps=2,
        integral=cos(x)*atanh(sin(x))/sqrt(a*cos(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x)**2)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=cos(x)*atanh(sin(x))/(2*a*sqrt(a*cos(x)**2)) + tan(x)/(2*a*sqrt(a*cos(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x)**2)**(sympy.S(-5)/2),
        variable=x,
        num_steps=4,
        integral=tan(x)/(4*a*(a*cos(x)**2)**(sympy.S(3)/2)) + 3*cos(x)*atanh(sin(x))/(8*a**2*sqrt(a*cos(x)**2)) + 3*tan(x)/(8*a**2*sqrt(a*cos(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x)**3)**(sympy.S(5)/2),
        variable=x,
        num_steps=6,
        integral=2*a**2*sqrt(a*cos(x)**3)*sin(x)*cos(x)**5/15 + 26*a**2*sqrt(a*cos(x)**3)*sin(x)*cos(x)**3/165 + 78*a**2*sqrt(a*cos(x)**3)*sin(x)*cos(x)/385 + 26*a**2*sqrt(a*cos(x)**3)*tan(x)/77 + 26*a**2*sqrt(a*cos(x)**3)*elliptic_f(x/2, 2)/(77*cos(x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x)**3)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=2*a*sqrt(a*cos(x)**3)*sin(x)*cos(x)**2/9 + 14*a*sqrt(a*cos(x)**3)*sin(x)/45 + 14*a*sqrt(a*cos(x)**3)*elliptic_e(x/2, 2)/(15*cos(x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*cos(x)**3),
        variable=x,
        num_steps=3,
        integral=2*sqrt(a*cos(x)**3)*tan(x)/3 + 2*sqrt(a*cos(x)**3)*elliptic_f(x/2, 2)/(3*cos(x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*cos(x)**3),
        variable=x,
        num_steps=3,
        integral=2*sin(x)*cos(x)/sqrt(a*cos(x)**3) - 2*cos(x)**(sympy.S(3)/2)*elliptic_e(x/2, 2)/sqrt(a*cos(x)**3),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x)**3)**(sympy.S(-3)/2),
        variable=x,
        num_steps=4,
        integral=10*sin(x)/(21*a*sqrt(a*cos(x)**3)) + 10*cos(x)**(sympy.S(3)/2)*elliptic_f(x/2, 2)/(21*a*sqrt(a*cos(x)**3)) + 2*tan(x)*sec(x)/(7*a*sqrt(a*cos(x)**3)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x)**3)**(sympy.S(-5)/2),
        variable=x,
        num_steps=6,
        integral=154*sin(x)*cos(x)/(195*a**2*sqrt(a*cos(x)**3)) - 154*cos(x)**(sympy.S(3)/2)*elliptic_e(x/2, 2)/(195*a**2*sqrt(a*cos(x)**3)) + 2*tan(x)*sec(x)**4/(13*a**2*sqrt(a*cos(x)**3)) + 22*tan(x)*sec(x)**2/(117*a**2*sqrt(a*cos(x)**3)) + 154*tan(x)/(585*a**2*sqrt(a*cos(x)**3)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x)**4)**(sympy.S(5)/2),
        variable=x,
        num_steps=7,
        integral=63*a**2*x*sqrt(a*cos(x)**4)*sec(x)**2/256 + a**2*sqrt(a*cos(x)**4)*sin(x)*cos(x)**7/10 + 9*a**2*sqrt(a*cos(x)**4)*sin(x)*cos(x)**5/80 + 21*a**2*sqrt(a*cos(x)**4)*sin(x)*cos(x)**3/160 + 21*a**2*sqrt(a*cos(x)**4)*sin(x)*cos(x)/128 + 63*a**2*sqrt(a*cos(x)**4)*tan(x)/256,
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x)**4)**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=5*a*x*sqrt(a*cos(x)**4)*sec(x)**2/16 + a*sqrt(a*cos(x)**4)*sin(x)*cos(x)**3/6 + 5*a*sqrt(a*cos(x)**4)*sin(x)*cos(x)/24 + 5*a*sqrt(a*cos(x)**4)*tan(x)/16,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*cos(x)**4),
        variable=x,
        num_steps=3,
        integral=x*sqrt(a*cos(x)**4)*sec(x)**2/2 + sqrt(a*cos(x)**4)*tan(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*cos(x)**4),
        variable=x,
        num_steps=3,
        integral=sin(x)*cos(x)/sqrt(a*cos(x)**4),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x)**4)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=sin(x)**2*tan(x)**3/(5*a*sqrt(a*cos(x)**4)) + 2*sin(x)**2*tan(x)/(3*a*sqrt(a*cos(x)**4)) + sin(x)*cos(x)/(a*sqrt(a*cos(x)**4)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(x)**4)**(sympy.S(-5)/2),
        variable=x,
        num_steps=3,
        integral=sin(x)**2*tan(x)**7/(9*a**2*sqrt(a*cos(x)**4)) + 4*sin(x)**2*tan(x)**5/(7*a**2*sqrt(a*cos(x)**4)) + 6*sin(x)**2*tan(x)**3/(5*a**2*sqrt(a*cos(x)**4)) + 4*sin(x)**2*tan(x)/(3*a**2*sqrt(a*cos(x)**4)) + sin(x)*cos(x)/(a**2*sqrt(a*cos(x)**4)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x)**m)**n,
        variable=x,
        num_steps=2,
        integral=-(b*cos(c + d*x)**m)**n*sin(c + d*x)*cos(c + d*x)*hyper((sympy.S.Half, m*n/2 + sympy.S.Half), (m*n/2 + sympy.S(3)/2,), cos(c + d*x)**2)/(d*(m*n + 1)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x)**m)**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=-2*c**2*sqrt(c*cos(a + b*x)**m)*sin(a + b*x)*cos(a + b*x)**(2*m + 1)*hyper((sympy.S.Half, 5*m/4 + sympy.S.Half), (5*m/4 + sympy.S(3)/2,), cos(a + b*x)**2)/(b*(5*m + 2)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x)**m)**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=-2*c*sqrt(c*cos(a + b*x)**m)*sin(a + b*x)*cos(a + b*x)**(m + 1)*hyper((sympy.S.Half, 3*m/4 + sympy.S.Half), (3*m/4 + sympy.S(3)/2,), cos(a + b*x)**2)/(b*(3*m + 2)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(c*cos(a + b*x)**m),
        variable=x,
        num_steps=2,
        integral=-2*sqrt(c*cos(a + b*x)**m)*sin(a + b*x)*cos(a + b*x)*hyper((sympy.S.Half, m/4 + sympy.S.Half), (m/4 + sympy.S(3)/2,), cos(a + b*x)**2)/(b*(m + 2)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(c*cos(a + b*x)**m),
        variable=x,
        num_steps=2,
        integral=-2*sin(a + b*x)*cos(a + b*x)*hyper((sympy.S.Half, sympy.S.Half - m/4), (sympy.S(3)/2 - m/4,), cos(a + b*x)**2)/(b*sqrt(c*cos(a + b*x)**m)*(2 - m)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x)**m)**(sympy.S(-3)/2),
        variable=x,
        num_steps=2,
        integral=-2*sin(a + b*x)*cos(a + b*x)**(1 - m)*hyper((sympy.S.Half, sympy.S.Half - 3*m/4), (sympy.S(3)/2 - 3*m/4,), cos(a + b*x)**2)/(b*c*sqrt(c*cos(a + b*x)**m)*(2 - 3*m)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x)**m)**(sympy.S(-5)/2),
        variable=x,
        num_steps=2,
        integral=-2*sin(a + b*x)*cos(a + b*x)**(1 - 2*m)*hyper((sympy.S.Half, sympy.S.Half - 5*m/4), (sympy.S(3)/2 - 5*m/4,), cos(a + b*x)**2)/(b*c**2*sqrt(c*cos(a + b*x)**m)*(2 - 5*m)*sqrt(sin(a + b*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(c*cos(a + b*x)**m)**(1/m),
        variable=x,
        num_steps=2,
        integral=(c*cos(a + b*x)**m)**(1/m)*tan(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=(a*(b*cos(c + d*x))**p)**n,
        variable=x,
        num_steps=2,
        integral=-(a*(b*cos(c + d*x))**p)**n*sin(c + d*x)*cos(c + d*x)*hyper((sympy.S.Half, n*p/2 + sympy.S.Half), (n*p/2 + sympy.S(3)/2,), cos(c + d*x)**2)/(d*(n*p + 1)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*cos(c + d*x)**5,
        variable=x,
        num_steps=6,
        integral=30*b*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(77*d*sqrt(b*cos(c + d*x))) + 30*sqrt(b*cos(c + d*x))*sin(c + d*x)/(77*d) + 18*(b*cos(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(77*b**2*d) + 2*(b*cos(c + d*x))**(sympy.S(9)/2)*sin(c + d*x)/(11*b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*cos(c + d*x)**4,
        variable=x,
        num_steps=5,
        integral=14*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(15*d*sqrt(cos(c + d*x))) + 14*(b*cos(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(45*b*d) + 2*(b*cos(c + d*x))**(sympy.S(7)/2)*sin(c + d*x)/(9*b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*cos(c + d*x)**3,
        variable=x,
        num_steps=5,
        integral=10*b*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d*sqrt(b*cos(c + d*x))) + 10*sqrt(b*cos(c + d*x))*sin(c + d*x)/(21*d) + 2*(b*cos(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(7*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*cos(c + d*x)**2,
        variable=x,
        num_steps=4,
        integral=6*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(cos(c + d*x))) + 2*(b*cos(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(5*b*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*cos(c + d*x),
        variable=x,
        num_steps=4,
        integral=2*b*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*d*sqrt(b*cos(c + d*x))) + 2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=2,
        integral=2*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*sec(c + d*x),
        variable=x,
        num_steps=3,
        integral=2*b*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*sec(c + d*x)**2,
        variable=x,
        num_steps=4,
        integral=2*b*sin(c + d*x)/(d*sqrt(b*cos(c + d*x))) - 2*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*sec(c + d*x)**3,
        variable=x,
        num_steps=4,
        integral=2*b**2*sin(c + d*x)/(3*d*(b*cos(c + d*x))**(sympy.S(3)/2)) + 2*b*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*sec(c + d*x)**4,
        variable=x,
        num_steps=5,
        integral=2*b**3*sin(c + d*x)/(5*d*(b*cos(c + d*x))**(sympy.S(5)/2)) + 6*b*sin(c + d*x)/(5*d*sqrt(b*cos(c + d*x))) - 6*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*sec(c + d*x)**5,
        variable=x,
        num_steps=5,
        integral=2*b**4*sin(c + d*x)/(7*d*(b*cos(c + d*x))**(sympy.S(7)/2)) + 10*b**2*sin(c + d*x)/(21*d*(b*cos(c + d*x))**(sympy.S(3)/2)) + 10*b*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*sec(c + d*x)**6,
        variable=x,
        num_steps=6,
        integral=2*b**5*sin(c + d*x)/(9*d*(b*cos(c + d*x))**(sympy.S(9)/2)) + 14*b**3*sin(c + d*x)/(45*d*(b*cos(c + d*x))**(sympy.S(5)/2)) + 14*b*sin(c + d*x)/(15*d*sqrt(b*cos(c + d*x))) - 14*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(15*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)*cos(c + d*x)**4,
        variable=x,
        num_steps=6,
        integral=30*b**2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(77*d*sqrt(b*cos(c + d*x))) + 30*b*sqrt(b*cos(c + d*x))*sin(c + d*x)/(77*d) + 18*(b*cos(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(77*b*d) + 2*(b*cos(c + d*x))**(sympy.S(9)/2)*sin(c + d*x)/(11*b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)*cos(c + d*x)**3,
        variable=x,
        num_steps=5,
        integral=14*b*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(15*d*sqrt(cos(c + d*x))) + 14*(b*cos(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(45*d) + 2*(b*cos(c + d*x))**(sympy.S(7)/2)*sin(c + d*x)/(9*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)*cos(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=10*b**2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d*sqrt(b*cos(c + d*x))) + 10*b*sqrt(b*cos(c + d*x))*sin(c + d*x)/(21*d) + 2*(b*cos(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(7*b*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)*cos(c + d*x),
        variable=x,
        num_steps=4,
        integral=6*b*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(cos(c + d*x))) + 2*(b*cos(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*b**2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*d*sqrt(b*cos(c + d*x))) + 2*b*sqrt(b*cos(c + d*x))*sin(c + d*x)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)*sec(c + d*x),
        variable=x,
        num_steps=3,
        integral=2*b*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)*sec(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=2*b**2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)*sec(c + d*x)**3,
        variable=x,
        num_steps=4,
        integral=2*b**2*sin(c + d*x)/(d*sqrt(b*cos(c + d*x))) - 2*b*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)*sec(c + d*x)**4,
        variable=x,
        num_steps=4,
        integral=2*b**3*sin(c + d*x)/(3*d*(b*cos(c + d*x))**(sympy.S(3)/2)) + 2*b**2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)*sec(c + d*x)**5,
        variable=x,
        num_steps=5,
        integral=2*b**4*sin(c + d*x)/(5*d*(b*cos(c + d*x))**(sympy.S(5)/2)) + 6*b**2*sin(c + d*x)/(5*d*sqrt(b*cos(c + d*x))) - 6*b*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)*sec(c + d*x)**6,
        variable=x,
        num_steps=5,
        integral=2*b**5*sin(c + d*x)/(7*d*(b*cos(c + d*x))**(sympy.S(7)/2)) + 10*b**3*sin(c + d*x)/(21*d*(b*cos(c + d*x))**(sympy.S(3)/2)) + 10*b**2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)*sec(c + d*x)**7,
        variable=x,
        num_steps=6,
        integral=2*b**6*sin(c + d*x)/(9*d*(b*cos(c + d*x))**(sympy.S(9)/2)) + 14*b**4*sin(c + d*x)/(45*d*(b*cos(c + d*x))**(sympy.S(5)/2)) + 14*b**2*sin(c + d*x)/(15*d*sqrt(b*cos(c + d*x))) - 14*b*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(15*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)*cos(c + d*x)**3,
        variable=x,
        num_steps=6,
        integral=30*b**3*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(77*d*sqrt(b*cos(c + d*x))) + 30*b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(77*d) + 18*(b*cos(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(77*d) + 2*(b*cos(c + d*x))**(sympy.S(9)/2)*sin(c + d*x)/(11*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)*cos(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=14*b**2*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(15*d*sqrt(cos(c + d*x))) + 14*b*(b*cos(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(45*d) + 2*(b*cos(c + d*x))**(sympy.S(7)/2)*sin(c + d*x)/(9*b*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)*cos(c + d*x),
        variable=x,
        num_steps=5,
        integral=10*b**3*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d*sqrt(b*cos(c + d*x))) + 10*b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(21*d) + 2*(b*cos(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(7*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=6*b**2*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(cos(c + d*x))) + 2*b*(b*cos(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)*sec(c + d*x),
        variable=x,
        num_steps=4,
        integral=2*b**3*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*d*sqrt(b*cos(c + d*x))) + 2*b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)*sec(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=2*b**2*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)*sec(c + d*x)**3,
        variable=x,
        num_steps=3,
        integral=2*b**3*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)*sec(c + d*x)**4,
        variable=x,
        num_steps=4,
        integral=2*b**3*sin(c + d*x)/(d*sqrt(b*cos(c + d*x))) - 2*b**2*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)*sec(c + d*x)**5,
        variable=x,
        num_steps=4,
        integral=2*b**4*sin(c + d*x)/(3*d*(b*cos(c + d*x))**(sympy.S(3)/2)) + 2*b**3*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)*sec(c + d*x)**6,
        variable=x,
        num_steps=5,
        integral=2*b**5*sin(c + d*x)/(5*d*(b*cos(c + d*x))**(sympy.S(5)/2)) + 6*b**3*sin(c + d*x)/(5*d*sqrt(b*cos(c + d*x))) - 6*b**2*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(5*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)*sec(c + d*x)**7,
        variable=x,
        num_steps=5,
        integral=2*b**6*sin(c + d*x)/(7*d*(b*cos(c + d*x))**(sympy.S(7)/2)) + 10*b**4*sin(c + d*x)/(21*d*(b*cos(c + d*x))**(sympy.S(3)/2)) + 10*b**3*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)*sec(c + d*x)**8,
        variable=x,
        num_steps=6,
        integral=2*b**7*sin(c + d*x)/(9*d*(b*cos(c + d*x))**(sympy.S(9)/2)) + 14*b**5*sin(c + d*x)/(45*d*(b*cos(c + d*x))**(sympy.S(5)/2)) + 14*b**3*sin(c + d*x)/(15*d*sqrt(b*cos(c + d*x))) - 14*b**2*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(15*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=4,
        integral=10*b**4*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d*sqrt(b*cos(c + d*x))) + 10*b**3*sqrt(b*cos(c + d*x))*sin(c + d*x)/(21*d) + 2*b*(b*cos(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(7*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**6/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=6,
        integral=30*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(77*d*sqrt(b*cos(c + d*x))) + 30*sqrt(b*cos(c + d*x))*sin(c + d*x)/(77*b*d) + 18*(b*cos(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(77*b**3*d) + 2*(b*cos(c + d*x))**(sympy.S(9)/2)*sin(c + d*x)/(11*b**5*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**5/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=5,
        integral=14*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(15*b*d*sqrt(cos(c + d*x))) + 14*(b*cos(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(45*b**2*d) + 2*(b*cos(c + d*x))**(sympy.S(7)/2)*sin(c + d*x)/(9*b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**4/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=5,
        integral=10*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d*sqrt(b*cos(c + d*x))) + 10*sqrt(b*cos(c + d*x))*sin(c + d*x)/(21*b*d) + 2*(b*cos(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(7*b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=4,
        integral=6*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(5*b*d*sqrt(cos(c + d*x))) + 2*(b*cos(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(5*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=4,
        integral=2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*d*sqrt(b*cos(c + d*x))) + 2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(3*b*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=3,
        integral=2*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(b*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=2,
        integral=2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=4,
        integral=2*sin(c + d*x)/(d*sqrt(b*cos(c + d*x))) - 2*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(b*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=4,
        integral=2*b*sin(c + d*x)/(3*d*(b*cos(c + d*x))**(sympy.S(3)/2)) + 2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=5,
        integral=2*b**2*sin(c + d*x)/(5*d*(b*cos(c + d*x))**(sympy.S(5)/2)) + 6*sin(c + d*x)/(5*d*sqrt(b*cos(c + d*x))) - 6*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(5*b*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**4/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=5,
        integral=2*b**3*sin(c + d*x)/(7*d*(b*cos(c + d*x))**(sympy.S(7)/2)) + 10*b*sin(c + d*x)/(21*d*(b*cos(c + d*x))**(sympy.S(3)/2)) + 10*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**5/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=6,
        integral=2*b**4*sin(c + d*x)/(9*d*(b*cos(c + d*x))**(sympy.S(9)/2)) + 14*b**2*sin(c + d*x)/(45*d*(b*cos(c + d*x))**(sympy.S(5)/2)) + 14*sin(c + d*x)/(15*d*sqrt(b*cos(c + d*x))) - 14*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(15*b*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**7/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=30*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(77*b*d*sqrt(b*cos(c + d*x))) + 30*sqrt(b*cos(c + d*x))*sin(c + d*x)/(77*b**2*d) + 18*(b*cos(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(77*b**4*d) + 2*(b*cos(c + d*x))**(sympy.S(9)/2)*sin(c + d*x)/(11*b**6*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**6/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=14*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(15*b**2*d*sqrt(cos(c + d*x))) + 14*(b*cos(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(45*b**3*d) + 2*(b*cos(c + d*x))**(sympy.S(7)/2)*sin(c + d*x)/(9*b**5*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**5/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=10*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*b*d*sqrt(b*cos(c + d*x))) + 10*sqrt(b*cos(c + d*x))*sin(c + d*x)/(21*b**2*d) + 2*(b*cos(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(7*b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**4/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=6*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(5*b**2*d*sqrt(cos(c + d*x))) + 2*(b*cos(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(5*b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*b*d*sqrt(b*cos(c + d*x))) + 2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(3*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(b**2*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(b*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=2*sin(c + d*x)/(b*d*sqrt(b*cos(c + d*x))) - 2*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(b**2*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=2*sin(c + d*x)/(3*d*(b*cos(c + d*x))**(sympy.S(3)/2)) + 2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*b*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=2*b*sin(c + d*x)/(5*d*(b*cos(c + d*x))**(sympy.S(5)/2)) + 6*sin(c + d*x)/(5*b*d*sqrt(b*cos(c + d*x))) - 6*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(5*b**2*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=2*b**2*sin(c + d*x)/(7*d*(b*cos(c + d*x))**(sympy.S(7)/2)) + 10*sin(c + d*x)/(21*d*(b*cos(c + d*x))**(sympy.S(3)/2)) + 10*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*b*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**4/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=2*b**3*sin(c + d*x)/(9*d*(b*cos(c + d*x))**(sympy.S(9)/2)) + 14*b*sin(c + d*x)/(45*d*(b*cos(c + d*x))**(sympy.S(5)/2)) + 14*sin(c + d*x)/(15*b*d*sqrt(b*cos(c + d*x))) - 14*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(15*b**2*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**8/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=6,
        integral=30*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(77*b**2*d*sqrt(b*cos(c + d*x))) + 30*sqrt(b*cos(c + d*x))*sin(c + d*x)/(77*b**3*d) + 18*(b*cos(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(77*b**5*d) + 2*(b*cos(c + d*x))**(sympy.S(9)/2)*sin(c + d*x)/(11*b**7*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**7/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=14*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(15*b**3*d*sqrt(cos(c + d*x))) + 14*(b*cos(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(45*b**4*d) + 2*(b*cos(c + d*x))**(sympy.S(7)/2)*sin(c + d*x)/(9*b**6*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**6/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=10*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*b**2*d*sqrt(b*cos(c + d*x))) + 10*sqrt(b*cos(c + d*x))*sin(c + d*x)/(21*b**3*d) + 2*(b*cos(c + d*x))**(sympy.S(5)/2)*sin(c + d*x)/(7*b**5*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**5/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=6*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(5*b**3*d*sqrt(cos(c + d*x))) + 2*(b*cos(c + d*x))**(sympy.S(3)/2)*sin(c + d*x)/(5*b**4*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**4/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*b**2*d*sqrt(b*cos(c + d*x))) + 2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(3*b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**3/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(b**3*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(b**2*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=2*sin(c + d*x)/(b**2*d*sqrt(b*cos(c + d*x))) - 2*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(b**3*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(-5)/2),
        variable=x,
        num_steps=3,
        integral=2*sin(c + d*x)/(3*b*d*(b*cos(c + d*x))**(sympy.S(3)/2)) + 2*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(3*b**2*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=2*sin(c + d*x)/(5*d*(b*cos(c + d*x))**(sympy.S(5)/2)) + 6*sin(c + d*x)/(5*b**2*d*sqrt(b*cos(c + d*x))) - 6*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(5*b**3*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=5,
        integral=2*b*sin(c + d*x)/(7*d*(b*cos(c + d*x))**(sympy.S(7)/2)) + 10*sin(c + d*x)/(21*b*d*(b*cos(c + d*x))**(sympy.S(3)/2)) + 10*sqrt(cos(c + d*x))*elliptic_f(c/2 + d*x/2, 2)/(21*b**2*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=6,
        integral=2*b**2*sin(c + d*x)/(9*d*(b*cos(c + d*x))**(sympy.S(9)/2)) + 14*sin(c + d*x)/(45*d*(b*cos(c + d*x))**(sympy.S(5)/2)) + 14*sin(c + d*x)/(15*b**2*d*sqrt(b*cos(c + d*x))) - 14*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(15*b**3*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(-7)/2),
        variable=x,
        num_steps=4,
        integral=2*sin(c + d*x)/(5*b*d*(b*cos(c + d*x))**(sympy.S(5)/2)) + 6*sin(c + d*x)/(5*b**3*d*sqrt(b*cos(c + d*x))) - 6*sqrt(b*cos(c + d*x))*elliptic_e(c/2 + d*x/2, 2)/(5*b**4*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=4,
        integral=3*x*sqrt(b*cos(c + d*x))/(8*sqrt(cos(c + d*x))) + sqrt(b*cos(c + d*x))*sin(c + d*x)*cos(c + d*x)**(sympy.S(5)/2)/(4*d) + 3*sqrt(b*cos(c + d*x))*sin(c + d*x)*sqrt(cos(c + d*x))/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=-sqrt(b*cos(c + d*x))*sin(c + d*x)**3/(3*d*sqrt(cos(c + d*x))) + sqrt(b*cos(c + d*x))*sin(c + d*x)/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=x*sqrt(b*cos(c + d*x))/(2*sqrt(cos(c + d*x))) + sqrt(b*cos(c + d*x))*sin(c + d*x)*sqrt(cos(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))*sqrt(cos(c + d*x)),
        variable=x,
        num_steps=2,
        integral=sqrt(b*cos(c + d*x))*sin(c + d*x)/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))/sqrt(cos(c + d*x)),
        variable=x,
        num_steps=2,
        integral=x*sqrt(b*cos(c + d*x))/sqrt(cos(c + d*x)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))/cos(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=sqrt(b*cos(c + d*x))*atanh(sin(c + d*x))/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))/cos(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=sqrt(b*cos(c + d*x))*sin(c + d*x)/(d*cos(c + d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))/cos(c + d*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=sqrt(b*cos(c + d*x))*sin(c + d*x)/(2*d*cos(c + d*x)**(sympy.S(5)/2)) + sqrt(b*cos(c + d*x))*atanh(sin(c + d*x))/(2*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))/cos(c + d*x)**(sympy.S(9)/2),
        variable=x,
        num_steps=3,
        integral=sqrt(b*cos(c + d*x))*sin(c + d*x)**3/(3*d*cos(c + d*x)**(sympy.S(7)/2)) + sqrt(b*cos(c + d*x))*sin(c + d*x)/(d*cos(c + d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*cos(c + d*x))/cos(c + d*x)**(sympy.S(11)/2),
        variable=x,
        num_steps=4,
        integral=3*sqrt(b*cos(c + d*x))*sin(c + d*x)/(8*d*cos(c + d*x)**(sympy.S(5)/2)) + sqrt(b*cos(c + d*x))*sin(c + d*x)/(4*d*cos(c + d*x)**(sympy.S(9)/2)) + 3*sqrt(b*cos(c + d*x))*atanh(sin(c + d*x))/(8*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)*cos(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=3*b*x*sqrt(b*cos(c + d*x))/(8*sqrt(cos(c + d*x))) + b*sqrt(b*cos(c + d*x))*sin(c + d*x)*cos(c + d*x)**(sympy.S(5)/2)/(4*d) + 3*b*sqrt(b*cos(c + d*x))*sin(c + d*x)*sqrt(cos(c + d*x))/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)*cos(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-b*sqrt(b*cos(c + d*x))*sin(c + d*x)**3/(3*d*sqrt(cos(c + d*x))) + b*sqrt(b*cos(c + d*x))*sin(c + d*x)/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)*sqrt(cos(c + d*x)),
        variable=x,
        num_steps=3,
        integral=b*x*sqrt(b*cos(c + d*x))/(2*sqrt(cos(c + d*x))) + b*sqrt(b*cos(c + d*x))*sin(c + d*x)*sqrt(cos(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)/sqrt(cos(c + d*x)),
        variable=x,
        num_steps=2,
        integral=b*sqrt(b*cos(c + d*x))*sin(c + d*x)/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)/cos(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=b*x*sqrt(b*cos(c + d*x))/sqrt(cos(c + d*x)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)/cos(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=b*sqrt(b*cos(c + d*x))*atanh(sin(c + d*x))/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)/cos(c + d*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=3,
        integral=b*sqrt(b*cos(c + d*x))*sin(c + d*x)/(d*cos(c + d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)/cos(c + d*x)**(sympy.S(9)/2),
        variable=x,
        num_steps=3,
        integral=b*sqrt(b*cos(c + d*x))*sin(c + d*x)/(2*d*cos(c + d*x)**(sympy.S(5)/2)) + b*sqrt(b*cos(c + d*x))*atanh(sin(c + d*x))/(2*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)/cos(c + d*x)**(sympy.S(11)/2),
        variable=x,
        num_steps=3,
        integral=b*sqrt(b*cos(c + d*x))*sin(c + d*x)**3/(3*d*cos(c + d*x)**(sympy.S(7)/2)) + b*sqrt(b*cos(c + d*x))*sin(c + d*x)/(d*cos(c + d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(3)/2)/cos(c + d*x)**(sympy.S(13)/2),
        variable=x,
        num_steps=4,
        integral=3*b*sqrt(b*cos(c + d*x))*sin(c + d*x)/(8*d*cos(c + d*x)**(sympy.S(5)/2)) + b*sqrt(b*cos(c + d*x))*sin(c + d*x)/(4*d*cos(c + d*x)**(sympy.S(9)/2)) + 3*b*sqrt(b*cos(c + d*x))*atanh(sin(c + d*x))/(8*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)*cos(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)**5/(5*d*sqrt(cos(c + d*x))) - 2*b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)**3/(3*d*sqrt(cos(c + d*x))) + b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)*cos(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=3*b**2*x*sqrt(b*cos(c + d*x))/(8*sqrt(cos(c + d*x))) + b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)*cos(c + d*x)**(sympy.S(5)/2)/(4*d) + 3*b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)*sqrt(cos(c + d*x))/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)*sqrt(cos(c + d*x)),
        variable=x,
        num_steps=3,
        integral=-b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)**3/(3*d*sqrt(cos(c + d*x))) + b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)/sqrt(cos(c + d*x)),
        variable=x,
        num_steps=3,
        integral=b**2*x*sqrt(b*cos(c + d*x))/(2*sqrt(cos(c + d*x))) + b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)*sqrt(cos(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)/cos(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)/cos(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=b**2*x*sqrt(b*cos(c + d*x))/sqrt(cos(c + d*x)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)/cos(c + d*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=2,
        integral=b**2*sqrt(b*cos(c + d*x))*atanh(sin(c + d*x))/(d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)/cos(c + d*x)**(sympy.S(9)/2),
        variable=x,
        num_steps=3,
        integral=b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(d*cos(c + d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)/cos(c + d*x)**(sympy.S(11)/2),
        variable=x,
        num_steps=3,
        integral=b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(2*d*cos(c + d*x)**(sympy.S(5)/2)) + b**2*sqrt(b*cos(c + d*x))*atanh(sin(c + d*x))/(2*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)/cos(c + d*x)**(sympy.S(13)/2),
        variable=x,
        num_steps=3,
        integral=b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)**3/(3*d*cos(c + d*x)**(sympy.S(7)/2)) + b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(d*cos(c + d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(5)/2)/cos(c + d*x)**(sympy.S(15)/2),
        variable=x,
        num_steps=4,
        integral=3*b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(8*d*cos(c + d*x)**(sympy.S(5)/2)) + b**2*sqrt(b*cos(c + d*x))*sin(c + d*x)/(4*d*cos(c + d*x)**(sympy.S(9)/2)) + 3*b**2*sqrt(b*cos(c + d*x))*atanh(sin(c + d*x))/(8*d*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(11)/2)/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)**5*sqrt(cos(c + d*x))/(5*d*sqrt(b*cos(c + d*x))) - 2*sin(c + d*x)**3*sqrt(cos(c + d*x))/(3*d*sqrt(b*cos(c + d*x))) + sin(c + d*x)*sqrt(cos(c + d*x))/(d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(9)/2)/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=4,
        integral=3*x*sqrt(cos(c + d*x))/(8*sqrt(b*cos(c + d*x))) + sin(c + d*x)*cos(c + d*x)**(sympy.S(7)/2)/(4*d*sqrt(b*cos(c + d*x))) + 3*sin(c + d*x)*cos(c + d*x)**(sympy.S(3)/2)/(8*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(7)/2)/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=3,
        integral=-sin(c + d*x)**3*sqrt(cos(c + d*x))/(3*d*sqrt(b*cos(c + d*x))) + sin(c + d*x)*sqrt(cos(c + d*x))/(d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(5)/2)/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=3,
        integral=x*sqrt(cos(c + d*x))/(2*sqrt(b*cos(c + d*x))) + sin(c + d*x)*cos(c + d*x)**(sympy.S(3)/2)/(2*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(3)/2)/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=2,
        integral=sin(c + d*x)*sqrt(cos(c + d*x))/(d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(cos(c + d*x))/sqrt(b*cos(c + d*x)),
        variable=x,
        num_steps=2,
        integral=x*sqrt(cos(c + d*x))/sqrt(b*cos(c + d*x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(b*cos(c + d*x))*sqrt(cos(c + d*x))),
        variable=x,
        num_steps=2,
        integral=sqrt(cos(c + d*x))*atanh(sin(c + d*x))/(d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(3)/2)),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)/(d*sqrt(b*cos(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(5)/2)),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)/(2*d*sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(3)/2)) + sqrt(cos(c + d*x))*atanh(sin(c + d*x))/(2*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(7)/2)),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)**3/(3*d*sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(5)/2)) + sin(c + d*x)/(d*sqrt(b*cos(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/(sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(9)/2)),
        variable=x,
        num_steps=4,
        integral=3*sin(c + d*x)/(8*d*sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(3)/2)) + sin(c + d*x)/(4*d*sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(7)/2)) + 3*sqrt(cos(c + d*x))*atanh(sin(c + d*x))/(8*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(11)/2)/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=3*x*sqrt(cos(c + d*x))/(8*b*sqrt(b*cos(c + d*x))) + sin(c + d*x)*cos(c + d*x)**(sympy.S(7)/2)/(4*b*d*sqrt(b*cos(c + d*x))) + 3*sin(c + d*x)*cos(c + d*x)**(sympy.S(3)/2)/(8*b*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(9)/2)/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-sin(c + d*x)**3*sqrt(cos(c + d*x))/(3*b*d*sqrt(b*cos(c + d*x))) + sin(c + d*x)*sqrt(cos(c + d*x))/(b*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(7)/2)/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=x*sqrt(cos(c + d*x))/(2*b*sqrt(b*cos(c + d*x))) + sin(c + d*x)*cos(c + d*x)**(sympy.S(3)/2)/(2*b*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(5)/2)/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=sin(c + d*x)*sqrt(cos(c + d*x))/(b*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(3)/2)/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=x*sqrt(cos(c + d*x))/(b*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(cos(c + d*x))/(b*cos(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=sqrt(cos(c + d*x))*atanh(sin(c + d*x))/(b*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((b*cos(c + d*x))**(sympy.S(3)/2)*sqrt(cos(c + d*x))),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)/(b*d*sqrt(b*cos(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((b*cos(c + d*x))**(sympy.S(3)/2)*cos(c + d*x)**(sympy.S(3)/2)),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)/(2*b*d*sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(3)/2)) + sqrt(cos(c + d*x))*atanh(sin(c + d*x))/(2*b*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((b*cos(c + d*x))**(sympy.S(3)/2)*cos(c + d*x)**(sympy.S(5)/2)),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)**3/(3*b*d*sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(5)/2)) + sin(c + d*x)/(b*d*sqrt(b*cos(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((b*cos(c + d*x))**(sympy.S(3)/2)*cos(c + d*x)**(sympy.S(7)/2)),
        variable=x,
        num_steps=4,
        integral=3*sin(c + d*x)/(8*b*d*sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(3)/2)) + sin(c + d*x)/(4*b*d*sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(7)/2)) + 3*sqrt(cos(c + d*x))*atanh(sin(c + d*x))/(8*b*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(13)/2)/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=3*x*sqrt(cos(c + d*x))/(8*b**2*sqrt(b*cos(c + d*x))) + sin(c + d*x)*cos(c + d*x)**(sympy.S(7)/2)/(4*b**2*d*sqrt(b*cos(c + d*x))) + 3*sin(c + d*x)*cos(c + d*x)**(sympy.S(3)/2)/(8*b**2*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(11)/2)/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=-sin(c + d*x)**3*sqrt(cos(c + d*x))/(3*b**2*d*sqrt(b*cos(c + d*x))) + sin(c + d*x)*sqrt(cos(c + d*x))/(b**2*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(9)/2)/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=x*sqrt(cos(c + d*x))/(2*b**2*sqrt(b*cos(c + d*x))) + sin(c + d*x)*cos(c + d*x)**(sympy.S(3)/2)/(2*b**2*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(7)/2)/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=sin(c + d*x)*sqrt(cos(c + d*x))/(b**2*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(5)/2)/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=x*sqrt(cos(c + d*x))/(b**2*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**(sympy.S(3)/2)/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=sqrt(cos(c + d*x))*atanh(sin(c + d*x))/(b**2*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(cos(c + d*x))/(b*cos(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)/(b**2*d*sqrt(b*cos(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((b*cos(c + d*x))**(sympy.S(5)/2)*sqrt(cos(c + d*x))),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)/(2*b**2*d*sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(3)/2)) + sqrt(cos(c + d*x))*atanh(sin(c + d*x))/(2*b**2*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((b*cos(c + d*x))**(sympy.S(5)/2)*cos(c + d*x)**(sympy.S(3)/2)),
        variable=x,
        num_steps=3,
        integral=sin(c + d*x)**3/(3*b**2*d*sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(5)/2)) + sin(c + d*x)/(b**2*d*sqrt(b*cos(c + d*x))*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=1/((b*cos(c + d*x))**(sympy.S(5)/2)*cos(c + d*x)**(sympy.S(5)/2)),
        variable=x,
        num_steps=4,
        integral=3*sin(c + d*x)/(8*b**2*d*sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(3)/2)) + sin(c + d*x)/(4*b**2*d*sqrt(b*cos(c + d*x))*cos(c + d*x)**(sympy.S(7)/2)) + 3*sqrt(cos(c + d*x))*atanh(sin(c + d*x))/(8*b**2*d*sqrt(b*cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(1)/3)*cos(c + d*x)**m,
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(1)/3)*sin(c + d*x)*cos(c + d*x)**(m + 1)*hyper((sympy.S.Half, m/2 + sympy.S(2)/3), (m/2 + sympy.S(5)/3,), cos(c + d*x)**2)/(d*(3*m + 4)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(1)/3)*cos(c + d*x)**2,
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(10)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(5)/3), (sympy.S(8)/3,), cos(c + d*x)**2)/(10*b**3*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(1)/3)*cos(c + d*x),
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(7)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(7)/6), (sympy.S(13)/6,), cos(c + d*x)**2)/(7*b**2*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=1,
        integral=-3*(b*cos(c + d*x))**(sympy.S(4)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(2)/3), (sympy.S(5)/3,), cos(c + d*x)**2)/(4*b*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(1)/3)*sec(c + d*x),
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(1)/3)*sin(c + d*x)*hyper((sympy.S(1)/6, sympy.S.Half), (sympy.S(7)/6,), cos(c + d*x)**2)/(d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(1)/3)*sec(c + d*x)**2,
        variable=x,
        num_steps=2,
        integral=3*b*sin(c + d*x)*hyper((sympy.S(-1)/3, sympy.S.Half), (sympy.S(2)/3,), cos(c + d*x)**2)/(2*d*(b*cos(c + d*x))**(sympy.S(2)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(1)/3)*sec(c + d*x)**3,
        variable=x,
        num_steps=2,
        integral=3*b**2*sin(c + d*x)*hyper((sympy.S(-5)/6, sympy.S.Half), (sympy.S(1)/6,), cos(c + d*x)**2)/(5*d*(b*cos(c + d*x))**(sympy.S(5)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(2)/3)*cos(c + d*x)**m,
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(2)/3)*sin(c + d*x)*cos(c + d*x)**(m + 1)*hyper((sympy.S.Half, m/2 + sympy.S(5)/6), (m/2 + sympy.S(11)/6,), cos(c + d*x)**2)/(d*(3*m + 5)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(2)/3)*cos(c + d*x)**2,
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(11)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(11)/6), (sympy.S(17)/6,), cos(c + d*x)**2)/(11*b**3*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(2)/3)*cos(c + d*x),
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(8)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(4)/3), (sympy.S(7)/3,), cos(c + d*x)**2)/(8*b**2*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(2)/3),
        variable=x,
        num_steps=1,
        integral=-3*(b*cos(c + d*x))**(sympy.S(5)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(5)/6), (sympy.S(11)/6,), cos(c + d*x)**2)/(5*b*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(2)/3)*sec(c + d*x),
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(2)/3)*sin(c + d*x)*hyper((sympy.S(1)/3, sympy.S.Half), (sympy.S(4)/3,), cos(c + d*x)**2)/(2*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(2)/3)*sec(c + d*x)**2,
        variable=x,
        num_steps=2,
        integral=3*b*sin(c + d*x)*hyper((sympy.S(-1)/6, sympy.S.Half), (sympy.S(5)/6,), cos(c + d*x)**2)/(d*(b*cos(c + d*x))**(sympy.S(1)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(2)/3)*sec(c + d*x)**3,
        variable=x,
        num_steps=2,
        integral=3*b**2*sin(c + d*x)*hyper((sympy.S(-2)/3, sympy.S.Half), (sympy.S(1)/3,), cos(c + d*x)**2)/(4*d*(b*cos(c + d*x))**(sympy.S(4)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(4)/3)*cos(c + d*x)**m,
        variable=x,
        num_steps=2,
        integral=-3*b*(b*cos(c + d*x))**(sympy.S(1)/3)*sin(c + d*x)*cos(c + d*x)**(m + 2)*hyper((sympy.S.Half, m/2 + sympy.S(7)/6), (m/2 + sympy.S(13)/6,), cos(c + d*x)**2)/(d*(3*m + 7)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(4)/3)*cos(c + d*x)**2,
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(13)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(13)/6), (sympy.S(19)/6,), cos(c + d*x)**2)/(13*b**3*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(4)/3)*cos(c + d*x),
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(10)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(5)/3), (sympy.S(8)/3,), cos(c + d*x)**2)/(10*b**2*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=1,
        integral=-3*(b*cos(c + d*x))**(sympy.S(7)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(7)/6), (sympy.S(13)/6,), cos(c + d*x)**2)/(7*b*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(4)/3)*sec(c + d*x),
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(4)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(2)/3), (sympy.S(5)/3,), cos(c + d*x)**2)/(4*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(4)/3)*sec(c + d*x)**2,
        variable=x,
        num_steps=2,
        integral=-3*b*(b*cos(c + d*x))**(sympy.S(1)/3)*sin(c + d*x)*hyper((sympy.S(1)/6, sympy.S.Half), (sympy.S(7)/6,), cos(c + d*x)**2)/(d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(4)/3)*sec(c + d*x)**3,
        variable=x,
        num_steps=2,
        integral=3*b**2*sin(c + d*x)*hyper((sympy.S(-1)/3, sympy.S.Half), (sympy.S(2)/3,), cos(c + d*x)**2)/(2*d*(b*cos(c + d*x))**(sympy.S(2)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**m/(b*cos(c + d*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=2,
        integral=-3*sin(c + d*x)*cos(c + d*x)**(m + 1)*hyper((sympy.S.Half, m/2 + sympy.S(1)/3), (m/2 + sympy.S(4)/3,), cos(c + d*x)**2)/(d*(b*cos(c + d*x))**(sympy.S(1)/3)*(3*m + 2)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(b*cos(c + d*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(8)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(4)/3), (sympy.S(7)/3,), cos(c + d*x)**2)/(8*b**3*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(b*cos(c + d*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(5)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(5)/6), (sympy.S(11)/6,), cos(c + d*x)**2)/(5*b**2*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(-1)/3),
        variable=x,
        num_steps=1,
        integral=-3*(b*cos(c + d*x))**(sympy.S(2)/3)*sin(c + d*x)*hyper((sympy.S(1)/3, sympy.S.Half), (sympy.S(4)/3,), cos(c + d*x)**2)/(2*b*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(b*cos(c + d*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=2,
        integral=3*sin(c + d*x)*hyper((sympy.S(-1)/6, sympy.S.Half), (sympy.S(5)/6,), cos(c + d*x)**2)/(d*(b*cos(c + d*x))**(sympy.S(1)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(b*cos(c + d*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=2,
        integral=3*b*sin(c + d*x)*hyper((sympy.S(-2)/3, sympy.S.Half), (sympy.S(1)/3,), cos(c + d*x)**2)/(4*d*(b*cos(c + d*x))**(sympy.S(4)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(b*cos(c + d*x))**(sympy.S(1)/3),
        variable=x,
        num_steps=2,
        integral=3*b**2*sin(c + d*x)*hyper((sympy.S(-7)/6, sympy.S.Half), (sympy.S(-1)/6,), cos(c + d*x)**2)/(7*d*(b*cos(c + d*x))**(sympy.S(7)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**m/(b*cos(c + d*x))**(sympy.S(2)/3),
        variable=x,
        num_steps=2,
        integral=-3*sin(c + d*x)*cos(c + d*x)**(m + 1)*hyper((sympy.S.Half, m/2 + sympy.S(1)/6), (m/2 + sympy.S(7)/6,), cos(c + d*x)**2)/(d*(b*cos(c + d*x))**(sympy.S(2)/3)*(3*m + 1)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(b*cos(c + d*x))**(sympy.S(2)/3),
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(7)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(7)/6), (sympy.S(13)/6,), cos(c + d*x)**2)/(7*b**3*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(b*cos(c + d*x))**(sympy.S(2)/3),
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(4)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(2)/3), (sympy.S(5)/3,), cos(c + d*x)**2)/(4*b**2*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(-2)/3),
        variable=x,
        num_steps=1,
        integral=-3*(b*cos(c + d*x))**(sympy.S(1)/3)*sin(c + d*x)*hyper((sympy.S(1)/6, sympy.S.Half), (sympy.S(7)/6,), cos(c + d*x)**2)/(b*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(b*cos(c + d*x))**(sympy.S(2)/3),
        variable=x,
        num_steps=2,
        integral=3*sin(c + d*x)*hyper((sympy.S(-1)/3, sympy.S.Half), (sympy.S(2)/3,), cos(c + d*x)**2)/(2*d*(b*cos(c + d*x))**(sympy.S(2)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(b*cos(c + d*x))**(sympy.S(2)/3),
        variable=x,
        num_steps=2,
        integral=3*b*sin(c + d*x)*hyper((sympy.S(-5)/6, sympy.S.Half), (sympy.S(1)/6,), cos(c + d*x)**2)/(5*d*(b*cos(c + d*x))**(sympy.S(5)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(b*cos(c + d*x))**(sympy.S(2)/3),
        variable=x,
        num_steps=2,
        integral=3*b**2*sin(c + d*x)*hyper((sympy.S(-4)/3, sympy.S.Half), (sympy.S(-1)/3,), cos(c + d*x)**2)/(8*d*(b*cos(c + d*x))**(sympy.S(8)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**m/(b*cos(c + d*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=2,
        integral=3*sin(c + d*x)*cos(c + d*x)**m*hyper((sympy.S.Half, m/2 + sympy.S(-1)/6), (m/2 + sympy.S(5)/6,), cos(c + d*x)**2)/(b*d*(b*cos(c + d*x))**(sympy.S(1)/3)*(1 - 3*m)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)**2/(b*cos(c + d*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(5)/3)*sin(c + d*x)*hyper((sympy.S.Half, sympy.S(5)/6), (sympy.S(11)/6,), cos(c + d*x)**2)/(5*b**3*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(c + d*x)/(b*cos(c + d*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=2,
        integral=-3*(b*cos(c + d*x))**(sympy.S(2)/3)*sin(c + d*x)*hyper((sympy.S(1)/3, sympy.S.Half), (sympy.S(4)/3,), cos(c + d*x)**2)/(2*b**2*d*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**(sympy.S(-4)/3),
        variable=x,
        num_steps=1,
        integral=3*sin(c + d*x)*hyper((sympy.S(-1)/6, sympy.S.Half), (sympy.S(5)/6,), cos(c + d*x)**2)/(b*d*(b*cos(c + d*x))**(sympy.S(1)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)/(b*cos(c + d*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=2,
        integral=3*sin(c + d*x)*hyper((sympy.S(-2)/3, sympy.S.Half), (sympy.S(1)/3,), cos(c + d*x)**2)/(4*d*(b*cos(c + d*x))**(sympy.S(4)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**2/(b*cos(c + d*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=2,
        integral=3*b*sin(c + d*x)*hyper((sympy.S(-7)/6, sympy.S.Half), (sympy.S(-1)/6,), cos(c + d*x)**2)/(7*d*(b*cos(c + d*x))**(sympy.S(7)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sec(c + d*x)**3/(b*cos(c + d*x))**(sympy.S(4)/3),
        variable=x,
        num_steps=2,
        integral=3*b**2*sin(c + d*x)*hyper((sympy.S(-5)/3, sympy.S.Half), (sympy.S(-2)/3,), cos(c + d*x)**2)/(10*d*(b*cos(c + d*x))**(sympy.S(10)/3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(e + f*x))**m*(b*cos(e + f*x))**n,
        variable=x,
        num_steps=2,
        integral=-(a*cos(e + f*x))**(m + 1)*(b*cos(e + f*x))**n*sin(e + f*x)*hyper((sympy.S.Half, m/2 + n/2 + sympy.S.Half), (m/2 + n/2 + sympy.S(3)/2,), cos(e + f*x)**2)/(a*f*(m + n + 1)*sqrt(sin(e + f*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n*cos(c + d*x)**2,
        variable=x,
        num_steps=2,
        integral=-(b*cos(c + d*x))**(n + 3)*sin(c + d*x)*hyper((sympy.S.Half, n/2 + sympy.S(3)/2), (n/2 + sympy.S(5)/2,), cos(c + d*x)**2)/(b**3*d*(n + 3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n*cos(c + d*x),
        variable=x,
        num_steps=2,
        integral=-(b*cos(c + d*x))**(n + 2)*sin(c + d*x)*hyper((sympy.S.Half, n/2 + 1), (n/2 + 2,), cos(c + d*x)**2)/(b**2*d*(n + 2)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n,
        variable=x,
        num_steps=1,
        integral=-(b*cos(c + d*x))**(n + 1)*sin(c + d*x)*hyper((sympy.S.Half, n/2 + sympy.S.Half), (n/2 + sympy.S(3)/2,), cos(c + d*x)**2)/(b*d*(n + 1)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n*sec(c + d*x),
        variable=x,
        num_steps=2,
        integral=-(b*cos(c + d*x))**n*sin(c + d*x)*hyper((sympy.S.Half, n/2), (n/2 + 1,), cos(c + d*x)**2)/(d*n*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n*sec(c + d*x)**2,
        variable=x,
        num_steps=2,
        integral=b*(b*cos(c + d*x))**(n - 1)*sin(c + d*x)*hyper((sympy.S.Half, n/2 + sympy.S(-1)/2), (n/2 + sympy.S.Half,), cos(c + d*x)**2)/(d*(1 - n)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n*sec(c + d*x)**3,
        variable=x,
        num_steps=2,
        integral=b**2*(b*cos(c + d*x))**(n - 2)*sin(c + d*x)*hyper((sympy.S.Half, n/2 - 1), (n/2,), cos(c + d*x)**2)/(d*(2 - n)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n*sec(c + d*x)**4,
        variable=x,
        num_steps=2,
        integral=b**3*(b*cos(c + d*x))**(n - 3)*sin(c + d*x)*hyper((sympy.S.Half, n/2 + sympy.S(-3)/2), (n/2 + sympy.S(-1)/2,), cos(c + d*x)**2)/(d*(3 - n)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n*cos(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=-2*(b*cos(c + d*x))**n*sin(c + d*x)*cos(c + d*x)**(sympy.S(7)/2)*hyper((sympy.S.Half, n/2 + sympy.S(7)/4), (n/2 + sympy.S(11)/4,), cos(c + d*x)**2)/(d*(2*n + 7)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n*cos(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=-2*(b*cos(c + d*x))**n*sin(c + d*x)*cos(c + d*x)**(sympy.S(5)/2)*hyper((sympy.S.Half, n/2 + sympy.S(5)/4), (n/2 + sympy.S(9)/4,), cos(c + d*x)**2)/(d*(2*n + 5)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n*sqrt(cos(c + d*x)),
        variable=x,
        num_steps=2,
        integral=-2*(b*cos(c + d*x))**n*sin(c + d*x)*cos(c + d*x)**(sympy.S(3)/2)*hyper((sympy.S.Half, n/2 + sympy.S(3)/4), (n/2 + sympy.S(7)/4,), cos(c + d*x)**2)/(d*(2*n + 3)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n/sqrt(cos(c + d*x)),
        variable=x,
        num_steps=2,
        integral=-2*(b*cos(c + d*x))**n*sin(c + d*x)*sqrt(cos(c + d*x))*hyper((sympy.S.Half, n/2 + sympy.S(1)/4), (n/2 + sympy.S(5)/4,), cos(c + d*x)**2)/(d*(2*n + 1)*sqrt(sin(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n/cos(c + d*x)**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=2*(b*cos(c + d*x))**n*sin(c + d*x)*hyper((sympy.S.Half, n/2 + sympy.S(-1)/4), (n/2 + sympy.S(3)/4,), cos(c + d*x)**2)/(d*(1 - 2*n)*sqrt(sin(c + d*x)**2)*sqrt(cos(c + d*x))),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n/cos(c + d*x)**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=2*(b*cos(c + d*x))**n*sin(c + d*x)*hyper((sympy.S.Half, n/2 + sympy.S(-3)/4), (n/2 + sympy.S(1)/4,), cos(c + d*x)**2)/(d*(3 - 2*n)*sqrt(sin(c + d*x)**2)*cos(c + d*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n/cos(c + d*x)**(sympy.S(7)/2),
        variable=x,
        num_steps=2,
        integral=2*(b*cos(c + d*x))**n*sin(c + d*x)*hyper((sympy.S.Half, n/2 + sympy.S(-5)/4), (n/2 + sympy.S(-1)/4,), cos(c + d*x)**2)/(d*(5 - 2*n)*sqrt(sin(c + d*x)**2)*cos(c + d*x)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x))**n/cos(c + d*x)**(sympy.S(9)/2),
        variable=x,
        num_steps=2,
        integral=2*(b*cos(c + d*x))**n*sin(c + d*x)*hyper((sympy.S.Half, n/2 + sympy.S(-7)/4), (n/2 + sympy.S(-3)/4,), cos(c + d*x)**2)/(d*(7 - 2*n)*sqrt(sin(c + d*x)**2)*cos(c + d*x)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(e + f*x))**m*(b*sec(e + f*x))**n,
        variable=x,
        num_steps=2,
        integral=-(a*cos(e + f*x))**(m + 1)*(b*sec(e + f*x))**n*sin(e + f*x)*hyper((sympy.S.Half, m/2 - n/2 + sympy.S.Half), (m/2 - n/2 + sympy.S(3)/2,), cos(e + f*x)**2)/(a*f*(m - n + 1)*sqrt(sin(e + f*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)*sqrt(csc(a + b*x)),
        variable=x,
        num_steps=2,
        integral=2/(b*sqrt(csc(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)/sqrt(csc(a + b*x)),
        variable=x,
        num_steps=2,
        integral=2/(3*b*csc(a + b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2*sqrt(csc(a + b*x)),
        variable=x,
        num_steps=3,
        integral=4*sqrt(sin(a + b*x))*sqrt(csc(a + b*x))*elliptic_f(a/2 + b*x/2 - pi/4, 2)/(3*b) + 2*cos(a + b*x)/(3*b*sqrt(csc(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**2/sqrt(csc(a + b*x)),
        variable=x,
        num_steps=3,
        integral=4*sqrt(sin(a + b*x))*sqrt(csc(a + b*x))*elliptic_e(a/2 + b*x/2 - pi/4, 2)/(5*b) + 2*cos(a + b*x)/(5*b*csc(a + b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**3*csc(x)**(sympy.S(9)/2),
        variable=x,
        num_steps=3,
        integral=-2*csc(x)**(sympy.S(7)/2)/7 + 2*csc(x)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3*sqrt(csc(a + b*x)),
        variable=x,
        num_steps=3,
        integral=2/(b*sqrt(csc(a + b*x))) - 2/(5*b*csc(a + b*x)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**3/sqrt(csc(a + b*x)),
        variable=x,
        num_steps=3,
        integral=2/(3*b*csc(a + b*x)**(sympy.S(3)/2)) - 2/(7*b*csc(a + b*x)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**4*sqrt(csc(a + b*x)),
        variable=x,
        num_steps=4,
        integral=8*sqrt(sin(a + b*x))*sqrt(csc(a + b*x))*elliptic_f(a/2 + b*x/2 - pi/4, 2)/(7*b) + 2*cos(a + b*x)**3/(7*b*sqrt(csc(a + b*x))) + 4*cos(a + b*x)/(7*b*sqrt(csc(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x)**4/sqrt(csc(a + b*x)),
        variable=x,
        num_steps=4,
        integral=8*sqrt(sin(a + b*x))*sqrt(csc(a + b*x))*elliptic_e(a/2 + b*x/2 - pi/4, 2)/(15*b) + 2*cos(a + b*x)**3/(9*b*csc(a + b*x)**(sympy.S(3)/2)) + 4*cos(a + b*x)/(15*b*csc(a + b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)*csc(x)**(sympy.S(7)/3),
        variable=x,
        num_steps=2,
        integral=-3*csc(x)**(sympy.S(4)/3)/4,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(csc(a + b*x))*sec(a + b*x),
        variable=x,
        num_steps=5,
        integral=-atan(sqrt(csc(a + b*x)))/b + atanh(sqrt(csc(a + b*x)))/b,
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)/sqrt(csc(a + b*x)),
        variable=x,
        num_steps=5,
        integral=atan(sqrt(csc(a + b*x)))/b + atanh(sqrt(csc(a + b*x)))/b,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(csc(a + b*x))*sec(a + b*x)**2,
        variable=x,
        num_steps=3,
        integral=sqrt(sin(a + b*x))*sqrt(csc(a + b*x))*elliptic_f(a/2 + b*x/2 - pi/4, 2)/b + sec(a + b*x)/(b*sqrt(csc(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**2/sqrt(csc(a + b*x)),
        variable=x,
        num_steps=3,
        integral=-sqrt(sin(a + b*x))*sqrt(csc(a + b*x))*elliptic_e(a/2 + b*x/2 - pi/4, 2)/b + sec(a + b*x)/(b*csc(a + b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(csc(a + b*x))*sec(a + b*x)**3,
        variable=x,
        num_steps=6,
        integral=-3*atan(sqrt(csc(a + b*x)))/(4*b) + 3*atanh(sqrt(csc(a + b*x)))/(4*b) + sec(a + b*x)**2/(2*b*sqrt(csc(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**3/sqrt(csc(a + b*x)),
        variable=x,
        num_steps=6,
        integral=atan(sqrt(csc(a + b*x)))/(4*b) + atanh(sqrt(csc(a + b*x)))/(4*b) + sec(a + b*x)**2/(2*b*csc(a + b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(csc(a + b*x))*sec(a + b*x)**4,
        variable=x,
        num_steps=4,
        integral=5*sqrt(sin(a + b*x))*sqrt(csc(a + b*x))*elliptic_f(a/2 + b*x/2 - pi/4, 2)/(6*b) + sec(a + b*x)**3/(3*b*sqrt(csc(a + b*x))) + 5*sec(a + b*x)/(6*b*sqrt(csc(a + b*x))),
    ),
    RubiTestSuiteCase(
        integrand=sec(a + b*x)**4/sqrt(csc(a + b*x)),
        variable=x,
        num_steps=4,
        integral=-sqrt(sin(a + b*x))*sqrt(csc(a + b*x))*elliptic_e(a/2 + b*x/2 - pi/4, 2)/(2*b) + sec(a + b*x)**3/(3*b*csc(a + b*x)**(sympy.S(3)/2)) + sec(a + b*x)/(2*b*csc(a + b*x)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(d*cos(a + b*x))**(sympy.S(3)/2)*csc(a + b*x)**p,
        variable=x,
        num_steps=2,
        integral=d*sqrt(d*cos(a + b*x))*csc(a + b*x)**(p - 1)*hyper((sympy.S(-1)/4, sympy.S.Half - p/2), (sympy.S(3)/2 - p/2,), sin(a + b*x)**2)/(b*(1 - p)*(cos(a + b*x)**2)**(sympy.S(1)/4)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(d*cos(a + b*x))*csc(a + b*x)**p,
        variable=x,
        num_steps=2,
        integral=d*(cos(a + b*x)**2)**(sympy.S(1)/4)*csc(a + b*x)**(p - 1)*hyper((sympy.S(1)/4, sympy.S.Half - p/2), (sympy.S(3)/2 - p/2,), sin(a + b*x)**2)/(b*sqrt(d*cos(a + b*x))*(1 - p)),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**p/sqrt(d*cos(a + b*x)),
        variable=x,
        num_steps=2,
        integral=d*(cos(a + b*x)**2)**(sympy.S(3)/4)*csc(a + b*x)**(p - 1)*hyper((sympy.S(3)/4, sympy.S.Half - p/2), (sympy.S(3)/2 - p/2,), sin(a + b*x)**2)/(b*(d*cos(a + b*x))**(sympy.S(3)/2)*(1 - p)),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**p/(d*cos(a + b*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=(cos(a + b*x)**2)**(sympy.S(1)/4)*csc(a + b*x)**(p - 1)*hyper((sympy.S(5)/4, sympy.S.Half - p/2), (sympy.S(3)/2 - p/2,), sin(a + b*x)**2)/(b*d*sqrt(d*cos(a + b*x))*(1 - p)),
    ),
    RubiTestSuiteCase(
        integrand=csc(a + b*x)**p/(d*cos(a + b*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=(cos(a + b*x)**2)**(sympy.S(3)/4)*csc(a + b*x)**(p - 1)*hyper((sympy.S(7)/4, sympy.S.Half - p/2), (sympy.S(3)/2 - p/2,), sin(a + b*x)**2)/(b*d*(d*cos(a + b*x))**(sympy.S(3)/2)*(1 - p)),
    ),
    RubiTestSuiteCase(
        integrand=cos(e + f*x)**m*csc(e + f*x)**n,
        variable=x,
        num_steps=2,
        integral=(cos(e + f*x)**2)**(sympy.S.Half - m/2)*cos(e + f*x)**(m - 1)*csc(e + f*x)**(n - 1)*hyper((sympy.S.Half - m/2, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)/(f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(e + f*x))**m*csc(e + f*x)**n,
        variable=x,
        num_steps=2,
        integral=a*(a*cos(e + f*x))**(m - 1)*(cos(e + f*x)**2)**(sympy.S.Half - m/2)*csc(e + f*x)**(n - 1)*hyper((sympy.S.Half - m/2, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)/(f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(b*csc(e + f*x))**n*cos(e + f*x)**m,
        variable=x,
        num_steps=2,
        integral=b*(b*csc(e + f*x))**(n - 1)*(cos(e + f*x)**2)**(sympy.S.Half - m/2)*cos(e + f*x)**(m - 1)*hyper((sympy.S.Half - m/2, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)/(f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(e + f*x))**m*(b*csc(e + f*x))**n,
        variable=x,
        num_steps=2,
        integral=a*b*(a*cos(e + f*x))**(m - 1)*(b*csc(e + f*x))**(n - 1)*(cos(e + f*x)**2)**(sympy.S.Half - m/2)*hyper((sympy.S.Half - m/2, sympy.S.Half - n/2), (sympy.S(3)/2 - n/2,), sin(e + f*x)**2)/(f*(1 - n)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(e + f*x))**m*(b*csc(e + f*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=2,
        integral=-b*(a*cos(e + f*x))**(m + 1)*(b*csc(e + f*x))**(sympy.S(3)/2)*(sin(e + f*x)**2)**(sympy.S(3)/4)*hyper((sympy.S(7)/4, m/2 + sympy.S.Half), (m/2 + sympy.S(3)/2,), cos(e + f*x)**2)/(a*f*(m + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(e + f*x))**m*(b*csc(e + f*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=-b*(a*cos(e + f*x))**(m + 1)*sqrt(b*csc(e + f*x))*(sin(e + f*x)**2)**(sympy.S(1)/4)*hyper((sympy.S(5)/4, m/2 + sympy.S.Half), (m/2 + sympy.S(3)/2,), cos(e + f*x)**2)/(a*f*(m + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(e + f*x))**m*sqrt(b*csc(e + f*x)),
        variable=x,
        num_steps=2,
        integral=-(a*cos(e + f*x))**(m + 1)*(b*csc(e + f*x))**(sympy.S(3)/2)*(sin(e + f*x)**2)**(sympy.S(3)/4)*hyper((sympy.S(3)/4, m/2 + sympy.S.Half), (m/2 + sympy.S(3)/2,), cos(e + f*x)**2)/(a*b*f*(m + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(e + f*x))**m/sqrt(b*csc(e + f*x)),
        variable=x,
        num_steps=2,
        integral=-(a*cos(e + f*x))**(m + 1)*sqrt(b*csc(e + f*x))*(sin(e + f*x)**2)**(sympy.S(1)/4)*hyper((sympy.S(1)/4, m/2 + sympy.S.Half), (m/2 + sympy.S(3)/2,), cos(e + f*x)**2)/(a*b*f*(m + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(a*cos(e + f*x))**m/(b*csc(e + f*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=2,
        integral=-(a*cos(e + f*x))**(m + 1)*hyper((sympy.S(-1)/4, m/2 + sympy.S.Half), (m/2 + sympy.S(3)/2,), cos(e + f*x)**2)/(a*b*f*sqrt(b*csc(e + f*x))*(m + 1)*(sin(e + f*x)**2)**(sympy.S(1)/4)),
    ),
]
