# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 4 Trig functions/4.2 Cosine/4.2.7 (d trig)^m (a+b (c cos)^n)^p.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '4 Trig functions/4.2 Cosine/4.2.7 (d trig)^m (a+b (c cos)^n)^p.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, n = symbols('a b n')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=sin(x)**6/(-a*cos(x)**2 + a),
        variable=x,
        num_steps=4,
        integral=3*x/(8*a) - sin(x)**3*cos(x)/(4*a) - 3*sin(x)*cos(x)/(8*a),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**5/(-a*cos(x)**2 + a),
        variable=x,
        num_steps=3,
        integral=cos(x)**3/(3*a) - cos(x)/a,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**4/(-a*cos(x)**2 + a),
        variable=x,
        num_steps=3,
        integral=x/(2*a) - sin(x)*cos(x)/(2*a),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3/(-a*cos(x)**2 + a),
        variable=x,
        num_steps=2,
        integral=-cos(x)/a,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2/(-a*cos(x)**2 + a),
        variable=x,
        num_steps=2,
        integral=x/a,
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/(-a*cos(x)**2 + a),
        variable=x,
        num_steps=2,
        integral=-atanh(cos(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=csc(x)/(-a*cos(x)**2 + a),
        variable=x,
        num_steps=3,
        integral=-cot(x)*csc(x)/(2*a) - atanh(cos(x))/(2*a),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**2/(-a*cos(x)**2 + a),
        variable=x,
        num_steps=3,
        integral=-cot(x)**3/(3*a) - cot(x)/a,
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**3/(-a*cos(x)**2 + a),
        variable=x,
        num_steps=4,
        integral=-cot(x)*csc(x)**3/(4*a) - 3*cot(x)*csc(x)/(8*a) - 3*atanh(cos(x))/(8*a),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**7/(a + b*cos(x)**2),
        variable=x,
        num_steps=4,
        integral=cos(x)**5/(5*b) - (a + 3*b)*cos(x)**3/(3*b**2) + (a**2 + 3*a*b + 3*b**2)*cos(x)/b**3 - (a + b)**3*atan(sqrt(b)*cos(x)/sqrt(a))/(sqrt(a)*b**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**5/(a + b*cos(x)**2),
        variable=x,
        num_steps=4,
        integral=-cos(x)**3/(3*b) + (a + 2*b)*cos(x)/b**2 - (a + b)**2*atan(sqrt(b)*cos(x)/sqrt(a))/(sqrt(a)*b**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**3/(a + b*cos(x)**2),
        variable=x,
        num_steps=3,
        integral=cos(x)/b - (a + b)*atan(sqrt(b)*cos(x)/sqrt(a))/(sqrt(a)*b**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/(a + b*cos(x)**2),
        variable=x,
        num_steps=2,
        integral=-atan(sqrt(b)*cos(x)/sqrt(a))/(sqrt(a)*sqrt(b)),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)/(a + b*cos(x)**2),
        variable=x,
        num_steps=4,
        integral=-atanh(cos(x))/(a + b) - sqrt(b)*atan(sqrt(b)*cos(x)/sqrt(a))/(sqrt(a)*(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**3/(a + b*cos(x)**2),
        variable=x,
        num_steps=5,
        integral=-cot(x)*csc(x)/(2*a + 2*b) - (a + 3*b)*atanh(cos(x))/(2*(a + b)**2) - b**(sympy.S(3)/2)*atan(sqrt(b)*cos(x)/sqrt(a))/(sqrt(a)*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**5/(a + b*cos(x)**2),
        variable=x,
        num_steps=6,
        integral=-cot(x)*csc(x)**3/(4*a + 4*b) - (3*a + 7*b)*cot(x)*csc(x)/(8*(a + b)**2) - (3*a**2 + 10*a*b + 15*b**2)*atanh(cos(x))/(8*(a + b)**3) - b**(sympy.S(5)/2)*atan(sqrt(b)*cos(x)/sqrt(a))/(sqrt(a)*(a + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**6/(a + b*cos(x)**2),
        variable=x,
        num_steps=6,
        integral=sin(x)**3*cos(x)/(4*b) + (4*a + 7*b)*sin(x)*cos(x)/(8*b**2) - x*(8*a**2 + 20*a*b + 15*b**2)/(8*b**3) - (a + b)**(sympy.S(5)/2)*atan(sqrt(a + b)*cot(x)/sqrt(a))/(sqrt(a)*b**3),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**4/(a + b*cos(x)**2),
        variable=x,
        num_steps=5,
        integral=sin(x)*cos(x)/(2*b) - x*(2*a + 3*b)/(2*b**2) - (a + b)**(sympy.S(3)/2)*atan(sqrt(a + b)*cot(x)/sqrt(a))/(sqrt(a)*b**2),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)**2/(a + b*cos(x)**2),
        variable=x,
        num_steps=4,
        integral=-x/b - sqrt(a + b)*atan(sqrt(a + b)*cot(x)/sqrt(a))/(sqrt(a)*b),
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*cos(x)**2),
        variable=x,
        num_steps=2,
        integral=-atan(sqrt(a + b)*cot(x)/sqrt(a))/(sqrt(a)*sqrt(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**2/(a + b*cos(x)**2),
        variable=x,
        num_steps=3,
        integral=-cot(x)/(a + b) - b*atan(sqrt(a + b)*cot(x)/sqrt(a))/(sqrt(a)*(a + b)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**4/(a + b*cos(x)**2),
        variable=x,
        num_steps=4,
        integral=-cot(x)**3/(3*a + 3*b) - (a + 2*b)*cot(x)/(a + b)**2 - b**2*atan(sqrt(a + b)*cot(x)/sqrt(a))/(sqrt(a)*(a + b)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=csc(x)**6/(a + b*cos(x)**2),
        variable=x,
        num_steps=4,
        integral=-cot(x)**5/(5*a + 5*b) - (2*a + 3*b)*cot(x)**3/(3*(a + b)**2) - (a**2 + 3*a*b + 3*b**2)*cot(x)/(a + b)**3 - b**3*atan(sqrt(a + b)*cot(x)/sqrt(a))/(sqrt(a)*(a + b)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(x)/(4 - 3*cos(x)**3),
        variable=x,
        num_steps=7,
        integral=6**(sympy.S(2)/3)*log(-3**(sympy.S(1)/3)*cos(x) + 2**(sympy.S(2)/3))/36 - 6**(sympy.S(2)/3)*log(3**(sympy.S(2)/3)*cos(x)**2 + 2**(sympy.S(2)/3)*3**(sympy.S(1)/3)*cos(x) + 2*2**(sympy.S(1)/3))/72 - 2**(sympy.S(2)/3)*3**(sympy.S(1)/6)*atan(sqrt(3)*(6**(sympy.S(1)/3)*cos(x) + 1)/3)/12,
    ),
    RubiTestSuiteCase(
        integrand=1/(1 - cos(x)**2),
        variable=x,
        num_steps=3,
        integral=-cot(x),
    ),
    RubiTestSuiteCase(
        integrand=(1 - cos(x)**2)**(-2),
        variable=x,
        num_steps=3,
        integral=-cot(x)**3/3 - cot(x),
    ),
    RubiTestSuiteCase(
        integrand=(1 - cos(x)**2)**(-3),
        variable=x,
        num_steps=3,
        integral=-cot(x)**5/5 - 2*cot(x)**3/3 - cot(x),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**7/(a + b*cos(x)**2),
        variable=x,
        num_steps=4,
        integral=-a**3*atanh(sqrt(b)*sin(x)/sqrt(a + b))/(b**(sympy.S(7)/2)*sqrt(a + b)) + sin(x)**5/(5*b) + (a - 2*b)*sin(x)**3/(3*b**2) + (a**2 - a*b + b**2)*sin(x)/b**3,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**5/(a + b*cos(x)**2),
        variable=x,
        num_steps=4,
        integral=a**2*atanh(sqrt(b)*sin(x)/sqrt(a + b))/(b**(sympy.S(5)/2)*sqrt(a + b)) - sin(x)**3/(3*b) - (a - b)*sin(x)/b**2,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**3/(a + b*cos(x)**2),
        variable=x,
        num_steps=3,
        integral=-a*atanh(sqrt(b)*sin(x)/sqrt(a + b))/(b**(sympy.S(3)/2)*sqrt(a + b)) + sin(x)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)/(a + b*cos(x)**2),
        variable=x,
        num_steps=2,
        integral=atanh(sqrt(b)*sin(x)/sqrt(a + b))/(sqrt(b)*sqrt(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)/(a + b*cos(x)**2),
        variable=x,
        num_steps=4,
        integral=-sqrt(b)*atanh(sqrt(b)*sin(x)/sqrt(a + b))/(a*sqrt(a + b)) + atanh(sin(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=sec(x)**3/(a + b*cos(x)**2),
        variable=x,
        num_steps=5,
        integral=tan(x)*sec(x)/(2*a) + b**(sympy.S(3)/2)*atanh(sqrt(b)*sin(x)/sqrt(a + b))/(a**2*sqrt(a + b)) + (a - 2*b)*atanh(sin(x))/(2*a**2),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)**5/(a + b*cos(x)**2),
        variable=x,
        num_steps=6,
        integral=tan(x)*sec(x)**3/(4*a) + (3*a - 4*b)*tan(x)*sec(x)/(8*a**2) - b**(sympy.S(5)/2)*atanh(sqrt(b)*sin(x)/sqrt(a + b))/(a**3*sqrt(a + b)) + (3*a**2 - 4*a*b + 8*b**2)*atanh(sin(x))/(8*a**3),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**6/(a + b*cos(x)**2),
        variable=x,
        num_steps=6,
        integral=a**(sympy.S(5)/2)*atan(sqrt(a + b)*cot(x)/sqrt(a))/(b**3*sqrt(a + b)) + sin(x)*cos(x)**3/(4*b) - (4*a - 3*b)*sin(x)*cos(x)/(8*b**2) + x*(8*a**2 - 4*a*b + 3*b**2)/(8*b**3),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**4/(a + b*cos(x)**2),
        variable=x,
        num_steps=5,
        integral=-a**(sympy.S(3)/2)*atan(sqrt(a + b)*cot(x)/sqrt(a))/(b**2*sqrt(a + b)) + sin(x)*cos(x)/(2*b) - x*(2*a - b)/(2*b**2),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)**2/(a + b*cos(x)**2),
        variable=x,
        num_steps=3,
        integral=sqrt(a)*atan(sqrt(a + b)*cot(x)/sqrt(a))/(b*sqrt(a + b)) + x/b,
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*cos(x)**2),
        variable=x,
        num_steps=2,
        integral=-atan(sqrt(a + b)*cot(x)/sqrt(a))/(sqrt(a)*sqrt(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)**2/(a + b*cos(x)**2),
        variable=x,
        num_steps=3,
        integral=tan(x)/a + b*atan(sqrt(a + b)*cot(x)/sqrt(a))/(a**(sympy.S(3)/2)*sqrt(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)**4/(a + b*cos(x)**2),
        variable=x,
        num_steps=4,
        integral=tan(x)**3/(3*a) + (a - b)*tan(x)/a**2 - b**2*atan(sqrt(a + b)*cot(x)/sqrt(a))/(a**(sympy.S(5)/2)*sqrt(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=sec(x)**6/(a + b*cos(x)**2),
        variable=x,
        num_steps=4,
        integral=tan(x)**5/(5*a) + (2*a - b)*tan(x)**3/(3*a**2) + (a**2 - a*b + b**2)*tan(x)/a**3 + b**3*atan(sqrt(a + b)*cot(x)/sqrt(a))/(a**(sympy.S(7)/2)*sqrt(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cos(x)**2)**(-2),
        variable=x,
        num_steps=4,
        integral=-b*sin(x)*cos(x)/(2*a*(a + b)*(a + b*cos(x)**2)) - (2*a + b)*atan(sqrt(a + b)*cot(x)/sqrt(a))/(2*a**(sympy.S(3)/2)*(a + b)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cos(x)**2)**(-3),
        variable=x,
        num_steps=5,
        integral=-b*sin(x)*cos(x)/(4*a*(a + b)*(a + b*cos(x)**2)**2) - 3*b*(2*a + b)*sin(x)*cos(x)/(8*a**2*(a + b)**2*(a + b*cos(x)**2)) - (8*a**2 + 8*a*b + 3*b**2)*atan(sqrt(a + b)*cot(x)/sqrt(a))/(8*a**(sympy.S(5)/2)*(a + b)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=1/(cos(x)**2 + 1),
        variable=x,
        num_steps=2,
        integral=sqrt(2)*x/2 - sqrt(2)*atan(sin(x)*cos(x)/(cos(x)**2 + 1 + sqrt(2)))/2,
    ),
    RubiTestSuiteCase(
        integrand=(cos(x)**2 + 1)**(-2),
        variable=x,
        num_steps=4,
        integral=3*sqrt(2)*x/8 - 3*sqrt(2)*atan(sin(x)*cos(x)/(cos(x)**2 + 1 + sqrt(2)))/8 - sin(x)*cos(x)/(4*cos(x)**2 + 4),
    ),
    RubiTestSuiteCase(
        integrand=(cos(x)**2 + 1)**(-3),
        variable=x,
        num_steps=5,
        integral=19*sqrt(2)*x/64 - 19*sqrt(2)*atan(sin(x)*cos(x)/(cos(x)**2 + 1 + sqrt(2)))/64 - 9*sin(x)*cos(x)/(32*cos(x)**2 + 32) - sin(x)*cos(x)/(8*(cos(x)**2 + 1)**2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(1 - cos(x)**2),
        variable=x,
        num_steps=3,
        integral=-sqrt(sin(x)**2)*cot(x),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(cos(x)**2 - 1),
        variable=x,
        num_steps=3,
        integral=-sqrt(-sin(x)**2)*cot(x),
    ),
    RubiTestSuiteCase(
        integrand=(1 - cos(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=-(sin(x)**2)**(sympy.S(3)/2)*cot(x)/3 - 2*sqrt(sin(x)**2)*cot(x)/3,
    ),
    RubiTestSuiteCase(
        integrand=(cos(x)**2 - 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=-(-sin(x)**2)**(sympy.S(3)/2)*cot(x)/3 + 2*sqrt(-sin(x)**2)*cot(x)/3,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(1 - cos(x)**2),
        variable=x,
        num_steps=3,
        integral=-sin(x)*atanh(cos(x))/sqrt(sin(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(cos(x)**2 - 1),
        variable=x,
        num_steps=3,
        integral=-sin(x)*atanh(cos(x))/sqrt(-sin(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=(1 - cos(x)**2)**(sympy.S(-3)/2),
        variable=x,
        num_steps=4,
        integral=-sin(x)*atanh(cos(x))/(2*sqrt(sin(x)**2)) - cot(x)/(2*sqrt(sin(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(cos(x)**2 - 1)**(sympy.S(-3)/2),
        variable=x,
        num_steps=4,
        integral=sin(x)*atanh(cos(x))/(2*sqrt(-sin(x)**2)) + cot(x)/(2*sqrt(-sin(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(cos(x)**2 + 1),
        variable=x,
        num_steps=1,
        integral=elliptic_e(x + pi/2, -1),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-cos(x)**2 - 1),
        variable=x,
        num_steps=2,
        integral=sqrt(-cos(x)**2 - 1)*elliptic_e(x + pi/2, -1)/sqrt(cos(x)**2 + 1),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*cos(x)**2),
        variable=x,
        num_steps=2,
        integral=sqrt(a + b*cos(x)**2)*elliptic_e(x + pi/2, -b/a)/sqrt(1 + b*cos(x)**2/a),
    ),
    RubiTestSuiteCase(
        integrand=(cos(x)**2 + 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=sqrt(cos(x)**2 + 1)*sin(x)*cos(x)/3 + 2*elliptic_e(x + pi/2, -1) - 2*elliptic_f(x + pi/2, -1)/3,
    ),
    RubiTestSuiteCase(
        integrand=(-cos(x)**2 - 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=-sqrt(-cos(x)**2 - 1)*sin(x)*cos(x)/3 - 2*sqrt(-cos(x)**2 - 1)*elliptic_e(x + pi/2, -1)/sqrt(cos(x)**2 + 1) - 2*sqrt(cos(x)**2 + 1)*elliptic_f(x + pi/2, -1)/(3*sqrt(-cos(x)**2 - 1)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cos(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=-a*sqrt(1 + b*cos(x)**2/a)*(a + b)*elliptic_f(x + pi/2, -b/a)/(3*sqrt(a + b*cos(x)**2)) + b*sqrt(a + b*cos(x)**2)*sin(x)*cos(x)/3 + sqrt(a + b*cos(x)**2)*(4*a + 2*b)*elliptic_e(x + pi/2, -b/a)/(3*sqrt(1 + b*cos(x)**2/a)),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(cos(x)**2 + 1),
        variable=x,
        num_steps=1,
        integral=elliptic_f(x + pi/2, -1),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-cos(x)**2 - 1),
        variable=x,
        num_steps=2,
        integral=sqrt(cos(x)**2 + 1)*elliptic_f(x + pi/2, -1)/sqrt(-cos(x)**2 - 1),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a + b*cos(x)**2),
        variable=x,
        num_steps=2,
        integral=sqrt(1 + b*cos(x)**2/a)*elliptic_f(x + pi/2, -b/a)/sqrt(a + b*cos(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=(cos(x)**2 + 1)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=elliptic_e(x + pi/2, -1)/2 - sin(x)*cos(x)/(2*sqrt(cos(x)**2 + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(-cos(x)**2 - 1)**(sympy.S(-3)/2),
        variable=x,
        num_steps=4,
        integral=sqrt(-cos(x)**2 - 1)*elliptic_e(x + pi/2, -1)/(2*sqrt(cos(x)**2 + 1)) + sin(x)*cos(x)/(2*sqrt(-cos(x)**2 - 1)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*cos(x)**2)**(sympy.S(-3)/2),
        variable=x,
        num_steps=4,
        integral=-b*sin(x)*cos(x)/(a*(a + b)*sqrt(a + b*cos(x)**2)) + sqrt(a + b*cos(x)**2)*elliptic_e(x + pi/2, -b/a)/(a*sqrt(1 + b*cos(x)**2/a)*(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=cos(x)/sqrt(cos(x)**2 + 1),
        variable=x,
        num_steps=2,
        integral=asin(sqrt(2)*sin(x)/2),
    ),
    RubiTestSuiteCase(
        integrand=cos(3*x + 5)/sqrt(cos(3*x + 5)**2 + 3),
        variable=x,
        num_steps=2,
        integral=asin(sin(3*x + 5)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=cos(x)/sqrt(4 - cos(x)**2),
        variable=x,
        num_steps=2,
        integral=asinh(sqrt(3)*sin(x)/3),
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*cos(x)**4),
        variable=x,
        num_steps=10,
        integral=-sqrt(2)*(sqrt(a) - sqrt(a + b))*log(-sqrt(2)*a**(sympy.S(1)/4)*sqrt(-sqrt(a)*sqrt(a + b) + a + b)*cot(x) + sqrt(a)*(a + b)**(sympy.S(1)/4) + (a + b)**(sympy.S(3)/4)*cot(x)**2)/(8*a**(sympy.S(3)/4)*(a + b)**(sympy.S(1)/4)*sqrt(-sqrt(a)*sqrt(a + b) + a + b)) + sqrt(2)*(sqrt(a) - sqrt(a + b))*log(sqrt(2)*a**(sympy.S(1)/4)*sqrt(-sqrt(a)*sqrt(a + b) + a + b)*cot(x) + sqrt(a)*(a + b)**(sympy.S(1)/4) + (a + b)**(sympy.S(3)/4)*cot(x)**2)/(8*a**(sympy.S(3)/4)*(a + b)**(sympy.S(1)/4)*sqrt(-sqrt(a)*sqrt(a + b) + a + b)) + sqrt(2)*(sqrt(a) + sqrt(a + b))*atan((a**(sympy.S(1)/4)*sqrt(-sqrt(a)*sqrt(a + b) + a + b) - sqrt(2)*(a + b)**(sympy.S(3)/4)*cot(x))/(a**(sympy.S(1)/4)*sqrt(sqrt(a)*sqrt(a + b) + a + b)))/(4*a**(sympy.S(3)/4)*(a + b)**(sympy.S(1)/4)*sqrt(sqrt(a)*sqrt(a + b) + a + b)) - sqrt(2)*(sqrt(a) + sqrt(a + b))*atan((a**(sympy.S(1)/4)*sqrt(-sqrt(a)*sqrt(a + b) + a + b) + sqrt(2)*(a + b)**(sympy.S(3)/4)*cot(x))/(a**(sympy.S(1)/4)*sqrt(sqrt(a)*sqrt(a + b) + a + b)))/(4*a**(sympy.S(3)/4)*(a + b)**(sympy.S(1)/4)*sqrt(sqrt(a)*sqrt(a + b) + a + b)),
    ),
    RubiTestSuiteCase(
        integrand=1/(a - b*cos(x)**4),
        variable=x,
        num_steps=4,
        integral=-atan(sqrt(sqrt(a) + sqrt(b))*cot(x)/a**(sympy.S(1)/4))/(2*a**(sympy.S(3)/4)*sqrt(sqrt(a) + sqrt(b))) - atan(sqrt(sqrt(a) - sqrt(b))*cot(x)/a**(sympy.S(1)/4))/(2*a**(sympy.S(3)/4)*sqrt(sqrt(a) - sqrt(b))),
    ),
    RubiTestSuiteCase(
        integrand=1/(cos(x)**4 + 1),
        variable=x,
        num_steps=10,
        integral=x/(2*sqrt(-1 + sqrt(2))) - sqrt(-1 + sqrt(2))*log(sqrt(2)*cot(x)**2 + sqrt(-2 + 2*sqrt(2))*cot(x) + 1)/8 + sqrt(-1 + sqrt(2))*log(2*cot(x)**2 - 2*sqrt(-1 + sqrt(2))*cot(x) + sqrt(2))/8 + atan((sqrt(-1 + sqrt(2))*(1 - 2*sin(x)**2) + (-2 + sqrt(2))*sin(x)*cos(x))/((-2 + sqrt(2))*sin(x)**2 + 2*sqrt(-1 + sqrt(2))*sin(x)*cos(x) + sqrt(1 + sqrt(2)) + 2))/(4*sqrt(-1 + sqrt(2))) + atan((sqrt(-1 + sqrt(2))*(2*sin(x)**2 - 1) + (-2 + sqrt(2))*sin(x)*cos(x))/((-2 + sqrt(2))*sin(x)**2 - 2*sqrt(-1 + sqrt(2))*sin(x)*cos(x) + sqrt(1 + sqrt(2)) + 2))/(4*sqrt(-1 + sqrt(2))),
    ),
    RubiTestSuiteCase(
        integrand=1/(1 - cos(x)**4),
        variable=x,
        num_steps=3,
        integral=sqrt(2)*x/4 - cot(x)/2 - sqrt(2)*atan(sin(x)*cos(x)/(cos(x)**2 + 1 + sqrt(2)))/4,
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*cos(x)**5),
        variable=x,
        num_steps=12,
        integral=2*atan(sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(4)/5)*b**(sympy.S(1)/5))*tan(x/2)/sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(4)/5)*b**(sympy.S(1)/5)))/(5*a**(sympy.S(4)/5)*sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(4)/5)*b**(sympy.S(1)/5))*sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(4)/5)*b**(sympy.S(1)/5))) + 2*atan(sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(3)/5)*b**(sympy.S(1)/5))*tan(x/2)/sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(3)/5)*b**(sympy.S(1)/5)))/(5*a**(sympy.S(4)/5)*sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(3)/5)*b**(sympy.S(1)/5))*sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(3)/5)*b**(sympy.S(1)/5))) + 2*atan(sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(2)/5)*b**(sympy.S(1)/5))*tan(x/2)/sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(2)/5)*b**(sympy.S(1)/5)))/(5*a**(sympy.S(4)/5)*sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(2)/5)*b**(sympy.S(1)/5))*sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(2)/5)*b**(sympy.S(1)/5))) + 2*atan(sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(1)/5)*b**(sympy.S(1)/5))*tan(x/2)/sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(1)/5)*b**(sympy.S(1)/5)))/(5*a**(sympy.S(4)/5)*sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(1)/5)*b**(sympy.S(1)/5))*sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(1)/5)*b**(sympy.S(1)/5))) + 2*atan(sqrt(a**(sympy.S(1)/5) - b**(sympy.S(1)/5))*tan(x/2)/sqrt(a**(sympy.S(1)/5) + b**(sympy.S(1)/5)))/(5*a**(sympy.S(4)/5)*sqrt(a**(sympy.S(1)/5) - b**(sympy.S(1)/5))*sqrt(a**(sympy.S(1)/5) + b**(sympy.S(1)/5))),
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*cos(x)**6),
        variable=x,
        num_steps=7,
        integral=-atan(sqrt(a**(sympy.S(1)/3) + (-1)**(sympy.S(2)/3)*b**(sympy.S(1)/3))*cot(x)/a**(sympy.S(1)/6))/(3*a**(sympy.S(5)/6)*sqrt(a**(sympy.S(1)/3) + (-1)**(sympy.S(2)/3)*b**(sympy.S(1)/3))) - atan(sqrt(a**(sympy.S(1)/3) - (-1)**(sympy.S(1)/3)*b**(sympy.S(1)/3))*cot(x)/a**(sympy.S(1)/6))/(3*a**(sympy.S(5)/6)*sqrt(a**(sympy.S(1)/3) - (-1)**(sympy.S(1)/3)*b**(sympy.S(1)/3))) - atan(sqrt(a**(sympy.S(1)/3) + b**(sympy.S(1)/3))*cot(x)/a**(sympy.S(1)/6))/(3*a**(sympy.S(5)/6)*sqrt(a**(sympy.S(1)/3) + b**(sympy.S(1)/3))),
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*cos(x)**8),
        variable=x,
        num_steps=9,
        integral=atan(sqrt(I*b**(sympy.S(1)/4) + (-a)**(sympy.S(1)/4))*cot(x)/(-a)**(sympy.S(1)/8))/(4*(-a)**(sympy.S(7)/8)*sqrt(I*b**(sympy.S(1)/4) + (-a)**(sympy.S(1)/4))) + atan(sqrt(-I*b**(sympy.S(1)/4) + (-a)**(sympy.S(1)/4))*cot(x)/(-a)**(sympy.S(1)/8))/(4*(-a)**(sympy.S(7)/8)*sqrt(-I*b**(sympy.S(1)/4) + (-a)**(sympy.S(1)/4))) + atan(sqrt(b**(sympy.S(1)/4) + (-a)**(sympy.S(1)/4))*cot(x)/(-a)**(sympy.S(1)/8))/(4*(-a)**(sympy.S(7)/8)*sqrt(b**(sympy.S(1)/4) + (-a)**(sympy.S(1)/4))) + atan(sqrt(-b**(sympy.S(1)/4) + (-a)**(sympy.S(1)/4))*cot(x)/(-a)**(sympy.S(1)/8))/(4*(-a)**(sympy.S(7)/8)*sqrt(-b**(sympy.S(1)/4) + (-a)**(sympy.S(1)/4))),
    ),
    RubiTestSuiteCase(
        integrand=1/(a - b*cos(x)**5),
        variable=x,
        num_steps=12,
        integral=2*atan(sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(4)/5)*b**(sympy.S(1)/5))*tan(x/2)/sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(4)/5)*b**(sympy.S(1)/5)))/(5*a**(sympy.S(4)/5)*sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(4)/5)*b**(sympy.S(1)/5))*sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(4)/5)*b**(sympy.S(1)/5))) + 2*atan(sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(3)/5)*b**(sympy.S(1)/5))*tan(x/2)/sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(3)/5)*b**(sympy.S(1)/5)))/(5*a**(sympy.S(4)/5)*sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(3)/5)*b**(sympy.S(1)/5))*sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(3)/5)*b**(sympy.S(1)/5))) + 2*atan(sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(2)/5)*b**(sympy.S(1)/5))*tan(x/2)/sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(2)/5)*b**(sympy.S(1)/5)))/(5*a**(sympy.S(4)/5)*sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(2)/5)*b**(sympy.S(1)/5))*sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(2)/5)*b**(sympy.S(1)/5))) + 2*atan(sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(1)/5)*b**(sympy.S(1)/5))*tan(x/2)/sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(1)/5)*b**(sympy.S(1)/5)))/(5*a**(sympy.S(4)/5)*sqrt(a**(sympy.S(1)/5) - (-1)**(sympy.S(1)/5)*b**(sympy.S(1)/5))*sqrt(a**(sympy.S(1)/5) + (-1)**(sympy.S(1)/5)*b**(sympy.S(1)/5))) + 2*atan(sqrt(a**(sympy.S(1)/5) + b**(sympy.S(1)/5))*tan(x/2)/sqrt(a**(sympy.S(1)/5) - b**(sympy.S(1)/5)))/(5*a**(sympy.S(4)/5)*sqrt(a**(sympy.S(1)/5) - b**(sympy.S(1)/5))*sqrt(a**(sympy.S(1)/5) + b**(sympy.S(1)/5))),
    ),
    RubiTestSuiteCase(
        integrand=1/(a - b*cos(x)**6),
        variable=x,
        num_steps=7,
        integral=-atan(sqrt(a**(sympy.S(1)/3) - (-1)**(sympy.S(2)/3)*b**(sympy.S(1)/3))*cot(x)/a**(sympy.S(1)/6))/(3*a**(sympy.S(5)/6)*sqrt(a**(sympy.S(1)/3) - (-1)**(sympy.S(2)/3)*b**(sympy.S(1)/3))) - atan(sqrt(a**(sympy.S(1)/3) + (-1)**(sympy.S(1)/3)*b**(sympy.S(1)/3))*cot(x)/a**(sympy.S(1)/6))/(3*a**(sympy.S(5)/6)*sqrt(a**(sympy.S(1)/3) + (-1)**(sympy.S(1)/3)*b**(sympy.S(1)/3))) - atan(sqrt(a**(sympy.S(1)/3) - b**(sympy.S(1)/3))*cot(x)/a**(sympy.S(1)/6))/(3*a**(sympy.S(5)/6)*sqrt(a**(sympy.S(1)/3) - b**(sympy.S(1)/3))),
    ),
    RubiTestSuiteCase(
        integrand=1/(a - b*cos(x)**8),
        variable=x,
        num_steps=9,
        integral=-atan(sqrt(a**(sympy.S(1)/4) + I*b**(sympy.S(1)/4))*cot(x)/a**(sympy.S(1)/8))/(4*a**(sympy.S(7)/8)*sqrt(a**(sympy.S(1)/4) + I*b**(sympy.S(1)/4))) - atan(sqrt(a**(sympy.S(1)/4) - I*b**(sympy.S(1)/4))*cot(x)/a**(sympy.S(1)/8))/(4*a**(sympy.S(7)/8)*sqrt(a**(sympy.S(1)/4) - I*b**(sympy.S(1)/4))) - atan(sqrt(a**(sympy.S(1)/4) + b**(sympy.S(1)/4))*cot(x)/a**(sympy.S(1)/8))/(4*a**(sympy.S(7)/8)*sqrt(a**(sympy.S(1)/4) + b**(sympy.S(1)/4))) - atan(sqrt(a**(sympy.S(1)/4) - b**(sympy.S(1)/4))*cot(x)/a**(sympy.S(1)/8))/(4*a**(sympy.S(7)/8)*sqrt(a**(sympy.S(1)/4) - b**(sympy.S(1)/4))),
    ),
    RubiTestSuiteCase(
        integrand=1/(cos(x)**5 + 1),
        variable=x,
        num_steps=11,
        integral=2*atan(sqrt((1 - (-1)**(sympy.S(2)/5))/(1 + (-1)**(sympy.S(2)/5)))*tan(x/2))/(5*sqrt(1 - (-1)**(sympy.S(4)/5))) + 2*atan(sqrt((1 - (-1)**(sympy.S(4)/5))/(1 + (-1)**(sympy.S(4)/5)))*tan(x/2))/(5*sqrt(1 + (-1)**(sympy.S(3)/5))) - 2*atanh(tan(x/2)/sqrt(-(1 - (-1)**(sympy.S(1)/5))/(1 + (-1)**(sympy.S(1)/5))))/(5*sqrt(-1 + (-1)**(sympy.S(2)/5))) - 2*sqrt(-(1 + (-1)**(sympy.S(3)/5))/(1 - (-1)**(sympy.S(3)/5)))*atanh(sqrt(-(1 + (-1)**(sympy.S(3)/5))/(1 - (-1)**(sympy.S(3)/5)))*tan(x/2))/(5 + 5*(-1)**(sympy.S(3)/5)) + sin(x)/(5*cos(x) + 5),
    ),
    RubiTestSuiteCase(
        integrand=1/(cos(x)**8 + 1),
        variable=x,
        num_steps=9,
        integral=-atan(sqrt(1 - (-1)**(sympy.S(1)/4))*cot(x))/(4*sqrt(1 - (-1)**(sympy.S(1)/4))) - atan(sqrt(1 + (-1)**(sympy.S(1)/4))*cot(x))/(4*sqrt(1 + (-1)**(sympy.S(1)/4))) - atan(sqrt(1 - (-1)**(sympy.S(3)/4))*cot(x))/(4*sqrt(1 - (-1)**(sympy.S(3)/4))) - atan(sqrt(1 + (-1)**(sympy.S(3)/4))*cot(x))/(4*sqrt(1 + (-1)**(sympy.S(3)/4))),
    ),
    RubiTestSuiteCase(
        integrand=1/(1 - cos(x)**5),
        variable=x,
        num_steps=11,
        integral=2*atan(sqrt((1 - (-1)**(sympy.S(1)/5))/(1 + (-1)**(sympy.S(1)/5)))*tan(x/2))/(5*sqrt(1 - (-1)**(sympy.S(2)/5))) + 2*atan(sqrt((1 - (-1)**(sympy.S(3)/5))/(1 + (-1)**(sympy.S(3)/5)))*tan(x/2))/(5*sqrt(1 + (-1)**(sympy.S(1)/5))) - 2*atanh(tan(x/2)/sqrt(-(1 - (-1)**(sympy.S(2)/5))/(1 + (-1)**(sympy.S(2)/5))))/(5*sqrt(-1 + (-1)**(sympy.S(4)/5))) + 2*atanh(sqrt(-(1 + (-1)**(sympy.S(4)/5))/(1 - (-1)**(sympy.S(4)/5)))*tan(x/2))/(5*sqrt(-1 - (-1)**(sympy.S(3)/5))) - sin(x)/(5 - 5*cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=1/(1 - cos(x)**6),
        variable=x,
        num_steps=8,
        integral=-cot(x)/3 - atan(sqrt(1 + (-1)**(sympy.S(1)/3))*cot(x))/(3*sqrt(1 + (-1)**(sympy.S(1)/3))) - atan(sqrt(1 - (-1)**(sympy.S(2)/3))*cot(x))/(3*sqrt(1 - (-1)**(sympy.S(2)/3))),
    ),
    RubiTestSuiteCase(
        integrand=1/(1 - cos(x)**8),
        variable=x,
        num_steps=10,
        integral=sqrt(2)*x/8 - cot(x)/4 - atan(sqrt(1 - I)*cot(x))/(4*sqrt(1 - I)) - atan(sqrt(1 + I)*cot(x))/(4*sqrt(1 + I)) - sqrt(2)*atan(sin(x)*cos(x)/(cos(x)**2 + 1 + sqrt(2)))/8,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)/(cos(x)**2 + 1),
        variable=x,
        num_steps=4,
        integral=log(cos(x)**2 + 1)/2 - log(cos(x)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*cos(x)**2)*tan(x),
        variable=x,
        num_steps=4,
        integral=sqrt(a)*atanh(sqrt(a + b*cos(x)**2)/sqrt(a)) - sqrt(a + b*cos(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(1 - cos(x)**2)*tan(x),
        variable=x,
        num_steps=5,
        integral=-sqrt(sin(x)**2) + atanh(sqrt(sin(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)/sqrt(a + b*cos(x)**2),
        variable=x,
        num_steps=3,
        integral=atanh(sqrt(a + b*cos(x)**2)/sqrt(a))/sqrt(a),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)/sqrt(cos(x)**2 + 1),
        variable=x,
        num_steps=3,
        integral=atanh(sqrt(cos(x)**2 + 1)),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)/sqrt(1 - cos(x)**2),
        variable=x,
        num_steps=4,
        integral=atanh(sqrt(sin(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=tan(x)**3/(a + b*cos(x)**3),
        variable=x,
        num_steps=11,
        integral=-log(a + b*cos(x)**3)/(3*a) + log(cos(x))/a + sec(x)**2/(2*a) + b**(sympy.S(2)/3)*log(a**(sympy.S(1)/3) + b**(sympy.S(1)/3)*cos(x))/(3*a**(sympy.S(5)/3)) - b**(sympy.S(2)/3)*log(a**(sympy.S(2)/3) - a**(sympy.S(1)/3)*b**(sympy.S(1)/3)*cos(x) + b**(sympy.S(2)/3)*cos(x)**2)/(6*a**(sympy.S(5)/3)) - sqrt(3)*b**(sympy.S(2)/3)*atan(sqrt(3)*(a**(sympy.S(1)/3) - 2*b**(sympy.S(1)/3)*cos(x))/(3*a**(sympy.S(1)/3)))/(3*a**(sympy.S(5)/3)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*cos(x)**3)*tan(x),
        variable=x,
        num_steps=5,
        integral=2*sqrt(a)*atanh(sqrt(a + b*cos(x)**3)/sqrt(a))/3 - 2*sqrt(a + b*cos(x)**3)/3,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)/sqrt(a + b*cos(x)**3),
        variable=x,
        num_steps=4,
        integral=2*atanh(sqrt(a + b*cos(x)**3)/sqrt(a))/(3*sqrt(a)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*cos(x)**4)*tan(x),
        variable=x,
        num_steps=5,
        integral=sqrt(a)*atanh(sqrt(a + b*cos(x)**4)/sqrt(a))/2 - sqrt(a + b*cos(x)**4)/2,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)/sqrt(a + b*cos(x)**4),
        variable=x,
        num_steps=4,
        integral=atanh(sqrt(a + b*cos(x)**4)/sqrt(a))/(2*sqrt(a)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*cos(x)**n)*tan(x),
        variable=x,
        num_steps=5,
        integral=2*sqrt(a)*atanh(sqrt(a + b*cos(x)**n)/sqrt(a))/n - 2*sqrt(a + b*cos(x)**n)/n,
    ),
    RubiTestSuiteCase(
        integrand=tan(x)/sqrt(a + b*cos(x)**n),
        variable=x,
        num_steps=4,
        integral=2*atanh(sqrt(a + b*cos(x)**n)/sqrt(a))/(sqrt(a)*n),
    ),
]
