# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 4 Trig functions/4.2 Cosine/4.2.12 (e x)^m (a+b cos(c+d x^n))^p.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '4 Trig functions/4.2 Cosine/4.2.12 (e x)^m (a+b cos(c+d x^n))^p.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, c, d, e, m, n, p = symbols('a b c d e m n p')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=x**3*cos(a + b*x**2),
        variable=x,
        num_steps=3,
        integral=x**2*sin(a + b*x**2)/(2*b) + cos(a + b*x**2)/(2*b**2),
    ),
    RubiTestSuiteCase(
        integrand=x**2*cos(a + b*x**2),
        variable=x,
        num_steps=4,
        integral=((Integer(-1) * ((sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.cos(Symbol('a')) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * x))) * ((Integer(2) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * x)) * sympy.sin(Symbol('a'))) * ((Integer(2) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + ((x * sympy.sin((Symbol('a') + (Symbol('b') * (x)**(Integer(2)))))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x*cos(a + b*x**2),
        variable=x,
        num_steps=2,
        integral=sin(a + b*x**2)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2),
        variable=x,
        num_steps=3,
        integral=(((sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.cos(Symbol('a')) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * x))) * (sympy.sqrt(Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * x)) * sympy.sin(Symbol('a'))) * (sympy.sqrt(Symbol('b')))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)/x,
        variable=x,
        num_steps=3,
        integral=(((Integer(2))**(Integer(-1)) * sympy.cos(Symbol('a')) * sympy.Function('CosIntegral')((Symbol('b') * (x)**(Integer(2))))) + (Integer(-1) * ((Integer(2))**(Integer(-1)) * sympy.sin(Symbol('a')) * sympy.Function('SinIntegral')((Symbol('b') * (x)**(Integer(2))))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)/x**2,
        variable=x,
        num_steps=4,
        integral=((Integer(-1) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**(Integer(2))))) * (x)**(Integer(-1)))) + (Integer(-1) * (sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * sympy.pi)) * sympy.cos(Symbol('a')) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * x)))) + (Integer(-1) * (sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * sympy.pi)) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * x)) * sympy.sin(Symbol('a'))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)/x**3,
        variable=x,
        num_steps=5,
        integral=((Integer(-1) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**(Integer(2))))) * ((Integer(2) * (x)**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * ((Integer(2))**(Integer(-1)) * Symbol('b') * sympy.Function('CosIntegral')((Symbol('b') * (x)**(Integer(2)))) * sympy.sin(Symbol('a')))) + (Integer(-1) * ((Integer(2))**(Integer(-1)) * Symbol('b') * sympy.cos(Symbol('a')) * sympy.Function('SinIntegral')((Symbol('b') * (x)**(Integer(2))))))),
    ),
    RubiTestSuiteCase(
        integrand=x**3*cos(a + b*x**2)**2,
        variable=x,
        num_steps=3,
        integral=x**4/8 + x**2*sin(a + b*x**2)*cos(a + b*x**2)/(4*b) + cos(a + b*x**2)**2/(8*b**2),
    ),
    RubiTestSuiteCase(
        integrand=x**2*cos(a + b*x**2)**2,
        variable=x,
        num_steps=6,
        integral=(((x)**(Integer(3)) * (Integer(6))**(Integer(-1))) + (Integer(-1) * ((sympy.sqrt(sympy.pi) * sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('FresnelS')(((Integer(2) * sympy.sqrt(Symbol('b')) * x) * (sympy.sqrt(sympy.pi))**(Integer(-1))))) * ((Integer(16) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((sympy.sqrt(sympy.pi) * sympy.Function('FresnelC')(((Integer(2) * sympy.sqrt(Symbol('b')) * x) * (sympy.sqrt(sympy.pi))**(Integer(-1)))) * sympy.sin((Integer(2) * Symbol('a')))) * ((Integer(16) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + ((x * sympy.sin(((Integer(2) * Symbol('a')) + (Integer(2) * Symbol('b') * (x)**(Integer(2)))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x*cos(a + b*x**2)**2,
        variable=x,
        num_steps=3,
        integral=x**2/4 + sin(a + b*x**2)*cos(a + b*x**2)/(4*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)**2,
        variable=x,
        num_steps=5,
        integral=((x * (Integer(2))**(Integer(-1))) + ((sympy.sqrt(sympy.pi) * sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('FresnelC')(((Integer(2) * sympy.sqrt(Symbol('b')) * x) * (sympy.sqrt(sympy.pi))**(Integer(-1))))) * ((Integer(4) * sympy.sqrt(Symbol('b'))))**(Integer(-1))) + (Integer(-1) * ((sympy.sqrt(sympy.pi) * sympy.Function('FresnelS')(((Integer(2) * sympy.sqrt(Symbol('b')) * x) * (sympy.sqrt(sympy.pi))**(Integer(-1)))) * sympy.sin((Integer(2) * Symbol('a')))) * ((Integer(4) * sympy.sqrt(Symbol('b'))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)**2/x,
        variable=x,
        num_steps=5,
        integral=(((Integer(4))**(Integer(-1)) * sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('CosIntegral')((Integer(2) * Symbol('b') * (x)**(Integer(2))))) + (sympy.log(x) * (Integer(2))**(Integer(-1))) + (Integer(-1) * ((Integer(4))**(Integer(-1)) * sympy.sin((Integer(2) * Symbol('a'))) * sympy.Function('SinIntegral')((Integer(2) * Symbol('b') * (x)**(Integer(2))))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)**2/x**2,
        variable=x,
        num_steps=6,
        integral=((Integer(-1) * ((sympy.cos((Symbol('a') + (Symbol('b') * (x)**(Integer(2))))))**(Integer(2)) * (x)**(Integer(-1)))) + (Integer(-1) * (sympy.sqrt(Symbol('b')) * sympy.sqrt(sympy.pi) * sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('FresnelS')(((Integer(2) * sympy.sqrt(Symbol('b')) * x) * (sympy.sqrt(sympy.pi))**(Integer(-1)))))) + (Integer(-1) * (sympy.sqrt(Symbol('b')) * sympy.sqrt(sympy.pi) * sympy.Function('FresnelC')(((Integer(2) * sympy.sqrt(Symbol('b')) * x) * (sympy.sqrt(sympy.pi))**(Integer(-1)))) * sympy.sin((Integer(2) * Symbol('a')))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)**2/x**3,
        variable=x,
        num_steps=7,
        integral=((Integer(-1) * ((Integer(4) * (x)**(Integer(2))))**(Integer(-1))) + (Integer(-1) * (sympy.cos((Integer(2) * (Symbol('a') + (Symbol('b') * (x)**(Integer(2)))))) * ((Integer(4) * (x)**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * ((Integer(2))**(Integer(-1)) * Symbol('b') * sympy.Function('CosIntegral')((Integer(2) * Symbol('b') * (x)**(Integer(2)))) * sympy.sin((Integer(2) * Symbol('a'))))) + (Integer(-1) * ((Integer(2))**(Integer(-1)) * Symbol('b') * sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('SinIntegral')((Integer(2) * Symbol('b') * (x)**(Integer(2))))))),
    ),
    RubiTestSuiteCase(
        integrand=x**3*cos(a + b*x**2)**3,
        variable=x,
        num_steps=4,
        integral=x**2*sin(a + b*x**2)*cos(a + b*x**2)**2/(6*b) + x**2*sin(a + b*x**2)/(3*b) + cos(a + b*x**2)**3/(18*b**2) + cos(a + b*x**2)/(3*b**2),
    ),
    RubiTestSuiteCase(
        integrand=x**2*cos(a + b*x**2)**3,
        variable=x,
        num_steps=10,
        integral=((Integer(-1) * ((Integer(3) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.cos(Symbol('a')) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * x))) * ((Integer(8) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((sympy.sqrt((sympy.pi * (Integer(6))**(Integer(-1)))) * sympy.cos((Integer(3) * Symbol('a'))) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(6) * (sympy.pi)**(Integer(-1)))) * x))) * ((Integer(24) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * x)) * sympy.sin(Symbol('a'))) * ((Integer(8) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((sympy.sqrt((sympy.pi * (Integer(6))**(Integer(-1)))) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(6) * (sympy.pi)**(Integer(-1)))) * x)) * sympy.sin((Integer(3) * Symbol('a')))) * ((Integer(24) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + ((Integer(3) * x * sympy.sin((Symbol('a') + (Symbol('b') * (x)**(Integer(2)))))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + ((x * sympy.sin(((Integer(3) * Symbol('a')) + (Integer(3) * Symbol('b') * (x)**(Integer(2)))))) * ((Integer(24) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x*cos(a + b*x**2)**3,
        variable=x,
        num_steps=3,
        integral=-sin(a + b*x**2)**3/(6*b) + sin(a + b*x**2)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)**3,
        variable=x,
        num_steps=8,
        integral=(((Integer(3) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.cos(Symbol('a')) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * x))) * ((Integer(4) * sympy.sqrt(Symbol('b'))))**(Integer(-1))) + ((sympy.sqrt((sympy.pi * (Integer(6))**(Integer(-1)))) * sympy.cos((Integer(3) * Symbol('a'))) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(6) * (sympy.pi)**(Integer(-1)))) * x))) * ((Integer(4) * sympy.sqrt(Symbol('b'))))**(Integer(-1))) + (Integer(-1) * ((Integer(3) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * x)) * sympy.sin(Symbol('a'))) * ((Integer(4) * sympy.sqrt(Symbol('b'))))**(Integer(-1)))) + (Integer(-1) * ((sympy.sqrt((sympy.pi * (Integer(6))**(Integer(-1)))) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(6) * (sympy.pi)**(Integer(-1)))) * x)) * sympy.sin((Integer(3) * Symbol('a')))) * ((Integer(4) * sympy.sqrt(Symbol('b'))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)**3/x,
        variable=x,
        num_steps=8,
        integral=(((Integer(3) * (Integer(8))**(Integer(-1))) * sympy.cos(Symbol('a')) * sympy.Function('CosIntegral')((Symbol('b') * (x)**(Integer(2))))) + ((Integer(8))**(Integer(-1)) * sympy.cos((Integer(3) * Symbol('a'))) * sympy.Function('CosIntegral')((Integer(3) * Symbol('b') * (x)**(Integer(2))))) + (Integer(-1) * ((Integer(3) * (Integer(8))**(Integer(-1))) * sympy.sin(Symbol('a')) * sympy.Function('SinIntegral')((Symbol('b') * (x)**(Integer(2)))))) + (Integer(-1) * ((Integer(8))**(Integer(-1)) * sympy.sin((Integer(3) * Symbol('a'))) * sympy.Function('SinIntegral')((Integer(3) * Symbol('b') * (x)**(Integer(2))))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)**3/x**2,
        variable=x,
        num_steps=9,
        integral=((Integer(-1) * ((sympy.cos((Symbol('a') + (Symbol('b') * (x)**(Integer(2))))))**(Integer(3)) * (x)**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * (Integer(2))**(Integer(-1))) * sympy.sqrt(Symbol('b')) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.cos(Symbol('a')) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * x)))) + (Integer(-1) * ((Integer(2))**(Integer(-1)) * sympy.sqrt(Symbol('b')) * sympy.sqrt(((Integer(3) * sympy.pi) * (Integer(2))**(Integer(-1)))) * sympy.cos((Integer(3) * Symbol('a'))) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(6) * (sympy.pi)**(Integer(-1)))) * x)))) + (Integer(-1) * ((Integer(3) * (Integer(2))**(Integer(-1))) * sympy.sqrt(Symbol('b')) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * x)) * sympy.sin(Symbol('a')))) + (Integer(-1) * ((Integer(2))**(Integer(-1)) * sympy.sqrt(Symbol('b')) * sympy.sqrt(((Integer(3) * sympy.pi) * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(6) * (sympy.pi)**(Integer(-1)))) * x)) * sympy.sin((Integer(3) * Symbol('a')))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)**3/x**3,
        variable=x,
        num_steps=12,
        integral=((Integer(-1) * ((Integer(3) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**(Integer(2)))))) * ((Integer(8) * (x)**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * (sympy.cos((Integer(3) * (Symbol('a') + (Symbol('b') * (x)**(Integer(2)))))) * ((Integer(8) * (x)**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * (Integer(8))**(Integer(-1))) * Symbol('b') * sympy.Function('CosIntegral')((Symbol('b') * (x)**(Integer(2)))) * sympy.sin(Symbol('a')))) + (Integer(-1) * ((Integer(3) * (Integer(8))**(Integer(-1))) * Symbol('b') * sympy.Function('CosIntegral')((Integer(3) * Symbol('b') * (x)**(Integer(2)))) * sympy.sin((Integer(3) * Symbol('a'))))) + (Integer(-1) * ((Integer(3) * (Integer(8))**(Integer(-1))) * Symbol('b') * sympy.cos(Symbol('a')) * sympy.Function('SinIntegral')((Symbol('b') * (x)**(Integer(2)))))) + (Integer(-1) * ((Integer(3) * (Integer(8))**(Integer(-1))) * Symbol('b') * sympy.cos((Integer(3) * Symbol('a'))) * sympy.Function('SinIntegral')((Integer(3) * Symbol('b') * (x)**(Integer(2))))))),
    ),
    RubiTestSuiteCase(
        integrand=x*cos(a + b*x**2)**7,
        variable=x,
        num_steps=3,
        integral=-sin(a + b*x**2)**7/(14*b) + 3*sin(a + b*x**2)**5/(10*b) - sin(a + b*x**2)**3/(2*b) + sin(a + b*x**2)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=x**(sympy.S(5)/2)*cos(a + b*x**2),
        variable=x,
        num_steps=4,
        integral=((Integer(-1) * ((Integer(3) * sympy.I * (sympy.E)**((sympy.I * Symbol('a'))) * (x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(3) * (Integer(4))**(Integer(-1))), ((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))) * ((Integer(16) * Symbol('b') * (((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))**((Integer(3) * (Integer(4))**(Integer(-1))))))**(Integer(-1)))) + ((Integer(3) * sympy.I * (x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(3) * (Integer(4))**(Integer(-1))), (sympy.I * Symbol('b') * (x)**(Integer(2))))) * (((sympy.E)**((sympy.I * Symbol('a'))) * (Integer(16) * Symbol('b') * ((sympy.I * Symbol('b') * (x)**(Integer(2))))**((Integer(3) * (Integer(4))**(Integer(-1)))))))**(Integer(-1))) + (((x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**(Integer(2)))))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x**(sympy.S(3)/2)*cos(a + b*x**2),
        variable=x,
        num_steps=4,
        integral=((Integer(-1) * ((sympy.I * (sympy.E)**((sympy.I * Symbol('a'))) * sympy.sqrt(x) * sympy.Function('Gamma')((Integer(4))**(Integer(-1)), ((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))) * ((Integer(16) * Symbol('b') * (((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))**((Integer(4))**(Integer(-1)))))**(Integer(-1)))) + ((sympy.I * sympy.sqrt(x) * sympy.Function('Gamma')((Integer(4))**(Integer(-1)), (sympy.I * Symbol('b') * (x)**(Integer(2))))) * (((sympy.E)**((sympy.I * Symbol('a'))) * (Integer(16) * Symbol('b') * ((sympy.I * Symbol('b') * (x)**(Integer(2))))**((Integer(4))**(Integer(-1))))))**(Integer(-1))) + ((sympy.sqrt(x) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**(Integer(2)))))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x)*cos(a + b*x**2),
        variable=x,
        num_steps=3,
        integral=((Integer(-1) * (((sympy.E)**((sympy.I * Symbol('a'))) * (x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(3) * (Integer(4))**(Integer(-1))), ((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))) * ((Integer(4) * (((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))**((Integer(3) * (Integer(4))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * (((x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(3) * (Integer(4))**(Integer(-1))), (sympy.I * Symbol('b') * (x)**(Integer(2))))) * (((sympy.E)**((sympy.I * Symbol('a'))) * (Integer(4) * ((sympy.I * Symbol('b') * (x)**(Integer(2))))**((Integer(3) * (Integer(4))**(Integer(-1)))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)/sqrt(x),
        variable=x,
        num_steps=3,
        integral=((Integer(-1) * (((sympy.E)**((sympy.I * Symbol('a'))) * sympy.sqrt(x) * sympy.Function('Gamma')((Integer(4))**(Integer(-1)), ((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))) * ((Integer(4) * (((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))**((Integer(4))**(Integer(-1)))))**(Integer(-1)))) + (Integer(-1) * ((sympy.sqrt(x) * sympy.Function('Gamma')((Integer(4))**(Integer(-1)), (sympy.I * Symbol('b') * (x)**(Integer(2))))) * (((sympy.E)**((sympy.I * Symbol('a'))) * (Integer(4) * ((sympy.I * Symbol('b') * (x)**(Integer(2))))**((Integer(4))**(Integer(-1))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)/x**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=((Integer(-1) * ((Integer(2) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**(Integer(2)))))) * (sympy.sqrt(x))**(Integer(-1)))) + (Integer(-1) * ((sympy.I * Symbol('b') * (sympy.E)**((sympy.I * Symbol('a'))) * (x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(3) * (Integer(4))**(Integer(-1))), ((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))) * ((((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))**((Integer(3) * (Integer(4))**(Integer(-1)))))**(Integer(-1)))) + ((sympy.I * Symbol('b') * (x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(3) * (Integer(4))**(Integer(-1))), (sympy.I * Symbol('b') * (x)**(Integer(2))))) * (((sympy.E)**((sympy.I * Symbol('a'))) * ((sympy.I * Symbol('b') * (x)**(Integer(2))))**((Integer(3) * (Integer(4))**(Integer(-1))))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)/x**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=((Integer(-1) * ((Integer(2) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**(Integer(2)))))) * ((Integer(3) * (x)**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((sympy.I * Symbol('b') * (sympy.E)**((sympy.I * Symbol('a'))) * sympy.sqrt(x) * sympy.Function('Gamma')((Integer(4))**(Integer(-1)), ((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))) * ((Integer(3) * (((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))**((Integer(4))**(Integer(-1)))))**(Integer(-1)))) + ((sympy.I * Symbol('b') * sympy.sqrt(x) * sympy.Function('Gamma')((Integer(4))**(Integer(-1)), (sympy.I * Symbol('b') * (x)**(Integer(2))))) * (((sympy.E)**((sympy.I * Symbol('a'))) * (Integer(3) * ((sympy.I * Symbol('b') * (x)**(Integer(2))))**((Integer(4))**(Integer(-1))))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x**(sympy.S(5)/2)*cos(a + b*x**2)**2,
        variable=x,
        num_steps=7,
        integral=(((x)**((Integer(7) * (Integer(2))**(Integer(-1)))) * (Integer(7))**(Integer(-1))) + (Integer(-1) * ((Integer(3) * sympy.I * (sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * (x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(3) * (Integer(4))**(Integer(-1))), (Integer(-2) * sympy.I * Symbol('b') * (x)**(Integer(2))))) * ((Integer(64) * (Integer(2))**((Integer(3) * (Integer(4))**(Integer(-1)))) * Symbol('b') * (((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))**((Integer(3) * (Integer(4))**(Integer(-1))))))**(Integer(-1)))) + ((Integer(3) * sympy.I * (x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(3) * (Integer(4))**(Integer(-1))), (Integer(2) * sympy.I * Symbol('b') * (x)**(Integer(2))))) * (((sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * (Integer(64) * (Integer(2))**((Integer(3) * (Integer(4))**(Integer(-1)))) * Symbol('b') * ((sympy.I * Symbol('b') * (x)**(Integer(2))))**((Integer(3) * (Integer(4))**(Integer(-1)))))))**(Integer(-1))) + (((x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sin((Integer(2) * (Symbol('a') + (Symbol('b') * (x)**(Integer(2))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x**(sympy.S(3)/2)*cos(a + b*x**2)**2,
        variable=x,
        num_steps=7,
        integral=(((x)**((Integer(5) * (Integer(2))**(Integer(-1)))) * (Integer(5))**(Integer(-1))) + (Integer(-1) * ((sympy.I * (sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * sympy.sqrt(x) * sympy.Function('Gamma')((Integer(4))**(Integer(-1)), (Integer(-2) * sympy.I * Symbol('b') * (x)**(Integer(2))))) * ((Integer(64) * (Integer(2))**((Integer(4))**(Integer(-1))) * Symbol('b') * (((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))**((Integer(4))**(Integer(-1)))))**(Integer(-1)))) + ((sympy.I * sympy.sqrt(x) * sympy.Function('Gamma')((Integer(4))**(Integer(-1)), (Integer(2) * sympy.I * Symbol('b') * (x)**(Integer(2))))) * (((sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * (Integer(64) * (Integer(2))**((Integer(4))**(Integer(-1))) * Symbol('b') * ((sympy.I * Symbol('b') * (x)**(Integer(2))))**((Integer(4))**(Integer(-1))))))**(Integer(-1))) + ((sympy.sqrt(x) * sympy.sin((Integer(2) * (Symbol('a') + (Symbol('b') * (x)**(Integer(2))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x)*cos(a + b*x**2)**2,
        variable=x,
        num_steps=6,
        integral=(((x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * (Integer(3))**(Integer(-1))) + (Integer(-1) * (((sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * (x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(3) * (Integer(4))**(Integer(-1))), (Integer(-2) * sympy.I * Symbol('b') * (x)**(Integer(2))))) * ((Integer(8) * (Integer(2))**((Integer(3) * (Integer(4))**(Integer(-1)))) * (((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))**((Integer(3) * (Integer(4))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * (((x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(3) * (Integer(4))**(Integer(-1))), (Integer(2) * sympy.I * Symbol('b') * (x)**(Integer(2))))) * (((sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * (Integer(8) * (Integer(2))**((Integer(3) * (Integer(4))**(Integer(-1)))) * ((sympy.I * Symbol('b') * (x)**(Integer(2))))**((Integer(3) * (Integer(4))**(Integer(-1)))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)**2/sqrt(x),
        variable=x,
        num_steps=6,
        integral=(sympy.sqrt(x) + (Integer(-1) * (((sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * sympy.sqrt(x) * sympy.Function('Gamma')((Integer(4))**(Integer(-1)), (Integer(-2) * sympy.I * Symbol('b') * (x)**(Integer(2))))) * ((Integer(8) * (Integer(2))**((Integer(4))**(Integer(-1))) * (((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))**((Integer(4))**(Integer(-1)))))**(Integer(-1)))) + (Integer(-1) * ((sympy.sqrt(x) * sympy.Function('Gamma')((Integer(4))**(Integer(-1)), (Integer(2) * sympy.I * Symbol('b') * (x)**(Integer(2))))) * (((sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * (Integer(8) * (Integer(2))**((Integer(4))**(Integer(-1))) * ((sympy.I * Symbol('b') * (x)**(Integer(2))))**((Integer(4))**(Integer(-1))))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)**2/x**(sympy.S(3)/2),
        variable=x,
        num_steps=7,
        integral=((Integer(-1) * (sympy.sqrt(x))**(Integer(-1))) + (Integer(-1) * (sympy.cos((Integer(2) * (Symbol('a') + (Symbol('b') * (x)**(Integer(2)))))) * (sympy.sqrt(x))**(Integer(-1)))) + (Integer(-1) * ((sympy.I * Symbol('b') * (sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * (x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(3) * (Integer(4))**(Integer(-1))), (Integer(-2) * sympy.I * Symbol('b') * (x)**(Integer(2))))) * (((Integer(2))**((Integer(3) * (Integer(4))**(Integer(-1)))) * (((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))**((Integer(3) * (Integer(4))**(Integer(-1))))))**(Integer(-1)))) + ((sympy.I * Symbol('b') * (x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.Function('Gamma')((Integer(3) * (Integer(4))**(Integer(-1))), (Integer(2) * sympy.I * Symbol('b') * (x)**(Integer(2))))) * (((sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * ((Integer(2))**((Integer(3) * (Integer(4))**(Integer(-1)))) * ((sympy.I * Symbol('b') * (x)**(Integer(2))))**((Integer(3) * (Integer(4))**(Integer(-1)))))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**2)**2/x**(sympy.S(5)/2),
        variable=x,
        num_steps=7,
        integral=((Integer(-1) * ((Integer(2) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**(Integer(2))))))**(Integer(2))) * ((Integer(3) * (x)**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((sympy.I * Symbol('b') * (sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * sympy.sqrt(x) * sympy.Function('Gamma')((Integer(4))**(Integer(-1)), (Integer(-2) * sympy.I * Symbol('b') * (x)**(Integer(2))))) * ((Integer(3) * (Integer(2))**((Integer(4))**(Integer(-1))) * (((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Integer(2))))**((Integer(4))**(Integer(-1)))))**(Integer(-1)))) + ((sympy.I * Symbol('b') * sympy.sqrt(x) * sympy.Function('Gamma')((Integer(4))**(Integer(-1)), (Integer(2) * sympy.I * Symbol('b') * (x)**(Integer(2))))) * (((sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * (Integer(3) * (Integer(2))**((Integer(4))**(Integer(-1))) * ((sympy.I * Symbol('b') * (x)**(Integer(2))))**((Integer(4))**(Integer(-1))))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b/x),
        variable=x,
        num_steps=5,
        integral=((x * sympy.cos((Symbol('a') + (Symbol('b') * (x)**(Integer(-1)))))) + (Symbol('b') * sympy.Function('CosIntegral')((Symbol('b') * (x)**(Integer(-1)))) * sympy.sin(Symbol('a'))) + (Symbol('b') * sympy.cos(Symbol('a')) * sympy.Function('SinIntegral')((Symbol('b') * (x)**(Integer(-1)))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b/x)/x,
        variable=x,
        num_steps=3,
        integral=(((Integer(-1) * sympy.cos(Symbol('a'))) * sympy.Function('CosIntegral')((Symbol('b') * (x)**(Integer(-1))))) + (sympy.sin(Symbol('a')) * sympy.Function('SinIntegral')((Symbol('b') * (x)**(Integer(-1)))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b/x)/x**2,
        variable=x,
        num_steps=2,
        integral=-sin(a + b/x)/b,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b/x)/x**3,
        variable=x,
        num_steps=3,
        integral=-sin(a + b/x)/(b*x) - cos(a + b/x)/b**2,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b/x)/x**4,
        variable=x,
        num_steps=4,
        integral=-sin(a + b/x)/(b*x**2) - 2*cos(a + b/x)/(b**2*x) + 2*sin(a + b/x)/b**3,
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b/x**2),
        variable=x,
        num_steps=5,
        integral=((x * sympy.cos((Symbol('a') + (Symbol('b') * ((x)**(Integer(2)))**(Integer(-1)))))) + (sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * sympy.pi)) * sympy.cos(Symbol('a')) * sympy.Function('FresnelS')(((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1))))) * (x)**(Integer(-1))))) + (sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * sympy.pi)) * sympy.Function('FresnelC')(((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1))))) * (x)**(Integer(-1)))) * sympy.sin(Symbol('a')))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b/x**2)/x,
        variable=x,
        num_steps=3,
        integral=(((Integer(-1) * (Integer(2))**(Integer(-1))) * sympy.cos(Symbol('a')) * sympy.Function('CosIntegral')((Symbol('b') * ((x)**(Integer(2)))**(Integer(-1))))) + ((Integer(2))**(Integer(-1)) * sympy.sin(Symbol('a')) * sympy.Function('SinIntegral')((Symbol('b') * ((x)**(Integer(2)))**(Integer(-1)))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b/x**2)/x**2,
        variable=x,
        num_steps=4,
        integral=((Integer(-1) * ((sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.cos(Symbol('a')) * sympy.Function('FresnelC')(((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1))))) * (x)**(Integer(-1))))) * (sympy.sqrt(Symbol('b')))**(Integer(-1)))) + ((sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelS')(((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1))))) * (x)**(Integer(-1)))) * sympy.sin(Symbol('a'))) * (sympy.sqrt(Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b/x**2)/x**3,
        variable=x,
        num_steps=2,
        integral=-sin(a + b/x**2)/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b/x**2)/x**4,
        variable=x,
        num_steps=5,
        integral=(((sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.cos(Symbol('a')) * sympy.Function('FresnelS')(((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1))))) * (x)**(Integer(-1))))) * ((Integer(2) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1))) + ((sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelC')(((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1))))) * (x)**(Integer(-1)))) * sympy.sin(Symbol('a'))) * ((Integer(2) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * (sympy.sin((Symbol('a') + (Symbol('b') * ((x)**(Integer(2)))**(Integer(-1))))) * ((Integer(2) * Symbol('b') * x))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(sqrt(x))**2/sqrt(x),
        variable=x,
        num_steps=3,
        integral=sqrt(x) + sin(sqrt(x))*cos(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=cos(sqrt(x))/sqrt(x),
        variable=x,
        num_steps=2,
        integral=2*sin(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=cos(sqrt(x)),
        variable=x,
        num_steps=3,
        integral=2*sqrt(x)*sin(sqrt(x)) + 2*cos(sqrt(x)),
    ),
    RubiTestSuiteCase(
        integrand=cos(sqrt(x))**2,
        variable=x,
        num_steps=3,
        integral=sqrt(x)*sin(sqrt(x))*cos(sqrt(x)) + x/2 + cos(sqrt(x))**2/2,
    ),
    RubiTestSuiteCase(
        integrand=x**(sympy.S(3)/2)*cos(a + b*x**(sympy.S(1)/3)),
        variable=x,
        num_steps=13,
        integral=(((Integer(135135) * sympy.sqrt(x) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(32) * (Symbol('b'))**(Integer(6))))**(Integer(-1))) + (Integer(-1) * ((Integer(3861) * (x)**((Integer(7) * (Integer(6))**(Integer(-1)))) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(8) * (Symbol('b'))**(Integer(4))))**(Integer(-1)))) + ((Integer(39) * (x)**((Integer(11) * (Integer(6))**(Integer(-1)))) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(2) * (Symbol('b'))**(Integer(2))))**(Integer(-1))) + ((Integer(405405) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.cos(Symbol('a')) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (x)**((Integer(6))**(Integer(-1)))))) * ((Integer(64) * (Symbol('b'))**((Integer(15) * (Integer(2))**(Integer(-1))))))**(Integer(-1))) + ((Integer(405405) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (x)**((Integer(6))**(Integer(-1))))) * sympy.sin(Symbol('a'))) * ((Integer(64) * (Symbol('b'))**((Integer(15) * (Integer(2))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(405405) * (x)**((Integer(6))**(Integer(-1))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(64) * (Symbol('b'))**(Integer(7))))**(Integer(-1)))) + ((Integer(27027) * (x)**((Integer(5) * (Integer(6))**(Integer(-1)))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(16) * (Symbol('b'))**(Integer(5))))**(Integer(-1))) + (Integer(-1) * ((Integer(429) * (x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(4) * (Symbol('b'))**(Integer(3))))**(Integer(-1)))) + ((Integer(3) * (x)**((Integer(13) * (Integer(6))**(Integer(-1)))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * (Symbol('b'))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x)*cos(a + b*x**(sympy.S(1)/3)),
        variable=x,
        num_steps=10,
        integral=((Integer(-1) * ((Integer(315) * (x)**((Integer(6))**(Integer(-1))) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(8) * (Symbol('b'))**(Integer(4))))**(Integer(-1)))) + ((Integer(21) * (x)**((Integer(5) * (Integer(6))**(Integer(-1)))) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(2) * (Symbol('b'))**(Integer(2))))**(Integer(-1))) + ((Integer(315) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.cos(Symbol('a')) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (x)**((Integer(6))**(Integer(-1)))))) * ((Integer(8) * (Symbol('b'))**((Integer(9) * (Integer(2))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(315) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (x)**((Integer(6))**(Integer(-1))))) * sympy.sin(Symbol('a'))) * ((Integer(8) * (Symbol('b'))**((Integer(9) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((Integer(105) * sympy.sqrt(x) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(4) * (Symbol('b'))**(Integer(3))))**(Integer(-1)))) + ((Integer(3) * (x)**((Integer(7) * (Integer(6))**(Integer(-1)))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * (Symbol('b'))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**(sympy.S(1)/3))/sqrt(x),
        variable=x,
        num_steps=7,
        integral=((Integer(-1) * ((Integer(3) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.cos(Symbol('a')) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (x)**((Integer(6))**(Integer(-1)))))) * ((Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1)))))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (x)**((Integer(6))**(Integer(-1))))) * sympy.sin(Symbol('a'))) * ((Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1)))))**(Integer(-1)))) + ((Integer(3) * (x)**((Integer(6))**(Integer(-1))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * (Symbol('b'))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**(sympy.S(1)/3))/x**(sympy.S(3)/2),
        variable=x,
        num_steps=8,
        integral=((Integer(-1) * ((Integer(2) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * (sympy.sqrt(x))**(Integer(-1)))) + (Integer(-1) * (Integer(4) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sqrt((Integer(2) * sympy.pi)) * sympy.cos(Symbol('a')) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (x)**((Integer(6))**(Integer(-1))))))) + (Integer(4) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sqrt((Integer(2) * sympy.pi)) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (x)**((Integer(6))**(Integer(-1))))) * sympy.sin(Symbol('a'))) + ((Integer(4) * Symbol('b') * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((x)**((Integer(6))**(Integer(-1))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**(sympy.S(1)/3))/x**(sympy.S(5)/2),
        variable=x,
        num_steps=11,
        integral=((Integer(-1) * ((Integer(2) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(3) * (x)**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + ((Integer(8) * (Symbol('b'))**(Integer(2)) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(105) * (x)**((Integer(5) * (Integer(6))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(32) * (Symbol('b'))**(Integer(4)) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(315) * (x)**((Integer(6))**(Integer(-1)))))**(Integer(-1)))) + (Integer(-1) * ((Integer(32) * (Integer(315))**(Integer(-1))) * (Symbol('b'))**((Integer(9) * (Integer(2))**(Integer(-1)))) * sympy.sqrt((Integer(2) * sympy.pi)) * sympy.cos(Symbol('a')) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (x)**((Integer(6))**(Integer(-1))))))) + (Integer(-1) * ((Integer(32) * (Integer(315))**(Integer(-1))) * (Symbol('b'))**((Integer(9) * (Integer(2))**(Integer(-1)))) * sympy.sqrt((Integer(2) * sympy.pi)) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (x)**((Integer(6))**(Integer(-1))))) * sympy.sin(Symbol('a')))) + ((Integer(4) * Symbol('b') * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(21) * (x)**((Integer(7) * (Integer(6))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(16) * (Symbol('b'))**(Integer(3)) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(315) * sympy.sqrt(x)))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**(sympy.S(1)/3))/x**(sympy.S(7)/2),
        variable=x,
        num_steps=14,
        integral=((Integer(-1) * ((Integer(2) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(5) * (x)**((Integer(5) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + ((Integer(8) * (Symbol('b'))**(Integer(2)) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(715) * (x)**((Integer(11) * (Integer(6))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(32) * (Symbol('b'))**(Integer(4)) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(45045) * (x)**((Integer(7) * (Integer(6))**(Integer(-1))))))**(Integer(-1)))) + ((Integer(128) * (Symbol('b'))**(Integer(6)) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(675675) * sympy.sqrt(x)))**(Integer(-1))) + ((Integer(256) * (Symbol('b'))**((Integer(15) * (Integer(2))**(Integer(-1)))) * sympy.sqrt((Integer(2) * sympy.pi)) * sympy.cos(Symbol('a')) * sympy.Function('FresnelC')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (x)**((Integer(6))**(Integer(-1)))))) * (Integer(675675))**(Integer(-1))) + (Integer(-1) * ((Integer(256) * (Symbol('b'))**((Integer(15) * (Integer(2))**(Integer(-1)))) * sympy.sqrt((Integer(2) * sympy.pi)) * sympy.Function('FresnelS')((sympy.sqrt(Symbol('b')) * sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (x)**((Integer(6))**(Integer(-1))))) * sympy.sin(Symbol('a'))) * (Integer(675675))**(Integer(-1)))) + ((Integer(4) * Symbol('b') * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(65) * (x)**((Integer(13) * (Integer(6))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(16) * (Symbol('b'))**(Integer(3)) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(6435) * (x)**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + ((Integer(64) * (Symbol('b'))**(Integer(5)) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(225225) * (x)**((Integer(5) * (Integer(6))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(256) * (Symbol('b'))**(Integer(7)) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(675675) * (x)**((Integer(6))**(Integer(-1)))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**(sympy.S(3)/2)*cos(a + b*x**(sympy.S(1)/3))**2,
        variable=x,
        num_steps=15,
        integral=((Integer(-1) * ((Integer(135135) * sympy.sqrt(x)) * ((Integer(4096) * (Symbol('b'))**(Integer(6))))**(Integer(-1)))) + ((Integer(3861) * (x)**((Integer(7) * (Integer(6))**(Integer(-1))))) * ((Integer(256) * (Symbol('b'))**(Integer(4))))**(Integer(-1))) + (Integer(-1) * ((Integer(39) * (x)**((Integer(11) * (Integer(6))**(Integer(-1))))) * ((Integer(16) * (Symbol('b'))**(Integer(2))))**(Integer(-1)))) + ((x)**((Integer(5) * (Integer(2))**(Integer(-1)))) * (Integer(5))**(Integer(-1))) + ((Integer(135135) * sympy.sqrt(x) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))**(Integer(2))) * ((Integer(2048) * (Symbol('b'))**(Integer(6))))**(Integer(-1))) + (Integer(-1) * ((Integer(3861) * (x)**((Integer(7) * (Integer(6))**(Integer(-1)))) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))**(Integer(2))) * ((Integer(128) * (Symbol('b'))**(Integer(4))))**(Integer(-1)))) + ((Integer(39) * (x)**((Integer(11) * (Integer(6))**(Integer(-1)))) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))**(Integer(2))) * ((Integer(8) * (Symbol('b'))**(Integer(2))))**(Integer(-1))) + ((Integer(405405) * sympy.sqrt(sympy.pi) * sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('FresnelS')(((Integer(2) * sympy.sqrt(Symbol('b')) * (x)**((Integer(6))**(Integer(-1)))) * (sympy.sqrt(sympy.pi))**(Integer(-1))))) * ((Integer(32768) * (Symbol('b'))**((Integer(15) * (Integer(2))**(Integer(-1))))))**(Integer(-1))) + ((Integer(405405) * sympy.sqrt(sympy.pi) * sympy.Function('FresnelC')(((Integer(2) * sympy.sqrt(Symbol('b')) * (x)**((Integer(6))**(Integer(-1)))) * (sympy.sqrt(sympy.pi))**(Integer(-1)))) * sympy.sin((Integer(2) * Symbol('a')))) * ((Integer(32768) * (Symbol('b'))**((Integer(15) * (Integer(2))**(Integer(-1))))))**(Integer(-1))) + ((Integer(27027) * (x)**((Integer(5) * (Integer(6))**(Integer(-1)))) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(512) * (Symbol('b'))**(Integer(5))))**(Integer(-1))) + (Integer(-1) * ((Integer(429) * (x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(32) * (Symbol('b'))**(Integer(3))))**(Integer(-1)))) + ((Integer(3) * (x)**((Integer(13) * (Integer(6))**(Integer(-1)))) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(2) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((Integer(405405) * (x)**((Integer(6))**(Integer(-1))) * sympy.sin((Integer(2) * (Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))) * ((Integer(16384) * (Symbol('b'))**(Integer(7))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(x)*cos(a + b*x**(sympy.S(1)/3))**2,
        variable=x,
        num_steps=12,
        integral=(((Integer(315) * (x)**((Integer(6))**(Integer(-1)))) * ((Integer(256) * (Symbol('b'))**(Integer(4))))**(Integer(-1))) + (Integer(-1) * ((Integer(21) * (x)**((Integer(5) * (Integer(6))**(Integer(-1))))) * ((Integer(16) * (Symbol('b'))**(Integer(2))))**(Integer(-1)))) + ((x)**((Integer(3) * (Integer(2))**(Integer(-1)))) * (Integer(3))**(Integer(-1))) + (Integer(-1) * ((Integer(315) * (x)**((Integer(6))**(Integer(-1))) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))**(Integer(2))) * ((Integer(128) * (Symbol('b'))**(Integer(4))))**(Integer(-1)))) + ((Integer(21) * (x)**((Integer(5) * (Integer(6))**(Integer(-1)))) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))**(Integer(2))) * ((Integer(8) * (Symbol('b'))**(Integer(2))))**(Integer(-1))) + ((Integer(315) * sympy.sqrt(sympy.pi) * sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('FresnelC')(((Integer(2) * sympy.sqrt(Symbol('b')) * (x)**((Integer(6))**(Integer(-1)))) * (sympy.sqrt(sympy.pi))**(Integer(-1))))) * ((Integer(512) * (Symbol('b'))**((Integer(9) * (Integer(2))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(315) * sympy.sqrt(sympy.pi) * sympy.Function('FresnelS')(((Integer(2) * sympy.sqrt(Symbol('b')) * (x)**((Integer(6))**(Integer(-1)))) * (sympy.sqrt(sympy.pi))**(Integer(-1)))) * sympy.sin((Integer(2) * Symbol('a')))) * ((Integer(512) * (Symbol('b'))**((Integer(9) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((Integer(105) * sympy.sqrt(x) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(32) * (Symbol('b'))**(Integer(3))))**(Integer(-1)))) + ((Integer(3) * (x)**((Integer(7) * (Integer(6))**(Integer(-1)))) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**(sympy.S(1)/3))**2/sqrt(x),
        variable=x,
        num_steps=9,
        integral=(sympy.sqrt(x) + (Integer(-1) * ((Integer(3) * sympy.sqrt(sympy.pi) * sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('FresnelS')(((Integer(2) * sympy.sqrt(Symbol('b')) * (x)**((Integer(6))**(Integer(-1)))) * (sympy.sqrt(sympy.pi))**(Integer(-1))))) * ((Integer(8) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * sympy.sqrt(sympy.pi) * sympy.Function('FresnelC')(((Integer(2) * sympy.sqrt(Symbol('b')) * (x)**((Integer(6))**(Integer(-1)))) * (sympy.sqrt(sympy.pi))**(Integer(-1)))) * sympy.sin((Integer(2) * Symbol('a')))) * ((Integer(8) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + ((Integer(3) * (x)**((Integer(6))**(Integer(-1))) * sympy.sin((Integer(2) * (Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**(sympy.S(1)/3))**2/x**(sympy.S(3)/2),
        variable=x,
        num_steps=10,
        integral=((Integer(-1) * ((Integer(2) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))**(Integer(2))) * (sympy.sqrt(x))**(Integer(-1)))) + (Integer(-1) * (Integer(8) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sqrt(sympy.pi) * sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('FresnelC')(((Integer(2) * sympy.sqrt(Symbol('b')) * (x)**((Integer(6))**(Integer(-1)))) * (sympy.sqrt(sympy.pi))**(Integer(-1)))))) + (Integer(8) * (Symbol('b'))**((Integer(3) * (Integer(2))**(Integer(-1)))) * sympy.sqrt(sympy.pi) * sympy.Function('FresnelS')(((Integer(2) * sympy.sqrt(Symbol('b')) * (x)**((Integer(6))**(Integer(-1)))) * (sympy.sqrt(sympy.pi))**(Integer(-1)))) * sympy.sin((Integer(2) * Symbol('a')))) + ((Integer(8) * Symbol('b') * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((x)**((Integer(6))**(Integer(-1))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**(sympy.S(1)/3))**2/x**(sympy.S(5)/2),
        variable=x,
        num_steps=12,
        integral=((Integer(-1) * ((Integer(16) * (Symbol('b'))**(Integer(2))) * ((Integer(105) * (x)**((Integer(5) * (Integer(6))**(Integer(-1))))))**(Integer(-1)))) + ((Integer(256) * (Symbol('b'))**(Integer(4))) * ((Integer(315) * (x)**((Integer(6))**(Integer(-1)))))**(Integer(-1))) + (Integer(-1) * ((Integer(2) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))**(Integer(2))) * ((Integer(3) * (x)**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + ((Integer(32) * (Symbol('b'))**(Integer(2)) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))**(Integer(2))) * ((Integer(105) * (x)**((Integer(5) * (Integer(6))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(512) * (Symbol('b'))**(Integer(4)) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))**(Integer(2))) * ((Integer(315) * (x)**((Integer(6))**(Integer(-1)))))**(Integer(-1)))) + (Integer(-1) * ((Integer(512) * (Integer(315))**(Integer(-1))) * (Symbol('b'))**((Integer(9) * (Integer(2))**(Integer(-1)))) * sympy.sqrt(sympy.pi) * sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('FresnelS')(((Integer(2) * sympy.sqrt(Symbol('b')) * (x)**((Integer(6))**(Integer(-1)))) * (sympy.sqrt(sympy.pi))**(Integer(-1)))))) + (Integer(-1) * ((Integer(512) * (Integer(315))**(Integer(-1))) * (Symbol('b'))**((Integer(9) * (Integer(2))**(Integer(-1)))) * sympy.sqrt(sympy.pi) * sympy.Function('FresnelC')(((Integer(2) * sympy.sqrt(Symbol('b')) * (x)**((Integer(6))**(Integer(-1)))) * (sympy.sqrt(sympy.pi))**(Integer(-1)))) * sympy.sin((Integer(2) * Symbol('a'))))) + ((Integer(8) * Symbol('b') * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(21) * (x)**((Integer(7) * (Integer(6))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(128) * (Symbol('b'))**(Integer(3)) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(315) * sympy.sqrt(x)))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**(sympy.S(1)/3))**2/x**(sympy.S(7)/2),
        variable=x,
        num_steps=16,
        integral=((Integer(-1) * ((Integer(16) * (Symbol('b'))**(Integer(2))) * ((Integer(715) * (x)**((Integer(11) * (Integer(6))**(Integer(-1))))))**(Integer(-1)))) + ((Integer(256) * (Symbol('b'))**(Integer(4))) * ((Integer(45045) * (x)**((Integer(7) * (Integer(6))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(4096) * (Symbol('b'))**(Integer(6))) * ((Integer(675675) * sympy.sqrt(x)))**(Integer(-1)))) + (Integer(-1) * ((Integer(2) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))**(Integer(2))) * ((Integer(5) * (x)**((Integer(5) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + ((Integer(32) * (Symbol('b'))**(Integer(2)) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))**(Integer(2))) * ((Integer(715) * (x)**((Integer(11) * (Integer(6))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(512) * (Symbol('b'))**(Integer(4)) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))**(Integer(2))) * ((Integer(45045) * (x)**((Integer(7) * (Integer(6))**(Integer(-1))))))**(Integer(-1)))) + ((Integer(8192) * (Symbol('b'))**(Integer(6)) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))))**(Integer(2))) * ((Integer(675675) * sympy.sqrt(x)))**(Integer(-1))) + ((Integer(32768) * (Symbol('b'))**((Integer(15) * (Integer(2))**(Integer(-1)))) * sympy.sqrt(sympy.pi) * sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('FresnelC')(((Integer(2) * sympy.sqrt(Symbol('b')) * (x)**((Integer(6))**(Integer(-1)))) * (sympy.sqrt(sympy.pi))**(Integer(-1))))) * (Integer(675675))**(Integer(-1))) + (Integer(-1) * ((Integer(32768) * (Symbol('b'))**((Integer(15) * (Integer(2))**(Integer(-1)))) * sympy.sqrt(sympy.pi) * sympy.Function('FresnelS')(((Integer(2) * sympy.sqrt(Symbol('b')) * (x)**((Integer(6))**(Integer(-1)))) * (sympy.sqrt(sympy.pi))**(Integer(-1)))) * sympy.sin((Integer(2) * Symbol('a')))) * (Integer(675675))**(Integer(-1)))) + ((Integer(8) * Symbol('b') * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(65) * (x)**((Integer(13) * (Integer(6))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(128) * (Symbol('b'))**(Integer(3)) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(6435) * (x)**((Integer(3) * (Integer(2))**(Integer(-1))))))**(Integer(-1)))) + ((Integer(2048) * (Symbol('b'))**(Integer(5)) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(225225) * (x)**((Integer(5) * (Integer(6))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * ((Integer(32768) * (Symbol('b'))**(Integer(7)) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1)))))) * sympy.sin((Symbol('a') + (Symbol('b') * (x)**((Integer(3))**(Integer(-1))))))) * ((Integer(675675) * (x)**((Integer(6))**(Integer(-1)))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(x**(sympy.S(1)/3))**3,
        variable=x,
        num_steps=7,
        integral=x**(sympy.S(2)/3)*sin(x**(sympy.S(1)/3))*cos(x**(sympy.S(1)/3))**2 + 2*x**(sympy.S(2)/3)*sin(x**(sympy.S(1)/3)) + 2*x**(sympy.S(1)/3)*cos(x**(sympy.S(1)/3))**3/3 + 4*x**(sympy.S(1)/3)*cos(x**(sympy.S(1)/3)) + 2*sin(x**(sympy.S(1)/3))**3/9 - 14*sin(x**(sympy.S(1)/3))/3,
    ),
    RubiTestSuiteCase(
        integrand=cos(x**(sympy.S(1)/6))/x**(sympy.S(5)/6),
        variable=x,
        num_steps=2,
        integral=6*sin(x**(sympy.S(1)/6)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x**n))**p*(e*x)**m,
        variable=x,
        num_steps=0,
        integral=sympy.Function('Unintegrable')((((Symbol('e') * x))**(Symbol('m')) * ((Symbol('b') * sympy.cos((Symbol('c') + (Symbol('d') * (x)**(Symbol('n')))))))**(Symbol('p'))), x),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**m*(a + b*cos(c + d*x**n))**p,
        variable=x,
        num_steps=0,
        integral=sympy.Function('Unintegrable')((((Symbol('e') * x))**(Symbol('m')) * ((Symbol('a') + (Symbol('b') * sympy.cos((Symbol('c') + (Symbol('d') * (x)**(Symbol('n'))))))))**(Symbol('p'))), x),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x**n))**p*(e*x)**(n - 1),
        variable=x,
        num_steps=3,
        integral=-(b*cos(c + d*x**n))**(p + 1)*(e*x)**n*sin(c + d*x**n)*hyper((sympy.S.Half, p/2 + sympy.S.Half), (p/2 + sympy.S(3)/2,), cos(c + d*x**n)**2)/(b*d*e*n*x**n*(p + 1)*sqrt(sin(c + d*x**n)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(b*cos(c + d*x**n))**p*(e*x)**(2*n - 1),
        variable=x,
        num_steps=1,
        integral=((((Symbol('e') * x))**((Integer(2) * Symbol('n'))) * sympy.Function('Unintegrable')(((x)**((Integer(-1) + (Integer(2) * Symbol('n')))) * ((Symbol('b') * sympy.cos((Symbol('c') + (Symbol('d') * (x)**(Symbol('n')))))))**(Symbol('p'))), x)) * (((x)**((Integer(2) * Symbol('n'))) * Symbol('e')))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**(n - 1)*(a + b*cos(c + d*x**n))**p,
        variable=x,
        num_steps=5,
        integral=sqrt(2)*(e*x)**n*(a + b*cos(c + d*x**n))**p*sin(c + d*x**n)*appellf1(sympy.S.Half, sympy.S.Half, -p, sympy.S(3)/2, sympy.S.Half - cos(c + d*x**n)/2, b*(1 - cos(c + d*x**n))/(a + b))/(d*e*n*x**n*((a + b*cos(c + d*x**n))/(a + b))**p*sqrt(cos(c + d*x**n) + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(e*x)**(2*n - 1)*(a + b*cos(c + d*x**n))**p,
        variable=x,
        num_steps=1,
        integral=((((Symbol('e') * x))**((Integer(2) * Symbol('n'))) * sympy.Function('Unintegrable')(((x)**((Integer(-1) + (Integer(2) * Symbol('n')))) * ((Symbol('a') + (Symbol('b') * sympy.cos((Symbol('c') + (Symbol('d') * (x)**(Symbol('n'))))))))**(Symbol('p'))), x)) * (((x)**((Integer(2) * Symbol('n'))) * Symbol('e')))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**n)/x,
        variable=x,
        num_steps=3,
        integral=(((sympy.cos(Symbol('a')) * sympy.Function('CosIntegral')((Symbol('b') * (x)**(Symbol('n'))))) * (Symbol('n'))**(Integer(-1))) + (Integer(-1) * ((sympy.sin(Symbol('a')) * sympy.Function('SinIntegral')((Symbol('b') * (x)**(Symbol('n'))))) * (Symbol('n'))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**n)**2/x,
        variable=x,
        num_steps=5,
        integral=(((sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('CosIntegral')((Integer(2) * Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(2) * Symbol('n')))**(Integer(-1))) + (sympy.log(x) * (Integer(2))**(Integer(-1))) + (Integer(-1) * ((sympy.sin((Integer(2) * Symbol('a'))) * sympy.Function('SinIntegral')((Integer(2) * Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(2) * Symbol('n')))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**n)**3/x,
        variable=x,
        num_steps=8,
        integral=(((Integer(3) * sympy.cos(Symbol('a')) * sympy.Function('CosIntegral')((Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(4) * Symbol('n')))**(Integer(-1))) + ((sympy.cos((Integer(3) * Symbol('a'))) * sympy.Function('CosIntegral')((Integer(3) * Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(4) * Symbol('n')))**(Integer(-1))) + (Integer(-1) * ((Integer(3) * sympy.sin(Symbol('a')) * sympy.Function('SinIntegral')((Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(4) * Symbol('n')))**(Integer(-1)))) + (Integer(-1) * ((sympy.sin((Integer(3) * Symbol('a'))) * sympy.Function('SinIntegral')((Integer(3) * Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(4) * Symbol('n')))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**n)**4/x,
        variable=x,
        num_steps=8,
        integral=(((sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('CosIntegral')((Integer(2) * Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(2) * Symbol('n')))**(Integer(-1))) + ((sympy.cos((Integer(4) * Symbol('a'))) * sympy.Function('CosIntegral')((Integer(4) * Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(8) * Symbol('n')))**(Integer(-1))) + ((Integer(3) * sympy.log(x)) * (Integer(8))**(Integer(-1))) + (Integer(-1) * ((sympy.sin((Integer(2) * Symbol('a'))) * sympy.Function('SinIntegral')((Integer(2) * Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(2) * Symbol('n')))**(Integer(-1)))) + (Integer(-1) * ((sympy.sin((Integer(4) * Symbol('a'))) * sympy.Function('SinIntegral')((Integer(4) * Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(8) * Symbol('n')))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**n),
        variable=x,
        num_steps=3,
        integral=((Integer(-1) * (((sympy.E)**((sympy.I * Symbol('a'))) * x * sympy.Function('Gamma')((Symbol('n'))**(Integer(-1)), ((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Symbol('n'))))) * (((((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * (Integer(2) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * ((x * sympy.Function('Gamma')((Symbol('n'))**(Integer(-1)), (sympy.I * Symbol('b') * (x)**(Symbol('n'))))) * (((sympy.E)**((sympy.I * Symbol('a'))) * ((sympy.I * Symbol('b') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * (Integer(2) * Symbol('n'))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**n)**2,
        variable=x,
        num_steps=5,
        integral=((x * (Integer(2))**(Integer(-1))) + (Integer(-1) * (((Integer(2))**((Integer(-2) + (Integer(-1) * (Symbol('n'))**(Integer(-1))))) * (sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * x * sympy.Function('Gamma')((Symbol('n'))**(Integer(-1)), (Integer(-2) * sympy.I * Symbol('b') * (x)**(Symbol('n'))))) * (((((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * Symbol('n')))**(Integer(-1)))) + (Integer(-1) * (((Integer(2))**((Integer(-2) + (Integer(-1) * (Symbol('n'))**(Integer(-1))))) * x * sympy.Function('Gamma')((Symbol('n'))**(Integer(-1)), (Integer(2) * sympy.I * Symbol('b') * (x)**(Symbol('n'))))) * (((sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * ((sympy.I * Symbol('b') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * Symbol('n')))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*x**n)**3,
        variable=x,
        num_steps=8,
        integral=((Integer(-1) * ((Integer(3) * (sympy.E)**((sympy.I * Symbol('a'))) * x * sympy.Function('Gamma')((Symbol('n'))**(Integer(-1)), ((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Symbol('n'))))) * (((((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * (Integer(8) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * x * sympy.Function('Gamma')((Symbol('n'))**(Integer(-1)), (sympy.I * Symbol('b') * (x)**(Symbol('n'))))) * (((sympy.E)**((sympy.I * Symbol('a'))) * ((sympy.I * Symbol('b') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * (Integer(8) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * (((sympy.E)**((Integer(3) * sympy.I * Symbol('a'))) * x * sympy.Function('Gamma')((Symbol('n'))**(Integer(-1)), (Integer(-3) * sympy.I * Symbol('b') * (x)**(Symbol('n'))))) * (((Integer(3))**((Symbol('n'))**(Integer(-1))) * (((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * (Integer(8) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * ((x * sympy.Function('Gamma')((Symbol('n'))**(Integer(-1)), (Integer(3) * sympy.I * Symbol('b') * (x)**(Symbol('n'))))) * (((Integer(3))**((Symbol('n'))**(Integer(-1))) * (sympy.E)**((Integer(3) * sympy.I * Symbol('a'))) * ((sympy.I * Symbol('b') * (x)**(Symbol('n'))))**((Symbol('n'))**(Integer(-1))) * (Integer(8) * Symbol('n'))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**m*cos(a + b*x**n),
        variable=x,
        num_steps=3,
        integral=((Integer(-1) * (((sympy.E)**((sympy.I * Symbol('a'))) * (x)**((Integer(1) + Symbol('m'))) * sympy.Function('Gamma')(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1))), ((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Symbol('n'))))) * (((((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (Integer(2) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * (((x)**((Integer(1) + Symbol('m'))) * sympy.Function('Gamma')(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1))), (sympy.I * Symbol('b') * (x)**(Symbol('n'))))) * (((sympy.E)**((sympy.I * Symbol('a'))) * ((sympy.I * Symbol('b') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (Integer(2) * Symbol('n'))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**m*cos(a + b*x**n)**2,
        variable=x,
        num_steps=5,
        integral=(((x)**((Integer(1) + Symbol('m'))) * ((Integer(2) * (Integer(1) + Symbol('m'))))**(Integer(-1))) + (Integer(-1) * (((sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * (x)**((Integer(1) + Symbol('m'))) * sympy.Function('Gamma')(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1))), (Integer(-2) * sympy.I * Symbol('b') * (x)**(Symbol('n'))))) * (((Integer(2))**(((Integer(1) + Symbol('m') + (Integer(2) * Symbol('n'))) * (Symbol('n'))**(Integer(-1)))) * (((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * Symbol('n')))**(Integer(-1)))) + (Integer(-1) * (((x)**((Integer(1) + Symbol('m'))) * sympy.Function('Gamma')(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1))), (Integer(2) * sympy.I * Symbol('b') * (x)**(Symbol('n'))))) * (((Integer(2))**(((Integer(1) + Symbol('m') + (Integer(2) * Symbol('n'))) * (Symbol('n'))**(Integer(-1)))) * (sympy.E)**((Integer(2) * sympy.I * Symbol('a'))) * ((sympy.I * Symbol('b') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * Symbol('n')))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**m*cos(a + b*x**n)**3,
        variable=x,
        num_steps=8,
        integral=((Integer(-1) * ((Integer(3) * (sympy.E)**((sympy.I * Symbol('a'))) * (x)**((Integer(1) + Symbol('m'))) * sympy.Function('Gamma')(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1))), ((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Symbol('n'))))) * (((((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (Integer(8) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * (x)**((Integer(1) + Symbol('m'))) * sympy.Function('Gamma')(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1))), (sympy.I * Symbol('b') * (x)**(Symbol('n'))))) * (((sympy.E)**((sympy.I * Symbol('a'))) * ((sympy.I * Symbol('b') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (Integer(8) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * (((sympy.E)**((Integer(3) * sympy.I * Symbol('a'))) * (x)**((Integer(1) + Symbol('m'))) * sympy.Function('Gamma')(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1))), (Integer(-3) * sympy.I * Symbol('b') * (x)**(Symbol('n'))))) * (((Integer(3))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (((Integer(-1) * sympy.I) * Symbol('b') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (Integer(8) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * (((x)**((Integer(1) + Symbol('m'))) * sympy.Function('Gamma')(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1))), (Integer(3) * sympy.I * Symbol('b') * (x)**(Symbol('n'))))) * (((Integer(3))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (sympy.E)**((Integer(3) * sympy.I * Symbol('a'))) * ((sympy.I * Symbol('b') * (x)**(Symbol('n'))))**(((Integer(1) + Symbol('m')) * (Symbol('n'))**(Integer(-1)))) * (Integer(8) * Symbol('n'))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**(-n - 1)*cos(a + b*x**n),
        variable=x,
        num_steps=5,
        integral=((Integer(-1) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**(Symbol('n'))))) * (((x)**(Symbol('n')) * Symbol('n')))**(Integer(-1)))) + (Integer(-1) * ((Symbol('b') * sympy.Function('CosIntegral')((Symbol('b') * (x)**(Symbol('n')))) * sympy.sin(Symbol('a'))) * (Symbol('n'))**(Integer(-1)))) + (Integer(-1) * ((Symbol('b') * sympy.cos(Symbol('a')) * sympy.Function('SinIntegral')((Symbol('b') * (x)**(Symbol('n'))))) * (Symbol('n'))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**(-n - 1)*cos(a + b*x**n)**2,
        variable=x,
        num_steps=7,
        integral=((Integer(-1) * (((x)**(Symbol('n')) * (Integer(2) * Symbol('n'))))**(Integer(-1))) + (Integer(-1) * (sympy.cos((Integer(2) * (Symbol('a') + (Symbol('b') * (x)**(Symbol('n')))))) * (((x)**(Symbol('n')) * (Integer(2) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * ((Symbol('b') * sympy.Function('CosIntegral')((Integer(2) * Symbol('b') * (x)**(Symbol('n')))) * sympy.sin((Integer(2) * Symbol('a')))) * (Symbol('n'))**(Integer(-1)))) + (Integer(-1) * ((Symbol('b') * sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('SinIntegral')((Integer(2) * Symbol('b') * (x)**(Symbol('n'))))) * (Symbol('n'))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**(-n - 1)*cos(a + b*x**n)**3,
        variable=x,
        num_steps=12,
        integral=((Integer(-1) * ((Integer(3) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**(Symbol('n')))))) * (((x)**(Symbol('n')) * (Integer(4) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * (sympy.cos((Integer(3) * (Symbol('a') + (Symbol('b') * (x)**(Symbol('n')))))) * (((x)**(Symbol('n')) * (Integer(4) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * Symbol('b') * sympy.Function('CosIntegral')((Symbol('b') * (x)**(Symbol('n')))) * sympy.sin(Symbol('a'))) * ((Integer(4) * Symbol('n')))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * Symbol('b') * sympy.Function('CosIntegral')((Integer(3) * Symbol('b') * (x)**(Symbol('n')))) * sympy.sin((Integer(3) * Symbol('a')))) * ((Integer(4) * Symbol('n')))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * Symbol('b') * sympy.cos(Symbol('a')) * sympy.Function('SinIntegral')((Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(4) * Symbol('n')))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * Symbol('b') * sympy.cos((Integer(3) * Symbol('a'))) * sympy.Function('SinIntegral')((Integer(3) * Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(4) * Symbol('n')))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**(-2*n - 1)*cos(a + b*x**n),
        variable=x,
        num_steps=6,
        integral=((Integer(-1) * (sympy.cos((Symbol('a') + (Symbol('b') * (x)**(Symbol('n'))))) * (((x)**((Integer(2) * Symbol('n'))) * (Integer(2) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * (((Symbol('b'))**(Integer(2)) * sympy.cos(Symbol('a')) * sympy.Function('CosIntegral')((Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(2) * Symbol('n')))**(Integer(-1)))) + ((Symbol('b') * sympy.sin((Symbol('a') + (Symbol('b') * (x)**(Symbol('n')))))) * (((x)**(Symbol('n')) * (Integer(2) * Symbol('n'))))**(Integer(-1))) + (((Symbol('b'))**(Integer(2)) * sympy.sin(Symbol('a')) * sympy.Function('SinIntegral')((Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(2) * Symbol('n')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x**(-2*n - 1)*cos(a + b*x**n)**2,
        variable=x,
        num_steps=8,
        integral=((Integer(-1) * (((x)**((Integer(2) * Symbol('n'))) * (Integer(4) * Symbol('n'))))**(Integer(-1))) + (Integer(-1) * (sympy.cos((Integer(2) * (Symbol('a') + (Symbol('b') * (x)**(Symbol('n')))))) * (((x)**((Integer(2) * Symbol('n'))) * (Integer(4) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * (((Symbol('b'))**(Integer(2)) * sympy.cos((Integer(2) * Symbol('a'))) * sympy.Function('CosIntegral')((Integer(2) * Symbol('b') * (x)**(Symbol('n'))))) * (Symbol('n'))**(Integer(-1)))) + ((Symbol('b') * sympy.sin((Integer(2) * (Symbol('a') + (Symbol('b') * (x)**(Symbol('n'))))))) * (((x)**(Symbol('n')) * (Integer(2) * Symbol('n'))))**(Integer(-1))) + (((Symbol('b'))**(Integer(2)) * sympy.sin((Integer(2) * Symbol('a'))) * sympy.Function('SinIntegral')((Integer(2) * Symbol('b') * (x)**(Symbol('n'))))) * (Symbol('n'))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x**(-2*n - 1)*cos(a + b*x**n)**3,
        variable=x,
        num_steps=14,
        integral=((Integer(-1) * ((Integer(3) * sympy.cos((Symbol('a') + (Symbol('b') * (x)**(Symbol('n')))))) * (((x)**((Integer(2) * Symbol('n'))) * (Integer(8) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * (sympy.cos((Integer(3) * (Symbol('a') + (Symbol('b') * (x)**(Symbol('n')))))) * (((x)**((Integer(2) * Symbol('n'))) * (Integer(8) * Symbol('n'))))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * (Symbol('b'))**(Integer(2)) * sympy.cos(Symbol('a')) * sympy.Function('CosIntegral')((Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(8) * Symbol('n')))**(Integer(-1)))) + (Integer(-1) * ((Integer(9) * (Symbol('b'))**(Integer(2)) * sympy.cos((Integer(3) * Symbol('a'))) * sympy.Function('CosIntegral')((Integer(3) * Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(8) * Symbol('n')))**(Integer(-1)))) + ((Integer(3) * Symbol('b') * sympy.sin((Symbol('a') + (Symbol('b') * (x)**(Symbol('n')))))) * (((x)**(Symbol('n')) * (Integer(8) * Symbol('n'))))**(Integer(-1))) + ((Integer(3) * Symbol('b') * sympy.sin((Integer(3) * (Symbol('a') + (Symbol('b') * (x)**(Symbol('n'))))))) * (((x)**(Symbol('n')) * (Integer(8) * Symbol('n'))))**(Integer(-1))) + ((Integer(3) * (Symbol('b'))**(Integer(2)) * sympy.sin(Symbol('a')) * sympy.Function('SinIntegral')((Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(8) * Symbol('n')))**(Integer(-1))) + ((Integer(9) * (Symbol('b'))**(Integer(2)) * sympy.sin((Integer(3) * Symbol('a'))) * sympy.Function('SinIntegral')((Integer(3) * Symbol('b') * (x)**(Symbol('n'))))) * ((Integer(8) * Symbol('n')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x**2*cos((a + b*x)**2),
        variable=x,
        num_steps=7,
        integral=((((Symbol('a'))**(Integer(2)) * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelC')((sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (Symbol('a') + (Symbol('b') * x))))) * ((Symbol('b'))**(Integer(3)))**(Integer(-1))) + (Integer(-1) * ((sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelS')((sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (Symbol('a') + (Symbol('b') * x))))) * ((Integer(2) * (Symbol('b'))**(Integer(3))))**(Integer(-1)))) + (Integer(-1) * ((Symbol('a') * sympy.sin(((Symbol('a') + (Symbol('b') * x)))**(Integer(2)))) * ((Symbol('b'))**(Integer(3)))**(Integer(-1)))) + (((Symbol('a') + (Symbol('b') * x)) * sympy.sin(((Symbol('a') + (Symbol('b') * x)))**(Integer(2)))) * ((Integer(2) * (Symbol('b'))**(Integer(3))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x*cos((a + b*x)**2),
        variable=x,
        num_steps=5,
        integral=((Integer(-1) * ((Symbol('a') * sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelC')((sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (Symbol('a') + (Symbol('b') * x))))) * ((Symbol('b'))**(Integer(2)))**(Integer(-1)))) + (sympy.sin(((Symbol('a') + (Symbol('b') * x)))**(Integer(2))) * ((Integer(2) * (Symbol('b'))**(Integer(2))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos((a + b*x)**2),
        variable=x,
        num_steps=1,
        integral=((sympy.sqrt((sympy.pi * (Integer(2))**(Integer(-1)))) * sympy.Function('FresnelC')((sympy.sqrt((Integer(2) * (sympy.pi)**(Integer(-1)))) * (Symbol('a') + (Symbol('b') * x))))) * (Symbol('b'))**(Integer(-1))),
    ),
    RubiTestSuiteCase(
        integrand=cos((a + b*x)**2)/x,
        variable=x,
        num_steps=0,
        integral=sympy.Function('Unintegrable')((sympy.cos(((Symbol('a') + (Symbol('b') * x)))**(Integer(2))) * (x)**(Integer(-1))), x),
    ),
    RubiTestSuiteCase(
        integrand=cos((a + b*x)**2)/x**2,
        variable=x,
        num_steps=0,
        integral=sympy.Function('Unintegrable')((sympy.cos(((Symbol('a') + (Symbol('b') * x)))**(Integer(2))) * ((x)**(Integer(2)))**(Integer(-1))), x),
    ),
    RubiTestSuiteCase(
        integrand=x**2*cos(a + b*sqrt(c + d*x)),
        variable=x,
        num_steps=14,
        integral=2*c**2*sqrt(c + d*x)*sin(a + b*sqrt(c + d*x))/(b*d**3) - 4*c*(c + d*x)**(sympy.S(3)/2)*sin(a + b*sqrt(c + d*x))/(b*d**3) + 2*(c + d*x)**(sympy.S(5)/2)*sin(a + b*sqrt(c + d*x))/(b*d**3) + 2*c**2*cos(a + b*sqrt(c + d*x))/(b**2*d**3) - 12*c*(c + d*x)*cos(a + b*sqrt(c + d*x))/(b**2*d**3) + 10*(c + d*x)**2*cos(a + b*sqrt(c + d*x))/(b**2*d**3) + 24*c*sqrt(c + d*x)*sin(a + b*sqrt(c + d*x))/(b**3*d**3) - 40*(c + d*x)**(sympy.S(3)/2)*sin(a + b*sqrt(c + d*x))/(b**3*d**3) + 24*c*cos(a + b*sqrt(c + d*x))/(b**4*d**3) - (120*c + 120*d*x)*cos(a + b*sqrt(c + d*x))/(b**4*d**3) + 240*sqrt(c + d*x)*sin(a + b*sqrt(c + d*x))/(b**5*d**3) + 240*cos(a + b*sqrt(c + d*x))/(b**6*d**3),
    ),
    RubiTestSuiteCase(
        integrand=x*cos(a + b*sqrt(c + d*x)),
        variable=x,
        num_steps=8,
        integral=-2*c*sqrt(c + d*x)*sin(a + b*sqrt(c + d*x))/(b*d**2) + 2*(c + d*x)**(sympy.S(3)/2)*sin(a + b*sqrt(c + d*x))/(b*d**2) - 2*c*cos(a + b*sqrt(c + d*x))/(b**2*d**2) + (6*c + 6*d*x)*cos(a + b*sqrt(c + d*x))/(b**2*d**2) - 12*sqrt(c + d*x)*sin(a + b*sqrt(c + d*x))/(b**3*d**2) - 12*cos(a + b*sqrt(c + d*x))/(b**4*d**2),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*sqrt(c + d*x)),
        variable=x,
        num_steps=3,
        integral=2*sqrt(c + d*x)*sin(a + b*sqrt(c + d*x))/(b*d) + 2*cos(a + b*sqrt(c + d*x))/(b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*sqrt(c + d*x))/x,
        variable=x,
        num_steps=8,
        integral=((sympy.cos((Symbol('a') + (Integer(-1) * (Symbol('b') * sympy.sqrt(Symbol('c')))))) * sympy.Function('CosIntegral')((Symbol('b') * (sympy.sqrt(Symbol('c')) + sympy.sqrt((Symbol('c') + (Symbol('d') * x))))))) + (sympy.cos((Symbol('a') + (Symbol('b') * sympy.sqrt(Symbol('c'))))) * sympy.Function('CosIntegral')(((Symbol('b') * sympy.sqrt(Symbol('c'))) + (Integer(-1) * (Symbol('b') * sympy.sqrt((Symbol('c') + (Symbol('d') * x)))))))) + (Integer(-1) * (sympy.sin((Symbol('a') + (Integer(-1) * (Symbol('b') * sympy.sqrt(Symbol('c')))))) * sympy.Function('SinIntegral')((Symbol('b') * (sympy.sqrt(Symbol('c')) + sympy.sqrt((Symbol('c') + (Symbol('d') * x)))))))) + (sympy.sin((Symbol('a') + (Symbol('b') * sympy.sqrt(Symbol('c'))))) * sympy.Function('SinIntegral')(((Symbol('b') * sympy.sqrt(Symbol('c'))) + (Integer(-1) * (Symbol('b') * sympy.sqrt((Symbol('c') + (Symbol('d') * x))))))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*sqrt(c + d*x))/x**2,
        variable=x,
        num_steps=10,
        integral=((Integer(-1) * (sympy.cos((Symbol('a') + (Symbol('b') * sympy.sqrt((Symbol('c') + (Symbol('d') * x)))))) * (x)**(Integer(-1)))) + ((Symbol('b') * Symbol('d') * sympy.Function('CosIntegral')((Symbol('b') * (sympy.sqrt(Symbol('c')) + sympy.sqrt((Symbol('c') + (Symbol('d') * x)))))) * sympy.sin((Symbol('a') + (Integer(-1) * (Symbol('b') * sympy.sqrt(Symbol('c'))))))) * ((Integer(2) * sympy.sqrt(Symbol('c'))))**(Integer(-1))) + (Integer(-1) * ((Symbol('b') * Symbol('d') * sympy.Function('CosIntegral')(((Symbol('b') * sympy.sqrt(Symbol('c'))) + (Integer(-1) * (Symbol('b') * sympy.sqrt((Symbol('c') + (Symbol('d') * x))))))) * sympy.sin((Symbol('a') + (Symbol('b') * sympy.sqrt(Symbol('c')))))) * ((Integer(2) * sympy.sqrt(Symbol('c'))))**(Integer(-1)))) + ((Symbol('b') * Symbol('d') * sympy.cos((Symbol('a') + (Integer(-1) * (Symbol('b') * sympy.sqrt(Symbol('c')))))) * sympy.Function('SinIntegral')((Symbol('b') * (sympy.sqrt(Symbol('c')) + sympy.sqrt((Symbol('c') + (Symbol('d') * x))))))) * ((Integer(2) * sympy.sqrt(Symbol('c'))))**(Integer(-1))) + ((Symbol('b') * Symbol('d') * sympy.cos((Symbol('a') + (Symbol('b') * sympy.sqrt(Symbol('c'))))) * sympy.Function('SinIntegral')(((Symbol('b') * sympy.sqrt(Symbol('c'))) + (Integer(-1) * (Symbol('b') * sympy.sqrt((Symbol('c') + (Symbol('d') * x)))))))) * ((Integer(2) * sympy.sqrt(Symbol('c'))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=x**2*cos(a + b*(c + d*x)**(sympy.S(1)/3)),
        variable=x,
        num_steps=20,
        integral=3*c**2*(c + d*x)**(sympy.S(2)/3)*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b*d**3) - 6*c*(c + d*x)**(sympy.S(5)/3)*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b*d**3) + 3*(c + d*x)**(sympy.S(8)/3)*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b*d**3) + 6*c**2*(c + d*x)**(sympy.S(1)/3)*cos(a + b*(c + d*x)**(sympy.S(1)/3))/(b**2*d**3) - 30*c*(c + d*x)**(sympy.S(4)/3)*cos(a + b*(c + d*x)**(sympy.S(1)/3))/(b**2*d**3) + 24*(c + d*x)**(sympy.S(7)/3)*cos(a + b*(c + d*x)**(sympy.S(1)/3))/(b**2*d**3) - 6*c**2*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b**3*d**3) + 120*c*(c + d*x)*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b**3*d**3) - 168*(c + d*x)**2*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b**3*d**3) + 360*c*(c + d*x)**(sympy.S(2)/3)*cos(a + b*(c + d*x)**(sympy.S(1)/3))/(b**4*d**3) - 1008*(c + d*x)**(sympy.S(5)/3)*cos(a + b*(c + d*x)**(sympy.S(1)/3))/(b**4*d**3) - 720*c*(c + d*x)**(sympy.S(1)/3)*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b**5*d**3) + 5040*(c + d*x)**(sympy.S(4)/3)*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b**5*d**3) - 720*c*cos(a + b*(c + d*x)**(sympy.S(1)/3))/(b**6*d**3) + (20160*c + 20160*d*x)*cos(a + b*(c + d*x)**(sympy.S(1)/3))/(b**6*d**3) - 60480*(c + d*x)**(sympy.S(2)/3)*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b**7*d**3) - 120960*(c + d*x)**(sympy.S(1)/3)*cos(a + b*(c + d*x)**(sympy.S(1)/3))/(b**8*d**3) + 120960*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b**9*d**3),
    ),
    RubiTestSuiteCase(
        integrand=x*cos(a + b*(c + d*x)**(sympy.S(1)/3)),
        variable=x,
        num_steps=11,
        integral=-3*c*(c + d*x)**(sympy.S(2)/3)*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b*d**2) + 3*(c + d*x)**(sympy.S(5)/3)*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b*d**2) - 6*c*(c + d*x)**(sympy.S(1)/3)*cos(a + b*(c + d*x)**(sympy.S(1)/3))/(b**2*d**2) + 15*(c + d*x)**(sympy.S(4)/3)*cos(a + b*(c + d*x)**(sympy.S(1)/3))/(b**2*d**2) + 6*c*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b**3*d**2) - (60*c + 60*d*x)*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b**3*d**2) - 180*(c + d*x)**(sympy.S(2)/3)*cos(a + b*(c + d*x)**(sympy.S(1)/3))/(b**4*d**2) + 360*(c + d*x)**(sympy.S(1)/3)*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b**5*d**2) + 360*cos(a + b*(c + d*x)**(sympy.S(1)/3))/(b**6*d**2),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*(c + d*x)**(sympy.S(1)/3)),
        variable=x,
        num_steps=4,
        integral=3*(c + d*x)**(sympy.S(2)/3)*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b*d) + 6*(c + d*x)**(sympy.S(1)/3)*cos(a + b*(c + d*x)**(sympy.S(1)/3))/(b**2*d) - 6*sin(a + b*(c + d*x)**(sympy.S(1)/3))/(b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*(c + d*x)**(sympy.S(1)/3))/x,
        variable=x,
        num_steps=11,
        integral=((sympy.cos((Symbol('a') + (Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))))) * sympy.Function('CosIntegral')(((Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))) + (Integer(-1) * (Symbol('b') * ((Symbol('c') + (Symbol('d') * x)))**((Integer(3))**(Integer(-1)))))))) + (sympy.cos((Symbol('a') + ((Integer(-1))**((Integer(2) * (Integer(3))**(Integer(-1)))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))))) * sympy.Function('CosIntegral')((((Integer(-1))**((Integer(2) * (Integer(3))**(Integer(-1)))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))) + (Integer(-1) * (Symbol('b') * ((Symbol('c') + (Symbol('d') * x)))**((Integer(3))**(Integer(-1)))))))) + (sympy.cos((Symbol('a') + (Integer(-1) * ((Integer(-1))**((Integer(3))**(Integer(-1))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1))))))) * sympy.Function('CosIntegral')((((Integer(-1))**((Integer(3))**(Integer(-1))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))) + (Symbol('b') * ((Symbol('c') + (Symbol('d') * x)))**((Integer(3))**(Integer(-1))))))) + (sympy.sin((Symbol('a') + (Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))))) * sympy.Function('SinIntegral')(((Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))) + (Integer(-1) * (Symbol('b') * ((Symbol('c') + (Symbol('d') * x)))**((Integer(3))**(Integer(-1)))))))) + (sympy.sin((Symbol('a') + ((Integer(-1))**((Integer(2) * (Integer(3))**(Integer(-1)))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))))) * sympy.Function('SinIntegral')((((Integer(-1))**((Integer(2) * (Integer(3))**(Integer(-1)))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))) + (Integer(-1) * (Symbol('b') * ((Symbol('c') + (Symbol('d') * x)))**((Integer(3))**(Integer(-1)))))))) + (Integer(-1) * (sympy.sin((Symbol('a') + (Integer(-1) * ((Integer(-1))**((Integer(3))**(Integer(-1))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1))))))) * sympy.Function('SinIntegral')((((Integer(-1))**((Integer(3))**(Integer(-1))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))) + (Symbol('b') * ((Symbol('c') + (Symbol('d') * x)))**((Integer(3))**(Integer(-1))))))))),
    ),
    RubiTestSuiteCase(
        integrand=cos(a + b*(c + d*x)**(sympy.S(1)/3))/x**2,
        variable=x,
        num_steps=13,
        integral=((Integer(-1) * (sympy.cos((Symbol('a') + (Symbol('b') * ((Symbol('c') + (Symbol('d') * x)))**((Integer(3))**(Integer(-1)))))) * (x)**(Integer(-1)))) + (Integer(-1) * ((Symbol('b') * Symbol('d') * sympy.Function('CosIntegral')(((Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))) + (Integer(-1) * (Symbol('b') * ((Symbol('c') + (Symbol('d') * x)))**((Integer(3))**(Integer(-1))))))) * sympy.sin((Symbol('a') + (Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1))))))) * ((Integer(3) * (Symbol('c'))**((Integer(2) * (Integer(3))**(Integer(-1))))))**(Integer(-1)))) + (((Integer(-1))**((Integer(3))**(Integer(-1))) * Symbol('b') * Symbol('d') * sympy.Function('CosIntegral')((((Integer(-1))**((Integer(3))**(Integer(-1))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))) + (Symbol('b') * ((Symbol('c') + (Symbol('d') * x)))**((Integer(3))**(Integer(-1)))))) * sympy.sin((Symbol('a') + (Integer(-1) * ((Integer(-1))**((Integer(3))**(Integer(-1))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))))))) * ((Integer(3) * (Symbol('c'))**((Integer(2) * (Integer(3))**(Integer(-1))))))**(Integer(-1))) + (Integer(-1) * (((Integer(-1))**((Integer(2) * (Integer(3))**(Integer(-1)))) * Symbol('b') * Symbol('d') * sympy.Function('CosIntegral')((((Integer(-1))**((Integer(2) * (Integer(3))**(Integer(-1)))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))) + (Integer(-1) * (Symbol('b') * ((Symbol('c') + (Symbol('d') * x)))**((Integer(3))**(Integer(-1))))))) * sympy.sin((Symbol('a') + ((Integer(-1))**((Integer(2) * (Integer(3))**(Integer(-1)))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1))))))) * ((Integer(3) * (Symbol('c'))**((Integer(2) * (Integer(3))**(Integer(-1))))))**(Integer(-1)))) + ((Symbol('b') * Symbol('d') * sympy.cos((Symbol('a') + (Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))))) * sympy.Function('SinIntegral')(((Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))) + (Integer(-1) * (Symbol('b') * ((Symbol('c') + (Symbol('d') * x)))**((Integer(3))**(Integer(-1)))))))) * ((Integer(3) * (Symbol('c'))**((Integer(2) * (Integer(3))**(Integer(-1))))))**(Integer(-1))) + (((Integer(-1))**((Integer(2) * (Integer(3))**(Integer(-1)))) * Symbol('b') * Symbol('d') * sympy.cos((Symbol('a') + ((Integer(-1))**((Integer(2) * (Integer(3))**(Integer(-1)))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))))) * sympy.Function('SinIntegral')((((Integer(-1))**((Integer(2) * (Integer(3))**(Integer(-1)))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))) + (Integer(-1) * (Symbol('b') * ((Symbol('c') + (Symbol('d') * x)))**((Integer(3))**(Integer(-1)))))))) * ((Integer(3) * (Symbol('c'))**((Integer(2) * (Integer(3))**(Integer(-1))))))**(Integer(-1))) + (((Integer(-1))**((Integer(3))**(Integer(-1))) * Symbol('b') * Symbol('d') * sympy.cos((Symbol('a') + (Integer(-1) * ((Integer(-1))**((Integer(3))**(Integer(-1))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1))))))) * sympy.Function('SinIntegral')((((Integer(-1))**((Integer(3))**(Integer(-1))) * Symbol('b') * (Symbol('c'))**((Integer(3))**(Integer(-1)))) + (Symbol('b') * ((Symbol('c') + (Symbol('d') * x)))**((Integer(3))**(Integer(-1))))))) * ((Integer(3) * (Symbol('c'))**((Integer(2) * (Integer(3))**(Integer(-1))))))**(Integer(-1)))),
    ),
]
