# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 6 Hyperbolic functions/6.3 Hyperbolic tangent/6.3.2 Hyperbolic tangent functions.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '6 Hyperbolic functions/6.3 Hyperbolic tangent/6.3.2 Hyperbolic tangent functions.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, c, d, e, m, n = symbols('a b c d e m n')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=tanh(a + b*x)**6,
        variable=x,
        num_steps=4,
        integral=x - tanh(a + b*x)**5/(5*b) - tanh(a + b*x)**3/(3*b) - tanh(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=tanh(a + b*x)**5,
        variable=x,
        num_steps=3,
        integral=log(cosh(a + b*x))/b - tanh(a + b*x)**4/(4*b) - tanh(a + b*x)**2/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=tanh(a + b*x)**4,
        variable=x,
        num_steps=3,
        integral=x - tanh(a + b*x)**3/(3*b) - tanh(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=tanh(a + b*x)**3,
        variable=x,
        num_steps=2,
        integral=log(cosh(a + b*x))/b - tanh(a + b*x)**2/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=tanh(a + b*x)**2,
        variable=x,
        num_steps=2,
        integral=x - tanh(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=tanh(a + b*x),
        variable=x,
        num_steps=1,
        integral=log(cosh(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=coth(a + b*x),
        variable=x,
        num_steps=1,
        integral=log(sinh(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=coth(a + b*x)**2,
        variable=x,
        num_steps=2,
        integral=x - coth(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=coth(a + b*x)**3,
        variable=x,
        num_steps=2,
        integral=log(sinh(a + b*x))/b - coth(a + b*x)**2/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=coth(a + b*x)**4,
        variable=x,
        num_steps=3,
        integral=x - coth(a + b*x)**3/(3*b) - coth(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=coth(a + b*x)**5,
        variable=x,
        num_steps=3,
        integral=log(sinh(a + b*x))/b - coth(a + b*x)**4/(4*b) - coth(a + b*x)**2/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=coth(a + b*x)**6,
        variable=x,
        num_steps=4,
        integral=x - coth(a + b*x)**5/(5*b) - coth(a + b*x)**3/(3*b) - coth(a + b*x)/b,
    ),
    RubiTestSuiteCase(
        integrand=(b*tanh(c + d*x))**(sympy.S(7)/2),
        variable=x,
        num_steps=7,
        integral=b**(sympy.S(7)/2)*atan(sqrt(b*tanh(c + d*x))/sqrt(b))/d + b**(sympy.S(7)/2)*atanh(sqrt(b*tanh(c + d*x))/sqrt(b))/d - 2*b**3*sqrt(b*tanh(c + d*x))/d - 2*b*(b*tanh(c + d*x))**(sympy.S(5)/2)/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*tanh(c + d*x))**(sympy.S(5)/2),
        variable=x,
        num_steps=6,
        integral=-b**(sympy.S(5)/2)*atan(sqrt(b*tanh(c + d*x))/sqrt(b))/d + b**(sympy.S(5)/2)*atanh(sqrt(b*tanh(c + d*x))/sqrt(b))/d - 2*b*(b*tanh(c + d*x))**(sympy.S(3)/2)/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*tanh(c + d*x))**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=b**(sympy.S(3)/2)*atan(sqrt(b*tanh(c + d*x))/sqrt(b))/d + b**(sympy.S(3)/2)*atanh(sqrt(b*tanh(c + d*x))/sqrt(b))/d - 2*b*sqrt(b*tanh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(b*tanh(c + d*x)),
        variable=x,
        num_steps=5,
        integral=-sqrt(b)*atan(sqrt(b*tanh(c + d*x))/sqrt(b))/d + sqrt(b)*atanh(sqrt(b*tanh(c + d*x))/sqrt(b))/d,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(b*tanh(c + d*x)),
        variable=x,
        num_steps=5,
        integral=atan(sqrt(b*tanh(c + d*x))/sqrt(b))/(sqrt(b)*d) + atanh(sqrt(b*tanh(c + d*x))/sqrt(b))/(sqrt(b)*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*tanh(c + d*x))**(sympy.S(-3)/2),
        variable=x,
        num_steps=6,
        integral=-2/(b*d*sqrt(b*tanh(c + d*x))) - atan(sqrt(b*tanh(c + d*x))/sqrt(b))/(b**(sympy.S(3)/2)*d) + atanh(sqrt(b*tanh(c + d*x))/sqrt(b))/(b**(sympy.S(3)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*tanh(c + d*x))**(sympy.S(-5)/2),
        variable=x,
        num_steps=6,
        integral=-2/(3*b*d*(b*tanh(c + d*x))**(sympy.S(3)/2)) + atan(sqrt(b*tanh(c + d*x))/sqrt(b))/(b**(sympy.S(5)/2)*d) + atanh(sqrt(b*tanh(c + d*x))/sqrt(b))/(b**(sympy.S(5)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=(b*tanh(c + d*x))**(sympy.S(-7)/2),
        variable=x,
        num_steps=7,
        integral=-2/(5*b*d*(b*tanh(c + d*x))**(sympy.S(5)/2)) - 2/(b**3*d*sqrt(b*tanh(c + d*x))) - atan(sqrt(b*tanh(c + d*x))/sqrt(b))/(b**(sympy.S(7)/2)*d) + atanh(sqrt(b*tanh(c + d*x))/sqrt(b))/(b**(sympy.S(7)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=tanh(8*x)**(sympy.S(1)/3),
        variable=x,
        num_steps=9,
        integral=-log(1 - tanh(8*x)**(sympy.S(2)/3))/16 + log(tanh(8*x)**(sympy.S(4)/3) + tanh(8*x)**(sympy.S(2)/3) + 1)/32 - sqrt(3)*atan(sqrt(3)*(2*tanh(8*x)**(sympy.S(2)/3) + 1)/3)/16,
    ),
    RubiTestSuiteCase(
        integrand=tanh(a + b*x)**n,
        variable=x,
        num_steps=2,
        integral=tanh(a + b*x)**(n + 1)*hyper((1, n/2 + sympy.S.Half), (n/2 + sympy.S(3)/2,), tanh(a + b*x)**2)/(b*(n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(b*tanh(c + d*x))**n,
        variable=x,
        num_steps=2,
        integral=(b*tanh(c + d*x))**(n + 1)*hyper((1, n/2 + sympy.S.Half), (n/2 + sympy.S(3)/2,), tanh(c + d*x)**2)/(b*d*(n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(a*tanh(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=a*sqrt(a*tanh(x)**2)*log(cosh(x))*coth(x) - a*sqrt(a*tanh(x)**2)*tanh(x)/2,
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*tanh(x)**2),
        variable=x,
        num_steps=2,
        integral=sqrt(a*tanh(x)**2)*log(cosh(x))*coth(x),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*tanh(x)**2),
        variable=x,
        num_steps=2,
        integral=log(sinh(x))*tanh(x)/sqrt(a*tanh(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=(-tanh(c + d*x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=sqrt(-tanh(c + d*x)**2)*log(cosh(c + d*x))*coth(c + d*x)/d - sqrt(-tanh(c + d*x)**2)*tanh(c + d*x)**3/(4*d) - sqrt(-tanh(c + d*x)**2)*tanh(c + d*x)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(-tanh(c + d*x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-sqrt(-tanh(c + d*x)**2)*log(cosh(c + d*x))*coth(c + d*x)/d + sqrt(-tanh(c + d*x)**2)*tanh(c + d*x)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-tanh(c + d*x)**2),
        variable=x,
        num_steps=2,
        integral=sqrt(-tanh(c + d*x)**2)*log(cosh(c + d*x))*coth(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-tanh(c + d*x)**2),
        variable=x,
        num_steps=2,
        integral=log(sinh(c + d*x))*tanh(c + d*x)/(d*sqrt(-tanh(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(-tanh(c + d*x)**2)**(sympy.S(-3)/2),
        variable=x,
        num_steps=3,
        integral=-log(sinh(c + d*x))*tanh(c + d*x)/(d*sqrt(-tanh(c + d*x)**2)) + coth(c + d*x)/(2*d*sqrt(-tanh(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(-tanh(c + d*x)**2)**(sympy.S(-5)/2),
        variable=x,
        num_steps=4,
        integral=log(sinh(c + d*x))*tanh(c + d*x)/(d*sqrt(-tanh(c + d*x)**2)) - coth(c + d*x)**3/(4*d*sqrt(-tanh(c + d*x)**2)) - coth(c + d*x)/(2*d*sqrt(-tanh(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(tanh(x)**3),
        variable=x,
        num_steps=7,
        integral=-2*sqrt(tanh(x)**3)*coth(x) + sqrt(tanh(x)**3)*atan(sqrt(tanh(x)))/tanh(x)**(sympy.S(3)/2) + sqrt(tanh(x)**3)*atanh(sqrt(tanh(x)))/tanh(x)**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=(a*tanh(x)**3)**(sympy.S(3)/2),
        variable=x,
        num_steps=8,
        integral=-2*a*sqrt(a*tanh(x)**3)*tanh(x)**2/7 - 2*a*sqrt(a*tanh(x)**3)/3 - a*sqrt(a*tanh(x)**3)*atan(sqrt(tanh(x)))/tanh(x)**(sympy.S(3)/2) + a*sqrt(a*tanh(x)**3)*atanh(sqrt(tanh(x)))/tanh(x)**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*tanh(x)**3),
        variable=x,
        num_steps=7,
        integral=-2*sqrt(a*tanh(x)**3)*coth(x) + sqrt(a*tanh(x)**3)*atan(sqrt(tanh(x)))/tanh(x)**(sympy.S(3)/2) + sqrt(a*tanh(x)**3)*atanh(sqrt(tanh(x)))/tanh(x)**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*tanh(x)**3),
        variable=x,
        num_steps=7,
        integral=-tanh(x)**(sympy.S(3)/2)*atan(sqrt(tanh(x)))/sqrt(a*tanh(x)**3) + tanh(x)**(sympy.S(3)/2)*atanh(sqrt(tanh(x)))/sqrt(a*tanh(x)**3) - 2*tanh(x)/sqrt(a*tanh(x)**3),
    ),
    RubiTestSuiteCase(
        integrand=(a*tanh(x)**4)**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=a*x*sqrt(a*tanh(x)**4)*coth(x)**2 - a*sqrt(a*tanh(x)**4)*tanh(x)**3/5 - a*sqrt(a*tanh(x)**4)*tanh(x)/3 - a*sqrt(a*tanh(x)**4)*coth(x),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a*tanh(x)**4),
        variable=x,
        num_steps=3,
        integral=x*sqrt(a*tanh(x)**4)*coth(x)**2 - sqrt(a*tanh(x)**4)*coth(x),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a*tanh(x)**4),
        variable=x,
        num_steps=3,
        integral=x*tanh(x)**2/sqrt(a*tanh(x)**4) - tanh(x)/sqrt(a*tanh(x)**4),
    ),
    RubiTestSuiteCase(
        integrand=(b*tanh(c + d*x)**m)**n,
        variable=x,
        num_steps=3,
        integral=(b*tanh(c + d*x)**m)**n*tanh(c + d*x)*hyper((1, m*n/2 + sympy.S.Half), (m*n/2 + sympy.S(3)/2,), tanh(c + d*x)**2)/(d*(m*n + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(a*tanh(c + d*x) + a)**5,
        variable=x,
        num_steps=5,
        integral=16*a**5*x + 16*a**5*log(cosh(c + d*x))/d - 8*a**5*tanh(c + d*x)/d - 2*a**2*(a*tanh(c + d*x) + a)**3/(3*d) - a*(a*tanh(c + d*x) + a)**4/(4*d) - 2*a*(a**2*tanh(c + d*x) + a**2)**2/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*tanh(c + d*x) + a)**4,
        variable=x,
        num_steps=4,
        integral=8*a**4*x + 8*a**4*log(cosh(c + d*x))/d - 4*a**4*tanh(c + d*x)/d - a*(a*tanh(c + d*x) + a)**3/(3*d) - (a**2*tanh(c + d*x) + a**2)**2/d,
    ),
    RubiTestSuiteCase(
        integrand=(a*tanh(c + d*x) + a)**3,
        variable=x,
        num_steps=3,
        integral=4*a**3*x + 4*a**3*log(cosh(c + d*x))/d - 2*a**3*tanh(c + d*x)/d - a*(a*tanh(c + d*x) + a)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a*tanh(c + d*x) + a)**2,
        variable=x,
        num_steps=2,
        integral=2*a**2*x + 2*a**2*log(cosh(c + d*x))/d - a**2*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=1/(a*tanh(c + d*x) + a),
        variable=x,
        num_steps=2,
        integral=-1/(2*d*(a*tanh(c + d*x) + a)) + x/(2*a),
    ),
    RubiTestSuiteCase(
        integrand=(a*tanh(c + d*x) + a)**(-2),
        variable=x,
        num_steps=3,
        integral=-1/(4*d*(a**2*tanh(c + d*x) + a**2)) - 1/(4*d*(a*tanh(c + d*x) + a)**2) + x/(4*a**2),
    ),
    RubiTestSuiteCase(
        integrand=(a*tanh(c + d*x) + a)**(-3),
        variable=x,
        num_steps=4,
        integral=-1/(8*d*(a**3*tanh(c + d*x) + a**3)) - 1/(6*d*(a*tanh(c + d*x) + a)**3) - 1/(8*a*d*(a*tanh(c + d*x) + a)**2) + x/(8*a**3),
    ),
    RubiTestSuiteCase(
        integrand=(a*tanh(c + d*x) + a)**(-4),
        variable=x,
        num_steps=5,
        integral=-1/(16*d*(a**4*tanh(c + d*x) + a**4)) - 1/(16*d*(a**2*tanh(c + d*x) + a**2)**2) - 1/(8*d*(a*tanh(c + d*x) + a)**4) - 1/(12*a*d*(a*tanh(c + d*x) + a)**3) + x/(16*a**4),
    ),
    RubiTestSuiteCase(
        integrand=(a*tanh(c + d*x) + a)**(-5),
        variable=x,
        num_steps=6,
        integral=-1/(32*d*(a**5*tanh(c + d*x) + a**5)) - 1/(10*d*(a*tanh(c + d*x) + a)**5) - 1/(32*a*d*(a**2*tanh(c + d*x) + a**2)**2) - 1/(16*a*d*(a*tanh(c + d*x) + a)**4) - 1/(24*a**2*d*(a*tanh(c + d*x) + a)**3) + x/(32*a**5),
    ),
    RubiTestSuiteCase(
        integrand=(tanh(x) + 1)**(sympy.S(7)/2),
        variable=x,
        num_steps=5,
        integral=-2*(tanh(x) + 1)**(sympy.S(5)/2)/5 - 4*(tanh(x) + 1)**(sympy.S(3)/2)/3 - 8*sqrt(tanh(x) + 1) + 8*sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=(tanh(x) + 1)**(sympy.S(5)/2),
        variable=x,
        num_steps=4,
        integral=-2*(tanh(x) + 1)**(sympy.S(3)/2)/3 - 4*sqrt(tanh(x) + 1) + 4*sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=(tanh(x) + 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=3,
        integral=-2*sqrt(tanh(x) + 1) + 2*sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(tanh(x) + 1),
        variable=x,
        num_steps=2,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(tanh(x) + 1),
        variable=x,
        num_steps=3,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2)/2 - 1/sqrt(tanh(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=(tanh(x) + 1)**(sympy.S(-3)/2),
        variable=x,
        num_steps=4,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2)/4 - 1/(2*sqrt(tanh(x) + 1)) - 1/(3*(tanh(x) + 1)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(tanh(x) + 1)**(sympy.S(-5)/2),
        variable=x,
        num_steps=5,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2)/8 - 1/(4*sqrt(tanh(x) + 1)) - 1/(6*(tanh(x) + 1)**(sympy.S(3)/2)) - 1/(5*(tanh(x) + 1)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x))**5,
        variable=x,
        num_steps=5,
        integral=-4*a*b**2*(a**2 + b**2)*tanh(c + d*x)/d - 2*a*b*(a + b*tanh(c + d*x))**3/(3*d) + a*x*(a**4 + 10*a**2*b**2 + 5*b**4) - b*(a + b*tanh(c + d*x))**4/(4*d) - b*(a + b*tanh(c + d*x))**2*(3*a**2 + b**2)/(2*d) + b*(5*a**4 + 10*a**2*b**2 + b**4)*log(cosh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x))**4,
        variable=x,
        num_steps=4,
        integral=-a*b*(a + b*tanh(c + d*x))**2/d + 4*a*b*(a**2 + b**2)*log(cosh(c + d*x))/d - b**2*(3*a**2 + b**2)*tanh(c + d*x)/d - b*(a + b*tanh(c + d*x))**3/(3*d) + x*(a**4 + 6*a**2*b**2 + b**4),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x))**3,
        variable=x,
        num_steps=3,
        integral=-2*a*b**2*tanh(c + d*x)/d + a*x*(a**2 + 3*b**2) - b*(a + b*tanh(c + d*x))**2/(2*d) + b*(3*a**2 + b**2)*log(cosh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x))**2,
        variable=x,
        num_steps=2,
        integral=2*a*b*log(cosh(c + d*x))/d - b**2*tanh(c + d*x)/d + x*(a**2 + b**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*tanh(c + d*x)),
        variable=x,
        num_steps=2,
        integral=a*x/(a**2 - b**2) - b*log(a*cosh(c + d*x) + b*sinh(c + d*x))/(d*(a**2 - b**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x))**(-2),
        variable=x,
        num_steps=3,
        integral=-2*a*b*log(a*cosh(c + d*x) + b*sinh(c + d*x))/(d*(a**2 - b**2)**2) + b/(d*(a + b*tanh(c + d*x))*(a**2 - b**2)) + x*(a**2 + b**2)/(a**2 - b**2)**2,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x))**(-3),
        variable=x,
        num_steps=4,
        integral=2*a*b/(d*(a + b*tanh(c + d*x))*(a**2 - b**2)**2) + a*x*(a**2 + 3*b**2)/(a**2 - b**2)**3 - b*(3*a**2 + b**2)*log(a*cosh(c + d*x) + b*sinh(c + d*x))/(d*(a**2 - b**2)**3) + b/(d*(a + b*tanh(c + d*x))**2*(2*a**2 - 2*b**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x))**(-4),
        variable=x,
        num_steps=5,
        integral=-4*a*b*(a**2 + b**2)*log(a*cosh(c + d*x) + b*sinh(c + d*x))/(d*(a**2 - b**2)**4) + a*b/(d*(a + b*tanh(c + d*x))**2*(a**2 - b**2)**2) + b*(3*a**2 + b**2)/(d*(a + b*tanh(c + d*x))*(a**2 - b**2)**3) + b/(d*(a + b*tanh(c + d*x))**3*(3*a**2 - 3*b**2)) + x*(a**4 + 6*a**2*b**2 + b**4)/(a**2 - b**2)**4,
    ),
    RubiTestSuiteCase(
        integrand=1/(6*tanh(c + d*x) + 4),
        variable=x,
        num_steps=2,
        integral=-x/5 + 3*log(3*sinh(c + d*x) + 2*cosh(c + d*x))/(10*d),
    ),
    RubiTestSuiteCase(
        integrand=1/(4 - 6*tanh(c + d*x)),
        variable=x,
        num_steps=2,
        integral=-x/5 - 3*log(-3*sinh(c + d*x) + 2*cosh(c + d*x))/(10*d),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*tanh(c + d*x)),
        variable=x,
        num_steps=5,
        integral=-sqrt(a - b)*atanh(sqrt(a + b*tanh(c + d*x))/sqrt(a - b))/d + sqrt(a + b)*atanh(sqrt(a + b*tanh(c + d*x))/sqrt(a + b))/d,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a + b*tanh(c + d*x)),
        variable=x,
        num_steps=5,
        integral=atanh(sqrt(a + b*tanh(c + d*x))/sqrt(a + b))/(d*sqrt(a + b)) - atanh(sqrt(a + b*tanh(c + d*x))/sqrt(a - b))/(d*sqrt(a - b)),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**4/(tanh(x) + 1),
        variable=x,
        num_steps=5,
        integral=x/16 - 3/(16*tanh(x) + 16) + 5/(32*(tanh(x) + 1)**2) - 1/(24*(tanh(x) + 1)**3) - 1/(8 - 8*tanh(x)) + 1/(32*(1 - tanh(x))**2),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**3/(tanh(x) + 1),
        variable=x,
        num_steps=9,
        integral=-sinh(x)**5/5 + cosh(x)**5/5 - cosh(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**2/(tanh(x) + 1),
        variable=x,
        num_steps=5,
        integral=-x/8 + 1/(4*tanh(x) + 4) - 1/(8*(tanh(x) + 1)**2) + 1/(8 - 8*tanh(x)),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)/(tanh(x) + 1),
        variable=x,
        num_steps=8,
        integral=-sinh(x)**3/3 + cosh(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)/(tanh(x) + 1),
        variable=x,
        num_steps=8,
        integral=-sinh(x) + cosh(x) - atanh(cosh(x)),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**2/(tanh(x) + 1),
        variable=x,
        num_steps=3,
        integral=log(tanh(x) + 1) - log(tanh(x)) - coth(x),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**3/(tanh(x) + 1),
        variable=x,
        num_steps=8,
        integral=-coth(x)*csch(x)/2 - atanh(cosh(x))/2 + csch(x),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**4/(tanh(x) + 1),
        variable=x,
        num_steps=4,
        integral=-coth(x)**3/3 + coth(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**5/(tanh(x) + 1),
        variable=x,
        num_steps=9,
        integral=-coth(x)*csch(x)**3/4 - coth(x)*csch(x)/8 + atanh(cosh(x))/8 + csch(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**6/(tanh(x) + 1),
        variable=x,
        num_steps=4,
        integral=-coth(x)**5/5 + coth(x)**4/4 + coth(x)**3/3 - coth(x)**2/2,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**7/(tanh(x) + 1),
        variable=x,
        num_steps=10,
        integral=-coth(x)*csch(x)**5/6 - coth(x)*csch(x)**3/24 + coth(x)*csch(x)/16 - atanh(cosh(x))/16 + csch(x)**5/5,
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**4/(a + b*tanh(x)),
        variable=x,
        num_steps=5,
        integral=-a**4*b*log(a + b*tanh(x))/(a**2 - b**2)**3 - a*(3*a + b)*log(1 - tanh(x))/(16*(a + b)**3) + a*(3*a - b)*log(tanh(x) + 1)/(16*(a - b)**3) - (-a*tanh(x) + b)*cosh(x)**4/(4*a**2 - 4*b**2) + (-a*(5*a**2 - b**2)*tanh(x) + 4*b*(2*a**2 - b**2))*cosh(x)**2/(8*(a**2 - b**2)**2),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**3/(a + b*tanh(x)),
        variable=x,
        num_steps=10,
        integral=-a**3*b*atan((a*sinh(x) + b*cosh(x))/sqrt(a**2 - b**2))/(a**2 - b**2)**(sympy.S(5)/2) + a**2*b*sinh(x)/(a**2 - b**2)**2 - a*b**2*cosh(x)/(a**2 - b**2)**2 + a*cosh(x)**3/(3*a**2 - 3*b**2) - a*cosh(x)/(a**2 - b**2) - b*sinh(x)**3/(3*a**2 - 3*b**2),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)**2/(a + b*tanh(x)),
        variable=x,
        num_steps=4,
        integral=a**2*b*log(a + b*tanh(x))/(a**2 - b**2)**2 + a*log(1 - tanh(x))/(4*(a + b)**2) - a*log(tanh(x) + 1)/(4*(a - b)**2) - (-a*tanh(x) + b)*cosh(x)**2/(2*a**2 - 2*b**2),
    ),
    RubiTestSuiteCase(
        integrand=sinh(x)/(a + b*tanh(x)),
        variable=x,
        num_steps=6,
        integral=a*b*atan((a*sinh(x) + b*cosh(x))/sqrt(a**2 - b**2))/(a**2 - b**2)**(sympy.S(3)/2) + a*cosh(x)/(a**2 - b**2) - b*sinh(x)/(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=csch(x)/(a + b*tanh(x)),
        variable=x,
        num_steps=6,
        integral=-b*atan((a*sinh(x) + b*cosh(x))/sqrt(a**2 - b**2))/(a*sqrt(a**2 - b**2)) - atanh(cosh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**2/(a + b*tanh(x)),
        variable=x,
        num_steps=3,
        integral=-coth(x)/a + b*log(a + b*tanh(x))/a**2 - b*log(tanh(x))/a**2,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**3/(a + b*tanh(x)),
        variable=x,
        num_steps=15,
        integral=-coth(x)*csch(x)/(2*a) + atanh(cosh(x))/(2*a) + b*csch(x)/a**2 - b**2*atanh(cosh(x))/a**3 + b*sqrt(a**2 - b**2)*atan((a*sinh(x) + b*cosh(x))/sqrt(a**2 - b**2))/a**3,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**4/(a + b*tanh(x)),
        variable=x,
        num_steps=3,
        integral=-coth(x)**3/(3*a) + b*coth(x)**2/(2*a**2) + (a**2 - b**2)*coth(x)/a**3 - b*(a**2 - b**2)*log(a + b*tanh(x))/a**4 + b*(a**2 - b**2)*log(tanh(x))/a**4,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**5/(a + b*tanh(x)),
        variable=x,
        num_steps=29,
        integral=-coth(x)*csch(x)**3/(4*a) + 3*coth(x)*csch(x)/(8*a) - 3*atanh(cosh(x))/(8*a) - b*atan(sinh(x))/a**2 + b*csch(x)**3/(3*a**2) - b*csch(x)/a**2 + 3*b**2*atanh(cosh(x))/(2*a**3) - b**2*csch(x)**2*sech(x)/(2*a**3) - 3*b**2*sech(x)/(2*a**3) - b**3*tanh(x)*sech(x)/(2*a**4) + b**3*atan(sinh(x))/a**4 - b**3*csch(x)*sech(x)**2/(2*a**4) + 3*b**3*csch(x)/(2*a**4) + b*(a**2 - b**2)*atan(sinh(x))/a**4 - b**4*atanh(cosh(x))/a**5 + b**4*sech(x)/a**5 + b**2*(a**2 - b**2)*sech(x)/a**5 - b*(a**2 - b**2)**(sympy.S(3)/2)*atan((a*sinh(x) + b*cosh(x))/sqrt(a**2 - b**2))/a**5,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)**6/(a + b*tanh(x)),
        variable=x,
        num_steps=3,
        integral=-coth(x)**5/(5*a) + b*coth(x)**4/(4*a**2) + (2*a**2 - b**2)*coth(x)**3/(3*a**3) - b*(2*a**2 - b**2)*coth(x)**2/(2*a**4) - (a**2 - b**2)**2*coth(x)/a**5 + b*(a**2 - b**2)**2*log(a + b*tanh(x))/a**6 - b*(a**2 - b**2)**2*log(tanh(x))/a**6,
    ),
    RubiTestSuiteCase(
        integrand=csch(x)/(tanh(x) + I),
        variable=x,
        num_steps=6,
        integral=-sqrt(2)*I*atanh(sqrt(2)*(I*sinh(x) + cosh(x))/2)/2 + I*atanh(cosh(x)),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**4/(tanh(x) + 1),
        variable=x,
        num_steps=4,
        integral=5*x/16 - 3/(16*tanh(x) + 16) - 3/(32*(tanh(x) + 1)**2) - 1/(24*(tanh(x) + 1)**3) + 1/(8 - 8*tanh(x)) + 1/(32*(1 - tanh(x))**2),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**3/(tanh(x) + 1),
        variable=x,
        num_steps=3,
        integral=4*sinh(x)**3/15 + 4*sinh(x)/5 - cosh(x)**3/(5*tanh(x) + 5),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**2/(tanh(x) + 1),
        variable=x,
        num_steps=4,
        integral=3*x/8 - 1/(4*tanh(x) + 4) - 1/(8*(tanh(x) + 1)**2) + 1/(8 - 8*tanh(x)),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)/(tanh(x) + 1),
        variable=x,
        num_steps=2,
        integral=2*sinh(x)/3 - cosh(x)/(3*tanh(x) + 3),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)/(tanh(x) + 1),
        variable=x,
        num_steps=1,
        integral=-sech(x)/(tanh(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**2/(tanh(x) + 1),
        variable=x,
        num_steps=2,
        integral=log(tanh(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**3/(tanh(x) + 1),
        variable=x,
        num_steps=2,
        integral=atan(sinh(x)) + sech(x),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**4/(tanh(x) + 1),
        variable=x,
        num_steps=2,
        integral=-tanh(x)**2/2 + tanh(x),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**5/(tanh(x) + 1),
        variable=x,
        num_steps=3,
        integral=tanh(x)*sech(x)/2 + atan(sinh(x))/2 + sech(x)**3/3,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**6/(tanh(x) + 1),
        variable=x,
        num_steps=3,
        integral=(1 - tanh(x))**4/4 - 2*(1 - tanh(x))**3/3,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**7/(tanh(x) + 1),
        variable=x,
        num_steps=4,
        integral=tanh(x)*sech(x)**3/4 + 3*tanh(x)*sech(x)/8 + 3*atan(sinh(x))/8 + sech(x)**5/5,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**8/(a + b*tanh(x)),
        variable=x,
        num_steps=3,
        integral=a*tanh(x)**5/(5*b**2) + a*(a**2 - 3*b**2)*tanh(x)**3/(3*b**4) + a*(a**4 - 3*a**2*b**2 + 3*b**4)*tanh(x)/b**6 - tanh(x)**6/(6*b) - (a**2 - 3*b**2)*tanh(x)**4/(4*b**3) - (a**4 - 3*a**2*b**2 + 3*b**4)*tanh(x)**2/(2*b**5) - (a**2 - b**2)**3*log(a + b*tanh(x))/b**7,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**6/(a + b*tanh(x)),
        variable=x,
        num_steps=3,
        integral=-a*tanh(x)**3/(3*b**2) - a*(a**2 - 2*b**2)*tanh(x)/b**4 + tanh(x)**4/(4*b) + (a**2 - 2*b**2)*tanh(x)**2/(2*b**3) + (a**2 - b**2)**2*log(a + b*tanh(x))/b**5,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**4/(a + b*tanh(x)),
        variable=x,
        num_steps=3,
        integral=a*tanh(x)/b**2 - tanh(x)**2/(2*b) - (a**2 - b**2)*log(a + b*tanh(x))/b**3,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**2/(a + b*tanh(x)),
        variable=x,
        num_steps=2,
        integral=log(a + b*tanh(x))/b,
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*tanh(x)),
        variable=x,
        num_steps=2,
        integral=a*x/(a**2 - b**2) - b*log(a*cosh(x) + b*sinh(x))/(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**2/(a + b*tanh(x)),
        variable=x,
        num_steps=4,
        integral=b**3*log(a + b*tanh(x))/(a**2 - b**2)**2 + (a - 2*b)*log(tanh(x) + 1)/(4*(a - b)**2) - (-a*tanh(x) + b)*cosh(x)**2/(2*a**2 - 2*b**2) - (a + 2*b)*log(1 - tanh(x))/(4*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**4/(a + b*tanh(x)),
        variable=x,
        num_steps=5,
        integral=-b**5*log(a + b*tanh(x))/(a**2 - b**2)**3 - (-a*tanh(x) + b)*cosh(x)**4/(4*a**2 - 4*b**2) + (-a*b**2*(-3*a**2/b**2 + 7)*tanh(x) + 4*b**3)*cosh(x)**2/(8*(a**2 - b**2)**2) - (3*a**2 + 9*a*b + 8*b**2)*log(1 - tanh(x))/(16*(a + b)**3) + (3*a**2 - 9*a*b + 8*b**2)*log(tanh(x) + 1)/(16*(a - b)**3),
    ),
    RubiTestSuiteCase(
        integrand=sech(x)**3/(a + b*tanh(x)),
        variable=x,
        num_steps=5,
        integral=a*atan(sinh(x))/b**2 + sech(x)/b - sqrt(a**2 - b**2)*atan((a*tanh(x) + b)*cosh(x)/sqrt(a**2 - b**2))/b**2,
    ),
    RubiTestSuiteCase(
        integrand=sech(x)/(a + b*tanh(x)),
        variable=x,
        num_steps=2,
        integral=atan((a*tanh(x) + b)*cosh(x)/sqrt(a**2 - b**2))/sqrt(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)/(a + b*tanh(x)),
        variable=x,
        num_steps=5,
        integral=a*sinh(x)/(a**2 - b**2) - b**2*atan((a*tanh(x) + b)*cosh(x)/sqrt(a**2 - b**2))/(a**2 - b**2)**(sympy.S(3)/2) - b*cosh(x)/(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=cosh(x)**3/(a + b*tanh(x)),
        variable=x,
        num_steps=9,
        integral=-a*b**2*sinh(x)/(a**2 - b**2)**2 + a*sinh(x)**3/(3*a**2 - 3*b**2) + a*sinh(x)/(a**2 - b**2) + b**4*atan((a*tanh(x) + b)*cosh(x)/sqrt(a**2 - b**2))/(a**2 - b**2)**(sympy.S(5)/2) + b**3*cosh(x)/(a**2 - b**2)**2 - b*cosh(x)**3/(3*a**2 - 3*b**2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**5/(tanh(x) + 1),
        variable=x,
        num_steps=5,
        integral=5*x/2 - 2*log(cosh(x)) - 5*tanh(x)**3/6 + tanh(x)**2 - 5*tanh(x)/2 + tanh(x)**4/(2*tanh(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**4/(tanh(x) + 1),
        variable=x,
        num_steps=4,
        integral=-3*x/2 + 2*log(cosh(x)) - tanh(x)**2 + 3*tanh(x)/2 + tanh(x)**3/(2*tanh(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**3/(tanh(x) + 1),
        variable=x,
        num_steps=3,
        integral=3*x/2 - log(cosh(x)) - 3*tanh(x)/2 + tanh(x)**2/(2*tanh(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**2/(tanh(x) + 1),
        variable=x,
        num_steps=3,
        integral=-x/2 + log(cosh(x)) - 1/(2*tanh(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/(tanh(x) + 1),
        variable=x,
        num_steps=2,
        integral=x/2 + 1/(2*tanh(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=1/(tanh(x) + 1),
        variable=x,
        num_steps=2,
        integral=x/2 - 1/(2*tanh(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/(tanh(x) + 1),
        variable=x,
        num_steps=4,
        integral=-x/2 + log(sinh(x)) + 1/(2*tanh(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**2/(tanh(x) + 1),
        variable=x,
        num_steps=4,
        integral=3*x/2 - log(sinh(x)) - 3*coth(x)/2 + coth(x)/(2*tanh(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**3/(tanh(x) + 1),
        variable=x,
        num_steps=5,
        integral=-3*x/2 + 2*log(sinh(x)) - coth(x)**2 + 3*coth(x)/2 + coth(x)**2/(2*tanh(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**4/(tanh(x) + 1),
        variable=x,
        num_steps=6,
        integral=5*x/2 - 2*log(sinh(x)) - 5*coth(x)**3/6 + coth(x)**2 - 5*coth(x)/2 + coth(x)**3/(2*tanh(x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=(tanh(x) + 1)**(sympy.S(3)/2)*tanh(x),
        variable=x,
        num_steps=4,
        integral=-2*(tanh(x) + 1)**(sympy.S(3)/2)/3 - 2*sqrt(tanh(x) + 1) + 2*sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(tanh(x) + 1)*tanh(x),
        variable=x,
        num_steps=3,
        integral=-2*sqrt(tanh(x) + 1) + sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/sqrt(tanh(x) + 1),
        variable=x,
        num_steps=3,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2)/2 + 1/sqrt(tanh(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/(tanh(x) + 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2)/4 - 1/(2*sqrt(tanh(x) + 1)) + 1/(3*(tanh(x) + 1)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(tanh(x) + 1)**(sympy.S(3)/2)*tanh(x)**2,
        variable=x,
        num_steps=4,
        integral=-2*(tanh(x) + 1)**(sympy.S(5)/2)/5 - 2*sqrt(tanh(x) + 1) + 2*sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(tanh(x) + 1)*tanh(x)**2,
        variable=x,
        num_steps=3,
        integral=-2*(tanh(x) + 1)**(sympy.S(3)/2)/3 + sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**2/sqrt(tanh(x) + 1),
        variable=x,
        num_steps=4,
        integral=-2*sqrt(tanh(x) + 1) + sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2)/2 - 1/sqrt(tanh(x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**2/(tanh(x) + 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=sqrt(2)*atanh(sqrt(2)*sqrt(tanh(x) + 1)/2)/4 + 3/(2*sqrt(tanh(x) + 1)) - 1/(3*(tanh(x) + 1)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**5/(a + b*tanh(x)),
        variable=x,
        num_steps=7,
        integral=a**5*log(a + b*tanh(x))/(b**4*(a**2 - b**2)) + a*log(cosh(x))/(a**2 - b**2) + a*tanh(x)**2/(2*b**2) - b*x/(a**2 - b**2) - tanh(x)**3/(3*b) - (a**2 + b**2)*tanh(x)/b**3,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**4/(a + b*tanh(x)),
        variable=x,
        num_steps=6,
        integral=-a**4*log(a + b*tanh(x))/(b**3*(a**2 - b**2)) + a*x/(a**2 - b**2) + a*tanh(x)/b**2 - b*log(cosh(x))/(a**2 - b**2) - tanh(x)**2/(2*b),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**3/(a + b*tanh(x)),
        variable=x,
        num_steps=5,
        integral=a**3*log(a + b*tanh(x))/(b**2*(a**2 - b**2)) + a*log(cosh(x))/(a**2 - b**2) - b*x/(a**2 - b**2) - tanh(x)/b,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**2/(a + b*tanh(x)),
        variable=x,
        num_steps=4,
        integral=a**3*x/(b**2*(a**2 - b**2)) - a**2*log(a*cosh(x) + b*sinh(x))/(b*(a**2 - b**2)) - a*x/b**2 + log(cosh(x))/b,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/(a + b*tanh(x)),
        variable=x,
        num_steps=2,
        integral=a*log(a*cosh(x) + b*sinh(x))/(a**2 - b**2) - b*x/(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*tanh(x)),
        variable=x,
        num_steps=2,
        integral=a*x/(a**2 - b**2) - b*log(a*cosh(x) + b*sinh(x))/(a**2 - b**2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/(a + b*tanh(x)),
        variable=x,
        num_steps=3,
        integral=-b*x/(a**2 - b**2) + b**2*log(a*cosh(x) + b*sinh(x))/(a*(a**2 - b**2)) + log(sinh(x))/a,
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**2/(a + b*tanh(x)),
        variable=x,
        num_steps=4,
        integral=a*x/(a**2 - b**2) - coth(x)/a - b**3*log(a*cosh(x) + b*sinh(x))/(a**2*(a**2 - b**2)) - b*log(sinh(x))/a**2,
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**3/(a + b*tanh(x)),
        variable=x,
        num_steps=5,
        integral=-b*x/(a**2 - b**2) - coth(x)**2/(2*a) + b*coth(x)/a**2 + b**4*log(a*cosh(x) + b*sinh(x))/(a**3*(a**2 - b**2)) + (a**2 + b**2)*log(sinh(x))/a**3,
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**4/(a + b*tanh(x)),
        variable=x,
        num_steps=6,
        integral=a*x/(a**2 - b**2) - coth(x)**3/(3*a) + b*coth(x)**2/(2*a**2) - (a**2 + b**2)*coth(x)/a**3 - b**5*log(a*cosh(x) + b*sinh(x))/(a**4*(a**2 - b**2)) - b*(a**2 + b**2)*log(sinh(x))/a**4,
    ),
    RubiTestSuiteCase(
        integrand=x*sech(x)**2/(a + b*tanh(x))**2,
        variable=x,
        num_steps=3,
        integral=a*x/(b*(a**2 - b**2)) - log(a*cosh(x) + b*sinh(x))/(a**2 - b**2) - x/(b*(a + b*tanh(x))),
    ),
    RubiTestSuiteCase(
        integrand=x*sech(c + d*x)**2/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=9,
        integral=(((x * sympy.log((Integer(1) + (((Symbol('a') + Symbol('b')) * (sympy.E)**(((Integer(2) * Symbol('c')) + (Integer(2) * Symbol('d') * x)))) * ((Symbol('a') + (Integer(-1) * (Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')))) + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')) * Symbol('d')))**(Integer(-1))) + (Integer(-1) * ((x * sympy.log((Integer(1) + (((Symbol('a') + Symbol('b')) * (sympy.E)**(((Integer(2) * Symbol('c')) + (Integer(2) * Symbol('d') * x)))) * ((Symbol('a') + (Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b'))) + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')) * Symbol('d')))**(Integer(-1)))) + (sympy.Function('PolyLog')(Integer(2), (Integer(-1) * (((Symbol('a') + Symbol('b')) * (sympy.E)**(((Integer(2) * Symbol('c')) + (Integer(2) * Symbol('d') * x)))) * ((Symbol('a') + (Integer(-1) * (Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')))) + (Integer(-1) * Symbol('b'))))**(Integer(-1))))) * ((Integer(4) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')) * (Symbol('d'))**(Integer(2))))**(Integer(-1))) + (Integer(-1) * (sympy.Function('PolyLog')(Integer(2), (Integer(-1) * (((Symbol('a') + Symbol('b')) * (sympy.E)**(((Integer(2) * Symbol('c')) + (Integer(2) * Symbol('d') * x)))) * ((Symbol('a') + (Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b'))) + (Integer(-1) * Symbol('b'))))**(Integer(-1))))) * ((Integer(4) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')) * (Symbol('d'))**(Integer(2))))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=x**2*sech(c + d*x)**2/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=11,
        integral=((((x)**(Integer(2)) * sympy.log((Integer(1) + (((Symbol('a') + Symbol('b')) * (sympy.E)**(((Integer(2) * Symbol('c')) + (Integer(2) * Symbol('d') * x)))) * ((Symbol('a') + (Integer(-1) * (Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')))) + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')) * Symbol('d')))**(Integer(-1))) + (Integer(-1) * (((x)**(Integer(2)) * sympy.log((Integer(1) + (((Symbol('a') + Symbol('b')) * (sympy.E)**(((Integer(2) * Symbol('c')) + (Integer(2) * Symbol('d') * x)))) * ((Symbol('a') + (Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b'))) + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')) * Symbol('d')))**(Integer(-1)))) + ((x * sympy.Function('PolyLog')(Integer(2), (Integer(-1) * (((Symbol('a') + Symbol('b')) * (sympy.E)**(((Integer(2) * Symbol('c')) + (Integer(2) * Symbol('d') * x)))) * ((Symbol('a') + (Integer(-1) * (Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')))) + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')) * (Symbol('d'))**(Integer(2))))**(Integer(-1))) + (Integer(-1) * ((x * sympy.Function('PolyLog')(Integer(2), (Integer(-1) * (((Symbol('a') + Symbol('b')) * (sympy.E)**(((Integer(2) * Symbol('c')) + (Integer(2) * Symbol('d') * x)))) * ((Symbol('a') + (Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b'))) + (Integer(-1) * Symbol('b'))))**(Integer(-1)))))) * ((Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')) * (Symbol('d'))**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * (sympy.Function('PolyLog')(Integer(3), (Integer(-1) * (((Symbol('a') + Symbol('b')) * (sympy.E)**(((Integer(2) * Symbol('c')) + (Integer(2) * Symbol('d') * x)))) * ((Symbol('a') + (Integer(-1) * (Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')))) + (Integer(-1) * Symbol('b'))))**(Integer(-1))))) * ((Integer(4) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')) * (Symbol('d'))**(Integer(3))))**(Integer(-1)))) + (sympy.Function('PolyLog')(Integer(3), (Integer(-1) * (((Symbol('a') + Symbol('b')) * (sympy.E)**(((Integer(2) * Symbol('c')) + (Integer(2) * Symbol('d') * x)))) * ((Symbol('a') + (Integer(2) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b'))) + (Integer(-1) * Symbol('b'))))**(Integer(-1))))) * ((Integer(4) * sympy.sqrt((Integer(-1) * Symbol('a'))) * sympy.sqrt(Symbol('b')) * (Symbol('d'))**(Integer(3))))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=tanh(a + b*log(c*x**n))/x,
        variable=x,
        num_steps=2,
        integral=log(cosh(a + b*log(c*x**n)))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=tanh(a + b*log(c*x**n))**2/x,
        variable=x,
        num_steps=3,
        integral=log(x) - tanh(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=tanh(a + b*log(c*x**n))**3/x,
        variable=x,
        num_steps=3,
        integral=log(cosh(a + b*log(c*x**n)))/(b*n) - tanh(a + b*log(c*x**n))**2/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=tanh(a + b*log(c*x**n))**4/x,
        variable=x,
        num_steps=4,
        integral=log(x) - tanh(a + b*log(c*x**n))**3/(3*b*n) - tanh(a + b*log(c*x**n))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=tanh(a + b*log(c*x**n))**5/x,
        variable=x,
        num_steps=4,
        integral=log(cosh(a + b*log(c*x**n)))/(b*n) - tanh(a + b*log(c*x**n))**4/(4*b*n) - tanh(a + b*log(c*x**n))**2/(2*b*n),
    ),
    RubiTestSuiteCase(
        integrand=tanh(a + b*log(c*x**n))**(sympy.S(5)/2)/x,
        variable=x,
        num_steps=7,
        integral=-2*tanh(a + b*log(c*x**n))**(sympy.S(3)/2)/(3*b*n) - atan(sqrt(tanh(a + b*log(c*x**n))))/(b*n) + atanh(sqrt(tanh(a + b*log(c*x**n))))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=tanh(a + b*log(c*x**n))**(sympy.S(3)/2)/x,
        variable=x,
        num_steps=7,
        integral=-2*sqrt(tanh(a + b*log(c*x**n)))/(b*n) + atan(sqrt(tanh(a + b*log(c*x**n))))/(b*n) + atanh(sqrt(tanh(a + b*log(c*x**n))))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(tanh(a + b*log(c*x**n)))/x,
        variable=x,
        num_steps=6,
        integral=-atan(sqrt(tanh(a + b*log(c*x**n))))/(b*n) + atanh(sqrt(tanh(a + b*log(c*x**n))))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*sqrt(tanh(a + b*log(c*x**n)))),
        variable=x,
        num_steps=6,
        integral=atan(sqrt(tanh(a + b*log(c*x**n))))/(b*n) + atanh(sqrt(tanh(a + b*log(c*x**n))))/(b*n),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*tanh(a + b*log(c*x**n))**(sympy.S(3)/2)),
        variable=x,
        num_steps=7,
        integral=-atan(sqrt(tanh(a + b*log(c*x**n))))/(b*n) + atanh(sqrt(tanh(a + b*log(c*x**n))))/(b*n) - 2/(b*n*sqrt(tanh(a + b*log(c*x**n)))),
    ),
    RubiTestSuiteCase(
        integrand=1/(x*tanh(a + b*log(c*x**n))**(sympy.S(5)/2)),
        variable=x,
        num_steps=7,
        integral=atan(sqrt(tanh(a + b*log(c*x**n))))/(b*n) + atanh(sqrt(tanh(a + b*log(c*x**n))))/(b*n) - 2/(3*b*n*tanh(a + b*log(c*x**n))**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**5/sqrt(a + b*tanh(x)**2 + c*tanh(x)**4),
        variable=x,
        num_steps=8,
        integral=atanh((2*a + b + (b + 2*c)*tanh(x)**2)/(2*sqrt(a + b + c)*sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)))/(2*sqrt(a + b + c)) - sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)/(2*c) + (b - 2*c)*atanh((b + 2*c*tanh(x)**2)/(2*sqrt(c)*sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)))/(4*c**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**3/sqrt(a + b*tanh(x)**2 + c*tanh(x)**4),
        variable=x,
        num_steps=7,
        integral=atanh((2*a + b + (b + 2*c)*tanh(x)**2)/(2*sqrt(a + b + c)*sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)))/(2*sqrt(a + b + c)) - atanh((b + 2*c*tanh(x)**2)/(2*sqrt(c)*sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)))/(2*sqrt(c)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/sqrt(a + b*tanh(x)**2 + c*tanh(x)**4),
        variable=x,
        num_steps=4,
        integral=atanh((2*a + b + (b + 2*c)*tanh(x)**2)/(2*sqrt(a + b + c)*sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)))/(2*sqrt(a + b + c)),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/sqrt(a + b*tanh(x)**2 + c*tanh(x)**4),
        variable=x,
        num_steps=8,
        integral=atanh((2*a + b + (b + 2*c)*tanh(x)**2)/(2*sqrt(a + b + c)*sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)))/(2*sqrt(a + b + c)) - atanh((2*a + b*tanh(x)**2)/(2*sqrt(a)*sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)))/(2*sqrt(a)),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**3/sqrt(a + b*tanh(x)**2 + c*tanh(x)**4),
        variable=x,
        num_steps=11,
        integral=atanh((2*a + b + (b + 2*c)*tanh(x)**2)/(2*sqrt(a + b + c)*sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)))/(2*sqrt(a + b + c)) - sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)*coth(x)**2/(2*a) - atanh((2*a + b*tanh(x)**2)/(2*sqrt(a)*sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)))/(2*sqrt(a)) + b*atanh((2*a + b*tanh(x)**2)/(2*sqrt(a)*sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)))/(4*a**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)*tanh(x),
        variable=x,
        num_steps=8,
        integral=sqrt(a + b + c)*atanh((2*a + b + (b + 2*c)*tanh(x)**2)/(2*sqrt(a + b + c)*sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)))/2 - sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)/2 - (b + 2*c)*atanh((b + 2*c*tanh(x)**2)/(2*sqrt(c)*sqrt(a + b*tanh(x)**2 + c*tanh(x)**4)))/(4*sqrt(c)),
    ),
    RubiTestSuiteCase(
        integrand=exp(a + b*x)*tanh(a + b*x)**4,
        variable=x,
        num_steps=7,
        integral=exp(a + b*x)/b - 3*atan(exp(a + b*x))/b + 5*exp(a + b*x)/(b*(exp(2*a + 2*b*x) + 1)) - 14*exp(a + b*x)/(3*b*(exp(2*a + 2*b*x) + 1)**2) + 8*exp(a + b*x)/(3*b*(exp(2*a + 2*b*x) + 1)**3),
    ),
    RubiTestSuiteCase(
        integrand=exp(a + b*x)*tanh(a + b*x)**3,
        variable=x,
        num_steps=7,
        integral=exp(a + b*x)/b - 3*atan(exp(a + b*x))/b + 3*exp(a + b*x)/(b*(exp(2*a + 2*b*x) + 1)) - 2*exp(a + b*x)/(b*(exp(2*a + 2*b*x) + 1)**2),
    ),
    RubiTestSuiteCase(
        integrand=exp(a + b*x)*tanh(a + b*x)**2,
        variable=x,
        num_steps=5,
        integral=exp(a + b*x)/b - 2*atan(exp(a + b*x))/b + 2*exp(a + b*x)/(b*(exp(2*a + 2*b*x) + 1)),
    ),
    RubiTestSuiteCase(
        integrand=exp(a + b*x)*tanh(a + b*x),
        variable=x,
        num_steps=3,
        integral=exp(a + b*x)/b - 2*atan(exp(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=exp(a + b*x)*coth(a + b*x),
        variable=x,
        num_steps=3,
        integral=exp(a + b*x)/b - 2*atanh(exp(a + b*x))/b,
    ),
    RubiTestSuiteCase(
        integrand=exp(a + b*x)*coth(a + b*x)**2,
        variable=x,
        num_steps=5,
        integral=exp(a + b*x)/b - 2*atanh(exp(a + b*x))/b + 2*exp(a + b*x)/(b*(1 - exp(2*a + 2*b*x))),
    ),
    RubiTestSuiteCase(
        integrand=exp(a + b*x)*coth(a + b*x)**3,
        variable=x,
        num_steps=7,
        integral=exp(a + b*x)/b - 3*atanh(exp(a + b*x))/b + 3*exp(a + b*x)/(b*(1 - exp(2*a + 2*b*x))) - 2*exp(a + b*x)/(b*(1 - exp(2*a + 2*b*x))**2),
    ),
    RubiTestSuiteCase(
        integrand=exp(a + b*x)*coth(a + b*x)**4,
        variable=x,
        num_steps=7,
        integral=exp(a + b*x)/b - 3*atanh(exp(a + b*x))/b + 5*exp(a + b*x)/(b*(1 - exp(2*a + 2*b*x))) - 14*exp(a + b*x)/(3*b*(1 - exp(2*a + 2*b*x))**2) + 8*exp(a + b*x)/(3*b*(1 - exp(2*a + 2*b*x))**3),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*tanh(2*x)**2,
        variable=x,
        num_steps=13,
        integral=exp(x) + sqrt(2)*log(exp(2*x) - sqrt(2)*exp(x) + 1)/8 - sqrt(2)*log(exp(2*x) + sqrt(2)*exp(x) + 1)/8 - sqrt(2)*atan(sqrt(2)*exp(x) - 1)/4 - sqrt(2)*atan(sqrt(2)*exp(x) + 1)/4 + exp(x)/(exp(4*x) + 1),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*tanh(2*x),
        variable=x,
        num_steps=11,
        integral=exp(x) + sqrt(2)*log(exp(2*x) - sqrt(2)*exp(x) + 1)/4 - sqrt(2)*log(exp(2*x) + sqrt(2)*exp(x) + 1)/4 - sqrt(2)*atan(sqrt(2)*exp(x) - 1)/2 - sqrt(2)*atan(sqrt(2)*exp(x) + 1)/2,
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*coth(2*x),
        variable=x,
        num_steps=5,
        integral=exp(x) - atan(exp(x)) - atanh(exp(x)),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*coth(2*x)**2,
        variable=x,
        num_steps=7,
        integral=exp(x) - atan(exp(x))/2 - atanh(exp(x))/2 + exp(x)/(1 - exp(4*x)),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*tanh(3*x)**2,
        variable=x,
        num_steps=14,
        integral=exp(x) + sqrt(3)*log(exp(2*x) - sqrt(3)*exp(x) + 1)/18 - sqrt(3)*log(exp(2*x) + sqrt(3)*exp(x) + 1)/18 - atan(2*exp(x) - sqrt(3))/9 - atan(2*exp(x) + sqrt(3))/9 - 2*atan(exp(x))/9 + 2*exp(x)/(3*exp(6*x) + 3),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*tanh(3*x),
        variable=x,
        num_steps=12,
        integral=exp(x) + sqrt(3)*log(exp(2*x) - sqrt(3)*exp(x) + 1)/6 - sqrt(3)*log(exp(2*x) + sqrt(3)*exp(x) + 1)/6 - atan(2*exp(x) - sqrt(3))/3 - atan(2*exp(x) + sqrt(3))/3 - 2*atan(exp(x))/3,
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*coth(3*x),
        variable=x,
        num_steps=12,
        integral=exp(x) + log(exp(2*x) - exp(x) + 1)/6 - log(exp(2*x) + exp(x) + 1)/6 + sqrt(3)*atan(sqrt(3)*(1 - 2*exp(x))/3)/3 - sqrt(3)*atan(sqrt(3)*(2*exp(x) + 1)/3)/3 - 2*atanh(exp(x))/3,
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*coth(3*x)**2,
        variable=x,
        num_steps=14,
        integral=exp(x) + log(exp(2*x) - exp(x) + 1)/18 - log(exp(2*x) + exp(x) + 1)/18 + sqrt(3)*atan(sqrt(3)*(1 - 2*exp(x))/3)/9 - sqrt(3)*atan(sqrt(3)*(2*exp(x) + 1)/3)/9 - 2*atanh(exp(x))/9 + 2*exp(x)/(3 - 3*exp(6*x)),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*tanh(4*x)**2,
        variable=x,
        num_steps=23,
        integral=exp(x) + sqrt(2 - sqrt(2))*log(exp(2*x) - sqrt(2 - sqrt(2))*exp(x) + 1)/32 - sqrt(2 - sqrt(2))*log(exp(2*x) + sqrt(2 - sqrt(2))*exp(x) + 1)/32 + sqrt(sqrt(2) + 2)*log(exp(2*x) - sqrt(sqrt(2) + 2)*exp(x) + 1)/32 - sqrt(sqrt(2) + 2)*log(exp(2*x) + sqrt(sqrt(2) + 2)*exp(x) + 1)/32 + atan((-2*exp(x) + sqrt(sqrt(2) + 2))/sqrt(2 - sqrt(2)))/(8*sqrt(2*sqrt(2) + 4)) - atan((2*exp(x) + sqrt(sqrt(2) + 2))/sqrt(2 - sqrt(2)))/(8*sqrt(2*sqrt(2) + 4)) + atan((-2*exp(x) + sqrt(2 - sqrt(2)))/sqrt(sqrt(2) + 2))/(8*sqrt(4 - 2*sqrt(2))) - atan((2*exp(x) + sqrt(2 - sqrt(2)))/sqrt(sqrt(2) + 2))/(8*sqrt(4 - 2*sqrt(2))) + exp(x)/(2*exp(8*x) + 2),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*tanh(4*x),
        variable=x,
        num_steps=21,
        integral=exp(x) + sqrt(2 - sqrt(2))*log(exp(2*x) - sqrt(2 - sqrt(2))*exp(x) + 1)/8 - sqrt(2 - sqrt(2))*log(exp(2*x) + sqrt(2 - sqrt(2))*exp(x) + 1)/8 + sqrt(sqrt(2) + 2)*log(exp(2*x) - sqrt(sqrt(2) + 2)*exp(x) + 1)/8 - sqrt(sqrt(2) + 2)*log(exp(2*x) + sqrt(sqrt(2) + 2)*exp(x) + 1)/8 + atan((-2*exp(x) + sqrt(sqrt(2) + 2))/sqrt(2 - sqrt(2)))/(2*sqrt(2*sqrt(2) + 4)) - atan((2*exp(x) + sqrt(sqrt(2) + 2))/sqrt(2 - sqrt(2)))/(2*sqrt(2*sqrt(2) + 4)) + atan((-2*exp(x) + sqrt(2 - sqrt(2)))/sqrt(sqrt(2) + 2))/(2*sqrt(4 - 2*sqrt(2))) - atan((2*exp(x) + sqrt(2 - sqrt(2)))/sqrt(sqrt(2) + 2))/(2*sqrt(4 - 2*sqrt(2))),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*coth(4*x),
        variable=x,
        num_steps=15,
        integral=exp(x) + sqrt(2)*log(exp(2*x) - sqrt(2)*exp(x) + 1)/8 - sqrt(2)*log(exp(2*x) + sqrt(2)*exp(x) + 1)/8 - sqrt(2)*atan(sqrt(2)*exp(x) - 1)/4 - sqrt(2)*atan(sqrt(2)*exp(x) + 1)/4 - atan(exp(x))/2 - atanh(exp(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=exp(x)*coth(4*x)**2,
        variable=x,
        num_steps=17,
        integral=exp(x) + sqrt(2)*log(exp(2*x) - sqrt(2)*exp(x) + 1)/32 - sqrt(2)*log(exp(2*x) + sqrt(2)*exp(x) + 1)/32 - sqrt(2)*atan(sqrt(2)*exp(x) - 1)/16 - sqrt(2)*atan(sqrt(2)*exp(x) + 1)/16 - atan(exp(x))/8 - atanh(exp(x))/8 + exp(x)/(2 - 2*exp(8*x)),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)/(a - tanh(2*x)),
        variable=x,
        num_steps=5,
        integral=-exp(x)/(1 - a) + atan((1 - a)**(sympy.S(1)/4)*exp(x)/(a + 1)**(sympy.S(1)/4))/((1 - a)*(1 - a**2)**(sympy.S(1)/4)*sqrt(a + 1)) + atanh((1 - a)**(sympy.S(1)/4)*exp(x)/(a + 1)**(sympy.S(1)/4))/((1 - a)*(1 - a**2)**(sympy.S(1)/4)*sqrt(a + 1)),
    ),
    RubiTestSuiteCase(
        integrand=exp(x)/(a - tanh(2*x))**2,
        variable=x,
        num_steps=7,
        integral=exp(x)/(1 - a)**2 + exp(x)/((1 - a)**2*(a + 1)*(a + (a - 1)*exp(4*x) + 1)) - (4*a + 1)*atan((1 - a)**(sympy.S(1)/4)*exp(x)/(a + 1)**(sympy.S(1)/4))/(2*(1 - a)**2*(1 - a**2)**(sympy.S(1)/4)*(a + 1)**(sympy.S(3)/2)) - (4*a + 1)*atanh((1 - a)**(sympy.S(1)/4)*exp(x)/(a + 1)**(sympy.S(1)/4))/(2*(1 - a)**2*(1 - a**2)**(sympy.S(1)/4)*(a + 1)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))*tanh(d + e*x)**3,
        variable=x,
        num_steps=6,
        integral=-6*exp(c*(a + b*x))*hyper((1, b*c/(2*e)), (b*c/(2*e) + 1,), -exp(2*d + 2*e*x))/(b*c) + 12*exp(c*(a + b*x))*hyper((2, b*c/(2*e)), (b*c/(2*e) + 1,), -exp(2*d + 2*e*x))/(b*c) - 8*exp(c*(a + b*x))*hyper((3, b*c/(2*e)), (b*c/(2*e) + 1,), -exp(2*d + 2*e*x))/(b*c) + exp(c*(a + b*x))/(b*c),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))*tanh(d + e*x)**2,
        variable=x,
        num_steps=5,
        integral=-4*exp(c*(a + b*x))*hyper((1, b*c/(2*e)), (b*c/(2*e) + 1,), -exp(2*d + 2*e*x))/(b*c) + 4*exp(c*(a + b*x))*hyper((2, b*c/(2*e)), (b*c/(2*e) + 1,), -exp(2*d + 2*e*x))/(b*c) + exp(c*(a + b*x))/(b*c),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))*tanh(d + e*x),
        variable=x,
        num_steps=4,
        integral=-2*exp(c*(a + b*x))*hyper((1, b*c/(2*e)), (b*c/(2*e) + 1,), -exp(2*d + 2*e*x))/(b*c) + exp(c*(a + b*x))/(b*c),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))*coth(d + e*x),
        variable=x,
        num_steps=4,
        integral=-2*exp(c*(a + b*x))*hyper((1, b*c/(2*e)), (b*c/(2*e) + 1,), exp(2*d + 2*e*x))/(b*c) + exp(c*(a + b*x))/(b*c),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))*coth(d + e*x)**2,
        variable=x,
        num_steps=5,
        integral=-4*exp(c*(a + b*x))*hyper((1, b*c/(2*e)), (b*c/(2*e) + 1,), exp(2*d + 2*e*x))/(b*c) + 4*exp(c*(a + b*x))*hyper((2, b*c/(2*e)), (b*c/(2*e) + 1,), exp(2*d + 2*e*x))/(b*c) + exp(c*(a + b*x))/(b*c),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))*coth(d + e*x)**3,
        variable=x,
        num_steps=6,
        integral=-6*exp(c*(a + b*x))*hyper((1, b*c/(2*e)), (b*c/(2*e) + 1,), exp(2*d + 2*e*x))/(b*c) + 12*exp(c*(a + b*x))*hyper((2, b*c/(2*e)), (b*c/(2*e) + 1,), exp(2*d + 2*e*x))/(b*c) - 8*exp(c*(a + b*x))*hyper((3, b*c/(2*e)), (b*c/(2*e) + 1,), exp(2*d + 2*e*x))/(b*c) + exp(c*(a + b*x))/(b*c),
    ),
    RubiTestSuiteCase(
        integrand=(tanh(a*c + b*c*x)**2)**(sympy.S(5)/2)*exp(c*(a + b*x)),
        variable=x,
        num_steps=9,
        integral=sqrt(tanh(a*c + b*c*x)**2)*exp(c*(a + b*x))*coth(a*c + b*c*x)/(b*c) - 15*sqrt(tanh(a*c + b*c*x)**2)*coth(a*c + b*c*x)*atan(exp(c*(a + b*x)))/(4*b*c) + 25*sqrt(tanh(a*c + b*c*x)**2)*exp(c*(a + b*x))*coth(a*c + b*c*x)/(4*b*c*(exp(2*c*(a + b*x)) + 1)) - 55*sqrt(tanh(a*c + b*c*x)**2)*exp(c*(a + b*x))*coth(a*c + b*c*x)/(6*b*c*(exp(2*c*(a + b*x)) + 1)**2) + 26*sqrt(tanh(a*c + b*c*x)**2)*exp(c*(a + b*x))*coth(a*c + b*c*x)/(3*b*c*(exp(2*c*(a + b*x)) + 1)**3) - 4*sqrt(tanh(a*c + b*c*x)**2)*exp(c*(a + b*x))*coth(a*c + b*c*x)/(b*c*(exp(2*c*(a + b*x)) + 1)**4),
    ),
    RubiTestSuiteCase(
        integrand=(tanh(a*c + b*c*x)**2)**(sympy.S(3)/2)*exp(c*(a + b*x)),
        variable=x,
        num_steps=8,
        integral=sqrt(tanh(a*c + b*c*x)**2)*exp(c*(a + b*x))*coth(a*c + b*c*x)/(b*c) - 3*sqrt(tanh(a*c + b*c*x)**2)*coth(a*c + b*c*x)*atan(exp(c*(a + b*x)))/(b*c) + 3*sqrt(tanh(a*c + b*c*x)**2)*exp(c*(a + b*x))*coth(a*c + b*c*x)/(b*c*(exp(2*c*(a + b*x)) + 1)) - 2*sqrt(tanh(a*c + b*c*x)**2)*exp(c*(a + b*x))*coth(a*c + b*c*x)/(b*c*(exp(2*c*(a + b*x)) + 1)**2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(tanh(a*c + b*c*x)**2)*exp(c*(a + b*x)),
        variable=x,
        num_steps=4,
        integral=sqrt(tanh(a*c + b*c*x)**2)*exp(c*(a + b*x))*coth(a*c + b*c*x)/(b*c) - 2*sqrt(tanh(a*c + b*c*x)**2)*coth(a*c + b*c*x)*atan(exp(c*(a + b*x)))/(b*c),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))/sqrt(tanh(a*c + b*c*x)**2),
        variable=x,
        num_steps=4,
        integral=exp(c*(a + b*x))*tanh(a*c + b*c*x)/(b*c*sqrt(tanh(a*c + b*c*x)**2)) - 2*tanh(a*c + b*c*x)*atanh(exp(c*(a + b*x)))/(b*c*sqrt(tanh(a*c + b*c*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))/(tanh(a*c + b*c*x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=8,
        integral=exp(c*(a + b*x))*tanh(a*c + b*c*x)/(b*c*sqrt(tanh(a*c + b*c*x)**2)) - 3*tanh(a*c + b*c*x)*atanh(exp(c*(a + b*x)))/(b*c*sqrt(tanh(a*c + b*c*x)**2)) + 3*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(b*c*(1 - exp(2*c*(a + b*x)))*sqrt(tanh(a*c + b*c*x)**2)) - 2*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(b*c*(1 - exp(2*c*(a + b*x)))**2*sqrt(tanh(a*c + b*c*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=exp(c*(a + b*x))/(tanh(a*c + b*c*x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=9,
        integral=exp(c*(a + b*x))*tanh(a*c + b*c*x)/(b*c*sqrt(tanh(a*c + b*c*x)**2)) - 15*tanh(a*c + b*c*x)*atanh(exp(c*(a + b*x)))/(4*b*c*sqrt(tanh(a*c + b*c*x)**2)) + 25*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(4*b*c*(1 - exp(2*c*(a + b*x)))*sqrt(tanh(a*c + b*c*x)**2)) - 55*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(6*b*c*(1 - exp(2*c*(a + b*x)))**2*sqrt(tanh(a*c + b*c*x)**2)) + 26*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(3*b*c*(1 - exp(2*c*(a + b*x)))**3*sqrt(tanh(a*c + b*c*x)**2)) - 4*exp(c*(a + b*x))*tanh(a*c + b*c*x)/(b*c*(1 - exp(2*c*(a + b*x)))**4*sqrt(tanh(a*c + b*c*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sin(tanh(a + b*x))**3,
        variable=x,
        num_steps=19,
        integral=((Integer(-1) * ((Integer(3) * sympy.Function('CosIntegral')((Integer(1) + (Integer(-1) * sympy.tanh((Symbol('a') + (Symbol('b') * x)))))) * sympy.sin(Integer(1))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * sympy.Function('CosIntegral')((Integer(1) + sympy.tanh((Symbol('a') + (Symbol('b') * x))))) * sympy.sin(Integer(1))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))) + ((sympy.Function('CosIntegral')((Integer(3) + (Integer(-1) * (Integer(3) * sympy.tanh((Symbol('a') + (Symbol('b') * x))))))) * sympy.sin(Integer(3))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + ((sympy.Function('CosIntegral')((Integer(3) + (Integer(3) * sympy.tanh((Symbol('a') + (Symbol('b') * x)))))) * sympy.sin(Integer(3))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.cos(Integer(3)) * sympy.Function('SinIntegral')((Integer(3) + (Integer(-1) * (Integer(3) * sympy.tanh((Symbol('a') + (Symbol('b') * x)))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))) + ((Integer(3) * sympy.cos(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + (Integer(-1) * sympy.tanh((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + ((Integer(3) * sympy.cos(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + sympy.tanh((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.cos(Integer(3)) * sympy.Function('SinIntegral')((Integer(3) + (Integer(3) * sympy.tanh((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=sin(tanh(a + b*x))**2,
        variable=x,
        num_steps=13,
        integral=(((sympy.cos(Integer(2)) * sympy.Function('CosIntegral')((Integer(2) + (Integer(-1) * (Integer(2) * sympy.tanh((Symbol('a') + (Symbol('b') * x)))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.cos(Integer(2)) * sympy.Function('CosIntegral')((Integer(2) + (Integer(2) * sympy.tanh((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1)))) + (Integer(-1) * (sympy.log((Integer(1) + (Integer(-1) * sympy.tanh((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(4) * Symbol('b')))**(Integer(-1)))) + (sympy.log((Integer(1) + sympy.tanh((Symbol('a') + (Symbol('b') * x))))) * ((Integer(4) * Symbol('b')))**(Integer(-1))) + ((sympy.sin(Integer(2)) * sympy.Function('SinIntegral')((Integer(2) + (Integer(-1) * (Integer(2) * sympy.tanh((Symbol('a') + (Symbol('b') * x)))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.sin(Integer(2)) * sympy.Function('SinIntegral')((Integer(2) + (Integer(2) * sympy.tanh((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1))))),
    ),
    RubiTestSuiteCase(
        integrand=sin(tanh(a + b*x)),
        variable=x,
        num_steps=9,
        integral=((Integer(-1) * ((sympy.Function('CosIntegral')((Integer(1) + (Integer(-1) * sympy.tanh((Symbol('a') + (Symbol('b') * x)))))) * sympy.sin(Integer(1))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))) + (Integer(-1) * ((sympy.Function('CosIntegral')((Integer(1) + sympy.tanh((Symbol('a') + (Symbol('b') * x))))) * sympy.sin(Integer(1))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))) + ((sympy.cos(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + (Integer(-1) * sympy.tanh((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(2) * Symbol('b')))**(Integer(-1))) + ((sympy.cos(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + sympy.tanh((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=csc(tanh(a + b*x)),
        variable=x,
        num_steps=3,
        integral=(((Integer(-1) * (Integer(2))**(Integer(-1))) * sympy.Function('Unintegrable')(((sympy.csc(sympy.tanh((Symbol('a') + (Symbol('b') * x)))) * (sympy.sech((Symbol('a') + (Symbol('b') * x))))**(Integer(2))) * ((Integer(-1) + sympy.tanh((Symbol('a') + (Symbol('b') * x)))))**(Integer(-1))), x)) + ((Integer(2))**(Integer(-1)) * sympy.Function('Unintegrable')(((sympy.csc(sympy.tanh((Symbol('a') + (Symbol('b') * x)))) * (sympy.sech((Symbol('a') + (Symbol('b') * x))))**(Integer(2))) * ((Integer(1) + sympy.tanh((Symbol('a') + (Symbol('b') * x)))))**(Integer(-1))), x))),
    ),
    RubiTestSuiteCase(
        integrand=cos(tanh(a + b*x))**3,
        variable=x,
        num_steps=19,
        integral=((Integer(-1) * ((sympy.cos(Integer(3)) * sympy.Function('CosIntegral')((Integer(3) + (Integer(-1) * (Integer(3) * sympy.tanh((Symbol('a') + (Symbol('b') * x)))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * sympy.cos(Integer(1)) * sympy.Function('CosIntegral')((Integer(1) + (Integer(-1) * sympy.tanh((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))) + ((Integer(3) * sympy.cos(Integer(1)) * sympy.Function('CosIntegral')((Integer(1) + sympy.tanh((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + ((sympy.cos(Integer(3)) * sympy.Function('CosIntegral')((Integer(3) + (Integer(3) * sympy.tanh((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.sin(Integer(3)) * sympy.Function('SinIntegral')((Integer(3) + (Integer(-1) * (Integer(3) * sympy.tanh((Symbol('a') + (Symbol('b') * x)))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))) + (Integer(-1) * ((Integer(3) * sympy.sin(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + (Integer(-1) * sympy.tanh((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))) + ((Integer(3) * sympy.sin(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + sympy.tanh((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(8) * Symbol('b')))**(Integer(-1))) + ((sympy.sin(Integer(3)) * sympy.Function('SinIntegral')((Integer(3) + (Integer(3) * sympy.tanh((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(8) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(tanh(a + b*x))**2,
        variable=x,
        num_steps=13,
        integral=((Integer(-1) * ((sympy.cos(Integer(2)) * sympy.Function('CosIntegral')((Integer(2) + (Integer(-1) * (Integer(2) * sympy.tanh((Symbol('a') + (Symbol('b') * x)))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1)))) + ((sympy.cos(Integer(2)) * sympy.Function('CosIntegral')((Integer(2) + (Integer(2) * sympy.tanh((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * (sympy.log((Integer(1) + (Integer(-1) * sympy.tanh((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(4) * Symbol('b')))**(Integer(-1)))) + (sympy.log((Integer(1) + sympy.tanh((Symbol('a') + (Symbol('b') * x))))) * ((Integer(4) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.sin(Integer(2)) * sympy.Function('SinIntegral')((Integer(2) + (Integer(-1) * (Integer(2) * sympy.tanh((Symbol('a') + (Symbol('b') * x)))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1)))) + ((sympy.sin(Integer(2)) * sympy.Function('SinIntegral')((Integer(2) + (Integer(2) * sympy.tanh((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(4) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=cos(tanh(a + b*x)),
        variable=x,
        num_steps=9,
        integral=((Integer(-1) * ((sympy.cos(Integer(1)) * sympy.Function('CosIntegral')((Integer(1) + (Integer(-1) * sympy.tanh((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))) + ((sympy.cos(Integer(1)) * sympy.Function('CosIntegral')((Integer(1) + sympy.tanh((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(2) * Symbol('b')))**(Integer(-1))) + (Integer(-1) * ((sympy.sin(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + (Integer(-1) * sympy.tanh((Symbol('a') + (Symbol('b') * x))))))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))) + ((sympy.sin(Integer(1)) * sympy.Function('SinIntegral')((Integer(1) + sympy.tanh((Symbol('a') + (Symbol('b') * x)))))) * ((Integer(2) * Symbol('b')))**(Integer(-1)))),
    ),
    RubiTestSuiteCase(
        integrand=sec(tanh(a + b*x)),
        variable=x,
        num_steps=3,
        integral=(((Integer(-1) * (Integer(2))**(Integer(-1))) * sympy.Function('Unintegrable')(((sympy.sec(sympy.tanh((Symbol('a') + (Symbol('b') * x)))) * (sympy.sech((Symbol('a') + (Symbol('b') * x))))**(Integer(2))) * ((Integer(-1) + sympy.tanh((Symbol('a') + (Symbol('b') * x)))))**(Integer(-1))), x)) + ((Integer(2))**(Integer(-1)) * sympy.Function('Unintegrable')(((sympy.sec(sympy.tanh((Symbol('a') + (Symbol('b') * x)))) * (sympy.sech((Symbol('a') + (Symbol('b') * x))))**(Integer(2))) * ((Integer(1) + sympy.tanh((Symbol('a') + (Symbol('b') * x)))))**(Integer(-1))), x))),
    ),
]
