# -*- coding: utf-8 -*-
"""Generated from MathematicaSyntaxTestSuite.

Source: 6 Hyperbolic functions/6.3 Hyperbolic tangent/6.3.7 (d hyper)^m (a+b (c tanh)^n)^p.m
"""

from sympy import *
import sympy

from rubi_integration_test_suite.base_test_objects import RubiTestSuiteCase

SOURCE_FILE = '6 Hyperbolic functions/6.3 Hyperbolic tangent/6.3.7 (d hyper)^m (a+b (c tanh)^n)^p.m'

# Free symbols used by round-trippable string expressions.
x = symbols('x')

# Free symbols used by round-trippable string expressions.
a, b, c, d = symbols('a b c d')

# Third tuple element: number of Rubi integration steps used.
TEST_CASES = [
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*sinh(c + d*x)**4,
        variable=x,
        num_steps=5,
        integral=-b*tanh(c + d*x)/d + x*(3*a/8 + 15*b/8) + (a + b)*sinh(c + d*x)*cosh(c + d*x)**3/(4*d) - (5*a + 9*b)*sinh(c + d*x)*cosh(c + d*x)/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*sinh(c + d*x)**3,
        variable=x,
        num_steps=3,
        integral=-b*sech(c + d*x)/d + (a + b)*cosh(c + d*x)**3/(3*d) - (a + 2*b)*cosh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*sinh(c + d*x)**2,
        variable=x,
        num_steps=4,
        integral=b*tanh(c + d*x)/d + x*(-a/2 - 3*b/2) + (a + b)*sinh(c + d*x)*cosh(c + d*x)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*sinh(c + d*x),
        variable=x,
        num_steps=3,
        integral=b*sech(c + d*x)/d + (a + b)*cosh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*csch(c + d*x),
        variable=x,
        num_steps=3,
        integral=-a*atanh(cosh(c + d*x))/d - b*sech(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*csch(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=-a*coth(c + d*x)/d + b*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*csch(c + d*x)**3,
        variable=x,
        num_steps=4,
        integral=-a*coth(c + d*x)*csch(c + d*x)/(2*d) + b*sech(c + d*x)/d + (a - 2*b)*atanh(cosh(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*csch(c + d*x)**4,
        variable=x,
        num_steps=3,
        integral=-a*coth(c + d*x)**3/(3*d) - b*tanh(c + d*x)/d + (a - b)*coth(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*sinh(c + d*x)**4,
        variable=x,
        num_steps=6,
        integral=-b**2*tanh(c + d*x)**3/(3*d) + x*(3*a**2/8 + 15*a*b/4 + 35*b**2/8) + (a + b)**2*sinh(c + d*x)**4*tanh(c + d*x)/(4*d) - (a + b)*(a + 9*b)*sinh(c + d*x)*cosh(c + d*x)/(8*d) - (a**2 + 10*a*b + 13*b**2)*tanh(c + d*x)/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*sinh(c + d*x)**3,
        variable=x,
        num_steps=3,
        integral=b**2*sech(c + d*x)**3/(3*d) - b*(2*a + 3*b)*sech(c + d*x)/d + (a + b)**2*cosh(c + d*x)**3/(3*d) - (a + b)*(a + 3*b)*cosh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*sinh(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=b**2*tanh(c + d*x)**3/(3*d) + x*(-a/2 - b/2)*(a + 5*b) + (a + b)**2*sinh(c + d*x)**2*tanh(c + d*x)/(2*d) + (a + b)*(a + 5*b)*tanh(c + d*x)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*sinh(c + d*x),
        variable=x,
        num_steps=3,
        integral=-b**2*sech(c + d*x)**3/(3*d) + 2*b*(a + b)*sech(c + d*x)/d + (a + b)**2*cosh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*csch(c + d*x),
        variable=x,
        num_steps=4,
        integral=-a**2*atanh(cosh(c + d*x))/d + b**2*sech(c + d*x)**3/(3*d) - b*(2*a + b)*sech(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*csch(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=-a**2*coth(c + d*x)/d + 2*a*b*tanh(c + d*x)/d + b**2*tanh(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*csch(c + d*x)**3,
        variable=x,
        num_steps=5,
        integral=-a**2*csch(c + d*x)**2*sech(c + d*x)/(2*d) + a*(a - 4*b)*atanh(cosh(c + d*x))/(2*d) - a*(a - 4*b)*sech(c + d*x)/(2*d) - b**2*sech(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*csch(c + d*x)**4,
        variable=x,
        num_steps=3,
        integral=-a**2*coth(c + d*x)**3/(3*d) + a*(a - 2*b)*coth(c + d*x)/d - b**2*tanh(c + d*x)**3/(3*d) - b*(2*a - b)*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*sinh(c + d*x)**4,
        variable=x,
        num_steps=6,
        integral=-3*b**2*(5*a + 21*b)*tanh(c + d*x)**5/(40*d) - b*(6*a**2 + 35*a*b + 21*b**2)*tanh(c + d*x)**3/(8*d) + x*(3*a/8 + 3*b/8)*(a**2 + 14*a*b + 21*b**2) + (a + b*tanh(c + d*x)**2)**3*sinh(c + d*x)**3*cosh(c + d*x)/(4*d) - (a + b*tanh(c + d*x)**2)**2*(3*a + 9*b)*sinh(c + d*x)**2*tanh(c + d*x)/(8*d) - (3*a + 3*b)*(a**2 + 14*a*b + 21*b**2)*tanh(c + d*x)/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*sinh(c + d*x)**3,
        variable=x,
        num_steps=3,
        integral=-b**3*sech(c + d*x)**5/(5*d) + b**2*(3*a + 4*b)*sech(c + d*x)**3/(3*d) - 3*b*(a + b)*(a + 2*b)*sech(c + d*x)/d + (a + b)**3*cosh(c + d*x)**3/(3*d) - (a + b)**2*(a + 4*b)*cosh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*sinh(c + d*x),
        variable=x,
        num_steps=3,
        integral=b**3*sech(c + d*x)**5/(5*d) - b**2*(a + b)*sech(c + d*x)**3/d + 3*b*(a + b)**2*sech(c + d*x)/d + (a + b)**3*cosh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*csch(c + d*x),
        variable=x,
        num_steps=4,
        integral=-a**3*atanh(cosh(c + d*x))/d - b**3*sech(c + d*x)**5/(5*d) + b**2*(3*a + 2*b)*sech(c + d*x)**3/(3*d) - b*(3*a**2 + 3*a*b + b**2)*sech(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*csch(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=-a**3*coth(c + d*x)/d + 3*a**2*b*tanh(c + d*x)/d + a*b**2*tanh(c + d*x)**3/d + b**3*tanh(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*csch(c + d*x)**3,
        variable=x,
        num_steps=6,
        integral=a**2*(a - 6*b)*atanh(cosh(c + d*x))/(2*d) + b*(33*a - 2*b)*(a - b*sech(c + d*x)**2 + b)*sech(c + d*x)/(30*d) + 7*b*(a - b*sech(c + d*x)**2 + b)**2*sech(c + d*x)/(10*d) + b*(81*a**2 - 28*a*b - 4*b**2)*sech(c + d*x)/(30*d) - (a - b*sech(c + d*x)**2 + b)**3*coth(c + d*x)*csch(c + d*x)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*csch(c + d*x)**4,
        variable=x,
        num_steps=3,
        integral=-a**3*coth(c + d*x)**3/(3*d) + a**2*(a - 3*b)*coth(c + d*x)/d - 3*a*b*(a - b)*tanh(c + d*x)/d - b**3*tanh(c + d*x)**5/(5*d) - b**2*(3*a - b)*tanh(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)**4/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=6,
        integral=a**(sympy.S(3)/2)*sqrt(b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(d*(a + b)**3) + x*(3*a**2 - 6*a*b - b**2)/(8*(a + b)**3) + sinh(c + d*x)*cosh(c + d*x)**3/(d*(4*a + 4*b)) - (5*a + b)*sinh(c + d*x)*cosh(c + d*x)/(8*d*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)**3/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=4,
        integral=a*sqrt(b)*atanh(sqrt(b)*sech(c + d*x)/sqrt(a + b))/(d*(a + b)**(sympy.S(5)/2)) - a*cosh(c + d*x)/(d*(a + b)**2) + cosh(c + d*x)**3/(d*(3*a + 3*b)),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)**2/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=5,
        integral=-sqrt(a)*sqrt(b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(d*(a + b)**2) - x*(a - b)/(2*(a + b)**2) + sinh(c + d*x)*cosh(c + d*x)/(d*(2*a + 2*b)),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=3,
        integral=-sqrt(b)*atanh(sqrt(b)*sech(c + d*x)/sqrt(a + b))/(d*(a + b)**(sympy.S(3)/2)) + cosh(c + d*x)/(d*(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=4,
        integral=sqrt(b)*atanh(sqrt(b)*sech(c + d*x)/sqrt(a + b))/(a*d*sqrt(a + b)) - atanh(cosh(c + d*x))/(a*d),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)**2/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=3,
        integral=-coth(c + d*x)/(a*d) - sqrt(b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(a**(sympy.S(3)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)**3/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=5,
        integral=-coth(c + d*x)*csch(c + d*x)/(2*a*d) - sqrt(b)*sqrt(a + b)*atanh(sqrt(b)*sech(c + d*x)/sqrt(a + b))/(a**2*d) + (a + 2*b)*atanh(cosh(c + d*x))/(2*a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)**4/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=4,
        integral=-coth(c + d*x)**3/(3*a*d) + (a + b)*coth(c + d*x)/(a**2*d) + sqrt(b)*(a + b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(a**(sympy.S(5)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)**4/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=7,
        integral=3*sqrt(a)*sqrt(b)*(a - b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(2*d*(a + b)**4) + b*(9*a - 3*b)*tanh(c + d*x)/(8*d*(a + b)**3*(a + b*tanh(c + d*x)**2)) + x*(3*a**2 - 18*a*b + 3*b**2)/(8*(a + b)**4) + sinh(c + d*x)*cosh(c + d*x)**3/(d*(a + b*tanh(c + d*x)**2)*(4*a + 4*b)) - (5*a - b)*sinh(c + d*x)*cosh(c + d*x)/(8*d*(a + b)**2*(a + b*tanh(c + d*x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)**3/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=5,
        integral=a*b*sech(c + d*x)/(2*d*(a + b)**3*(a - b*sech(c + d*x)**2 + b)) + sqrt(b)*(3*a - 2*b)*atanh(sqrt(b)*sech(c + d*x)/sqrt(a + b))/(2*d*(a + b)**(sympy.S(7)/2)) - (a - b)*cosh(c + d*x)/(d*(a + b)**3) + cosh(c + d*x)**3/(3*d*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)**2/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=6,
        integral=-b*tanh(c + d*x)/(d*(a + b)**2*(a + b*tanh(c + d*x)**2)) - x*(a - 3*b)/(2*(a + b)**3) + sinh(c + d*x)*cosh(c + d*x)/(d*(a + b*tanh(c + d*x)**2)*(2*a + 2*b)) - sqrt(b)*(3*a - b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(2*sqrt(a)*d*(a + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=4,
        integral=-3*sqrt(b)*atanh(sqrt(b)*sech(c + d*x)/sqrt(a + b))/(2*d*(a + b)**(sympy.S(5)/2)) - cosh(c + d*x)/(d*(2*a + 2*b)*(a - b*sech(c + d*x)**2 + b)) + 3*cosh(c + d*x)/(2*d*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=5,
        integral=b*sech(c + d*x)/(2*a*d*(a + b)*(a - b*sech(c + d*x)**2 + b)) + sqrt(b)*(3*a + 2*b)*atanh(sqrt(b)*sech(c + d*x)/sqrt(a + b))/(2*a**2*d*(a + b)**(sympy.S(3)/2)) - atanh(cosh(c + d*x))/(a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)**2/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=4,
        integral=coth(c + d*x)/(2*a*d*(a + b*tanh(c + d*x)**2)) - 3*coth(c + d*x)/(2*a**2*d) - 3*sqrt(b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(2*a**(sympy.S(5)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)**3/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=6,
        integral=-coth(c + d*x)*csch(c + d*x)/(2*a*d*(a - b*sech(c + d*x)**2 + b)) - b*sech(c + d*x)/(a**2*d*(a - b*sech(c + d*x)**2 + b)) - sqrt(b)*(3*a + 4*b)*atanh(sqrt(b)*sech(c + d*x)/sqrt(a + b))/(2*a**3*d*sqrt(a + b)) + (a + 4*b)*atanh(cosh(c + d*x))/(2*a**3*d),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)**4/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=5,
        integral=-coth(c + d*x)**3/(3*a**2*d) + b*(a + b)*tanh(c + d*x)/(2*a**3*d*(a + b*tanh(c + d*x)**2)) + (a + 2*b)*coth(c + d*x)/(a**3*d) + sqrt(b)*(3*a + 5*b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(2*a**(sympy.S(7)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)**4/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=8,
        integral=b*(7*a - 5*b)*tanh(c + d*x)/(8*d*(a + b)**3*(a + b*tanh(c + d*x)**2)**2) + b*(3*a - 3*b)*tanh(c + d*x)/(2*d*(a + b)**4*(a + b*tanh(c + d*x)**2)) + x*(3*a**2 - 30*a*b + 15*b**2)/(8*(a + b)**5) + sinh(c + d*x)*cosh(c + d*x)**3/(d*(a + b*tanh(c + d*x)**2)**2*(4*a + 4*b)) - (5*a - 3*b)*sinh(c + d*x)*cosh(c + d*x)/(8*d*(a + b)**2*(a + b*tanh(c + d*x)**2)**2) + 3*sqrt(b)*(5*a**2 - 10*a*b + b**2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(8*sqrt(a)*d*(a + b)**5),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)**3/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=6,
        integral=a*b*sech(c + d*x)/(4*d*(a + b)**3*(a - b*sech(c + d*x)**2 + b)**2) + sqrt(b)*(15*a - 20*b)*atanh(sqrt(b)*sech(c + d*x)/sqrt(a + b))/(8*d*(a + b)**(sympy.S(9)/2)) + b*(7*a - 4*b)*sech(c + d*x)/(8*d*(a + b)**4*(a - b*sech(c + d*x)**2 + b)) - (a - 2*b)*cosh(c + d*x)/(d*(a + b)**4) + cosh(c + d*x)**3/(3*d*(a + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)**2/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=7,
        integral=-3*b*tanh(c + d*x)/(4*d*(a + b)**2*(a + b*tanh(c + d*x)**2)**2) - x*(a - 5*b)/(2*(a + b)**4) + sinh(c + d*x)*cosh(c + d*x)/(d*(a + b*tanh(c + d*x)**2)**2*(2*a + 2*b)) - b*(11*a - b)*tanh(c + d*x)/(8*a*d*(a + b)**3*(a + b*tanh(c + d*x)**2)) - sqrt(b)*(15*a**2 - 10*a*b - b**2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(8*a**(sympy.S(3)/2)*d*(a + b)**4),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=5,
        integral=-15*sqrt(b)*atanh(sqrt(b)*sech(c + d*x)/sqrt(a + b))/(8*d*(a + b)**(sympy.S(7)/2)) - cosh(c + d*x)/(d*(4*a + 4*b)*(a - b*sech(c + d*x)**2 + b)**2) - 5*cosh(c + d*x)/(8*d*(a + b)**2*(a - b*sech(c + d*x)**2 + b)) + 15*cosh(c + d*x)/(8*d*(a + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=6,
        integral=b*sech(c + d*x)/(4*a*d*(a + b)*(a - b*sech(c + d*x)**2 + b)**2) + b*(7*a + 4*b)*sech(c + d*x)/(8*a**2*d*(a + b)**2*(a - b*sech(c + d*x)**2 + b)) + sqrt(b)*(15*a**2 + 20*a*b + 8*b**2)*atanh(sqrt(b)*sech(c + d*x)/sqrt(a + b))/(8*a**3*d*(a + b)**(sympy.S(5)/2)) - atanh(cosh(c + d*x))/(a**3*d),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)**2/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=5,
        integral=coth(c + d*x)/(4*a*d*(a + b*tanh(c + d*x)**2)**2) + 5*coth(c + d*x)/(8*a**2*d*(a + b*tanh(c + d*x)**2)) - 15*coth(c + d*x)/(8*a**3*d) - 15*sqrt(b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(8*a**(sympy.S(7)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)**3/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=7,
        integral=-coth(c + d*x)*csch(c + d*x)/(2*a*d*(a - b*sech(c + d*x)**2 + b)**2) - 3*b*sech(c + d*x)/(4*a**2*d*(a - b*sech(c + d*x)**2 + b)**2) - b*(11*a + 12*b)*sech(c + d*x)/(8*a**3*d*(a + b)*(a - b*sech(c + d*x)**2 + b)) - sqrt(b)*(15*a**2 + 40*a*b + 24*b**2)*atanh(sqrt(b)*sech(c + d*x)/sqrt(a + b))/(8*a**4*d*(a + b)**(sympy.S(3)/2)) + (a + 6*b)*atanh(cosh(c + d*x))/(2*a**4*d),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)**4/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=6,
        integral=b*(a + b)*tanh(c + d*x)/(4*a**3*d*(a + b*tanh(c + d*x)**2)**2) - coth(c + d*x)**3/(3*a**3*d) + b*(7*a + 11*b)*tanh(c + d*x)/(8*a**4*d*(a + b*tanh(c + d*x)**2)) + (a + 3*b)*coth(c + d*x)/(a**4*d) + 5*sqrt(b)*(3*a + 7*b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(8*a**(sympy.S(9)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)*sinh(c + d*x)**4,
        variable=x,
        num_steps=8,
        integral=-3*a*tanh(c + d*x)/(8*d) - 3*b*tanh(c + d*x)**2/(2*d) - (a + 8*b*tanh(c + d*x))*sinh(c + d*x)**2*tanh(c + d*x)/(8*d) + (3*a - 24*b)*log(tanh(c + d*x) + 1)/(16*d) - (3*a + 24*b)*log(1 - tanh(c + d*x))/(16*d) + (a*tanh(c + d*x) + b)*sinh(c + d*x)**4/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)*sinh(c + d*x)**3,
        variable=x,
        num_steps=9,
        integral=a*cosh(c + d*x)**3/(3*d) - a*cosh(c + d*x)/d - b*sinh(c + d*x)**3*tanh(c + d*x)**2/(2*d) + 5*b*sinh(c + d*x)**3/(6*d) - 5*b*sinh(c + d*x)/(2*d) + 5*b*atan(sinh(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)*sinh(c + d*x)**2,
        variable=x,
        num_steps=7,
        integral=a*tanh(c + d*x)/(2*d) + b*tanh(c + d*x)**2/(2*d) - (a - 4*b)*log(tanh(c + d*x) + 1)/(4*d) + (a + 4*b)*log(1 - tanh(c + d*x))/(4*d) + (a*tanh(c + d*x) + b)*sinh(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)*sinh(c + d*x),
        variable=x,
        num_steps=7,
        integral=a*cosh(c + d*x)/d - b*sinh(c + d*x)*tanh(c + d*x)**2/(2*d) + 3*b*sinh(c + d*x)/(2*d) - 3*b*atan(sinh(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)*csch(c + d*x),
        variable=x,
        num_steps=5,
        integral=-a*atanh(cosh(c + d*x))/d - b*tanh(c + d*x)*sech(c + d*x)/(2*d) + b*atan(sinh(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)*csch(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=-a*coth(c + d*x)/d + b*tanh(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)*csch(c + d*x)**3,
        variable=x,
        num_steps=6,
        integral=-a*coth(c + d*x)*csch(c + d*x)/(2*d) + a*atanh(cosh(c + d*x))/(2*d) + b*tanh(c + d*x)*sech(c + d*x)/(2*d) + b*atan(sinh(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)*csch(c + d*x)**4,
        variable=x,
        num_steps=3,
        integral=-a*coth(c + d*x)**3/(3*d) + a*coth(c + d*x)/d + b*log(tanh(c + d*x))/d - b*tanh(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)**2*sinh(c + d*x)**3,
        variable=x,
        num_steps=12,
        integral=a**2*cosh(c + d*x)**3/(3*d) - a**2*cosh(c + d*x)/d - a*b*sinh(c + d*x)**3*tanh(c + d*x)**2/d + 5*a*b*sinh(c + d*x)**3/(3*d) - 5*a*b*sinh(c + d*x)/d + 5*a*b*atan(sinh(c + d*x))/d + b**2*cosh(c + d*x)**3/(3*d) - 4*b**2*cosh(c + d*x)/d - b**2*sech(c + d*x)**5/(5*d) + 4*b**2*sech(c + d*x)**3/(3*d) - 6*b**2*sech(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)**2*sinh(c + d*x),
        variable=x,
        num_steps=10,
        integral=a**2*cosh(c + d*x)/d - a*b*sinh(c + d*x)*tanh(c + d*x)**2/d + 3*a*b*sinh(c + d*x)/d - 3*a*b*atan(sinh(c + d*x))/d + b**2*cosh(c + d*x)/d + b**2*sech(c + d*x)**5/(5*d) - b**2*sech(c + d*x)**3/d + 3*b**2*sech(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)**2*csch(c + d*x),
        variable=x,
        num_steps=8,
        integral=-a**2*atanh(cosh(c + d*x))/d - a*b*tanh(c + d*x)*sech(c + d*x)/d + a*b*atan(sinh(c + d*x))/d - b**2*sech(c + d*x)**5/(5*d) + 2*b**2*sech(c + d*x)**3/(3*d) - b**2*sech(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)**2*csch(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=-a**2*coth(c + d*x)/d + a*b*tanh(c + d*x)**2/d + b**2*tanh(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)**2*csch(c + d*x)**3,
        variable=x,
        num_steps=9,
        integral=-a**2*coth(c + d*x)*csch(c + d*x)/(2*d) + a**2*atanh(cosh(c + d*x))/(2*d) + a*b*tanh(c + d*x)*sech(c + d*x)/d + a*b*atan(sinh(c + d*x))/d + b**2*sech(c + d*x)**5/(5*d) - b**2*sech(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)**2*csch(c + d*x)**4,
        variable=x,
        num_steps=3,
        integral=-a**2*coth(c + d*x)**3/(3*d) + a**2*coth(c + d*x)/d + 2*a*b*log(tanh(c + d*x))/d - a*b*tanh(c + d*x)**2/d - b**2*tanh(c + d*x)**5/(5*d) + b**2*tanh(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)**3*sinh(c + d*x)**3,
        variable=x,
        num_steps=20,
        integral=a**3*cosh(c + d*x)**3/(3*d) - a**3*cosh(c + d*x)/d - 3*a**2*b*sinh(c + d*x)**3*tanh(c + d*x)**2/(2*d) + 5*a**2*b*sinh(c + d*x)**3/(2*d) - 15*a**2*b*sinh(c + d*x)/(2*d) + 15*a**2*b*atan(sinh(c + d*x))/(2*d) + a*b**2*cosh(c + d*x)**3/d - 12*a*b**2*cosh(c + d*x)/d - 3*a*b**2*sech(c + d*x)**5/(5*d) + 4*a*b**2*sech(c + d*x)**3/d - 18*a*b**2*sech(c + d*x)/d - b**3*sinh(c + d*x)**3*tanh(c + d*x)**8/(8*d) - 11*b**3*sinh(c + d*x)**3*tanh(c + d*x)**6/(48*d) - 33*b**3*sinh(c + d*x)**3*tanh(c + d*x)**4/(64*d) - 231*b**3*sinh(c + d*x)**3*tanh(c + d*x)**2/(128*d) + 385*b**3*sinh(c + d*x)**3/(128*d) - 1155*b**3*sinh(c + d*x)/(128*d) + 1155*b**3*atan(sinh(c + d*x))/(128*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)**3*sinh(c + d*x),
        variable=x,
        num_steps=17,
        integral=a**3*cosh(c + d*x)/d - 3*a**2*b*sinh(c + d*x)*tanh(c + d*x)**2/(2*d) + 9*a**2*b*sinh(c + d*x)/(2*d) - 9*a**2*b*atan(sinh(c + d*x))/(2*d) + 3*a*b**2*cosh(c + d*x)/d + 3*a*b**2*sech(c + d*x)**5/(5*d) - 3*a*b**2*sech(c + d*x)**3/d + 9*a*b**2*sech(c + d*x)/d - b**3*sinh(c + d*x)*tanh(c + d*x)**8/(8*d) - 3*b**3*sinh(c + d*x)*tanh(c + d*x)**6/(16*d) - 21*b**3*sinh(c + d*x)*tanh(c + d*x)**4/(64*d) - 105*b**3*sinh(c + d*x)*tanh(c + d*x)**2/(128*d) + 315*b**3*sinh(c + d*x)/(128*d) - 315*b**3*atan(sinh(c + d*x))/(128*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)**3*csch(c + d*x),
        variable=x,
        num_steps=13,
        integral=-a**3*atanh(cosh(c + d*x))/d - 3*a**2*b*tanh(c + d*x)*sech(c + d*x)/(2*d) + 3*a**2*b*atan(sinh(c + d*x))/(2*d) - 3*a*b**2*sech(c + d*x)**5/(5*d) + 2*a*b**2*sech(c + d*x)**3/d - 3*a*b**2*sech(c + d*x)/d - b**3*tanh(c + d*x)**7*sech(c + d*x)/(8*d) - 7*b**3*tanh(c + d*x)**5*sech(c + d*x)/(48*d) - 35*b**3*tanh(c + d*x)**3*sech(c + d*x)/(192*d) - 35*b**3*tanh(c + d*x)*sech(c + d*x)/(128*d) + 35*b**3*atan(sinh(c + d*x))/(128*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)**3*csch(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=-a**3*coth(c + d*x)/d + 3*a**2*b*tanh(c + d*x)**2/(2*d) + 3*a*b**2*tanh(c + d*x)**5/(5*d) + b**3*tanh(c + d*x)**8/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)**3*csch(c + d*x)**3,
        variable=x,
        num_steps=14,
        integral=-a**3*coth(c + d*x)*csch(c + d*x)/(2*d) + a**3*atanh(cosh(c + d*x))/(2*d) + 3*a**2*b*tanh(c + d*x)*sech(c + d*x)/(2*d) + 3*a**2*b*atan(sinh(c + d*x))/(2*d) + 3*a*b**2*sech(c + d*x)**5/(5*d) - a*b**2*sech(c + d*x)**3/d - b**3*tanh(c + d*x)**5*sech(c + d*x)**3/(8*d) - 5*b**3*tanh(c + d*x)**3*sech(c + d*x)**3/(48*d) - 5*b**3*tanh(c + d*x)*sech(c + d*x)**3/(64*d) + 5*b**3*tanh(c + d*x)*sech(c + d*x)/(128*d) + 5*b**3*atan(sinh(c + d*x))/(128*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**3)**3*csch(c + d*x)**4,
        variable=x,
        num_steps=3,
        integral=-a**3*coth(c + d*x)**3/(3*d) + a**3*coth(c + d*x)/d + 3*a**2*b*log(tanh(c + d*x))/d - 3*a**2*b*tanh(c + d*x)**2/(2*d) - 3*a*b**2*tanh(c + d*x)**5/(5*d) + a*b**2*tanh(c + d*x)**3/d - b**3*tanh(c + d*x)**8/(8*d) + b**3*tanh(c + d*x)**6/(6*d),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)**4/(a + b*tanh(c + d*x)**3),
        variable=x,
        num_steps=11,
        integral=-sqrt(3)*a**(sympy.S(2)/3)*b**(sympy.S(1)/3)*(3*a**(sympy.S(4)/3)*b**(sympy.S(2)/3) + a**2 - b**2)*atan(sqrt(3)*(a**(sympy.S(1)/3) - 2*b**(sympy.S(1)/3)*tanh(c + d*x))/(3*a**(sympy.S(1)/3)))/(3*d*(a**(sympy.S(4)/3) + a**(sympy.S(2)/3)*b**(sympy.S(2)/3) + b**(sympy.S(4)/3))**3) - a**(sympy.S(2)/3)*b**(sympy.S(1)/3)*(3*a**(sympy.S(2)/3)*b**(sympy.S(4)/3)*(2*a**2 + b**2) + a**4 + 7*a**2*b**2 + b**4)*log(a**(sympy.S(1)/3) + b**(sympy.S(1)/3)*tanh(c + d*x))/(3*d*(a**2 - b**2)**3) + a**(sympy.S(2)/3)*b**(sympy.S(1)/3)*(3*a**(sympy.S(2)/3)*b**(sympy.S(4)/3)*(2*a**2 + b**2) + a**4 + 7*a**2*b**2 + b**4)*log(a**(sympy.S(2)/3) - a**(sympy.S(1)/3)*b**(sympy.S(1)/3)*tanh(c + d*x) + b**(sympy.S(2)/3)*tanh(c + d*x)**2)/(6*d*(a**2 - b**2)**3) - a**2*b*(a**2 + 2*b**2)*log(a + b*tanh(c + d*x)**3)/(d*(a**2 - b**2)**3) - 3*a*(a - 5*b)*log(1 - tanh(c + d*x))/(16*d*(a + b)**3) + 3*a*(a + 5*b)*log(tanh(c + d*x) + 1)/(16*d*(a - b)**3) - 1/(d*(16*a - 16*b)*(tanh(c + d*x) + 1)**2) + (5*a + b)/(16*d*(a - b)**2*(tanh(c + d*x) + 1)) - (5*a - b)/(16*d*(1 - tanh(c + d*x))*(a + b)**2) + 1/(d*(1 - tanh(c + d*x))**2*(16*a + 16*b)),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)**3/(a + b*tanh(c + d*x)**3),
        variable=x,
        num_steps=0,
        integral=(sympy.I * sympy.Function('Unintegrable')((((Integer(-1) * sympy.I) * (sympy.sinh((Symbol('c') + (Symbol('d') * x))))**(Integer(3))) * ((Symbol('a') + (Symbol('b') * (sympy.tanh((Symbol('c') + (Symbol('d') * x))))**(Integer(3)))))**(Integer(-1))), x)),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)**2/(a + b*tanh(c + d*x)**3),
        variable=x,
        num_steps=11,
        integral=sqrt(3)*a**(sympy.S(2)/3)*b**(sympy.S(1)/3)*(-3*a**(sympy.S(2)/3)*b**(sympy.S(4)/3) + a**2 + 2*b**2)*atan(sqrt(3)*(a**(sympy.S(1)/3) - 2*b**(sympy.S(1)/3)*tanh(c + d*x))/(3*a**(sympy.S(1)/3)))/(3*d*(a**2 - b**2)**2) + a**(sympy.S(2)/3)*b**(sympy.S(1)/3)*(3*a**(sympy.S(2)/3)*b**(sympy.S(4)/3) + a**2 + 2*b**2)*log(a**(sympy.S(1)/3) + b**(sympy.S(1)/3)*tanh(c + d*x))/(3*d*(a**2 - b**2)**2) - a**(sympy.S(2)/3)*b**(sympy.S(1)/3)*(3*a**(sympy.S(2)/3)*b**(sympy.S(4)/3) + a**2 + 2*b**2)*log(a**(sympy.S(2)/3) - a**(sympy.S(1)/3)*b**(sympy.S(1)/3)*tanh(c + d*x) + b**(sympy.S(2)/3)*tanh(c + d*x)**2)/(6*d*(a**2 - b**2)**2) + b*(2*a**2 + b**2)*log(a + b*tanh(c + d*x)**3)/(3*d*(a**2 - b**2)**2) + (a - 2*b)*log(1 - tanh(c + d*x))/(4*d*(a + b)**2) - 1/(d*(4*a - 4*b)*(tanh(c + d*x) + 1)) - (a + 2*b)*log(tanh(c + d*x) + 1)/(4*d*(a - b)**2) + 1/(d*(1 - tanh(c + d*x))*(4*a + 4*b)),
    ),
    RubiTestSuiteCase(
        integrand=sinh(c + d*x)/(a + b*tanh(c + d*x)**3),
        variable=x,
        num_steps=0,
        integral=((Integer(-1) * sympy.I) * sympy.Function('Unintegrable')(((sympy.I * sympy.sinh((Symbol('c') + (Symbol('d') * x)))) * ((Symbol('a') + (Symbol('b') * (sympy.tanh((Symbol('c') + (Symbol('d') * x))))**(Integer(3)))))**(Integer(-1))), x)),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)/(a + b*tanh(c + d*x)**3),
        variable=x,
        num_steps=0,
        integral=(sympy.I * sympy.Function('Unintegrable')((((Integer(-1) * sympy.I) * sympy.csch((Symbol('c') + (Symbol('d') * x)))) * ((Symbol('a') + (Symbol('b') * (sympy.tanh((Symbol('c') + (Symbol('d') * x))))**(Integer(3)))))**(Integer(-1))), x)),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)**2/(a + b*tanh(c + d*x)**3),
        variable=x,
        num_steps=8,
        integral=-coth(c + d*x)/(a*d) + b**(sympy.S(1)/3)*log(a**(sympy.S(1)/3) + b**(sympy.S(1)/3)*tanh(c + d*x))/(3*a**(sympy.S(4)/3)*d) - b**(sympy.S(1)/3)*log(a**(sympy.S(2)/3) - a**(sympy.S(1)/3)*b**(sympy.S(1)/3)*tanh(c + d*x) + b**(sympy.S(2)/3)*tanh(c + d*x)**2)/(6*a**(sympy.S(4)/3)*d) + sqrt(3)*b**(sympy.S(1)/3)*atan(sqrt(3)*(a**(sympy.S(1)/3) - 2*b**(sympy.S(1)/3)*tanh(c + d*x))/(3*a**(sympy.S(1)/3)))/(3*a**(sympy.S(4)/3)*d),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)**3/(a + b*tanh(c + d*x)**3),
        variable=x,
        num_steps=0,
        integral=((Integer(-1) * sympy.I) * sympy.Function('Unintegrable')(((sympy.I * (sympy.csch((Symbol('c') + (Symbol('d') * x))))**(Integer(3))) * ((Symbol('a') + (Symbol('b') * (sympy.tanh((Symbol('c') + (Symbol('d') * x))))**(Integer(3)))))**(Integer(-1))), x)),
    ),
    RubiTestSuiteCase(
        integrand=csch(c + d*x)**4/(a + b*tanh(c + d*x)**3),
        variable=x,
        num_steps=12,
        integral=-coth(c + d*x)**3/(3*a*d) + coth(c + d*x)/(a*d) + b*log(a + b*tanh(c + d*x)**3)/(3*a**2*d) - b*log(tanh(c + d*x))/(a**2*d) - b**(sympy.S(1)/3)*log(a**(sympy.S(1)/3) + b**(sympy.S(1)/3)*tanh(c + d*x))/(3*a**(sympy.S(4)/3)*d) + b**(sympy.S(1)/3)*log(a**(sympy.S(2)/3) - a**(sympy.S(1)/3)*b**(sympy.S(1)/3)*tanh(c + d*x) + b**(sympy.S(2)/3)*tanh(c + d*x)**2)/(6*a**(sympy.S(4)/3)*d) - sqrt(3)*b**(sympy.S(1)/3)*atan(sqrt(3)*(a**(sympy.S(1)/3) - 2*b**(sympy.S(1)/3)*tanh(c + d*x))/(3*a**(sympy.S(1)/3)))/(3*a**(sympy.S(4)/3)*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*cosh(c + d*x)**4,
        variable=x,
        num_steps=4,
        integral=x*(3*a/8 - b/8) + (a + b)*sinh(c + d*x)*cosh(c + d*x)**3/(4*d) + (3*a - b)*sinh(c + d*x)*cosh(c + d*x)/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*cosh(c + d*x)**3,
        variable=x,
        num_steps=2,
        integral=a*sinh(c + d*x)/d + (a + b)*sinh(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*cosh(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=x*(a/2 - b/2) + (a + b)*sinh(c + d*x)*cosh(c + d*x)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*cosh(c + d*x),
        variable=x,
        num_steps=3,
        integral=-b*atan(sinh(c + d*x))/d + (a + b)*sinh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*sech(c + d*x),
        variable=x,
        num_steps=3,
        integral=-b*tanh(c + d*x)*sech(c + d*x)/(2*d) + (2*a + b)*atan(sinh(c + d*x))/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*sech(c + d*x)**2,
        variable=x,
        num_steps=2,
        integral=a*tanh(c + d*x)/d + b*tanh(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*sech(c + d*x)**3,
        variable=x,
        num_steps=4,
        integral=-b*tanh(c + d*x)*sech(c + d*x)**3/(4*d) + (4*a + b)*tanh(c + d*x)*sech(c + d*x)/(8*d) + (4*a + b)*atan(sinh(c + d*x))/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*sech(c + d*x)**4,
        variable=x,
        num_steps=3,
        integral=a*tanh(c + d*x)/d - b*tanh(c + d*x)**5/(5*d) - (a - b)*tanh(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*cosh(c + d*x)**4,
        variable=x,
        num_steps=4,
        integral=x*(3*a**2/8 - a*b/4 + 3*b**2/8) + (a + b)*(a + b*tanh(c + d*x)**2)*sinh(c + d*x)*cosh(c + d*x)**3/(4*d) + (3*a**2 - 3*b**2)*sinh(c + d*x)*cosh(c + d*x)/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*cosh(c + d*x)**3,
        variable=x,
        num_steps=4,
        integral=b**2*atan(sinh(c + d*x))/d + (a + b)**2*sinh(c + d*x)**3/(3*d) + (a**2 - b**2)*sinh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*cosh(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=b**2*tanh(c + d*x)/d + x*(a/2 - 3*b/2)*(a + b) + (a + b)**2*sinh(c + d*x)*cosh(c + d*x)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*cosh(c + d*x),
        variable=x,
        num_steps=5,
        integral=b**2*tanh(c + d*x)*sech(c + d*x)/(2*d) - b*(4*a + 3*b)*atan(sinh(c + d*x))/(2*d) + (a + b)**2*sinh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*sech(c + d*x),
        variable=x,
        num_steps=4,
        integral=-b*(a + (a + b)*sinh(c + d*x)**2)*tanh(c + d*x)*sech(c + d*x)**3/(4*d) - 3*b*(2*a + b)*tanh(c + d*x)*sech(c + d*x)/(8*d) + (8*a**2 + 8*a*b + 3*b**2)*atan(sinh(c + d*x))/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*sech(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=a**2*tanh(c + d*x)/d + 2*a*b*tanh(c + d*x)**3/(3*d) + b**2*tanh(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*sech(c + d*x)**3,
        variable=x,
        num_steps=5,
        integral=-b*(a + (a + b)*sinh(c + d*x)**2)*tanh(c + d*x)*sech(c + d*x)**5/(6*d) - b*(8*a + 3*b)*tanh(c + d*x)*sech(c + d*x)**3/(24*d) + (8*a**2 + 4*a*b + b**2)*tanh(c + d*x)*sech(c + d*x)/(16*d) + (8*a**2 + 4*a*b + b**2)*atan(sinh(c + d*x))/(16*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*sech(c + d*x)**4,
        variable=x,
        num_steps=3,
        integral=a**2*tanh(c + d*x)/d - a*(a - 2*b)*tanh(c + d*x)**3/(3*d) - b**2*tanh(c + d*x)**7/(7*d) - b*(2*a - b)*tanh(c + d*x)**5/(5*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*cosh(c + d*x)**4,
        variable=x,
        num_steps=6,
        integral=-b**3*tanh(c + d*x)/d + x*(3*a/8 + 3*b/8)*(a**2 - 2*a*b + 5*b**2) + (a + b)**3*sinh(c + d*x)*cosh(c + d*x)**3/(4*d) + (a + b)**2*(3*a - 9*b)*sinh(c + d*x)*cosh(c + d*x)/(8*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*cosh(c + d*x)**3,
        variable=x,
        num_steps=5,
        integral=-b**3*tanh(c + d*x)*sech(c + d*x)/(2*d) + b**2*(6*a + 5*b)*atan(sinh(c + d*x))/(2*d) + (a - 2*b)*(a + b)**2*sinh(c + d*x)/d + (a + b)**3*sinh(c + d*x)**3/(3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*cosh(c + d*x)**2,
        variable=x,
        num_steps=5,
        integral=b**3*tanh(c + d*x)**3/(3*d) + b**2*(3*a + 2*b)*tanh(c + d*x)/d + x*(a/2 - 5*b/2)*(a + b)**2 + (a + b)**3*sinh(c + d*x)*cosh(c + d*x)/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*cosh(c + d*x),
        variable=x,
        num_steps=6,
        integral=-b**3*tanh(c + d*x)*sech(c + d*x)**3/(4*d) + 3*b**2*(4*a + 3*b)*tanh(c + d*x)*sech(c + d*x)/(8*d) - 3*b*(4*(a + b)**2 + (2*a + b)**2)*atan(sinh(c + d*x))/(8*d) + (a + b)**3*sinh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*sech(c + d*x),
        variable=x,
        num_steps=5,
        integral=-b*(a + (a + b)*sinh(c + d*x)**2)**2*tanh(c + d*x)*sech(c + d*x)**5/(6*d) - 5*b*(a + (a + b)*sinh(c + d*x)**2)*(2*a + b)*tanh(c + d*x)*sech(c + d*x)**3/(24*d) - b*(44*a**2 + 44*a*b + 15*b**2)*tanh(c + d*x)*sech(c + d*x)/(48*d) + (2*a + b)*(8*a**2 + 8*a*b + 5*b**2)*atan(sinh(c + d*x))/(16*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*sech(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=a**3*tanh(c + d*x)/d + a**2*b*tanh(c + d*x)**3/d + 3*a*b**2*tanh(c + d*x)**5/(5*d) + b**3*tanh(c + d*x)**7/(7*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*sech(c + d*x)**3,
        variable=x,
        num_steps=6,
        integral=-b*(a + (a + b)*sinh(c + d*x)**2)**2*tanh(c + d*x)*sech(c + d*x)**7/(8*d) - b*(a + (a + b)*sinh(c + d*x)**2)*(12*a + 5*b)*tanh(c + d*x)*sech(c + d*x)**5/(48*d) - b*(72*a**2 + 52*a*b + 15*b**2)*tanh(c + d*x)*sech(c + d*x)**3/(192*d) + (64*a**3 + 48*a**2*b + 24*a*b**2 + 5*b**3)*tanh(c + d*x)*sech(c + d*x)/(128*d) + (64*a**3 + 48*a**2*b + 24*a*b**2 + 5*b**3)*atan(sinh(c + d*x))/(128*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*sech(c + d*x)**4,
        variable=x,
        num_steps=3,
        integral=a**3*tanh(c + d*x)/d - a**2*(a - 3*b)*tanh(c + d*x)**3/(3*d) - 3*a*b*(a - b)*tanh(c + d*x)**5/(5*d) - b**3*tanh(c + d*x)**9/(9*d) - b**2*(3*a - b)*tanh(c + d*x)**7/(7*d),
    ),
    RubiTestSuiteCase(
        integrand=cosh(c + d*x)**4/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=6,
        integral=x*(3*a**2 + 10*a*b + 15*b**2)/(8*(a + b)**3) + sinh(c + d*x)*cosh(c + d*x)**3/(d*(4*a + 4*b)) + (3*a + 7*b)*sinh(c + d*x)*cosh(c + d*x)/(8*d*(a + b)**2) + b**(sympy.S(5)/2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(sqrt(a)*d*(a + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=cosh(c + d*x)**3/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=4,
        integral=sinh(c + d*x)**3/(d*(3*a + 3*b)) + (a + 2*b)*sinh(c + d*x)/(d*(a + b)**2) + b**2*atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(sqrt(a)*d*(a + b)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cosh(c + d*x)**2/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=5,
        integral=x*(a + 3*b)/(2*(a + b)**2) + sinh(c + d*x)*cosh(c + d*x)/(d*(2*a + 2*b)) + b**(sympy.S(3)/2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(sqrt(a)*d*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=cosh(c + d*x)/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=3,
        integral=sinh(c + d*x)/(d*(a + b)) + b*atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(sqrt(a)*d*(a + b)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=2,
        integral=atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(sqrt(a)*d*sqrt(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**2/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=2,
        integral=atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(sqrt(a)*sqrt(b)*d),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**3/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=4,
        integral=-atan(sinh(c + d*x))/(b*d) + sqrt(a + b)*atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(sqrt(a)*b*d),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**4/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=3,
        integral=-tanh(c + d*x)/(b*d) + (a + b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(sqrt(a)*b**(sympy.S(3)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**5/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=5,
        integral=-tanh(c + d*x)*sech(c + d*x)/(2*b*d) - (2*a + 3*b)*atan(sinh(c + d*x))/(2*b**2*d) + (a + b)**(sympy.S(3)/2)*atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(sqrt(a)*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**6/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=4,
        integral=tanh(c + d*x)**3/(3*b*d) - (a + 2*b)*tanh(c + d*x)/(b**2*d) + (a + b)**2*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(sqrt(a)*b**(sympy.S(5)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=cosh(c + d*x)**3/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=5,
        integral=sinh(c + d*x)**3/(3*d*(a + b)**2) + (a + 3*b)*sinh(c + d*x)/(d*(a + b)**3) + b**3*sinh(c + d*x)/(2*a*d*(a + b)**3*(a + (a + b)*sinh(c + d*x)**2)) + b**2*(6*a + b)*atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(2*a**(sympy.S(3)/2)*d*(a + b)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=cosh(c + d*x)**2/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=6,
        integral=x*(a + 5*b)/(2*(a + b)**3) + sinh(c + d*x)*cosh(c + d*x)/(d*(a + b*tanh(c + d*x)**2)*(2*a + 2*b)) - b*(a - b)*tanh(c + d*x)/(2*a*d*(a + b)**2*(a + b*tanh(c + d*x)**2)) + b**(sympy.S(3)/2)*(5*a + b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(2*a**(sympy.S(3)/2)*d*(a + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=cosh(c + d*x)/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=5,
        integral=sinh(c + d*x)/(d*(a + b)**2) + b**2*sinh(c + d*x)/(2*a*d*(a + b)**2*(a + (a + b)*sinh(c + d*x)**2)) + b*(4*a + b)*atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(2*a**(sympy.S(3)/2)*d*(a + b)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=3,
        integral=b*sinh(c + d*x)/(2*a*d*(a + b)*(a + (a + b)*sinh(c + d*x)**2)) + (2*a + b)*atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(2*a**(sympy.S(3)/2)*d*(a + b)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**2/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=3,
        integral=tanh(c + d*x)/(2*a*d*(a + b*tanh(c + d*x)**2)) + atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(2*a**(sympy.S(3)/2)*sqrt(b)*d),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**3/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=3,
        integral=sinh(c + d*x)/(2*a*d*(a + (a + b)*sinh(c + d*x)**2)) + atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(2*a**(sympy.S(3)/2)*d*sqrt(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**4/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=3,
        integral=(a + b)*tanh(c + d*x)/(2*a*b*d*(a + b*tanh(c + d*x)**2)) - (a - b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(2*a**(sympy.S(3)/2)*b**(sympy.S(3)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**5/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=5,
        integral=atan(sinh(c + d*x))/(b**2*d) + (a + b)*sinh(c + d*x)/(2*a*b*d*(a + (a + b)*sinh(c + d*x)**2)) - sqrt(a + b)*(2*a - b)*atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(2*a**(sympy.S(3)/2)*b**2*d),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**6/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=5,
        integral=tanh(c + d*x)/(b**2*d) + (a + b)**2*tanh(c + d*x)/(2*a*b**2*d*(a + b*tanh(c + d*x)**2)) - (a + b)*(3*a - b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(2*a**(sympy.S(3)/2)*b**(sympy.S(5)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**7/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=6,
        integral=-tanh(c + d*x)*sech(c + d*x)/(2*b*d*(a + (a + b)*sinh(c + d*x)**2)) + (4*a + 5*b)*atan(sinh(c + d*x))/(2*b**3*d) + (a + b)*(2*a + b)*sinh(c + d*x)/(2*a*b**2*d*(a + (a + b)*sinh(c + d*x)**2)) - (a + b)**(sympy.S(3)/2)*(4*a - b)*atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(2*a**(sympy.S(3)/2)*b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=cosh(c + d*x)**2/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=7,
        integral=x*(a + 7*b)/(2*(a + b)**4) + sinh(c + d*x)*cosh(c + d*x)/(d*(a + b*tanh(c + d*x)**2)**2*(2*a + 2*b)) - b*(2*a - b)*tanh(c + d*x)/(4*a*d*(a + b)**2*(a + b*tanh(c + d*x)**2)**2) - b*(a - 3*b)*(4*a + b)*tanh(c + d*x)/(8*a**2*d*(a + b)**3*(a + b*tanh(c + d*x)**2)) + b**(sympy.S(3)/2)*(35*a**2 + 14*a*b + 3*b**2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(8*a**(sympy.S(5)/2)*d*(a + b)**4),
    ),
    RubiTestSuiteCase(
        integrand=cosh(c + d*x)/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=6,
        integral=sinh(c + d*x)/(d*(a + b)**3) + b**3*sinh(c + d*x)/(4*a*d*(a + b)**3*(a + (a + b)*sinh(c + d*x)**2)**2) + 3*b**2*(4*a + b)*sinh(c + d*x)/(8*a**2*d*(a + b)**3*(a + (a + b)*sinh(c + d*x)**2)) + 3*b*(8*a**2 + 4*a*b + b**2)*atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(8*a**(sympy.S(5)/2)*d*(a + b)**(sympy.S(7)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=4,
        integral=b*sinh(c + d*x)*cosh(c + d*x)**2/(4*a*d*(a + b)*(a + (a + b)*sinh(c + d*x)**2)**2) + 3*b*(2*a + b)*sinh(c + d*x)/(8*a**2*d*(a + b)**2*(a + (a + b)*sinh(c + d*x)**2)) + (8*a**2 + 8*a*b + 3*b**2)*atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(8*a**(sympy.S(5)/2)*d*(a + b)**(sympy.S(5)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**2/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=4,
        integral=tanh(c + d*x)/(4*a*d*(a + b*tanh(c + d*x)**2)**2) + 3*tanh(c + d*x)/(8*a**2*d*(a + b*tanh(c + d*x)**2)) + 3*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(8*a**(sympy.S(5)/2)*sqrt(b)*d),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**3/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=4,
        integral=b*sinh(c + d*x)/(4*a*d*(a + b)*(a + (a + b)*sinh(c + d*x)**2)**2) + (4*a + 3*b)*sinh(c + d*x)/(8*a**2*d*(a + b)*(a + (a + b)*sinh(c + d*x)**2)) + (4*a + 3*b)*atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(8*a**(sympy.S(5)/2)*d*(a + b)**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**4/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=4,
        integral=(a + b)*tanh(c + d*x)/(4*a*b*d*(a + b*tanh(c + d*x)**2)**2) - (a - 3*b)*tanh(c + d*x)/(8*a**2*b*d*(a + b*tanh(c + d*x)**2)) - (a - 3*b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(8*a**(sympy.S(5)/2)*b**(sympy.S(3)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**5/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=4,
        integral=sinh(c + d*x)/(4*a*d*(a + (a + b)*sinh(c + d*x)**2)**2) + 3*sinh(c + d*x)/(8*a**2*d*(a + (a + b)*sinh(c + d*x)**2)) + 3*atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(8*a**(sympy.S(5)/2)*d*sqrt(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**6/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=4,
        integral=(-3/b**2 + 3/a**2)*tanh(c + d*x)/(8*d*(a + b*tanh(c + d*x)**2)) + (a + b)*tanh(c + d*x)*sech(c + d*x)**2/(4*a*b*d*(a + b*tanh(c + d*x)**2)**2) + (3*a**2 - 2*a*b + 3*b**2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(8*a**(sympy.S(5)/2)*b**(sympy.S(5)/2)*d),
    ),
    RubiTestSuiteCase(
        integrand=sech(c + d*x)**7/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=6,
        integral=-atan(sinh(c + d*x))/(b**3*d) + (a + b)*sinh(c + d*x)/(4*a*b*d*(a + (a + b)*sinh(c + d*x)**2)**2) - (a + b)*(4*a - 3*b)*sinh(c + d*x)/(8*a**2*b**2*d*(a + (a + b)*sinh(c + d*x)**2)) + sqrt(a + b)*(8*a**2 - 4*a*b + 3*b**2)*atan(sqrt(a + b)*sinh(c + d*x)/sqrt(a))/(8*a**(sympy.S(5)/2)*b**3*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*tanh(c + d*x)**4,
        variable=x,
        num_steps=4,
        integral=-b*tanh(c + d*x)**5/(5*d) + x*(a + b) - (a + b)*tanh(c + d*x)**3/(3*d) - (a + b)*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*tanh(c + d*x)**3,
        variable=x,
        num_steps=3,
        integral=-b*tanh(c + d*x)**4/(4*d) + (a + b)*log(cosh(c + d*x))/d - (a + b)*tanh(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*tanh(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=-b*tanh(c + d*x)**3/(3*d) + x*(a + b) - (a + b)*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*tanh(c + d*x),
        variable=x,
        num_steps=2,
        integral=-b*tanh(c + d*x)**2/(2*d) + (a + b)*log(cosh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=a + b*tanh(c + d*x)**2,
        variable=x,
        num_steps=3,
        integral=a*x + b*x - b*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*coth(c + d*x),
        variable=x,
        num_steps=3,
        integral=a*log(sinh(c + d*x))/d + b*log(cosh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*coth(c + d*x)**2,
        variable=x,
        num_steps=2,
        integral=-a*coth(c + d*x)/d + x*(a + b),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*coth(c + d*x)**3,
        variable=x,
        num_steps=3,
        integral=-a*coth(c + d*x)**2/(2*d) + (a + b)*log(sinh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*coth(c + d*x)**4,
        variable=x,
        num_steps=4,
        integral=-a*coth(c + d*x)**3/(3*d) + x*(a + b) - (a + b)*coth(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)*coth(c + d*x)**5,
        variable=x,
        num_steps=4,
        integral=-a*coth(c + d*x)**4/(4*d) + (a + b)*log(sinh(c + d*x))/d - (a + b)*coth(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*tanh(c + d*x)**4,
        variable=x,
        num_steps=4,
        integral=-b**2*tanh(c + d*x)**7/(7*d) - b*(2*a + b)*tanh(c + d*x)**5/(5*d) + x*(a + b)**2 - (a + b)**2*tanh(c + d*x)**3/(3*d) - (a + b)**2*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*tanh(c + d*x)**3,
        variable=x,
        num_steps=4,
        integral=-b**2*tanh(c + d*x)**6/(6*d) - b*(2*a + b)*tanh(c + d*x)**4/(4*d) + (a + b)**2*log(cosh(c + d*x))/d - (a + b)**2*tanh(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*tanh(c + d*x)**2,
        variable=x,
        num_steps=4,
        integral=-b**2*tanh(c + d*x)**5/(5*d) - b*(2*a + b)*tanh(c + d*x)**3/(3*d) + x*(a + b)**2 - (a + b)**2*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*tanh(c + d*x),
        variable=x,
        num_steps=4,
        integral=-b*(a + b)*tanh(c + d*x)**2/(2*d) + (a + b)**2*log(cosh(c + d*x))/d - (a + b*tanh(c + d*x)**2)**2/(4*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=4,
        integral=-b**2*tanh(c + d*x)**3/(3*d) - b*(2*a + b)*tanh(c + d*x)/d + x*(a + b)**2,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*coth(c + d*x),
        variable=x,
        num_steps=4,
        integral=a**2*log(tanh(c + d*x))/d - b**2*tanh(c + d*x)**2/(2*d) + (a + b)**2*log(cosh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*coth(c + d*x)**2,
        variable=x,
        num_steps=4,
        integral=-a**2*coth(c + d*x)/d - b**2*tanh(c + d*x)/d + x*(a + b)**2,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*coth(c + d*x)**3,
        variable=x,
        num_steps=4,
        integral=-a**2*coth(c + d*x)**2/(2*d) + a*(a + 2*b)*log(tanh(c + d*x))/d + (a + b)**2*log(cosh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*coth(c + d*x)**4,
        variable=x,
        num_steps=4,
        integral=-a**2*coth(c + d*x)**3/(3*d) - a*(a + 2*b)*coth(c + d*x)/d + x*(a + b)**2,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*coth(c + d*x)**5,
        variable=x,
        num_steps=4,
        integral=-a**2*coth(c + d*x)**4/(4*d) - a*(a + 2*b)*coth(c + d*x)**2/(2*d) + (a + b)**2*log(cosh(c + d*x))/d + (a + b)**2*log(tanh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*coth(c + d*x)**6,
        variable=x,
        num_steps=4,
        integral=-a**2*coth(c + d*x)**5/(5*d) - a*(a + 2*b)*coth(c + d*x)**3/(3*d) + x*(a + b)**2 - (a + b)**2*coth(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**2*coth(c + d*x)**7,
        variable=x,
        num_steps=4,
        integral=-a**2*coth(c + d*x)**6/(6*d) - a*(a + 2*b)*coth(c + d*x)**4/(4*d) + (a + b)**2*log(cosh(c + d*x))/d + (a + b)**2*log(tanh(c + d*x))/d - (a + b)**2*coth(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*tanh(c + d*x)**4,
        variable=x,
        num_steps=4,
        integral=-b**3*tanh(c + d*x)**9/(9*d) - b**2*(3*a + b)*tanh(c + d*x)**7/(7*d) - b*(3*a**2 + 3*a*b + b**2)*tanh(c + d*x)**5/(5*d) + x*(a + b)**3 - (a + b)**3*tanh(c + d*x)**3/(3*d) - (a + b)**3*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*tanh(c + d*x)**3,
        variable=x,
        num_steps=4,
        integral=-b**3*tanh(c + d*x)**8/(8*d) - b**2*(3*a + b)*tanh(c + d*x)**6/(6*d) - b*(3*a**2 + 3*a*b + b**2)*tanh(c + d*x)**4/(4*d) + (a + b)**3*log(cosh(c + d*x))/d - (a + b)**3*tanh(c + d*x)**2/(2*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*tanh(c + d*x)**2,
        variable=x,
        num_steps=4,
        integral=-b**3*tanh(c + d*x)**7/(7*d) - b**2*(3*a + b)*tanh(c + d*x)**5/(5*d) - b*(3*a**2 + 3*a*b + b**2)*tanh(c + d*x)**3/(3*d) + x*(a + b)**3 - (a + b)**3*tanh(c + d*x)/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*tanh(c + d*x),
        variable=x,
        num_steps=4,
        integral=-b*(a + b)**2*tanh(c + d*x)**2/(2*d) + (a + b)**3*log(cosh(c + d*x))/d - (a + b)*(a + b*tanh(c + d*x)**2)**2/(4*d) - (a + b*tanh(c + d*x)**2)**3/(6*d),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=4,
        integral=-b**3*tanh(c + d*x)**5/(5*d) - b**2*(3*a + b)*tanh(c + d*x)**3/(3*d) - b*(3*a**2 + 3*a*b + b**2)*tanh(c + d*x)/d + x*(a + b)**3,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*coth(c + d*x),
        variable=x,
        num_steps=4,
        integral=a**3*log(tanh(c + d*x))/d - b**3*tanh(c + d*x)**4/(4*d) - b**2*(3*a + b)*tanh(c + d*x)**2/(2*d) + (a + b)**3*log(cosh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*coth(c + d*x)**2,
        variable=x,
        num_steps=4,
        integral=-a**3*coth(c + d*x)/d - b**3*tanh(c + d*x)**3/(3*d) - b**2*(3*a + b)*tanh(c + d*x)/d + x*(a + b)**3,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*coth(c + d*x)**3,
        variable=x,
        num_steps=4,
        integral=-a**3*coth(c + d*x)**2/(2*d) + a**2*(a + 3*b)*log(tanh(c + d*x))/d - b**3*tanh(c + d*x)**2/(2*d) + (a + b)**3*log(cosh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*coth(c + d*x)**4,
        variable=x,
        num_steps=4,
        integral=-a**3*coth(c + d*x)**3/(3*d) - a**2*(a + 3*b)*coth(c + d*x)/d - b**3*tanh(c + d*x)/d + x*(a + b)**3,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*coth(c + d*x)**5,
        variable=x,
        num_steps=4,
        integral=-a**3*coth(c + d*x)**4/(4*d) - a**2*(a + 3*b)*coth(c + d*x)**2/(2*d) + a*(a**2 + 3*a*b + 3*b**2)*log(tanh(c + d*x))/d + (a + b)**3*log(cosh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*coth(c + d*x)**6,
        variable=x,
        num_steps=4,
        integral=-a**3*coth(c + d*x)**5/(5*d) - a**2*(a + 3*b)*coth(c + d*x)**3/(3*d) - a*(a**2 + 3*a*b + 3*b**2)*coth(c + d*x)/d + x*(a + b)**3,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**3*coth(c + d*x)**7,
        variable=x,
        num_steps=4,
        integral=-a**3*coth(c + d*x)**6/(6*d) - a**2*(a + 3*b)*coth(c + d*x)**4/(4*d) - a*(a**2 + 3*a*b + 3*b**2)*coth(c + d*x)**2/(2*d) + (a + b)**3*log(cosh(c + d*x))/d + (a + b)**3*log(tanh(c + d*x))/d,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**4,
        variable=x,
        num_steps=4,
        integral=-b**4*tanh(c + d*x)**7/(7*d) - b**3*(4*a + b)*tanh(c + d*x)**5/(5*d) - b**2*(6*a**2 + 4*a*b + b**2)*tanh(c + d*x)**3/(3*d) - b*(2*a + b)*(2*a**2 + 2*a*b + b**2)*tanh(c + d*x)/d + x*(a + b)**4,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**5,
        variable=x,
        num_steps=4,
        integral=-b**5*tanh(c + d*x)**9/(9*d) - b**4*(5*a + b)*tanh(c + d*x)**7/(7*d) - b**3*(10*a**2 + 5*a*b + b**2)*tanh(c + d*x)**5/(5*d) - b**2*(10*a**3 + 10*a**2*b + 5*a*b**2 + b**3)*tanh(c + d*x)**3/(3*d) - b*(5*a**4 + 10*a**3*b + 10*a**2*b**2 + 5*a*b**3 + b**4)*tanh(c + d*x)/d + x*(a + b)**5,
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**5/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=4,
        integral=a**2*log(a + b*tanh(c + d*x)**2)/(2*b**2*d*(a + b)) + log(cosh(c + d*x))/(d*(a + b)) - tanh(c + d*x)**2/(2*b*d),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**4/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=5,
        integral=a**(sympy.S(3)/2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(b**(sympy.S(3)/2)*d*(a + b)) + x/(a + b) - tanh(c + d*x)/(b*d),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**3/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=4,
        integral=-a*log(a + b*tanh(c + d*x)**2)/(2*b*d*(a + b)) + log(cosh(c + d*x))/(d*(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**2/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=4,
        integral=-sqrt(a)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(sqrt(b)*d*(a + b)) + x/(a + b),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=5,
        integral=log(a + b*tanh(c + d*x)**2)/(d*(2*a + 2*b)) + log(cosh(c + d*x))/(d*(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=1/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=3,
        integral=x/(a + b) + sqrt(b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(sqrt(a)*d*(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=4,
        integral=log(cosh(c + d*x))/(d*(a + b)) - b*log(a + b*tanh(c + d*x)**2)/(2*a*d*(a + b)) + log(tanh(c + d*x))/(a*d),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)**2/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=5,
        integral=x/(a + b) - coth(c + d*x)/(a*d) - b**(sympy.S(3)/2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(a**(sympy.S(3)/2)*d*(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)**3/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=4,
        integral=log(cosh(c + d*x))/(d*(a + b)) - coth(c + d*x)**2/(2*a*d) + b**2*log(a + b*tanh(c + d*x)**2)/(2*a**2*d*(a + b)) + (a - b)*log(tanh(c + d*x))/(a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)**4/(a + b*tanh(c + d*x)**2),
        variable=x,
        num_steps=6,
        integral=x/(a + b) - coth(c + d*x)**3/(3*a*d) - (a - b)*coth(c + d*x)/(a**2*d) + b**(sympy.S(5)/2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(a**(sympy.S(5)/2)*d*(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**5/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=4,
        integral=-a**2/(2*b**2*d*(a + b)*(a + b*tanh(c + d*x)**2)) - a*(a + 2*b)*log(a + b*tanh(c + d*x)**2)/(2*b**2*d*(a + b)**2) + log(cosh(c + d*x))/(d*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**4/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=5,
        integral=-sqrt(a)*(a + 3*b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(2*b**(sympy.S(3)/2)*d*(a + b)**2) + a*tanh(c + d*x)/(2*b*d*(a + b)*(a + b*tanh(c + d*x)**2)) + x/(a + b)**2,
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**3/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=4,
        integral=a/(2*b*d*(a + b)*(a + b*tanh(c + d*x)**2)) + log(a + b*tanh(c + d*x)**2)/(2*d*(a + b)**2) + log(cosh(c + d*x))/(d*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**2/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=5,
        integral=x/(a + b)**2 - tanh(c + d*x)/(d*(a + b*tanh(c + d*x)**2)*(2*a + 2*b)) - (a - b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(2*sqrt(a)*sqrt(b)*d*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=4,
        integral=-1/(d*(a + b*tanh(c + d*x)**2)*(2*a + 2*b)) + log(a + b*tanh(c + d*x)**2)/(2*d*(a + b)**2) + log(cosh(c + d*x))/(d*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**(-2),
        variable=x,
        num_steps=5,
        integral=x/(a + b)**2 + b*tanh(c + d*x)/(2*a*d*(a + b)*(a + b*tanh(c + d*x)**2)) + sqrt(b)*(3*a + b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(2*a**(sympy.S(3)/2)*d*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=4,
        integral=log(cosh(c + d*x))/(d*(a + b)**2) + b/(2*a*d*(a + b)*(a + b*tanh(c + d*x)**2)) - b*(2*a + b)*log(a + b*tanh(c + d*x)**2)/(2*a**2*d*(a + b)**2) + log(tanh(c + d*x))/(a**2*d),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)**2/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=6,
        integral=x/(a + b)**2 + b*coth(c + d*x)/(2*a*d*(a + b)*(a + b*tanh(c + d*x)**2)) - (2*a + 3*b)*coth(c + d*x)/(2*a**2*d*(a + b)) - b**(sympy.S(3)/2)*(5*a + 3*b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(2*a**(sympy.S(5)/2)*d*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)**3/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=4,
        integral=log(cosh(c + d*x))/(d*(a + b)**2) - b**2/(2*a**2*d*(a + b)*(a + b*tanh(c + d*x)**2)) - coth(c + d*x)**2/(2*a**2*d) + b**2*(3*a + 2*b)*log(a + b*tanh(c + d*x)**2)/(2*a**3*d*(a + b)**2) + (a - 2*b)*log(tanh(c + d*x))/(a**3*d),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)**4/(a + b*tanh(c + d*x)**2)**2,
        variable=x,
        num_steps=7,
        integral=x/(a + b)**2 + b*coth(c + d*x)**3/(2*a*d*(a + b)*(a + b*tanh(c + d*x)**2)) - (2*a + 5*b)*coth(c + d*x)**3/(6*a**2*d*(a + b)) - (2*a**2 - 2*a*b - 5*b**2)*coth(c + d*x)/(2*a**3*d*(a + b)) + b**(sympy.S(5)/2)*(7*a + 5*b)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(2*a**(sympy.S(7)/2)*d*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**6/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=6,
        integral=-sqrt(a)*(3*a**2 + 10*a*b + 15*b**2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(8*b**(sympy.S(5)/2)*d*(a + b)**3) + a*tanh(c + d*x)**3/(4*b*d*(a + b)*(a + b*tanh(c + d*x)**2)**2) + a*(3*a + 7*b)*tanh(c + d*x)/(8*b**2*d*(a + b)**2*(a + b*tanh(c + d*x)**2)) + x/(a + b)**3,
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**5/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=4,
        integral=-a**2/(4*b**2*d*(a + b)*(a + b*tanh(c + d*x)**2)**2) + a*(a + 2*b)/(2*b**2*d*(a + b)**2*(a + b*tanh(c + d*x)**2)) + log(a + b*tanh(c + d*x)**2)/(2*d*(a + b)**3) + log(cosh(c + d*x))/(d*(a + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**4/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=6,
        integral=a*tanh(c + d*x)/(4*b*d*(a + b)*(a + b*tanh(c + d*x)**2)**2) + x/(a + b)**3 - (a + 5*b)*tanh(c + d*x)/(8*b*d*(a + b)**2*(a + b*tanh(c + d*x)**2)) - (a**2 + 6*a*b - 3*b**2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(8*sqrt(a)*b**(sympy.S(3)/2)*d*(a + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**3/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=4,
        integral=a/(4*b*d*(a + b)*(a + b*tanh(c + d*x)**2)**2) - 1/(2*d*(a + b)**2*(a + b*tanh(c + d*x)**2)) + log(a + b*tanh(c + d*x)**2)/(2*d*(a + b)**3) + log(cosh(c + d*x))/(d*(a + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)**2/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=6,
        integral=x/(a + b)**3 - tanh(c + d*x)/(d*(a + b*tanh(c + d*x)**2)**2*(4*a + 4*b)) - (3*a - b)*tanh(c + d*x)/(8*a*d*(a + b)**2*(a + b*tanh(c + d*x)**2)) - (3*a**2 - 6*a*b - b**2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(8*a**(sympy.S(3)/2)*sqrt(b)*d*(a + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=tanh(c + d*x)/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=4,
        integral=-1/(d*(a + b*tanh(c + d*x)**2)**2*(4*a + 4*b)) - 1/(2*d*(a + b)**2*(a + b*tanh(c + d*x)**2)) + log(a + b*tanh(c + d*x)**2)/(2*d*(a + b)**3) + log(cosh(c + d*x))/(d*(a + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**(-3),
        variable=x,
        num_steps=6,
        integral=x/(a + b)**3 + b*tanh(c + d*x)/(4*a*d*(a + b)*(a + b*tanh(c + d*x)**2)**2) + b*(7*a + 3*b)*tanh(c + d*x)/(8*a**2*d*(a + b)**2*(a + b*tanh(c + d*x)**2)) + sqrt(b)*(15*a**2 + 10*a*b + 3*b**2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(8*a**(sympy.S(5)/2)*d*(a + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=4,
        integral=log(cosh(c + d*x))/(d*(a + b)**3) + b/(4*a*d*(a + b)*(a + b*tanh(c + d*x)**2)**2) + b*(2*a + b)/(2*a**2*d*(a + b)**2*(a + b*tanh(c + d*x)**2)) - b*(3*a**2 + 3*a*b + b**2)*log(a + b*tanh(c + d*x)**2)/(2*a**3*d*(a + b)**3) + log(tanh(c + d*x))/(a**3*d),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)**2/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=7,
        integral=x/(a + b)**3 + b*coth(c + d*x)/(4*a*d*(a + b)*(a + b*tanh(c + d*x)**2)**2) + b*(9*a + 5*b)*coth(c + d*x)/(8*a**2*d*(a + b)**2*(a + b*tanh(c + d*x)**2)) - (8*a**2 + 27*a*b + 15*b**2)*coth(c + d*x)/(8*a**3*d*(a + b)**2) - b**(sympy.S(3)/2)*(35*a**2 + 42*a*b + 15*b**2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(8*a**(sympy.S(7)/2)*d*(a + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)**3/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=4,
        integral=log(cosh(c + d*x))/(d*(a + b)**3) - b**2/(4*a**2*d*(a + b)*(a + b*tanh(c + d*x)**2)**2) - b**2*(3*a + 2*b)/(2*a**3*d*(a + b)**2*(a + b*tanh(c + d*x)**2)) - coth(c + d*x)**2/(2*a**3*d) + b**2*(6*a**2 + 8*a*b + 3*b**2)*log(a + b*tanh(c + d*x)**2)/(2*a**4*d*(a + b)**3) + (a - 3*b)*log(tanh(c + d*x))/(a**4*d),
    ),
    RubiTestSuiteCase(
        integrand=coth(c + d*x)**4/(a + b*tanh(c + d*x)**2)**3,
        variable=x,
        num_steps=8,
        integral=x/(a + b)**3 + b*coth(c + d*x)**3/(4*a*d*(a + b)*(a + b*tanh(c + d*x)**2)**2) + b*(11*a + 7*b)*coth(c + d*x)**3/(8*a**2*d*(a + b)**2*(a + b*tanh(c + d*x)**2)) - (8*a**2 + 55*a*b + 35*b**2)*coth(c + d*x)**3/(24*a**3*d*(a + b)**2) - (8*a**3 - 8*a**2*b - 55*a*b**2 - 35*b**3)*coth(c + d*x)/(8*a**4*d*(a + b)**2) + b**(sympy.S(5)/2)*(63*a**2 + 90*a*b + 35*b**2)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(8*a**(sympy.S(9)/2)*d*(a + b)**3),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(c + d*x)**2)**(-4),
        variable=x,
        num_steps=7,
        integral=x/(a + b)**4 + b*tanh(c + d*x)/(6*a*d*(a + b)*(a + b*tanh(c + d*x)**2)**3) + b*(11*a + 5*b)*tanh(c + d*x)/(24*a**2*d*(a + b)**2*(a + b*tanh(c + d*x)**2)**2) + b*(19*a**2 + 16*a*b + 5*b**2)*tanh(c + d*x)/(16*a**3*d*(a + b)**3*(a + b*tanh(c + d*x)**2)) + sqrt(b)*(35*a**3 + 35*a**2*b + 21*a*b**2 + 5*b**3)*atan(sqrt(b)*tanh(c + d*x)/sqrt(a))/(16*a**(sympy.S(7)/2)*d*(a + b)**4),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(1 - tanh(x)**2),
        variable=x,
        num_steps=3,
        integral=asin(tanh(x)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(tanh(x)**2 - 1),
        variable=x,
        num_steps=4,
        integral=-atanh(tanh(x)/sqrt(-sech(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(1 - tanh(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=sqrt(sech(x)**2)*tanh(x)/2 + asin(tanh(x))/2,
    ),
    RubiTestSuiteCase(
        integrand=(tanh(x)**2 - 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=-sqrt(-sech(x)**2)*tanh(x)/2 + atanh(tanh(x)/sqrt(-sech(x)**2))/2,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(1 - tanh(x)**2),
        variable=x,
        num_steps=3,
        integral=tanh(x)/sqrt(sech(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(tanh(x)**2 - 1),
        variable=x,
        num_steps=3,
        integral=tanh(x)/sqrt(-sech(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*tanh(x)**2)*tanh(x)**5,
        variable=x,
        num_steps=7,
        integral=sqrt(a + b)*atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b)) - sqrt(a + b*tanh(x)**2) + (a - b)*(a + b*tanh(x)**2)**(sympy.S(3)/2)/(3*b**2) - (a + b*tanh(x)**2)**(sympy.S(5)/2)/(5*b**2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*tanh(x)**2)*tanh(x)**4,
        variable=x,
        num_steps=8,
        integral=sqrt(a + b)*atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2)) - sqrt(a + b*tanh(x)**2)*tanh(x)**3/4 - (a + 4*b)*sqrt(a + b*tanh(x)**2)*tanh(x)/(8*b) + (a**2 - 4*a*b - 8*b**2)*atanh(sqrt(b)*tanh(x)/sqrt(a + b*tanh(x)**2))/(8*b**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*tanh(x)**2)*tanh(x)**3,
        variable=x,
        num_steps=6,
        integral=sqrt(a + b)*atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b)) - sqrt(a + b*tanh(x)**2) - (a + b*tanh(x)**2)**(sympy.S(3)/2)/(3*b),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*tanh(x)**2)*tanh(x)**2,
        variable=x,
        num_steps=7,
        integral=sqrt(a + b)*atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2)) - sqrt(a + b*tanh(x)**2)*tanh(x)/2 - (a + 2*b)*atanh(sqrt(b)*tanh(x)/sqrt(a + b*tanh(x)**2))/(2*sqrt(b)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*tanh(x)**2)*tanh(x),
        variable=x,
        num_steps=5,
        integral=sqrt(a + b)*atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b)) - sqrt(a + b*tanh(x)**2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*tanh(x)**2),
        variable=x,
        num_steps=6,
        integral=-sqrt(b)*atanh(sqrt(b)*tanh(x)/sqrt(a + b*tanh(x)**2)) + sqrt(a + b)*atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*tanh(x)**2)*coth(x),
        variable=x,
        num_steps=7,
        integral=-sqrt(a)*atanh(sqrt(a + b*tanh(x)**2)/sqrt(a)) + sqrt(a + b)*atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*tanh(x)**2)*coth(x)**2,
        variable=x,
        num_steps=5,
        integral=sqrt(a + b)*atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2)) - sqrt(a + b*tanh(x)**2)*coth(x),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*tanh(x)**2)*coth(x)**3,
        variable=x,
        num_steps=8,
        integral=sqrt(a + b)*atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b)) - sqrt(a + b*tanh(x)**2)*coth(x)**2/2 - (2*a + b)*atanh(sqrt(a + b*tanh(x)**2)/sqrt(a))/(2*sqrt(a)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*tanh(x)**2)*coth(x)**4,
        variable=x,
        num_steps=6,
        integral=sqrt(a + b)*atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2)) - sqrt(a + b*tanh(x)**2)*coth(x)**3/3 - sqrt(a + b*tanh(x)**2)*(3*a + b)*coth(x)/(3*a),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*tanh(x)**2)*coth(x)**5,
        variable=x,
        num_steps=9,
        integral=sqrt(a + b)*atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b)) - sqrt(a + b*tanh(x)**2)*coth(x)**4/4 - sqrt(a + b*tanh(x)**2)*(4*a + b)*coth(x)**2/(8*a) - (8*a**2 + 4*a*b - b**2)*atanh(sqrt(a + b*tanh(x)**2)/sqrt(a))/(8*a**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(x)**2)**(sympy.S(3)/2)*tanh(x)**3,
        variable=x,
        num_steps=7,
        integral=(a + b)**(sympy.S(3)/2)*atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b)) - (a + b)*sqrt(a + b*tanh(x)**2) - (a + b*tanh(x)**2)**(sympy.S(3)/2)/3 - (a + b*tanh(x)**2)**(sympy.S(5)/2)/(5*b),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(x)**2)**(sympy.S(3)/2)*tanh(x)**2,
        variable=x,
        num_steps=8,
        integral=-b*sqrt(a + b*tanh(x)**2)*tanh(x)**3/4 - (5*a/8 + b/2)*sqrt(a + b*tanh(x)**2)*tanh(x) + (a + b)**(sympy.S(3)/2)*atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2)) - (3*a**2 + 12*a*b + 8*b**2)*atanh(sqrt(b)*tanh(x)/sqrt(a + b*tanh(x)**2))/(8*sqrt(b)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(x)**2)**(sympy.S(3)/2)*tanh(x),
        variable=x,
        num_steps=6,
        integral=(a + b)**(sympy.S(3)/2)*atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b)) - (a + b)*sqrt(a + b*tanh(x)**2) - (a + b*tanh(x)**2)**(sympy.S(3)/2)/3,
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=7,
        integral=-sqrt(b)*(3*a + 2*b)*atanh(sqrt(b)*tanh(x)/sqrt(a + b*tanh(x)**2))/2 - b*sqrt(a + b*tanh(x)**2)*tanh(x)/2 + (a + b)**(sympy.S(3)/2)*atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(x)**2)**(sympy.S(3)/2)*coth(x),
        variable=x,
        num_steps=8,
        integral=-a**(sympy.S(3)/2)*atanh(sqrt(a + b*tanh(x)**2)/sqrt(a)) - b*sqrt(a + b*tanh(x)**2) + (a + b)**(sympy.S(3)/2)*atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(x)**2)**(sympy.S(3)/2)*coth(x)**2,
        variable=x,
        num_steps=7,
        integral=-a*sqrt(a + b*tanh(x)**2)*coth(x) - b**(sympy.S(3)/2)*atanh(sqrt(b)*tanh(x)/sqrt(a + b*tanh(x)**2)) + (a + b)**(sympy.S(3)/2)*atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(tanh(x)**2 + 1),
        variable=x,
        num_steps=5,
        integral=-asinh(tanh(x)) + sqrt(2)*atanh(sqrt(2)*tanh(x)/sqrt(tanh(x)**2 + 1)),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(-tanh(x)**2 - 1),
        variable=x,
        num_steps=6,
        integral=atan(tanh(x)/sqrt(-tanh(x)**2 - 1)) - sqrt(2)*atan(sqrt(2)*tanh(x)/sqrt(-tanh(x)**2 - 1)),
    ),
    RubiTestSuiteCase(
        integrand=(tanh(x)**2 + 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=-sqrt(tanh(x)**2 + 1)*tanh(x)/2 - 5*asinh(tanh(x))/2 + 2*sqrt(2)*atanh(sqrt(2)*tanh(x)/sqrt(tanh(x)**2 + 1)),
    ),
    RubiTestSuiteCase(
        integrand=(-tanh(x)**2 - 1)**(sympy.S(3)/2),
        variable=x,
        num_steps=7,
        integral=sqrt(-tanh(x)**2 - 1)*tanh(x)/2 - 5*atan(tanh(x)/sqrt(-tanh(x)**2 - 1))/2 + 2*sqrt(2)*atan(sqrt(2)*tanh(x)/sqrt(-tanh(x)**2 - 1)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**5/sqrt(a + b*tanh(x)**2),
        variable=x,
        num_steps=6,
        integral=atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b))/sqrt(a + b) + (a - b)*sqrt(a + b*tanh(x)**2)/b**2 - (a + b*tanh(x)**2)**(sympy.S(3)/2)/(3*b**2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**4/sqrt(a + b*tanh(x)**2),
        variable=x,
        num_steps=7,
        integral=atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2))/sqrt(a + b) - sqrt(a + b*tanh(x)**2)*tanh(x)/(2*b) + (a - 2*b)*atanh(sqrt(b)*tanh(x)/sqrt(a + b*tanh(x)**2))/(2*b**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**3/sqrt(a + b*tanh(x)**2),
        variable=x,
        num_steps=5,
        integral=atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b))/sqrt(a + b) - sqrt(a + b*tanh(x)**2)/b,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**2/sqrt(a + b*tanh(x)**2),
        variable=x,
        num_steps=6,
        integral=atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2))/sqrt(a + b) - atanh(sqrt(b)*tanh(x)/sqrt(a + b*tanh(x)**2))/sqrt(b),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/sqrt(a + b*tanh(x)**2),
        variable=x,
        num_steps=4,
        integral=atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b))/sqrt(a + b),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(a + b*tanh(x)**2),
        variable=x,
        num_steps=3,
        integral=atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2))/sqrt(a + b),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/sqrt(a + b*tanh(x)**2),
        variable=x,
        num_steps=7,
        integral=atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b))/sqrt(a + b) - atanh(sqrt(a + b*tanh(x)**2)/sqrt(a))/sqrt(a),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**2/sqrt(a + b*tanh(x)**2),
        variable=x,
        num_steps=5,
        integral=atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2))/sqrt(a + b) - sqrt(a + b*tanh(x)**2)*coth(x)/a,
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**3/sqrt(a + b*tanh(x)**2),
        variable=x,
        num_steps=8,
        integral=atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b))/sqrt(a + b) - sqrt(a + b*tanh(x)**2)*coth(x)**2/(2*a) - (2*a - b)*atanh(sqrt(a + b*tanh(x)**2)/sqrt(a))/(2*a**(sympy.S(3)/2)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**5/(a + b*tanh(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=-a**2/(b**2*(a + b)*sqrt(a + b*tanh(x)**2)) + atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b))/(a + b)**(sympy.S(3)/2) - sqrt(a + b*tanh(x)**2)/b**2,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**4/(a + b*tanh(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=7,
        integral=a*tanh(x)/(b*(a + b)*sqrt(a + b*tanh(x)**2)) + atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2))/(a + b)**(sympy.S(3)/2) - atanh(sqrt(b)*tanh(x)/sqrt(a + b*tanh(x)**2))/b**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**3/(a + b*tanh(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=a/(b*(a + b)*sqrt(a + b*tanh(x)**2)) + atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b))/(a + b)**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**2/(a + b*tanh(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=4,
        integral=-tanh(x)/((a + b)*sqrt(a + b*tanh(x)**2)) + atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2))/(a + b)**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/(a + b*tanh(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=5,
        integral=-1/((a + b)*sqrt(a + b*tanh(x)**2)) + atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b))/(a + b)**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(x)**2)**(sympy.S(-3)/2),
        variable=x,
        num_steps=4,
        integral=atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2))/(a + b)**(sympy.S(3)/2) + b*tanh(x)/(a*(a + b)*sqrt(a + b*tanh(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/(a + b*tanh(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=8,
        integral=atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b))/(a + b)**(sympy.S(3)/2) + b/(a*(a + b)*sqrt(a + b*tanh(x)**2)) - atanh(sqrt(a + b*tanh(x)**2)/sqrt(a))/a**(sympy.S(3)/2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**2/(a + b*tanh(x)**2)**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2))/(a + b)**(sympy.S(3)/2) + b*coth(x)/(a*(a + b)*sqrt(a + b*tanh(x)**2)) - (a + 2*b)*sqrt(a + b*tanh(x)**2)*coth(x)/(a**2*(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**6/(a + b*tanh(x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=8,
        integral=a*tanh(x)**3/(3*b*(a + b)*(a + b*tanh(x)**2)**(sympy.S(3)/2)) + a*(a + 2*b)*tanh(x)/(b**2*(a + b)**2*sqrt(a + b*tanh(x)**2)) + atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2))/(a + b)**(sympy.S(5)/2) - atanh(sqrt(b)*tanh(x)/sqrt(a + b*tanh(x)**2))/b**(sympy.S(5)/2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**5/(a + b*tanh(x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=6,
        integral=-a**2/(3*b**2*(a + b)*(a + b*tanh(x)**2)**(sympy.S(3)/2)) + a*(a + 2*b)/(b**2*(a + b)**2*sqrt(a + b*tanh(x)**2)) + atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b))/(a + b)**(sympy.S(5)/2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**4/(a + b*tanh(x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=6,
        integral=a*tanh(x)/(3*b*(a + b)*(a + b*tanh(x)**2)**(sympy.S(3)/2)) + atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2))/(a + b)**(sympy.S(5)/2) - (a + 4*b)*tanh(x)/(3*b*(a + b)**2*sqrt(a + b*tanh(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**3/(a + b*tanh(x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=6,
        integral=a/(3*b*(a + b)*(a + b*tanh(x)**2)**(sympy.S(3)/2)) - 1/((a + b)**2*sqrt(a + b*tanh(x)**2)) + atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b))/(a + b)**(sympy.S(5)/2),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)**2/(a + b*tanh(x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=6,
        integral=-tanh(x)/((a + b*tanh(x)**2)**(sympy.S(3)/2)*(3*a + 3*b)) + atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2))/(a + b)**(sympy.S(5)/2) - (2*a - b)*tanh(x)/(3*a*(a + b)**2*sqrt(a + b*tanh(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/(a + b*tanh(x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=6,
        integral=-1/((a + b*tanh(x)**2)**(sympy.S(3)/2)*(3*a + 3*b)) - 1/((a + b)**2*sqrt(a + b*tanh(x)**2)) + atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b))/(a + b)**(sympy.S(5)/2),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(x)**2)**(sympy.S(-5)/2),
        variable=x,
        num_steps=6,
        integral=atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2))/(a + b)**(sympy.S(5)/2) + b*tanh(x)/(3*a*(a + b)*(a + b*tanh(x)**2)**(sympy.S(3)/2)) + b*(5*a + 2*b)*tanh(x)/(3*a**2*(a + b)**2*sqrt(a + b*tanh(x)**2)),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)/(a + b*tanh(x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=9,
        integral=atanh(sqrt(a + b*tanh(x)**2)/sqrt(a + b))/(a + b)**(sympy.S(5)/2) + b/(3*a*(a + b)*(a + b*tanh(x)**2)**(sympy.S(3)/2)) + b*(2*a + b)/(a**2*(a + b)**2*sqrt(a + b*tanh(x)**2)) - atanh(sqrt(a + b*tanh(x)**2)/sqrt(a))/a**(sympy.S(5)/2),
    ),
    RubiTestSuiteCase(
        integrand=coth(x)**2/(a + b*tanh(x)**2)**(sympy.S(5)/2),
        variable=x,
        num_steps=7,
        integral=atanh(sqrt(a + b)*tanh(x)/sqrt(a + b*tanh(x)**2))/(a + b)**(sympy.S(5)/2) + b*coth(x)/(3*a*(a + b)*(a + b*tanh(x)**2)**(sympy.S(3)/2)) + b*(7*a + 4*b)*coth(x)/(3*a**2*(a + b)**2*sqrt(a + b*tanh(x)**2)) - (a + 4*b)*sqrt(a + b*tanh(x)**2)*(3*a + 2*b)*coth(x)/(3*a**3*(a + b)**2),
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(tanh(x)**2 + 1),
        variable=x,
        num_steps=3,
        integral=sqrt(2)*atanh(sqrt(2)*tanh(x)/sqrt(tanh(x)**2 + 1))/2,
    ),
    RubiTestSuiteCase(
        integrand=1/sqrt(-tanh(x)**2 - 1),
        variable=x,
        num_steps=3,
        integral=sqrt(2)*atan(sqrt(2)*tanh(x)/sqrt(-tanh(x)**2 - 1))/2,
    ),
    RubiTestSuiteCase(
        integrand=1/(tanh(x)**3 + 1),
        variable=x,
        num_steps=6,
        integral=x/2 - 2*sqrt(3)*atan(sqrt(3)*(1 - 2*tanh(x))/3)/9 - 1/(6*tanh(x) + 6),
    ),
    RubiTestSuiteCase(
        integrand=(a + b*tanh(x)**4)**(sympy.S(3)/2)*tanh(x),
        variable=x,
        num_steps=9,
        integral=-sqrt(b)*(3*a + 2*b)*atanh(sqrt(b)*tanh(x)**2/sqrt(a + b*tanh(x)**4))/4 + (a + b)**(sympy.S(3)/2)*atanh((a + b*tanh(x)**2)/(sqrt(a + b)*sqrt(a + b*tanh(x)**4)))/2 - (a + b*tanh(x)**4)**(sympy.S(3)/2)/6 - sqrt(a + b*tanh(x)**4)*(a/2 + b*tanh(x)**2/4 + b/2),
    ),
    RubiTestSuiteCase(
        integrand=sqrt(a + b*tanh(x)**4)*tanh(x),
        variable=x,
        num_steps=8,
        integral=-sqrt(b)*atanh(sqrt(b)*tanh(x)**2/sqrt(a + b*tanh(x)**4))/2 + sqrt(a + b)*atanh((a + b*tanh(x)**2)/(sqrt(a + b)*sqrt(a + b*tanh(x)**4)))/2 - sqrt(a + b*tanh(x)**4)/2,
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/sqrt(a + b*tanh(x)**4),
        variable=x,
        num_steps=4,
        integral=atanh((a + b*tanh(x)**2)/(sqrt(a + b)*sqrt(a + b*tanh(x)**4)))/(2*sqrt(a + b)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/(a + b*tanh(x)**4)**(sympy.S(3)/2),
        variable=x,
        num_steps=6,
        integral=atanh((a + b*tanh(x)**2)/(sqrt(a + b)*sqrt(a + b*tanh(x)**4)))/(2*(a + b)**(sympy.S(3)/2)) - (a - b*tanh(x)**2)/(2*a*(a + b)*sqrt(a + b*tanh(x)**4)),
    ),
    RubiTestSuiteCase(
        integrand=tanh(x)/(a + b*tanh(x)**4)**(sympy.S(5)/2),
        variable=x,
        num_steps=7,
        integral=atanh((a + b*tanh(x)**2)/(sqrt(a + b)*sqrt(a + b*tanh(x)**4)))/(2*(a + b)**(sympy.S(5)/2)) - (a - b*tanh(x)**2)/(6*a*(a + b)*(a + b*tanh(x)**4)**(sympy.S(3)/2)) - (3*a**2 - b*(5*a + 2*b)*tanh(x)**2)/(6*a**2*(a + b)**2*sqrt(a + b*tanh(x)**4)),
    ),
]
